= Full Text Search Operations
:page-layout: article
:page-status: {release-status-cbl} -- {release-comments-cbl}
:page-edition: Under Development
:page-role:
:description: Couchbase mobile database full-text search concepts

include::shared-mobile::partial$_attributes-shared.adoc[]
include::ROOT:partial$_page-index.adoc[]
include::ROOT:partial$_glossary-links.adoc[]
include::ROOT:partial$_attributes-local.adoc[]
include::{lang-mod-objc}:partial$_attributes-module.adoc[]

// BEGIN::Local page attributes
:blank-field: ____
:lang-title: {lang-title-objc}
:module: {lang-mod-objc}
:packageNm: couchbase-lite-{module}
:source-language: {lang-name-objc}
:snippet: {snippets-content--objc}
:url-issues: {url-github-cbl}{module}/issues

// END::Local page attributes

[abstract]
{description}

== Overview

To run a full-text search (FTS) query, you must have created a full-text index on the expression being matched.
Unlike regular queries, the index is not optional.
The following example inserts documents and creates an FTS index on the `name` property.

[source]
----
include::{snippet}[tag=fts-index,indent=0]
----

Multiple properties to index can be specified in the `Index.fullTextIndex(withItems: [FullTextIndexItem])` method.

With the index created, an FTS query on the property that is being indexed can be constructed and ran.
The full-text search criteria is defined as a `FullTextExpression`.
The left-hand side is the full-text index to use and the right-hand side is the pattern to match.

[source]
----
include::{snippet}[tag=fts-query,indent=0]
----

In the example above, the pattern to match is a word, the full-text search query matches all documents that contain the word "buy" in the value of the `doc.name` property.

Search is supported for all languages that use whitespace to separate words.

Stemming, which is the process of fuzzy matching parts of speech, like "fast" and "faster", is supported in the following languages: danish, dutch, english, finnish, french, german, hungarian, italian, norwegian, portuguese, romanian, russian, spanish, swedish and turkish.

The pattern to match can also be in the following forms:

== Prefix Queries
The query expression used to search for a term prefix is the prefix itself with a "*" character appended to it.
For example:
+
....
"'lin*'"
-- Query for all documents containing a term with the prefix "lin". This will match
-- all documents that contain "linux", but also those that contain terms "linear",
--"linker", "linguistic" and so on.
....

== Overriding the property name that is being indexed

Normally, a token or token prefix query is matched against the document property specified as the left-hand side of the `match` operator.
This may be overridden by specifying a property name followed by a ":" character before a basic term query.
There may be space between the ":" and the term to query for, but not between the property name and the ":" character.
For example:
+
....
'title:linux problems'
-- Query the database for documents for which the term "linux" appears in
-- the document title, and the term "problems" appears in either the title
-- or body of the document.
....

== Phrase Queries
A phrase query is a query that retrieves all documents that contain a nominated set of terms or term prefixes in a specified order with no intervening tokens.
Phrase queries are specified by enclosing a space separated sequence of terms or term prefixes in double quotes (").
For example:
+
....
"'"linux applications"'"
-- Query for all documents that contain the phrase "linux applications".
....

== NEAR Queries
A NEAR query is a query that returns documents that contain a two or more nominated terms or phrases within a specified proximity of each other (by default with 10 or less intervening terms).
A NEAR query is specified by putting the keyword "NEAR" between two phrase, token or token prefix queries.
To specify a proximity other than the default, an operator of the form "NEAR/" may be used, where is the maximum number of intervening terms allowed.
For example:
+
....
"'database NEAR/2 "replication"'"
-- Search for a document that contains the phrase "replication" and the term
-- "database" with not more than 2 terms separating the two.
....

== AND, OR & NOT Query Operators

The enhanced query syntax supports the AND, OR and NOT binary set operators.
Each of the two operands to an operator may be a basic FTS query, or the result of another AND, OR or NOT set operation.
Operators must be entered using capital letters.
Otherwise, they are interpreted as basic term queries instead of set operators.
For example:
+
....
'couchbase AND database'
-- Return the set of documents that contain the term "couchbase", and the
-- term "database". This query will return the document with docid 3 only.
....
+
When using the enhanced query syntax, parenthesis may be used to specify the precedence of the various operators.
For example:
+
....
'("couchbase database" OR "sqlite library") AND linux'
-- Query for the set of documents that contains the term "linux", and at least
-- one of the phrases "couchbase database" and "sqlite library".
....

== Ordering Results

It's very common to sort full-text results in descending order of relevance.
This can be a very difficult heuristic to define, but Couchbase Lite comes with a ranking function you can use.
In the `OrderBy` array, use a string of the form `Rank(X)`, where `X` is the property or expression being searched, to represent the ranking of the result.
