plugins {
    id 'java'
    id 'application'
}

ext {
    CBL_VERSION = project.hasProperty('cblVersion') ? project.cblVersion : { throw new GradleException('cblVersion property is required. Use -PcblVersion=x.x.x-x') }()
    EXT_VERSION = project.hasProperty('extVersion') ? project.extVersion : { throw new GradleException('extVersion property is required. Use -PextVersion=x.x.x-x') }()
}

def USE_LOCAL_MAVEN = project.hasProperty("useLocalMaven")

group 'com.couchbase'
version '3.1.0'

java {
    targetCompatibility JavaVersion.VERSION_11
    sourceCompatibility JavaVersion.VERSION_11

    application {mainClassName = "com.couchbase.gettingstarted.Main" }
}

repositories {
    if (USE_LOCAL_MAVEN) {
        mavenLocal()
    }

    maven {
        url "https://proget.sc.couchbase.com/maven2/internalmaven/"
        content { includeGroupByRegex "com\\.couchbase\\.lite.*" }
    }

    maven {
        url "https://mobile.maven.couchbase.com/maven2/dev/"
        content { includeGroupByRegex "com\\.couchbase\\.lite.*" }
    }

    google()
    mavenCentral()
}
 
dependencies {
    compileOnly 'androidx.annotation:annotation:1.5.0'

    implementation "com.couchbase.lite:couchbase-lite-java-ee:${CBL_VERSION}"
    // If using Vector Search
    implementation "com.couchbase.lite:couchbase-lite-java-vector-search:${EXT_VERSION}"

    testImplementation 'junit:junit:4.13.2'
}

task appRun(type: JavaExec) {
    group = "Execution"
    description = "Run the main class with JavaExecTask"
    classpath = sourceSets.main.runtimeClasspath
    main = "com.couchbase.gettingstarted.Main"
}
