
= Intra-device Sync
:page-aliases: learn/java-dbreplica.adoc
:page-role:
:description: Couchbase Lite Database Sync - Synchronize changes between databases on the same device


// :param-name: java
// :param-title: Java
// :param-module: java


[abstract]
--
Description -- _{description}_ +
Related Content -- xref:java:replication.adoc[Remote Sync Gateway] | xref:java:landing-p2psync.adoc[Peer-to-Peer Sync]
--

[#overview]
== Overview


Couchbase Lite supports replication between two local databases at the database, scope, or collection level.
This allows a Couchbase Lite replicator to store data on secondary storage.
It is useful in scenarios when a user's device is damaged and its data is moved to a different device.

.Replication between Local Databases


====


[source, Java]
----
include::java:example$codesnippet_collection.java[tags="database-replica", indent=0]
----
====


[#related-content]
== Related Content
++++
<div class="card-row three-column-row">
++++

[.column]
====== {empty}
.How to . . .
* xref:java:gs-prereqs.adoc[Prerequisites]
* xref:java:gs-install.adoc[Install]
* xref:java:gs-build.adoc[Build and Run]


.

[.column]
====== {empty}
.Learn more . . .
* xref:java:database.adoc[Databases]
* xref:java:document.adoc[Documents]
* xref:java:blob.adoc[Blobs]
* xref:java:replication.adoc[Remote Sync Gateway]
* xref:java:conflict.adoc[Handling Data Conflicts]

.


[.column]
====== {empty}
.Dive Deeper . . .
https://forums.couchbase.com/c/mobile/14[Mobile Forum] |
https://blog.couchbase.com/[Blog] |
https://docs.couchbase.com/tutorials/[Tutorials]

.


++++
</div>
++++


