
= Couchbase Lite on Java -- Prerequisites
:page-aliases: start/java-gs-prereqs.adoc
:page-role:
:description: Couchbase Lite on Java -- a framework for developing offline-first Java applications for mobile and edge
:keywords: mobile edge nosql api Java JVM web-app device-app


:source-language: Java


:tabs:


[abstract]
--
Description -- _{description}_ +
_Abstract -- This content identities the pre-requisites and preparatory steps to be considered before installing Couchbase Lite for java_ +
--
// include::ROOT:partial$block-related-get-started.adoc[]


.Vector Search Prerequisites
[IMPORTANT]
--
To use Vector Search, you must have Couchbase Lite installed and add the Vector Search extension to your Couchbase Lite application.
Vector Search is available only for 64-bit architectures and
Intel processors that support the Advanced Vector Extensions 2 (AVX2) instruction set.
To verify whether your device supports the AVX2 instructions set, https://www.intel.com/content/www/us/en/support/articles/000090473/processors/intel-core-processors.html[follow these instructions.]
--

[#introduction]
== Introduction

Couchbase{nbsp}Lite enables development and deployment of Couchbase{nbsp}Lite applications to a JVM environment.
You can deploy to a desktop or web server (for example, Tomcat), including embedded Tomcat deployments.

NOTE: We use _Intellij IDEA_, _gradle_, _Maven_ and _Tomcat_ as tools to build and run the examples presented in this content.
You are free to use the tools of your choice.


[#bmkSetupSyncAndServer, Setting up Sync Gateway]

[#bmkSetupSyncAndServer]
== Install Server Software

If you want to use Couchbase{nbsp}Lite with _Couchbase{nbsp}Server_ and-or _Sync{nbsp}Gateway you will need to have installed operational instances of these before completing the installation and test build steps.

So, If you have not already done so, see xref:sync-gateway:start-here:get-started-prepare.adoc[Prepare Sync Gateway]

* Within _Couchbase{nbsp}Server_, create a bucket named getting-started.cblite2
* Create a RBAC user for _Sync{nbsp}Gateway with username = `sync-gateway` and password = `password`


[#macos-and-windows]
== MacOS and Windows

You may now proceed directly to xref:java:gs-install.adoc[].

[#additional-steps-for-linux]
== Additional Steps For Linux

Before proceeding to xref:java:gs-install.adoc[], you will need to make the supplied support libraries available to your running application.

[#steps]
=== Steps

. Download the _zip_ file from here -- https://packages.couchbase.com/releases/couchbase-lite-java/{major}.{minor}.{maintenance-java}{empty}/couchbase-lite-java-linux-supportlibs-{major}.{minor}.{maintenance-java}{empty}.zip
.
. Unpack the downloaded file to a location accessible to your build and runtime environments, for example `your_dir/couchbase-lite-java-{major}.{minor}.{maintenance-java}{empty}`.

[#bmkLinuxSharedLibs]
. Set up the Native Libraries for Linux.
You will need to add the path of the directory containing the unpacked support libraries to the value of the Java system property `java.library.path`.
+
The simplest way to set this is through the shell variable `LD_LIBRARY_PATH`:
+
[source,bash,subs="attributes+"]
----
export LD_LIBRARY_PATH=<your_dir>/couchbase-lite-java-{major}.{minor}.{maintenance-java}/:$LD_LIBRARY_PATH
----
+
Where `<your_dir>` is the path where you unpacked the support libraries in step 2.
+
NOTE: This environment variable must be set before running your Java application that uses Couchbase Lite.

[tabs]
====

Web Service/Tomcat::
+
--
Add the variables to your `$CATALINA_BASE/bin/setenv.sh`.
(If the setenv.sh file doesn't exist, you will need to create a new file.)

[source, bashrc, subs="attributes"]
----
LD_LIBRARY_PATH="$LD_LIBRARY_PATH:<lib-directory>"
----
--


Desktop::
+
--
Export the variable in your .bashrc file:

[source, bashrc, subs="attributes"]
----
export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:<lib-directory>"
----
--
====


For more information, see the Linux Platform Support section for the minimum version requirements of those libraries.


[#related-content]
== Related Content
++++
<div class="card-row three-column-row">
++++

[.column]
====== {empty}
.How to . . .
* xref:java:gs-prereqs.adoc[Prerequisites]
* xref:java:gs-install.adoc[Install]
* xref:java:gs-build.adoc[Build and Run]


.

[.column]
====== {empty}
.Learn more . . .
* xref:java:database.adoc[Databases]
* xref:java:document.adoc[Documents]
* xref:java:blob.adoc[Blobs]
* xref:java:replication.adoc[Remote Sync Gateway]
* xref:java:conflict.adoc[Handling Data Conflicts]

.


[.column]
====== {empty}
.Dive Deeper . . .
https://forums.couchbase.com/c/mobile/14[Mobile Forum] |
https://blog.couchbase.com/[Blog] |
https://docs.couchbase.com/tutorials/[Tutorials]

.


++++
</div>
++++


