:docname: p2psync-websocket-using-active
:page-module: java
:page-relative-src-path: p2psync-websocket-using-active.adoc
:page-origin-url: https://github.com/couchbase/docs-couchbase-lite.git
:page-origin-start-path:
:page-origin-refname: antora-assembler-simplification
:page-origin-reftype: branch
:page-origin-refhash: (worktree)
[#java:p2psync-websocket-using-active:::]
==== Active Peer
:page-aliases: advance/java-p2psync-websocket-using-active.adoc
ifdef::show_edition[:page-edition: {release}] {enterprise}
:page-role:
:description: Couchbase Lite's Peer-to-Peer Synchronization enables edge devices to synchronize securely without consuming centralized cloud-server resources

// Define our environment



// BEGIN -- _define_module_attributes.adoc -- Java
//
// Definition:
//    Objective: This adoc defines values for attributes specific to pages within this module (Java)
//    Invoked-by: ROOT:_partials/_std_cbl_hdr.adoc (from within module/_partials/_set_page_context_for_java.adoc)
//    Parameters: none
// End Definition:


// BEGIN -- module page attributes
// Begin workaround for 2.8.1 mis-release, to avoid unnecessary install of 2.8.0
// SET full maintenance version number

// VECTOR SEARCH attributes

// End workaround
// :snippet-p2psync-ws: {snippets-p2psync-ws--java}
// END -- module page attributes


// BEGIN -- Define API References for this module
//  These attributes s
//:url-api-references-structs: https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-java}{empty}/couchbase-lite-java/Structs
// :url-api-references-classes: https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-java}{empty}/couchbase-lite-java/Classes




// Supporting Data Type Classes



// DatabaseConfiguration


//Database.SAVE



//Database.DELETE()




// deprecated 2.8
//
// :url-api-method-database-compact: https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-java}{empty}/couchbase-lite-java/com/couchbase/lite/Database.html#compact--[Database.compact()]
// was copy-java.io.File-java.lang.String-com.couchbase.lite.DatabaseConfiguration-[Database.copy()]





// links for documents pages


// :url-api-class-dictionary: https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-java}{empty}/couchbase-lite-java/com/couchbase/lite/Dictionary.html[property accessors]

// QUERY RELATED CLASSES and METHODS

// Result Classes and Methods




// Query class and methods

// Expression class and methods


// ArrayFunction class and methods
// https://docs.couchbase.com/mobile/2.8.0/couchbase-lite-java/com/couchbase/lite/ArrayFunction.html


// Function class and methods
//

// Where class and methods
//

// orderby class and methods
//

// GroupBy class and methods
//

// Endpoints








// https://ibsoln.github.io/betasites/api/mobile/2.8.0/couchbase-lite-java/com/couchbase/lite/URLEndpointListenerConfiguration.html#setPort-int-







// diag: Env+Module java




// Authenticators




// Replicator API










//:url-api-property-replicator-status-activity: https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-java}{empty}/couchbase-lite-java/com/couchbase/lite/Replicator.html#s:18CouchbaseLiteandroid10ReplicatorC13ActivityLevelO


// ReplicatorStatus



// ReplicatorConfiguration API












// replaced
// replaced
// replaces ^^



// Begin Replicator Retry Config
// End Replicator Retry Config










// Meta API


// END -- Define API References for this module

// diag: Env+Module java



// BEGIN Logs and logging references
// :url-api-class-logging: https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-java}{empty}/couchbase-lite-java/Logging.html[Logging classes]






// END  Logs and logging references







// END -- _define_module_attributes.adoc -- Java

// BEGIN::module page attributes
// :snippet-p2psync-ws: {snippets-p2psync-ws--java}

// END::Local page attributes

// Define page abstract
// done in commons

// Present common content including abstract and related content footer blocks
//= Using Peer-to-Peer Synchronization (WebSockets)

// DO NOT EDIT


//  | {xref-cbl-pg-p2p-manage-tls-id}
[abstract]
--
Description -- _{description}_ +
_Abstract -- How to set up a Replicator to connect with a Listener and replicate changes using peer-to-peer sync_ +
Related Content -- https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-java}{empty}/couchbase-lite-java/[API Reference]  |  xref:java:p2psync-websocket-using-passive.adoc[Passive Peer]  |  xref:java:p2psync-websocket-using-active.adoc[Active Peer]
--

// Set is-p2p on for inclusions that may use it
// DO NOT EDIT






.Code Snippets
[NOTE]
All code examples are indicative only.
They demonstrate the basic concepts and approaches to using a feature.
Use them as inspiration and adapt these examples to best practice when developing applications for your platform.


[discrete#java:p2psync-websocket-using-active:::introduction]
===== Introduction
This content provides sample code and configuration examples covering the implementation of xref:refer-glossary.adoc#peer-to-peer-sync[Peer-to-Peer Sync] over WebSockets.
Specifically it covers the implementation of an xref:refer-glossary.adoc#active-peer[Active Peer].

This _active peer_ (also referred to as a client and-or a replicator) will initiate the connection with a xref:refer-glossary.adoc#passive-peer[Passive Peer] (also referred to as a server and-or listener) and participate in the replication of database changes to bring both databases into sync.

Subsequent sections provide additional details and examples for the main configuration options.

.Secure Storage
[NOTE]
The use of TLS, its associated keys and certificates requires using secure storage to minimize the chances of a security breach.
The implementation of this storage differs from platform to platform -- see xref:java:p2psync-websocket.adoc#using-secure-storage[Using secure storage].


[discrete#java:p2psync-websocket-using-active:::configuration-summary]
===== Configuration Summary
You should configure and initialize a replicator for each Couchbase Lite database instance you want to sync.
<<java:p2psync-websocket-using-active:::simple-replication-to-listener>> shows the initialization and configuration process.


[#simple-replication-to-listener]
.Replication configuration and initialization
// BEGIN inclusion -- block -- block_tabbed_code_example.adoc
//
//  Allows for abstraction of the showing of snippet examples
//  which makes displaying tabbed snippets for platforms with
//  more than one native language to show -- Android (Kotlin and Java)
//
// Surrounds code in Example block
//
//  PARAMETERS:
//    param-tags comma-separated list of tags to include/exclude
//    param-leader text for opening para of an example block
//
//  USE:
//    :param_tags: query-access-json
//    include::partial$block_show_snippet.adoc[]
//    :param_tags!:
//

[#java:p2psync-websocket-using-active:::simple-replication-to-listener]
====


// Show Main Snippet
[source, Java]
----
include ::java:example$codesnippet_collection.java[tags="p2p-act-rep-func;!autopurge-override", indent=0]
    // initialize the replicator configuration
    new ReplicatorConfiguration(new URLEndpoint(new URI("wss://listener.com:8954"))) // <.>
        .addCollections(collections, null)

        // Set replicator type
        .setType(ReplicatorType.PUSH_AND_PULL)

        // Configure Sync Mode
        .setContinuous(false) // default value



        // Configure Server Authentication --
        // only accept self-signed certs
        .setAcceptOnlySelfSignedServerCertificate(true) // <.>

        // Configure the credentials the
        // client will provide if prompted
        .setAuthenticator(new BasicAuthenticator("Our Username", "Our Password".toCharArray())) // <.>

);

// Optionally add a change listener <.>
ListenerToken token = repl.addChangeListener(change -> {
    CouchbaseLiteException err = change.getStatus().getError();
    if (err != null) { Logger.log("Error code :: " + err.getCode(), err); }
});

// Start replicator
repl.start(false); // <.>


thisReplicator = repl;
thisToken = token;

----




// close example block

====

// Tidy-up atttibutes created
// END -- block_show_snippet.doc
<.> Configure how the client will authenticate the server.
Here we say connect only to servers presenting a self-signed certificate.
By default, clients accept only servers presenting certificates that can be verified using the OS bundled Root CA Certificates -- see: <<java:p2psync-websocket-using-active:::authenticate-listener>>.

<.> Configure the credentials the client will present to the server.
Here we say to provide _Basic Authentication_ credentials. Other options are available -- see: <<java:p2psync-websocket-using-active:::configuring-client-authentication>>.

<.> Configure how the replication should perform <<java:p2psync-websocket-using-active:::conflict-resolution>>.

<.> Initialize the replicator using your configuration object.

<.> Register an observer, which will notify you of changes to the replication status.

<.> Start the replicator.

[discrete#java:p2psync-websocket-using-active:::api-references]
===== API References

You can find https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-java}{empty}/couchbase-lite-java/[Java API References] here.

[discrete#java:p2psync-websocket-using-active:::device-discovery]
===== Device Discovery
*This phase is optional:* If the listener is initialized on a well known URL endpoint (for example, a static IP Address or well known DNS address) then you can configure Active Peers to connect to those.

Prior to connecting with a listener you may execute a Peer discovery phase to dynamically discover Peers.


// image::ROOT:replication.svg[,800]

[discrete#java:p2psync-websocket-using-active:::configure-replicator]
===== Configure Replicator
In this section::
<<java:p2psync-websocket-using-active:::lbl-cfg-tgt>>
|  <<java:p2psync-websocket-using-active:::lbl-cfg-sync>>
|  <<java:p2psync-websocket-using-active:::lbl-cfg-retry>>
|  <<java:p2psync-websocket-using-active:::authenticate-listener>>
|  <<java:p2psync-websocket-using-active:::lbl-authclnt>>
// | <<lbl-auto-purge-on-revoke>>


[discrete#java:p2psync-websocket-using-active:::lbl-cfg-tgt]
====== Configure Target

// BEGIN -- inclusion -- common-sgw-replication-cfg-tgt.adoc
//  Used-by:
//    common-p2psync-websocket-using-active.adoc
//    common-sgw-replication.adoc
//

Use the
Initialize and define the replication configuration with local and remote database locations using the https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-java}{empty}/couchbase-lite-java/com/couchbase/lite/ReplicatorConfiguration.html[ReplicatorConfiguration] object.

The constructor provides:

* the name of the local database to be sync'd
* the server's URL (including the port number and the name of the remote database to sync with)
+
--
It is expected that the app will identify the IP address and URL and append the remote database name to the URL endpoint, producing for example: `wss://10.0.2.2:4984/travel-sample`

The URL scheme for web socket URLs uses `ws:` (non-TLS) or `wss:` (SSL/TLS) prefixes.
--

// Example 2
.Add Target to Configuration
// BEGIN inclusion -- block -- block_tabbed_code_example.adoc
//
//  Allows for abstraction of the showing of snippet examples
//  which makes displaying tabbed snippets for platforms with
//  more than one native language to show -- Android (Kotlin and Java)
//
// Surrounds code in Example block
//
//  PARAMETERS:
//    param-tags comma-separated list of tags to include/exclude
//    param-leader text for opening para of an example block
//
//  USE:
//    :param_tags: query-access-json
//    include::partial$block_show_snippet.adoc[]
//    :param_tags!:
//

====


// Show Main Snippet
[source, Java]
----
include ::java:example$codesnippet_collection.java[tags="sgw-act-rep-initialize", indent=0]
// initialize the replicator configuration
ReplicatorConfiguration thisConfig = new ReplicatorConfiguration(
    new URLEndpoint(new URI("wss://10.0.2.2:8954/travel-sample"))) // <.>
    .addCollections(collections, null);
----




// close example block

====

// Tidy-up atttibutes created
// END -- block_show_snippet.doc
<.> Note use of the scheme prefix (`wss://`
to ensure TLS encryption -- strongly recommended in production -- or `ws://`)
// END -- inclusion -- common-sgw-replication-cfg-tgt.adoc


[discrete#java:p2psync-websocket-using-active:::lbl-cfg-sync]
====== Sync Mode


Here we define the direction and type of replication we want to initiate.

We use `https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-java}{empty}/couchbase-lite-java/com/couchbase/lite/ReplicatorConfiguration.html[ReplicatorConfiguration]` class's https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-java}{empty}/couchbase-lite-java/com/couchbase/lite/ReplicatorConfiguration.html#setReplicatorType-com.couchbase.lite.AbstractReplicatorConfiguration.ReplicatorType-[replicatorType] and
`https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-java}{empty}/couchbase-lite-java/com/couchbase/lite/ReplicatorConfiguration.html#setContinuous-boolean-[continuous]` parameters, to tell the replicator:

* The type (or direction) of the replication:
`*pushAndPull*`; `pull`; `push`

* The replication mode, that is either of:

** Continuous -- remaining active indefinitely to replicate changed documents (`continuous=true`).

** Ad-hoc -- a one-shot replication of changed documents (`continuous=false`).

// Example 3
[#ex-repl-sync]
.Configure replicator type and mode
// BEGIN inclusion -- block -- block_tabbed_code_example.adoc
//
//  Allows for abstraction of the showing of snippet examples
//  which makes displaying tabbed snippets for platforms with
//  more than one native language to show -- Android (Kotlin and Java)
//
// Surrounds code in Example block
//
//  PARAMETERS:
//    param-tags comma-separated list of tags to include/exclude
//    param-leader text for opening para of an example block
//
//  USE:
//    :param_tags: query-access-json
//    include::partial$block_show_snippet.adoc[]
//    :param_tags!:
//

[#java:p2psync-websocket-using-active:::ex-repl-sync]
====


// Show Main Snippet
[source, Java]
----
include ::java:example$codesnippet_collection.java[tags="p2p-act-rep-config-type;p2p-act-rep-config-cont", indent=0]
// Set replicator type
.setType(ReplicatorType.PUSH_AND_PULL)

// Configure Sync Mode
.setContinuous(false) // default value

----




// close example block

====

// Tidy-up atttibutes created
// END -- block_show_snippet.doc

[TIP]
--
Unless there is a solid use-case not to, always initiate a single `PUSH_AND_PULL` replication rather than identical separate `PUSH` and `PULL` replications.

This prevents the replications generating the same checkpoint `docID` resulting in multiple conflicts.
--


[discrete#java:p2psync-websocket-using-active:::lbl-cfg-retry]
====== Retry Configuration

// BEGIN -- inclusion -- common-sgw-replication-cfg-retryadoc
//  Begin -- inclusion definition
//    Use - output text pertaining to replication retry logic and config
//    Params:
//      :is-p2p: - sets the server as a listener and not a Sync Gateway
//    Location -- modules/ROOT/pages/_partials/commons/
//
//    Inclusions and Attributes:
//      Uses attributes from the _define_module_attributes.adoc to links to
//      REST API properties (eg {url-api-prop-<blah>})
//      You can find _define_module_attributes.adoc in this location for each platform:
//        modules/<platform>/pages/_partials/
//
//  End -- inclusion definition


Couchbase Lite for Java's replication retry logic assures a resilient connection.

The replicator minimizes the chance and impact of dropped connections by maintaining a heartbeat; essentially pinging the listener at a configurable interval to ensure the connection remains alive.

In the event it detects a transient error, the replicator will attempt to reconnect, stopping only when the connection is re-established, or the number of retries exceeds the retry limit (9 times for a single-shot replication and unlimited for a continuous replication).

On each retry the interval between attempts is increased exponentially (exponential backoff) up to the maximum wait time limit (5 minutes).

The REST API provides configurable control over this replication retry logic using a set of configiurable properties -- see: <<java:p2psync-websocket-using-active:::tbl-repl-retry>>.

.Replication Retry Configuration Properties
[#java:p2psync-websocket-using-active:::tbl-repl-retry,cols="2,3,5"]
|===

h|Property
h|Use cases
h|Description

|https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-java}{empty}/couchbase-lite-java/com/couchbase/lite/AbstractReplicatorConfiguration.html#setHeartbeat-long-[setHeartbeat()]
a|* Reduce to detect connection errors sooner
* Align to load-balancer or proxy `keep-alive` interval -- see Sync Gateway's topic xref:sync-gateway::load-balancer.adoc#websocket-connection[Load Balancer - Keep Alive]
a|The interval (in seconds) between the heartbeat pulses.

Default: The replicator pings the listener every 300 seconds.

|https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-java}{empty}/couchbase-lite-java/com/couchbase/lite/AbstractReplicatorConfiguration.html#setMaxAttempts-int-[setMaxAttempts()]
|Change this to limit or extend the number of retry attempts.
a| The maximum number of retry attempts

* Set to zero (0) to use default values
* Set to zero (1) to prevent any retry attempt
* The retry attempt count is reset when the replicator is able to connect and replicate
* Default values are:
** Single-shot replication = 9;
** Continuous replication = maximum integer value
* Negative values generate a Couchbase exception `InvalidArgumentException`

|https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-java}{empty}/couchbase-lite-java/com/couchbase/lite/AbstractReplicatorConfiguration.html#setMaxAttemptWaitTime-long-[setMaxAttemptWaitTime()]
|Change this to adjust the interval between retries.
a|The maximum interval between retry attempts

While you can configure the *maximum permitted* wait time,  the replicator's exponential backoff algorithm calculates each individual interval which is not configurable.

* Default value: 300 seconds (5 minutes)
* Zero sets the maximum interval between retries to the default of 300 seconds
* 300 sets the maximum interval between retries to the default of 300 seconds
* A negative value generates a Couchbase exception, `InvalidArgumentException`

|===

When necessary you can adjust any or all of those configurable values -- see: <<java:p2psync-websocket-using-active:::ex-repl-retry>> for how to do this.

.Configuring Replication Retries
[#ex-repl-retry]
// BEGIN inclusion -- block -- block_tabbed_code_example.adoc
//
//  Allows for abstraction of the showing of snippet examples
//  which makes displaying tabbed snippets for platforms with
//  more than one native language to show -- Android (Kotlin and Java)
//
// Surrounds code in Example block
//
//  PARAMETERS:
//    param-tags comma-separated list of tags to include/exclude
//    param-leader text for opening para of an example block
//
//  USE:
//    :param_tags: query-access-json
//    include::partial$block_show_snippet.adoc[]
//    :param_tags!:
//

[#java:p2psync-websocket-using-active:::ex-repl-retry]
====



// Show Main Snippet
[source, Java]
----
include ::java:example$codesnippet_collection.java[tags="replication-retry-config", indent=0]
Replicator repl = new Replicator(
    new ReplicatorConfiguration(new URLEndpoint(new URI("ws://localhost:4984/mydatabase")))
        .addCollections(collections, null)
        //  other config as required . . .
        .setHeartbeat(150) // <.>
        .setMaxAttempts(20) // <.>
        .setMaxAttemptWaitTime(600)); // <.>

repl.start();
thisReplicator = repl;
----




// close example block

====

// Tidy-up atttibutes created
// END -- block_show_snippet.doc
<.> Here we use https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-java}{empty}/couchbase-lite-java/com/couchbase/lite/AbstractReplicatorConfiguration.html#setHeartbeat-long-[setHeartbeat()] to set the required interval (in seconds) between the heartbeat pulses
<.> Here we use https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-java}{empty}/couchbase-lite-java/com/couchbase/lite/AbstractReplicatorConfiguration.html#setMaxAttempts-int-[setMaxAttempts()] to set the required number of retry attempts
<.> Here we use https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-java}{empty}/couchbase-lite-java/com/couchbase/lite/AbstractReplicatorConfiguration.html#setMaxAttemptWaitTime-long-[setMaxAttemptWaitTime()] to set the required interval between retry attempts.

// END -- inclusion -- common-sgw-replication-cfg-retryadoc


[discrete#java:p2psync-websocket-using-active:::authenticate-listener]
====== Authenticating the Listener

Define the credentials the your app (the client) is expecting to receive from the server (listener) in order to ensure that the server is one it is prepared to interact with.

// BEGIN -- inclusion -- common-set-server-authentication.adoc
//  Used from:
//    common-p2psync-websocket-using-active.adoc
//    java-android-replication.adoc
//  Location: ROOT:partial$commons/common-
//

Note that the client cannot authenticate the server if TLS is turned off.
When TLS is enabled (Sync Gateway's default) the client _must_ authenticate the server.
If the server cannot provide acceptable credentials then the connection will fail.

Use `https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-java}{empty}/couchbase-lite-java/com/couchbase/lite/ReplicatorConfiguration.html[ReplicatorConfiguration]` properties https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-java}{empty}/couchbase-lite-java/com/couchbase/lite/ReplicatorConfiguration.html#setAcceptOnlySelfSignedServerCertificate-boolean-[setAcceptOnlySelfSignedServerCertificate] and https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-java}{empty}/couchbase-lite-java/com/couchbase/lite/ReplicatorConfiguration.html#setPinnedServerCertificate-byte:A-[setPinnedServerCertificate()], to tell the replicator how to verify server-supplied TLS server certificates.

* If there is a pinned certificate, nothing else matters, the server cert must *exactly* match the pinned certificate.
* If there are no pinned certs and https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-java}{empty}/couchbase-lite-java/com/couchbase/lite/ReplicatorConfiguration.html#setAcceptOnlySelfSignedServerCertificate-boolean-[setAcceptOnlySelfSignedServerCertificate] is `true` then any self-signed certificate is accepted.  Certificates that are not self signed are rejected, no matter who signed them.
* If there are no pinned certificates and https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-java}{empty}/couchbase-lite-java/com/couchbase/lite/ReplicatorConfiguration.html#setAcceptOnlySelfSignedServerCertificate-boolean-[setAcceptOnlySelfSignedServerCertificate] is `false` (default), the client validates the server’s certificates against the system CA certificates.  The server must supply a chain of certificates whose root is signed by one of the certificates in the system CA bundle.

// :is-android:
// Example 4
.Set Server TLS security
====
[tabs]
======

CA Cert::
+
--
Set the client to expect and accept only CA attested certificates.

[source, Java]
----
// Configure Server Security
// -- only accept CA attested certs
.setAcceptOnlySelfSignedServerCertificate(false); // <.>

----
<.> This is the default.
Only certificate chains with roots signed by a trusted CA are allowed.
Self signed certificates are not allowed.
--


Self Signed Cert::
+
--
Set the client to expect and accept only self-signed certificates

[source, Java]
----
// Configure Server Authentication --
// only accept self-signed certs
.setAcceptOnlySelfSignedServerCertificate(true) // <.>

----
<.> Set this to `true` to accept any self signed cert.
Any certificates that are not self-signed are rejected.
--


Pinned Certificate::
+
--
Set the client to expect and accept only a pinned certificate.

[source, Java]
----
// Use the pinned certificate from the byte array (cert)

TLSIdentity identity = TLSIdentity.getIdentity(keyStore, "OurCorp", "sekrit".toCharArray());
if (identity == null) { throw new IllegalStateException("Cannot find corporate id"); }
config.setPinnedServerX509Certificate((X509Certificate) identity.getCerts().get(0)); // <.>

----

--

======


====
//
// END -- inclusion -- common-set-server-authentication.adoc


[discrete#java:p2psync-websocket-using-active:::lbl-authclnt]
====== Client Authentication

Here we define the credentials that the client can present to the server if prompted to do so in order that the server can authenticate it.

We use https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-java}{empty}/couchbase-lite-java/com/couchbase/lite/ReplicatorConfiguration.html[ReplicatorConfiguration]'s https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-java}{empty}/couchbase-lite-java/com/couchbase/lite/ReplicatorConfiguration.html#setAuthenticator-com.couchbase.lite.Authenticator-[setAuthenticator] method to define the authentication method to the replicator.


[discrete#java:p2psync-websocket-using-active:::basic-authentication]
====== Basic Authentication
Use the `https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-java}{empty}/couchbase-lite-java/com/couchbase/lite/BasicAuthenticator.html[BasicAuthenticator]` to supply basic authentication credentials (username and word).

// Example 5
[[java:p2psync-websocket-using-active:::basic-authentication]]
.Basic Authentication
// BEGIN inclusion -- block -- block_tabbed_code_example.adoc
//
//  Allows for abstraction of the showing of snippet examples
//  which makes displaying tabbed snippets for platforms with
//  more than one native language to show -- Android (Kotlin and Java)
//
// Surrounds code in Example block
//
//  PARAMETERS:
//    param-tags comma-separated list of tags to include/exclude
//    param-leader text for opening para of an example block
//
//  USE:
//    :param_tags: query-access-json
//    include::partial$block_show_snippet.adoc[]
//    :param_tags!:
//

[#java:p2psync-websocket-using-active:::basic-authentication]
====

This example shows basic authentication using user name and password:

// Show Main Snippet
[source, Java]
----
include ::java:example$codesnippet_collection.java[tags="p2p-act-rep-auth", indent=0]
// Configure the credentials the
// client will provide if prompted
.setAuthenticator(new BasicAuthenticator("Our Username", "Our Password".toCharArray())) // <.>

----




// close example block

====

// Tidy-up atttibutes created
// END -- block_show_snippet.doc


[discrete#java:p2psync-websocket-using-active:::certificate-authentication]
====== Certificate Authentication
Use the `https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-java}{empty}/couchbase-lite-java/com/couchbase/lite/ClientCertificateAuthenticator.html[ClientCertificateAuthenticator]` to configure the client TLS certificates to be presented to the server, on connection.
This applies only to the https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-java}{empty}/couchbase-lite-java/com/couchbase/lite/URLEndpointListener.html[URLEndpointListener].

NOTE: The *server* (listener) must have `disableTLS` set `false` and have a https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-java}{empty}/couchbase-lite-java/com/couchbase/lite/ClientCertificateAuthenticator.html[ClientCertificateAuthenticator] configured, or it will never ask for this client's certificate.

The certificate to be presented to the server will need to be signed by the root certificates or be valid based on the authentication callback set to the listener via ListenerCertificateAuthenticator.



// See {xref-cbl-pg-p2p-manage-tls-id} for more on how to do this.
// Example 6
.Client Cert Authentication
[#configuring-client-authentication]
// BEGIN inclusion -- block -- block_tabbed_code_example.adoc
//
//  Allows for abstraction of the showing of snippet examples
//  which makes displaying tabbed snippets for platforms with
//  more than one native language to show -- Android (Kotlin and Java)
//
// Surrounds code in Example block
//
//  PARAMETERS:
//    param-tags comma-separated list of tags to include/exclude
//    param-leader text for opening para of an example block
//
//  USE:
//    :param_tags: query-access-json
//    include::partial$block_show_snippet.adoc[]
//    :param_tags!:
//

[#java:p2psync-websocket-using-active:::configuring-client-authentication]
====

This example shows client certificate authentication using an identity from secure storage.

// Show Main Snippet
[source, Java]
----
include ::java:example$codesnippet_collection.java[tags="p2p-tlsid-tlsidentity-with-label", indent=0]
// Provide a client certificate to the server for authentication
TLSIdentity clientId = TLSIdentity.getIdentity(keyStore, "client", "squirrel".toCharArray());
if (clientId == null) { throw new IllegalStateException("Cannot find client id"); }
config.setAuthenticator(new ClientCertificateAuthenticator(clientId)); // <.>

// ... other replicator configuration

Replicator repl = new Replicator(config);
repl.start();
thisReplicator = repl;
----




// close example block

====

// Tidy-up atttibutes created
// END -- block_show_snippet.doc
<.> Get an identity from secure storage and create a TLS Identity object
<.> Set the authenticator to https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-java}{empty}/couchbase-lite-java/com/couchbase/lite/ClientCertificateAuthenticator.html[ClientCertificateAuthenticator] and configure it to use the retrieved identity



[discrete#java:p2psync-websocket-using-active:::initialize-replicator]
===== Initialize Replicator


// BEGIN -- inclusion -- common-sgw-replication-init.adoc
//  Location: ROOT:partial$commons/common-
//  Purpose:
//  Used-by:
//

Use the `https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-java}{empty}/couchbase-lite-java/com/couchbase/lite/Replicator.html[Replicator]` class's https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-java}{empty}/couchbase-lite-java/com/couchbase/lite/Replicator.html#Replicator-com.couchbase.lite.ReplicatorConfiguration-[ReplicatorConfiguration(config)] constructor, to initialize the replicator with the configuration you have defined.
You can, optionally, add a change listener (see <<java:p2psync-websocket-using-active:::lbl-repl-mon>>) before starting the replicator running using https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-java}{empty}/couchbase-lite-java/com/couchbase/lite/AbstractReplicator.html#start-boolean-[start()].

// Example 7
.Initialize and run replicator
// BEGIN inclusion -- block -- block_tabbed_code_example.adoc
//
//  Allows for abstraction of the showing of snippet examples
//  which makes displaying tabbed snippets for platforms with
//  more than one native language to show -- Android (Kotlin and Java)
//
// Surrounds code in Example block
//
//  PARAMETERS:
//    param-tags comma-separated list of tags to include/exclude
//    param-leader text for opening para of an example block
//
//  USE:
//    :param_tags: query-access-json
//    include::partial$block_show_snippet.adoc[]
//    :param_tags!:
//

====


// Show Main Snippet
[source, Java]
----
include ::java:example$codesnippet_collection.java[tags="p2p-act-rep-start-full;!p2p-act-rep-add-change-listener", indent=0]
// Create replicator
// Consider holding a reference somewhere
// to prevent the Replicator from being GCed
Replicator repl = new Replicator( // <.>

    // initialize the replicator configuration
    new ReplicatorConfiguration(new URLEndpoint(new URI("wss://listener.com:8954"))) // <.>
        .addCollections(collections, null)

        // Set replicator type
        .setType(ReplicatorType.PUSH_AND_PULL)

        // Configure Sync Mode
        .setContinuous(false) // default value


        // set auto-purge behavior
        // (here we override default)
        .setAutoPurgeEnabled(false) // <.>


        // Configure Server Authentication --
        // only accept self-signed certs
        .setAcceptOnlySelfSignedServerCertificate(true) // <.>

        // Configure the credentials the
        // client will provide if prompted
        .setAuthenticator(new BasicAuthenticator("Our Username", "Our Password".toCharArray())) // <.>

);

// Start replicator
repl.start(false); // <.>


thisReplicator = repl;
thisToken = token;

----




// close example block

====

// Tidy-up atttibutes created
// END -- block_show_snippet.doc
<.> Initialize the replicator with the configuration
<.> Start the replicator
// END -- inclusion -- common-sgw-replication-init.adoc

[discrete#java:p2psync-websocket-using-active:::lbl-repl-mon]
===== Monitor Sync


// BEGIN -- inclusion -- common-sgw-replication-monitor.adoc
//  Usage:
//  Params:
//    :is-p2p:  set when including from P2P topic such as common-p2psync-websocket-using-active
//  Included-by:
//    ROOT:partial$commons/common-p2psync-websocket-using-active.adoc
//    ROOT:partial$commons/common-sgw-replication.adoc
//  ####
// :is-p2p:

In this section::
<<java:p2psync-websocket-using-active:::lbl-repl-chng>>  |
<<java:p2psync-websocket-using-active:::lbl-repl-status>>  |
<<java:p2psync-websocket-using-active:::lbl-repl-evnts>> |
<<java:p2psync-websocket-using-active:::lbl-repl-pend>>

You can monitor a replication’s status by using a combination of <<java:p2psync-websocket-using-active:::lbl-repl-chng>> and the `replication.status.activity` property -- see; https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-java}{empty}/couchbase-lite-java/com/couchbase/lite/ReplicatorStatus.html#getActivityLevel--[getActivityLevel()].
This enables you to know, for example, when the replication is actively transferring data and when it has stopped.

You can also choose to monitor document changes -- see: <<java:p2psync-websocket-using-active:::lbl-repl-evnts>>.

[discrete#java:p2psync-websocket-using-active:::lbl-repl-chng]
====== Change Listeners
Use this to monitor changes and to inform on sync progress; this is an optional step.
You can add and a replicator change listener at any point; it will report changes from the point it is registered.

.Best Practice
TIP: Don't forget to save the token so you can remove the listener later

Use the https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-java}{empty}/couchbase-lite-java/com/couchbase/lite/Replicator.html[Replicator] class to add a change listener as a callback to the Replicator (https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-java}{empty}/couchbase-lite-java/com/couchbase/lite/AbstractReplicator.html#addChangeListener-java.util.concurrent.Executor-com.couchbase.lite.ReplicatorChangeListener-[addChangeListener()]) -- see: <<java:p2psync-websocket-using-active:::ex-repl-mon>>.
You will then be asynchronously notified of state changes.

You can remove a change listener with https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-java}{empty}/couchbase-lite-java/com/couchbase/lite/AbstractReplicator.html#removeChangeListener-com.couchbase.lite.ListenerToken-[removeChangeListener(ListenerToken token)].



[discrete#java:p2psync-websocket-using-active:::lbl-repl-status]
====== Replicator Status

You can use the
https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-java}{empty}/couchbase-lite-java/com/couchbase/lite/ReplicatorStatus.html[ReplicatorStatus()] class
to check the replicator status.
That is, whether it is actively transferring data or if it has stopped -- see: <<java:p2psync-websocket-using-active:::ex-repl-mon>>.

// // ifeval::["{source-language"=="objc"]
// Alternatively, use the https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-java}{empty}/couchbase-lite-java/com/couchbase/lite/ReplicatorStatus.html[ReplicatorStatus()] class to get status information.
The returned _ReplicationStatus_ structure comprises:

* https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-java}{empty}/couchbase-lite-java/com/couchbase/lite/ReplicatorStatus.html#getActivityLevel--[getActivityLevel()] -- stopped, offline, connecting, idle or busy -- see states described in: <<java:p2psync-websocket-using-active:::tbl-states>>
* https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-java}{empty}/couchbase-lite-java/com/couchbase/lite/ReplicatorStatus.html#getProgress--[getProgress()]
** completed -- the total number of changes completed
** total -- the total number of changes to be processed
* https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-java}{empty}/couchbase-lite-java/com/couchbase/lite/ReplicatorStatus.html#getError--[getError()] -- the current error, if any

// :is-android:
// Example 8
[#java:p2psync-websocket-using-active:::ex-repl-mon]
[[java:p2psync-websocket-using-active:::ex-repl-mon]]
.Monitor replication
====


[tabs]
======

Adding a Change Listener::
+
--
[source, Java]
----

ListenerToken token = repl.addChangeListener(change -> {
    CouchbaseLiteException err = change.getStatus().getError();
    if (err != null) { Logger.log("Error code :: " + err.getCode(), err); }
});


----
--
+

Using replicator.status::
+
--
[source, Java]
----

    ReplicatorStatus status = repl.getStatus();
    ReplicatorProgress progress = status.getProgress();
    Logger.log(
        "The Replicator is " + status.getActivityLevel()
            + "and has processed " + progress.getCompleted()
            + " of " + progress.getTotal() + " changes");
}

----
--
======



====


[discrete#java:p2psync-websocket-using-active:::lbl-repl-states]
====== Replication States
<<java:p2psync-websocket-using-active:::tbl-states>> shows the different states, or activity levels, reported in the API; and the meaning of each.

.Replicator activity levels
[#java:p2psync-websocket-using-active:::tbl-states,cols="^1,4"]
|===
h|State
h|Meaning

|`STOPPED`
|The replication is finished or hit a fatal error.

|`OFFLINE`
|The replicator is offline as the remote host is unreachable.

|`CONNECTING`
|The replicator is connecting to the remote host.

|`IDLE`
|The replication caught up with all the changes available from the server.
The `IDLE` state is only used in continuous replications.

|`BUSY`
|The replication is actively transferring data.
|===

NOTE: The replication change object also has properties to track the progress (`change.status.completed` and `change.status.total`).
Since the replication occurs in batches the total count can vary through the course of a replication.



// begin inclusion of document changes text
[#lbl-repl-evnts]
// end inclusion of document changes text

[discrete#java:p2psync-websocket-using-active:::lbl-repl-pend]
====== Documents Pending Push

TIP: https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-java}{empty}/couchbase-lite-java/com/couchbase/lite/AbstractReplicator.html#isDocumentPending-java.lang.String-[Replicator.isDocumentPending] is quicker and more efficient.
Use it in preference to returning a list of pending document IDs, where possible.

You can check whether documents are waiting to be pushed in any forthcoming sync by using either of the following API methods:

* Use the https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-java}{empty}/couchbase-lite-java/com/couchbase/lite/AbstractReplicator.html#getPendingDocumentIds--[Replicator.getPendingDocumentIds()] method, which returns a list of document IDs that have local changes, but which have not yet been pushed to the server.
+
This can be very useful in tracking the progress of a push sync, enabling the app to provide a visual indicator to the end user on its status, or decide when it is safe to exit.

* Use the https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-java}{empty}/couchbase-lite-java/com/couchbase/lite/AbstractReplicator.html#isDocumentPending-java.lang.String-[Replicator.isDocumentPending] method to quickly check whether an individual document is pending a push.

[#ex-pending]
.Use Pending Document ID API
// BEGIN inclusion -- block -- block_tabbed_code_example.adoc
//
//  Allows for abstraction of the showing of snippet examples
//  which makes displaying tabbed snippets for platforms with
//  more than one native language to show -- Android (Kotlin and Java)
//
// Surrounds code in Example block
//
//  PARAMETERS:
//    param-tags comma-separated list of tags to include/exclude
//    param-leader text for opening para of an example block
//
//  USE:
//    :param_tags: query-access-json
//    include::partial$block_show_snippet.adoc[]
//    :param_tags!:
//

[#java:p2psync-websocket-using-active:::ex-pending]
====


// Show Main Snippet
[source, Java]
----
include ::java:example$codesnippet_collection.java[tags="replication-pendingdocuments", indent=0]
Replicator repl = new Replicator(
    new ReplicatorConfiguration(new URLEndpoint(new URI("ws://localhost:4984/mydatabase")))
        .addCollection(collection, null)
        .setType(ReplicatorType.PUSH));

Set<String> pendingDocs = repl.getPendingDocumentIds(collection);

if (!pendingDocs.isEmpty()) {
    Logger.log("There are " + pendingDocs.size() + " documents pending");

    final String firstDoc = pendingDocs.iterator().next();

    repl.addChangeListener(change -> {
        Logger.log("Replicator activity level is " + change.getStatus().getActivityLevel());
        try {
            if (!repl.isDocumentPending(firstDoc, collection)) {
                Logger.log("Doc ID " + firstDoc + " has been pushed");
            }
        }
        catch (CouchbaseLiteException err) {
            Logger.log("Failed getting pending docs", err);
        }
    });

    repl.start();
    this.thisReplicator = repl;
}
----




// close example block

====

// Tidy-up atttibutes created
// END -- block_show_snippet.doc
<.> https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-java}{empty}/couchbase-lite-java/com/couchbase/lite/AbstractReplicator.html#getPendingDocumentIds--[Replicator.getPendingDocumentIds()] returns a list of the document IDs for all documents waiting to be pushed.
This is a snapshot and may have changed by the time the response is received and processed.
<.> https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-java}{empty}/couchbase-lite-java/com/couchbase/lite/AbstractReplicator.html#isDocumentPending-java.lang.String-[Replicator.isDocumentPending] returns `true` if the document is waiting to be pushed, and `false` otherwise.

// END -- inclusion -- common-sgw-replication-monitor.adoc


[discrete#java:p2psync-websocket-using-active:::lbl-repl-stop]
===== Stop Sync

// BEGIN -- inclusion -- common-sgw-replication-stop.adoc
//  Usage:
//  Params:
//    :is-p2p:  set when including from P2P topic such as common-p2psync-websocket-using-active
//  Included-by:
//    ROOT:partial$commons/common-p2psync-websocket-using-active.adoc
//    ROOT:partial$commons/common-sgw-replication.adoc
//  ####

Stopping a replication is straightforward.
It is done using https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-java}{empty}/couchbase-lite-java/com/couchbase/lite/AbstractReplicator.html#stop--[stop()].
This initiates an asynchronous operation and so is not necessarily immediate.
Your app should account for this potential delay before attempting any subsequent operations.

You can find further information on database operations in xref:java:database.adoc[Databases].

// Example 9
.Stop replicator
// BEGIN inclusion -- block -- block_tabbed_code_example.adoc
//
//  Allows for abstraction of the showing of snippet examples
//  which makes displaying tabbed snippets for platforms with
//  more than one native language to show -- Android (Kotlin and Java)
//
// Surrounds code in Example block
//
//  PARAMETERS:
//    param-tags comma-separated list of tags to include/exclude
//    param-leader text for opening para of an example block
//
//  USE:
//    :param_tags: query-access-json
//    include::partial$block_show_snippet.adoc[]
//    :param_tags!:
//

====


// Show Main Snippet
[source, Java]
----
include ::java:example$codesnippet_collection.java[tags="p2p-act-rep-stop", indent=0]
// Stop replication.
repl.stop(); // <.>
----




// close example block

====

// Tidy-up atttibutes created
// END -- block_show_snippet.doc
<.> Here we initiate the stopping of the replication using the https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-java}{empty}/couchbase-lite-java/com/couchbase/lite/AbstractReplicator.html#stop--[stop()] method.
It will stop any active <<java:p2psync-websocket-using-active:::lbl-repl-chng,change listener>> once the replication is stopped.

// END -- inclusion -- common-sgw-replication-monitor.adoc


[discrete#java:p2psync-websocket-using-active:::conflict-resolution]
===== Conflict Resolution

Unless you specify otherwise, Couchbase Lite's default conflict resolution policy is applied -- see xref:java:conflict.adoc[Handling Data Conflicts].

To use a different policy, specify a _conflict resolver_ using https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-java}{empty}/couchbase-lite-java/com/couchbase/lite/ReplicatorConfiguration.html#setConflictResolver-com.couchbase.lite.ConflictResolver-[conflictResolver] as shown in <<java:p2psync-websocket-using-active:::using-conflict-resolvers>>.

For more complex solutions you can provide a custom conflict resolver - see: xref:java:conflict.adoc[Handling Data Conflicts].

// Example 10
[#java:p2psync-websocket-using-active:::using-conflict-resolvers]
.Using conflict resolvers
====
// :is-android:

[tabs]
=====

Local Wins::
+
--

[source, Java]
----

class LocalWinConflictResolver implements ConflictResolver {
    public Document resolve(Conflict conflict) {
        return conflict.getLocalDocument();
    }
}

----
--


Remote Wins::
+
--

[source, Java]
----

class RemoteWinConflictResolver implements ConflictResolver {
    public Document resolve(Conflict conflict) {
        return conflict.getRemoteDocument();
    }
}

----

--


Merge::
+
--

[source, Java]
----

class MergeConflictResolver implements ConflictResolver {
    public Document resolve(Conflict conflict) {
        Map<String, Object> merge = conflict.getLocalDocument().toMap();
        merge.putAll(conflict.getRemoteDocument().toMap());
        return new MutableDocument(conflict.getDocumentId(), merge);
    }
}

----

--
=====

====

Just as a replicator may observe a conflict -- when updating a document that has changed both in the local database and in a remote database -- any attempt to save a document may also observe a conflict, if a replication has taken place since the local app retrieved the document from the database.
To address that possibility, a version of the `Database.save()` method also takes a conflict resolver as shown in <<java:p2psync-websocket-using-active:::ex-merge-props>>.

The following code snippet shows an example of merging properties from the existing document (`current`) into the one being saved (`new`).
In the event of conflicting keys, it will pick the key value from `new`.

.Merging document properties
[#ex-merge-props]
// BEGIN inclusion -- block -- block_tabbed_code_example.adoc
//
//  Allows for abstraction of the showing of snippet examples
//  which makes displaying tabbed snippets for platforms with
//  more than one native language to show -- Android (Kotlin and Java)
//
// Surrounds code in Example block
//
//  PARAMETERS:
//    param-tags comma-separated list of tags to include/exclude
//    param-leader text for opening para of an example block
//
//  USE:
//    :param_tags: query-access-json
//    include::partial$block_show_snippet.adoc[]
//    :param_tags!:
//

[#java:p2psync-websocket-using-active:::ex-merge-props]
====


// Show Main Snippet
[source, Java]
----
include ::java:example$codesnippet_collection.java[tags="update-document-with-conflict-handler", indent=0]
Document doc = collection.getDocument("xyz");
if (doc == null) { return; }
MutableDocument mutableDocument = doc.toMutable();
mutableDocument.setString("name", "apples");

collection.save(
    mutableDocument,
    (newDoc, curDoc) -> {
        if (curDoc == null) { return false; }
        Map<String, Object> dataMap = curDoc.toMap();
        dataMap.putAll(newDoc.toMap());
        newDoc.setData(dataMap);
        return true;
    });
----




// close example block

====

// Tidy-up atttibutes created
// END -- block_show_snippet.doc





For more on replicator conflict resolution see: xref:java:conflict.adoc[Handling Data Conflicts].


[discrete#java:p2psync-websocket-using-active:::delta-sync]
===== Delta Sync
// DONE: Add reference to listener section tht includes enableDeltaSync parameter being set to true
If delta sync is enabled on the listener, then replication will use delta sync.


// DO NOT EDIT OR REMOVE
// Unset is-p2p flag
// inclusion
//:param-how: //:param-reference: reference-deploy




[discrete#java:p2psync-websocket-using-active:::related-content]
===== Related Content
++++
<div class="card-row three-column-row">
++++

[.column]
====== {empty}
.How to
* xref:java:p2psync-websocket-using-passive.adoc[Passive Peer]
* xref:java:p2psync-websocket-using-active.adoc[Active Peer]


.

[discrete.colum#java:p2psync-websocket-using-active:::-2n]
====== {empty}
.Concepts
* xref:java:landing-p2psync.adoc[Peer-to-Peer Sync]

* https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-java}{empty}/couchbase-lite-java/[API References]

.


[.column]
// [.content]
[discrete#java:p2psync-websocket-using-active:::-3]
====== {empty}
.Community Resources ...
//* Community
https://forums.couchbase.com/c/mobile/14[Mobile Forum] |
https://blog.couchbase.com/[Blog] |
https://docs.couchbase.com/tutorials/[Tutorials]


.
xref:tutorials:cbl-p2p-sync-websockets:swift/cbl-p2p-sync-websockets.adoc[Getting Started with Peer-to-Peer Synchronization]




++++
</div>
++++
// DO NOT EDIT OR REMOVE

// include::ROOT:partial$block-caveats.adoc[tag=enterprise-only]


