:docname: troubleshooting-logs
:page-module: java
:page-relative-src-path: troubleshooting-logs.adoc
:page-origin-url: https://github.com/couchbase/docs-couchbase-lite.git
:page-origin-start-path:
:page-origin-refname: antora-assembler-simplification
:page-origin-reftype: branch
:page-origin-refhash: (worktree)
[#java:troubleshooting-logs:::]
== Using Logs
:page-role:
:description: Couchbase Lite on Java -- Using Logs for Troubleshooting


[abstract]
--
Description -- _{description}_ +
Related Content -- xref:java:troubleshooting-queries.adoc[Troubleshooting Queries]
--


.Constraints
[NOTE]
--

* The retrieval of logs from the device is out of scope of this feature.
* This content applies to the post 2.5 versions.
If you are using a Couchbase Lite release prior to 2.5 see <<java:troubleshooting-logs:::pre-2x5-logging,Deprecated functionality>>

--


[#java:troubleshooting-logs:::introduction]
=== Introduction
Couchbase Lite provides a robust Logging API footnote:fn-2x5[From version 2.5] -- see: API References for https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-java}{empty}/couchbase-lite-java/com/couchbase/lite/Log.html[Log], https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-java}{empty}/couchbase-lite-java/com/couchbase/lite/FileLogger.html[FileLogger] and https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-java}{empty}/couchbase-lite-java/com/couchbase/lite/LogFileConfiguration.html[LogFileConfiguration(String directory)] -- which make debugging and troubleshooting easier during development and in production.
It delivers flexibility in terms of how logs are generated and retained, whilst also maintaining the level of logging required by Couchbase Support for investigation of issues.

Log output is split into the following streams:

* <<java:troubleshooting-logs:::lbl-file-logs>>
+
Here logs are written to <<java:troubleshooting-logs:::log-file-outputs,separate log files>> filtered by log level, with each log level supporting individual retention policies.

* <<java:troubleshooting-logs:::lbl-console-logs>>
+
--
You can independently configure and control console logs, which provides a convenient method of accessing diagnostic information during debugging scenarios.
With console logging, you can fine-tune diagnostic output to suit specific debug scenarios, without interfering with any logging required by Couchbase Support for the investigation of issues.
--

* <<java:troubleshooting-logs:::lbl-custom-logs>>
+
--
For greater flexibility you can implement a custom logging class using the https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-java}{empty}/couchbase-lite-java/com/couchbase/lite/Logger.html[Logger] interface.

--

In all instances, you control what is logged and at what level using the https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-java}{empty}/couchbase-lite-java/com/couchbase/lite/Log.html[Log] class.

[#java:troubleshooting-logs:::lbl-console-logs]
=== Console based logging
Console based logging is often used to facilitate troubleshooting during development.

Console logs are your go-to resource for diagnostic information.
You can easily fine-tune their diagnostic content to meet the needs of a particular debugging scenario, perhaps by increasing the verbosity and-or choosing to focus on messages from a specific domain; to better focus on the problem area.

Changes to console logging are independent of file logging, so you can make change without compromising any files logging streams.
It is enabled by default.
To change default settings use database's https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-java}{empty}/couchbase-lite-java/com/couchbase/lite/Log.html[Log] method to set the required values -- see <<java:troubleshooting-logs:::eg-cons-log>>

You will primarily use https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-java}{empty}/couchbase-lite-java/com/couchbase/lite/Log.html[log.getConsole()] and https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-java}{empty}/couchbase-lite-java/com/couchbase/lite/ConsoleLogger.html[ConsoleLogger] to control console logging.


[#eg-cons-log]
.Change Console Logging Settings


[#java:troubleshooting-logs:::eg-cons-log]
====

This example enables and defines console-based logging settings.

// Show Main Snippet
// include::java:example$codesnippet_collection.java[tags="console-logging", indent=0]
[source, Java]
----
Database.log.getConsole().setLevel(LogLevel.DEBUG); // <.>
----


====

<.> Define the required domain ; here we turn on logging for all available domains -- see: https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-java}{empty}/couchbase-lite-java/com/couchbase/lite/ConsoleLogger.html#setDomains-java.util.EnumSet-[log.getConsole().setDomain()] and enum https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-java}{empty}/couchbase-lite-java/com/couchbase/lite/LogDomain.html[LogDomain]
<.> Here we turn on the most verbose log level -- see: https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-java}{empty}/couchbase-lite-java/com/couchbase/lite/ConsoleLogger.html#setLevel-com.couchbase.lite.LogLevel-[log.getConsole().setLevel()] and enum https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-java}{empty}/couchbase-lite-java/com/couchbase/lite/LogLevel.html[LogLevel]. +
To disable logging for the specified https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-java}{empty}/couchbase-lite-java/com/couchbase/lite/LogDomain.html[LogDomain] set the https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-java}{empty}/couchbase-lite-java/com/couchbase/lite/LogLevel.html[LogLevel] to `None`.

Related::
https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-java}{empty}/couchbase-lite-java/com/couchbase/lite/Log.html[Log] | https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-java}{empty}/couchbase-lite-java/com/couchbase/lite/Log.html[log.getConsole()] | https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-java}{empty}/couchbase-lite-java/com/couchbase/lite/ConsoleLogger.html[ConsoleLogger]

[#java:troubleshooting-logs:::lbl-file-logs]
=== File based logging
File based logging is disabled by default --  see: <<java:troubleshooting-logs:::eg-file-log>> for how to enable it.

You will primarily use https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-java}{empty}/couchbase-lite-java/com/couchbase/lite/Log.html[log.getFile()] and https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-java}{empty}/couchbase-lite-java/com/couchbase/lite/FileLogger.html[FileLogger] to control file-based logging.

[#java:troubleshooting-logs:::formats]
==== Formats
Available file based logging formats:

* Binary -- most efficient for storage and performance. It is the default for file based logging.
+
Use this format and a decoder, such as *cbl-log*, to view them -- see: <<java:troubleshooting-logs:::decoding-binary-logs>>.
* Plaintext

[#java:troubleshooting-logs:::configuration]
==== Configuration
As with console logging you can set the log level -- see:  the https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-java}{empty}/couchbase-lite-java/com/couchbase/lite/FileLogger.html[FileLogger] class.

With file based logging you can also use the https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-java}{empty}/couchbase-lite-java/com/couchbase/lite/LogFileConfiguration.html[LogFileConfiguration(String directory)] class's properties to specify the:

* log file path to the directory to store the log file
Once this limit is exceeded a new log file is started.
* log file format +
The default is _binary_.
You can over ride that where necessary and output a plain text log.
* maximum number of rotated log files to keep
* maximum size of the log file (bytes).

[#eg-file-log]
.Enabling file logging


[#java:troubleshooting-logs:::eg-file-log]
====


// Show Main Snippet
// include::java:example$codesnippet_collection.java[tags="file-logging", indent=0]
[source, Java]
----
LogFileConfiguration LogCfg = new LogFileConfiguration(
    (System.getProperty("user.dir") + "/MyApp/logs")); // <.>
LogCfg.setMaxSize(10240); // <.>
LogCfg.setMaxRotateCount(5); // <.>
LogCfg.setUsePlaintext(false); // <.>
Database.log.getFile().setConfig(LogCfg);
Database.log.getFile().setLevel(LogLevel.INFO); // <.>
----


====

<.> Set the log file directory
<.> Here we change the max rotation count from the default (1) to 5. +
*Note* this means six files may exist at any one time; the five rotated log files, plus the active log file
<.> Here we set the maximum size (bytes) for our log file
<.> Here we select the binary log format (included for reference only as this is the default)
<.> Here we increase the log output level from the default (_warnings_) to _info_ -- see: https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-java}{empty}/couchbase-lite-java/com/couchbase/lite/FileLogger.html#setLevel-com.couchbase.lite.LogLevel-[log.getFile().setLevel()]
+
*Note* that the use of https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-java}{empty}/couchbase-lite-java/com/couchbase/lite/Database.html#setLogLevel-com.couchbase.lite.LogDomain-com.couchbase.lite.LogLevel-[Database.setLogLevel()] is now deprecated.
Further, you can no longer set a log level for a specific domain.

Related::
 https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-java}{empty}/couchbase-lite-java/com/couchbase/lite/Log.html[Log] |
https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-java}{empty}/couchbase-lite-java/com/couchbase/lite/Log.html[log.getFile()] | https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-java}{empty}/couchbase-lite-java/com/couchbase/lite/FileLogger.html[FileLogger]

[#java:troubleshooting-logs:::lbl-custom-logs]
=== Custom logging

Couchbase Lite allows for the registration of a callback function to receive Couchbase Lite log messages, which may be logged using any external logging framework.

To do this, apps must implement the https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-java}{empty}/couchbase-lite-java/com/couchbase/lite/Logger.html[Logger] interface -- see <<java:troubleshooting-logs:::eg-impl-log>> -- and enable custom logging using https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-java}{empty}/couchbase-lite-java/com/couchbase/lite/Log.html[log.setCustom()] -- see <<java:troubleshooting-logs:::eg-cust-log>>.


[#eg-impl-log]
.Implementing logger interface


[#java:troubleshooting-logs:::eg-impl-log]
====

pass:q,a[Here we introduce the code that implements the https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-java}{empty}/couchbase-lite-java/com/couchbase/lite/Logger.html[Logger] interface.]

// Show Main Snippet
// include::java:example$codesnippet_collection.java[tags="custom-logging", indent=0]
[source, Java]
----
class LogTestLogger implements com.couchbase.lite.Logger {
    @NonNull
    private final LogLevel level;

    public LogTestLogger(@NonNull LogLevel level) { this.level = level; }

    @NonNull
    @Override
    public LogLevel getLevel() { return level; }

    @Override
    public void log(@NonNull LogLevel level, @NonNull LogDomain domain, @NonNull String message) {

    }
}
----


====


[#eg-cust-log]
.Enabling custom logging


[#java:troubleshooting-logs:::eg-cust-log]
====

pass:q,a[This example show how to enable the custom logger from <<java:troubleshooting-logs:::eg-impl-log>>.]

// Show Main Snippet
// include::java:example$codesnippet_collection.java[tags="set-custom-logging", indent=0]
[source, Java]
----
Database.log.setCustom(new LogTestLogger(LogLevel.WARNING)); // <.>
----


====

<.> Here we set the custom logger with a level of 'warning'.
The custom logger is called with every log and may choose to filter it, using its configured level.


Related::
https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-java}{empty}/couchbase-lite-java/com/couchbase/lite/Log.html[Log] | https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-java}{empty}/couchbase-lite-java/com/couchbase/lite/Log.html[log.getCustom()] | https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-java}{empty}/couchbase-lite-java/com/couchbase/lite/Logger.html[Logger]

[#java:troubleshooting-logs:::decoding-binary-logs]
=== Decoding binary logs

You can use the *cbl-log* tool to decode binary log files -- see <<java:troubleshooting-logs:::eg-cbl-log>>.

[#java:troubleshooting-logs:::eg-cbl-log]
.Using the cbl-log tool
=====
[tabs]
====

macOS::
+
--
Download the *cbl-log* tool using `wget`.

[source,console,subs="attributes"]
----
wget https://packages.couchbase.com/releases/couchbase-lite-log/{major}.{minor}.{base}{empty}/couchbase-lite-log-{major}.{minor}.{base}{empty}-macos.zip
----

Navigate to the *bin* directory and run the `cbl-log` executable.

[source,console]
----
$ ./cbl-log logcat LOGFILE <OUTPUT_PATH>
----
--


CentOS::
+
--
Download the *cbl-log* tool using `wget`.

[source,console, subs="attributes"]
----
wget https://packages.couchbase.com/releases/couchbase-lite-log/{major}.{minor}.{base}{empty}/couchbase-lite-log-{major}.{minor}.{base}{empty}-centos.zip
----

Navigate to the *bin* directory and run the `cbl-log` executable.

[source,console]
----
cbl-log logcat LOGFILE <OUTPUT_PATH>
----
--


Windows::
+
--
Download the *cbl-log* tool using PowerShell.

[source,powershell, subs="attributes"]
----
Invoke-WebRequest https://packages.couchbase.com/releases/couchbase-lite-log/{major}.{minor}.{base}{empty}/couchbase-lite-log-{major}.{minor}.{base}{empty}-windows.zip -OutFile couchbase-lite-log-{major}.{minor}.{base}{empty}-windows.zip
----

Run the `cbl-log` executable.

[source,powershell]
----
$ .\cbl-log.exe logcat LOGFILE <OUTPUT_PATH>
----
--
====
=====


[#java:troubleshooting-logs:::related-content]
=== Related Content
++++
<div class="card-row three-column-row">
++++

[.column]
==== {empty}
.How to . . .
* xref:java:querybuilder.adoc[QueryBuilder]
* xref:java:query-n1ql-mobile.adoc[{sqlpp} for Mobile]
* xref:java:query-live.adoc[Live Queries]
* xref:java:fts.adoc[Full Text Search]


.

[discrete.colum#java:troubleshooting-logs:::-2n]
==== {empty}
.Learn more . . .
* xref:java:query-n1ql-mobile-querybuilder-diffs.adoc[{sqlpp} Mobile - Querybuilder  Differences]
* xref:java:query-n1ql-mobile-server-diffs.adoc[{sqlpp} Mobile - {sqlpp} Server Differences]
* xref:java:query-resultsets.adoc[Query Resultsets]
* xref:java:query-troubleshooting.adoc[Query Troubleshooting]
* xref:java:query-live.adoc[Live Queries]

* xref:java:database.adoc[Databases]
* xref:java:document.adoc[Documents]
* xref:java:blob.adoc[Blobs]

.


[discrete.colum#java:troubleshooting-logs:::-3n]
==== {empty}
.Dive Deeper . . .
https://forums.couchbase.com/c/mobile/14[Mobile Forum] |
https://blog.couchbase.com/[Blog] |
https://docs.couchbase.com/tutorials/[Tutorials]

.


++++
</div>
++++


