= Upgrade
:page-aliases: advance/java-dep-upgrade.adoc, dep-upgrade.adoc
:page-role:
:description:


:source-language: Java


[IMPORTANT]
--
On upgrading from a 2.x release, all Couchbase Lite databases will be automatically re-indexed on initial database open. +
This can result in a delay before the database is usable.
--

=== Vector Search Extension

Couchbase Lite 3.4.0 is compatible with Vector Search Extension 2.0.0 only.
If your application uses Vector Search, update the Vector Search Extension to 2.0.0 when upgrading to Couchbase Lite 3.4.0.

[#3-4-0-upgrade]
== {major}.{minor-java}.{maintenance-java}{empty} Upgrade

Couchbase Lite {major}.{minor} is a non-breaking upgrade from 3.3.
Update your Couchbase Lite dependency to {major}.{minor} -- no API or configuration changes are required.

[WARNING]
--
When upgrading from Couchbase Lite 3.4.0 to the 4.x release line, upgrade directly to 4.1.0 or later.
Couchbase Lite 4.x versions below 4.1.0 do not include all APIs added in 3.4.0 (Multipeer Replicator with Bluetooth and Auto Switching, Replication Correlation ID, and on Android, Kotlin Serialization; and on C, the C++ API).
--

[#api-changes]
=== API Changes

This content introduces the changes made to the Couchbase{nbsp}Lite for Java API for release {major}.{minor-java}.{maintenance-java}{empty}.

[#removed]
==== Removed

[#resetcheckpoint]
===== ResetCheckpoint

The method https://docs.couchbase.com/mobile/2.8.0/couchbase-lite-java/com/couchbase/lite/AbstractReplicator.html#resetCheckpoint--[Replicator.resetCheckpoint()] method has been removed. +
Instead, use https://docs.couchbase.com/mobile/{major}.{minor-java}.{base}{empty}/couchbase-lite-java/com/couchbase/lite/AbstractReplicator.html#start-boolean-[Replicator.resetCheckpoint(boolean reset)].

.Before
[source, Java,subs="attributes+, macros+"]
----
replicator.resetCheckpoint()
replicator.start()
----

.After
[source, Java,subs="attributes+, macros+"]
----
replicator.start(true)
----

[#lbl-db-upgrades]
== 1.x Databases Upgrades to 2.x

Databases created using Couchbase Lite 1.2 or later can still be used with Couchbase Lite 2.x; but will be automatically updated to the current 2.x version.
This feature is only available for the default storage type (i.e., not a ForestDB database).

[#encrypted-databases]
=== Encrypted Databases
The automatic migration feature does not support encrypted databases.
So if the 1.x database is encrypted you will first need to disable encryption using the Couchbase Lite 1.x API (see the https://docs-archive.couchbase.com/couchbase-lite/1.4/Java.html#database-encryption[1.x Database Guide]).

.Upgrading Encrypted Databases
****
. Disable encryption using the Couchbase Lite 1.x framework (see https://docs-archive.couchbase.com/couchbase-lite/1.4/java.html#database-encryption[1.x encryption guide])
. Open the database file with encryption enabled using the Couchbase Lite 2.x framework.
****

Since it is not possible to package Couchbase Lite 1.x and Couchbase Lite 2.x in the same application this upgrade path would require two successive upgrades.

[#downgrading-couchbase-lite]
== Downgrading Couchbase Lite

[#downgrading-between-major-releases]
=== Downgrading Between Major Releases

*No Downgrade Support* - Downgrades between major versions of Couchbase Lite (CBL) are not supported.

[#downgrading-between-minor-releases]
=== Downgrading Between Minor Releases

*Conditional Downgrade Support* - Downgrade support for minor releases is considered on a case-by-case basis.
The release notes for each minor version will clarify whether downgrades are supported.

[#downgrading-between-patch-releases]
=== Downgrading Between Patch Releases

*Full Downgrade Support* - Downgrades between patch releases are supported.
Users can safely downgrade between different patch versions within the same minor release.

[#related-content]
== Related Content
++++
<div class="card-row three-column-row">
++++

[.column]
=== {empty}
.How to . . .
* xref:java:gs-prereqs.adoc[Prerequisites]
* xref:java:gs-install.adoc[Install]
* xref:java:gs-build.adoc[Build and Run]

.

[.column]
=== {empty}
.Learn more . . .
* xref:java:database.adoc[Databases]
* xref:java:document.adoc[Documents]
* xref:java:blob.adoc[Blobs]
* xref:java:replication.adoc[Remote Sync Gateway]
* xref:java:conflict.adoc[Handling Data Conflicts]

.

[.column]
=== {empty}
.Dive Deeper . . .
https://forums.couchbase.com/c/mobile/14[Mobile Forum] |
https://blog.couchbase.com/[Blog] |
https://docs.couchbase.com/tutorials/[Tutorials]

.

++++
</div>
++++