= New in {release}
ifdef::prerelease[:page-status: {prerelease}]
ifdef::show_edition[:page-edition: {release}]
:page-partial:
:page-content-type: reference
:keywords: edge nosql performant compatibility mobile replication
// End of Page Definition Statements

include::partial$_set_page_context_for_root.adoc[]

:param-abstract: This content covers the new features and behaviors introduced in Couchbase Lite {version-full}
:param-related: {release-notes--xref-list}
include::partial$_show_page_header_block.adoc[]


NOTE: Couchbase Lite 3.0 introduces some breaking changes. +
If you are upgrading from 2.x, please refer to the appropriate upgrade page -- see: <<lbl-upgrade>>
Users should be able to upgrade to 3.1.x from 3.0.x without manual intervention.


== Release 3.2.0 - Beta 1 (March 2024)

.Deprecation Notice
[IMPORTANT]

--

Support for iOS 12 across all platforms will be deprecated in this release and will be removed in a future release.
Please plan to migrate your apps to use an appropriate alternative version.

--

=== New Features

==== Vector Search

Couchbase Lite for iOS(Swift, Objective-C) and Android is now providing an open beta for our vector search offering.

Vector Search is a Similarity Search method that looks for approximated nearest vectors in localised vector space. 
These vectors are represented by arrays of numbers known as an embedding, which are generated by Large Language Models (LLMs) to represent objects such as text, images, and audio. 
You can use Vector Search to efficiently find similar items or content based on the similarity of their vector representations. 
This is particularly useful for large datasets and real-time response applications.

Read more at: 

* xref:swift:vector-search.adoc[Vector Search - Swift]

* xref:objc:vector-search.adoc[Vector Search - Objective-C]

* xref:android:vector-search.adoc[Vector Search - Android]

==== Extended Date/Time Functionality

Six new functions

== See also

xref:3.1@couchbase-lite:ROOT:cbl-whatsnew.adoc[What's new in previous version 3.1]

=== Release Notes

xref:swift:releasenotes.adoc[Swift]
|
xref:objc:releasenotes.adoc[Objective-C]
|
xref:java:releasenotes.adoc[Java]
|
xref:android:releasenotes.adoc[Android]
|
xref:csharp:releasenotes.adoc[.Net]
|
xref:c:releasenotes.adoc[C]

[#lbl-upgrade]
=== Upgrading

xref:swift:upgrade.adoc[Swift]
|
xref:objc:upgrade.adoc[Objective-C]
|
xref:java:upgrade.adoc[Java]
|
xref:android:upgrade.adoc[Android]
|
xref:csharp:upgrade.adoc[.Net]
// Upgrade.adoc doesn't seem to exist for C?
// |
// xref:c:upgrade.adoc[C]



