= What's New
:page-status: {release-status-cbl} -- {release-comments-cbl}
:page-edition: Under Development
:page-layout: article
:page-content-type: procedural
:page-roles:
:description: Couchbase Lite - latest features
:keywords: edge nosql performant compatibility mobile replication
// End of Page Definition Statements

include::{param-module}::partial$_std-cbl-hdr-{param-module}.adoc[]

ifndef::release-status-cbl[:release-status-cbl!:]
ifeval::["{release-status-cbl}" == "gamma"]
[.pane__frame--orange]
.Author's Notes
--
Add content covering CBL P2P's new features, plus other changes at this release.

* DOC-6368-H2: CBL What's New - update page
https://issues.couchbase.com/browse/DOC-6368

Compile the release highlights page for Sync Gateway 2.8 to include summaries of: 

* New Features
* Major behaviour changes in:
** Usage, Config, Support (e.g. deprecations), bugs and other –  as appropriate
SOURCE: https://issues.couchbase.com/secure/attachment/89196/89196_compatibility_matrix_hydrogen.adoc
+
See: {xref-cbl-pg-replication} and {xref-cbl-pg-supportnotes}
--
endif::[]

[.pane__frames.no-title.cols-3]
== {empty}

.Highlights
* This release introduces an out-of-the-box _MessageEndpointListener_ the _WebsocketEndpointLisener_, which makes developing peer-to-peer-sync for your applications easier.
* Read more: {xref-cbl-pg-p2psync-oob}

.Release Notes
* This release also contains a number of bug fixes and enhancements for Couchbase Lite.
* Find out more in the release notes.
* {empty}
+
xref:swift.adoc#release-notes[Swift] | xref:java-platform.adoc#release-notes[Java] | xref:java-android.adoc#release-notes[Java (Android)] | xref:javascript.adoc#release-notes[Javascript] | xref:csharp.adoc#release-notes[C#] | xref:objc.adoc#release-notes[objective-C]
