= What's New

== Highlights

=== N1QL for Couchbase Lite

Couchbase Lite 2.0 introduces a new Query API with semantics based on Couchbase's N1QL query language.

xref:swift.adoc#query[swift] | xref:java.adoc#query[java] | xref:csharp.adoc#query[c#] | xref:objc.adoc#query[objective-c]

=== WebSocket replication protocol

Couchbase Lite 2.0 uses a new replication protocol based on WebSockets. This protocol is designed to be faster and more efficient.

xref:swift.adoc#replication[swift] | xref:java.adoc#replication[java] | xref:csharp.adoc#replication[c#] | xref:objc.adoc#replication[objective-c]

=== Full-Text Search

This release includes the ability to run Full-Text Search queries on documents stored in the local database.

xref:swift.adoc#full-text-search[swift] | xref:java.adoc#full-text-search[java] | xref:csharp.adoc#full-text-search[c#] | xref:objc.adoc#full-text-search[objective-c]

=== Database Replicas

Replication between two local databases is now supported. This feature can be used for data recovery on device.

xref:swift.adoc#database-replicas[swift] | xref:java.adoc#database-replicas[java] | xref:csharp.adoc#database-replicas[c#] | xref:objc.adoc#database-replicas[objective-c]

=== Automatic Conflict Resolution

In Couchbase Lite 2.0, document conflicts are automatically resolved. This functionality simplifies conflict management.

xref:swift.adoc#handling-conflicts[swift] | xref:java.adoc#handling-conflicts[java] | xref:csharp.adoc#handling-conflicts[c#] | xref:objc.adoc#handling-conflicts[objective-c]

== Release Notes

This release contains a number of bug fixes and enhancements for Couchbase Lite. Find out more in the release notes.
