= What's New

== Highlights

=== Delta Sync

This release adds delta sync support in replications between Couchbase Lite and Sync Gateway.
Delta Sync is the ability to replicate only parts of the Couchbase mobile document that have changed.
This can result in significant savings in bandwidth consumption as well as throughput improvements, especially when network bandwidth is typically constrained.

xref:sync-gateway::config-properties.adoc#databases-foo_db-delta_sync[Read more]

=== Replication Filters

Replication filters allow users to have control over which documents are stored as the result of a push and/or pull replication.

xref:swift.adoc#replication-filters[swift] | xref:java.adoc#replication-filters[java] | xref:csharp.adoc#replication-filters[c#] | xref:objc.adoc#replication-filters[objective-c]

=== Continuous Logging

Continuous logging feature unifies the logging behavior across all Couchbase Lite platforms with options to log to files or to integrate with custom log frameworks within mobile apps.

xref:swift.adoc#logging[swift] | xref:java.adoc#logging[java] | xref:csharp.adoc#logging[c#] | xref:objc.adoc#logging[objective-c]

=== Predictive Query

Predictive Queries allow apps to run prediction queries against Couchbase Lite data using pre-trained Machine Learning (ML) models bundled along with the apps.

Predictive query is in developer preview.
The API is xref:compatibility.adoc#interface-stability[uncommitted].

xref:swift.adoc#predictive-query[swift] | xref:java.adoc#predictive-query[java] | xref:csharp.adoc#predictive-query[c#] | xref:objc.adoc#predictive-query[objective-c]

=== Document Expiration

Document expiration allows you to set the expiration date on a document.
When the document is expired, the document is purged from the database.

xref:swift.adoc#document-expiration[swift] | xref:java.adoc#document-expiration[java] | xref:csharp.adoc#document-expiration[c#] | xref:objc.adoc#document-expiration[objective-c]

=== Replication Events

Replication Events add the possibility to register for document updates during a replication.
With this new feature, you can perform actions based on data synchronization.

xref:swift.adoc#replication-events[swift] | xref:java.adoc#replication-events[java] | xref:csharp.adoc#replication-events[c#] | xref:objc.adoc#replication-events[objective-c]

== Release Notes

This release contains a number of bug fixes and enhancements for Couchbase Lite.
Find out more in the release notes.

xref:swift.adoc#release-notes[swift] | xref:java.adoc#release-notes[java] | xref:csharp.adoc#release-notes[c#] | xref:objc.adoc#release-notes[objective-c]
