= What's New

== Highlights

=== Delta Sync

This release adds delta sync support in replications between Couchbase Lite and Sync Gateway.
Delta Sync is the ability to replicate only parts of the Couchbase mobile document that have changed.
This can result in significant savings in bandwidth consumption as well as throughput improvements, especially when network bandwidth is typically constrained.

xref:sync-gateway::config-properties.adoc#databases-foo_db-delta_sync[Read more]

=== Replication Filters

Replication filters allow users to have quick control over which documents are stored as the result of a push and/or pull replication.

xref:swift.adoc#replication-filters[swift] | xref:java.adoc#replication-filters[java] | xref:csharp.adoc#replication-filters[c#] | xref:objc.adoc#replication-filters[objective-c]

=== Continuous Logging

Continuous logging is a new feature in Couchbase Lite that unifies the logging behavior across all platforms and making logs easier to both retrieve and decode during development and in production.

xref:swift.adoc#continuous-logging[swift] | xref:java.adoc#continuous-logging[java] | xref:csharp.adoc#continuous-logging[c#] | xref:objc.adoc#continuous-logging[objective-c]

=== Predictive Query

Predictive Queries allow apps to run prediction queries against Couchbase Lite data using pre-trained Machine Learning (ML) models bundled along with the apps.

Predictive query is in developer preview.
The API is xref:compatibility-matrix.adoc[uncommitted].

xref:swift.adoc#predictive-query[swift] | xref:java.adoc#predictive-query[java] | xref:csharp.adoc#predictive-query[c#] | xref:objc.adoc#predictive-query[objective-c]

== Release Notes

This release contains a number of bug fixes and enhancements for Couchbase Lite.
Find out more in the release notes.

xref:swift.adoc#release-notes[swift] | xref:java.adoc#release-notes[java] | xref:csharp.adoc#release-notes[c#] | xref:objc.adoc#release-notes[objective-c]
