= Introduction
:page-aliases: introduction.adoc
:page-layout: landing-page-core-concept
:page-status:
:page-role: tiles, -toc
:!sectids:

= Introducing Couchbase Lite
++++
<div class="card-row">
++++

[.column]
====== {empty}
[.content]
Couchbase Lite is an embedded, NoSQL JSON-document Style database for your mobile apps.

You can use Couchbase Lite as a standalone embedded database within your mobile apps, or with Sync Gateway and Couchbase Server to provide a complete cloud to edge synchronized solution.

[.column]
====== {empty}
[.media-left]
image::get-the-agility-of-sql-and-the-flexibility-of-json.svg[,250]
++++
</div>
++++
++++
<div class="card-row">
++++
[.column]
===== Work locally . . .
* Couchbase Lite is designed to work with data stored locally and includes
** The ability to write queries with semantics based on SQL.
** _Full-Text Search_ queries on documents stored locally.
** The ability to store document attachments (blobs), for example images or PDF files.

[.column]
===== Sync at the edge . . .
* It manages data sync automatically through:
** A replication protocol built over WebSockets to synchronize data with Sync Gateway.
** A Peer-to-Peer sync implementation to synchronize data between Couchbase Lite clients without dependency upon centralized control.

++++
</div>
++++
