= JavaScript
:description: Using Couchbase Lite with Javascript applications
:page-role: tiles
:!sectids:

// :topic-group: platforms
:param-abstract: If you are building mobile or desktop applications using web technologies such as JavaScript/HTML/CSS, here are some options for using Couchbase Lite as an embedded database within your app.
// :param-related!:
// include::{root-partials}block-abstract.adoc[]

{param-abstract}

== Cordova/PhoneGap

You can https://blog.couchbase.com/couchbase-lite-data-storage-ionic-app-cordova-plugins/[build] your own https://cordova.apache.org/docs/en//latest/guide/hybrid/plugins/index.html[Cordova plugin] on top of Couchbase Lite’s native API for iOS and Android.

We have a couple of tutorials that describe how you can build your own plugin for https://docs.couchbase.com/tutorials/hotel-lister/android.html[Android] and http://docs.couchbase.com/tutorials/hotel-lister/ios.html[iOS] respectively.

You can use the samples in the tutorials  as a starting point and expand it to suit your application requirements.
As described in the tutorials, it is recommended that your plugin implements a subset of native APIs that is relevant to your application.

== Ionic

You can https://blog.couchbase.com/couchbase-lite-data-storage-ionic-app-cordova-plugins/[build] your own https://cordova.apache.org/docs/en//latest/guide/hybrid/plugins/index.html[Cordova plugin] on top of Couchbase Lite’s native API for iOS and Android.

The Cordova plugin is independent of the application's UI layer and can be used to access native functionality from within your Ionic apps.

We have a couple of tutorials that describe how you can build your own plugin for https://docs.couchbase.com/tutorials/hotel-lister/android.html[Android] and http://docs.couchbase.com/tutorials/hotel-lister/ios.html[iOS] respectively.

You can use the samples in the tutorials as a starting point and expand it to suit your application requirements.
As described in the tutorials, it is recommended that your plugin implement a subset of native APIs that is relevant to your application.

== React Native

https://facebook.github.io/react-native/docs/native-modules-ios[React Native Modules] make it easy to access native platform functionality from within your JavaScript based React Native apps.
You can leverage this to https://blog.couchbase.com/couchbase-lite-react-native/[build] your own React Native plugin on top of Couchbase Lite’s native API for iOS and Android.
We have a couple of tutorials that describe how you can build your plugin for https://docs.couchbase.com/tutorials/hotel-finder/android.html[Android] and https://docs.couchbase.com/tutorials/hotel-finder/ios.html[iOS] respectively.
You can use the samples as a starting point and expand it to suit your application requirements.
As described in the tutorials, it is recommended that your plugin implement a subset of native APIs that is relevant to your application.

== Electron

You can develop your own https://electronjs.org[Electron.js] wrapper on top of https://docs.couchbase.com/couchbase-lite/current/csharp/quickstart.html[Couchbase Lite’s C#.NET] API.

// DO NOT EDIT -- Footer Related Content Block
// include::{root-partials}block-related-content-std.adoc[]
// DO NOT EDIT

