= JavaScript
:page-role: tiles
:!sectids:

If you are building mobile or desktop applications using web technologies such as JavaScript/HTML/CSS, here are some options for using Couchbase Lite as an embedded database within your app.

== Cordova/PhoneGap

=== Supported Plugin

Ionic offers a fully supported https://ionicframework.com/integrations/couchbase-lite[Offline Storage Plugin] that is powered by Couchbase Lite Enterprise Edition.
The plugin exposes a JavaScript API that has full feature-parity with the underlying native API layer.
The Ionic native plugin leverages the Cordova plugin to access Couchbase Lite’s native functionality on iOS and Android.
This means that with Ionic’s native plugin, you can build hybrid apps using Cordova/PhoneGap for iOS and Android platforms.
If you do not have access to the plugin, please contact your Accounts team.

=== Build your own

You can also https://blog.couchbase.com/couchbase-lite-data-storage-ionic-app-cordova-plugins/[build] your own https://cordova.apache.org/docs/en//latest/guide/hybrid/plugins/index.html[Cordova plugin] on top of Couchbase Lite’s native API for iOS and Android.
We have a couple of tutorials that describe how you can build your own plugin for https://docs.couchbase.com/tutorials/hotel-lister/android.html[Android] and http://docs.couchbase.com/tutorials/hotel-lister/ios.html[iOS] respectively.
You can use the samples as a starting point and expand it to suit your application requirements.
As described in the tutorials, it is recommended that your plugin implements a subset of native APIs that is relevant to your application.

== Ionic

=== Supported Plugin

Ionic offers a fully supported https://ionicframework.com/integrations/couchbase-lite[Offline Storage Plugin] that is powered by Couchbase Lite Enterprise Edition.
If you are developing cross-platform apps in Ionic, you can use Ionic’s native plugin to access Couchbase Lite’s native functionality on iOS and Android.
The plugin works with Cordova and is compatible with https://capacitor.ionicframework.com/docs/[Capacitor], Ionic’s new app runtime.
If you do not have access to the plugin, please contact your Accounts team.

=== Build your own

You can https://blog.couchbase.com/couchbase-lite-data-storage-ionic-app-cordova-plugins/[build] your own https://cordova.apache.org/docs/en//latest/guide/hybrid/plugins/index.html[Cordova plugin] on top of Couchbase Lite’s native API for iOS and Android.
The Cordova plugin is independent of the application's UI layer and can be used to access native functionality from within your Ionic apps.
We have a couple of tutorials that describe how you can build your own plugin for https://docs.couchbase.com/tutorials/hotel-lister/android.html[Android] and http://docs.couchbase.com/tutorials/hotel-lister/ios.html[iOS] respectively.
You can use the samples as a starting point and expand it to suit your application requirements.
As described in the tutorials, it is recommended that your plugin implement a subset of native APIs that is relevant to your application.

== React Native

=== Build your own

https://facebook.github.io/react-native/docs/native-modules-ios[React Native Modules] make it easy to access native platform functionality from within your JavaScript based React Native apps.
You can leverage this to https://blog.couchbase.com/couchbase-lite-react-native/[build] your own React Native plugin on top of Couchbase Lite’s native API for iOS and Android.
We have a couple of tutorials that describe how you can build your plugin for https://docs.couchbase.com/tutorials/hotel-finder/android.html[Android] and https://docs.couchbase.com/tutorials/hotel-finder/ios.html[iOS] respectively.
You can use the samples as a starting point and expand it to suit your application requirements.
As described in the tutorials, it is recommended that your plugin implement a subset of native APIs that is relevant to your application.

== Electron

=== Supported Plugin

Ionic offers a fully supported https://ionicframework.com/integrations/couchbase-lite[Offline Storage Plugin] that is powered by Couchbase Lite Enterprise Edition.
This plugin can be used to build cross-platform desktop apps using web technologies such as JavaScript/HTML/CCS powered by https://electronjs.org[Electron].
The plugin exposes a JavaScript API that has feature parity with the underlying Couchbase Lite native API.

=== Build your own

You can develop your own Electron.js wrapper on top of https://docs.couchbase.com/couchbase-lite/current/csharp.html[Couchbase Lite’s .NET] API.
