= JavaScript
:page-edition:
:page-status:
:page-role:
:page-toclevels: 2@
:description: Using Couchbase Lite with Javascript applications

// :topic-group: platforms
:param-abstract: If you are building mobile or desktop applications using web technologies such as JavaScript/HTML/CSS, here are some options for using Couchbase Lite as an embedded database within your app.
:param-related!:

include::partial$_std-cbl-hdr-root.adoc[]

include::partial$block-abstract.adoc[]


== Ionic

=== Enterprise Edition Deployments

Ionic's Couchbase Lite integration is tailor-made for web developers, making it easy to build secure, high-performance, offline-enabled apps.
This premier integration supports apps built for iOS, Android, and native Windows.

Using a robust JavaScript API, you can access the entirety of Couchbase Lite's functionality with no native experience required.

As a starting point, follow the hotel search tutorial which shows how to build an app that allows users to search and bookmark hotels using data loaded from a Couchbase Lite database -- see tutorial at https://ionic.io/docs/couchbase-lite/tutorials/hotel-search[tutorial/to/be/created/for/3.0.GA].

.Resources
****
* Docs: https://ionic.io/docs/couchbase-lite. +
* Demo: https://github.com/ionic-team/demo-couchbaselite-hotels  +
* Downloading the plugin:
Reach out to Ionic sales to get access, either from the docs page or this landing page.
****

=== Community Edition Deployments

You can build your own native plugin on top of Couchbase Lite's native API for iOS and Android.
The plugin is independent of the application's UI layer and can be used to access native functionality from within your Ionic apps.

You have two options:

* Capacitor: +
Ionic recommends use of [Capacitor|capacitor], so building a capacitor plugin would be preferred option
* Cordova: +
Alternatively, you have the option of building a Cordova Plugin and using that within your Ionic app.
+
We have some reference implementation of a Cordova plugin and a sample Ionic app that uses the Cordova plugin.
You can use the samples in the tutorials as a starting point and expand it to suit your application requirements.

.Resources:
****
* Reference Plugin (Android): https://github.com/rajagp/couchbase-lite-cordova-plugin-android
* Sample App: https://github.com/rajagp/userprofile-couchbase-mobile-cordova-android

****


== React Native


https://facebook.github.io/react-native/docs/native-modules-ios[React Native Modules] make it easy to access native platform functionality from within your JavaScript based React Native apps.
You can leverage this to https://blog.couchbase.com/couchbase-lite-react-native/[build] your own React Native plugin on top of Couchbase Lite's native API for iOS and Android.

We have a couple of tutorials that describe how you can build your plugin for https://docs.couchbase.com/tutorials/hotel-finder/android.html[Android] and https://docs.couchbase.com/tutorials/hotel-finder/ios.html[iOS] respectively.

You can use the samples as a starting point and expand it to suit your application requirements.
As described in the tutorials, it is recommended that your plugin implement a subset of native APIs that is relevant to your application.


== Cordova

You also have the option of building a Cordova Plugin and using that within your Ionic app.

We have some reference implementations of a Cordova plugin and a sample Ionic app that uses the Cordova plugin.
You can use the samples in the tutorials as a starting point and expand it to suit your application requirements.

.Resources
****
* Reference Plugin (Android): https://github.com/rajagp/couchbase-lite-cordova-plugin-android
* Sample App: https://github.com/rajagp/userprofile-couchbase-mobile-cordova-android
****

== Electron


You can develop your own https://electronjs.org[Electron.js] wrapper on top of xref:csharp:quickstart.adoc[Couchbase Lite's C#.NET] API.

// DO NOT EDIT -- Footer Related Content Block
// include::{root-partials}block-related-content-std.adoc[]
// DO NOT EDIT

