= Java

:idprefix:
:idseparator: -
:icons: font
:source-highlighter: rouge
:quick-uri: https://asciidoctor.org/docs/asciidoc-syntax-quick-reference/
ifndef::env-site,env-github[]
:toc: left
:toclevels: 3
endif::[]
toc::[]

NOTE: This is a *Beta* build that is NOT QE approved. This is intended for use in development/test environments to integrate with the new Couchbase Lite 2.7 Java API. It must NOT be used in production environments. Since this is a private beta, please direct all questions to Priya Rajagopal (priya.rajagopal@couchbase.com) and your respective accounts team.

== Getting Started
=== Couchbase Lite
A Beta1 version of Couchbase Lite EE 2.7 Java framework is packaged as a .zip file and is available for download from the <<Download Links>> section.

The .zip includes the following

* The `couchbase-lite-java-ee-2.7.0-DB001.jar` that includes native libraries for  Windows, Linux and macOS

* Relevant dependencies including
** `json-20180813.jar`
** `okhttp-3.9.1.jar`
** `okio-1.13.0.jar`

* Given the heterogenity of Linux platforms, specifically for Linux, we have included the required versions of relevant shared support libraries
** The `support` folder  contains the relevant shared system libraries (libz, libc++, icu ) that must be linked to when building on Linux. *Note*: Distributing the compatible system libraries elimintaes the hassle of having to download/ build compatible versions of system libraries for the Linux platform of choice.

==== Linux platforms
In addition to the .jars, you will need to load the support libraries distributed with Couchbase Lite.

There are two options to load the support libraries for linux:

1. Set `LD_LIBRARY_PATH` environment parameter for example:
[source,bash]
----
export LD_LIBRARY_PATH=/path/to/ouchbase-lite-java-ee-2.7.0-DB001/download/support/linux/icu/lib:$LD_LIBRARY_PATH

export LD_LIBRARY_PATH=//path/to/ouchbase-lite-java-ee-2.7.0-DB001/download/support/linux/zlib/1.2.11/lib:$LD_LIBRARY_PATH

export LD_LIBRARY_PATH=//path/to/ouchbase-lite-java-ee-2.7.0-DB001/download/support/linux/libc++:$LD_LIBRARY_PATH
----

(You can also put this in your .bashrc file)

2. Use java.library.path property when running java command.
[source,bash]
----
java -Djava.library.path=/path/to/ouchbase-lite-java-ee-2.7.0-DB001/support/linux/libc++:/path/to/ouchbase-lite-java-ee-2.7.0-DB001/support/linux/icu/lib:/path/to/ouchbase-lite-java-ee-2.7.0-DB001/support/linux/zlib/1.2.11/lib:
----


==== non-Linux platforms
Build and run with the .jars that are provided in the .zip package. You do not need the support libraries.

==== API References
With the exception of the link:https://docs.couchbase.com/mobile/2.6.0/couchbase-lite-java/[`init()`] API, all other APIs are identical to the Android Java version of Couchbase Lite. The only difference is that the `init()` API accepts no parameters.

Refer to the link:https://docs.couchbase.com/couchbase-lite/2.6/java.html#database[java code snippets] provided in the Android Java section while implementing the Java app.


==== Sample App
You can download a starter app from the <<Download Links>> section.  The Couchbase Lite enabled Java app demonstrates the basic CRUD and sync functionality.

This is the source code of the sample app is found in the `StarterApp.java` file
[source,java]
----
import com.couchbase.lite.*;

import java.net.URI;

public class StarterCode {
    private static final String SYNC_GATEWAY_URL = "ws://localhost:4984/db"; //<1>

    public static void main(String[] args) throws Exception {
        // Initialize Couchbase Lite
        CouchbaseLite.init(); // <2>

        // Get the database (and create it if it doesn’t exist).
        DatabaseConfiguration config = new DatabaseConfiguration();
        config.setEncryptionKey(new EncryptionKey("PASSWORD")); // <3>
        Database database = new Database("mydb", config);

        // Create a new document (i.e. a record) in the database.
        MutableDocument mutableDoc = new MutableDocument()
                .setDouble("version", 2.0)
                .setString("type", "SDK");

        // Save it to the database.
        database.save(mutableDoc);

        // Update a document.
        mutableDoc = database.getDocument(mutableDoc.getId()).toMutable();
        mutableDoc.setString("language", "Java");
        database.save(mutableDoc);

        Document document = database.getDocument(mutableDoc.getId());
        // Log the document ID (generated by the database) and properties
        System.out.println("Document ID is :: " + document.getId());
        System.out.println("Learning " + document.getString("language"));

        // Create a query to fetch documents of type SDK.
        Query query = QueryBuilder.select(SelectResult.all())
                .from(DataSource.database(database))
                .where(Expression.property("type").equalTo(Expression.string("SDK")));
        ResultSet result = query.execute();
        System.out.println("Number of rows ::  " + result.allResults().size());

        // Create a query to fetch documents of type SDK.
        Document document2 = database.getDocument("demo101");
        // Log the document ID (generated by the database) and properties
        System.out.println("Document ID :: " + document2.getId());
        System.out.println("Learning " + document2.getString("foo"));


        Endpoint targetEndpoint = new URLEndpoint(new URI(SYNC_GATEWAY_URL));
        ReplicatorConfiguration replConfig = new ReplicatorConfiguration(database, targetEndpoint);
        replConfig.setReplicatorType(ReplicatorConfiguration.ReplicatorType.PUSH_AND_PULL);

        // Add authentication.
        replConfig.setAuthenticator(new BasicAuthenticator("demo", "password"));

        // Create replicator (be sure to hold a reference somewhere that will prevent the Replicator from being GCed)
        Replicator replicator = new Replicator(replConfig);

        // Listen to replicator change events.
        replicator.addChangeListener(change -> {
            if (change.getStatus().getError() != null) {
                System.err.println("Error code ::  " + change.getStatus().getError().getCode());
            }

        });

        // Start replication.
        replicator.start();

        // Check status of replication and wait till it is completed
        while (replicator.getStatus().getActivityLevel() != Replicator.ActivityLevel.STOPPED) {
            Thread.sleep(1000);
        }

        System.out.println("Finish!");

        System.exit(0); // <4>
    }
}

----
<1> The app will start a replicator pointing to `ws://localhost:4984/db`.
<2> This is the only API that differs from the Android Java version. It accepts no parameters
<3> You can optionally AES-256 encrypt the database by providing a key
<4> This is needed for the websocket connections to gracefully close

===== Testing the sample app
====== Setup Couchbase Server
- Install Couchbase Server following steps outlined in link:https://docs.couchbase.com/sync-gateway/2.6/getting-started.html#creating-an-rbac-user[documentation]
-  Create a bucket named "db" following instructions link:https://docs.couchbase.com/sync-gateway/2.6/getting-started.html#creating-a-bucket[here]
-  Create a RBAC user with "admin" as username and password as "password" following instructions link:https://docs.couchbase.com/sync-gateway/2.6/getting-started.html#creating-an-rbac-user[here]

====== Setup Sync Gateway
- Install the Sync Gateway following the steps outlined in the link:https://docs.couchbase.com/sync-gateway/2.6/getting-started.html#enterprise-edition[documentation].
- Configure the Sync Gateway using the following sample sync-gateway-config file.

[source,json]
----
{
  "log": ["*"],
  "logging": {
    "log_file_path": "/var/tmp/sglogs",
    "console": {
      "log_level": "debug",
      "log_keys": ["*"]
    },
    "error": {
      "enabled": true,
      "rotation": {
        "max_size": 20,
        "max_age": 180
      }
    },
    "warn": {
      "enabled": true,
      "rotation": {
        "max_size": 20,
        "max_age": 90
      }
    },
    "info": {
      "enabled": true
    },
    "debug": {
      "enabled": true
    }
  },
  "databases": {
    "db": {
      "server": "http://localhost:8091",
      "bucket": "db", // <1>
      "username": "admin", // <2>
      "password": "password", // <3>
      "enable_shared_bucket_access": true,
      "import_docs": "continuous",
      "num_index_replicas": 0,
       "import_filter": `
        function(doc) {

          return true;
        }`,
      "users":{
          "GUEST":{"disabled":true},
          "admin": {"password": "password", "admin_channels": ["*"]},
          "demo": {"password": "password", "admin_channels": ["*"]} // <4>
      }
    }
  }
}
----

<1> This is the name of the bucket you configured on server
<2> This is the username of the RBAC user
<3> This is password of the RBAC user
<4> This is a Sync Gateway user. Replication will happen within the context of the user.

====== Running the sample app
- On Linux, follow the steps outlined in <<Linux platforms>> to load the correct support libraries
- To build the .jar, run the following command. The FAT jar file will be generated in build/libs folder
[source,java]
----
./gradlew jar
----

- To run the app, run the following command
[source,java]
----
./gradlew run
----

- To run using the generated FAT jar file, use the following command
[source,java]
----
java -jar StarterCode-1.0.jar
----

- The `mydb.cblite2` database directory will be created at the current directory from where the application is run

== OS Support
Couchbase Lite Java will be supported on x86 64-bit platforms. These are the targeted OS versions

.Table Supported OS Versions
|===
| OS|Version|Type

.2+|RHEL
|6.10
|Desktop & Web Service/Servlet (Tomcat)
|7
|Desktop & Web Service/Servlet (Tomcat)
.2+|centOS
|6.10
|Desktop & Web Service/Servlet (Tomcat)
|7
|Desktop & Web Service/Servlet (Tomcat)
|Ubuntu
|16.0
|Desktop & Web Service/Servlet (Tomcat)
|Debian
|GNU/Linux 8
|Desktop & Web Service/Servlet (Tomcat)
|Microsoft Server
|Windows Server 2012
|Web Service/Servlet (Tomcat)
|Microsoft
|Windows 10
|Desktop

|===
.Table Supported OS Versions (DEVELOPMENT & TESTING ONLY)
|===
| OS|Version|Type

|macOS
|macOS 10.12.6 (High Sierra)
|Desktop & Web Service/Servlet (Tomcat)
|===



== Download Links

- link:https://drive.google.com/file/d/1LTyydRRI7ZrgnBPgXnIinuaERc61hHX6/view?usp=sharing[Couchbase Lite Java]
- link:https://drive.google.com/file/d/1OZqKA6gN5DB3fJtF3oD7D8C7E7C_jxDr/view?usp=sharing[Sample Starter App]


== License
Enterprise License : https://www.couchbase.com/legal/agreements/LA07152019
