= Samples
:page-role: tiles
:!sectids:

== Travel Sample

An in-depth tutorial that demonstrates key end-to-end Couchbase Mobile 2.0 capabilities for iOS, Android and .NET (UWP and Xamarin) platforms.
The Travel Sample app will allow users to search for and to make flight reservations
Shared bucket access is enabled to allow web and mobile clients to perform the same operations on the bucket.

http://docs.couchbase.com/tutorials/travel-sample/[Learn more >]

== ToDo Sample

This simple ToDo List application is built with Couchbase Lite 2.0 for iOS, Android, UWP and Xamarin (iOS, Android) platforms.
Users can authenticate, create lists with tasks.
Each task can have an optional blob (image) attached to it.
Lists can be shared with multiple users.

https://github.com/couchbaselabs/mobile-training-todo/tree/feature/2.0[Learn more >]

== Hotel Finder: Building a React Native Module

In this tutorial, you will learn how to use Couchbase Lite in a React Native project for iOS and Android.
The user Interface is written in JavaScript while the business logic and data model is written in native Swift/Java.

https://docs.couchbase.com/tutorials/hotel-finder/ios.html[iOS >]
https://docs.couchbase.com/tutorials/hotel-finder/android.html[Android >]

== Hotel Lister: Building a Cordova Plugin

In this tutorial, you will learn how to use Couchbase Lite in a Cordova plugin for an Ionic project targeting iOS and Android.
The user Interface is written in JavaScript while the business logic and data model is written in native Swift/Java.

https://docs.couchbase.com/tutorials/hotel-lister/ios.html[iOS >]
https://docs.couchbase.com/tutorials/hotel-lister/android.html[Android >]

== Swift Playground

This Xcode playground demonstrates many features of the Couchbase Lite 2.0 API.
And with the features of Xcode playgrounds, you can run the code sequentially and see results instantly within Xcode.

https://github.com/couchbaselabs/couchbase-lite-ios-api-playground[Learn more >]

== User Profile Sample: Fundamentals

This tutorial will walk you through a very basic example of how you can use Couchbase Lite 2.0 as a standalone, embedded data store within your iOS App.
You will learn the fundamentals of Database Operations and Document CRUD Operations.

https://docs.couchbase.com/tutorials/userprofile-couchbase-mobile/standalone/userprofile/userprofile_basic.html[Learn more >]

== User Profile Sample: Prebuilt Database & Query Introduction

This tutorial will walk you through a simple app that will demonstrate how to use a pre-built Couchbase Lite database.
In addition, we will look at a sample Query using the new Query API to retrieve records from the local database.

https://docs.couchbase.com/tutorials/userprofile-couchbase-mobile/query/userprofile/userprofile_query.html[Learn more >]

== User Profile Sample: Data Sync Fundamentals

This tutorial will introduce you to data sync/replication across Couchbase Lite apps using the Sync Gateway.
We will walk through Sync Gateway configuration and the core Sync Function API.

https://docs.couchbase.com/tutorials/userprofile-couchbase-mobile/sync/userprofile/userprofile_sync.html[Learn more >]

== University Lister – Using Couchbase Lite with Recycler Views

This tutorial will walk you through a simple example of how you can use Couchbase Lite 2.0 as a standalone, embedded data store within your Android App.
Specifically, you will learn the basics of Database CRUD and Query API and specifically how to use Couchbase Lite as a data source for your Recycler Views.

https://docs.couchbase.com/tutorials/universitylister-android/livequery_recyclerview.html[Learn more >]
