= Release Notes
:page-layout: article
:page-status:
:page-edition: Under Development
:page-role: -toc
:description: Documents release notes for each platform release


include::{param-module}::partial$_std-cbl-hdr-{param-module}.adoc[]

ifndef::release-status-cbl[:release-status-cbl!:]
ifeval::["{release-status-cbl}" == "gamma"]
[.pane__frame--orange]
.Author's Notes
--
DOC-6272-ReleaseNotes
https://issues.couchbase.com/browse/DOC-6272

Add content to release notes, whats news etc

* New Features section – summarise any new features in a release * highlights section
* Behaviour Changes section*
* Features – summarise any changed features including implication* s, constraints etc
* Configuration – identify any config changes including implicati* ons (note this includes highlighting deprecation)
* Major bugs/KE changes – summarise  as appropriate*
* License change – as appropriate*
* Other –  as appropriate*
* Support Notes section*
* New/changed constraints – as appropriate*
* New deprecation notices*
* Update existing deprecation notices*
* Enhancements/Bugs/KE content - extract and include Jira ticket * links


* DOC-6865-H2-P2P: New topic - Implementing TLS in P2P Sync
https://issues.couchbase.com/browse/DOC-6865
SOURCE: https://docs.google.com/document/d/1LDM8PozLIG2Y0Th7y8NKiEhcED_z-yUXXYEJ29d3wp8/edit?ts=5eceb5c8#heading=h.jt6eun8ptdvy
+
See: {xref-cbl-pg-replication} and {xref-cbl-pg-supportnotes}


DOC-6866-H2-P2P: Database Maintenance API
https://issues.couchbase.com/browse/DOC-6866
+
SOURCE: https://docs.google.com/document/d/1xPPUEqOs8MSDk5mvlxq1JgIJu8WfnjgpHKgF_y_Asyc/edit?ts=5ecfc5b8#
+
See: {xref-cbl-pg-supportnotes}

Create a conceptual topic that describes Couchbase Lite's implementation of TLS in P2P sync.

Sources include:
* https://docs.google.com/document/d/1HupbJ8HMka6SlNewzN-tG2gybrQrF0wB6FPaqc-NJ8E/edit?usp=sharing_eil&ts=5e615876

[IB] Topics to cover

* his feature will only be supported on iOS versions starting iOS10 due to dependencies on keychain APIs
It  should be noted that for all other features, the minimum supported iOS will continue to be iOS9


--
endif::[]

== New Features
//section – summarise any new features in a release highlights section

== Behaviour Changes section

== Features
// – summarise any changed features including implications, constraints etc

== Configuration Changes
// – identify any config changes including implications (note this includes highlighting deprecation)

== Major bugs/KE changes
// – summarise  as appropriate

== License changes
// – as appropriate

== Other
// –  as appropriate

== Support Notes section

== New/changed constraints
// – as appropriate

== New deprecation notices

// Update existing deprecation notices
// Enhancements/Bugs/KE content - extract and include Jira ticket links