= Release Notes -- Couchbase Lite for Android
:page-layout: article
:page-status:
:page-edition: Under Development
:page-role: -toc
:description: Documents release notes for each platform release
:keywords: edge nosql api android java

include::partial$_std-cbl-hdr-android.adoc[]

:param-abstract: Related Content -- {xref-cbl-pg-whatsnew}
include::{root-partials}block-abstract.adoc[]
// :ziputils: ROOT:example$/java-android/app/src/main/java/com/couchbase/code_snippets/ZipUtils.java

ifndef::release-status-cbl[:release-status-cbl!:]
ifeval::["{release-status-cbl}" == "gamma"]
[.pane__frame--orange]
.Author's Notes
--
DOC-6272-ReleaseNotes
https://issues.couchbase.com/browse/DOC-6272

Add content to release notes, whats news etc

* New Features section – summarise any new features in a release * highlights section
* Behaviour Changes section*
* Features – summarise any changed features including implication* s, constraints etc
* Configuration – identify any config changes including implicati* ons (note this includes highlighting deprecation)
* Major bugs/KE changes – summarise  as appropriate*
* License change – as appropriate*
* Other –  as appropriate*
* Support Notes section*
* New/changed constraints – as appropriate*
* New deprecation notices*
* Update existing deprecation notices*
* Enhancements/Bugs/KE content - extract and include Jira ticket * links


* DOC-6865-H2-P2P: New topic - Implementing TLS in P2P Sync
https://issues.couchbase.com/browse/DOC-6865
SOURCE: https://docs.google.com/document/d/1LDM8PozLIG2Y0Th7y8NKiEhcED_z-yUXXYEJ29d3wp8/edit?ts=5eceb5c8#heading=h.jt6eun8ptdvy
+
See: {xref-cbl-pg-replication} and {xref-cbl-pg-supportnotes}


DOC-6866-H2-P2P: Database Maintenance API
https://issues.couchbase.com/browse/DOC-6866
+
SOURCE: https://docs.google.com/document/d/1xPPUEqOs8MSDk5mvlxq1JgIJu8WfnjgpHKgF_y_Asyc/edit?ts=5ecfc5b8#
+
See: {xref-cbl-pg-supportnotes}

Create a conceptual topic that describes Couchbase Lite's implementation of TLS in P2P sync.

Sources include:
* https://docs.google.com/document/d/1HupbJ8HMka6SlNewzN-tG2gybrQrF0wB6FPaqc-NJ8E/edit?usp=sharing_eil&ts=5e615876

[IB] Topics to cover

* his feature will only be supported on iOS versions starting iOS10 due to dependencies on keychain APIs
It  should be noted that for all other features, the minimum supported iOS will continue to be iOS9


--
endif::[]

NOTE1: This is a *Beta* build that is NOT QE approved. This is intended for use in development and test environments. It must NOT be used in production environments.

Since this is a private release, please direct all questions to the Product Manager, Priya Rajagopal (priya.rajagopal@couchbase.com) and your respective accounts team. Pleaase do not use any public forums for questions.

=== Couchbase Lite - what's new

include::{android-pages}product/cbl-whatsnew.adoc[tag=whatsnew]

//include::couchbase-lite:{param-module}:product/cbl-whatsnew.adoc[tag=whatsnew]


=== Documentation
* Beta Documentation: {xref-cbl-pg-p2psync-websocket}
* {url-api-reference-URLEndpointListener}[API References]

// === Sample App
// You can download a detailed tutorial and corresponding android app project from the <<Download Links>> section. The sample app demonstrates the websockets listener based peer-to-peer capability.

== OS Support
Couchbase Lite for Android OS will support peer-to-peer functionality on Android API 22+.

== Download Links

include::{android-pages}product/cbl-whatsnew.adoc[tag=downloads]

//- link:https://packages.couchbase.com/releases/couchbase-lite-ios/2.8.0-beta/couchbase-lite-android_enterprise_2.8.0.zip[Couchbase Lite iOS Swift Prerelease]
//- link:https://packages.couchbase.com/releases/couchbase-lite-ios/2.8.0-beta/couchbase-lite-objc_enterprise_2.8.0.zip[Couchbase Lite iOS ObjC Prerelease]
//- link:https://drive.google.com/file/d/1ewD11aeY0jr0M0YdwQ-XDlZRCnj8-1Gg/view?usp=sharing[Sample Swift App for Peer-to-Peer - Sample Project and Tutorial]

== License
Enterprise License : https://www.couchbase.com/legal/agreements/LA07152019


include::{root-partials}block-related-content-start.adoc[]
