ext {
    CBL_VERSION = project.hasProperty('cblVersion') ? project.cblVersion : { throw new GradleException('cblVersion property is required. Use -PcblVersion=x.x.x-x') }()
    EXT_VERSION = project.hasProperty('extVersion') ? project.extVersion : { throw new GradleException('extVersion property is required. Use -PextVersion=x.x.x-x') }()
}

buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.8.20"
        classpath 'com.android.tools.build:gradle:8.0.2'
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
