= Couchbase Lite for React Native
:description: Couchbase Lite is an embedded, document-style NoSQL database that is syncable and makes it easy to build offline-enabled applications.
:page-aliases: hybrid:react.adoc
:pp: {plus}{plus}
:version-rn: {major-rn}.{minor-rn}.{maintenance-rn}

Couchbase Lite for React Native is a Native Module implementation of Couchbase Lite for React Native using Typescript. It has feature parity with Couchbase Lite implementations for other platforms, with a few exceptions.

Version 1.1 adds official React Native New Architecture support through TurboModules.

More information on React Native - Native Modules can be found here: https://reactnative.dev/docs/legacy/native-modules-intro[React Native Docs]

[NOTE]
====
Couchbase Lite for React Native has officially graduated from a community project to a fully Enterprise-Supported offering
====

Install via npm: https://www.npmjs.com/package/@couchbase/couchbase-lite-react-native[@couchbase/couchbase-lite-react-native] -- see xref:react-native:start-here/install.adoc[Install] for full setup.

The version of this Native Module is based on supporting Couchbase Lite Enterprise for iOS and Android.  A https://www.couchbase.com/pricing/[license] is required to use Couchbase Lite Enterprise edition.

== Features

* Offline First
* Documents
 	- Schemaless
 	- Stored in efficient binary format
* Blobs
 	- Store and sync binary data, for example JPGs or PDFs
* Queries
 	- SQL{pp} Query Language
      - Extension of familiar SQL for JSON-like data
      - Many built-in functions
 ** Full-Text Search
 ** Indexing
* Data Sync
 ** https://www.couchbase.com/products/capella[Couchbase Capella App Servcies] - Sync your data from your mobile app to the Cloud
 ** Remote On-Premise via https://www.couchbase.com/products/sync-gateway[Sync Gateway]
* Change Notifications for
 ** Documents
 ** Collections
 ** Queries
 ** Replication
* Encryption
 ** Full Database
* Pre-built Databases
 ** Bundle a pre-populated database with your app to reduce initial sync time and bandwidth on first launch
* React Native New Architecture
 ** TurboModule support for iOS and Android
* Logging
 ** Console, file, and custom log sinks
 ** React Native wrapper logs can be forwarded to file and custom sinks

[NOTE]
====
This plugin only works with iOS and Android platforms.  Web, Windows, and macOS support is not available -- see xref:react-native:product-notes/compatibility.adoc#platform-support[Platform Support].
====

== Upgrading?

If you are upgrading from 1.0.x to 1.1, see the xref:react-native:guides/migration/v1.1.adoc[Version 1.1 Migration Guide].

If you are upgrading from 0.6.x, see the xref:react-native:guides/migration/v1.adoc[Version 1.0 Migration Guide] for detailed instructions on upgrading to version 1.0.

[NOTE]
====
Migrating from 0.6.x directly to 1.1? Follow both guides in order -- complete the xref:react-native:guides/migration/v1.adoc[Version 1.0 Migration Guide] first, then the xref:react-native:guides/migration/v1.1.adoc[Version 1.1 Migration Guide].
====

== Limitations

Some of the features supported by other platform implementations of Couchbase Lite are currently not supported:

* Vector Search
 ** Not yet available on this platform.
* Peer-to-Peer Sync
 ** There is no "platform" specific code built into the plugin to allow you to find other peers.
