:docname: database
:page-module: csharp
:page-relative-src-path: database.adoc
:page-origin-url: https://github.com/couchbase/docs-couchbase-lite.git
:page-origin-start-path:
:page-origin-refname: antora-assembler-simplification
:page-origin-reftype: branch
:page-origin-refhash: (worktree)
[#csharp:database:::]
== Databases
:page-aliases: learn/csharp-database.adoc
:page-role:
:description: Working with Couchbase Lite Databases



// BEGIN -- inclusion -- {module-partials}_define_module_attributes.adoc
//  Usage:  Here we define module specific attributes. It is invoked during the compilation of a page,
//          making all attributes available for use on the page.
//  UsedBy: ROOT:partial$_std_cbl_hdr.adoc

// BEGIN::module page attributes
// :source-language: Java

// :snippet-p2psync-ws: {snippets-p2psync-ws--csharp}
// SET full maintenance version number

// VECTOR SEARCH attributes

// END::module page attributes


// BEGIN - Set attributes pointing to API references for this module


// Supporting Data Type Classes

// COLLECTION CLASSES


// DATABASE CLASSES



//Database.SAVE



//Database.DELETE


// deprecated 2.8
//
// :url-api-method-database-compact: https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-net}{empty}/couchbase-lite-net/api/Couchbase.Lite.Database.html#Couchbase_Lite_Database_Compact[Database.Compact()]





// links for documents pages

// :url-api-class-dictionary: https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-net}{empty}/couchbase-lite-net/api/Couchbase.Lite.DictionaryObject.html[property accessors]



// QUERY RELATED CLASSES and METHODS

// Result Classes and Methods






// Query class and methods

// Expression class and methods
// :url-api-method-expression-like: https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-net}{empty}/couchbase-lite-net/api/Couchbase.Lite.Query.IExpression.html#Couchbase_Lite_Query_IExpression_Like_Couchbase_Lite_Query_IExpression_

// ArrayFunction class and methods


// Function class and methods
//

// Where class and methods
//

// orderby class and methods
//

// GroupBy class and methods
//





// PEER-TO-PEER CLASSES

// URLENDPOINT CLASSES




// :url-api-references-tlsidentity-property: https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-net}{empty}/couchbase-lite-net/api/Couchbase.Lite.P2P.TLSIdentity.html#Couchbase_Lite_P2P_TLSIdentity_







// https://ibsoln.github.io/betasites/api/mobile/2.8.0/couchbase-lite-csharp/com/couchbase/lite/URLEndpointListenerConfiguration.html#setPort-int-




// :url-api-references-urlendpointconfiguration-initcfg: https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-net}{empty}/couchbase-lite-net/api/Couchbase.Lite.P2P.URLEndpointListenerConfiguration.html#Couchbase_Lite_P2P_URLEndpointListenerConfiguration_initWithConfig::[-initWithConfig:]
// :url-api-references-urlendpointconfiguration-init: https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-net}{empty}/couchbase-lite-net/api/Couchbase.Lite.P2P.URLEndpointListenerConfiguration.html#Couchbase_Lite_P2P_URLEndpointListenerConfiguration_init:[-init:]




// diag: Env+Module csharp


// AUTHENTICATORS




// REPLICATOR API CLASSES



// :url-api-references-replicator-abs: https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-net}{empty}/couchbase-lite-net/api/Couchbase.Lite.Sync.AbstractReplicator.html
// :url-api-class-replicator-abs: {url-api-references-replicator-abs}[AbstractReplicator]
// :url-api-properties-replicator-abs: {url-api-references-replicator-abs}#









//:url-api-property-replicator-status-activity: https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-net}{empty}/couchbase-lite-net/api/Couchbase.Lite.Sync.Replicator.html#s:18CouchbaseLitecsharp10ReplicatorC13ActivityLevelO


// REPLICATORSTATUS


// ReplicatorConfiguration API





// :url-api-prop-replicator-config-auth-get: https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-net}{empty}/couchbase-lite-net/api/Couchbase.Lite.Sync.ReplicatorConfiguration.html#Couchbase_Lite_Sync_ReplicatorConfiguration_getAuthenticator--[getAuthenticator]



// Begin Replicator Retry Config
// End Replicator Retry Config




// replaced
// replaced

// :url-api-enum-replicator-config-ServerCertificateVerificationMode: https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-net}{empty}/couchbase-lite-net/api/Couchbase.Lite.Sync.ReplicatorConfiguration.html{Enums/ServerCertificateVerificationMode.html[serverCertificateVerificationMode enum]
// // replaces ^^
// :url-api-prop-replicator-config-AcceptOnlySelfSignedServerCertificate: https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-net}{empty}/couchbase-lite-net/api/Couchbase.Lite.Sync.ReplicatorConfiguration.html#Couchbase_Lite_Sync_ReplicatorConfiguration_setAcceptOnlySelfSignedServerCertificate-boolean-[setAcceptOnlySelfSignedServerCertificate]





// Meta API




// BEGIN Logs and logging references








// END  Logs and logging references

// End -- API References attributes

// END - Set attributes pointing to API references for this module

// END -- inclusion -- csharp:partial$_define_module_attributes.adoc

// BEGIN::module page attributes
//:source-language: csharp
// :snippet-p2psync-ws: {snippets-p2psync-ws--csharp}

// END::Local page attributes

// BEGIN -- page-inclusion -- common-database.adoc
// Applies to all platforms with some platform-specific differences


// include::ROOT:partial$_set-platform.adoc[]

[abstract]
--
Description -- _{description}_ +
Related Content -- xref:csharp:blob.adoc[Blobs] | xref:csharp:document.adoc[Documents] | xref:csharp:indexing.adoc[Indexing]
--


[discrete#csharp:database:::database-concepts]
=== Database Concepts

Databases created on Couchbase Lite can share the same hierarchical structure as Capella databases.
This makes it easier to sync data between mobile applications and applications built using Capella.

.Couchbase Lite Database Hierarchy
[plantuml]
----
@startuml


database "Database" as db

rectangle "Scope" as scope

folder "Collection" as collection



file "Document" as document1
file "Document" as document2
file "Document" as document3

db --> scope
scope --> collection
collection --> document1
collection --> document2
collection --> document3




note right of collection

  Maximum of 1000 per scope

end note

note right of db

  One database per application

end note

@enduml
----

Although the terminology is different, the structure can be mapped to relational database terms:


.Relational Database -> Couchbase
[width=70%,grid=none]
|===
|Relational database |Couchbase

|Database
|Database

|Schema
|Scope

|Table
|Collection
|===

This structure gives you plenty of choices when it comes to partitioning your data.
The most basic structure is to use the single default scope with a single default collection; or you could opt for a structure that allow you to split your collections into logical scopes.

[#cbl-database-structure]
.Couchbase Lite Examples

[plantum#csharp:database:::cbl-database-structurel]
----
@startuml


database "Couchbase Lite database" as db1 {

      node "_default scope" as dfs1 {

        folder "_default collection" as dfc1 {

        }
      }

}

database "Couchbase Lite database" as db2 {


    node "_default scope" as dfs2 {

      folder "_default collection" as dfc2 {

      }

        folder "Collection A" as collectionA {

        }
    }

    node "Scope A" as scopeA {

      folder "Collection A" as collectionA2 {

      }

        folder "Collection B" as collectionB {

        }
    }

}

collectionA2 -D[hidden]-> collectionB
collectionA -D[hidden]-> dfc2
@enduml
----


.Storing local configuration
****
You may not need to sync all the data related for a particular application. You can set up a scope that syncs data, and a second scope that doesn't.

One reason for doing this is to store local configuration data (such as the preferred screen orientation or keyboard layout). Since this information only relates to a particular device, there is no need to sync it:

[horizontal]
local data scope:: Contains information pertaining to the device.

syncing data scope:: Contains information pertaining to the user, which can be synced back to the cloud for use on the web or another device.

****

// BEGIN: Conditional Block -- applies to Android and JVM Java
// END: Conditional Block -- applies to Android and JVM Java

[discrete#csharp:database:::open-db]
=== Create or Open Database


You can create a new database and-or open an existing database, using the https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-net}{empty}/couchbase-lite-net/api/Couchbase.Lite.Database.html[Database] class.
Just pass in a database name and optionally a https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-net}{empty}/couchbase-lite-net/api/Couchbase.Lite.DatabaseConfiguration.html[DatabaseConfiguration] -- see <<csharp:database:::ex-dbopen>>.

Things to watch for include:

* If the named database does not exist in the specified, or default, location then a new one is created
* The database is created in a default location unless you  specify a directory for it -- see: https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-net}{empty}/couchbase-lite-net/api/Couchbase.Lite.DatabaseConfiguration.html[DatabaseConfiguration] and https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-net}{empty}/couchbase-lite-net/api/Couchbase.Lite.DatabaseConfiguration.html#Couchbase_Lite_DatabaseConfiguration_directory[DatabaseConfiguration.Directory()]
+
--

Typically, the default location for C#.Net is
.
a platform-dependant location:


* .NET Console: `Path.Combine(AppContext.BaseDirectory, "CouchbaseLite")` (unless the app context is altered [e.g. by XUnit], this will be the same directory as the output binary)
* WinUI: `Windows.Storage.ApplicationData.Current.LocalFolder.Path` (Inside the installed app sandbox.
Note that this sandbox gets deleted sometimes when debugging from inside Visual Studio when the app is shutdown)
* iOS: In a folder named CouchbaseLite inside of `ApplicationSupportDirectory` (this can be retrieved more easily from the simulator using the https://simpholders.com/3/[SimPholders] utility)
* Android: Using the `Context` passed in the `Activate()` method, `Context.FilesDir.AbsolutePath` (database can be retrieved using adb)


See also <<csharp:database:::lbl-find-db-loc>>.
--

[#ex-dbopen]
.Open or create a database
// BEGIN inclusion -- block -- block_tabbed_code_example.adoc
//
//  Allows for abstraction of the showing of snippet examples
//  which makes displaying tabbed snippets for platforms with
//  more than one native language to show -- Android (Kotlin and Java)
//
// Surrounds code in Example block
//
//  PARAMETERS:
//    param-tags comma-separated list of tags to include/exclude
//    param-leader text for opening para of an example block
//
//  USE:
//    :param_tags: query-access-json
//    include::partial$block_show_snippet.adoc[]
//    :param_tags!:
//

[#csharp:database:::ex-dbopen]
====


// Show Main Snippet
[source, C#]
----
include ::csharp:example$code_snippets/Program.cs[tags="new-database", indent=0]
var database = new Database("my-database");
----




// close example block

====

// Tidy-up atttibutes created
// END -- block_show_snippet.doc
// <.> Here we are specifying the database directory path.

[discrete#csharp:database:::close-database]
=== Close Database

You are advised to incorporate the closing of all open databases into your application workflow.

To close a database, use https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-net}{empty}/couchbase-lite-net/api/Couchbase.Lite.Database.html#Couchbase_Lite_Database_Close[Database.Close()] -- see: <<csharp:database:::ex-dbclose>>.
This also closes
footnote:fn28[Commencing with Release 2.8]
active replications, listeners and-or live queries connected to the database.

NOTE: Closing a database soon after starting a replication involving it can cause an exception as the asynchronous `replicator (start)` may not yet be `connected`.

.Safely Closing a Database pre 2.8
TIP: Before closing, check that any attached listeners (query/replication/change) indicate they are at least at `connected` status before closing -- see for example: xref:csharp:replication.adoc#lbl-repl-mon[Monitor Status].

.Close a Database
[#ex-dbclose]
// BEGIN inclusion -- block -- block_tabbed_code_example.adoc
//
//  Allows for abstraction of the showing of snippet examples
//  which makes displaying tabbed snippets for platforms with
//  more than one native language to show -- Android (Kotlin and Java)
//
// Surrounds code in Example block
//
//  PARAMETERS:
//    param-tags comma-separated list of tags to include/exclude
//    param-leader text for opening para of an example block
//
//  USE:
//    :param_tags: query-access-json
//    include::partial$block_show_snippet.adoc[]
//    :param_tags!:
//

[#csharp:database:::ex-dbclose]
====


// Show Main Snippet
[source, C#]
----
include ::csharp:example$code_snippets/Program.cs[tags="close-database", indent=0]
database.Close();
----




// close example block

====

// Tidy-up atttibutes created
// END -- block_show_snippet.doc

[discrete#csharp:database:::database-full-sync]
=== Database Full Sync

Database Full Sync will prevent the loss of transactional data due to an unexpected system crash or loss of power.
This feature is not enabled by default and must be manually set in your database configuration.


CAUTION: Database Full Sync is a safe method to prevent data loss but will incur a significant degredation of performance.

.Enable Database Full Sync
[#ex-dbfullsync]
// BEGIN inclusion -- block -- block_tabbed_code_example.adoc
//
//  Allows for abstraction of the showing of snippet examples
//  which makes displaying tabbed snippets for platforms with
//  more than one native language to show -- Android (Kotlin and Java)
//
// Surrounds code in Example block
//
//  PARAMETERS:
//    param-tags comma-separated list of tags to include/exclude
//    param-leader text for opening para of an example block
//
//  USE:
//    :param_tags: query-access-json
//    include::partial$block_show_snippet.adoc[]
//    :param_tags!:
//

[#csharp:database:::ex-dbfullsync]
====


// Show Main Snippet
[source, C#]
----
include ::csharp:example$code_snippets/Program.cs[tags="database-fullsync", indent=0]
// this enables fullsync
config.FullSync = true;
----




// close example block

====

// Tidy-up atttibutes created
// END -- block_show_snippet.doc

NOTE: It is not possible to change the configuration of a Database after instantiating the Database with the configuration by updating its `DatabaseConfiguration` property.

[discrete#csharp:database:::database-encryption]
=== Database Encryption



IMPORTANT: This is an https://www.couchbase.com/products/editions[Enterprise Edition] feature.


_Couchbase Lite on C#.Net_ includes the ability to encrypt Couchbase Lite databases.
This allows mobile applications to secure the data at rest, when it is being stored on the device.
The algorithm used to encrypt the database is 256-bit AES.

[discrete#csharp:database:::enabling]
==== Enabling
To enable encryption, use https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-net}{empty}/couchbase-lite-net/api/Couchbase.Lite.DatabaseConfiguration.html#Couchbase_Lite_DatabaseConfiguration_EncryptionKey[DatabaseConfiguration.EncryptionKey()] to set the encryption key of your choice.
Provide this encryption key every time the database is opened -- see <<csharp:database:::ex-sdb-encrypt>>.

.Configure Database Encryption
[#ex-sdb-encrypt]
// BEGIN inclusion -- block -- block_tabbed_code_example.adoc
//
//  Allows for abstraction of the showing of snippet examples
//  which makes displaying tabbed snippets for platforms with
//  more than one native language to show -- Android (Kotlin and Java)
//
// Surrounds code in Example block
//
//  PARAMETERS:
//    param-tags comma-separated list of tags to include/exclude
//    param-leader text for opening para of an example block
//
//  USE:
//    :param_tags: query-access-json
//    include::partial$block_show_snippet.adoc[]
//    :param_tags!:
//

[#csharp:database:::ex-sdb-encrypt]
====


// Show Main Snippet
[source, C#]
----
include ::csharp:example$code_snippets/Program.cs[tags="database-encryption", indent=0]
// Create a new, or open an existing database with encryption enabled
var config = new DatabaseConfiguration
{
    // Or, derive a key yourself and pass a byte array of the proper size
    EncryptionKey = new EncryptionKey("password")
};

using var database = new Database("seekrit", config);

// Change the encryption key (or add encryption if the DB is unencrypted)
database.ChangeEncryptionKey(new EncryptionKey("betterpassw0rd"));

// Remove encryption
database.ChangeEncryptionKey(null);
----




// close example block

====

// Tidy-up atttibutes created
// END -- block_show_snippet.doc

[discrete#csharp:database:::persisting]
==== Persisting
Couchbase Lite does not persist the key.
It is the application's responsibility to manage the key and store it in a platform-specific secure store such Android's
https://developer.android.com/training/articles/keystore[Keystore].

[discrete#csharp:database:::opening]
==== Opening
An encrypted database can only be opened with the same platform that was used to encrypt it in the first place.
So a database encrypted using the C#.Net SDK, and then exported, is readable only by the C#.Net SDK.

[discrete#csharp:database:::changing]
==== Changing
To change an existing encryption key, open the database using its existing encryption-key and use https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-net}{empty}/couchbase-lite-net/api/Couchbase.Lite.Database.html#Couchbase_Lite_Database_ChangeEncryptionKey_Couchbase_Lite_EncryptionKey_[Database.ChangeEncryptionKey()]
to set the required new encryption-key value.


[discrete#csharp:database:::removing]
==== Removing
To remove encryption, open the database using its existing encryption-key and use
https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-net}{empty}/couchbase-lite-net/api/Couchbase.Lite.Database.html#Couchbase_Lite_Database_ChangeEncryptionKey_Couchbase_Lite_EncryptionKey_[Database.ChangeEncryptionKey()]
with a null value as the encryption key.

[discrete#csharp:database:::upgrading]
==== Upgrading
To upgrade an encrypted database see: xref:csharp:dep-upgrade.adoc#lbl-db-upgrades[Upgrade 1.x databases]


[discrete#csharp:database:::lbl-find-db-loc]
=== Finding a Database File



Where a database goes by default depends on the platform it is running on.
Here are the defaults for each platform:

// tag::list-only[]

* .NET Console: `Path.Combine(AppContext.BaseDirectory, "CouchbaseLite")` (unless the app context is altered [e.g. by XUnit], this will be the same directory as the output binary)
* WinUI: `Windows.Storage.ApplicationData.Current.LocalFolder.Path` (Inside the installed app sandbox.
Note that this sandbox gets deleted sometimes when debugging from inside Visual Studio when the app is shutdown)
* iOS: In a folder named CouchbaseLite inside of `ApplicationSupportDirectory` (this can be retrieved more easily from the simulator using the https://simpholders.com/3/[SimPholders] utility)
* Android: Using the `Context` passed in the `Activate()` method, `Context.FilesDir.AbsolutePath` (database can be retrieved using adb)

// end::list-only[]


[discrete#csharp:database:::lbl-db-util]
=== Database Maintenance

From time to time it may be necessary to perform certain maintenance activities on your database, for example to
compact the database file, removing unused documents and blobs no longer referenced by any documents.

Couchbase Lite's API provides the https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-net}{empty}/couchbase-lite-net/api/Couchbase.Lite.Database.html#Couchbase_Lite_Database_PerformMaintenance-com.couchbase.lite.MaintenanceType-[Database.PerformMaintenance()] method.
The available maintenance operations, including `compact` are as shown in the enum https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-net}{empty}/couchbase-lite-net/api/Couchbase.Lite.MaintenanceType.html[MaintenanceType] to accomplish this.

This is a resource intensive operation and is not performed automatically.
It should be run on-demand using the API.
If in doubt, consult Couchbase support.


[discrete#csharp:database:::cli-tool]
=== Command Line Tool

// tag::cli-tool[]
`cblite` is a command-line tool for inspecting and querying Couchbase Lite databases.

You can download and build it from the couchbaselabs https://github.com/couchbaselabs/couchbase-mobile-tools/blob/master/README.cblite.md[GitHub repository].
Note that the `cblite` tool is not supported by the https://www.couchbase.com/support-policy[Couchbase Support Policy].

// end::cli-tool[]

[discrete#csharp:database:::troubleshooting]
=== Troubleshooting
You should use console logs as your first source of diagnostic information.
If the information in the default logging level is insufficient you can focus it on database errors and generate more verbose messages -- see: <<csharp:database:::ex-logdb>>.

For more on using Couchbase logs -- see: xref:csharp:troubleshooting-logs.adoc[Using Logs].

[#ex-logdb]
.Increase Level of Database Log Messages
// BEGIN inclusion -- block -- block_tabbed_code_example.adoc
//
//  Allows for abstraction of the showing of snippet examples
//  which makes displaying tabbed snippets for platforms with
//  more than one native language to show -- Android (Kotlin and Java)
//
// Surrounds code in Example block
//
//  PARAMETERS:
//    param-tags comma-separated list of tags to include/exclude
//    param-leader text for opening para of an example block
//
//  USE:
//    :param_tags: query-access-json
//    include::partial$block_show_snippet.adoc[]
//    :param_tags!:
//

[#csharp:database:::ex-logdb]
====


// Show Main Snippet
[source, C#]
----
include ::csharp:example$code_snippets/Program.cs[tags="console-logging-db", indent=0]
Database.Log.Console.Domains = LogDomain.Database;
----




// close example block

====

// Tidy-up atttibutes created
// END -- block_show_snippet.doc

// DO NOT DELETE
// Include standard

// :param-add3-title: {empty}
// :param-reference: reference-p2psync


[discrete#csharp:database:::related-content]
=== Related Content
++++
<div class="card-row three-column-row">
++++

[.column]
==== {empty}
.How to . . .
* xref:csharp:gs-prereqs.adoc[Prerequisites]
* xref:csharp:gs-install.adoc[Install]
* xref:csharp:gs-build.adoc[Build and Run]


.

[discrete.colum#csharp:database:::-2n]
==== {empty}
.Learn more . . .
* xref:csharp:database.adoc[Databases]
* xref:csharp:document.adoc[Documents]
* xref:csharp:blob.adoc[Blobs]
* xref:csharp:replication.adoc[Remote Sync Gateway]
* xref:csharp:conflict.adoc[Handling Data Conflicts]

.


[.column]
// [.content]
[discrete#csharp:database:::-3]
==== {empty}
.Dive Deeper . . .
//* Community
https://forums.couchbase.com/c/mobile/14[Mobile Forum] |
https://blog.couchbase.com/[Blog] |
https://docs.couchbase.com/tutorials/[Tutorials]


.



++++
</div>
++++
// [.pane__frames.cols-3]
// == Related Content

// .How-to ...

// * xref:csharp:p2psync-custom.adoc[Integrate Custom Listener]
// * xref:csharp:p2psync-websocket.adoc[Peer-to-Peer]

// .Learn more ...

// * include how-to links as relevant,
// * include how-to links as relevant,

// .Dive Deeper ...

// * Reference content
// ** https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-net}{empty}/couchbase-lite-net[API References]
// // +
// include::shared-mobile::partial$block-related-content-menulinks.adoc[tags=community]

// DO NOT DELETE

// DO NOT DELETE
// include::ROOT:partial$_unset-platform.adoc[]
// DO NOT DELETE
// END: inclusion-page - common-database.adoc[]


