:docname: fts
:page-module: csharp
:page-relative-src-path: fts.adoc
:page-origin-url: https://github.com/couchbase/docs-couchbase-lite.git
:page-origin-start-path:
:page-origin-refname: antora-assembler-simplification
:page-origin-reftype: branch
:page-origin-refhash: (worktree)
[#csharp:fts:::]
== Full Text Search
:page-aliases: learn/csharp-fts.adoc
:page-role:
:description: Couchbase Lite database data querying concepts -- full text search

// Define our environment


:version: {major}.{minor}
:vs-version: {vs-major}.{vs-minor}
:version-full: {major}.{minor}.{base}{empty}
:version-full-hyphenated: {major}-{minor}-{base}{empty}
:version-full-untagged: {major}.{minor}.{base}
:version-maintenance-android: {major}.{minor}.{maintenance-android}{empty}
:version-maintenance-c: {major}.{minor}.{maintenance-c}{empty}
:version-maintenance-net: {major}.{minor}.{maintenance-net}{empty}
:version-maintenance-java: {major}.{minor}.{maintenance-java}{empty}
:version-maintenance-ios: {major}.{minor}.{maintenance-ios}{empty}
:vs-version-maintenance-android: {vs-major}.{vs-minor}.{vs-maintenance-android}{empty}
:vs-version-maintenance-c: {vs-major}.{vs-minor}.{vs-maintenance-c}{empty}
:vs-version-maintenance-net: {vs-major}.{vs-minor}.{vs-maintenance-net}{empty}
:vs-version-maintenance-java: {vs-major}.{vs-minor}.{vs-maintenance-java}{empty}
:vs-version-maintenance-ios: {vs-major}.{vs-minor}.{vs-maintenance-ios}{empty}
:version-maintenance: {version}.{maintenance-net}{empty}
:version-maintenance-hyphenated: {major}-{minor}-{maintenance-net}{empty}
:vs-version-maintenance: {vs-version}.{vs-maintenance-net}{empty}
:vs-version-maintenance-hyphenated: {vs-major}-{vs-minor}-{vs-maintenance-net}{empty}


:version: {major}.{minor}
:vs-version: {vs-major}.{vs-minor}
:version-full: {major}.{minor}.{base}{empty}
:version-full-hyphenated: {major}-{minor}-{base}{empty}
:version-full-untagged: {major}.{minor}.{base}
:version-maintenance-android: {major}.{minor}.{maintenance-android}{empty}
:version-maintenance-c: {major}.{minor}.{maintenance-c}{empty}
:version-maintenance-net: {major}.{minor}.{maintenance-net}{empty}
:version-maintenance-java: {major}.{minor}.{maintenance-java}{empty}
:version-maintenance-ios: {major}.{minor}.{maintenance-ios}{empty}
:vs-version-maintenance-android: {vs-major}.{vs-minor}.{vs-maintenance-android}{empty}
:vs-version-maintenance-c: {vs-major}.{vs-minor}.{vs-maintenance-c}{empty}
:vs-version-maintenance-net: {vs-major}.{vs-minor}.{vs-maintenance-net}{empty}
:vs-version-maintenance-java: {vs-major}.{vs-minor}.{vs-maintenance-java}{empty}
:vs-version-maintenance-ios: {vs-major}.{vs-minor}.{vs-maintenance-ios}{empty}


// Include common page abstract block -- this is now part of
// Common Content component for this page
// :param-name: kotlin
// :param-title: Android
// :param-module: android
// :topic-group: Topic Group -- Replication
// include::ROOT:partial$_show_page_header_block.adoc[]

// Present common content including abstract and related content footer blocks
[abstract]
--
Description -- _{description}_ +
Related Content -- xref:csharp:querybuilder.adoc#lbl-predquery[Predictive Queries] | xref:csharp:indexing.adoc[Indexing] | xref:csharp:querybuilder.adoc[QueryBuilder]
--

[discrete#csharp:fts:::overview]
=== Overview
To run a full-text search (FTS) query, you must create a full-text index on the expression being matched.
Unlike regular queries, the index is not optional.

You can choose to use {sqlpp} or QueryBuilder syntaxes to create and use FTS indexes.

The following examples use the data model introduced in xref:csharp:indexing.adoc[Indexing].
They create and use an FTS index built from the hotel's `Overview` text.

[discrete#csharp:fts:::sql]
=== {sqlpp}

[discrete#csharp:fts:::create-index]
==== Create Index

{sqlpp} provides a configuration object to define Full Text Search indexes -- `FullTextIndexConfiguration`.

.Using {sqlpp}'s FullTextIndexConfiguration
[#ex-indexbuilder]


[#csharp:fts:::ex-indexbuilder]
====


// Show Main Snippet
// include::csharp:example$code_snippets/Program.cs[tags="fts-index", indent=0]
[source, C#]
----
string[] indexProperties = new string[] { "overview", "name" };
var config = new FullTextIndexConfiguration(indexProperties);
collection.CreateIndex("overviewFTSIndex", config);
----


====


[discrete#csharp:fts:::use-index]
==== Use Index

FullTextSearch is enabled using the {sqlpp} match() function.

With the index created, you can construct and run a Full-text search (FTS) query using the indexed properties.

The index will omit a set of common words, to avoid words like "I", "the", "an" from overly influencing your queries.
See https://github.com/couchbasedeps/sqlite3-unicodesn/blob/HEAD/stopwords_en.h[full list of these **stopwords**].

The following example finds all hotels mentioning _Michigan_ in their _Overview_ text.

.Using {sqlpp} Full Text Search
[#ex-indexbuilder]


[#csharp:fts:::ex-indexbuilder]
====


// Show Main Snippet
// include::csharp:example$code_snippets/Program.cs[tags="fts-query", indent=0]
[source, C#]
----
var query = collection.CreateQuery("SELECT * FROM _ WHERE MATCH(overviewFTSIndex, 'Michigan') ORDER BY RANK(overviewFTSIndex)");
foreach (var result in query.Execute()) {
    Console.WriteLine($"Document id {result.GetString(0)}");
}
----


====


[discrete#csharp:fts:::querybuilder]
=== QueryBuilder

[discrete#csharp:fts:::create-index-2]
==== Create Index
The following example creates an FTS index on the `overview` property.

.Using the IndexBuilder method
[#ex-indexbuilder-queyrbuilder]


[#csharp:fts:::ex-indexbuilder-queyrbuilder]
====


// Show Main Snippet
// include::csharp:example$code_snippets/Program.cs[tags="fts-index_Querybuilder", indent=0]
[source, C#]
----
var index = IndexBuilder.FullTextIndex(FullTextIndexItem.Property("overview")).IgnoreAccents(false);
collection.CreateIndex("overviewFTSIndex", index);
----


====


[discrete#csharp:fts:::use-index-2]
==== Use Index
With the index created, you can construct and run a Full-text search (FTS) query using the indexed properties.

The following example finds all hotels mentioning _Michigan_ in their _Overview_ text.

.Using QueryBuilder Full Text Search
[#ex-indexbuilder]


[#csharp:fts:::ex-indexbuilder]
====


// Show Main Snippet
// include::csharp:example$code_snippets/Program.cs[tags="fts-query_Querybuilder", indent=0]
[source, C#]
----
var whereClause = FullTextFunction.Match(Expression.FullTextIndex("overviewFTSIndex"), "'michigan'");

using var query = QueryBuilder.Select(SelectResult.Expression(Meta.ID))
    .From(DataSource.Collection(collection))
    .Where(whereClause);

foreach (var result in query.Execute()) {
    Console.WriteLine($"Document id {result.GetString(0)}");
}
----


====


[discrete#csharp:fts:::operation]
=== Operation

In the examples above, the pattern to match is a word, the full-text search query matches all documents that contain the word "michigan" in the value of the `doc.overview` property.

Search is supported for all languages that use whitespace to separate words.

Stemming, which is the process of fuzzy matching parts of speech, like "fast" and "faster", is supported in the following languages: Danish, Dutch, English, Finnish, French, German, Hungarian, Italian, Norwegian, Portuguese, Romanian, Russian, Spanish, Swedish and Turkish.


[discrete#csharp:fts:::pattern-matching-formats]
=== Pattern Matching Formats


As well as providing specific words or strings to match against, you can provide the pattern to match in these formats.

[discrete#csharp:fts:::prefix-queries]
==== Prefix Queries

The query expression used to search for a term prefix is the prefix itself with a "*" character appended to it.

.Prefix query
====
Query for all documents containing a term with the prefix "lin".
....
"lin*"
....

This will match

* All documents that contain "linux"
* And ... those that contain terms "linear","linker", "linguistic" and so on.
====

[discrete#csharp:fts:::overriding-the-property-name]
==== Overriding the Property Name

Normally, a token or token prefix query is matched against the document property specified as the left-hand side of the `match` operator.
This may be overridden by specifying a property name followed by a ":" character before a basic term query.
There may be space between the ":" and the term to query for, but not between the property name and the ":" character.

.Override indexed property name
====
Query the database for documents for which the term "linux" appears in the document title, and the term "problems" appears in either the title or body of the document.
....
'title:linux problems'
....
====


[discrete#csharp:fts:::phrase-queries]
==== Phrase Queries

A _phrase query_ is one that retrieves all documents containing a nominated set of terms or term prefixes in a specified order with no intervening tokens.

Phrase queries are specified by enclosing a space separated sequence of terms or term prefixes in double quotes (").

.Phrase query
====
Query for all documents that contain the phrase "linux applications".
....
"linux applications"
....
====

[discrete#csharp:fts:::near-queries]
==== NEAR Queries
A NEAR query is a query that returns documents that contain a two or more nominated terms or phrases within a specified proximity of each other (by default with 10 or less intervening terms).
A NEAR query is specified by putting the keyword "NEAR" between two phrase, token or token prefix queries.
To specify a proximity other than the default, an operator of the form "NEAR/" may be used, where is the maximum number of intervening terms allowed.

.Near query
====
Search for a document that contains the phrase "replication" and the term "database" with not more than 2 terms separating the two.
....
"database NEAR/2 replication"
....
====

[discrete#csharp:fts:::and-or-not-query-operators]
==== AND, OR & NOT Query Operators::
The enhanced query syntax supports the AND, OR and NOT binary set operators.
Each of the two operands to an operator may be a basic FTS query, or the result of another AND, OR or NOT set operation.
Operators must be entered using capital letters.
Otherwise, they are interpreted as basic term queries instead of set operators.

.Using And, Or and Not
====
Return the set of documents that contain the term "couchbase", and the term "database".
....
"couchbase AND database"
....

====

[discrete#csharp:fts:::operator-precedence]
==== Operator Precedence
When using the enhanced query syntax, parenthesis may be used to specify the precedence of the various operators.

.Operator precedence
====
Query for the set of documents that contains the term "linux", and at least one of the phrases "couchbase database" and "sqlite library".
....
'("couchbase database" OR "sqlite library") AND "linux"'
....
====

[discrete#csharp:fts:::ordering-results]
=== Ordering Results

It's very common to sort full-text results in descending order of relevance.
This can be a very difficult heuristic to define, but Couchbase Lite comes with a ranking function you can use.

In the `OrderBy` array, use a string of the form `Rank(X)`, where `X` is the property or expression being searched, to represent the ranking of the result.


[discrete#csharp:fts:::related-content]
=== Related Content
++++
<div class="card-row three-column-row">
++++

[.column]
==== {empty}
.How to . . .
* xref:csharp:querybuilder.adoc[QueryBuilder]
* xref:csharp:query-n1ql-mobile.adoc[{sqlpp} for Mobile]
* xref:csharp:query-live.adoc[Live Queries]
* xref:csharp:fts.adoc[Full Text Search]


.

[discrete.colum#csharp:fts:::-2n]
==== {empty}
.Learn more . . .
* xref:csharp:query-n1ql-mobile-querybuilder-diffs.adoc[{sqlpp} Mobile - Querybuilder  Differences]
* xref:csharp:query-n1ql-mobile-server-diffs.adoc[{sqlpp} Mobile - {sqlpp} Server Differences]
* xref:csharp:query-resultsets.adoc[Query Resultsets]
* xref:csharp:query-troubleshooting.adoc[Query Troubleshooting]
* xref:csharp:query-live.adoc[Live Queries]

* xref:csharp:database.adoc[Databases]
* xref:csharp:document.adoc[Documents]
* xref:csharp:blob.adoc[Blobs]

.


[discrete.colum#csharp:fts:::-3n]
==== {empty}
.Dive Deeper . . .
https://forums.couchbase.com/c/mobile/14[Mobile Forum] |
https://blog.couchbase.com/[Blog] |
https://docs.couchbase.com/tutorials/[Tutorials]

.


++++
</div>
++++

// Include common footer block -- this is now part of
// Common Content component for this page
// include::ROOT:partial$block-related-content-query.adoc[]


