:docname: gs-build
:page-module: csharp
:page-relative-src-path: gs-build.adoc
:page-origin-url: https://github.com/couchbase/docs-couchbase-lite.git
:page-origin-start-path:
:page-origin-refname: antora-assembler-simplification
:page-origin-reftype: branch
:page-origin-refhash: (worktree)
[#csharp:gs-build:::]
== Build and Run
:page-aliases: start/csharp-gs-build.adoc
:page-role:
:description: Build and run a starter app to validate your install of Couchbase Lite on C#
:keywords: mobile edge nosql api C# .net web-app device-app


:version: {major}.{minor}
:vs-version: {vs-major}.{vs-minor}
:version-full: {major}.{minor}.{base}{empty}
:version-full-hyphenated: {major}-{minor}-{base}{empty}
:version-full-untagged: {major}.{minor}.{base}
:version-maintenance-android: {major}.{minor}.{maintenance-android}{empty}
:version-maintenance-c: {major}.{minor}.{maintenance-c}{empty}
:version-maintenance-net: {major}.{minor}.{maintenance-net}{empty}
:version-maintenance-java: {major}.{minor}.{maintenance-java}{empty}
:version-maintenance-ios: {major}.{minor}.{maintenance-ios}{empty}
:vs-version-maintenance-android: {vs-major}.{vs-minor}.{vs-maintenance-android}{empty}
:vs-version-maintenance-c: {vs-major}.{vs-minor}.{vs-maintenance-c}{empty}
:vs-version-maintenance-net: {vs-major}.{vs-minor}.{vs-maintenance-net}{empty}
:vs-version-maintenance-java: {vs-major}.{vs-minor}.{vs-maintenance-java}{empty}
:vs-version-maintenance-ios: {vs-major}.{vs-minor}.{vs-maintenance-ios}{empty}
:version-maintenance: {version}.{maintenance-net}{empty}
:version-maintenance-hyphenated: {major}-{minor}-{maintenance-net}{empty}
:vs-version-maintenance: {vs-version}.{vs-maintenance-net}{empty}
:vs-version-maintenance-hyphenated: {vs-major}-{vs-minor}-{vs-maintenance-net}{empty}


:version: {major}.{minor}
:vs-version: {vs-major}.{vs-minor}
:version-full: {major}.{minor}.{base}{empty}
:version-full-hyphenated: {major}-{minor}-{base}{empty}
:version-full-untagged: {major}.{minor}.{base}
:version-maintenance-android: {major}.{minor}.{maintenance-android}{empty}
:version-maintenance-c: {major}.{minor}.{maintenance-c}{empty}
:version-maintenance-net: {major}.{minor}.{maintenance-net}{empty}
:version-maintenance-java: {major}.{minor}.{maintenance-java}{empty}
:version-maintenance-ios: {major}.{minor}.{maintenance-ios}{empty}
:vs-version-maintenance-android: {vs-major}.{vs-minor}.{vs-maintenance-android}{empty}
:vs-version-maintenance-c: {vs-major}.{vs-minor}.{vs-maintenance-c}{empty}
:vs-version-maintenance-net: {vs-major}.{vs-minor}.{vs-maintenance-net}{empty}
:vs-version-maintenance-java: {vs-major}.{vs-minor}.{vs-maintenance-java}{empty}
:vs-version-maintenance-ios: {vs-major}.{vs-minor}.{vs-maintenance-ios}{empty}


// DO NOT EDIT
[abstract]
--
Description -- _{description}_ +
_Abstract -- This content provides sample code and instructions that enable you to test your Couchbase Lite for csharp installation._ +
--
// include::ROOT:partial$block-related-get-started.adoc[]
// DO NOT EDIT

[discrete#csharp:gs-build:::starter-code]
=== Starter code

Open *Main.cs* in Visual Studio and copy the following code in the `main` method.
This snippet demonstrates how to run basic CRUD operations, a simple Query and running bi-directional replications with Sync Gateway.

[source, C#]
----

// using System;
// using Couchbase.Lite;
// using Couchbase.Lite.Query;
// using Couchbase.Lite.Sync;

// Get the database (and create it if it doesn't exist)
var database = new Database("mydb");
var collection = database.GetDefaultCollection();

// Create a new document (i.e. a record) in the database
var id = default(string);
using var createdDoc = new MutableDocument();
createdDoc.SetFloat("version", 2.0f)
    .SetString("type", "SDK");

// Save it to the database
collection.Save(createdDoc);
id = createdDoc.Id;

// Update a document
using var doc = collection.GetDocument(id);
using var mutableDoc = doc.ToMutable();
createdDoc.SetString("language", "C#");
collection.Save(createdDoc);

using var docAgain = collection.GetDocument(id);
Console.WriteLine($"Document ID :: {docAgain.Id}");
Console.WriteLine($"Learning {docAgain.GetString("language")}");


// Create a query to fetch documents of type SDK
// i.e. SELECT * FROM database WHERE type = "SDK"
using var query = QueryBuilder.Select(SelectResult.All())
    .From(DataSource.Collection(collection))
    .Where(Expression.Property("type").EqualTo(Expression.String("SDK")));

// Run the query
var result = query.Execute();
Console.WriteLine($"Number of rows :: {result.AllResults().Count}");

// Create replicator to push and pull changes to and from the cloud
var targetEndpoint = new URLEndpoint(new Uri("ws://localhost:4984/getting-started-db"));
var replConfig = new ReplicatorConfiguration(targetEndpoint);
replConfig.AddCollection(database.GetDefaultCollection());

// Add authentication
replConfig.Authenticator = new BasicAuthenticator("john", "pass");

// Create replicator (make sure to add an instance or static variable
// named _Replicator)
var replicator = new Replicator(replConfig);
replicator.AddChangeListener((sender, args) =>
{
    if (args.Status.Error != null) {
        Console.WriteLine($"Error :: {args.Status.Error}");
    }
});

replicator.Start();

// Later, stop and dispose the replicator *before* closing/disposing the database

----

Build and run.
You should see the document ID and property printed to the console.
The document was successfully persisted to the database.

See also -- xref:sync-gateway::get-started-install.adoc[Install Sync Gateway]

[discrete#csharp:gs-build:::building-with-vector-search]
==== Building With Vector Search

To build your Couchbase Lite application with Vector Search, you must add the following to your existing Couchbase Lite application:

. Add the Vector Search import statement
+
[source, csharp]
----

using Couchbase.Lite.Extensions;

----
+
. Load the extension.
+
[source, csharp]
----
// For Android applications
Extension.Load(new VectorSearchExtension(Context));

// For non-Android applications
Extension.Load(new VectorSearchExtension());

----

// DO NOT EDIT -- Footer Related Content Block


[discrete#csharp:gs-build:::related-content]
=== Related Content
++++
<div class="card-row three-column-row">
++++

[.column]
==== {empty}
.How to
* xref:csharp:p2psync-websocket-using-passive.adoc[Passive Peer]
* xref:csharp:p2psync-websocket-using-active.adoc[Active Peer]


.

[discrete.colum#csharp:gs-build:::-2n]
==== {empty}
.Concepts
* xref:csharp:landing-p2psync.adoc[Peer-to-Peer Sync]

* https://docs.couchbase.com/mobile/{version-maintenance-net}/couchbase-lite-net[API References]

.


[discrete.colum#csharp:gs-build:::-3n]
==== {empty}
.Community Resources ...
https://forums.couchbase.com/c/mobile/14[Mobile Forum] |
https://blog.couchbase.com/[Blog] |
https://docs.couchbase.com/tutorials/[Tutorials]

.
xref:tutorials:cbl-p2p-sync-websockets:swift/cbl-p2p-sync-websockets.adoc[Getting Started with Peer-to-Peer Synchronization]


++++
</div>
++++

// DO NOT EDIT


