:docname: p2psync-websocket-using-active
:page-module: csharp
:page-relative-src-path: p2psync-websocket-using-active.adoc
:page-origin-url: https://github.com/couchbase/docs-couchbase-lite.git
:page-origin-start-path:
:page-origin-refname: antora-assembler-simplification
:page-origin-reftype: branch
:page-origin-refhash: (worktree)
[#csharp:p2psync-websocket-using-active:::]
=== Active Peer
:page-aliases: advance/csharp-p2psync-websocket-using-active.adoc
ifdef::show_edition[:page-edition: {release}] {enterprise}
:page-role:
:description: Couchbase Lite's Peer-to-Peer Synchronization enables edge devices to synchronize securely without consuming centralized cloud-server resources

// Define our environment


:version: {major}.{minor}
:vs-version: {vs-major}.{vs-minor}
:version-full: {major}.{minor}.{base}{empty}
:version-full-hyphenated: {major}-{minor}-{base}{empty}
:version-full-untagged: {major}.{minor}.{base}
:version-maintenance-android: {major}.{minor}.{maintenance-android}{empty}
:version-maintenance-c: {major}.{minor}.{maintenance-c}{empty}
:version-maintenance-net: {major}.{minor}.{maintenance-net}{empty}
:version-maintenance-java: {major}.{minor}.{maintenance-java}{empty}
:version-maintenance-ios: {major}.{minor}.{maintenance-ios}{empty}
:vs-version-maintenance-android: {vs-major}.{vs-minor}.{vs-maintenance-android}{empty}
:vs-version-maintenance-c: {vs-major}.{vs-minor}.{vs-maintenance-c}{empty}
:vs-version-maintenance-net: {vs-major}.{vs-minor}.{vs-maintenance-net}{empty}
:vs-version-maintenance-java: {vs-major}.{vs-minor}.{vs-maintenance-java}{empty}
:vs-version-maintenance-ios: {vs-major}.{vs-minor}.{vs-maintenance-ios}{empty}
:version-maintenance: {version}.{maintenance-net}{empty}
:version-maintenance-hyphenated: {major}-{minor}-{maintenance-net}{empty}
:vs-version-maintenance: {vs-version}.{vs-maintenance-net}{empty}
:vs-version-maintenance-hyphenated: {vs-major}-{vs-minor}-{vs-maintenance-net}{empty}


:version: {major}.{minor}
:vs-version: {vs-major}.{vs-minor}
:version-full: {major}.{minor}.{base}{empty}
:version-full-hyphenated: {major}-{minor}-{base}{empty}
:version-full-untagged: {major}.{minor}.{base}
:version-maintenance-android: {major}.{minor}.{maintenance-android}{empty}
:version-maintenance-c: {major}.{minor}.{maintenance-c}{empty}
:version-maintenance-net: {major}.{minor}.{maintenance-net}{empty}
:version-maintenance-java: {major}.{minor}.{maintenance-java}{empty}
:version-maintenance-ios: {major}.{minor}.{maintenance-ios}{empty}
:vs-version-maintenance-android: {vs-major}.{vs-minor}.{vs-maintenance-android}{empty}
:vs-version-maintenance-c: {vs-major}.{vs-minor}.{vs-maintenance-c}{empty}
:vs-version-maintenance-net: {vs-major}.{vs-minor}.{vs-maintenance-net}{empty}
:vs-version-maintenance-java: {vs-major}.{vs-minor}.{vs-maintenance-java}{empty}
:vs-version-maintenance-ios: {vs-major}.{vs-minor}.{vs-maintenance-ios}{empty}


// Define page abstract
// done in commons

// Present common content including abstract and related content footer blocks
[abstract]
--
Description -- _{description}_ +
_Abstract -- How to set up a Replicator to connect with a Listener and replicate changes using peer-to-peer sync_ +
Related Content -- https://docs.couchbase.com/mobile/{version-maintenance-net}/couchbase-lite-net[API Reference]  |  xref:csharp:p2psync-websocket-using-passive.adoc[Passive Peer]  |  xref:csharp:p2psync-websocket-using-active.adoc[Active Peer]
--


.Code Snippets
[NOTE]
All code examples are indicative only.
They demonstrate the basic concepts and approaches to using a feature.
Use them as inspiration and adapt these examples to best practice when developing applications for your platform.


[discrete#csharp:p2psync-websocket-using-active:::introduction]
==== Introduction
This content provides sample code and configuration examples covering the implementation of xref:refer-glossary.adoc#peer-to-peer-sync[Peer-to-Peer Sync] over WebSockets.
Specifically it covers the implementation of an xref:refer-glossary.adoc#active-peer[Active Peer].

This _active peer_ (also referred to as a client and-or a replicator) will initiate the connection with a xref:refer-glossary.adoc#passive-peer[Passive Peer] (also referred to as a server and-or listener) and participate in the replication of database changes to bring both databases into sync.

Subsequent sections provide additional details and examples for the main configuration options.

.Secure Storage
[NOTE]
The use of TLS, its associated keys and certificates requires using secure storage to minimize the chances of a security breach.
The implementation of this storage differs from platform to platform -- see xref:csharp:p2psync-websocket.adoc#using-secure-storage[Using secure storage].


[discrete#csharp:p2psync-websocket-using-active:::configuration-summary]
==== Configuration Summary
You should configure and initialize a replicator for each Couchbase Lite database instance you want to sync.
<<csharp:p2psync-websocket-using-active:::simple-replication-to-listener>> shows the initialization and configuration process.


[#simple-replication-to-listener]
.Replication configuration and initialization


[#csharp:p2psync-websocket-using-active:::simple-replication-to-listener]
====


// Show Main Snippet
// include::csharp:example$code_snippets/Program.cs[tags="p2p-act-rep-func;!autopurge-override", indent=0]
[source, C#]
----

#warning p2p-act-rep-config-type used, but contains nothing


#warning autopurge-override used, but contains nothing

#warning p2p-act-rep-config-cont used, but contains nothing
// Configure Sync Mode


#warning p2p-act-rep-config-self-cert used, but contains nothing
// Configure Server Security -- only accept self-signed certs


// Configure Client Security // <.>

#warning p2p-act-rep-auth used, but contains nothing
// Configure basic auth using user credentials


#warning p2p-act-rep-start-full used, but contains nothing
// Initialize and start a replicator
// Initialize replicator with configuration data

#warning p2p-act-rep-add-change-listener used, but contains nothing
#warning p2p-act-rep-add-change-listener-label used, but contains nothing
//Optionally add a change listener // <.>


#warning p2p-act-rep-start used, but contains nothing
// Start replicator

----


====

<.> Configure how the client will authenticate the server.
Here we say connect only to servers presenting a self-signed certificate.
By default, clients accept only servers presenting certificates that can be verified using the OS bundled Root CA Certificates -- see: <<csharp:p2psync-websocket-using-active:::authenticate-listener>>.

<.> Configure the credentials the client will present to the server.
Here we say to provide _Basic Authentication_ credentials. Other options are available -- see: <<csharp:p2psync-websocket-using-active:::configuring-client-authentication>>.

<.> Configure how the replication should perform <<csharp:p2psync-websocket-using-active:::conflict-resolution>>.

<.> Initialize the replicator using your configuration object.

<.> Register an observer, which will notify you of changes to the replication status.

<.> Start the replicator.

[discrete#csharp:p2psync-websocket-using-active:::api-references]
==== API References

You can find https://docs.couchbase.com/mobile/{version-maintenance-net}/couchbase-lite-net[C#.Net API References] here.

[discrete#csharp:p2psync-websocket-using-active:::device-discovery]
==== Device Discovery
*This phase is optional:* If the listener is initialized on a well known URL endpoint (for example, a static IP Address or well known DNS address) then you can configure Active Peers to connect to those.

Prior to connecting with a listener you may execute a Peer discovery phase to dynamically discover Peers.


[discrete#csharp:p2psync-websocket-using-active:::configure-replicator]
==== Configure Replicator
In this section::
<<csharp:p2psync-websocket-using-active:::lbl-cfg-tgt>>
|  <<csharp:p2psync-websocket-using-active:::lbl-cfg-sync>>
|  <<csharp:p2psync-websocket-using-active:::lbl-cfg-retry>>
|  <<csharp:p2psync-websocket-using-active:::authenticate-listener>>
|  <<csharp:p2psync-websocket-using-active:::lbl-authclnt>>


[discrete#csharp:p2psync-websocket-using-active:::lbl-cfg-tgt]
===== Configure Target

Use the
Initialize and define the replication configuration with local and remote database locations using the https://docs.couchbase.com/mobile/{version-maintenance-net}/couchbase-lite-net/api/Couchbase.Lite.Sync.ReplicatorConfiguration.html[ReplicatorConfiguration] object.

The constructor provides:

* the name of the local database to be sync'd
* the server's URL (including the port number and the name of the remote database to sync with)
+
--
It is expected that the app will identify the IP address and URL and append the remote database name to the URL endpoint, producing for example: `wss://10.0.2.2:4984/travel-sample`

The URL scheme for web socket URLs uses `ws:` (non-TLS) or `wss:` (SSL/TLS) prefixes.
--

// Example 2
.Add Target to Configuration


====


// Show Main Snippet
// include::csharp:example$code_snippets/Program.cs[tags="sgw-act-rep-initialize", indent=0]
[source, C#]
----
// initialize the replicator configuration

var url = new URLEndpoint(new Uri("wss://10.0.2.2:4984/anotherDB")); // <.>
var replConfig = new ReplicatorConfiguration(url);
// Add collections to the config now

----


====

<.> Note use of the scheme prefix (`wss://`
to ensure TLS encryption -- strongly recommended in production -- or `ws://`)


[discrete#csharp:p2psync-websocket-using-active:::lbl-cfg-sync]
===== Sync Mode


Here we define the direction and type of replication we want to initiate.

We use `https://docs.couchbase.com/mobile/{version-maintenance-net}/couchbase-lite-net/api/Couchbase.Lite.Sync.ReplicatorConfiguration.html[ReplicatorConfiguration]` class's https://docs.couchbase.com/mobile/{version-maintenance-net}/couchbase-lite-net/api/Couchbase.Lite.Sync.ReplicatorConfiguration.html#Couchbase_Lite_Sync_ReplicatorConfiguration_ReplicatorType[ReplicatorType] and
`https://docs.couchbase.com/mobile/{version-maintenance-net}/couchbase-lite-net/api/Couchbase.Lite.Sync.ReplicatorConfiguration.html#Couchbase_Lite_Sync_ReplicatorConfiguration_Continuous[Continuous]` parameters, to tell the replicator:

* The type (or direction) of the replication:
`*pushAndPull*`; `pull`; `push`

* The replication mode, that is either of:

** Continuous -- remaining active indefinitely to replicate changed documents (`continuous=true`).

** Ad-hoc -- a one-shot replication of changed documents (`continuous=false`).

// Example 3
[#ex-repl-sync]
.Configure replicator type and mode


[#csharp:p2psync-websocket-using-active:::ex-repl-sync]
====


// Show Main Snippet
// include::csharp:example$code_snippets/Program.cs[tags="p2p-act-rep-config-type;p2p-act-rep-config-cont", indent=0]
[source, C#]
----

// Configure Sync Mode

----


====


[TIP]
--
Unless there is a solid use-case not to, always initiate a single `PUSH_AND_PULL` replication rather than identical separate `PUSH` and `PULL` replications.

This prevents the replications generating the same checkpoint `docID` resulting in multiple conflicts.
--


[discrete#csharp:p2psync-websocket-using-active:::lbl-cfg-retry]
===== Retry Configuration


Couchbase Lite for C#.Net's replication retry logic assures a resilient connection.

The replicator minimizes the chance and impact of dropped connections by maintaining a heartbeat; essentially pinging the listener at a configurable interval to ensure the connection remains alive.

In the event it detects a transient error, the replicator will attempt to reconnect, stopping only when the connection is re-established, or the number of retries exceeds the retry limit (9 times for a single-shot replication and unlimited for a continuous replication).

On each retry the interval between attempts is increased exponentially (exponential backoff) up to the maximum wait time limit (5 minutes).

The REST API provides configurable control over this replication retry logic using a set of configiurable properties -- see: <<csharp:p2psync-websocket-using-active:::tbl-repl-retry>>.

.Replication Retry Configuration Properties
[#csharp:p2psync-websocket-using-active:::tbl-repl-retry,cols="2,3,5"]
|===

h|Property
h|Use cases
h|Description

|https://docs.couchbase.com/mobile/{version-maintenance-net}/couchbase-lite-net/api/Couchbase.Lite.Sync.ReplicatorConfiguration.html#Couchbase_Lite_Sync_ReplicatorConfiguration_Heartbeat[Heartbeat()]
a|* Reduce to detect connection errors sooner
* Align to load-balancer or proxy `keep-alive` interval -- see Sync Gateway's topic xref:sync-gateway::load-balancer.adoc#websocket-connection[Load Balancer - Keep Alive]
a|The interval (in seconds) between the heartbeat pulses.

Default: The replicator pings the listener every 300 seconds.

|https://docs.couchbase.com/mobile/{version-maintenance-net}/couchbase-lite-net/api/Couchbase.Lite.Sync.ReplicatorConfiguration.html#Couchbase_Lite_Sync_ReplicatorConfiguration_MaxAttempts[MaxAttempts()]
|Change this to limit or extend the number of retry attempts.
a| The maximum number of retry attempts

* Set to zero (0) to use default values
* Set to zero (1) to prevent any retry attempt
* The retry attempt count is reset when the replicator is able to connect and replicate
* Default values are:
** Single-shot replication = 9;
** Continuous replication = maximum integer value
* Negative values generate a Couchbase exception `InvalidArgumentException`

|https://docs.couchbase.com/mobile/{version-maintenance-net}/couchbase-lite-net/api/Couchbase.Lite.Sync.ReplicatorConfiguration.html#Couchbase_Lite_Sync_ReplicatorConfiguration_MaxAttemptWaitTime[MaxAttemptWaitTime()]
|Change this to adjust the interval between retries.
a|The maximum interval between retry attempts

While you can configure the *maximum permitted* wait time,  the replicator's exponential backoff algorithm calculates each individual interval which is not configurable.

* Default value: 300 seconds (5 minutes)
* Zero sets the maximum interval between retries to the default of 300 seconds
* 300 sets the maximum interval between retries to the default of 300 seconds
* A negative value generates a Couchbase exception, `InvalidArgumentException`

|===

When necessary you can adjust any or all of those configurable values -- see: <<csharp:p2psync-websocket-using-active:::ex-repl-retry>> for how to do this.

.Configuring Replication Retries
[#ex-repl-retry]


[#csharp:p2psync-websocket-using-active:::ex-repl-retry]
====


// Show Main Snippet
// include::csharp:example$code_snippets/Program.cs[tags="replication-retry-config", indent=0]
[source, C#]
----
            var url = new Uri("ws://localhost:4984/mydatabase");
            var target = new URLEndpoint(url);

            var config = new ReplicatorConfiguration(target);

            //  other config as required . . .

#warning replication-set-heartbeat unused?
            config.Heartbeat = TimeSpan.FromSeconds(120); //  <.>

#warning replication-set-maxattempts unused?
            config.MaxAttempts = 20; //  <.>

#warning replication-set-maxattemptwaittime unused?
            config.MaxAttemptsWaitTime = TimeSpan.FromSeconds(600); //  <.>

            //  other config as required . . .

            var replicator = new Replicator(config);

----


====

<.> Here we use https://docs.couchbase.com/mobile/{version-maintenance-net}/couchbase-lite-net/api/Couchbase.Lite.Sync.ReplicatorConfiguration.html#Couchbase_Lite_Sync_ReplicatorConfiguration_Heartbeat[Heartbeat()] to set the required interval (in seconds) between the heartbeat pulses
<.> Here we use https://docs.couchbase.com/mobile/{version-maintenance-net}/couchbase-lite-net/api/Couchbase.Lite.Sync.ReplicatorConfiguration.html#Couchbase_Lite_Sync_ReplicatorConfiguration_MaxAttempts[MaxAttempts()] to set the required number of retry attempts
<.> Here we use https://docs.couchbase.com/mobile/{version-maintenance-net}/couchbase-lite-net/api/Couchbase.Lite.Sync.ReplicatorConfiguration.html#Couchbase_Lite_Sync_ReplicatorConfiguration_MaxAttemptWaitTime[MaxAttemptWaitTime()] to set the required interval between retry attempts.


[discrete#csharp:p2psync-websocket-using-active:::authenticate-listener]
===== Authenticating the Listener

Define the credentials the your app (the client) is expecting to receive from the server (listener) in order to ensure that the server is one it is prepared to interact with.

Note that the client cannot authenticate the server if TLS is turned off.
When TLS is enabled (Sync Gateway's default) the client _must_ authenticate the server.
If the server cannot provide acceptable credentials then the connection will fail.

Use `https://docs.couchbase.com/mobile/{version-maintenance-net}/couchbase-lite-net/api/Couchbase.Lite.Sync.ReplicatorConfiguration.html[ReplicatorConfiguration]` properties https://docs.couchbase.com/mobile/{version-maintenance-net}/couchbase-lite-net/api/Couchbase.Lite.Sync.ReplicatorConfiguration.html#Couchbase_Lite_Sync_ReplicatorConfiguration_AcceptOnlySelfSignedServerCertificate[AcceptOnlySelfSignedServerCertificate] and https://docs.couchbase.com/mobile/{version-maintenance-net}/couchbase-lite-net/api/Couchbase.Lite.Sync.ReplicatorConfiguration.html#Couchbase_Lite_Sync_ReplicatorConfiguration_PinnedServerCertificate[PinnedServerCertificate], to tell the replicator how to verify server-supplied TLS server certificates.

* If there is a pinned certificate, nothing else matters, the server cert must *exactly* match the pinned certificate.
* If there are no pinned certs and https://docs.couchbase.com/mobile/{version-maintenance-net}/couchbase-lite-net/api/Couchbase.Lite.Sync.ReplicatorConfiguration.html#Couchbase_Lite_Sync_ReplicatorConfiguration_AcceptOnlySelfSignedServerCertificate[AcceptOnlySelfSignedServerCertificate] is `true` then any self-signed certificate is accepted.  Certificates that are not self signed are rejected, no matter who signed them.
* If there are no pinned certificates and https://docs.couchbase.com/mobile/{version-maintenance-net}/couchbase-lite-net/api/Couchbase.Lite.Sync.ReplicatorConfiguration.html#Couchbase_Lite_Sync_ReplicatorConfiguration_AcceptOnlySelfSignedServerCertificate[AcceptOnlySelfSignedServerCertificate] is `false` (default), the client validates the server’s certificates against the system CA certificates.  The server must supply a chain of certificates whose root is signed by one of the certificates in the system CA bundle.

// Example 4
.Set Server TLS security
====
[tabs]
======

CA Cert::
+
--
Set the client to expect and accept only CA attested certificates.

[source, C#]
----
// Configure Server Security -- only accept CA certs
----
<.> This is the default.
Only certificate chains with roots signed by a trusted CA are allowed.
Self signed certificates are not allowed.
--


Self Signed Cert::
+
--
Set the client to expect and accept only self-signed certificates

[source, C#]
----
// Configure Server Security -- only accept self-signed certs

----
<.> Set this to `true` to accept any self signed cert.
Any certificates that are not self-signed are rejected.
--


Pinned Certificate::
+
--
Set the client to expect and accept only a pinned certificate.

[source, C#]
----
// Only CA Certs accepted
----

--

======


====


[discrete#csharp:p2psync-websocket-using-active:::lbl-authclnt]
===== Client Authentication

Here we define the credentials that the client can present to the server if prompted to do so in order that the server can authenticate it.

We use https://docs.couchbase.com/mobile/{version-maintenance-net}/couchbase-lite-net/api/Couchbase.Lite.Sync.ReplicatorConfiguration.html[ReplicatorConfiguration]'s https://docs.couchbase.com/mobile/{version-maintenance-net}/couchbase-lite-net/api/Couchbase.Lite.Sync.ReplicatorConfiguration.html#Couchbase_Lite_Sync_ReplicatorConfiguration_Authenticator[Authenticator] method to define the authentication method to the replicator.


[discrete#csharp:p2psync-websocket-using-active:::basic-authentication]
===== Basic Authentication
Use the `https://docs.couchbase.com/mobile/{version-maintenance-net}/couchbase-lite-net/api/Couchbase.Lite.Sync.BasicAuthenticator.html[BasicAuthenticator]` to supply basic authentication credentials (username and word).

// Example 5
[[csharp:p2psync-websocket-using-active:::basic-authentication]]
.Basic Authentication


[#csharp:p2psync-websocket-using-active:::basic-authentication]
====

This example shows basic authentication using user name and password:

// Show Main Snippet
// include::csharp:example$code_snippets/Program.cs[tags="p2p-act-rep-auth", indent=0]
[source, C#]
----
// Configure basic auth using user credentials

----


====


[discrete#csharp:p2psync-websocket-using-active:::certificate-authentication]
===== Certificate Authentication
Use the `https://docs.couchbase.com/mobile/{version-maintenance-net}/couchbase-lite-net/api/Couchbase.Lite.P2P.ClientCertificateAuthenticator.html[ClientCertificateAuthenticator]` to configure the client TLS certificates to be presented to the server, on connection.
This applies only to the https://docs.couchbase.com/mobile/{version-maintenance-net}/couchbase-lite-net/api/Couchbase.Lite.P2P.URLEndpointListener.html[URLEndpointListener].

NOTE: The *server* (listener) must have `disableTLS` set `false` and have a https://docs.couchbase.com/mobile/{version-maintenance-net}/couchbase-lite-net/api/Couchbase.Lite.P2P.ClientCertificateAuthenticator.html[ClientCertificateAuthenticator] configured, or it will never ask for this client's certificate.

The certificate to be presented to the server will need to be signed by the root certificates or be valid based on the authentication callback set to the listener via ListenerCertificateAuthenticator.


// Example 6
.Client Cert Authentication
[#configuring-client-authentication]


[#csharp:p2psync-websocket-using-active:::configuring-client-authentication]
====

This example shows client certificate authentication using an identity from secure storage.

// Show Main Snippet
// include::csharp:example$code_snippets/Program.cs[tags="p2p-tlsid-tlsidentity-with-label", indent=0]
[source, C#]
----
// Client identity
var identity =
  TLSIdentity.ImportIdentity(store,
    clientData,
    "123",
    "CBL-Client-Cert",
    null); // <.>

replConfig.Authenticator =
  new ClientCertificateAuthenticator(identity); // <.>

----


====

<.> Get an identity from secure storage and create a TLS Identity object
<.> Set the authenticator to https://docs.couchbase.com/mobile/{version-maintenance-net}/couchbase-lite-net/api/Couchbase.Lite.P2P.ClientCertificateAuthenticator.html[ClientCertificateAuthenticator] and configure it to use the retrieved identity


[discrete#csharp:p2psync-websocket-using-active:::initialize-replicator]
==== Initialize Replicator


Use the `https://docs.couchbase.com/mobile/{version-maintenance-net}/couchbase-lite-net/api/Couchbase.Lite.Sync.Replicator.html[Replicator]` class's https://docs.couchbase.com/mobile/{version-maintenance-net}/couchbase-lite-net/api/Couchbase.Lite.Sync.Replicator.html#Couchbase_Lite_Sync_Replicator__ctor_Couchbase_Lite_Sync_ReplicatorConfiguration_[(ReplicatorConfiguration config)] constructor, to initialize the replicator with the configuration you have defined.
You can, optionally, add a change listener (see <<csharp:p2psync-websocket-using-active:::lbl-repl-mon>>) before starting the replicator running using https://docs.couchbase.com/mobile/{version-maintenance-net}/couchbase-lite-net/api/Couchbase.Lite.Sync.Replicator.html#Couchbase_Lite_Sync_Replicator_Start[Start()].

// Example 7
.Initialize and run replicator


====


// Show Main Snippet
// include::csharp:example$code_snippets/Program.cs[tags="p2p-act-rep-start-full;!p2p-act-rep-add-change-listener", indent=0]
[source, C#]
----
// Initialize and start a replicator
// Initialize replicator with configuration data

#warning p2p-act-rep-add-change-listener used, but contains nothing

#warning p2p-act-rep-start used, but contains nothing
// Start replicator

----


====

<.> Initialize the replicator with the configuration
<.> Start the replicator

[discrete#csharp:p2psync-websocket-using-active:::lbl-repl-mon]
==== Monitor Sync


In this section::
<<csharp:p2psync-websocket-using-active:::lbl-repl-chng>>  |
<<csharp:p2psync-websocket-using-active:::lbl-repl-status>>  |
<<csharp:p2psync-websocket-using-active:::lbl-repl-evnts>> |
<<csharp:p2psync-websocket-using-active:::lbl-repl-pend>>

You can monitor a replication’s status by using a combination of <<csharp:p2psync-websocket-using-active:::lbl-repl-chng>> and the `replication.status.activity` property -- see; https://docs.couchbase.com/mobile/{version-maintenance-net}/couchbase-lite-net/api/Couchbase.Lite.Sync.ReplicatorStatus.html#Couchbase_Lite_Sync_ReplicatorStatus_Activity[Activity].
This enables you to know, for example, when the replication is actively transferring data and when it has stopped.

You can also choose to monitor document changes -- see: <<csharp:p2psync-websocket-using-active:::lbl-repl-evnts>>.

[discrete#csharp:p2psync-websocket-using-active:::lbl-repl-chng]
===== Change Listeners
Use this to monitor changes and to inform on sync progress; this is an optional step.
You can add and a replicator change listener at any point; it will report changes from the point it is registered.

.Best Practice
TIP: Don't forget to save the token so you can remove the listener later

Use the https://docs.couchbase.com/mobile/{version-maintenance-net}/couchbase-lite-net/api/Couchbase.Lite.Sync.Replicator.html[Replicator] class to add a change listener as a callback to the Replicator (https://docs.couchbase.com/mobile/{version-maintenance-net}/couchbase-lite-net/api/Couchbase.Lite.Sync.Replicator.html#Couchbase_Lite_Sync_Replicator_AddChangeListener_System_EventHandler_Couchbase_Lite_Sync_ReplicatorStatusChangedEventArgs__[addChangeListener()]) -- see: <<csharp:p2psync-websocket-using-active:::ex-repl-mon>>.
You will then be asynchronously notified of state changes.

You can remove a change listener with https://docs.couchbase.com/mobile/{version-maintenance-net}/couchbase-lite-net/api/Couchbase.Lite.Sync.Replicator.html#Couchbase_Lite_Sync_Replicator_RemoveChangeListener_Couchbase_Lite_ListenerToken_[RemoveChangeListener(ListenerToken)].


[discrete#csharp:p2psync-websocket-using-active:::lbl-repl-status]
===== Replicator Status

You can use the
https://docs.couchbase.com/mobile/{version-maintenance-net}/couchbase-lite-net/api/Couchbase.Lite.Sync.ReplicatorStatus.html[ReplicatorStatus] struct
to check the replicator status.
That is, whether it is actively transferring data or if it has stopped -- see: <<csharp:p2psync-websocket-using-active:::ex-repl-mon>>.

The returned _ReplicationStatus_ structure comprises:

* https://docs.couchbase.com/mobile/{version-maintenance-net}/couchbase-lite-net/api/Couchbase.Lite.Sync.ReplicatorStatus.html#Couchbase_Lite_Sync_ReplicatorStatus_Activity[Activity] -- stopped, offline, connecting, idle or busy -- see states described in: <<csharp:p2psync-websocket-using-active:::tbl-states>>
* https://docs.couchbase.com/mobile/{version-maintenance-net}/couchbase-lite-net/api/Couchbase.Lite.Sync.ReplicatorStatus.html#Couchbase_Lite_Sync_ReplicatorStatus_Progress[Progress]
** completed -- the total number of changes completed
** total -- the total number of changes to be processed
* https://docs.couchbase.com/mobile/{version-maintenance-net}/couchbase-lite-net/api/Couchbase.Lite.Sync.ReplicatorStatus.html#Couchbase_Lite_Sync_ReplicatorStatus_Error[Error] -- the current error, if any

// Example 8
[#csharp:p2psync-websocket-using-active:::ex-repl-mon]
[[csharp:p2psync-websocket-using-active:::ex-repl-mon]]
.Monitor replication
====


[tabs]
======

Adding a Change Listener::
+
--
[source, C#]
----

#warning p2p-act-rep-add-change-listener-label used, but contains nothing


----
--
+

Using replicator.status::
+
--
[source, C#]
----


----
--
======


====


[discrete#csharp:p2psync-websocket-using-active:::lbl-repl-states]
===== Replication States
<<csharp:p2psync-websocket-using-active:::tbl-states>> shows the different states, or activity levels, reported in the API; and the meaning of each.

.Replicator activity levels
[#csharp:p2psync-websocket-using-active:::tbl-states,cols="^1,4"]
|===
h|State
h|Meaning

|`STOPPED`
|The replication is finished or hit a fatal error.

|`OFFLINE`
|The replicator is offline as the remote host is unreachable.

|`CONNECTING`
|The replicator is connecting to the remote host.

|`IDLE`
|The replication caught up with all the changes available from the server.
The `IDLE` state is only used in continuous replications.

|`BUSY`
|The replication is actively transferring data.
|===

NOTE: The replication change object also has properties to track the progress (`change.status.completed` and `change.status.total`).
Since the replication occurs in batches the total count can vary through the course of a replication.

[discrete#csharp:p2psync-websocket-using-active:::replication-status-and-app-life-cycle]
===== Replication Status and App Life Cycle

Couchbase Lite doesn't react to OS backgrounding or foregrounding events and replication(s) will continue running as long as the remote system does not terminate the connection and the app does not terminate.
It is generally recommended to stop replications before going into the background otherwise socket connections may be closed by the OS and this may interfere with the replication process.


[#lbl-repl-evnts]

[discrete#csharp:p2psync-websocket-using-active:::lbl-repl-pend]
===== Documents Pending Push

TIP: https://docs.couchbase.com/mobile/{version-maintenance-net}/couchbase-lite-net/api/Couchbase.Lite.Sync.Replicator.html#Couchbase_Lite_Sync_Replicator_IsDocumentPending_System_String_[Replicator.IsDocumentPending()] is quicker and more efficient.
Use it in preference to returning a list of pending document IDs, where possible.

You can check whether documents are waiting to be pushed in any forthcoming sync by using either of the following API methods:

* Use the https://docs.couchbase.com/mobile/{version-maintenance-net}/couchbase-lite-net/api/Couchbase.Lite.Sync.Replicator.html#Couchbase_Lite_Sync_Replicator_GetPendingDocumentIDs[Replicator.GetPendingDocumentIDs()] method, which returns a list of document IDs that have local changes, but which have not yet been pushed to the server.
+
This can be very useful in tracking the progress of a push sync, enabling the app to provide a visual indicator to the end user on its status, or decide when it is safe to exit.

* Use the https://docs.couchbase.com/mobile/{version-maintenance-net}/couchbase-lite-net/api/Couchbase.Lite.Sync.Replicator.html#Couchbase_Lite_Sync_Replicator_IsDocumentPending_System_String_[Replicator.IsDocumentPending()] method to quickly check whether an individual document is pending a push.

[#ex-pending]
.Use Pending Document ID API


[#csharp:p2psync-websocket-using-active:::ex-pending]
====


// Show Main Snippet
// include::csharp:example$code_snippets/Program.cs[tags="replication-pendingdocuments", indent=0]
[source, C#]
----
            var url = new Uri("ws://localhost:4984/mydatabase");
            var target = new URLEndpoint(url);
            var database = new Database("myDB");
            var config = new ReplicatorConfiguration(target);
            config.AddCollection(database.GetDefaultCollection());
            config.ReplicatorType = ReplicatorType.Push;

            var replicator = new Replicator(config);

            var pendingDocIDs =
              new HashSet<string>(replicator.GetPendingDocumentIDs(database.GetDefaultCollection())); // <.>

            if (pendingDocIDs.Count > 0) {
                Console.WriteLine($"There are {pendingDocIDs.Count} documents pending");
                replicator.AddChangeListener((sender, change) =>
                {
                    Console.WriteLine($"Replicator activity level is " +
                                      change.Status.Activity.ToString());
                    // iterate and report-on previously
                    // retrieved pending docids 'list'
                    foreach (var docID in pendingDocIDs)
#warning replication-push-isdocumentpending unused?
                        if (!replicator.IsDocumentPending(docID, database.GetDefaultCollection())) // <.>
                        {
                            Console.WriteLine($"Doc ID {docID} now pushed");
                        };
                });

                replicator.Start();
            }
----


====

<.> https://docs.couchbase.com/mobile/{version-maintenance-net}/couchbase-lite-net/api/Couchbase.Lite.Sync.Replicator.html#Couchbase_Lite_Sync_Replicator_GetPendingDocumentIDs[Replicator.GetPendingDocumentIDs()] returns a list of the document IDs for all documents waiting to be pushed.
This is a snapshot and may have changed by the time the response is received and processed.
<.> https://docs.couchbase.com/mobile/{version-maintenance-net}/couchbase-lite-net/api/Couchbase.Lite.Sync.Replicator.html#Couchbase_Lite_Sync_Replicator_IsDocumentPending_System_String_[Replicator.IsDocumentPending()] returns `true` if the document is waiting to be pushed, and `false` otherwise.


[discrete#csharp:p2psync-websocket-using-active:::lbl-repl-stop]
==== Stop Sync

Stopping a replication is straightforward.
It is done using https://docs.couchbase.com/mobile/{version-maintenance-net}/couchbase-lite-net/api/Couchbase.Lite.Sync.Replicator.html#Couchbase_Lite_Sync_Replicator_Stop[Stop()].
This initiates an asynchronous operation and so is not necessarily immediate.
Your app should account for this potential delay before attempting any subsequent operations.

You can find further information on database operations in xref:csharp:database.adoc[Databases].

// Example 9
.Stop replicator


====


// Show Main Snippet
// include::csharp:example$code_snippets/Program.cs[tags="p2p-act-rep-stop", indent=0]
[source, C#]
----
// Stop replication.
----


====

<.> Here we initiate the stopping of the replication using the https://docs.couchbase.com/mobile/{version-maintenance-net}/couchbase-lite-net/api/Couchbase.Lite.Sync.Replicator.html#Couchbase_Lite_Sync_Replicator_Stop[Stop()] method.
It will stop any active <<csharp:p2psync-websocket-using-active:::lbl-repl-chng,change listener>> once the replication is stopped.


[discrete#csharp:p2psync-websocket-using-active:::conflict-resolution]
==== Conflict Resolution

Unless you specify otherwise, Couchbase Lite's default conflict resolution policy is applied -- see xref:csharp:conflict.adoc[Handling Data Conflicts].

To use a different policy, specify a _conflict resolver_ using https://docs.couchbase.com/mobile/{version-maintenance-net}/couchbase-lite-net/api/Couchbase.Lite.Sync.ReplicatorConfiguration.html#Couchbase_Lite_Sync_ReplicatorConfiguration_ConflictResolver[ConflictResolver] as shown in <<csharp:p2psync-websocket-using-active:::using-conflict-resolvers>>.

For more complex solutions you can provide a custom conflict resolver - see: xref:csharp:conflict.adoc[Handling Data Conflicts].

// Example 10
[#csharp:p2psync-websocket-using-active:::using-conflict-resolvers]
.Using conflict resolvers
====

[tabs]
=====

Local Wins::
+
--

[source, C#]
----

class LocalWinConflictResolver : IConflictResolver
{
    public Document Resolve(Conflict conflict)
    {
        return conflict.LocalDocument;
    }
}

----
--


Remote Wins::
+
--

[source, C#]
----

class RemoteWinConflictResolver : IConflictResolver
{
    public Document Resolve(Conflict conflict)
    {
        return conflict.RemoteDocument;
    }
}

----

--


Merge::
+
--

[source, C#]
----

class MergeConflictResolver : IConflictResolver
{
    public Document Resolve(Conflict conflict)
    {
        var localDict = conflict.LocalDocument.ToDictionary();
        var remoteDict = conflict.RemoteDocument.ToDictionary();
        var result = localDict.Concat(remoteDict)
           .GroupBy(kv => kv.Key)
           .ToDictionary(g => g.Key, g => g.First().Value);
        return new MutableDocument(conflict.DocumentID, result);
    }
}

----

--
=====

====

Just as a replicator may observe a conflict -- when updating a document that has changed both in the local database and in a remote database -- any attempt to save a document may also observe a conflict, if a replication has taken place since the local app retrieved the document from the database.
To address that possibility, a version of the `Database.save()` method also takes a conflict resolver as shown in <<csharp:p2psync-websocket-using-active:::ex-merge-props>>.

The following code snippet shows an example of merging properties from the existing document (`current`) into the one being saved (`new`).
In the event of conflicting keys, it will pick the key value from `new`.

.Merging document properties
[#ex-merge-props]


[#csharp:p2psync-websocket-using-active:::ex-merge-props]
====


// Show Main Snippet
// include::csharp:example$code_snippets/Program.cs[tags="update-document-with-conflict-handler", indent=0]
[source, C#]
----
using var doc = collection.GetDocument("xyz");
using var mutableDoc = doc.ToMutable();
mutableDoc.SetString("name", "apples");
collection.Save(mutableDoc, (updated, current) =>
{
    var currentDict = current.ToDictionary();
    var newDict = updated.ToDictionary();
    var result = newDict.Concat(currentDict)
        .GroupBy(kv => kv.Key)
        .ToDictionary(g => g.Key, g => g.First().Value);
    updated.SetData(result);
    return true;
});
----


====


For more on replicator conflict resolution see: xref:csharp:conflict.adoc[Handling Data Conflicts].


[discrete#csharp:p2psync-websocket-using-active:::delta-sync]
==== Delta Sync
If delta sync is enabled on the listener, then replication will use delta sync.


[discrete#csharp:p2psync-websocket-using-active:::related-content]
==== Related Content
++++
<div class="card-row three-column-row">
++++

[.column]
===== {empty}
.How to
* xref:csharp:p2psync-websocket-using-passive.adoc[Passive Peer]
* xref:csharp:p2psync-websocket-using-active.adoc[Active Peer]


.

[discrete.colum#csharp:p2psync-websocket-using-active:::-2n]
===== {empty}
.Concepts
* xref:csharp:landing-p2psync.adoc[Peer-to-Peer Sync]

* https://docs.couchbase.com/mobile/{version-maintenance-net}/couchbase-lite-net[API References]

.


[discrete.colum#csharp:p2psync-websocket-using-active:::-3n]
===== {empty}
.Community Resources ...
https://forums.couchbase.com/c/mobile/14[Mobile Forum] |
https://blog.couchbase.com/[Blog] |
https://docs.couchbase.com/tutorials/[Tutorials]

.
xref:tutorials:cbl-p2p-sync-websockets:swift/cbl-p2p-sync-websockets.adoc[Getting Started with Peer-to-Peer Synchronization]


++++
</div>
++++

// include::ROOT:partial$block-caveats.adoc[tag=enterprise-only]


