:docname: query-n1ql-mobile
:page-module: csharp
:page-relative-src-path: query-n1ql-mobile.adoc
:page-origin-url: https://github.com/couchbase/docs-couchbase-lite.git
:page-origin-start-path:
:page-origin-refname: antora-assembler-simplification
:page-origin-reftype: branch
:page-origin-refhash: (worktree)
[#csharp:query-n1ql-mobile:::]
== SQL++ for Mobile
:page-role:
:description: How to use {sqlpp} Query Strings to build effective queries with Couchbase Lite on C#
:keywords: sql, n1ql


[abstract]
--
Description -- _{description}_ +
Related Content -- xref:csharp:querybuilder.adoc#lbl-predquery[Predictive Queries] | xref:csharp:query-live.adoc[Live Queries] | xref:csharp:indexing.adoc[Indexing]
--


NOTE: The examples used in this topic are based on the _Travel Sample_ app and data introduced in the https://docs.couchbase.com/tutorials/mobile-travel-tutorial/introduction.html[Couchbase Mobile Workshop] tutorial


[#csharp:query-n1ql-mobile:::introduction]
=== Introduction

Developers using Couchbase Lite for C#.Net can provide {sqlpp} query strings using the {sqlpp} Query API.
This API uses query statements of the form shown in <<csharp:query-n1ql-mobile:::ex-query-form>>.

The structure and semantics of the query format are based on that of Couchbase Server's {sqlpp} query language -- see xref:server:n1ql:n1ql-language-reference/index.adoc[{sqlpp} Reference Guide] and xref:server:learn:data/n1ql-versus-sql.adoc[{sqlpp} Data Model].


[#csharp:query-n1ql-mobile:::running]
=== Running

The database can create a query object with the SQL++ string.
See xref:csharp:query-resultsets.adoc[Query Resultsets] for how to work with result sets.

.Running a {sqlpp} Query
[#ex-samplerun]


[#csharp:query-n1ql-mobile:::ex-samplerun]
====


// Show Main Snippet
// include::csharp:example$code_snippets/Program.cs[tags="query-syntax-n1ql", indent=0]
[source, C#]
----
using var query =
    database.CreateQuery("SELECT META().id AS thisId FROM _ WHERE type = \"hotel\""); // <.>

return query.Execute().AllResults();
----


====

We are accessing the current database using the shorthand notation *`_`* -- see the <<csharp:query-n1ql-mobile:::lbl-from>> clause for more on data source selection and <<csharp:query-n1ql-mobile:::lbl-query-params>> for more on parameterized queries.


[#csharp:query-n1ql-mobile:::query-format]
=== Query Format

The API uses query statements of the form shown in <<csharp:query-n1ql-mobile:::ex-query-form>>.

[#csharp:query-n1ql-mobile:::ex-query-form]
.Query Format
====
[source, SQL, subs="+attributes, +macros"]
----
SELECT ____
FROM 'data-source'
WHERE ____,
JOIN ____
GROUP BY ____
ORDER BY ____
LIMIT ____
OFFSET ____

----

====

Query Components::
|====
| Component | Description

| <<csharp:query-n1ql-mobile:::lbl-select>>
a| The document properties that will be returned in the result set

| <<csharp:query-n1ql-mobile:::lbl-from>>
a| The data source to be queried

 | <<csharp:query-n1ql-mobile:::lbl-where>>
a| The query criteria +
The `SELECT`ed properties of documents matching this criteria will be returned in the result set

| <<csharp:query-n1ql-mobile:::lbl-join>>
a| The criteria for joining multiple documents

| <<csharp:query-n1ql-mobile:::lbl-group>>
a| The criteria used to group returned items in the result set

| <<csharp:query-n1ql-mobile:::lbl-order>>
a| The criteria used to order the items in the result set

| <<csharp:query-n1ql-mobile:::lbl-limit>>
a| The maximum number of results to be returned

| <<csharp:query-n1ql-mobile:::lbl-offset>>
a| The number of results to be skipped before starting to return results
|====


TIP: We recommend working through the https://query-tutorial.couchbase.com/tutorial/#1[{sqlpp} Tutorials] to build your {sqlpp} skills.


[#csharp:query-n1ql-mobile:::lbl-select]
=== SELECT statement

[#csharp:query-n1ql-mobile:::purpose]
==== Purpose
Projects the result returned by the query, identifying the columns it will contain.

[#csharp:query-n1ql-mobile:::syntax]
==== Syntax

.{sqlpp} Select Syntax
====
[source, sql]
----
select = SELECT _ ( DISTINCT | ALL )? selectResult // <.>

selectResults = selectResult ( _ ',' _ selectResult )* <.>

selectResult = expression ( _ (AS)? columnAlias )? // <.>

columnAlias = IDENTIFIER
----
====

[#csharp:query-n1ql-mobile:::arguments]
==== Arguments

<.> The select clause begins with the SELECT keyword.
+
--
* The optional `ALL` argument is used to specify that the query should return ALL results (the default)
* The optional `DISTINCT` argument specifies that the query should remove duplicated results.
--

<.> selectResults is a list of columns projected in the query result.
Each column is an expression which could be a property expression or any expressions or functions.
You can use the wildcard *** to select all columns -- see <<csharp:query-n1ql-mobile:::select-wildcard>>

<.> Use the optional `AS` argument to provides an alias name for a property. Each property can be aliased by putting the `AS <alias name>` after the column name.

[#csharp:query-n1ql-mobile:::select-wildcard]
===== Select Wildcard
When using the `SELECT *` option the column name (key) of the {sqlpp} string is one of:

* The alias name if one was specified
* The data source name (or its alias if provided) as specified in the `FROM` clause.

This behavior is inline with that of Couchbase Server {sqlpp} -- see example in <<csharp:query-n1ql-mobile:::tbl-selstar>>.


.Example Column Names for SELECT ***
[#csharp:query-n1ql-mobile:::tbl-selstar,cols="3m,2m"]
|===
| Query| Column Name

| SELECT * AS data FROM _
| data

| SELECT * FROM _
| _

| SELECT * FROM _default
| _default

|SELECT * FROM db
|db

|SELECT * FROM db AS store
|store

|===


[#csharp:query-n1ql-mobile:::example]
==== Example

.SELECT properties
====
[source, sql]
----

SELECT * <.>

SELECT db.* AS data <.>

SELECT name fullName <.>

SELECT db.name fullName <.>

SELECT DISTINCT address.city <.>

----

<.> Use the `*` wildcard to select all properties
<.> Select all properties from the `db` data source. Give the object an alias name of `data`
<.> Select  pair of properties
<.> Select a specific property from the `db` data source.
<.> Select the property item `city` from its parent property `address`.

====

See: xref:csharp:query-resultsets.adoc[Query Resultsets] for more on processing query results.

[#csharp:query-n1ql-mobile:::lbl-from]
=== FROM

[#csharp:query-n1ql-mobile:::purpose-2]
==== Purpose
Specifies the data source, or sources, and optionally applies an alias ( `AS`).
It is mandatory.

[#csharp:query-n1ql-mobile:::syntax-2]
==== Syntax

[source, sql]
----
FROM dataSource  <.>
      (optional JOIN joinClause )  <.>

----

[#csharp:query-n1ql-mobile:::datasource]
==== Datasource

A datasource can be:

* < database-name > : default collection
* _ (underscore) : default collection
* < scope-name >.< collection-name > : a collection in a scope
* < collection-name > : a collection in the default scope


[#csharp:query-n1ql-mobile:::arguments-2]
==== Arguments

<.> Here `dataSource` is the database name against which the query is to run or the <scope>.<collection>.
Use `AS` to give the database an alias you can use within the query. +
To use the current datasource without specifying a name, use `_` as the datasource.

<.> `JOIN joinclause` -- use this optional argument to link datasources -- see <<csharp:query-n1ql-mobile:::lbl-join>>

[#csharp:query-n1ql-mobile:::example-2]
==== Example

.FROM clause
====
[source, sql]
----
SELECT name FROM db
SELECT name FROM scope.collection
SELECT store.name FROM db AS store
SELECT store.name FROM db store
SELECT name FROM _
SELECT store.name FROM _ AS store
SELECT store.name FROM _ store
----

====


[#csharp:query-n1ql-mobile:::lbl-join]
=== JOIN statement

[#csharp:query-n1ql-mobile:::purpose-3]
==== Purpose
The JOIN clause enables you to select data from multiple data sources linked by criteria specified in the JOIN statement.

Currently only self-joins are supported.
For example to combine airline details with route details, linked by the airline id -- see <<csharp:query-n1ql-mobile:::ex-join>>.

[#csharp:query-n1ql-mobile:::syntax-3]
==== Syntax

[source, sql]
----
joinClause = ( join )*

join = joinOperator _ dataSource _  (constraint)? <.>

joinOperator = ( LEFT (OUTER)? | INNER | CROSS )? JOIN <.>

dataSource = databaseName ( ( AS | _ )? databaseAlias )?

constraint ( ON expression )? <.>
----

[#csharp:query-n1ql-mobile:::arguments-3]
==== Arguments

<.> The join clause starts with a JOIN operator followed by the data source. +

<.> Five JOIN operators are supported: +
JOIN, LEFT JOIN, LEFT OUTER JOIN, INNER JOIN, and CROSS JOIN. +
Note: JOIN and INNER JOIN are the same, LEFT JOIN and LEFT OUTER JOIN are the same.

<.> The join constraint starts with the ON keyword followed by the expression that defines the joining constraints.

[#csharp:query-n1ql-mobile:::example-3]
==== Example

[source,sql]
----
SELECT db.prop1, other.prop2 FROM db JOIN db AS other ON db.key = other.key

SELECT db.prop1, other.prop2 FROM db LEFT JOIN db other ON db.key = other.key

SELECT * FROM route r JOIN airline a ON r.airlineid = meta(a).id WHERE a.country = "France"
----


[#csharp:query-n1ql-mobile:::ex-join]
.Using JOIN to Combine Document Details
====
This example JOINS the document of type `route` with documents of type `airline` using the document ID (`_id`) on the _airline_ document and `airlineid` on the _route_ document.

[source, sql]
----
SELECT * FROM travel-sample r JOIN travel-sample a ON r.airlineid = a.meta.id WHERE a.country = "France"

----
====

[#csharp:query-n1ql-mobile:::lbl-where]
=== WHERE statement

[#csharp:query-n1ql-mobile:::purpose-4]
==== Purpose
Specifies the selecion criteria used to filter results.

As with SQL, use the `WHERE` statement to choose which documents are returned by your query.

[#csharp:query-n1ql-mobile:::syntax-4]
==== Syntax

[source, sql]
----
where = WHERE expression <.>

----

[#csharp:query-n1ql-mobile:::arguments-4]
==== Arguments

<.> WHERE evalates `expression` to a BOOLEAN value.
You can chain any number of Expressions in order to implement sophisticated filtering capabilities.

See also -- <<csharp:query-n1ql-mobile:::lbl-operators>> for more on building expressions and <<csharp:query-n1ql-mobile:::lbl-query-params>> for more on parameterized queries.

[#csharp:query-n1ql-mobile:::examples]
==== Examples

[source, sql]
----

SELECT name FROM db WHERE department = ‘engineer’ AND group = ‘mobile

----


[#csharp:query-n1ql-mobile:::lbl-group]
=== GROUP BY statement

[#csharp:query-n1ql-mobile:::purpose-5]
==== Purpose
Use `group by` to arrange values in groups of one or more properties.

[#csharp:query-n1ql-mobile:::syntax-5]
==== Syntax

[source, sql]
----
groupBy = grouping _( having )? <.>

grouping = GROUP BY expression( _ ',' _ expression )* <.>

having = HAVING expression <.>

----

[#csharp:query-n1ql-mobile:::arguments-5]
==== Arguments
<.> The group by clause starts with the GROUP BY keyword followed by one or more expressions.

<.> Grouping
+
The group by clause is normally used together with the aggregate functions (e.g. COUNT, MAX, MIN, SUM, AVG)

<.> Having -- allows you to filter the result based on aggregate functions -- for example, `HAVING count(empnum)>100`


[#csharp:query-n1ql-mobile:::examples-2]
==== Examples

[source,sql]
----
SELECT COUNT(empno), city FROM db GROUP BY city

SELECT COUNT(empno), city FROM db GROUP BY city HAVING COUNT(empno) > 100

SELECT COUNT(empno), city FROM db GROUP BY city HAVING COUNT(empno) > 100 WHERE state = ‘CA’

----


[#csharp:query-n1ql-mobile:::lbl-order]
=== ORDER BY statement

[#csharp:query-n1ql-mobile:::purpose-6]
==== Purpose
Sort query results based on a given expression result.

[#csharp:query-n1ql-mobile:::syntax-6]
==== Syntax

[source, sql]
----
orderBy = ORDER BY ordering ( _ ',' _ ordering )* <.>

ordering = expression ( _ order )? <.>

order = ( ASC / DESC ) <.>

----

[#csharp:query-n1ql-mobile:::arguments-6]
==== Arguments

<.> orderBy -- The order by clause starts with the ORDER BY keyword followed by the ordering clause.

<.> Ordering -- The ordering clause specifies the properties or expressions to use for ordering the results.

<.> Order -- In each ordering clause, the sorting direction is specified using the optional ASC (ascending) or DESC (descending) directives. Default is ASC.


[#csharp:query-n1ql-mobile:::examples-3]
==== Examples

.Simple usage
====
[source, sql]
----
SELECT name FROM db  ORDER BY name

SELECT name FROM db  ORDER BY name DESC

SELECT name, score FROM db  ORDER BY name ASC, score DESC

----
====


[#csharp:query-n1ql-mobile:::lbl-limit]
=== LIMIT statement

[#csharp:query-n1ql-mobile:::purpose-7]
==== Purpose
Specifies the maximum number of results to be returned by the query.

[#csharp:query-n1ql-mobile:::syntax-7]
==== Syntax

[source, sql]
----
limit = LIMIT expression <.>

----

[#csharp:query-n1ql-mobile:::arguments-7]
==== Arguments

<.> The LIMIT clause starts with the LIMIT keyword followed by an expression that will be evaluated as a number.


[#csharp:query-n1ql-mobile:::examples-4]
==== Examples

.Simple usage
====
[source, sql]
----

SELECT name FROM db LIMIT 10 <.>

----
<.> Return only 10 results
====

[#csharp:query-n1ql-mobile:::lbl-offset]
=== OFFSET statement

[#csharp:query-n1ql-mobile:::purpose-8]
==== Purpose
Specifies the number of results to be skipped by the query.

[#csharp:query-n1ql-mobile:::syntax-8]
==== Syntax

[source, sql]
----
offset = OFFSET expression <.>

----

[#csharp:query-n1ql-mobile:::arguments-8]
==== Arguments

<.> The offset clause starts with the OFFSET keyword followed by an expression that will be evaluated as a number that represents the number of results ignored before the query begins returning results.

[#csharp:query-n1ql-mobile:::examples-5]
==== Examples

.Simple usage
====
[source, sql]
----

SELECT name FROM db OFFSET 10 <.>

SELECT name FROM db  LIMIT 10 OFFSET 10 <.>

----

<.> Ignore first 10 results

<.> Ignore first 10 results then return the next 10 results

====


[#csharp:query-n1ql-mobile:::lbl-literals]
=== Expressions
In this section::
  <<csharp:query-n1ql-mobile:::lbl-exp-literals>>{nbsp}{nbsp}|{nbsp}{nbsp}
  <<csharp:query-n1ql-mobile:::lbl-exp-ident>>{nbsp}{nbsp}|{nbsp}{nbsp}
  <<csharp:query-n1ql-mobile:::lbl-exp-prop>>{nbsp}{nbsp}|{nbsp}{nbsp}
  <<csharp:query-n1ql-mobile:::lbl-exp-any>>{nbsp}{nbsp}|{nbsp}{nbsp}
  <<csharp:query-n1ql-mobile:::lbl-exp-param>>{nbsp}{nbsp}|{nbsp}{nbsp}
  <<csharp:query-n1ql-mobile:::lbl-exp-paren>>

Expressions are references to identifiers that resolve to values.
Categories of expression comprise the elements covered in this section (see above), together with <<csharp:query-n1ql-mobile:::lbl-operators>> and <<csharp:query-n1ql-mobile:::lbl-functions>>, which are covered in their own sections


[#csharp:query-n1ql-mobile:::lbl-exp-literals]
==== Literals
<<csharp:query-n1ql-mobile:::lbl-lit-bool>>{nbsp}{nbsp}|{nbsp}{nbsp}
<<csharp:query-n1ql-mobile:::lbl-lit-numbers>>{nbsp}{nbsp}|{nbsp}{nbsp}
<<csharp:query-n1ql-mobile:::lbl-lit-string>>{nbsp}{nbsp}|{nbsp}{nbsp}
<<csharp:query-n1ql-mobile:::lbl-lit-null>>{nbsp}{nbsp}|{nbsp}{nbsp}
<<csharp:query-n1ql-mobile:::lbl-lit-missing>>{nbsp}{nbsp}|{nbsp}{nbsp}
<<csharp:query-n1ql-mobile:::lbl-lit-array>>{nbsp}{nbsp}|{nbsp}{nbsp}
<<csharp:query-n1ql-mobile:::lbl-lit-dict>>{nbsp}{nbsp}|{nbsp}{nbsp}


[#csharp:query-n1ql-mobile:::lbl-lit-bool]
===== Boolean

[#csharp:query-n1ql-mobile:::purpose-9]
===== Purpose
Represents a true or false value.

[#csharp:query-n1ql-mobile:::syntax-9]
===== Syntax

`TRUE | FALSE`

[#csharp:query-n1ql-mobile:::example-4]
===== Example

[source,sql]
----
SELECT value FROM db  WHERE value = true
SELECT value FROM db  WHERE value = false
----

[#csharp:query-n1ql-mobile:::lbl-lit-numbers]
===== Numeric

[#csharp:query-n1ql-mobile:::purpose-10]
===== Purpose
Represents a numeric value.
Numbers may be signed or unsigned digits.
They have optional fractional and exponent components.

[#csharp:query-n1ql-mobile:::syntax-10]
===== Syntax

[source,sql]
----
'-'? (('.' DIGIT+) | (DIGIT+ ('.' DIGIT*)?)) ( [Ee] [-+]? DIGIT+ )? WB

DIGIT = [0-9]
----

[#csharp:query-n1ql-mobile:::example-5]
===== Example

[source,sql]
----
SELECT value FROM db  WHERE value = 10
SELECT value FROM db  WHERE value = 0
SELECT value FROM db WHERE value = -10
SELECT value FROM db WHERE value = 10.25
SELECT value FROM db WHERE value = 10.25e2
SELECT value FROM db WHERE value = 10.25E2
SELECT value FROM db WHERE value = 10.25E+2
SELECT value FROM db WHERE value = 10.25E-2
----

[#csharp:query-n1ql-mobile:::lbl-lit-string]
===== String

[#csharp:query-n1ql-mobile:::purpose-11]
===== Purpose
The string literal represents a string or sequence of characters.


[#csharp:query-n1ql-mobile:::syntax-11]
===== Syntax

[source,sql]
----
“characters” |  ‘characters’ <.>
----

<.> The string literal can be double-quoted as well as single-quoted.

[#csharp:query-n1ql-mobile:::example-6]
===== Example
[source,sql]
----
SELECT firstName, lastName FROM db WHERE middleName = “middle”
SELECT firstName, lastName FROM db WHERE middleName = ‘middle’
----

[#csharp:query-n1ql-mobile:::lbl-lit-null]
===== NULL

[#csharp:query-n1ql-mobile:::purpose-12]
===== Purpose
The literal NULL represents an empty value.

[#csharp:query-n1ql-mobile:::syntax-12]
===== Syntax

[source,sql]
----
NULL
----

[#csharp:query-n1ql-mobile:::example-7]
===== Example
[source,sql]
----
SELECT firstName, lastName FROM db WHERE middleName IS NULL

----

[#csharp:query-n1ql-mobile:::lbl-lit-missing]
===== MISSING

[#csharp:query-n1ql-mobile:::purpose-13]
===== Purpose
The MISSING literal represents a missing name-value pair in a document.

[#csharp:query-n1ql-mobile:::syntax-13]
===== Syntax

[source,sql]
----
MISSING
----

[#csharp:query-n1ql-mobile:::example-8]
===== Example
[source,sql]
----
SELECT firstName, lastName FROM db WHERE middleName IS MISSING
----

[#csharp:query-n1ql-mobile:::lbl-lit-array]
===== Array

[#csharp:query-n1ql-mobile:::purpose-14]
===== Purpose
Represents an Array

[#csharp:query-n1ql-mobile:::syntax-14]
===== Syntax

[source,sql]
----
arrayLiteral = '[' _ (expression ( _ ',' _ e2:expression )* )? ']'
----

[#csharp:query-n1ql-mobile:::example-9]
===== Example
[source,sql]
----
SELECT [“a”, “b”, “c”] FROM _
SELECT [ property1, property2, property3] FROM _

----

[#csharp:query-n1ql-mobile:::lbl-lit-dict]
===== Dictionary

[#csharp:query-n1ql-mobile:::purpose-15]
===== Purpose
Represents a dictionary literal

[#csharp:query-n1ql-mobile:::syntax-15]
===== Syntax

[source,sql]
----
dictionaryLiteral = '{' _ ( STRING_LITERAL ':' e:expression
  ( _ ',' _ STRING_LITERAL ':' _ expression )* )?
   '}'

----

[#csharp:query-n1ql-mobile:::example-10]
===== Example
[source,sql]
----
SELECT { ‘name’: ‘James’, ‘department’: 10 } FROM db
SELECT { ‘name’: ‘James’, ‘department’: dept } FROM db
SELECT { ‘name’: ‘James’, ‘phones’: [‘650-100-1000’, ‘650-100-2000’] } FROM db
----


[#csharp:query-n1ql-mobile:::lbl-exp-ident]
==== Identifiers

[#csharp:query-n1ql-mobile:::purpose-16]
===== Purpose

Identifiers provide symbolic references.
Use them for example to identify: column alias names, database names, database alias names, property names, parameter names, function names, and FTS index names.

[#csharp:query-n1ql-mobile:::syntax-16]
===== Syntax

[source, sql]
----
<[a-zA-Z_] [a-zA-Z0-9_$]*> _ | "`" ( [^`] | "``"   )* "`"  _ <.>
----

<.> The identifier allows a-z, A-Z, 0-9, _ (underscore), and $ character. +
The identifier is case sensitive.

TIP: To use other characters in the identifier, surround the identifier with the backticks ` character.

[#csharp:query-n1ql-mobile:::example-11]
===== Example


.Identifiers
====

[source, sql]
----
SELECT * FROM _

SELECT * FROM `db-1` <.>

SELECT key FROM db

SELECT key$1 FROM db_1

SELECT `key-1` FROM db
----

<.> Use of backticks allows a hyphen as part of the identifier name.

====


[#csharp:query-n1ql-mobile:::lbl-exp-prop]
==== Property Expressions

[#csharp:query-n1ql-mobile:::purpose-17]
===== Purpose
The property expression is used to reference a property in a document

[#csharp:query-n1ql-mobile:::syntax-17]
===== Syntax

[source,sql]
----
property = '*'| dataSourceName '.' _ '*'  | propertyPath <.>

propertyPath = propertyName (
    ('.' _ propertyName ) |  <.>
    ('[' _ INT_LITERAL _ ']' _  ) <.>
    )* <.>

propertyName = IDENTIFIER
----
<.> Prefix the property expression with the data  source name or alias to indicate its origin

<.> Use dot syntax to refer to nested properties in the propertyPath. +
<.> Use bracket ([index]) syntax to refer to an item in an array. +
<.> Use the asterisk (*) character to represents _all properties_. This can only be used in the result list of the SELECT clause.

[#csharp:query-n1ql-mobile:::example-12]
===== Example

.Property Expressions
====
[source,sql]
----
SELECT *
  FROM db
  WHERE contact.name = "daniel"

SELECT db.*
  FROM db
  WHERE collection.contact.name = "daniel"

SELECT collection.contact.address.city
  FROM scope.collection
  WHERE collection.contact.name = "daniel"

SELECT contact.address.city
  FROM scope.collection
  WHERE contact.name = "daniel"

SELECT contact.address.city, contact.phones[0]
  FROM db
  WHERE contact.name = "daniel"

----

====

[#csharp:query-n1ql-mobile:::lbl-exp-any]
==== Any and Every Expressions

[#csharp:query-n1ql-mobile:::purpose-18]
===== Purpose
Evaluates expressions over items in an array object.


[#csharp:query-n1ql-mobile:::syntax-18]
===== Syntax

[source,sql]
----
arrayExpression = <.>
  anyEvery _ variableName <.>
     _ IN  _ expression <.>
       _ SATISFIES _ expression <.>
    END <.>

anyEvery = anyOrSome AND EVERY | anyOrSome | EVERY

anyOrSome = ANY | SOME
----

<.> The array expression starts with `ANY/SOME`, `EVERY`, or `ANY/SOME AND EVERY`, each of which has a different function as described below, and is terminated by `END`
+
--
* `ANY/SOME` : Returns `TRUE` if at least one item in the array satisfies the expression, otherwise returns `FALSE`. +
NOTE: `ANY` and `SOME` are interchangeable
* `EVERY`: Returns `TRUE` if all items in the array satisfies the expression, otherwise return `FALSE`. If the array is empty, returns `TRUE`.
* `ANY/SOME AND EVERY`: Same as `EVERY` but returns false if the array is empty.
--

<.> The variable name represents each item in the array.

<.> The IN keyword is used for specifying the array to be evaluated.

<.> The SATISFIES keyword is used for evaluating each item in the array.
<.> END terminates the array expression.

[#csharp:query-n1ql-mobile:::example-13]
===== Example

.ALL and Every Expressions
====
[source,sql]
----
SELECT name
  FROM db
  WHERE ANY v
          IN contacts
          SATISFIES v.city = ’San Mateo’
        END
----
====

[#csharp:query-n1ql-mobile:::lbl-exp-param]
==== Parameter Expressions

[#csharp:query-n1ql-mobile:::purpose-19]
===== Purpose

Parameter expressions specify a value to be assigned from the parameter map presented when executing the query.

NOTE: If parameters are specified in the query string, but the parameter and value mapping is not specified in the query object, an error will be  thrown when executing the query.

[#csharp:query-n1ql-mobile:::syntax-19]
===== Syntax

[source,sql]
----

$IDENTIFIER

----


[#csharp:query-n1ql-mobile:::examples-6]
===== Examples

.Parameter Expression
====
[source,sql]
----

SELECT name
  FROM db
  WHERE department = $department

----

====

.Using a Parameter
====

[source,java]
----

let q = Query(
          query: “SELECT name
                    WHERE department = $department”,
          database: db
        );

q.parameters =
      Parameters().setValue(“E001”, forName: "department"); // <.>

let result = q.execute();

----

<.> The query resolves to
`SELECT name WHERE department = "E001"`

====


[#csharp:query-n1ql-mobile:::lbl-exp-paren]
==== Parenthesis Expressions

[#csharp:query-n1ql-mobile:::purpose-20]
===== Purpose

Use parentheses to group expressions together to make them more readable or to establish operator precedences.

[#csharp:query-n1ql-mobile:::example-14]
===== Example

.Parenthesis Expression
====

[source, sql]
----
SELECT (value1 + value2) * value 3 // <.>
  FROM db

SELECT *
  FROM db
  WHERE ((value1 + value2) * value3) + value4 = 10

SELECT *
  FROM db
  WHERE (value1 = value2)
     OR (value3 = value4) // <.>
----

<.> Establish the desired operator precedence; do the addition *before* the multiplication

<.> Clarify the conditional grouping

====


[#csharp:query-n1ql-mobile:::lbl-operators]
=== Operators
In this section::
<<csharp:query-n1ql-mobile:::lbl-ops-binary>>{nbsp}{nbsp}|{nbsp}{nbsp}
<<csharp:query-n1ql-mobile:::lbl-ops-unary>>{nbsp}{nbsp}|{nbsp}{nbsp}
<<csharp:query-n1ql-mobile:::lbl-ops-coll>>{nbsp}{nbsp}|{nbsp}{nbsp}
<<csharp:query-n1ql-mobile:::lbl-ops-cond>>


[#csharp:query-n1ql-mobile:::lbl-ops-binary]
==== Binary Operators
<<csharp:query-n1ql-mobile:::lbl-ops-maths>>{nbsp}{nbsp}|{nbsp}{nbsp}
<<csharp:query-n1ql-mobile:::lbl-comp-ops>>{nbsp}{nbsp}|{nbsp}{nbsp}
<<csharp:query-n1ql-mobile:::lbl-ops-logical>>{nbsp}{nbsp}|{nbsp}{nbsp}
<<csharp:query-n1ql-mobile:::lbl-ops-string>>


[#csharp:query-n1ql-mobile:::lbl-ops-maths]
===== Maths

.Maths Operators
[ops-maths, cols="^1m,2,2m", options="header"]
|===

|Op
|Desc
|Example

|+
|Add
|WHERE v1 + v2 = 10

|-
|Subtract
|WHERE v1 - v2 = 10

|*
|Multiply
|WHERE v1 * v2 = 10

|/
|Divide -- see note ^1^

|WHERE v1 / v2 = 10

|%
|Modulo
|WHERE v1 % v2 = 0

|===

^1^ If both operands are integers, integer division is  used, but if one is a floating number, then float division is used.
This differs from Server {sqlpp}, which performs float division regardless. Use `DIV(x, y)` to force float division in CBL {sqlpp}

[#csharp:query-n1ql-mobile:::lbl-comp-ops]
===== Comparison Operators

[#csharp:query-n1ql-mobile:::purpose-21]
===== Purpose
The _comparison operators_ are used in the WHERE statement to specify the condition on which to match documents.

.Comparison Operators
[#tbl-ops-comp]
[ops-com#csharp:query-n1ql-mobile:::tbl-ops-compp, cols="^1m,2,2m", options="header"]
|===

|Op
|Desc
|Example

a|`=` or `==`
|Equals
|WHERE v1 = v2 +
WHERE v1 == v2

a|`!=` or `<>`
|Not Equal to
|WHERE v1 != v2 +
WHERE v1 <> v2

|>
|Greater than
|WHERE v1 > v2

|>=
|Greater than or equal to
|WHERE v1 >= v2

|>
|Less than
|WHERE v1 < v2

|>=
|Less than or equal to
|WHERE v1 <= v2

|IN
|Returns TRUE if the value is in the list or array of values specified by the right hand side expression; Otherwise returns FALSE.
|WHERE “James” IN contactsList

|LIKE
a|String wildcard pattern matching ^2^ comparison.
Two wildcards are supported:

* `%` Matches zero or more characters. +
* `_` Matches a single character.


|WHERE name LIKE 'a%' +
WHERE name LIKE '%a' +
WHERE name LIKE '%or%'‘ +
WHERE name LIKE 'a%o%' +
WHERE name LIKE '%\_r%' +
WHERE name LIKE '%a_%' +
WHERE name LIKE '%a__%' +
WHERE name LIKE 'aldo'


|MATCH
|String matching using FTS see <<csharp:query-n1ql-mobile:::lbl-func-fts>>
|WHERE v1-index MATCH "value"

|BETWEEN
|Logically equivalent to v1>=X and v1<=X+z
|WHERE v1 BETWEEN 10 and 100

|IS ^3^ NULL
|Equal to null
|WHERE v1 IS NULL

|IS NOT NULL
|Not equal to null
|WHERE v1 IS NOT NULL

|IS MISSING
|Equal to MISSING
|WHERE v1 IS MISSING

|IS NOT MISSING
|Not equal to MISSING
|WHERE v1 IS NOT MISSING

|IS VALUED
|IS NOT NULL AND MISSING
|WHERE v1 IS VALUED

|IS NOT VALUED
|IS NULL OR MISSING
|WHERE v1 IS NOT VALUED


|===

^2^ Matching is case-insensitive for ASCII characters, case-sensitive for non-ASCII.


^3^ Use of `IS` and `IS NOT` is limited to comparing `NULL` and `MISSING` values (this encompasses `VALUED`).
This is different from QueryBuilder, in which they operate as equivalents of `==` and `!=`.

.Comparing NULL and MISSING values using IS.
[#tbl-ops-isnot]
[ops-com#csharp:query-n1ql-mobile:::tbl-ops-isnotp, cols="^1,^1,^1,^1", options="header"]
|===

|OP
|NON-NULL Value
|NULL
|MISSING

|IS NULL
|FALSE
|TRUE
|MISSING

|IS NOT NULL
|TRUE
|FALSE
|MISSING

|IS MISSING
|FALSE
|FALSE
|TRUE

|IS NOT MISSING
|TRUE
|TRUE
|FALSE

|IS VALUED
|TRUE
|FALSE
|FALSE

|IS NOT VALUED
|FALSE
|TRUE
|TRUE

|===


[#csharp:query-n1ql-mobile:::lbl-ops-logical]
===== Logical Operators

[#csharp:query-n1ql-mobile:::purpose-22]
===== Purpose
Logical operators combine expressions using the following Boolean Logic Rules:

* TRUE is TRUE, and FALSE is FALSE
* Numbers 0 or 0.0 are FALSE
* Arrays and dictionaries are FALSE
* String and Blob are TRUE if the values are casted as a non-zero or FALSE if the values are casted as 0 or 0.0
* NULL is FALSE
* MISSING is MISSING

[NOTE]
--
This is different from Server {sqlpp}, where:

* MISSING, NULL and FALSE are FALSE
* Numbers 0 is FALSE
* Empty strings, arrays, and objects are FALSE
* All other values are TRUE

TIP: Use TOBOOLEAN(expr) function to convert a value based on Server {sqlpp} boolean value rules,
--

.Logical Operators
[#tbl-ops-logical]
[ops-com#csharp:query-n1ql-mobile:::tbl-ops-logicalp, cols="^1m,2,2m", options="header"]
|===

|Op
|Description
|Example

|AND
|Returns TRUE if the operand expressions evaluate to TRUE; otherwise FALSE.

If an operand is MISSING and the other is TRUE returns MISSING, if the other operand is FALSE it returns FALSE.

If an operand is NULL and the other is TRUE returns NULL, if the other operand is FALSE it returns FALSE.

|WHERE city = “San Francisco” AND status = true


|OR
|Returns TRUE if one of the operand expressions is evaluated to TRUE; otherwise returns FALSE.

If an operand is MISSING, the operation will result in MISSING if the other operand is FALSE or TRUE if the other operand is TRUE.

If an operand is NULL, the operation will result in NULL if the other operand is FALSE or TRUE if the other operand is TRUE.

|WHERE city = “San Francisco” OR city = “Santa Clara”


|===

.Logical Operation Table
[tbl-ops-logtbl,cols="1,1,1,1", options="header"]
|===

|a
|b
|a AND b
|a OR b

.4+|TRUE

|TRUE
|TRUE
|TRUE

|FALSE
|FALSE
|TRUE

|NULL
|FALSE	^5-1^
|TRUE

|MISSING
|MISSING
|TRUE

.4+|FALSE

|TRUE
|FALSE
|TRUE

|FALSE
|FALSE
|FALSE

|NULL
|FALSE
|FALSE ^5-1^

|MISSING
|FALSE
|MISSING

.4+|NULL

|TRUE
|FALSE ^5-1^
|TRUE

|FALSE
|FALSE
|FALSE ^5-1^

|NULL
|FALSE ^5-1^
|FALSE ^5-1^

|MISSING
|FALSE  ^5-2^
|MISSING  ^5-3^

.4+|MISSING

|TRUE
|MISSING
|TRUE

|FALSE
|FALSE
|MISSING

|NULL
|FALSE  ^5-2^
|MISSING  ^5-3^

|MISSING
|MISSING
|MISSING

|===

[NOTE]
This differs from Server {sqlpp} in the following instances: +
 ^5-1^ Server will return: NULL instead of FALSE +
 ^5-2^ Server will return: MISSING instead of FALSE +
 ^5-3^ Server will return: NULL instead of MISSING +


[#csharp:query-n1ql-mobile:::lbl-ops-string]
===== String Operator

[#csharp:query-n1ql-mobile:::purpose-23]
===== Purpose
A single string operator is provided.
It enables string concatenation.

.String Operators
[#tbl-ops-logical]
[ops-com#csharp:query-n1ql-mobile:::tbl-ops-logicalp, cols="^1m,2,2m", options="header"]
|===

|Op
|Description
|Example

a|`\|\|`
|Concatenating
|SELECT firstnm \|\| lastnm AS fullname FROM db

|===


[#csharp:query-n1ql-mobile:::lbl-ops-unary]
==== Unary Operators

[#csharp:query-n1ql-mobile:::purpose-24]
===== Purpose
Three unary operators are provided.
They operate by modifying an expression, making it numerically positive or negative, or by logically negating its value (TRUE becomes FALSE).

[#csharp:query-n1ql-mobile:::syntax-20]
===== Syntax

[source]
----

----

.Unary Operators
[#tbl-ops-logical]
[ops-com#csharp:query-n1ql-mobile:::tbl-ops-logicalp, cols="^1m,2,2m", options="header"]
|===

|Op
|Description
|Example

|+
|Positive value
|WHERE v1 = +10

|+
|Negative value
|WHERE v1 = -10

|NOT
|Logical Negate operator ^*^
|WHERE "James" NOT IN contactsList

|===

^*^ The NOT operator is often used in conjunction with operators such as IN, LIKE, MATCH, and BETWEEN operators. +
NOT operation on NULL value returns NULL. +
NOT operation on MISSING value returns MISSING.

.NOT Operation TABLE
[tbl-ops-not,cols="^1,^1", options="header"]
|===

|a
|NOT a

|TRUE
|FALSE

|FALSE
|TRUE

|NULL
|FALSE

|MISSING
|MISSING
|===


[#csharp:query-n1ql-mobile:::lbl-ops-coll]
==== COLLATE Operators

[#csharp:query-n1ql-mobile:::purpose-25]
===== Purpose
Collate operators specify how the string comparison is conducted.

[#csharp:query-n1ql-mobile:::usage]
===== Usage
The collate operator is used in conjunction with string comparison expressions and ORDER BY clauses.
It allows for one or more collations.

If multiple collations are used, the collations need to be specified in a parenthesis. When only one collation is used, the parenthesis is optional.

NOTE: Collate is not supported by Server {sqlpp}

[#csharp:query-n1ql-mobile:::syntax-21]
===== Syntax

[source, sql]
----
collate = COLLATE collation | '(' collation (_ collation )* ')'

collation = NO? (UNICODE | CASE | DIACRITICS) WB <.>
----

[#csharp:query-n1ql-mobile:::arguments-9]
===== Arguments

<.> The available collation options are:
+
--
* UNICODE: Conduct a Unicode comparison; the default is to do ASCII comparison.
* CASE: Conduct case-sensitive comparison
* DIACRITIC: Take account of accents and diacritics in the comparison; On by default.
* NO: This can be used as a prefix to the other collations, to disable them (for example: `NOCASE` to enable case-insensitive comparison)

--

[#csharp:query-n1ql-mobile:::example-15]
===== Example

[source, sql]
----
SELECT department FROM db WHERE (name = "fred") COLLATE UNICODE

----


[source, sql]
----
SELECT department FROM db WHERE (name = "fred")
COLLATE (UNICODE)
----


[source, sql]
----
SELECT department FROM db WHERE (name = "fred") COLLATE (UNICODE CASE)

----


[source, sql]
----
SELECT name FROM db ORDER BY name COLLATE (UNICODE DIACRITIC)

----


[#csharp:query-n1ql-mobile:::lbl-ops-cond]
==== CONDITIONAL Operator

[#csharp:query-n1ql-mobile:::purpose-26]
===== Purpose

The Conditional (or `CASE`) operator evaluates conditional logic in a similar way to the IF/ELSE operator.

[#csharp:query-n1ql-mobile:::syntax-22]
===== Syntax

[source,sql]
----
CASE (expression) (WHEN expression THEN expression)+ (ELSE expression)? END <.>

CASE (expression)? (!WHEN expression)?
  (WHEN expression THEN expression)+ (ELSE expression)? END <.>
----

Both _Simple Case_ and _Searched Case_ expressions are supported.
The syntactic difference being that the _Simple Case_ expression has an expression after the CASE keyword.

<.> Simple Case Expression
+
--
* If the CASE expression is equal to the first WHEN expression, the result is the THEN expression.
* Otherwise, any subsequent WHEN clauses are evaluated in the same way.
* If no match is found, the result of the CASE expression is the ELSE expression, NULL if no ELSE expression was provided.
--

<.> Searched Case Expression
+
--
* If the first WHEN expression is TRUE, the result of this expression is its THEN expression.
* Otherwise, subsequent WHEN clauses are evaluated in the same way.
If no WHEN clause evaluate to TRUE, then the result of the expression is the ELSE expression, or NULL if no ELSE expression was provided.
--

[#csharp:query-n1ql-mobile:::example-16]
===== Example

.Simple Case
====
[source,sql]
----
SELECT CASE state WHEN ‘CA’ THEN ‘Local’ ELSE ‘Non-Local’ END FROM DB
----

====

.Searched Case
====

[source,sql]
----

SELECT CASE WHEN shippedOn IS NOT NULL THEN ‘SHIPPED’ ELSE "NOT-SHIPPED" END FROM db

----

====


[#csharp:query-n1ql-mobile:::lbl-functions]
=== Functions
In this section::
<<csharp:query-n1ql-mobile:::lbl-func-agg>>{nbsp}{nbsp}|{nbsp}{nbsp}
<<csharp:query-n1ql-mobile:::lbl-func-array>>{nbsp}{nbsp}|{nbsp}{nbsp}
<<csharp:query-n1ql-mobile:::lbl-func-cond>>{nbsp}{nbsp}|{nbsp}{nbsp}
<<csharp:query-n1ql-mobile:::lbl-func-date>>{nbsp}{nbsp}|{nbsp}{nbsp}
<<csharp:query-n1ql-mobile:::lbl-func-fts>>{nbsp}{nbsp}|{nbsp}{nbsp}
<<csharp:query-n1ql-mobile:::lbl-func-maths>>{nbsp}{nbsp}|{nbsp}{nbsp}
<<csharp:query-n1ql-mobile:::lbl-func-meta>>{nbsp}{nbsp}|{nbsp}{nbsp}
<<csharp:query-n1ql-mobile:::lbl-func-pattern>>{nbsp}{nbsp}|{nbsp}{nbsp}
<<csharp:query-n1ql-mobile:::lbl-func-string>>{nbsp}{nbsp}|{nbsp}{nbsp}
<<csharp:query-n1ql-mobile:::lbl-func-typecheck>>{nbsp}{nbsp}|{nbsp}{nbsp}
<<csharp:query-n1ql-mobile:::lbl-func-typeconv>>

[#csharp:query-n1ql-mobile:::purpose-27]
==== Purpose

Functions are also expressions.

[#csharp:query-n1ql-mobile:::syntax-23]
==== Syntax
The function syntax is the same as Java’s method syntax.
It starts with the function name, followed by optional arguments inside parentheses.

[source, sql]
----
function = functionName parenExprs

functionName  = IDENTIFIER

parenExprs = '(' ( expression (_ ',' _ expression )* )? ')'

----


[#csharp:query-n1ql-mobile:::lbl-func-agg]
==== Aggregation Functions

.Aggregation Functions
[tbl-func-agg,cols="1m,4", options="header"]
|===

|Function
|Description

|AVG(expr)
|Returns average value of the number values in the group

|COUNT(expr)
|Returns a count of all values in the group

|MIN(expr)
|Returns the minimum value in the group

|MAX(expr)
|Returns the maximum value in the group

|SUM(expr)
|Returns the sum of all number values in the group

|===

[#csharp:query-n1ql-mobile:::lbl-func-array]
==== Array Functions

.Array Functions
[tbl-func-agg,cols="1m,4", options="header"]
|===

|Function
|Description

|ARRAY_AGG(expr)
|Returns an array of the non-MISSING group values in the input expression, including NULL values.

|ARRAY_AVG(expr)
|Returns the average of all non-NULL number values in the array; or NULL if there are none

|ARRAY_CONTAINS(expr)
|Returns TRUE if the value exists in the array; otherwise FALSE

|ARRAY_COUNT(expr)
|Returns the number of non-null values in the array

|ARRAY_IFNULL(expr)
|Returns the first non-null value in the array

|ARRAY_MAX(expr)
|Returns the largest non-NULL, non_MISSING value in the array

|ARRAY_MIN(expr)
|Returns the smallest non-NULL, non_MISSING value in the array

|ARRAY_LENGTH(expr)
|Returns the length of the array

|ARRAY_SUM(expr)
|Returns the sum of all non-NULL numeric value in the array
|

|===

[#csharp:query-n1ql-mobile:::lbl-func-cond]
==== Conditional Functions

.Conditional Functions
[tbl-func-agg,cols="2m,3", options="header"]
|===

|Function
|Description

|IFMISSING(expr1, expr2, ...)
|Returns the first non-MISSING value, or NULL if all values are MISSING

|IFMISSINGRONULL(expr1, expr2, ...)
|Returns the first non-NULL and non-MISSING value, or NULL if all values are NULL or MISSING

|IFNULL(expr1, expr2, ...)
|Returns the first non-NULL, or NULL if all values are NULL

|MISSINGIF(expr1, expr2)
|Returns `MISSING` when `expr1 = expr2`; otherwise returns `expr1`. +
Returns `MISSING` if either or both expressions are `MISSING`. +
Returns `NULL` if either or both expressions are `NULL`.+

|NULLF(expr1, expr2)
|Returns `NULL` when `expr1 = expr2`; otherwise returns `expr1`. +
Returns `MISSING` if either or both expressions are `MISSING`. +
Returns `NULL` if either or both expressions are `NULL`.+

|===


[#csharp:query-n1ql-mobile:::lbl-func-date]
==== Date and Time Functions

.Date and Time Functions
[cols="3*", options="header"]
|===

|Function |Arguments |Return Value

a|`STR_TO_MILLIS(date1)`::
Coverts a date string to Epoch/UNIX milliseconds.

a|

* `date1` -  A valid date string.

|Returns an integer containing the converted date string into Epoch/UNIX milliseconds.


a|`STR_TO_UTC(date1)`::
Converts a date string into the equivalent date in UTC.

a|

* `date1` - A valid date string

|Returns a date string representing the date string converted to UTC.

The output date format follows the date format of the input date.
Returns `null` if an invalid  date format is provided.


a|`STR_TO_TZ(date1, tz)`::
Converts a date string to it's equivalent in the specified timezone.

a|

* `date1` -  A valid date string.
This is converted to UTC.
* `tz` -  An integer that represents minutes offset from UTC.
For example, `UTC-5` would be represented as `-300`.

|Returns a date string representing the date string converted to the specified timezone.

Returns `null` if an invalid  date format is provided.


a|`MILLIS_TO_STR(date1)`::
Converts an Epoch/UNIX timestamp into the specified date string format.

a|

* `date1` -  An integer representing an Epoch/UNIX timestamp in millseconds.

|Returns a date string representing the local date.

Returns null if an invalid timestamp is provided.


a|`MILLIS_TO_UTC(date1)`::
Converts an Epoch/UNIX timestamp into a local time date string.

a|

* `date1` -  An integer representing an Epoch/UNIX timestamp in millseconds.

|Returns a date string representing the date in UTC.

Returns null if an invalid timestamp is provided.


a|`MILLIS_TO_TZ(date1,tz, [fmt])`::
Converts an Epoch/UNIX timestamp into the specified time zone in the specified date string format.

a|

* `date1` -  An integer representing an Epoch/UNIX timestamp in milliseconds.
* `tz` -  An integer that represents minutes offset from UTC.
For example, `UTC-5` would be represented as `-300`.
* `fmt` -  An optional string parameter representing a date format to output the result as.

|Returns a date string representing the date in the specified timezone in the specified format.

If `fmt` is not specified, the output default to the combined full date and time.


a|`DATE_DIFF_STR(date1, date2, part)`::
Finds the elapsed time between two date strings.
This is measured from `date2` to `date1`.

a|

* `date1` -  A valid date string.
This is converted to UTC.
* `date2` -  A valid date string.
This is converted to UTC.
* `part` -  A string representing the date component units to return.

a|Returns an integer representing the elapsed time measured from `date2` to  `date1` (in units based on the specified `part`) between both dates.

The value is positive if `date1` is greater than `date2`, negative otherwise.

Returns null if any of the parameters are invalid.


a|`DATE_DIFF_MILLIS(date1, date2, part)`::
Finds the elapsed time between two Epoch/UNIX timestamps.

a|

* `date1` -  An integer representing an Epoch/UNIX timestamp in milliseconds.
* `date2` -  An integer representing an Epoch/UNIX timestamp in milliseconds.
* `part` -  A string representing the date component units to return.

a|Returns an integer representing the elapsed time  measured from `date2` to  `date1` (in units based on the specified `part`) between both dates.

The value is positive if `date1` is greater than `date2`, negative otherwise.

Returns null if any of the parameters are invalid.


a|`DATE_ADD_STR(date1, n, part)`::
Performs date arithmetic on a date string.
For example `DATE_ADD_STR("2024-03-20T15:43:01+0000", 3, "day")` adds 3 days to the provided date.

a|

* `date1` -  A valid date string.
This is converted to UTC.
* `n` -  An integer or expression that evaluates to an integer.
A positive value will increment the date component whereas a negative value will decrement the date component.
* `part` -  A string representing the component of the date to increment.

|Returns an integer representing the calculation result as an Epoch/UNIX timestamp in milliseconds.

Returns null if any of the parameters are invalid.


a|`DATE_ADD_MILLIS(date1, n, part)`::
Performs date arithmetic on a particular component of an Epoch/UNIX timestamp value.
For example `DATE_ADD_STR(1710946158819, 3, 'day')` adds 3 days to the provided date.

a|

* `date1` -  An integer representing an Epoch/UNIX timestamp in milliseconds.
* `n` -  An integer or expression that evaluates to an integer.
A positive value will increment the date component whereas a negative value will decrement the date component.
* `part` -  A string representing the component of the date to increment.

a|Returns an integer representing the calculation result as an Epoch/UNIX timestamp in milliseconds.

Returns null if any of the parameters are invalid.

|===


[#csharp:query-n1ql-mobile:::lbl-func-fts]
==== Full Text Search Functions

.FTS Functions
[tbl-func-fts,cols="1m,2,2m", options="header"]
|===

|Function
|Description
|Example

|MATCH(indexName, term)
|Returns `TRUE` if `term` expression matches the FTS indexed term. `indexName` identifies the FTS index, `term` expression to search for matching.
|WHERE MATCH (description, “couchbase”)

|RANK(indexName)
|Returns a numeric value indicating how well the current query result matches the full-text query when performing the `MATCH`. `indexName` is an IDENTIFIER for the FTS index.
|WHERE MATCH (description, “couchbase”) ORDER BY RANK(description)


|===


[#csharp:query-n1ql-mobile:::lbl-func-maths]
==== Maths Functions

.Maths Functions
[tbl-func-maths,cols="1m,4", options="header"]
|===

|Function
|Description

|ABS(expr)
|Returns the absolute value of a number.

|ACOS(expr)
|Returns the arc cosine in radians.

|ASIN(expr)
|Returns the arcsine in radians.

|ATAN(expr)
|Returns the arctangent in radians.

|ATAN2(expr1,expr2)
|Returns the arctangent of expr1/expr2.

|CEIL(expr)
|Returns the smallest integer not less than the number.

|COS(expr)
|Returns the cosine value of the expression.

|DIV(expr1, expr2)
|Returns float division of expr1 and expr2. +
Both expr1 and expr2 are cast to a double number before division. +
The returned result is always a double.

|DEGREES(expr)
|Converts radians to degrees.

|E()
|Returns base of natural logarithms.

|EXP(expr)
|Returns expr value

|FLOOR(expr)
|Returns largest integer not greater than the number.

|IDIV(expr1, expr2)
|Returns integer division of expr1 and expr2.

|LN(expr)
|Returns log base e value.

|LOG(expr)
|Returns log base 10 value.

|PI()
|Return PI value.

|POWER(expr1, expr2)
|Returns expr1expr2 value.

|RADIANS(expr)
|Returns degrees to radians.

|ROUND(expr (, digits_expr)?)
|Returns the rounded value to the given number of integer digits to the right of the decimal point (left if digits is negative). Digits are 0 if not given. +
The function uses `Rounding Away From Zero` convention to round midpoint values to the next number away from zero (so, for example, `ROUND(1.75)` returns 1.8 but `ROUND(1.85)` returns 1.9. ^*^


|ROUND_EVEN(expr (, digits_expr)?)
|Returns rounded value to the given number of integer digits to the right of the decimal point (left if digits is negative). Digits are 0 if not given.

The function uses _Rounding to Nearest Even_ (Banker’s Rounding) convention which rounds midpoint values to the nearest even number (for example, both `ROUND_EVEN(1.75)` and `ROUND_EVEN(1.85)` return 1.8).

|SIGN(expr)
|Returns -1 for negative, 0 for zero, and 1 for positive numbers.

|SIN(expr)
|Returns sine value.

|SQRT(expr)
|Returns square root value.

|TAN(expr)
|Returns tangent value.

|TRUNC (expr (, digits, expr)?)
|Returns a truncated number to the given number of integer digits to the right of the decimal point (left if digits is negative). Digits are 0 if not given.

|===

^*^ The behavior of the ROUND() function is different from Server {sqlpp} ROUND(), which rounds the midpoint values using _Rounding to Nearest Even_ convention.


[#csharp:query-n1ql-mobile:::lbl-func-meta]
==== Metadata Functions

.Metadata Functions
[tbl-func-meta,cols="1m,2,2m", options="header"]
|===


|Function
|Description
|Example

|META(dataSourceName?)

a|Returns a dictionary containing metadata properties including:

* id : document identifier
* sequence : document mutating sequence number
* deleted : flag indicating whether document is deleted or not
* expiration : document expiration date in timestamp format

The optional dataSourceName identifies the database  or the database alias name. +
To access a specific metadata property, use the dot expression.

|SELECT META() FROM db

SELECT META().id, META().sequence, META().deleted, META().expiration FROM db

SELECT p.name, r.rating FROM product as p INNER JOIN reviews AS r ON META(r).id IN p.reviewList WHERE META(p).id = "product320"


|===


[#csharp:query-n1ql-mobile:::lbl-func-pattern]
==== Pattern Searching Functions

.Pattern Searching Functions
[tbl-func-meta,cols="1m,4", options="header"]
|===

|Function
|Description

|REGEXP_CONTAINS(expr, pattern)
|Returns TRUE if the string value contains any sequence that matches the regular expression pattern.

|REGEXP_LIKE(expr, pattern)
|Return TRUE if the string value exactly matches the regular expression pattern.

|REGEXP_POSITION(expr, pattern)
|Returns the first position of the occurrence of the regular expression pattern within the input string expression. Return -1 if no match is found. Position counting starts from zero.

|REGEXP_REPLACE(expr, pattern, repl [, n])
|Returns new string with occurrences of pattern replaced with repl. If n is given, at the most n replacements are performed. If n is not given, all matching occurrences are replaced.

|===

[#csharp:query-n1ql-mobile:::lbl-func-string]
==== String Functions

.String Functions
[tbl-func-str,cols="1m,4", options="header"]
|===

|Function
|Description

|CONTAINS(expr, substring_expr)
|Returns true if the substring exists within the input string, otherwise returns false.
|LENGTH(expr)
|Returns the length of a string. The length is defined as the number of characters within the string.
|LOWER(expr)
|Returns the lowercase string of the input string.

|LTRIM(expr)
|Returns the string with all leading whitespace characters removed.

|RTRIM(expr)
|Returns the string with all trailing whitespace characters removed.

|TRIM(expr)
|Returns the string with all leading and trailing whitespace characters removed.

|UPPER(expr)
|Returns the uppercase string of the input string.

|===


[#csharp:query-n1ql-mobile:::lbl-func-typecheck]
==== Type Checking Functions

.Type Checking Functions
[tbl-func-tpcheck,cols="1m,4", options="header"]
|===

|Function
|Description

|ISARRAY(expr)
|Returns TRUE if expression is an array, otherwise returns MISSING, NULL or FALSE.

|ISATOM(expr)
|Returns TRUE if expression is a Boolean, number, or string, otherwise returns MISSING, NULL or FALSE.

|ISBOOLEAN(expr)
|Returns TRUE if expression is a Boolean, otherwise returns MISSING, NULL or FALSE.

|ISNUMBER(expr)
|Returns TRUE if expression is a number, otherwise returns MISSING, NULL or FALSE.

|ISOBJECT(expr)
|Returns TRUE if expression is an object (dictionary), otherwise returns MISSING, NULL or FALSE.

|ISSTRING(expr)
|Returns TRUE if expression is a string, otherwise returns MISSING, NULL or FALSE.

|TYPE(expr)
a|Returns one of the following strings, based on the value of expression:

* “missing”
* “null”
* “boolean”
* “number”
* “string”
* “array”
* “object”
* “binary”

|===


[#csharp:query-n1ql-mobile:::lbl-func-typeconv]
==== Type Conversion Functions

.Type Conversion Functions
[tbl-func-tpconv,cols="3,7", options="header"]
|===

|Function
|Description

.4+m|TOARRAY(expr)
|Returns MISSING if the value is MISSING.

|Returns NULL if the value is NULL.
|Returns the array itself.
|Returns all other values wrapped in an array.


.6+m|TOATOM(expr)
|Returns MISSING if the value is MISSING.

|Returns NULL if the value is NULL.
|Returns an array of a single item if the value is an array.
|Returns an object of a single key/value pair if the value is an object.
|Returns boolean, numbers, or strings
|Returns NULL for all other values.

.6+m|TOBOOLEAN(expr)
|Returns MISSING if the value is MISSING.

|Returns NULL if the value is NULL.
|Returns FALSE if the value is FALSE.
|Returns FALSE if the value is 0 or NaN.
|Returns FALSE if the value is an empty string, array, and object.
|Return TRUE for all other values.

.7+m|TONUMBER(expr)
|Returns MISSING if the value is MISSING.

|Returns NULL if the value is NULL.
|Returns 0 if the value is FALSE.
|Returns 1 if the value is TRUE.
|Returns NUMBER if the value is NUMBER.
|Returns NUMBER parsed from the string value.
|Returns NULL for all other values.

.4+m|TOOBJECT(expr)
|Returns MISSING if the value is MISSING.

|Returns NULL if the value is NULL.
|Returns the object if the value is an object.
|Returns an empty object for all other  values.

.8+m|TOSTRING(expr)
|Returns MISSING if the value is MISSING.

|Returns NULL if the value is NULL.
|Returns “false” if the value is FALSE.
|Returns “true” if the value is TRUE.
|Returns NUMBER in String if the value is NUMBER.
|Returns the string value if the value is a string.
|Returns NULL for all other values.

|===


[#csharp:query-n1ql-mobile:::querybuilder-differences]
=== QueryBuilder Differences

Couchbase Lite {sqlpp} Query supports all QueryBuilder features, except _Predictive Query_ and _Index_. See <<csharp:query-n1ql-mobile:::tbl-qbldr-diffs>> for the features supported by {sqlpp} but not by QueryBuilder.


.QueryBuilder Differences
[#csharp:query-n1ql-mobile:::tbl-qbldr-diffs,cols="4,6m", options="header"]
|===

|Category
|Components

|Conditional Operator
|CASE(WHEN ... THEN ... ELSE ..)

|Array Functions
|ARRAY_AGG
ARRAY_AVG
ARRAY_COUNT
ARRAY_IFNULL
ARRAY_MAX
ARRAY_MIN
ARRAY_SUM

|Conditional Functions
|IFMISSING
IFMISSINGORNULL
IFNULL
MISSINGIF
NULLIF
Match Functions
DIV
IDIV
ROUND_EVEN

|Pattern Matching Functions
|REGEXP_CONTAINS
REGEXP_LIKE
REGEXP_POSITION
REGEXP_REPLACE

|Type Checking Functions
|ISARRAY
ISATOM
ISBOOLEAN
ISNUMBER
ISOBJECT
ISSTRING
TYPE

|Type Conversion Functions
|TOARRAY
TOATOM
TOBOOLEAN
TONUMBER
TOOBJECT
TOSTRING
|===

[#csharp:query-n1ql-mobile:::lbl-query-params]
=== Query Parameters

You can provide runtime parameters to your {sqlpp} query to make it more flexible.

To specify substitutable parameters within your query string prefix the name with *`$`*, `$type` -- see: <<csharp:query-n1ql-mobile:::ex-sample-params>>.

.Running a {sqlpp} Query
[#ex-sample-params]


[#csharp:query-n1ql-mobile:::ex-sample-params]
====


// Show Main Snippet
// include::csharp:example$code_snippets/Program.cs[tags="query-syntax-n1ql-params", indent=0]
[source, C#]
----
using var query =
    database.CreateQuery("SELECT META().id AS thisId FROM _ WHERE type = $type"); // <.>

var n1qlParams = new Parameters();
n1qlParams.SetString("type", "hotel"); // <.>
query.Parameters = n1qlParams;

var results = query.Execute().AllResults();
----


====


<.> Define a parameter placeholder `$type`
<.> Set the value of the `$type` parameter


[#csharp:query-n1ql-mobile:::related-content]
=== Related Content
++++
<div class="card-row three-column-row">
++++

[.column]
==== {empty}
.How to . . .
* xref:csharp:gs-prereqs.adoc[Prerequisites]
* xref:csharp:gs-install.adoc[Install]
* xref:csharp:gs-build.adoc[Build and Run]


.

[discrete.colum#csharp:query-n1ql-mobile:::-2n]
==== {empty}
.Learn more . . .
* xref:csharp:database.adoc[Databases]
* xref:csharp:document.adoc[Documents]
* xref:csharp:blob.adoc[Blobs]
* xref:csharp:replication.adoc[Remote Sync Gateway]
* xref:csharp:conflict.adoc[Handling Data Conflicts]

.


[discrete.colum#csharp:query-n1ql-mobile:::-3n]
==== {empty}
.Dive Deeper . . .
https://forums.couchbase.com/c/mobile/14[Mobile Forum] |
https://blog.couchbase.com/[Blog] |
https://docs.couchbase.com/tutorials/[Tutorials]

.


++++
</div>
++++


