= Manage Scopes and Collections
:page-aliases: 
ifdef::show_edition[:page-edition: {release}]
ifdef::prerelease[:page-status: {prerelease}]
:page-role:
:description: Manage Scopes and Collections

Scopes and collections allow you to organize your documents within a database.

.At a glance
****
**Use collections to organize your content in a database**

For example, if your database contains travel information, airport documents can be assigned to an airports collection, hotel documents can be assigned to a hotels collection, and so on.

* You can create up to 1000 collections per database. 
* Document names must be unique within their collection.
* Applications can be assigned per-collection access-rights.


**Use scopes to group multiple collections** 

Collections can be assigned to different scopes according to content-type or deployment-phase (for example, test versus production). 

* You can create up to 1000 scopes per database. 
* Collection names must be unique within their scope. 
* Applications can be assigned per-scope access-rights so they can only access the scopes they require.



****

== Default Scopes and Collections

Every database you create contains a default scope and a default collection named _default. 

If you create a document in the database and don’t specify a specific scope or collection, it is saved in the default collection, in the default scope. 

If you upgrade from a version of Couchbase Lite prior to 3.1, all existing data is automatically placed in the default scope and default collection.

The default scope  and collection cannot be dropped. 




== Assign access to Scopes and Collections
Access to scopes and collections is protected by Role-Based Access Control (RBAC). For information on RBAC, see Authorization. For a list of roles, see Roles. For examples of how to assign roles to scopes and collections, see Manage Users, Groups, and Roles. [do we have any of this info already for Mobile?]


== Create a Scope

In addition to the default, you can create your own scopes.

User-defined scopes:

* Must be between 1 and 251 characters in length.
* Can only contain the characters A-Z, a-z, 0-9, and the symbols _, -, and %. 
* Cannot start with _ or %.
* Scope names must be unique in databases. 
Collections names must be unique within a scope.

NOTE: Scope names are case sensitive.

[source,csharp]
–
PLEASE INSERT CODE ABOUT CREATING A COLLECTION!


–


 


== Create a Collection

In addition to the default, you can create your own collections.

User-defined collections:

* Must be between 1 and 251 characters in length.
* Can only contain the characters A-Z, a-z, 0-9, and the symbols _, -, and %. 
* Cannot start with _ or %.
* Collections names must be unique within a scope.

NOTE: Collection names are case sensitive.

[source,csharp]
–
PLEASE INSERT CODE 


– 


== Index a Collection



[source,csharp]
–
PLEASE INSERT CODE 


–




== Drop a Scope


[source,csharp]
–
PLEASE INSERT CODE 


–

== Drop a Collection


[source,csharp]
–
PLEASE INSERT CODE 


–

== List Scopes and Collections

[source,csharp]
–
PLEASE INSERT CODE 


–
