
= Supported Operating System Versions
:page-aliases: product/csharp-supported-os.adoc
:page-role: -toc
:description: Couchbase Lite on C#.Net -- the OS and SDK versions on which this framework is supported


:source-language: C#


[abstract]
--
Description -- _{description}_ +
Related Content -- xref:cbl-whatsnew.adoc[What's New]  |  xref:csharp:releasenotes.adoc[Release Notes] | xref:csharp:compatibility.adoc[Compatibility]
--

[#officially-supported-versions]
== Officially Supported Versions

The following table identifies the supported platforms.

Run-times which have received more testing and are *officially* supported are shown in xref:csharp:supported-os.adoc#supported-os-versions[]:

[IMPORTANT]
.Deprecation Notice
--
Couchbase Lite 4.0 deprecates Windows 10 support and will remove it in a future release.
Plan to migrate your apps to use an appropriate alternative version.
--

[NOTE]
.Newer .NET Runtime Versions
--
The *Minimum Runtime Version* column specifies the minimum required version for each .NET runtime. 
Later versions, including .NET 10 and higher, also work because .NET provides backward compatibility.
Couchbase Lite is built to be compatible with newer .NET runtime versions as they're released.
If you encounter any issues with a newer .NET version, submit a support ticket to address any breaking changes introduced by Microsoft.
--

.Supported versions
[#supported-os-versions]
[#supported-os-versions,cols="1,^2,^2", options="header"]
|===
.>|.NET Runtime .>|Minimum Runtime Version (and newer) .>|Minimum OS version

| .NET Framework
| 4.6.2
a| Windows 10 +
 (any Microsoft supported)

| .NET Desktop
| 8.0
a| Windows 10 +
  (any Microsoft supported)

| .NET Mac Catalyst
| 9.0
a| MacOS 13

|WinUI
|9.0
|10.0.19041.0

|.NET iOS
|9.0
|15

|.NET Android
|9.0
|API 24

|===


[#not-officially-supported]
== Not Officially Supported

The following run-times are compatible but are not QE tested, and so are not officially supported.

[cols="1,^2,^2", options="header"]
|===
.>|.NET Runtime .>|Minimum Runtime Version .>|Minimum OS version
|.NET Mac
| 8.0
|13

|.NET Linux
| 8.0
|n/a

|===


