= Supported Operating System Versions
:page-aliases: product/csharp-supported-os.adoc
:page-role: -toc
:description: Couchbase Lite on C#.Net -- the OS and SDK versions on which this framework is supported


:source-language: C#


[abstract]
--
Description -- _{description}_ +
Related Content -- xref:cbl-whatsnew.adoc[What's New]  |  xref:csharp:releasenotes.adoc[Release Notes] | xref:csharp:compatibility.adoc[Compatibility]
--

[#officially-supported-versions]
== Officially Supported Versions

The following table identifies the supported platforms.

<<<<<<< HEAD
Run-times which have received more testing and are *officially* supported are shown in xref:csharp:supported-os.adoc#supported-os-versions[].

[NOTE]
.Newer .NET Runtime Versions
--
Later versions, including .NET 11 and higher, also work because .NET provides backward compatibility.
Couchbase Lite is built to be compatible with newer .NET runtime versions as they're released.
If you encounter any issues with a newer .NET version, submit a support ticket.
=======
Run-times which have received more testing and are *officially* supported are shown in xref:csharp:supported-os.adoc#supported-os-versions[]:

[IMPORTANT]
.Deprecation Notice
--
Support for the following will be deprecated in this release and will be removed in a future release:

* Xamarin Android - All Versions
* Xamarin iOS - All Versions
* .NET Desktop - 6

Please plan to migrate your apps to use an appropriate alternative version.
>>>>>>> 8c0e7861 (update the file for .net)
--

.Supported versions
[#supported-os-versions]
[#supported-os-versions,cols="1,^2,^2", options="header"]
|===
.>|.NET Runtime .>|Minimum Runtime Version .>|Minimum OS version

| .NET Framework
| 4.6.2
a| Windows 11 +
 (any Microsoft supported)

| .NET Desktop
| 8.0
a| Windows 11 +
  (any Microsoft supported)

| .NET Mac Catalyst
| 10.0
a| MacOS 14

|WinUI
|10.0
|10.0.19041.0

|.NET iOS
|10.0
|15

|.NET Android
|10.0
|API 22+

|Xamarin Android
|10+
|API 22

|Xamarin iOS
|10+
|10

|===


[#not-officially-supported]
== Not Officially Supported

The following run-times are compatible but are not QE tested, and so are not officially supported.

[cols="1,^2,^2", options="header"]
|===
.>|.NET Runtime .>|Minimum Runtime Version .>|Minimum OS version
|.NET Mac
| 8.0
|14

|.NET Linux
| 8.0
|n/a
|===

*{sp}There are many different variants of Linux, and we don't have the resources to test all of them.
They are tested on Ubuntu 20.04, but have been shown to work on CentOS, and in theory work on any distro supported by .NET.

[#removed-versions]
== Removed Versions

[cols="1,^2,^2", options="header"]
|===
.>|.NET Runtime .>|Version Removed .>|Deprecation Release

|Windows 10
|3.4 / 4.1
|4.0
<<<<<<< HEAD

|===


[#removed-versions]
== Removed Versions

[cols="1,^2,^2", options="header"]
|===
.>|.NET Runtime .>|Version Removed .>|Deprecation Release

|Windows 10
|4.1
|4.0
=======
>>>>>>> 8c0e7861 (update the file for .net)

|===