
= Supported Operating System Versions
:page-aliases: product/csharp-supported-os.adoc
:page-role: -toc
:description: Couchbase Lite on C#.Net -- the OS and SDK versions on which this framework is supported


:source-language: C#


[abstract]
--
Description -- _{description}_ +
Related Content -- xref:cbl-whatsnew.adoc[What's New]  |  xref:csharp:releasenotes.adoc[Release Notes] | xref:csharp:compatibility.adoc[Compatibility]
--

[#officially-supported-versions]
== Officially Supported Versions

The following table identifies the supported platforms.

Run-times which have received more testing and are *officially* supported are shown in xref:csharp:supported-os.adoc#supported-os-versions[]:

[IMPORTANT]
.Deprecation Notice
--
Support for the following will be deprecated in this release and will be removed in a future release:

* .NET Desktop - 6

Please plan to migrate your apps to use an appropriate alternative version.
--

.Supported versions
[#supported-os-versions]
[#supported-os-versions,cols="1,^2,^2", options="header"]
|===
.>|.NET Runtime .>|Minimum Runtime Version .>|Minimum OS version

| .NET Framework
| 4.6.2
a| Windows 10 +
 (any Microsoft supported)

| .NET Desktop
| 6.0
a| Windows 10 +
  (any Microsoft supported)

| .NET Mac Catalyst
| 9.0
a| MacOS 13

|WinUI
|9.0
|10.0.19041.0

|.NET iOS
|9.0
|15+

|.NET Android
|9.0
|API 24+

|===


[#not-officially-supported]
== Not Officially Supported

The following run-times are compatible but are not QE tested, and so are not officially supported.

[cols="1,^2,^2", options="header"]
|===
.>|.NET Runtime .>|Minimum Runtime Version .>|Minimum OS version
|.NET Mac
| 6.0
|12

|.NET Linux
| 6.0
|n/a*
|===

*{sp}Multiple Linux variants exist, and testing coverage does not extend to all distributions.
Testing occurs on Ubuntu 20.04, with demonstrated compatibility on CentOS and theoretical support for any distribution supported by .NET.


