
= Troubleshooting Queries
:page-role:
:description: Couchbase Lite on C# -- Using query.explain()


:source-language: C#


[abstract]
--
Description -- _{description}_ +
_Abstract -- This content describes how to use the Couchbase Lite on C#.Net Query API's explain() method to examine a query_ +
Related Content -- xref:csharp:troubleshooting-logs.adoc[Using Logs] | xref:csharp:querybuilder.adoc#lbl-predquery[Predictive Queries] | xref:csharp:query-live.adoc[Live Queries] | xref:csharp:indexing.adoc[Indexing]
--


[#query-explain]
== Query Explain


[#using]
=== Using
Query's https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-net}{empty}/couchbase-lite-net/api/Couchbase.Lite.Query.#Couchbase_Lite__Query_IQuery_Explain[Explain()] method can provide useful insight when you're trying to diagnose query performance issues and-or optimize queries.
To examine how your query is working, either embed the call inside your app (see: xref:csharp:troubleshooting-queries.adoc#use-qe-app[]), or use it interactively within a `cblite` shell (see: xref:csharp:troubleshooting-queries.adoc#use-qe-cblite[]).

[#use-qe-app]
.Using Query Explain in App


[#use-qe-app]
====


[source, C#]
----
include::csharp:example$code_snippets/Program.cs[tags="query-explain-all", indent=0]
----


====

<.> Construct your query as normal
<.> Call the query's `explain` method; All output is sent to the application's log file.

[#use-qe-cblite]
.Using Query Explain in cblite
====
`cblite` is a command-line tool for inspecting and querying Couchbase Lite databases.
You can download and build it from the couchbaselabs https://github.com/couchbaselabs/couchbase-mobile-tools/blob/master/README.cblite.md[GitHub repository].

NOTE: The `cblite` tool is not supported by the https://www.couchbase.com/support-policy[Couchbase Support Policy].

[source, console]
----
cblite <your-database-name>.cblite2 // <.>

(cblite) select --explain domains group by country order by country, name // <.>

(cblite) query --explain {"GROUP_BY":[[".country"]],"ORDER_BY":[[".country"],[".name"]],"WHAT":[[".domains"]]} // <.>

----
<.> Within a terminal session, open your database with `cblite` and enter your query
<.> This example enters the query as a N1QL-query using `select` +
<.> This example enters the query as a JSON-string using `query`
====


[#output]
=== Output
The output from `https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-net}{empty}/couchbase-lite-net/api/Couchbase.Lite.Query.#Couchbase_Lite__Query_IQuery_Explain[Explain()]` remains the same whether invoked by an app, or `cblite` -- see xref:csharp:troubleshooting-queries.adoc#qe-output[] for an example of how it looks.

[#qe-output]
.Query.explain() Output
====

[source, console]
----
SELECT fl_result(fl_value(_doc.body, 'domains')) FROM kv_default AS _doc WHERE (_doc.flags & 1 = 0) GROUP BY fl_value(_doc.body, 'country') ORDER BY fl_value(_doc.body, 'country'), fl_value(_doc.body, 'name') // <.>

7|0|0| SCAN TABLE kv_default AS _doc // <.>
12|0|0| USE TEMP B-TREE FOR GROUP BY
52|0|0| USE TEMP B-TREE FOR ORDER BY

{"GROUP_BY":[[".country"]],"ORDER_BY":[[".country"],[".name"]],"WHAT":[[".domains"]]} // <.>

----

====

This output (xref:csharp:troubleshooting-queries.adoc#qe-output[]) comprises 3 main elements:

<.> The translated SQL-query, which targets Couchbase support and engineering teams rather than general users.
<.> The _SQLite_ query plan, which gives a high-level view of how SQLite implements the query.
You can use this to identify potential issues and so optimize problematic queries.
<.> The query in JSON-string format, which you can copy-and-paste directly into the _cblite_ tool.


[#the-query-plan]
== The Query Plan


[#format]
=== Format
The query plan section of the output displays a tabular form of the translated query's execution plan.
It primarily shows how SQLite retrieves the data and, where appropriate, how it sorts results for navigation and-or presentation purposes.
For more on SQLite's Explain Query Plan -- see: https://www.sqlite.org/eqp.html

[#qry-plan]
.A Query Plan
====
[source, console]
----
7|0|0| SCAN TABLE kv_default AS _doc // <.>
12|0|0| USE TEMP B-TREE FOR GROUP BY // <.>
52|0|0| USE TEMP B-TREE FOR ORDER BY // <.>
----

<.> *Retrieval method* -- This line shows the retrieval method the query uses; here a sequential read of the database.
Something you may want to optimize -- see xref:csharp:troubleshooting-queries.adoc#ret-method[] for more.
<.> *Grouping method* --- This line shows that the *Group By* clause in the query requires sorted data and uses a b-tree for temporary storage -- see xref:csharp:troubleshooting-queries.adoc#order-group[].
<.> *Ordering method* -- This line shows that the *Order By* clause in the query requires sorted data and uses a b-tree for temporary storage -- see xref:csharp:troubleshooting-queries.adoc#order-group[].
====


[#ret-method]
=== Retrieval Method
The query optimizer attempts to retrieve the requested data items as efficiently as possible, which generally involves using 1 or more of the available indexes.
The _retrieval method_ shows the approach chosen by the optimizer -- see xref:csharp:troubleshooting-queries.adoc#ret-meths[].

[#ret-meths]
.Retrieval methods
[#,cols="2,8"]
|===
|Retrieval Method | Description

|Search
|Here the query can view the required data directly using keys into the index.
Queries using the Search mode are the fastest.

|Scan Index
|Here the query is able to retrieve the data by scanning all or part-of the index (for example when seeking to match values within a range).
This type of query is slower than search, but at least benefits from the compact and ordered form of the index.

|Scan Table
|Here the query must scan the database table(s) to retrieve the required data.
It's the slowest of these methods and benefits most from optimization.
|===

When looking to optimize a query's retrieval method, consider whether:

* Providing an additional index makes sense
* You could use an existing index -- perhaps by restructuring the query to minimize wildcard use, or the reliance on functions that modify the query's interpretation of index keys (for example, 'lower')
* You could reduce the dataset the query requests to minimize its footprint on the database

[#order-group]
=== Order and Group
The `Use temp b-tree for` lines in the example indicate that the query requires sorting to cater for grouping and then sorting again to present the output results.
Minimizing, if not eliminating, this ordering and re-ordering obviously reduces the time taken to process the query.

Ask "is the grouping and-or ordering absolutely necessary?": if it's not, drop it or modify it to minimize its impact.


[#queries-and-indexes]
== Queries and Indexes

Querying documents using a pre-existing database index is much faster because an index reduces the set of documents to examine -- see: the xref:csharp:query-troubleshooting.adoc[Query Troubleshooting] topic.

When planning the indexes you need for your database, remember that while indexes make queries faster, they may also:

* Make writes slightly slower, because the system updates each index whenever you update a document
* Make your Couchbase Lite database slightly larger.

Excessive indexes may hurt performance.
Optimal performance depends on designing and creating the _right_ indexes to go along with your queries.

.Constraints
[NOTE]
Couchbase Lite for .Net does not currently support partial value indexes; indexes with non-property expressions.
You should only index with properties that you plan to use in the query.


The Query optimizer converts your query into a parse tree that groups zero or more _and-connected_ clauses together (as dictated by your `where` conditionals) for effective query engine processing.

Ideally, a query should be able to satisfy its requirements entirely by either directly accessing the index or searching sequential index rows.
Less good is if the query must scan the whole index; although the compact nature of most indexes means this is still much faster than the alternative of scanning the entire database with no help from the indexes at all.

Searches that begin with or rely upon an inequality with the primary key are inherently less effective than those using a primary key equality.


[#working-with-the-query-optimizer]
== Working with the Query Optimizer
You may have noticed that sometimes a query runs faster on a second run, or after re-opening the database, or after deleting and recreating an index.
This typically happens when SQL Query Optimizer has gathered sufficient stats to recognize a means of optimizing a sub-optimal query.

If only those stats were available from the start.
In fact they're gathered after certain events, such as:

* Following index creation
* On a database close
* When running a database compact.

If your analysis of the xref:csharp:troubleshooting-queries.adoc#qe-output[Query Explain output] indicates a sub-optimal query and your rewrites fail to sufficiently optimize it, consider compacting the database.
Then re-generate the Query Explain and note any improvements in optimization.
They may not, in themselves, resolve the issue entirely; but they can provide useful guide to further optimizing changes you could make.


[#use-like-based-queries]
== Wildcard and Like-based Queries

Like-based searches can use the index(es) only if:

* The search-string does not start with a wildcard
* The primary search expression uses a property that's indexed key
* The search-string is a constant known at run time) (that is, not a value derived during processing of the query)

To show this, you can use a modified query from the Mobile Travel Sample application, replacing an equality test with a 'LIKE'

In xref:csharp:troubleshooting-queries.adoc#like-wild-pfx-qry[] we use a wildcard prefix and suffix.
You can see that the query plan decides on a retrieval method of `Scan Table`.

TIP: For more on indexes -- see: xref:csharp:indexing.adoc[Indexing]

[#like-wild-pfx-qry]
.Like with Wildcard Prefix


[source#like-wild-pfx-qry, C#]
----
include::csharp:example$code_snippets/Program.cs[tags="query-explain-like", indent=0]
----


<.> The indexed property, TYPE, cannot use its index because of the wildcard prefix.


.Resulting Query Plan
[source, console]
----
2|0|0| SCAN TABLE kv_default AS _doc
----

By contrast, removing the wildcard prefix `%` (in xref:csharp:troubleshooting-queries.adoc#like-no-wild-pfx-qry[]) changes the query plan's retrieval method to an index search.
Where practical, changes like this can make significant differences in query performance.

.Like with No Wildcard-prefix
[#like-no-wild-pfx-qry]


[#like-no-wild-pfx-qry]
====


[source, C#]
----
include::csharp:example$code_snippets/Program.cs[tags="query-explain-nopfx", indent=0]
----


====

<.> Simply removing the wildcard prefix enables the query optimizer to access the `typeIndex`, which results in a more efficient search.

.Resulting Query Plan
[source, bash]
----
3|0|0| SEARCH TABLE kv_default AS _doc USING INDEX typeIndex (<expr>>? AND <expr><?)
----

[#use-functions-wisely]
== Use Functions Wisely

Functions are a useful tool in building queries, but be aware that they can affect whether the query-optimizer is able to use your index(es).

For example, you can observe a similar situation to that shown in xref:csharp:troubleshooting-queries.adoc#use-like-based-queries[] when using the `https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-net}{empty}/couchbase-lite-net/api/Couchbase.Lite.Query.Function.html#Couchbase_Lite_Query_Function_Lower_Couchbase_Lite_Query_IExpression_[Lower()]` function on an indexed property.

.Query
[#use-like-based-queries]


[source#use-like-based-queries, C#]
----
include::csharp:example$code_snippets/Program.cs[tags="query-explain-function", indent=0]
----


<.> Here we use the `https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-net}{empty}/couchbase-lite-net/api/Couchbase.Lite.Query.Function.html#Couchbase_Lite_Query_Function_Lower_Couchbase_Lite_Query_IExpression_[Lower()]` function in the _Where_ expression

.Query Plan:
[source, bash]
----
2|0|0| SCAN TABLE kv_default AS _doc
----


Removing the `https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-net}{empty}/couchbase-lite-net/api/Couchbase.Lite.Query.Function.html#Couchbase_Lite_Query_Function_Lower_Couchbase_Lite_Query_IExpression_[Lower()]` function changes things:

.Query


[source, C#]
----
include::csharp:example$code_snippets/Program.cs[tags="query-explain-nofunction", indent=0]
----


<.> Here we have removed `https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-net}{empty}/couchbase-lite-net/api/Couchbase.Lite.Query.Function.html#Couchbase_Lite_Query_Function_Lower_Couchbase_Lite_Query_IExpression_[Lower()]` from the _Where_ expression

.Query plan
----
3|0|0| SEARCH TABLE kv_default AS _doc USING INDEX typeIndex (<expr>=?)
----

Knowing this, you can consider how you create the index; for example, using https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-net}{empty}/couchbase-lite-net/api/Couchbase.Lite.Query.Function.html#Couchbase_Lite_Query_Function_Lower_Couchbase_Lite_Query_IExpression_[Lower()] when you create the index and then always using lowercase comparisons.

[#optimization-considerations]
== Optimization Considerations

Try to minimize the amount of data retrieved.
Limit it to the properties you *do* need to achieve the required result.

Consider fetching details _lazily_.
You could break complex queries into components.
For example, return just the doc-ids first, then process the array of doc-ids using either the Document API or a query that uses the doc-ids to return detailed information.

Consider using paging to minimize the data returned when the number of results returned is expected to be high.
Getting the whole lot at once is slow and resource intensive.
Instead, retrieve batches of information at a time, perhaps using the `Where` method's `limit(offset)` feature to set a starting point for each subsequent batch.

NOTE: Using query offsets becomes less effective as the overhead of skipping a growing number of rows each time increases.
You can work around this by using ranges of search-key values instead.
If the last search-key value of batch 1 was 'x', that becomes the starting point for your next batch, and so on.

Optimize document size in design.
Smaller docs load faster.
Break your data into logical linked units.

Consider Using Full Text Search instead of complex like or regular expression patterns -- see xref:csharp:fts.adoc[Full Text Search]. +
{empty}


[#related-content]
== Related Content
++++
<div class="card-row three-column-row">
++++

[.column]
====== {empty}
.How to . . .
* xref:csharp:querybuilder.adoc[QueryBuilder]
* xref:csharp:query-n1ql-mobile.adoc[{sqlpp} for Mobile]
* xref:csharp:query-live.adoc[Live Queries]
* xref:csharp:fts.adoc[Full Text Search]


.

[.column]
====== {empty}
.Learn more . . .
* xref:csharp:query-n1ql-mobile-querybuilder-diffs.adoc[{sqlpp} Mobile - Querybuilder  Differences]
* xref:csharp:query-n1ql-mobile-server-diffs.adoc[{sqlpp} Mobile - {sqlpp} Server Differences]
* xref:csharp:query-resultsets.adoc[Query Resultsets]
* xref:csharp:query-troubleshooting.adoc[Query Troubleshooting]
* xref:csharp:query-live.adoc[Live Queries]

* xref:csharp:database.adoc[Databases]
* xref:csharp:document.adoc[Documents]
* xref:csharp:blob.adoc[Blobs]

.


[.column]
====== {empty}
.Dive Deeper . . .
https://forums.couchbase.com/c/mobile/14[Mobile Forum] |
https://blog.couchbase.com/[Blog] |
https://docs.couchbase.com/tutorials/[Tutorials]

.


++++
</div>
++++

