= Upgrade
:page-aliases: advance/csharp-dep-upgrade.adoc, dep-upgrade.adoc
:page-role:

:source-language: c#


[IMPORTANT]
--
On upgrading from a 3.x release, all Couchbase Lite databases automatically re-index on initial database open. +
This can result in a delay before the database is usable.
--

[#4-0-0-upgrade]
== {major}.{minor}.{base}{empty} Upgrade

Couchbase Lite 4.0 introduces significant architectural changes, most notably the migration from revision trees to version vectors for document versioning.
This upgrade requires understanding of the compatibility requirements.

The action takes place automatically and can lead to some delay in the database becoming available for use in your application.

In addition, if you're syncing with a {major}.{minor}.{base}{empty} Sync Gateway, you should be aware of the significant configuration enhancements introduced and their effects.
See xref:sync-gateway::upgrading.adoc[Upgrading Sync Gateway] for more details.
This is a one-way conversion.

=== Major Changes in {major}.{minor}.{base}{empty}

**Version Vector Architecture**:
CBL {major}.{minor}.{base}{empty} replaces the revision tree system with version vectors, providing improved performance, scalability, and conflict resolution.
Documents now use version-based revision IDs in the format `<timestamp>@<source-id>` instead of the previous `<generation>-<document-hash>` format.

**Enhanced Conflict Resolution**: The default conflict resolution strategy changes from `most active wins` to `last write wins` based on hybrid logical timestamps, providing more intuitive and predictable conflict resolution behavior.

**New Document Properties**:
a new `Timestamp` property is available on Document objects, providing direct access to the document's logical timestamp as a `ulong` value representing nanoseconds since the Unix epoch.

[#database-compatibility-40]
=== Database Compatibility

**Automatic Upgrade from 3.x**:
CBL {major}.{minor}.{base}{empty} databases are compatible with CBL 3.1 and 3.2 databases.
When opening a 3.1 or 3.2 database with CBL {major}.{minor}.{base}{empty}, documents are automatically upgraded to use version vectors when they're updated and saved.

**No Configuration Required**:
CBL {major}.{minor}.{base}{empty} enables version vectors by default - the feature requires no API configuration.

[#synchronization-compatibility-40]
=== Synchronization Compatibility

**Sync Gateway Requirements**:
CBL {major}.{minor}.{base}{empty} requires Sync Gateway 4.x or later for synchronization.
Attempting to sync with Sync Gateway versions prior to 4.x results in replication errors with appropriate error messages indicating the incompatibility.

**Peer-to-Peer Compatibility**: CBL {major}.{minor}.{base}{empty} can only perform peer-to-peer synchronization with other CBL 4.x instances using either `URLEndpointListener` or `MessageEndpointListener`.
Sync attempts with CBL 3.x peers fail with appropriate error messages.

[#replication-compatibility]
=== Replication Compatibility

CBL 4.0 introduces strict replication compatibility requirements due to the version vector architecture changes.

**Sync Gateway Compatibility**: CBL 4.0 requires Sync Gateway 4.0 or later for synchronization.
Attempting to sync with Sync Gateway versions prior to 4.0 results in replication errors with appropriate error messages indicating the incompatibility.

**Peer-to-Peer Compatibility**: CBL 4.0 can only perform peer-to-peer synchronization with other CBL 4.0+ instances.
Sync attempts with CBL 3.x or earlier peers fails with appropriate error messages.

**No Backward Compatibility**: unlike previous CBL versions, CBL 4.0 cannot sync with earlier versions of either Sync Gateway or other CBL instances due to the fundamental changes in document versioning architecture.

[#replicator-configuration]
==== ReplicatorConfiguration

Couchbase Lite {major}.{minor} introduces changes to the `ReplicatorConfiguration` class to improve API consistency across all Couchbase Lite platforms.
The API no longer supports legacy collection management methods.

**Removed APIs:**
* `addCollection(s)` / `removeCollection(s)` / `getCollectionConfig()` methods
* `ReplicatorConfiguration(Database, Endpoint)` constructor that uses default collection

[#before-replicator]
===== Before (.NET 3.x)
[source, csharp]
----
var collConfig = new CollectionConfiguration();
collConfig.Channels = new[] { "a", "b", "c" };

var replicatorConfig = new ReplicatorConfiguration(target: endpoint);
replicatorConfig.AddCollection(collectionA, collConfig);
----

[#after-replicator]
===== After (.NET 4.0.0)
[source, csharp]
----
var collConfig = new CollectionConfiguration(collection: collectionA);
collConfig.Channels = new[] { "a", "b", "c" };

var replicatorConfig = new ReplicatorConfiguration(collections: new[] { collConfig }, target: endpoint);
----

NOTE: This change provides API consistency across all CBL platforms and simplifies the implementation by requiring collections and configurations at construction time.

[#api-changes]
=== API Changes

This content introduces the changes made to the Couchbase{nbsp}Lite for C#.Net API for release {major}.{minor}.{base}{empty}.

// Starting from 3.2 Couchbase{nbsp}Lite for C#.Net requires _Visual Studio 2019+_ and uses .Net Core 3.1 (updating from .Net Core 2.0).

[#breaking-change]
==== Breaking Change

The function https://docs.couchbase.com/mobile/2.8.0/couchbase-lite-net/api/Couchbase.Lite.Query.Function.html#Couchbase_Lite_Query_Function_Atan2_Couchbase_Lite_Query_IExpression_Couchbase_Lite_Query_IExpression_[ATAN2(x, y)],
which returns the principal value of the arc tangent of y/x, now becomes
https://docs.couchbase.com/mobile/{major}.{minor}.{base}{empty}/couchbase-lite-net/api/Couchbase.Lite.Query.Function.html#Couchbase_Lite_Query_Function_Atan2_Couchbase_Lite_Query_IExpression_Couchbase_Lite_Query_IExpression_[ATAN2(y, x)];
that's, the arguments reverses in line with common notation.

[#removed]
==== Removed

[#activate]
===== Activate

The method `Activate()` has been removed from *all* platform support libraries *except* `Support.Android` (Xamarin Android)

[#enabletextlogging]
===== EnableTextLogging()
The obsolete method `EnableTextLogging()` is no longer supported in any platform support libraries.

[#resetcheckpoint]
===== ResetCheckpoint

The method
https://docs.couchbase.com/mobile/2.8.0/couchbase-lite-net/api/Couchbase.Lite.Sync.Replicator.html#Couchbase_Lite_Sync_Replicator_ResetCheckpoint[ResetCheckpoint()]
has been removed.
Use the `reset:` argument when starting the replicator instead.

[#before]
===== Before
[source, java,subs="attributes+, macros+"]
----
replicator.ResetCheckpoint();
replicator.Start();
----

[#after]
===== After
[source, java,subs="attributes+, macros+"]
----
replicator.Start(true) // <.>
----
<.> Set the `reset:` argument `true` to initiate a replicator checkpoint reset

[#setloglevel]
===== SetLogLevel()
We have removed the method
https://docs.couchbase.com/mobile/2.8.0/couchbase-lite-net/api/Couchbase.Lite.Database.html#Couchbase_Lite_Database_SetLogLevel_Couchbase_Lite_Logging_LogDomain_Couchbase_Lite_Logging_LogLevel_[Database.setLogLevel()] +
Use
https://docs.couchbase.com/mobile/{major}.{minor}.{base}{empty}/couchbase-lite-net/api/Couchbase.Lite.Logging.Log.html#Couchbase_Lite_Logging_Log_Console[
Database.log.console]
instead:

[#before-2]
===== Before
[source, java,subs="attributes+, macros+"]
----
Database.SetLogLevel(LogDomain.Replicator, LogLevel.Verbose);
Database.SetLogLevel(LogDomain.Query, LogLevel.Verbose);
----

[#after-2]
===== After
[source, java,subs="attributes+, macros+"]
----
Database.Log.Console.Domains = LogDomain.All;
Database.Log.Console.LogLevel = LogLevel.Verbose;
----

[#database-compact]
==== Database.Compact
We have removed the method
https://docs.couchbase.com/mobile/2.8.0/couchbase-lite-net/api/Couchbase.Lite.Database.html#Couchbase_Lite_Database_Compact[Database.compact()]. +
Use the method
https://docs.couchbase.com/mobile/{major}.{minor}.{base}{empty}/couchbase-lite-net/api/Couchbase.Lite.Database.html#Couchbase_Lite_Database_PerformMaintenance_Couchbase_Lite_MaintenanceType_[Database.PerformMaintenance()] and the enum
https://docs.couchbase.com/mobile/{major}.{minor}.{base}{empty}/couchbase-lite-net/api/Couchbase.Lite.MaintenanceType.html[MaintenanceType]
instead

[#before-3]
===== Before
[source, java,subs="attributes+, macros+"]
----
var db = new Database("thisdb");
db.Compact()
----

[#after-3]
===== After
[source, java,subs="attributes+, macros+"]
----
var db = new Database("thisdb");

db.PerformMaintenance(MaintenanceType.Compact)
----

[#deprecated-api]
==== Deprecated API

[#match]
===== Match
We're removing
https://docs.couchbase.com/mobile/2.8.0/couchbase-lite-net/api/Couchbase.Lite.Query.IFullTextExpression.html#Couchbase_Lite_Query_IFullTextExpression_Match_System_String_[Match]
at the next major release. +
You should plan to switch to using the alternative
https://docs.couchbase.com/mobile/{major}.{minor}.{base}{empty}/couchbase-lite-net/api/Couchbase.Lite.Query.FullTextFunction.html#Couchbase_Lite_Query_FullTextFunction_Match_System_String_System_String_[FullTextFunction.match(indexName:)]
at the earliest opportunity.

[#before-4]
===== Before
[source, java,subs="attributes+, macros+"]
----
var whereClause =
        FullTextExpression.Index("nameFTSIndex").Match("'querystring'");
using (var query = QueryBuilder.Select(SelectResult.Expression(Meta.ID))
    .From(DataSource.Database(db))
    .Where(whereClause)) {
    foreach (var result in query.Execute()) {
        Console.WriteLine($"Document id {result.GetString(0)}");
    }
}
----

[#after-4]
===== After
[source, java,subs="attributes+, macros+"]
----
var whereClause =
      FullTextFunction.Match("nameFTSIndex"),"'querystring'"); // <.>
using (var query =
    QueryBuilder.Select(SelectResult.Expression(Meta.ID))
      .From(DataSource.Database(db))
      .Where(whereClause)) {
      foreach (var result in query.Execute()) {
        Console.WriteLine($"Document id {result.GetString(0)}");
      }
  }
----
<.> Here we use https://docs.couchbase.com/mobile/{major}.{minor}.{base}{empty}/couchbase-lite-net/api/Couchbase.Lite.Query.FullTextFunction.htmlFullTextFunction.match(indexName:)[FullTextFunction.match(indexName:)]
to build the query

[#isnullormissing]
===== IsNullOrMissing
We're removing
https://docs.couchbase.com/mobile/2.8.0/couchbase-lite-net/api/Couchbase.Lite.Query.IExpression.html#Couchbase_Lite_Query_IExpression_IsNullOrMissing[isNullOrMissing] +
You should plan to switch to using the alternative
https://docs.couchbase.com/mobile/{major}.{minor}.{base}{empty}/couchbase-lite-net/api/Couchbase.Lite.Query.IExpression.html#Couchbase_Lite_Query_IExpression_IsNotValued[IsNotValued()]

at the earliest opportunity.

[#before-5]
===== Before
[source, java,subs="attributes+, macros+"]
----
var query = QueryBuilder.Select(SelectResult.All())
    .From(DataSource.Database(db))
    .Where(Expression.Property("missingprop").IsNullOrMissing())
----

[#after-5]
===== After
[source, java,subs="attributes+, macros+"]
----
var query = QueryBuilder.Select(SelectResult.All())
    .From(DataSource.Database(db))
    .Where(Expression.Property("missingprop").IsNotValued())
----

[#notnullormissing]
===== NotNullOrMissing
We are removing
https://docs.couchbase.com/mobile/2.8.0/couchbase-lite-net/api/Couchbase.Lite.Query.IExpression.html#Couchbase_Lite_Query_IExpression_NotNullOrMissing[notNullOrMissing]. +
You should plan to switch to using the alternative
https://docs.couchbase.com/mobile/{major}.{minor}.{base}{empty}/couchbase-lite-net/api/Couchbase.Lite.Query.IExpression.html#Couchbase_Lite_Query_IExpression_IsValued[isValued()]
at the earliest opportunity.

| isNotValued()

[#before-6]
===== Before
[source, java,subs="attributes+, macros+"]
----
var query = QueryBuilder.Select(SelectResult.All())
    .From(DataSource.Database(db))
    .Where(Expression.Property("notmissingprop").NotNullOrMissing())
----

[#after-6]
===== After
[source, java,subs="attributes+, macros+"]
----
var query = QueryBuilder.Select(SelectResult.All())
    .From(DataSource.Database(db))
    .Where(Expression.Property("notmissingprop").IsValued())
----


[#visual-studio]
== Visual Studio

The public facing API has completely changed in Couchbase Lite 2.0 and will require a re-write to upgrade an application that is using Couchbase Lite 1.x.
To update an Xcode project built with Couchbase Lite 1.x:

* Remove the existing Couchbase Lite nuget package from the Visual Studio project.
* Remove all the Couchbase Lite 1.x dependencies -- see the https://docs-archive.couchbase.com/couchbase-lite/1.4/csharp.html#getting-started[1.x installation guide].
* Install the Couchbase Lite 2.0 framework in your project  -- see xref:csharp:gs-install.adoc[Install].
At this point, there will be many compiler warnings.
See the examples on this page to learn about the new API.
* Build & run your application.

[#downgrading-couchbase-lite]
== Downgrading Couchbase Lite

[#downgrading-between-major-releases]
=== Downgrading Between Major Releases

*No Downgrade Support* - Couchbase Lite (CBL) does not support downgrades between major versions.
Once you upgrade to a new major version, attempting to downgrade to a previous major version creates incompatibility issues.
For example, upgrading from CBL 3.x.x to CBL 4.x.x does not allow you to revert to CBL 3.x.x.

[#downgrading-between-minor-releases]
=== Downgrading Between Minor Releases

*Conditional Downgrade Support* - Downgrade support for minor releases is considered on a case-by-case basis.
The release notes for each minor version clarify whether downgrades receive support.

For example, when a new minor version such as CBL 3.1.0 becomes available, the release notes specify whether reverting to CBL 3.0.x receives support.

[#downgrading-between-patch-releases]
=== Downgrading Between Patch Releases

*Full Downgrade Support* - Downgrades between patch releases are supported.
Users can safely downgrade between different patch versions within the same minor release.

For example, if you're running CBL 3.1.6 you can downgrade to CBL 3.1.4 or CBL 3.1.3 without issues.

// Include standard footer

[#related-content]
== Related Content
++++
<div class="card-row three-column-row">
++++

[.column]
=== {empty}
.How to
* xref:csharp:gs-prereqs.adoc[Prerequisites]
* xref:csharp:gs-install.adoc[Install]
* xref:csharp:gs-build.adoc[Build and Run]

.

[.column]
=== {empty}
.Learn more
* xref:csharp:database.adoc[Databases]
* xref:csharp:document.adoc[Documents]
* xref:csharp:version-vectors.adoc[Version Vectors]
* xref:csharp:blob.adoc[Blobs]
* xref:csharp:replication.adoc[Remote Sync Gateway]
* xref:csharp:conflict.adoc[Handling Data Conflicts]

.

[.column]
=== {empty}
.Dive Deeper
https://forums.couchbase.com/c/mobile/14[Mobile Forum] |
https://blog.couchbase.com/[Blog] |
https://docs.couchbase.com/tutorials/[Tutorials]

.

++++
</div>
++++