:docname: upgrade
:page-module: csharp
:page-relative-src-path: upgrade.adoc
:page-origin-url: https://github.com/couchbase/docs-couchbase-lite.git
:page-origin-start-path:
:page-origin-refname: antora-assembler-simplification
:page-origin-reftype: branch
:page-origin-refhash: (worktree)
[#csharp:upgrade:::]
== Upgrade
:page-aliases: advance/csharp-dep-upgrade.adoc, dep-upgrade.adoc
:page-role:



// BEGIN -- inclusion -- {module-partials}_define_module_attributes.adoc
//  Usage:  Here we define module specific attributes. It is invoked during the compilation of a page,
//          making all attributes available for use on the page.
//  UsedBy: ROOT:partial$_std_cbl_hdr.adoc

// BEGIN::module page attributes
// :source-language: Java

// :snippet-p2psync-ws: {snippets-p2psync-ws--csharp}
// SET full maintenance version number

// VECTOR SEARCH attributes

// END::module page attributes


// BEGIN - Set attributes pointing to API references for this module


// Supporting Data Type Classes

// COLLECTION CLASSES


// DATABASE CLASSES



//Database.SAVE



//Database.DELETE


// deprecated 2.8
//
// :url-api-method-database-compact: https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-net}{empty}/couchbase-lite-net/api/Couchbase.Lite.Database.html#Couchbase_Lite_Database_Compact[Database.Compact()]





// links for documents pages

// :url-api-class-dictionary: https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-net}{empty}/couchbase-lite-net/api/Couchbase.Lite.DictionaryObject.html[property accessors]



// QUERY RELATED CLASSES and METHODS

// Result Classes and Methods






// Query class and methods

// Expression class and methods
// :url-api-method-expression-like: https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-net}{empty}/couchbase-lite-net/api/Couchbase.Lite.Query.IExpression.html#Couchbase_Lite_Query_IExpression_Like_Couchbase_Lite_Query_IExpression_

// ArrayFunction class and methods


// Function class and methods
//

// Where class and methods
//

// orderby class and methods
//

// GroupBy class and methods
//





// PEER-TO-PEER CLASSES

// URLENDPOINT CLASSES




// :url-api-references-tlsidentity-property: https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-net}{empty}/couchbase-lite-net/api/Couchbase.Lite.P2P.TLSIdentity.html#Couchbase_Lite_P2P_TLSIdentity_







// https://ibsoln.github.io/betasites/api/mobile/2.8.0/couchbase-lite-csharp/com/couchbase/lite/URLEndpointListenerConfiguration.html#setPort-int-




// :url-api-references-urlendpointconfiguration-initcfg: https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-net}{empty}/couchbase-lite-net/api/Couchbase.Lite.P2P.URLEndpointListenerConfiguration.html#Couchbase_Lite_P2P_URLEndpointListenerConfiguration_initWithConfig::[-initWithConfig:]
// :url-api-references-urlendpointconfiguration-init: https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-net}{empty}/couchbase-lite-net/api/Couchbase.Lite.P2P.URLEndpointListenerConfiguration.html#Couchbase_Lite_P2P_URLEndpointListenerConfiguration_init:[-init:]




// diag: Env+Module csharp


// AUTHENTICATORS




// REPLICATOR API CLASSES



// :url-api-references-replicator-abs: https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-net}{empty}/couchbase-lite-net/api/Couchbase.Lite.Sync.AbstractReplicator.html
// :url-api-class-replicator-abs: {url-api-references-replicator-abs}[AbstractReplicator]
// :url-api-properties-replicator-abs: {url-api-references-replicator-abs}#









//:url-api-property-replicator-status-activity: https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-net}{empty}/couchbase-lite-net/api/Couchbase.Lite.Sync.Replicator.html#s:18CouchbaseLitecsharp10ReplicatorC13ActivityLevelO


// REPLICATORSTATUS


// ReplicatorConfiguration API





// :url-api-prop-replicator-config-auth-get: https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-net}{empty}/couchbase-lite-net/api/Couchbase.Lite.Sync.ReplicatorConfiguration.html#Couchbase_Lite_Sync_ReplicatorConfiguration_getAuthenticator--[getAuthenticator]



// Begin Replicator Retry Config
// End Replicator Retry Config




// replaced
// replaced

// :url-api-enum-replicator-config-ServerCertificateVerificationMode: https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-net}{empty}/couchbase-lite-net/api/Couchbase.Lite.Sync.ReplicatorConfiguration.html{Enums/ServerCertificateVerificationMode.html[serverCertificateVerificationMode enum]
// // replaces ^^
// :url-api-prop-replicator-config-AcceptOnlySelfSignedServerCertificate: https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-net}{empty}/couchbase-lite-net/api/Couchbase.Lite.Sync.ReplicatorConfiguration.html#Couchbase_Lite_Sync_ReplicatorConfiguration_setAcceptOnlySelfSignedServerCertificate-boolean-[setAcceptOnlySelfSignedServerCertificate]





// Meta API




// BEGIN Logs and logging references








// END  Logs and logging references

// End -- API References attributes

// END - Set attributes pointing to API references for this module

// END -- inclusion -- csharp:partial$_define_module_attributes.adoc

// BEGIN::module page attributes
//:source-language: csharp
// :snippet-p2psync-ws: {snippets-p2psync-ws--csharp}

// END::Local page attributes



[IMPORTANT]
--
On upgrading from a 2.x release, all Couchbase Lite databases will be automatically re-indexed on initial database open. +
This can result in a delay before the database is usable.
--


[discrete#csharp:upgrade:::3-2-0-upgrade]
=== {major}.{minor}.{base}{empty} Upgrade

NOTE: This upgrade requires all 2.x databases be reindexed on initial open.

The action will take place automatically and can lead to some delay in the database becoming available for use in your application.

In addition, if you are syncing with a {major}.{minor}.{base}{empty} Sync Gateway, you should be aware of the significant configuration enhancements introduced and their impact.
This is a one-way conversion.

[discrete#csharp:upgrade:::api-changes]
==== API Changes


This content introduces the changes made to the pass:q,a[pass:q,a[Couchbase{nbsp}Lite]] for C#.Net API for release {major}.{minor}.{base}{empty}.

Starting from this release pass:q,a[pass:q,a[Couchbase{nbsp}Lite]] for C#.Net requires _Visual Studio 2019+_ and uses .Net Core 3.1 (updating from .Net Core 2.0).

[discrete#csharp:upgrade:::breaking-change]
===== Breaking Change

The function https://docs.couchbase.com/mobile/2.8.0/couchbase-lite-net/api/Couchbase.Lite.Query.Function.html#Couchbase_Lite_Query_Function_Atan2_Couchbase_Lite_Query_IExpression_Couchbase_Lite_Query_IExpression_[ATAN2(x, y)],
which returns the principal value of the arc tangent of y/x, now becomes
https://docs.couchbase.com/mobile/{major}.{minor}.{base}{empty}/couchbase-lite-net/api/Couchbase.Lite.Query.Function.html#Couchbase_Lite_Query_Function_Atan2_Couchbase_Lite_Query_IExpression_Couchbase_Lite_Query_IExpression_[ATAN2(y, x)];
that is, the arguments are reversed in line with common notation.


[discrete#csharp:upgrade:::removed]
===== Removed

[discrete#csharp:upgrade:::activate]
====== Activate

We have removed the method `Activate()` from *all* platform support libraries *except* `Support.Android` (Xamarin Android)


[discrete#csharp:upgrade:::enabletextlogging]
====== EnableTextLogging()
We have removed the obsolete method `EnableTextLogging()` from all the platform support libraries.


[discrete#csharp:upgrade:::resetcheckpoint]
====== ResetCheckpoint

The method
https://docs.couchbase.com/mobile/2.8.0/couchbase-lite-net/api/Couchbase.Lite.Sync.Replicator.html#Couchbase_Lite_Sync_Replicator_ResetCheckpoint[ResetCheckpoint()]
has been removed.
Use the `reset:` argument when starting the replicator instead.

[discrete#csharp:upgrade:::before]
====== Before
[pass:q,a[source, java,subs="attributes+, macros+"]]
----
replicator.ResetCheckpoint();
replicator.Start();
----

[discrete#csharp:upgrade:::after]
====== After
[pass:q,a[source, java,subs="attributes+, macros+"]]
----
replicator.Start(true) // <.>

----
<.> Set the `reset:` argument `true` to initiate a replicator checkpoint reset

[discrete#csharp:upgrade:::setloglevel]
====== SetLogLevel()
We have removed the method
https://docs.couchbase.com/mobile/2.8.0/couchbase-lite-net/api/Couchbase.Lite.Database.html#Couchbase_Lite_Database_SetLogLevel_Couchbase_Lite_Logging_LogDomain_Couchbase_Lite_Logging_LogLevel_[Database.setLogLevel()] +
Use
https://docs.couchbase.com/mobile/{major}.{minor}.{base}{empty}/couchbase-lite-net/api/Couchbase.Lite.Logging.Log.html#Couchbase_Lite_Logging_Log_Console[
Database.log.console]
instead:

[discrete#csharp:upgrade:::before-2]
====== Before
[pass:q,a[source, java,subs="attributes+, macros+"]]
----
Database.SetLogLevel(LogDomain.Replicator, LogLevel.Verbose);
Database.SetLogLevel(LogDomain.Query, LogLevel.Verbose);
----

[discrete#csharp:upgrade:::after-2]
====== After
[pass:q,a[source, java,subs="attributes+, macros+"]]
----
Database.Log.Console.Domains = LogDomain.All;
Database.Log.Console.LogLevel = LogLevel.Verbose;

----


[discrete#csharp:upgrade:::database-compact]
===== Database.Compact
We have removed the method
https://docs.couchbase.com/mobile/2.8.0/couchbase-lite-net/api/Couchbase.Lite.Database.html#Couchbase_Lite_Database_Compact[Database.compact()]. +
Use the method
https://docs.couchbase.com/mobile/{major}.{minor}.{base}{empty}/couchbase-lite-net/api/Couchbase.Lite.Database.html#Couchbase_Lite_Database_PerformMaintenance_Couchbase_Lite_MaintenanceType_[Database.PerformMaintenance()] and the enum
https://docs.couchbase.com/mobile/{major}.{minor}.{base}{empty}/couchbase-lite-net/api/Couchbase.Lite.MaintenanceType.html[MaintenanceType]
instead

[discrete#csharp:upgrade:::before-3]
====== Before
[pass:q,a[source, java,subs="attributes+, macros+"]]
----
var db = new Database("thisdb");
db.Compact()
----

[discrete#csharp:upgrade:::after-3]
====== After
[pass:q,a[source, java,subs="attributes+, macros+"]]
----
var db = new Database("thisdb");

db.PerformMaintenance(MaintenanceType.Compact)

----


[discrete#csharp:upgrade:::deprecated-api]
===== Deprecated API


[discrete#csharp:upgrade:::match]
====== Match
We will remove
https://docs.couchbase.com/mobile/2.8.0/couchbase-lite-net/api/Couchbase.Lite.Query.IFullTextExpression.html#Couchbase_Lite_Query_IFullTextExpression_Match_System_String_[Match]
at the next major release. +
You should plan to switch to using the alternative
https://docs.couchbase.com/mobile/{major}.{minor}.{base}{empty}/couchbase-lite-net/api/Couchbase.Lite.Query.FullTextFunction.html#Couchbase_Lite_Query_FullTextFunction_Match_System_String_System_String_[FullTextFunction.match(indexName:)]
at the earliest opportunity.

[discrete#csharp:upgrade:::before-4]
====== Before
[pass:q,a[source, java,subs="attributes+, macros+"]]
----
var whereClause =
        FullTextExpression.Index("nameFTSIndex").Match("'querystring'");
using (var query = QueryBuilder.Select(SelectResult.Expression(Meta.ID))
    .From(DataSource.Database(db))
    .Where(whereClause)) {
    foreach (var result in query.Execute()) {
        Console.WriteLine($"Document id {result.GetString(0)}");
    }
}
----

[discrete#csharp:upgrade:::after-4]
====== After
[pass:q,a[source, java,subs="attributes+, macros+"]]
----
var whereClause =
      FullTextFunction.Match("nameFTSIndex"),"'querystring'"); // <.>
using (var query =
    QueryBuilder.Select(SelectResult.Expression(Meta.ID))
      .From(DataSource.Database(db))
      .Where(whereClause)) {
      foreach (var result in query.Execute()) {
        Console.WriteLine($"Document id {result.GetString(0)}");
      }
  }
----
<.> Here we use https://docs.couchbase.com/mobile/{major}.{minor}.{base}{empty}/couchbase-lite-net/api/Couchbase.Lite.Query.FullTextFunction.htmlFullTextFunction.match(indexName:)[FullTextFunction.match(indexName:)]
to build the query

[discrete#csharp:upgrade:::isnullormissing]
====== IsNullOrMissing
We will remove
https://docs.couchbase.com/mobile/2.8.0/couchbase-lite-net/api/Couchbase.Lite.Query.IExpression.html#Couchbase_Lite_Query_IExpression_IsNullOrMissing[isNullOrMissing] +
You should plan to switch to using the alternative
https://docs.couchbase.com/mobile/{major}.{minor}.{base}{empty}/couchbase-lite-net/api/Couchbase.Lite.Query.IExpression.html#Couchbase_Lite_Query_IExpression_IsNotValued[IsNotValued()]

at the earliest opportunity.

[discrete#csharp:upgrade:::before-5]
====== Before
[pass:q,a[source, java,subs="attributes+, macros+"]]
----
var query = QueryBuilder.Select(SelectResult.All())
    .From(DataSource.Database(db))
    .Where(Expression.Property("missingprop").IsNullOrMissing())
----

[discrete#csharp:upgrade:::after-5]
====== After
[pass:q,a[source, java,subs="attributes+, macros+"]]
----
var query = QueryBuilder.Select(SelectResult.All())
    .From(DataSource.Database(db))
    .Where(Expression.Property("missingprop").IsNotValued())
----


[discrete#csharp:upgrade:::notnullormissing]
====== NotNullOrMissing
We will remove
https://docs.couchbase.com/mobile/2.8.0/couchbase-lite-net/api/Couchbase.Lite.Query.IExpression.html#Couchbase_Lite_Query_IExpression_NotNullOrMissing[notNullOrMissing]. +
You should plan to switch to using the alternative
https://docs.couchbase.com/mobile/{major}.{minor}.{base}{empty}/couchbase-lite-net/api/Couchbase.Lite.Query.IExpression.html#Couchbase_Lite_Query_IExpression_IsValued[isValued()]
at the earliest opportunity.


| isNotValued()


[discrete#csharp:upgrade:::before-6]
====== Before
[pass:q,a[source, java,subs="attributes+, macros+"]]
----
var query = QueryBuilder.Select(SelectResult.All())
    .From(DataSource.Database(db))
    .Where(Expression.Property("notmissingprop").NotNullOrMissing())
----

[discrete#csharp:upgrade:::after-6]
====== After
[pass:q,a[source, java,subs="attributes+, macros+"]]
----
var query = QueryBuilder.Select(SelectResult.All())
    .From(DataSource.Database(db))
    .Where(Expression.Property("notmissingprop").IsValued())

----



[discrete#csharp:upgrade:::lbl-db-upgrades]
=== 1.x Databases Upgrades to 2.x

Databases created using Couchbase Lite 1.2 or later can still be used with Couchbase Lite 2.x; but will be automatically updated to the  current 2.x version.
This feature is only available for the default storage type (i.e., not a ForestDB database).

[discrete#csharp:upgrade:::encrypted-databases]
==== Encrypted Databases
The automatic migration feature does not support encrypted databases.
So if the 1.x database is encrypted you will first need to disable encryption using the Couchbase Lite 1.x API (see the https://docs-archive.couchbase.com/couchbase-lite/1.4/C#.html#database-encryption[1.x Database Guide]).

Thus, to upgrade an encrypted 1.x database, you should do the following:

// set the correct language name for 1.4 pages
.Upgrading Encrypted Databases
****
. Disable encryption using the Couchbase Lite 1.x framework (see https://docs-archive.couchbase.com/couchbase-lite/1.4/csharp.html#database-encryption[1.x encryption guide])
. Open the database file with encryption enabled using the Couchbase Lite 2.x framework.
****

Since it is not possible to package Couchbase Lite 1.x and Couchbase Lite 2.x in the same application this upgrade path would require two successive upgrades.

If you are using Sync Gateway to synchronize the database content, it may be preferable to run a pull replication from a new 2.x database with encryption enabled and delete the 1.x local database.


[discrete#csharp:upgrade:::handling-of-existing-conflicts]
==== Handling of Existing Conflicts

If there are existing conflicts in the 1.x database, the automatic upgrade process copies the default winning revision to the new database and does NOT copy any conflicting revisions.

This functionality is related to the way conflicts are now being handled in Couchbase Lite -- see xref:csharp:conflict.adoc[Handling Data Conflicts].

Optionally, existing conflicts in the 1.x database can be resolved with the https://docs-archive.couchbase.com/couchbase-lite/1.4/C#.html#resolving-conflicts[1.x API] prior to the database being upgraded.

[discrete#csharp:upgrade:::handling-of-existing-attachments]
==== Handling of Existing Attachments

Attachments persisted in a 1.x database are copied to the new database.
NOTE: The relevant Couchbase Lite API is now called the `Blob` API not the `Attachments` API.

The functionally is identical but the internal schema for attachments has changed.

Blobs are stored anywhere in the document, just like other value types.
Whereas in 1.x they were stored under the `_attachments` field.

The automatic upgrade functionality *does not* update the internal schema for attachments, so they remain accessible under the `_attachments` field.
See <<csharp:upgrade:::ex-get-att>> for how to retrieve an attachment that was created in a 1.x database with a 2.x API.

.Retrieve 1.x Attachment
[#ex-get-att]
// BEGIN inclusion -- block -- block_tabbed_code_example.adoc
//
//  Allows for abstraction of the showing of snippet examples
//  which makes displaying tabbed snippets for platforms with
//  more than one native language to show -- Android (Kotlin and Java)
//
// Surrounds code in Example block
//
//  PARAMETERS:
//    param-tags comma-separated list of tags to include/exclude
//    param-leader text for opening para of an example block
//
//  USE:
//    :param_tags: query-access-json
//    include::partial$block_show_snippet.adoc[]
//    :param_tags!:
//

[#csharp:upgrade:::ex-get-att]
====


// Show Main Snippet
[source, C#]
----
include ::csharp:example$code_snippets/Program.cs[tags="1x-attachment", indent=0]
var attachments = doc.GetDictionary("_attachments");
var avatar = attachments.GetBlob("avatar");
var content = avatar?.Content;
----




// close example block

====

// Tidy-up atttibutes created
// END -- block_show_snippet.doc

[discrete#csharp:upgrade:::replication-compatibility]
==== Replication Compatibility

The current replication protocol is not backwards compatible with the 1.x replication protocol.
Therefore, to use replication with Couchbase Lite 2.x, the target Sync Gateway instance must also be upgraded to 2.x.

Sync Gateway 2.x will continue to accept clients that connect through the 1.x protocol.
It will automatically use the 1.x replication protocol when a Couchbase Lite 1.x client connects through \http://localhost:4984/db and the 2.0 replication protocol when a Couchbase Lite 2.0 client connects through ws://localhost:4984/db.
This allows for a smoother transition to get all your user base onto a version of your application built with Couchbase Lite 2.x.


[discrete#csharp:upgrade:::visual-studio]
=== Visual Studio

The public facing API has completely changed in Couchbase Lite 2.0 and will require a re-write to upgrade an application that is using Couchbase Lite 1.x.
To update an Xcode project built with Couchbase Lite 1.x:

* Remove the existing Couchbase Lite nuget package from the Visual Studio project.
* Remove all the Couchbase Lite 1.x dependencies -- see the  https://docs-archive.couchbase.com/couchbase-lite/1.4/csharp.html#getting-started[1.x installation guide].
* Install the Couchbase Lite 2.0 framework in your project  -- see xref:csharp:gs-install.adoc[Install].
At this point, there will be many compiler warnings.
Refer to the examples on this page to learn about the new API.
* Build & run your application.



// DO NOT DELETE
// Include standard footer
// :param-add3-title: {empty}
// :param-reference: reference-p2psync


[discrete#csharp:upgrade:::related-content]
=== Related Content
++++
<div class="card-row three-column-row">
++++

[.column]
==== {empty}
.How to . . .
* xref:csharp:gs-prereqs.adoc[Prerequisites]
* xref:csharp:gs-install.adoc[Install]
* xref:csharp:gs-build.adoc[Build and Run]


.

[discrete.colum#csharp:upgrade:::-2n]
==== {empty}
.Learn more . . .
* xref:csharp:database.adoc[Databases]
* xref:csharp:document.adoc[Documents]
* xref:csharp:blob.adoc[Blobs]
* xref:csharp:replication.adoc[Remote Sync Gateway]
* xref:csharp:conflict.adoc[Handling Data Conflicts]

.


[.column]
// [.content]
[discrete#csharp:upgrade:::-3]
==== {empty}
.Dive Deeper . . .
//* Community
https://forums.couchbase.com/c/mobile/14[Mobile Forum] |
https://blog.couchbase.com/[Blog] |
https://docs.couchbase.com/tutorials/[Tutorials]


.



++++
</div>
++++
// [.pane__frames.cols-3]
// == Related Content

// .How-to ...

// * xref:csharp:p2psync-custom.adoc[Integrate Custom Listener]
// * xref:csharp:p2psync-websocket.adoc[Peer-to-Peer]

// .Learn more ...

// * include how-to links as relevant,
// * include how-to links as relevant,

// .Dive Deeper ...

// * Reference content
// ** https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-net}{empty}/couchbase-lite-net[API References]
// // +
// include::shared-mobile::partial$block-related-content-menulinks.adoc[tags=community]

// include::ROOT:partial$_unset-platform.adoc[]
// DO NOT DELETE


== Troubleshooting

