= Working with Vector Search
:page-status: Beta
:page-edition: Enterprise
:page-aliases: 
ifdef::show_edition[:page-edition: {release}]
ifdef::prerelease[:page-status: {prerelease}]
:page-role:
:description: Use Vector Search with Full Text Search and Query.
:keywords: edge AI api swift ios macos apple vector search generative

[abstract]
{description}

== Use Vector Search

To configure a project to use vector search, follow the xref:csharp:gs-install.adoc[installation instructions] to add the Vector Search extension.

NOTE: You must install Couchbase Lite to use the Vector Search extension.

== Create a Vector Index

This method shows how you can create the default vector index configuration using the Couchbase Lite Vector Search extension.

[source, csharp]
----

include::csharp:example$code_snippets/VectorSearch.cs[tags=vs-create-default-config]

----

First, we initialize the `config` object with a new `VectorIndexConfiguration` object intialized with the following parameters:

* The expression of the data as a vector.

* The width or `dimensions` of the vector index is set to `3`.

* The amount of `centroids` is set to `2`.
This means that there will be two buckets with a single centroid each that gathers together similar vectors.

There are also some default values that we did not set with the `VectorIndexConfiguration()` method, these are:

* The encoding type - 8 bit Scalar Quantization.

* The distance metric - Squared Euclidean.

* The minimum and maximum number of vectors for training the index.

The method below shows the generation of a custom vector index configuration.

[source, csharp]
----

include::csharp:example$code_snippets/VectorSearch.cs[tags=vs-create-custom-config]

----

NOTE: The number of vectors, the width or dimensions of the vectors and the training size can incur high CPU and memory costs as the size of each variable increases.
This is because the training vectors have to be resident on the machine.

=== Vector Index Configuration

The table below displays the different configurations you can modify within your `VectorIndexConfiguration()` function.
For more information on specific configurations, see xref:csharp:vector-search.adoc[Vector Search.]

IMPORTANT: The beta release currently only supports the format of vectors as an array of numbers.

.Vector Index Configuration Options
[cols ="4*"]
|===
|Configuration Name |Is Required |Default Configuration |Further Information

|Expression
|Required
|No default
| A SQL++ expression indicating where to get the vectors. 
A document property for embedded vectors
`prediction()` to call a registered Predictive model.
|Number of Dimensions
|Required
|No default
|2-2048
|Number of Centroids
|Required
|No default
|1-64000. The general guideline is an approximate square root of the number of documents
|Distance Metric
|Optional
|Euclidean Distance
|You can also configure Cosine Distance as your Distance Metric
|Encoding
|Optional
| Scalar Quantizer(SQ) or SQ-8 bits
a|There are three possible configurations:

* None
No compression, No data loss
* Scalar Quantizer (SQ) or SQ-8 bits (Default)
Reduces the number of bits per dimension 
* Product Quantizer (PQ)
Reduces the number of dimensions and bits per dimension

|Training Size
|Optional
a|There are defaults for both the minimum and maximum training size for training the vectors

* The minimum training size is set to 25x the number of Centroids

* The maximum training size is set to 256x the number of Centroids
|

|===

CAUTION: Altering the default training sizes could be detrimental to the accuracy of returned results produced by the model and total computation time.

== Generating Vectors

You can use two methods to generate vectors in Couchbase Lite:

. You can call a Machine Learning(ML) model, and embed the generated vectors inside the documents.

. You can use the `prediction()` function to generate vectors to be indexed for each document at the indexing time.

Below are example configurations of the previously mentioned methods.

=== Create a Vector Index with Embeddings

This method shows you how to create a Vector Index with embeddings.

[source, csharp]
----

include::csharp:example$code_snippets/VectorSearch.cs[tags=vs-create-index]

----

. First, create the standard configuration, setting up an expressions, number of dimensions and number of centroids for the vector embedding.

. Next, create a collection variable passing it the contents of a given collection from our `database` object, in our case, the `colors` collection.

. Finally, create a vector index, `colors_index`, on a collection and pass it our configuration.

=== Create Vector Index Embeddings from a Predictive Model

This method generates vectors to be indexed for each document at the index time by using the `prediction()` function.
The key difference to note is that the `config` object uses the output of the `prediction()` function as the `expression` parameter to generate the color embedding.

[source, csharp]
----
        
include::csharp:example$code_snippets/VectorSearch.cs[tags=vs-create-predictive-index]

----

NOTE: You can use less storage by using the `prediction()` function as the encoded vectors will only be stored in the index. 
However, the index time will be longer as vector embedding generation is occurring at run time.

== Vector SQL++ Functions

Couchbase Lite currently supports two SQL++ functions, `vector_match()` and `vector_distance()`.

=== `vector_match(vectorIndexIdentifier, targetVectorExpr, [limit = 3])`

[cols = "3*"]
|===
|Parameter |Is Required |Description

|vectorIndexIdentifier
|Required
|The name of the vector index to perform the vector search on.
|targetVectorExpr
|Required
|The target vector expression that returns a vector in the form of an array of numbers.
|limit
|Optional
|The limit number of the returned matched results.
The maximum number allowed is 10000. An error will be returned when creating a query with a limit greater than 10000.

|===

NOTE: The default value for the `limit` parameter is 3.

=== Use `vector_match()`

[source, csharp]
----
        
include::csharp:example$code_snippets/VectorSearch.cs[tags=vs-use-vector-match]

----

This function performs vector search against a specific vector index identifier for the specified vector expression.
If the specified index does not exist, an error will occur on creation of the query.
The matched vectors will be returned up to the specified limit number, if the limit is not specified then the default value will be used. 
The returned vectors are sorted by their distance values in ascending order by default.

IMPORTANT: Similar to the xref:csharp:fts.adoc[Full Text Search] `match()` function, `vector_match()` can only be called alone or at the top level `AND` expression.

=== `vector_distance(vectorIndexIdentifier)`

[cols = "3*"]
|===
|Parameter |Is Required |Description

|vectorIndexIdentifier
|Required
|The name of the vector index.

|===

=== Use `vector_distance()`

[source, csharp]
----

include::csharp:example$code_snippets/VectorSearch.cs[tags=vs-use-vector-distance]

----

This function returns the distance between the target vector specified in the `vector_match()` function and the matched vector in the specified vector index based on the distance metric set in the index configuration.

== See Also

* xref:csharp:gs-install.adoc[Installation Instructions]

* xref:csharp:vector-search.adoc[Vector Search]

* xref:csharp:fts.adoc[Full Text Search]