= Couchbase Lite API for Java (Android)
include::ROOT:partial$_attributes-local.adoc[]
// :snippet: ROOT:example$/java-android/app/src/main/java/com/couchbase/code_snippets/Examples.java
// :ziputils: ROOT:example$/java-android/app/src/main/java/com/couchbase/code_snippets/ZipUtils.java
// :source-language: java
// :version: 2.7.0
// :packageNm: couchbase-lite-android
// :blank-field: ____
// :url-issues-java: https://github.com/couchbase/couchbase-lite-android/issues
// :url-api-references: http://docs.couchbase.com/mobile/{version}/couchbase-lite-android

== API References

{url-api-references}[Java SDK API References]

== Initializer

Your first step in using the API must be to call its initializer.
An exception is raised if any other API method is invoked before the  initializer.

[source]
----
include::{snippet}[tag=sdk-initializer,indent=0]
----

== Database

=== New Database

As the top-level entity in the API, new databases can be created using the `Database` class by passing in a name, configuration, or both.
The following example creates a database using the `Database(String name, DatabaseConfiguration config)` method.

[source]
----
include::{snippet}[tag=new-database,indent=0]
----

Just as before, the database will be created in a default location.
Alternatively, the `Database(string name, DatabaseConfiguration config)` initializer can be used to provide specific options in the {url-api-references}/com/couchbase/lite/DatabaseConfiguration.html[`DatabaseConfiguration`] object such as the database directory.

=== Database Encryption

include::ROOT:partial$database-encryption.adoc[]

=== Finding a Database File

When the application is running on the Android emulator, you can locate the application's data folder and access the database file by using the *adb* CLI tools.
For example, to list the different databases on the emulator, you can run the following commands.

[source,bash]
----
$ adb shell
$ su
$ cd /data/data/{APPLICATION_ID}/files
$ ls
----

The *adb pull* command can be used to pull a specific database to your host machine.

[source,bash]
----
$ adb root
$ adb pull /data/data/{APPLICATION_ID}/files/{DATABASE_NAME}.cblite2 .
----

=== CLI tool

include::ROOT:partial$cli-tool.adoc[]

=== Logging

If you are using a Couchbase Lite release prior to 2.5 see <<Logging functionality prior to Release 2.5, Deprecated functionality>>

include::ROOT:partial$logging.adoc[leveloffset=+2]

==== Logging functionality prior to Release 2.5

include::ROOT:partial$logging-pre2.5.adoc[]

[source, {source-language}]

----
include::{snippet}[tags=logging,indent=0]
----

=== Loading a pre-built database

include::ROOT:partial$database-load-prebuilt.adoc[]

If the database does not exist, your application should copy it from the assets folder to the app's files directory.

[source]
----
include::{snippet}[tag=prebuilt-database,indent=0]
----

In the example below, the `ZipUtils.unzip` method copies the zipped pre-built database from the APK's *assets* directory to the *files* directory.
This method is provided below for reference as it isn't included in the Couchbase Lite library.

[source]
----
include::{ziputils}[tag=ziputils-unzip,indent=0]
----

== Document

include::ROOT:partial$document.adoc[]

=== Mutability

By default, when a document is read from the database it is immutable.
The `document.toMutable()` method should be used to create an instance of the document which can be updated.

[source]
----
include::{snippet}[tag=update-document,indent=0]
----

Changes to the document are persisted to the database when the `save` method is called.

=== Typed Accessors

The `Document` class now offers a set of {url-api-references}/com/couchbase/lite/Dictionary.html[`property accessors`] for various scalar types, including boolean, integers, floating-point and strings.
These accessors take care of converting to/from JSON encoding, and make sure you get the type you're expecting.

In addition, as a convenience we offer `Date` accessors.
Dates are a common data type, but JSON doesn't natively support them, so the convention is to store them as strings in ISO-8601 format.
The following example sets the date on the `createdAt` property and reads it back using the `document.getDate(String key)` accessor method.

[source]
----
include::{snippet}[tag=date-getter,indent=0]
----

If the property doesn't exist in the document it will return the default value for that getter method (0 for `getInt`, 0.0 for `getFloat` etc.).
To check whether a given property exists in the document, you should use the {url-api-references}/com/couchbase/lite/Document.html#contains-java.lang.String-[`Document.Contains(String key)`] method.

=== Batch operations

include::ROOT:document-batch-ops.adoc[]

=== Document change events

include::ROOT:document-change-events.adoc[]

=== Document Expiration

include::ROOT:partial$document-expiration.adoc[]

== Blobs

include::ROOT:partial$blobs.adoc[]

== Query

Database queries have changed significantly.
Instead of the map/reduce views used in 1.x, they're now based on expressions, of the form "return {blank-field} from documents where {blank-field}, ordered by {blank-field}", with semantics based on Couchbase's N1QL query language.

There are several parts to specifying a query:

SELECT:: Specifies the projection, which is the part of the document that is to be returned.
FROM:: Specifies the database to query the documents from.
JOIN:: Specifies the matching criteria in which to join multiple documents.
WHERE:: Specifies the query criteria that the result must satisfy.
GROUP BY:: Specifies the query criteria to group rows by.
ORDER BY:: Specifies the query criteria to sort the rows in the result.

=== SELECT statement

With the SELECT statement, you can query and manipulate JSON data.
With projections, you retrieve just the fields that you need and not the entire document.

A SelectResult represents a single return value of the query statement.
You can specify a comma separated list of `SelectResult` expressions in the select statement of your query.
For instance the following select statement queries for the document `_id` as well as the `type` and `name` properties of all documents in the database.
In the query result, we print the `_id` and `name` properties of each row using the property name getter method.

[source,json]
----
{
    "_id": "hotel123",
    "type": "hotel",
    "name": "Apple Droid"
}
----

[source]
----
include::{snippet}[tag=query-select-meta,indent=0]
----

The `SelectResult.all()` method can be used to query all the properties of a document.
In this case, the document in the result is embedded in a dictionary where the key is the database name.
The following snippet shows the same query using `SelectResult.all()` and the result in JSON.

[source]
----
include::{snippet}[tag=query-select-all,indent=0]
----

[source,json]
----
[
    {
        "travel-sample": {
            "callsign": "MILE-AIR",
            "country": "United States",
            "iata": "Q5",
            "icao": "MLA",
            "id": 10,
            "name": "40-Mile Air",
            "type": "airline"
        }
    },
    {
        "travel-sample": {
            "callsign": "TXW",
            "country": "United States",
            "iata": "TQ",
            "icao": "TXW",
            "id": 10123,
            "name": "Texas Wings",
            "type": "airline"
        }
    }
]
----

=== WHERE statement

Similar to SQL, you can use the where clause to filter the documents to be returned as part of the query.
The select statement takes in an `Expression`.
You can chain any number of Expressions in order to implement sophisticated filtering capabilities.

==== Comparison

The {url-api-references}/com/couchbase/lite/Expression.html[comparison operators] can be used in the WHERE statement to specify on which property to match documents.
In the example below, we use the `equalTo` operator to query documents where the `type` property equals "hotel".

[source,json]
----
{
    "_id": "hotel123",
    "type": "hotel",
    "name": "Apple Droid"
}
----

[source]
----
include::{snippet}[tag=query-where,indent=0]
----

==== Collection Operators

{url-api-references}/com/couchbase/lite/ArrayFunction.html[Collection operators] are useful to check if a given value is present in an array.

===== CONTAINS Operator

The following example uses the `Function.arrayContains` to find documents whose `public_likes` array property contain a value equal to "Armani Langworth".

[source,json]
----
{
    "_id": "hotel123",
    "name": "Apple Droid",
    "public_likes": ["Armani Langworth", "Elfrieda Gutkowski", "Maureen Ruecker"]
}
----

[source]
----
include::{snippet}[tag=query-collection-operator-contains,indent=0]
----

===== IN Operator

The `IN` operator is useful when you need to explicitly list out the values to test against.
The following example looks for documents whose `first`, `last` or `username` property value equals "Armani".

[source]
----
include::{snippet}[tag=query-collection-operator-in,indent=0]
----

==== Like Operator

The {url-api-references}/com/couchbase/lite/Expression.html#like-com.couchbase.lite.Expression-[`like`] operator can be used for string matching.

The `like` operator performs **case sensitive** matches.
So if you want to make the string matching case insensitive, you would have to use `Function.lower` or `Function.upper` to transform the matched string to lowercase or uppercase equivalents.

In the example below, we are looking for documents of type `landmark` where the name property exactly matches the string "Royal engineers museum".
Note that since `like` does a case sensitive match, we use `Function.lower` to transform the matched string to the lowercase equivalent.
So the following query will return "landmark" type documents with the name matching "Royal Engineers Museum", "royal engineers museum", "ROYAL ENGINEERS MUSEUM" and so on.

[source]
----
include::{snippet}[tag=query-like-operator,indent=0]
----

==== Wildcard Match

We can use `%` sign within a `like` expression to do a wildcard match against zero or more characters.
Using wildcards allows you to have some fuzziness in your search string.

In the example below, we are looking for documents of `type` "landmark" where the name property matches any string that begins with "eng" followed by zero or more characters, the letter "e", followed by zero or more characters.
Once again, we are using `Function.lower` to make the search case insensitive.

The following query will return "landmark" `type` documents with name matching "Engineers", "engine", "english egg" , "England Eagle" and so on.
Notice that the matches may span word boundaries.

[source]
----
include::{snippet}[tag=query-like-operator-wildcard-match,indent=0]
----

==== Wildcard Character Match

We can use an `_` sign within a like expression to do a wildcard match against a single character.

In the example below, we are looking for documents of type "landmark" where the `name` property matches any string that begins with "eng" followed by exactly 4 wildcard characters and ending in the letter "r".
The following query will return "landmark" `type` documents with the `name` matching "Engineer", "engineer" and so on.

[source]
----
include::{snippet}[tag=query-like-operator-wildcard-character-match,indent=0]
----

==== Regex Operator

Similar to wildcard `like` expressions, `regex` expressions based pattern matching allow you to have some fuzziness in your search string.

The `regex` operator is case sensitive.

In the example below, we are looking for documents of `type` "landmark" where the name property matches any string (on word boundaries) that begins with "eng" followed by exactly 4 wildcard characters and ending in the letter "r".
The following query will return "landmark" type documents with name matching "Engine", "engine" and so on.
Note that the `\b` specifies that the match must occur on word boundaries.

[source]
----
include::{snippet}[tag=query-regex-operator,indent=0]
----

==== Deleted Document

Starting in Couchbase Lite 2.5, you can query documents that have been deleted (tombstones).
The following example shows how to query deleted documents in the database.

[source]
----
include::{snippet}[tag=query-deleted-documents,indent=0]
----

=== JOIN statement

The JOIN clause enables you to create new input objects by combining two or more source objects.

The following example uses a JOIN clause to find the airline details which have routes that start from RIX.
This example JOINS the document of type "route" with documents of type "airline" using the document ID (`_id`) on the "airline" document and `airlineid` on the "route" document.

[source]
----
include::{snippet}[tag=query-join,indent=0]
----

=== GROUP BY statement

You can perform further processing on the data in your result set before the final projection is generated.
The following example looks for the number of airports at an altitude of 300 ft or higher and groups the results by country and timezone.

[source,json]
----
{
    "_id": "airport123",
    "type": "airport",
    "country": "United States",
    "geo": { "alt": 456 },
    "tz": "America/Anchorage"
}
----

[source]
----
include::{snippet}[tag=query-groupby,indent=0]
----

[source,text]
----
There are 138 airports on the Europe/Paris timezone located in France and above 300 ft
There are 29 airports on the Europe/London timezone located in United Kingdom and above 300 ft
There are 50 airports on the America/Anchorage timezone located in United States and above 300 ft
There are 279 airports on the America/Chicago timezone located in United States and above 300 ft
There are 123 airports on the America/Denver timezone located in United States and above 300 ft
----

=== ORDER BY statement

It is possible to sort the results of a query based on a given expression result.
The example below returns documents of type equal to "hotel" sorted in ascending order by the value of the title property.

[source]
----
include::{snippet}[tag=query-orderby,indent=0]
----

[source,text]
----
Aberdyfi
Achiltibuie
Altrincham
Ambleside
Annan
Ardèche
Armagh
Avignon
----

=== Date/Time Functions

include::ROOT:partial$query-date-time-functions.adoc[]

== Live Query

include::ROOT:partial$live-query.adoc[]

== Predictive Query

include::ROOT:partial$predictive-query.adoc[]

== Indexing

Creating indexes can speed up the performance of queries.
While indexes make queries faster, they also make writes slightly slower, and the Couchbase Lite database file slightly larger.
As such, it is best to only create indexes when you need to optimize a specific case for better query performance.

The following example creates a new index for the `type` and `name` properties.

[source,json]
----
{
    "_id": "hotel123",
    "type": "hotel",
    "name": "Apple Droid"
}
----

[source]
----
include::{snippet}[tag=query-index,indent=0]
----

If there are multiple expressions, the first one will be the primary key, the second the secondary key, etc.

NOTE: Every index has to be updated whenever a document is updated, so too many indexes can hurt performance.
Thus, good performance depends on designing and creating the _right_ indexes to go along with your queries.

== Full-Text Search

To run a full-text search (FTS) query, you must have created a full-text index on the expression being matched.
Unlike regular queries, the index is not optional.
The following example inserts documents and creates an FTS index on the `name` property.

[source]
----
include::{snippet}[tag=fts-index,indent=0]
----

Multiple properties to index can be specified in the index creation method.

With the index created, an FTS query on the property that is being indexed can be constructed and ran.
The full-text search criteria is defined as a `FullTextExpression`.
The left-hand side is the full-text index to use and the right-hand side is the pattern to match.

[source]
----
include::{snippet}[tag=fts-query,indent=0]
----

In the example above, the pattern to match is a word, the full-text search query matches all documents that contain the word "buy" in the value of the `doc.name` property.

Search is supported for all languages that use whitespace to separate words.

Stemming, which is the process of fuzzy matching parts of speech, like "fast" and "faster", is supported in the following languages: danish, dutch, english, finnish, french, german, hungarian, italian, norwegian, portuguese, romanian, russian, spanish, swedish and turkish.

The pattern to match can also be in the following forms:

prefix queries::
The query expression used to search for a term prefix is the prefix itself with a "*" character appended to it.
For example:
+
....
"'lin*'"
-- Query for all documents containing a term with the prefix "lin". This will match
-- all documents that contain "linux", but also those that contain terms "linear",
--"linker", "linguistic" and so on.
....

overriding the property name that is being indexed::
Normally, a token or token prefix query is matched against the document property specified as the left-hand side of the `match` operator.
This may be overridden by specifying a property name followed by a ":" character before a basic term query.
There may be space between the ":" and the term to query for, but not between the property name and the ":" character.
For example:
+
....
'title:linux problems'
-- Query the database for documents for which the term "linux" appears in
-- the document title, and the term "problems" appears in either the title
-- or body of the document.
....

phrase queries::
A phrase query is a query that retrieves all documents that contain a nominated set of terms or term prefixes in a specified order with no intervening tokens.
Phrase queries are specified by enclosing a space separated sequence of terms or term prefixes in double quotes (").
For example:
+
....
"'"linux applications"'"
-- Query for all documents that contain the phrase "linux applications".
....

NEAR queries::
A NEAR query is a query that returns documents that contain a two or more nominated terms or phrases within a specified proximity of each other (by default with 10 or less intervening terms).
A NEAR query is specified by putting the keyword "NEAR" between two phrase, token or token prefix queries.
To specify a proximity other than the default, an operator of the form "NEAR/" may be used, where is the maximum number of intervening terms allowed.
For example:
+
....
"'database NEAR/2 "replication"'"
-- Search for a document that contains the phrase "replication" and the term
-- "database" with not more than 2 terms separating the two.
....

AND, OR & NOT query operators::
The enhanced query syntax supports the AND, OR and NOT binary set operators.
Each of the two operands to an operator may be a basic FTS query, or the result of another AND, OR or NOT set operation.
Operators must be entered using capital letters.
Otherwise, they are interpreted as basic term queries instead of set operators.
For example:
+
....
'couchbase AND database'
-- Return the set of documents that contain the term "couchbase", and the
-- term "database". This query will return the document with docid 3 only.
....
+
When using the enhanced query syntax, parenthesis may be used to specify the precedence of the various operators.
For example:
+
....
'("couchbase database" OR "sqlite library") AND linux'
-- Query for the set of documents that contains the term "linux", and at least
-- one of the phrases "couchbase database" and "sqlite library".
....

=== Ordering results

It's very common to sort full-text results in descending order of relevance.
This can be a very difficult heuristic to define, but Couchbase Lite comes with a ranking function you can use.
In the `OrderBy` array, use a string of the form `Rank(X)`, where `X` is the property or expression being searched, to represent the ranking of the result.

== Replication

include::ROOT:partial$replication-introduction.adoc[]

=== Compatibility

WARNING: The new protocol is *incompatible* with CouchDB-based databases.
And since Couchbase Lite 2 only supports the new protocol, you will need to run a version of Sync Gateway that xref:sync-gateway::prodnotes/pn-compatibility.adoc[supports it].

To use this protocol with Couchbase Lite 2.0, the replication URL should specify WebSockets as the URL scheme (see the <<Starting a Replication>> section below).
Mobile clients using Couchbase Lite 1.x can continue to use *http* as the URL scheme.
Sync Gateway 2.0 will automatically use the 1.x replication protocol when a Couchbase Lite 1.x client connects through \http://localhost:4984/db and the 2.0 replication protocol when a Couchbase Lite 2.0 client connects through "ws://localhost:4984/db".

=== Starting Sync Gateway

https://www.couchbase.com/downloads[Download Sync Gateway] and start it from the command line with the configuration file created above.

[source,bash]
----
~/Downloads/couchbase-sync-gateway/bin/sync_gateway
----

For platform specific installation instructions, refer to the Sync Gateway xref:sync-gateway::start/gs-sgw-install.adoc[installation guide].

=== Starting a Replication

Replication can be bidirectional, this means you can start a `push`/`pull` replication with a single instance.
The replication's parameters can be specified through the {url-api-references}/index.html?com/couchbase/lite/ReplicatorConfiguration.html[`ReplicatorConfiguration`] object;
for example, if you wish to start a `push` only or `pull` only replication.

The following example creates a `pull` replication with Sync Gateway.

[source]
----
class MyClass {
    Database database;
    Replicator replicator; // <1>

    void startReplication() {
        URI uri = null;
        try {
            uri = new URI("wss://10.0.2.2:4984/db"); // <2>
        } catch (URISyntaxException e) {
            e.printStackTrace();
        }
        Endpoint endpoint = new URLEndpoint(uri);
        ReplicatorConfiguration config = new ReplicatorConfiguration(database, endpoint);
        config.setReplicatorType(ReplicatorConfiguration.ReplicatorType.PULL);
        this.replicator = new Replicator(config);
        this.replicator.start();
    }

}
----
<1> A replication is an asynchronous operation.
To keep a reference to the `replicator` object, you can set it as an instance property.
<2> The URL scheme for remote database URLs has changed in Couchbase Lite 2.0.
You should now use `ws:`, or `wss:` for SSL/TLS connections.
In this example the hostname is `10.0.2.2` because the Android emulator runs in a VM that is generally accessible on `10.0.2.2` from the host machine (see https://developer.android.com/studio/run/emulator-networking[Android Emulator networking] documentation).
+
NOTE: As of Android Pie, version 9, API 28, cleartext support is disabled, by default.
Although `wss:` protocol URLs are not affected, in order to use the `ws:` protocol, applications must target API 27 or lower, or must configure application network security as described https://developer.android.com/training/articles/security-config#CleartextTrafficPermitted[here].

include::ROOT:partial$verify-replication.adoc[]

Couchbase Lite 2.0 uses WebSockets as the communication protocol to transmit data.
Some load balancers are not configured for WebSocket connections by default (NGINX for example);
so it might be necessary to explicitly enable them in the load balancer's configuration (see xref:sync-gateway::load-balancer.adoc[Load Balancers]).

By default, the WebSocket protocol uses compression to optimize for speed and bandwidth utilization.
The level of compression is set on Sync Gateway and can be tuned in the configuration file (xref:sync-gateway:ROOT:refer/config-properties.adoc#replicator_compression[`replicator_compression`]).

=== Replication Ordering

To optimize for speed, the replication protocol doesn't guarantee that documents will be received in a particular order.
So we don't recommend to rely on that when using the replication or database change listeners for example.

==== Replicator Notifications on a Custom Executor

Prior to version 2.6, Couchbase Lite spun up multiple executors.
This policy could result in too many threads being spun up.

NOTE: If no listeners are registered to listen to a replicator at the time of the most recent `start(. . .)`, then no subsequently registered listeners will receive notifications.

An executor manages a pool of threads and, perhaps, a queue in front of the executor, to handle the asynchronous callbacks.
Couchbase Lite API calls which are processed by an executor are listed below.

[source]
----
Query.addChangeListener
MessageEndpointListerner.addChangeListener
LiveQuery.addChangeListener
AbstractReplicator.addDocumentReplicationListener
AbstractReplicator.addChangeListener
Database.addChangeListener
Database.addDocumentChangeListener
Database.addDatabaseChangeListener
Database.addChangeListener
----

As of version 2.6, Couchbase sometimes uses its own internal executor to run asynchronous client code.
While this is fine for small tasks, larger tasks -- those that take significant compute time, or that perform I/O -- can block Couchbase processing.
If this happens your application will fail with a `RejectedExecutionException` and it may be necessary to create a separate executor on which to run the large tasks.

The following examples show how to specify a separate executor in the client code.
The client code executor can enforce an application policy for delivery ordering and the number of threads.

*Guaranteed Order Delivery*

[source,java]
----
/**
 * This version guarantees in order delivery and is parsimonious with space
 * The listener does not need to be thread safe (at least as far as this code is concerned).
 * It will run on only thread (the Executor's thread) and must return from a given call
 * before the next call commences.  Events may be delivered arbitrarily late, though,
 * depending on how long it takes the listener to run.
 */
public class InOrderExample {
    private static final ExecutorService IN_ORDER_EXEC = Executors.newSingleThreadExecutor();

    public Replicator runReplicator(Database db1, Database db2, ReplicatorChangeListener listener)
        throws CouchbaseLiteException {
        ReplicatorConfiguration config = new ReplicatorConfiguration(db1, new DatabaseEndpoint(db2));
        config.setReplicatorType(ReplicatorConfiguration.ReplicatorType.PUSH_AND_PULL);
        config.setContinuous(false);

        Replicator repl = new Replicator(config);
        ListenerToken token = repl.addChangeListener(IN_ORDER_EXEC, listener::changed);

        repl.start();

        return repl;
    }
}
----

*Maximum Throughput*

[source,]
----
/**
 * This version maximizes throughput.  It will deliver change notifications as quickly
 * as CPU availability allows. It may deliver change notifications out of order.
 * Listeners must be thread safe because they may be called from multiple threads.
 * In fact, they must be re-entrant because a given listener may be running on mutiple threads
 * simultaneously.  In addition, when notifications swamp the processors, notifications awaiting
 * a processor will be queued as Threads, (instead of as Runnables) with accompanying memory
 * and GC impact.
 */
public class MaxThroughputExample {
    private static final ExecutorService MAX_THROUGHPUT_EXEC = Executors.newCachedThreadPool();

    public Replicator runReplicator(Database db1, Database db2, ReplicatorChangeListener listener)
        throws CouchbaseLiteException {
        ReplicatorConfiguration config = new ReplicatorConfiguration(db1, new DatabaseEndpoint(db2));
        config.setReplicatorType(ReplicatorConfiguration.ReplicatorType.PUSH_AND_PULL);
        config.setContinuous(false);

        Replicator repl = new Replicator(config);
        ListenerToken token = repl.addChangeListener(MAX_THROUGHPUT_EXEC, listener::changed);

        repl.start();

        return repl;
    }
}
----

*Extreme Configurability*

[source]
----
/**
 * This version demonstrates the extreme configurability of the CouchBase Lite replicator callback system.
 * It may deliver updates out of order and does require thread-safe and re-entrant listeners
 * (though it does correctly synchronizes tasks passed to it using a SynchronousQueue).
 * The thread pool executor shown here is configured for the sweet spot for number of threads per CPU.
 * In a real system, this single executor might be used by the entire application and be passed to
 * this module, thus establishing a reasonable app-wide threading policy.
 * In an emergency (Rejected Execution) it lazily creates a backup executor with an unbounded queue
 * in front of it.  It, thus, may deliver notifications late, as well as out of order.
 */
public class PolicyExample {
    private static final int CPUS = Runtime.getRuntime().availableProcessors();

    private static ThreadPoolExecutor BACKUP_EXEC;

    private static final RejectedExecutionHandler BACKUP_EXECUTION
        = new RejectedExecutionHandler() {
        public void rejectedExecution(Runnable r, ThreadPoolExecutor e) {
            synchronized (this) {
                if (BACKUP_EXEC == null) { BACKUP_EXEC = createBackupExecutor(); }
            }
            BACKUP_EXEC.execute(r);
        }
    };

    private static ThreadPoolExecutor createBackupExecutor() {
        ThreadPoolExecutor exec
            = new ThreadPoolExecutor(CPUS + 1, 2 * CPUS + 1, 30, TimeUnit.SECONDS, new LinkedBlockingQueue<Runnable>());
        exec.allowCoreThreadTimeOut(true);
        return exec;
    }

    private static final ThreadPoolExecutor STANDARD_EXEC
        = new ThreadPoolExecutor(CPUS + 1, 2 * CPUS + 1, 30, TimeUnit.SECONDS, new SynchronousQueue<Runnable>());

    static { STANDARD_EXEC.setRejectedExecutionHandler(BACKUP_EXECUTION); }

    public Replicator runReplicator(Database db1, Database db2, ReplicatorChangeListener listener)
        throws CouchbaseLiteException {
        ReplicatorConfiguration config = new ReplicatorConfiguration(db1, new DatabaseEndpoint(db2));
        config.setReplicatorType(ReplicatorConfiguration.ReplicatorType.PUSH_AND_PULL);
        config.setContinuous(false);

        Replicator repl = new Replicator(config);
        ListenerToken token = repl.addChangeListener(STANDARD_EXEC, listener::changed);

        repl.start();

        return repl;
    }
}
----

=== Troubleshooting

As always, when there is a problem with replication, logging is your friend.
The following example increases the log output for activity related to replication with Sync Gateway.

[source]
----
include::{snippet}[tag=replication-logging,indent=0]
----

=== Authentication

include::ROOT:partial$authentication.adoc[]

=== Replication Status

The `replication.Status.Activity` property can be used to check the status of a replication.
For example, when the replication is actively transferring data and when it has stopped.

[source]
----
include::{snippet}[tag=replication-status,indent=0]
----

The following table lists the different activity levels in the API and the meaning of each one.

[cols="1,2"]
|===
|State |Meaning

|`STOPPED`
|The replication is finished or hit a fatal error.

|`OFFLINE`
|The replicator is offline as the remote host is unreachable.

|`CONNECTING`
|The replicator is connecting to the remote host.

|`IDLE`
|The replication caught up with all the changes available from the server.
The `IDLE` state is only used in continuous replications.

|`BUSY`
|The replication is actively transferring data.
|===

NOTE: The replication change object also has properties to track the progress (`change.status.completed` and `change.status.total`).
But since the replication occurs in batches and the total count can vary through the course of a replication, those progress indicators are not very useful from the standpoint of an app user.
Hence, these should not be used for tracking the actual progress of the replication.

anchor:repstatus-and-lifecycle[]

==== Replication Status and App Lifecycle

Couchbase Lite replications will continue running until the app terminates, unless the remote system, or the application, terminates the connection.

NOTE: Recall that the Android OS may kill an application without warning.
You should explicitly stop replication processes when they are no longer useful (for example, when they are `suspended` or `idle`) to avoid socket connections being closed by the OS, which may interfere with the replication process.

=== Handling Network Errors

If an error occurs, the replication status will be updated with an `Error` which follows the standard HTTP error codes.
The following example monitors the replication for errors and logs the error code to the console.

[source]
----
include::{snippet}[tag=replication-error-handling,indent=0]
----

When a permanent error occurs (i.e., `404`: not found, `401`: unauthorized), the replicator (continuous or one-shot) will stop permanently.
If the error is temporary (i.e., waiting for the network to recover), a continuous replication will retry to connect indefinitely and if the replication is one-shot it will retry for a limited number of times.
The following error codes are considered temporary by the Couchbase Lite replicator and thus will trigger a connection retry.

* `408`: Request Timeout
* `429`: Too Many Requests
* `500`: Internal Server Error
* `502`: Bad Gateway
* `503`: Service Unavailable
* `504`: Gateway Timeout
* `1001`: DNS resolution error

=== Replication Events

include::ROOT:partial$replication-events.adoc[]

=== Custom Headers

include::ROOT:partial$replication-custom-header.adoc[]

[source]
----
include::{snippet}[tag=replication-custom-header,indent=0]
----

=== Replication Checkpoint Reset

include::ROOT:partial$replication-checkpoint.adoc[]

[source]
----
include::{snippet}[tag=replication-reset-checkpoint,indent=0]
----

=== Replication Filters

include::ROOT:partial$replication-filters.adoc[]

== Handling Conflicts

include::ROOT:partial$handling-conflicts.adoc[]

== Database Replicas

include::ROOT:partial$database-replicas.adoc[]

== Certificate Pinning

include::ROOT:partial$::{root-commons}cert-pinning.adoc

== Peer-to-Peer Sync

.Enterprise Edition only
IMPORTANT: Peer-to-Peer Synchronization is an https://www.couchbase.com/products/editions[Enterprise Edition] feature.
You must purchase the Enterprise License which includes official https://www.couchbase.com/support-policy[Couchbase Support] to use it in production (also see the https://www.couchbase.com/licensing-and-support-faq[FAQ]).

Peer-to-Peer Synchronization allows devices running Couchbase Lite to directly sync data with each other.
As part of this, Couchbase Lite is responsible for storing the data and keeping track of the data exchange, but isn't responsible for the data transfer itself.
Sending and receiving data must be handled by the platform APIs or a third party framework.
In this section, we will refer to these third party frameworks as communication frameworks.

On Android, the https://developers.google.com/nearby/messages/overview[Nearby Messages API] would be a good choice for the Communication Framework.
This framework will handle sending and receiving messages and supports multiple transport technologies -- WiFi and Bluetooth and uses whichever is available to establish a connection between devices.

Thus, to enable peer-to-peer sync with Couchbase Lite, the application must use the Communication Framework with Couchbase Lite.
The following sections describe a typical peer-to-peer workflow.
Where applicable, we discuss how to integrate Couchbase Lite into the workflow.

In Couchbase Lite, a peer can take on one of these two roles:

* *Active Peer:* The peer that initializes the connection and replication (i.e the "client" side).
* *Passive Peer:* The passive side reacts to things that it receives but does not initiate any communication on its own (i.e. the "server" side).

=== Peer Discovery

include::ROOT:partial$p2p-peer-discovery.adoc[]

=== Peer Selection and Connection Setup

include::ROOT:partial$p2p-peer-selection.adoc[]

=== Replication Setup

include::ROOT:partial$p2p-replication-setup.adoc[]

=== Push/Pull Replication

include::ROOT:partial$p2p-push-pull-repl.adoc[]

=== Connection Teardown

include::ROOT:partial$p2p-connection-teardown.adoc[]

== Thread Safety

The Couchbase Lite API is thread safe except for calls to mutable objects: `MutableDocument`, `MutableDictionary` and `MutableArray`.
