:docname: dbreplica
:page-module: objc
:page-relative-src-path: dbreplica.adoc
:page-origin-url: https://github.com/couchbase/docs-couchbase-lite.git
:page-origin-start-path:
:page-origin-refname: antora-assembler-simplification
:page-origin-reftype: branch
:page-origin-refhash: (worktree)
[#objc:dbreplica:::]
== Intra-device Sync
:page-aliases: learn/objc-dbreplica.adoc
:page-role:
:description: Couchbase Lite Database Sync - Synchronize changes between databases on the same device


:maintenance: 1


// :param-name: objc
// :param-title: Objective C
// :param-module: objc
[abstract]
--
Description -- _{description}_ +
--


[abstract]
--
Description -- _{description}_ +
Related Content -- xref:objc:replication.adoc[Remote Sync Gateway] | xref:objc:landing-p2psync.adoc[Peer-to-Peer Sync]
--

[#objc:dbreplica:::overview]
=== Overview


Couchbase Lite supports replication between two local databases at the database, scope, or collection level.
This allows a Couchbase Lite replicator to store data on secondary storage.
It is useful in scenarios when a user's device is damaged and its data is moved to a different device.

.Replication between Local Databases


====


// Show Main Snippet
// include::objc:example$code_snippets/SampleCodeTest.m[tags="database-replica", indent=0]
[source, objc]
----
CBLDatabaseEndpoint *targetDatabase = [[CBLDatabaseEndpoint alloc] initWithDatabase:self.otherDB];
CBLReplicatorConfiguration *replConfig = [[CBLReplicatorConfiguration alloc] initWithTarget:targetDatabase];
replConfig.replicatorType = kCBLReplicatorTypePush;

NSError* error = nil;
CBLCollection *collection = [database collectionWithName:@"collection1" scope:@"scope1" error:&error];
[replConfig addCollection:collection config:nil];

self.replicator = [[CBLReplicator alloc] initWithConfig:replConfig];
[self.replicator start];
----


====


[#objc:dbreplica:::related-content]
=== Related Content
++++
<div class="card-row three-column-row">
++++

[.column]
==== {empty}
.How to . . .
* xref:objc:gs-prereqs.adoc[Prerequisites]
* xref:objc:gs-install.adoc[Install]
* xref:objc:gs-build.adoc[Build and Run]


.

[discrete.colum#objc:dbreplica:::-2n]
==== {empty}
.Learn more . . .
* xref:objc:database.adoc[Databases]
* xref:objc:document.adoc[Documents]
* xref:objc:blob.adoc[Blobs]
* xref:objc:replication.adoc[Remote Sync Gateway]
* xref:objc:conflict.adoc[Handling Data Conflicts]

.


[discrete.colum#objc:dbreplica:::-3n]
==== {empty}
.Dive Deeper . . .
https://forums.couchbase.com/c/mobile/14[Mobile Forum] |
https://blog.couchbase.com/[Blog] |
https://docs.couchbase.com/tutorials/[Tutorials]

.


++++
</div>
++++


