:docname: document
:page-module: objc
:page-relative-src-path: document.adoc
:page-origin-url: https://github.com/couchbase/docs-couchbase-lite.git
:page-origin-start-path:
:page-origin-refname: antora-assembler-simplification
:page-origin-reftype: branch
:page-origin-refhash: (worktree)
[#objc:document:::]
== Documents
:page-aliases: documents.adoc, learn/objc-document.adoc
:page-toclevels: 2@
:page-role:
:description: Couchbase Lite concepts -- Data model -- Documents



// BEGIN -- inclusion -- {module-partials}_define_module_attributes.adoc
//  Usage:  Here we define module specific attributes. It is invoked during the compilation of a page,
//          making all attributes available for use on the page.
//  UsedBy: ROOT:partial$_std_cbl_hdr.adoc

// BEGIN::module page attributes

//
// CBL-Obj-C Maintenance release number
//
:maintenance: 1
//

// VECTOR SEARCH attributes
//



// BEGIN - Set attributes pointing to API references for this module


// API Reference Links
//
//



// Supporting Data Type Classes



// DATABASE CLASSES


// Docuument Class




// Begin -- DatabaseConfiguration
// End -- DatabaseConfiguration

//Database.SAVE



//Database.DELETE


//Database.COMPACT
// deprecated 2.8
//
// :url-api-method-database-compact: https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-ios}{empty}/couchbase-lite-objc/Classes/CBLDatabase.html#/c:objc(cs)CBLDatabase(im)compact:[CBLDatabase.compact()]






// QUERY RELATED CLASSES and METHODS

// Result Classes and Methods




// Query class and methods





// Expression class and methods
// :url-api-references-query-classes: https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-ios}{empty}/couchbase-lite-objc/Classes/[Query Class index]


// ArrayFunction class and methods


// Function class and methods
//

// Where class and methods
//
// https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-ios}{empty}/couchbase-lite-objc/Classes/CBLWhere.html
// NOT SET[Where]

// orderby class and methods
//
// https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-ios}{empty}/couchbase-lite-objc/Classes/CBLOrderBy.html

// GroupBy class and methods
//
// https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-ios}{empty}/couchbase-lite-objc/Classes/CBLGroupBy.html
// NOT SET[GroupBy]

// URLEndpointConfiguration





















// diag: Env+Module objc


// Replicator API











// Note there is a replicator.status property AND
// a ReplicationStatus class/struct --- oh yes, easy to confuse.

//:url-api-property-replicator-status-activity: https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-ios}{empty}/couchbase-lite-objc/Classes/CBLReplicator.html#/s:18CouchbaseLiteobjc10ReplicatorC13ActivityLevelO







// ReplicatorConfiguration API











// Begin Replicator Retry Config
// End Replicator Retry Config


// :url-api-prop-replicator-config-ServerCertificateVerificationMode: https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-ios}{empty}/couchbase-lite-objc/Classes/CBLReplicatorConfiguration.html#/c:objc(cs)CBLReplicatorConfiguration(py)serverCertificateVerificationMode[serverCertificateVerificationMode]

// :url-api-enum-replicator-config-ServerCertificateVerificationMode: https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-ios}{empty}/couchbase-lite-objc/Classes/CBLReplicatorConfiguration.html{Enums/ServerCertificateVerificationMode.html[serverCertificateVerificationMode enum]








// Meta API




// BEGIN Logs and logging references
// :url-api-class-logging: https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-ios}{empty}/couchbase-lite-objcLogging.html[CBLLogging classes]







// END  Logs and logging references

// End define module specific attributes

// BEGIN::module page attributes
// :snippet-p2psync-ws: {snippets-p2psync-ws--objc}
// END::Local page attributes

// Inclusion
[abstract]
--
Description -- _{description}_ +
Related Content -- xref:objc:database.adoc[Databases] | xref:objc:blob.adoc[Blobs] | xref:objc:indexing.adoc[Indexing] |
--




[discrete#objc:document:::overview]
=== Overview


[discrete#objc:document:::document-structure]
==== Document Structure

In pass:q,a[_pass:q,a[pass:q,a[Couchbase{nbsp}Lite]]_] the term 'document' refers to an entry in the database.
You can compare it to a record, or a row in a table.

Each document has an ID or unique identifier.
This ID is similar to a primary key in other databases.

You can specify the ID programmatically.
If you omit it, it will be automatically generated as a UUID.

NOTE: Couchbase documents are assigned to a <<objc:database:::database-concepts,Collection>>.
The ID of a document must be unique within the Collection it is written to.
You cannot change it after you have written the document.

The document also has a value which contains the actual application data.
This value is stored as a dictionary of key-value (k-v) pairs.
The values can be made of up several different <<objc:document:::data-types>> such as numbers, strings, arrays, and nested objects.


[discrete#objc:document:::data-encoding]
==== Data Encoding

The document body is stored in an internal, efficient, binary form called
https://github.com/couchbaselabs/fleece#readme[Fleece].
This internal form can be easily converted into a manageable native dictionary format for manipulation in applications.

Fleece data is stored in the smallest format that will hold the value whilst maintaining the integrity of the value.






[discrete#objc:document:::data-types]
==== Data Types

The `Document` class offers a set of property accessors for various scalar types, such as:

* Boolean
* Date
* Double
* Float
* Int
* Long
* String

These accessors take care of converting to/from JSON encoding, and make sure you get the type you expect.

In addition to these basic data types Couchbase Lite provides for the following:

Dictionary:: represents a read-only key-value pair collection
MutableDictionary:: represents a writeable key-value pair collection
Array:: represents a readonly ordered collection of objects
MutableArray:: represents a writeable collection of objects
Blob:: represents an arbitrary piece of binary data



[discrete#objc:document:::json]
==== JSON

Couchbase Lite also provides for the direct handling of JSON data implemented in most cases by the provision of a pass:a,q[`toJSON()`] method on appropriate API classes (for example, on MutableDocument, Dictionary, Blob and Array) -- see <<objc:document:::lbl-json-data>>.


[discrete#objc:document:::constructing-a-document]
=== Constructing a Document


An individual document often represents a single instance of an object in application code.

You can consider a document as the equivalent of a 'row' in a relational table,
with each of the document's attributes being equivalent to a 'column'.

Documents can contain nested structures.
This allows developers to express many-to-many relationships without requiring a reference or join table,
and is naturally expressive of hierarchical data.

Most apps will work with one or more documents, persisting them to a local database and optionally syncing them, either centrally or to the cloud.

In this section we provide an example of how you might create a `hotel` document, which provides basic contact details and price data.

.Data Model
[source]
----

hotel: {
  type: string (value = `hotel`)
  name: string
  address: dictionary {
    street: string
    city: string
    state: string
    country: string
    code: string
  }
  phones: array
  rate: float
}

----

[discrete#objc:document:::ex-usage]
==== Open a Database

First open your database.
If the database does not already exist, Couchbase Lite will create it for you.

Couchbase documents are assigned to a <<objc:database:::database-concepts,Collection>>.
All the CRUD examples in this document operate on a `collection` object (here, the Default Collection).

// BEGIN inclusion -- block -- block_tabbed_code.adoc
//
//  Allows for abstraction of the showing of snippet examples
//  which makes displaying tabbed snippets for platforms with
//  more than one native language to show -- Android (Kotlin and Java)
//
// This version does not add an example block
//
//  PARAMETERS:
//    param-tags comma-separated list of tags to include/exclude
//
//  USE:
//    :param_tags: query-access-json
//    include::partial$block_show_snippet.adoc[]
//    :param_tags!:
//


// Show Main Snippet
[source, objc]
----
include ::objc:example$code_snippets/SampleCodeTest.m[tags="datatype_usage_createdb", indent=0]
// Get the database (and create it if it doesn’t exist).

NSError *error;
CBLDatabase *database = [[CBLDatabase alloc] initWithName:@"hoteldb" error:&error];
CBLCollection *collection = [database defaultCollection:&error];

----





// Tidy-up attributes created
// END -- block_tabbed_code.adoc

See xref:objc:database.adoc[Databases] for more information

[discrete#objc:document:::create-a-document]
==== Create a Document

Now create a new document to hold your application's data.

Use the mutable form, so that you can add data to the document.

// BEGIN inclusion -- block -- block_tabbed_code.adoc
//
//  Allows for abstraction of the showing of snippet examples
//  which makes displaying tabbed snippets for platforms with
//  more than one native language to show -- Android (Kotlin and Java)
//
// This version does not add an example block
//
//  PARAMETERS:
//    param-tags comma-separated list of tags to include/exclude
//
//  USE:
//    :param_tags: query-access-json
//    include::partial$block_show_snippet.adoc[]
//    :param_tags!:
//


// Show Main Snippet
[source, objc]
----
include ::objc:example$code_snippets/SampleCodeTest.m[tags="datatype_usage_createdoc", indent=0]
// Create your new document
// The lack of 'const' indicates this document is mutable
CBLMutableDocument *mutableDoc = [[CBLMutableDocument alloc] init];


----





// Tidy-up attributes created
// END -- block_tabbed_code.adoc

For more on using *Documents*, see <<objc:document:::document-initializers>> and <<objc:document:::mutability>>.

[discrete#objc:document:::create-a-dictionary]
==== Create a Dictionary

Now create a mutable dictionary (`address`).

Each element of the dictionary value will be directly accessible via its own key.

// BEGIN inclusion -- block -- block_tabbed_code.adoc
//
//  Allows for abstraction of the showing of snippet examples
//  which makes displaying tabbed snippets for platforms with
//  more than one native language to show -- Android (Kotlin and Java)
//
// This version does not add an example block
//
//  PARAMETERS:
//    param-tags comma-separated list of tags to include/exclude
//
//  USE:
//    :param_tags: query-access-json
//    include::partial$block_show_snippet.adoc[]
//    :param_tags!:
//


// Show Main Snippet
[source, objc]
----
include ::objc:example$code_snippets/SampleCodeTest.m[tags="datatype_usage_mutdict", indent=0]
// Create and populate mutable dictionary
// Create a new mutable dictionary and populate some keys/values
CBLMutableDictionary *address = [[CBLMutableDictionary alloc] init];
[address setString:@"1 Main st" forKey:@"street"];
[address setString:@"San Francisco" forKey:@"city"];
[address setString:@"CA" forKey:@"state"];
[address setString:@"USA" forKey:@"country"];
[address setString:@"90210" forKey:@"code"];

----





// Tidy-up attributes created
// END -- block_tabbed_code.adoc

Learn more about <<objc:document:::using-dictionaries>>.

[discrete#objc:document:::create-an-array]
==== Create an Array

Since the hotel may have multiple contact numbers, provide a field (`phones`) as a mutable array.

// BEGIN inclusion -- block -- block_tabbed_code.adoc
//
//  Allows for abstraction of the showing of snippet examples
//  which makes displaying tabbed snippets for platforms with
//  more than one native language to show -- Android (Kotlin and Java)
//
// This version does not add an example block
//
//  PARAMETERS:
//    param-tags comma-separated list of tags to include/exclude
//
//  USE:
//    :param_tags: query-access-json
//    include::partial$block_show_snippet.adoc[]
//    :param_tags!:
//


// Show Main Snippet
[source, objc]
----
include ::objc:example$code_snippets/SampleCodeTest.m[tags="datatype_usage_mutarray", indent=0]
// Create and populate mutable array
CBLMutableArray *phones = [[CBLMutableArray alloc] init];
[phones addString:@"650-000-0000"];
[phones addString:@"650-000-0001"];

----





// Tidy-up attributes created
// END -- block_tabbed_code.adoc

Learn more about <<objc:document:::using-arrays>>

[discrete#objc:document:::populate-a-document]
==== Populate a Document

Now add your data to the mutable document created earlier.
Each data item is stored as a key-value pair.

// BEGIN inclusion -- block -- block_tabbed_code.adoc
//
//  Allows for abstraction of the showing of snippet examples
//  which makes displaying tabbed snippets for platforms with
//  more than one native language to show -- Android (Kotlin and Java)
//
// This version does not add an example block
//
//  PARAMETERS:
//    param-tags comma-separated list of tags to include/exclude
//
//  USE:
//    :param_tags: query-access-json
//    include::partial$block_show_snippet.adoc[]
//    :param_tags!:
//


// Show Main Snippet
[source, objc]
----
include ::objc:example$code_snippets/SampleCodeTest.m[tags="datatype_usage_populate", indent=0]
// Initialize and populate the document

// Add document type and hotel name as string
[mutableDoc setString:@"hotel" forKey:@"type"];
[mutableDoc setString:@"Hotel Java Mo" forKey:@"name"];

// Add average room rate (float)
[mutableDoc setFloat:121.75 forKey:@"room_rate"];

// Add address (dictionary)
[mutableDoc setDictionary:address forKey:@"address"];

// Add phone numbers(array)
[mutableDoc setArray:phones forKey:@"phones"];

----





// Tidy-up attributes created
// END -- block_tabbed_code.adoc


NOTE: Couchbase recommend using a `type` attribute to define each logical document type.


[discrete#objc:document:::save-a-document]
==== Save a Document

Now persist the populated document to your Couchbase Lite database.
This will auto-generate the document id.

// BEGIN inclusion -- block -- block_tabbed_code.adoc
//
//  Allows for abstraction of the showing of snippet examples
//  which makes displaying tabbed snippets for platforms with
//  more than one native language to show -- Android (Kotlin and Java)
//
// This version does not add an example block
//
//  PARAMETERS:
//    param-tags comma-separated list of tags to include/exclude
//
//  USE:
//    :param_tags: query-access-json
//    include::partial$block_show_snippet.adoc[]
//    :param_tags!:
//


// Show Main Snippet
[source, objc]
----
include ::objc:example$code_snippets/SampleCodeTest.m[tags="datatype_usage_persist", indent=0]
[collection saveDocument:mutableDoc error:&error];

----





// Tidy-up attributes created
// END -- block_tabbed_code.adoc

[discrete#objc:document:::close-the-database]
==== Close the Database

With your document saved, you can now close our Couchbase Lite database.

// BEGIN inclusion -- block -- block_tabbed_code.adoc
//
//  Allows for abstraction of the showing of snippet examples
//  which makes displaying tabbed snippets for platforms with
//  more than one native language to show -- Android (Kotlin and Java)
//
// This version does not add an example block
//
//  PARAMETERS:
//    param-tags comma-separated list of tags to include/exclude
//
//  USE:
//    :param_tags: query-access-json
//    include::partial$block_show_snippet.adoc[]
//    :param_tags!:
//


// Show Main Snippet
[source, objc]
----
include ::objc:example$code_snippets/SampleCodeTest.m[tags="datatype_usage_closedb", indent=0]
if (![self.database close:&error])
    NSLog(@"Error closing db:%@", error);

----





// Tidy-up attributes created
// END -- block_tabbed_code.adoc



[discrete#objc:document:::working-with-data]
=== Working with Data




[discrete#objc:document:::date-accessors]
==== Date accessors

Couchbase Lite offers _Date_ accessors as a convenience.
Dates are a common data type, but JSON doesn't natively support them, so the convention is to store them as strings in ISO-8601 format.

.Date Getter
[#ex-date-getter]
// BEGIN inclusion -- block -- block_tabbed_code_example.adoc
//
//  Allows for abstraction of the showing of snippet examples
//  which makes displaying tabbed snippets for platforms with
//  more than one native language to show -- Android (Kotlin and Java)
//
// Surrounds code in Example block
//
//  PARAMETERS:
//    param-tags comma-separated list of tags to include/exclude
//    param-leader text for opening para of an example block
//
//  USE:
//    :param_tags: query-access-json
//    include::partial$block_show_snippet.adoc[]
//    :param_tags!:
//

[#objc:document:::ex-date-getter]
====

pass:q,a[This example sets the date on the `createdAt` property and reads it back using the https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-ios}{empty}/couchbase-lite-objc/Protocols/CBLDictionary.html#/c:objc(pl)CBLDictionary(im)dateForKey:[dateForKey:] accessor method.]

// Show Main Snippet
[source, objc]
----
include ::objc:example$code_snippets/SampleCodeTest.m[tags="date-getter", indent=0]
[doc setValue:[NSDate date] forKey:@"createdAt"];
NSDate *date = [doc dateForKey:@"createdAt"];
----




// close example block

====

// Tidy-up atttibutes created
// END -- block_show_snippet.doc


[discrete#objc:document:::using-dictionaries]
==== Using Dictionaries

.API References

* https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-ios}{empty}/couchbase-lite-objc/Classes/CBLDictionary.html[CBLDictionary]

* https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-ios}{empty}/couchbase-lite-objc/Classes/CBLMutableDictionary.html[CBLMutableDictionary]


.Read Only
[#ex-dict]
// :param-leader: pass:q,a[Changes to the document are persisted to the database when the `save` method is called.]
// BEGIN inclusion -- block -- block_tabbed_code_example.adoc
//
//  Allows for abstraction of the showing of snippet examples
//  which makes displaying tabbed snippets for platforms with
//  more than one native language to show -- Android (Kotlin and Java)
//
// Surrounds code in Example block
//
//  PARAMETERS:
//    param-tags comma-separated list of tags to include/exclude
//    param-leader text for opening para of an example block
//
//  USE:
//    :param_tags: query-access-json
//    include::partial$block_show_snippet.adoc[]
//    :param_tags!:
//

[#objc:document:::ex-dict]
====


// Show Main Snippet
[source, objc]
----
include ::objc:example$code_snippets/SampleCodeTest.m[tags="datatype_dictionary", indent=0]
CBLDocument *doc = [collection documentWithID:@"doc1" error:&error];

// Getting a dictionary value from the document
CBLDictionary *dict = [doc dictionaryForKey:@"address"];

// Access a value from the dictionary
NSString *street = [dict stringForKey:@"street"];
NSLog(@"Street:: %@", street);

// Iterate dictionary
for (NSString *key in dict) {
    id value = [dict valueForKey:key];
    NSLog(@"Value:: %@", value);
}

// Create a mutable copy
CBLMutableDictionary *mutableDict = [dict toMutable];
[mutableDict setString:@"1 Great sts" forKey:@"street"];
----




// close example block

====

// Tidy-up atttibutes created
// END -- block_show_snippet.doc


.Mutable
[#ex-mutdict]
// :param-leader: pass:q,a[Changes to the document are persisted to the database when the `save` method is called.]
// BEGIN inclusion -- block -- block_tabbed_code_example.adoc
//
//  Allows for abstraction of the showing of snippet examples
//  which makes displaying tabbed snippets for platforms with
//  more than one native language to show -- Android (Kotlin and Java)
//
// Surrounds code in Example block
//
//  PARAMETERS:
//    param-tags comma-separated list of tags to include/exclude
//    param-leader text for opening para of an example block
//
//  USE:
//    :param_tags: query-access-json
//    include::partial$block_show_snippet.adoc[]
//    :param_tags!:
//

[#objc:document:::ex-mutdict]
====


// Show Main Snippet
[source, objc]
----
include ::objc:example$code_snippets/SampleCodeTest.m[tags="datatype_mutable_dictionary", indent=0]

// Create a new mutable dictionary and populate some keys/values
CBLMutableDictionary *dict = [[CBLMutableDictionary alloc] init];
[dict setString:@"1 Main st" forKey:@"street"];
[dict setString:@"San Francisco" forKey:@"city"];

// Set the dictionary to a document and save the document
CBLMutableDocument *doc = [[CBLMutableDocument alloc] init];
[doc setDictionary:dict forKey:@"address"];
NSError *error;
[collection saveDocument:doc error:&error];
----




// close example block

====

// Tidy-up atttibutes created
// END -- block_show_snippet.doc

[discrete#objc:document:::using-arrays]
==== Using Arrays

.API References
* https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-ios}{empty}/couchbase-lite-objc/Classes/CBLArray.html[CBLArray]

* https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-ios}{empty}/couchbase-lite-objc/Classes/CBLMutableArray.html[CBLMutableArray]

.Read Only
[#ex-array]
// :param-leader: pass:q,a[Changes to the document are persisted to the database when the `save` method is called.]
// BEGIN inclusion -- block -- block_tabbed_code_example.adoc
//
//  Allows for abstraction of the showing of snippet examples
//  which makes displaying tabbed snippets for platforms with
//  more than one native language to show -- Android (Kotlin and Java)
//
// Surrounds code in Example block
//
//  PARAMETERS:
//    param-tags comma-separated list of tags to include/exclude
//    param-leader text for opening para of an example block
//
//  USE:
//    :param_tags: query-access-json
//    include::partial$block_show_snippet.adoc[]
//    :param_tags!:
//

[#objc:document:::ex-array]
====


// Show Main Snippet
[source, objc]
----
include ::objc:example$code_snippets/SampleCodeTest.m[tags="datatype_array", indent=0]
NSError *error;
CBLDocument *doc = [collection documentWithID:@"doc1" error:&error];

// Getting an array value from the document
CBLArray *array = [doc arrayForKey:@"phones"];

// Get element count
NSUInteger count = array.count;
NSLog(@"Count:: %lu", (unsigned long)count);

// Access an array element by index
if (count > 0) {
    id value = [array valueAtIndex:0];
    NSLog(@"Value:: %@", value);
}

// Iterate the array
for (id value in array) {
    NSLog(@"Value:: %@", value);
}

// Create a mutable copy
CBLMutableArray *mutableArray = [array toMutable];
[mutableArray addString:@"650-000-0002"];
----




// close example block

====

// Tidy-up atttibutes created
// END -- block_show_snippet.doc

.Mutable
[#ex-mutarray]
// :param-leader: pass:q,a[Changes to the document are persisted to the database when the `save` method is called.]
// BEGIN inclusion -- block -- block_tabbed_code_example.adoc
//
//  Allows for abstraction of the showing of snippet examples
//  which makes displaying tabbed snippets for platforms with
//  more than one native language to show -- Android (Kotlin and Java)
//
// Surrounds code in Example block
//
//  PARAMETERS:
//    param-tags comma-separated list of tags to include/exclude
//    param-leader text for opening para of an example block
//
//  USE:
//    :param_tags: query-access-json
//    include::partial$block_show_snippet.adoc[]
//    :param_tags!:
//

[#objc:document:::ex-mutarray]
====


// Show Main Snippet
[source, objc]
----
include ::objc:example$code_snippets/SampleCodeTest.m[tags="datatype_mutable_array", indent=0]
// Create a new mutable array and populate data into the array
CBLMutableArray *array = [[CBLMutableArray alloc] init];
[array addString:@"650-000-0000"];
[array addString:@"650-000-0001"];

// Set the array to a document and save the document
CBLMutableDocument *doc = [[CBLMutableDocument alloc] init];
[doc setArray:array forKey:@"address"];
NSError *error;
[collection saveDocument:doc error:&error];
----




// close example block

====

// Tidy-up atttibutes created
// END -- block_show_snippet.doc


[discrete#objc:document:::using-blobs]
==== Using Blobs

For more on working with blobs, see xref:objc:blob.adoc[Blobs]


[discrete#objc:document:::document-initializers]
=== Document Initializers


You can use the following methods/initializers:

* Use the https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-ios}{empty}/couchbase-lite-objc/Classes/CBLMutableDocument.html#/c:objc(cs)CBLMutableDocument(im)init[(nonnull instancetype)init;] initializer to create a new document where the document ID is randomly generated by the database.

* Use the https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-ios}{empty}/couchbase-lite-objc/Classes/CBLMutableDocument.html#/c:objc(cs)CBLMutableDocument(im)initWithID:[(nonnull instancetype)initWithID:(nullable NSString *)documentID;] initializer to create a new document with a specific ID.

* Use the {url-api-method-collection-getdocument} method to get a document.
If the document doesn't exist in the collection, the method will return `null`.
You can use this behavior to check if a document with a given ID already exists in the collection.


.Persist a document
[#ex-persists-doc]
// BEGIN inclusion -- block -- block_tabbed_code_example.adoc
//
//  Allows for abstraction of the showing of snippet examples
//  which makes displaying tabbed snippets for platforms with
//  more than one native language to show -- Android (Kotlin and Java)
//
// Surrounds code in Example block
//
//  PARAMETERS:
//    param-tags comma-separated list of tags to include/exclude
//    param-leader text for opening para of an example block
//
//  USE:
//    :param_tags: query-access-json
//    include::partial$block_show_snippet.adoc[]
//    :param_tags!:
//

[#objc:document:::ex-persists-doc]
====

pass:q,a[The following code example creates a document and persists it to the database.]

// Show Main Snippet
[source, objc]
----
include ::objc:example$code_snippets/SampleCodeTest.m[tags="initializer", indent=0]
CBLMutableDocument *doc = [[CBLMutableDocument alloc] init];
[doc setString:@"task" forKey:@"task"];
[doc setString:@"todo" forKey:@"owner"];
[doc setString:@"task" forKey:@"createdAt"];
[collection saveDocument:doc error:&error];
----




// close example block

====

// Tidy-up atttibutes created
// END -- block_show_snippet.doc


[discrete#objc:document:::mutability]
=== Mutability


By default, a document is immutable when it is read from the database.
Use the https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-ios}{empty}/couchbase-lite-objc/Classes/CBLDocument.htmlc:objc(cs)CBLDocument(im)toMutable[(nonnull CBLMutableDocument *)toMutable;] to create an updatable instance of the document.


.Make a mutable document
[#ex-update-doc]
// BEGIN inclusion -- block -- block_tabbed_code_example.adoc
//
//  Allows for abstraction of the showing of snippet examples
//  which makes displaying tabbed snippets for platforms with
//  more than one native language to show -- Android (Kotlin and Java)
//
// Surrounds code in Example block
//
//  PARAMETERS:
//    param-tags comma-separated list of tags to include/exclude
//    param-leader text for opening para of an example block
//
//  USE:
//    :param_tags: query-access-json
//    include::partial$block_show_snippet.adoc[]
//    :param_tags!:
//

[#objc:document:::ex-update-doc]
====

pass:q,a[Changes to the document are persisted to the database when the `save` method is called.]

// Show Main Snippet
[source, objc]
----
include ::objc:example$code_snippets/SampleCodeTest.m[tags="update-document", indent=0]
CBLDocument *doc = [collection documentWithID:@"xyz" error:&error];
CBLMutableDocument *mutableDocument = [doc toMutable];
[mutableDocument setString:@"apples" forKey:@"name"];
[collection saveDocument:mutableDocument error:&error];
----




// close example block

====

// Tidy-up atttibutes created
// END -- block_show_snippet.doc

NOTE: Any user change to the value of reserved keys (`_id`, `_rev` or `_deleted`) will be detected when a document is saved and will result in an exception (Error Code 5 -- `CorruptRevisionData`) -- see also <<objc:document:::lbl-doc-constraints>>.




[discrete#objc:document:::batch-operations]
=== Batch operations

If you're making multiple changes to a database at once, it's faster to group them together.
The following example persists a few documents in batch.

.Batch operations
[#ex-batch-ops]
// BEGIN inclusion -- block -- block_tabbed_code_example.adoc
//
//  Allows for abstraction of the showing of snippet examples
//  which makes displaying tabbed snippets for platforms with
//  more than one native language to show -- Android (Kotlin and Java)
//
// Surrounds code in Example block
//
//  PARAMETERS:
//    param-tags comma-separated list of tags to include/exclude
//    param-leader text for opening para of an example block
//
//  USE:
//    :param_tags: query-access-json
//    include::partial$block_show_snippet.adoc[]
//    :param_tags!:
//

[#objc:document:::ex-batch-ops]
====


// Show Main Snippet
[source, objc]
----
include ::objc:example$code_snippets/SampleCodeTest.m[tags="batch", indent=0]
[database inBatch:&error usingBlock:^{
    for (int i = 0; i < 10; i++) {
        CBLMutableDocument *doc = [[CBLMutableDocument alloc] init];
        [doc setValue:@"user" forKey:@"type"];
        [doc setValue:[NSString stringWithFormat:@"user %d", i] forKey:@"name"];
        [doc setBoolean:NO forKey:@"admin"];

        NSError *err = nil;
        [collection saveDocument:doc error:&err];
    }
}];
----




// close example block

====

// Tidy-up atttibutes created
// END -- block_show_snippet.doc

At the *local* level this operation is still transactional: no other `Database` instances, including ones managed by the replicator can make changes during the execution of the block, and other instances will not see partial changes.
But Couchbase Mobile is a distributed system, and due to the way replication works, there's no guarantee that Sync Gateway or other devices will receive your changes all at once.


[discrete#objc:document:::document-change-events]
=== Document change events

You can register for document changes.
The following example registers for changes to the document with ID `user.john` and prints the `verified_account` property when a change is detected.


.Document change events
[#ex-doc-events]
// BEGIN inclusion -- block -- block_tabbed_code_example.adoc
//
//  Allows for abstraction of the showing of snippet examples
//  which makes displaying tabbed snippets for platforms with
//  more than one native language to show -- Android (Kotlin and Java)
//
// Surrounds code in Example block
//
//  PARAMETERS:
//    param-tags comma-separated list of tags to include/exclude
//    param-leader text for opening para of an example block
//
//  USE:
//    :param_tags: query-access-json
//    include::partial$block_show_snippet.adoc[]
//    :param_tags!:
//

[#objc:document:::ex-doc-events]
====


// Show Main Snippet
[source, objc]
----
include ::objc:example$code_snippets/SampleCodeTest.m[tags="document-listener", indent=0]
[collection addDocumentChangeListenerWithID:@"user.john" listener:^(CBLDocumentChange  *change) {
    NSError *error;
    CBLDocument *doc = [wCollection documentWithID:change.documentID error:&error];
    NSLog(@"Status ::%@)", [doc stringForKey:@"verified_account"]);
}];
----




// close example block

====

// Tidy-up atttibutes created
// END -- block_show_snippet.doc



[discrete#objc:document:::document-expiration]
=== Document Expiration

Document expiration allows users to set the expiration date for a document.
When the document expires, it is purged from the database.
The purge is not replicated to Sync Gateway.

.Set document expiration
[#ex-set-doc-exp]
// BEGIN inclusion -- block -- block_tabbed_code_example.adoc
//
//  Allows for abstraction of the showing of snippet examples
//  which makes displaying tabbed snippets for platforms with
//  more than one native language to show -- Android (Kotlin and Java)
//
// Surrounds code in Example block
//
//  PARAMETERS:
//    param-tags comma-separated list of tags to include/exclude
//    param-leader text for opening para of an example block
//
//  USE:
//    :param_tags: query-access-json
//    include::partial$block_show_snippet.adoc[]
//    :param_tags!:
//

[#objc:document:::ex-set-doc-exp]
====

This example sets the TTL for a document to 1 day from the current time.

// Show Main Snippet
[source, objc]
----
include ::objc:example$code_snippets/SampleCodeTest.m[tags="document-expiration", indent=0]
// Purge the document one day from now
NSDate *ttl = [[NSCalendar currentCalendar] dateByAddingUnit:NSCalendarUnitDay
                                                       value:1
                                                      toDate:[NSDate date]
                                                     options:0];
[collection setDocumentExpirationWithID:@"doc123" expiration:ttl error:&error];

// Reset expiration
[collection setDocumentExpirationWithID:@"doc1" expiration:nil error:&error];

// Query documents that will be expired in less than five minutes
NSTimeInterval fiveMinutesFromNow = [[NSDate dateWithTimeIntervalSinceNow:60 * 5] timeIntervalSince1970];
CBLQuery *query = [CBLQueryBuilder select:@[[CBLQuerySelectResult expression:[CBLQueryMeta id]]]
                                     from:[CBLQueryDataSource collection:collection]
                                    where:[[CBLQueryMeta expiration]
                                            lessThan:[CBLQueryExpression double:fiveMinutesFromNow]]];
----




// close example block

====

// Tidy-up atttibutes created
// END -- block_show_snippet.doc

You can set expiration for a whole Collection

[discrete#objc:document:::lbl-doc-constraints]
=== Document Constraints

Couchbase Lite APIs do not explicitly disallow the use of attributes with the underscore prefix at the top level of document.
This is to facilitate the creation of documents for use either in _local only_ mode where documents are not synced, or when used exclusively in peer-to-peer sync.

NOTE: "_id", :"_rev" and "_sequence" are reserved keywords and must not be used as top-level attributes -- see <<objc:document:::res-keys>>.

Users are cautioned that any attempt to sync such documents to Sync Gateway will result in an error.
To be future proof, you are advised to avoid creating such documents.
Use of these attributes for user-level data may result in undefined system behavior.

For more guidance -- see: xref:sync-gateway:ROOT:data-modeling.adoc[Sync Gateway - data modeling guidelines]

[#objc:document:::res-keys]
.Reserved Keys List
====

* _attachments

* _deleted footnote:fn1[Any change to this reserved key will be detected when it is saved and will result in a Couchbase exception (Error Code 5 -- `CorruptRevisionData`)]

* _id footnote:fn1[]

* _removed

* _rev footnote:fn1[]

* _sequence
====


[discrete#objc:document:::lbl-json-data]
=== Working with JSON Data

In this section::
<<objc:document:::lbl-array>>
| <<objc:document:::lbl-blob>>
| <<objc:document:::lbl-dictionary>>
| <<objc:document:::lbl-document>>
| <<objc:document:::lbl-result>>


The pass:a,q[`toJSON()`] typed-accessor means you can easily work with JSON data, native and Couchbase Lite objects.

[discrete#objc:document:::lbl-array]
==== Arrays

Convert an `ArrayObject` to and from JSON using the pass:a,q[`toJSON()`] and `toArray` methods -- see <<objc:document:::ex-array>>.

Additionally you can:

* Initialize a 'MutableArrayObject' using data supplied as a JSON string.
This is done using the `init(json)` constructor -- see: <<objc:document:::ex-array>>

* Convert an `ArrayFragment` object to a JSON String

* Set data with a JSON string using `setJSON()`

.Arrays as JSON strings
[#ex-array]
// BEGIN inclusion -- block -- block_tabbed_code_example.adoc
//
//  Allows for abstraction of the showing of snippet examples
//  which makes displaying tabbed snippets for platforms with
//  more than one native language to show -- Android (Kotlin and Java)
//
// Surrounds code in Example block
//
//  PARAMETERS:
//    param-tags comma-separated list of tags to include/exclude
//    param-leader text for opening para of an example block
//
//  USE:
//    :param_tags: query-access-json
//    include::partial$block_show_snippet.adoc[]
//    :param_tags!:
//

[#objc:document:::ex-array]
====


// Show Main Snippet
[source, objc]
----
include ::objc:example$code_snippets/SampleCodeTest.m[tags="tojson-array", indent=0]
NSString *json = @"[\"1000\",\"1001\",\"1002\",\"1003\"]";

CBLMutableArray *array = [[CBLMutableArray alloc] initWithJSON:json error:&error];

for (NSString *item in array) {
    NSLog(@"%@", item);
}

----




// close example block

====

// Tidy-up atttibutes created
// END -- block_show_snippet.doc

[discrete#objc:document:::lbl-blob]
==== Blobs
Convert a `Blob` to JSON using the `toJSON` method -- see <<objc:document:::ex-blob>>.

You can use `isBlob()` to check whether a given dictionary object is a blob or not -- see <<objc:document:::ex-blob>>.

Note that the blob object must first be saved to the database (generating the required metadata) before you can use the `toJSON` method.

[#ex-blob]
.Blobs as JSON strings
// BEGIN inclusion -- block -- block_tabbed_code_example.adoc
//
//  Allows for abstraction of the showing of snippet examples
//  which makes displaying tabbed snippets for platforms with
//  more than one native language to show -- Android (Kotlin and Java)
//
// Surrounds code in Example block
//
//  PARAMETERS:
//    param-tags comma-separated list of tags to include/exclude
//    param-leader text for opening para of an example block
//
//  USE:
//    :param_tags: query-access-json
//    include::partial$block_show_snippet.adoc[]
//    :param_tags!:
//

[#objc:document:::ex-blob]
====


// Show Main Snippet
[source, objc]
----
include ::objc:example$code_snippets/SampleCodeTest.m[tags="tojson-blob", indent=0]

CBLDocument *doc = [collection documentWithID:@"doc-1000" error:&error];
CBLBlob *blob = [doc blobForKey:@"avatar"];
NSString *json = [blob toJSON];
NSLog(@"json string is %@", json);

----




// close example block

====

// Tidy-up atttibutes created
// END -- block_show_snippet.doc

See also: xref:objc:blob.adoc[Blobs]

[discrete#objc:document:::lbl-dictionary]
==== Dictionaries

Convert a `DictionaryObject` to and from JSON using the `toJSON` and `toDictionary` methods -- see <<objc:document:::ex-dictionary>>.

Additionally you can:

* Initialize a 'MutableDictionaryObject' using data supplied as a JSON string.
This is done using the `init(json)` constructor-- see: <<objc:document:::ex-dictionary>>

* Set data with a JSON string using `setJSON()`

[#ex-dictionary]
.Dictionaries as JSON strings
// BEGIN inclusion -- block -- block_tabbed_code_example.adoc
//
//  Allows for abstraction of the showing of snippet examples
//  which makes displaying tabbed snippets for platforms with
//  more than one native language to show -- Android (Kotlin and Java)
//
// Surrounds code in Example block
//
//  PARAMETERS:
//    param-tags comma-separated list of tags to include/exclude
//    param-leader text for opening para of an example block
//
//  USE:
//    :param_tags: query-access-json
//    include::partial$block_show_snippet.adoc[]
//    :param_tags!:
//

[#objc:document:::ex-dictionary]
====


// Show Main Snippet
[source, objc]
----
include ::objc:example$code_snippets/SampleCodeTest.m[tags="tojson-dictionary", indent=0]
NSString *json = @"{\"id\":\"1002\",\"type\":\"hotel\",\"name\":\"Hotel Ned\","
"\"city\":\"Balmain\",\"country\":\"Australia\",\"description\":\"Undefined description for Hotel Ned\"}";


CBLMutableDictionary *dict = [[CBLMutableDictionary alloc] initWithJSON:json
                                                                  error:&error];

NSString *name = [dict stringForKey:@"name"];

for (NSString *key in dict) {
    NSLog(@"%@ %@", key, [dict valueForKey:key]);
}

----




// close example block

====

// Tidy-up atttibutes created
// END -- block_show_snippet.doc

[discrete#objc:document:::lbl-document]
==== Documents

Convert a `Document` to and from JSON strings using the pass:a,q[`toJSON()`] and pass:a,q[`setJSON()`] methods -- see <<objc:document:::ex-document>>.

Additionally you can:

* Initialize a 'MutableDocument' using data supplied as a JSON string.
This is done using the `init(json)` or `init(id: json:)` constructor -- see: <<objc:document:::ex-document>>

* Set data with a JSON string using `setJSON()`

.Documents as JSON strings
[#ex-document]
// BEGIN inclusion -- block -- block_tabbed_code_example.adoc
//
//  Allows for abstraction of the showing of snippet examples
//  which makes displaying tabbed snippets for platforms with
//  more than one native language to show -- Android (Kotlin and Java)
//
// Surrounds code in Example block
//
//  PARAMETERS:
//    param-tags comma-separated list of tags to include/exclude
//    param-leader text for opening para of an example block
//
//  USE:
//    :param_tags: query-access-json
//    include::partial$block_show_snippet.adoc[]
//    :param_tags!:
//

[#objc:document:::ex-document]
====


// Show Main Snippet
[source, objc]
----
include ::objc:example$code_snippets/SampleCodeTest.m[tags="query-get-all;tojson-document", indent=0]
CBLCollection *collection = [self.database createCollectionWithName:@"hotel"
                                                              scope:nil
                                                              error:&error];
CBLQuery *query = [CBLQueryBuilder select:@[[CBLQuerySelectResult expression:[CBLQueryMeta id]
                                                                          as:@"metaId"]]
                                     from:[CBLQueryDataSource collection:collection]];


CBLDocument *doc = [collection documentWithID:@"doc-1000" error:&error];
NSString *json = [doc toJSON];
NSLog(@"json %@", json);

----




// close example block

====

// Tidy-up atttibutes created
// END -- block_show_snippet.doc

[discrete#objc:document:::lbl-result]
==== Query Results as JSON

Convert a `Query Result` to JSON using its {to-JSON} accessor method.

// Inclusion block
[#ex-json]
.Using JSON Results
// BEGIN inclusion -- block -- block_tabbed_code_example.adoc
//
//  Allows for abstraction of the showing of snippet examples
//  which makes displaying tabbed snippets for platforms with
//  more than one native language to show -- Android (Kotlin and Java)
//
// Surrounds code in Example block
//
//  PARAMETERS:
//    param-tags comma-separated list of tags to include/exclude
//    param-leader text for opening para of an example block
//
//  USE:
//    :param_tags: query-access-json
//    include::partial$block_show_snippet.adoc[]
//    :param_tags!:
//

[#objc:document:::ex-json]
====

pass:q,a[Use https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-ios}{empty}/couchbase-lite-objc/Classes/CBLQueryResult.html#/c:objc(cs)CBLQueryResult(im)toJSON[CBLResult.toJSON] to transform your result string into a JSON string, which can easily be serialized or used as required in your application. See <<objc:document:::ex-json>> for a working example.]

// Show Main Snippet
[source, objc]
----
include ::objc:example$code_snippets/SampleCodeTest.m[tags="query-access-json", indent=0]
CBLQueryResultSet *rs = [query execute:&error];
for (CBLQueryResult *result in rs) {

    // Get result as a JSON string
    NSString *json = [result toJSON];

    // Get an native Obj-C object from the Json String
    NSDictionary *dict = [NSJSONSerialization JSONObjectWithData:[json dataUsingEncoding:NSUTF8StringEncoding]
                                                                     options:NSJSONReadingAllowFragments
                                                                       error:&error];

    // Log generated Json and Native objects
    // For demo/example purposes
    NSLog(@"Json String %@", json);
    NSLog(@"Native Object %@", dict);

}; // end for

----




// close example block

====

// Tidy-up atttibutes created
// END -- block_show_snippet.doc

.JSON String Format
[#objc:document:::ex-json-format]
If your query selects ALL then the JSON format will be:

[source, JSON]
----
{
  database-name: {
    key1: "value1",
    keyx: "valuex"
  }
}
----

If your query selects a sub-set of available properties then the JSON format will be:

[source, JSON]
----
{
  key1: "value1",
  keyx: "valuex"
}
----



// :param-add3-title: {empty}
// :param-reference: reference-p2psync


[discrete#objc:document:::related-content]
=== Related Content
++++
<div class="card-row three-column-row">
++++

[.column]
==== {empty}
.How to . . .
* xref:objc:gs-prereqs.adoc[Prerequisites]
* xref:objc:gs-install.adoc[Install]
* xref:objc:gs-build.adoc[Build and Run]


.

[discrete.colum#objc:document:::-2n]
==== {empty}
.Learn more . . .
* xref:objc:database.adoc[Databases]
* xref:objc:document.adoc[Documents]
* xref:objc:blob.adoc[Blobs]
* xref:objc:replication.adoc[Remote Sync Gateway]
* xref:objc:conflict.adoc[Handling Data Conflicts]

.


[.column]
// [.content]
[discrete#objc:document:::-3]
==== {empty}
.Dive Deeper . . .
//* Community
https://forums.couchbase.com/c/mobile/14[Mobile Forum] |
https://blog.couchbase.com/[Blog] |
https://docs.couchbase.com/tutorials/[Tutorials]


.



++++
</div>
++++

:page-toclevels: 2

