= Installation - Couchbase Lite on Objective-C
:page-aliases: start/objc-gs-install.adoc
:page-edition: {release}
:page-status: {prerelease}
:page-role:
:description: Installing Couchbase Lite on Objective-C
:keywords: edge nosql api
:tabs:

:this-release: 3.0.0-beta01



include::partial$_std-cbl-hdr-objc.adoc[]
include::{root-partials}block-abstract.adoc[]


== Get Started

Create or open an existing _Xcode_ project and install _Couchbase Lite {this-release}_ using one of the <<lbl-install-tabs>> methods shown.

// include::{root-partials}_block-caveats.adoc[tag=xcode-12x3-fix]

[NOTE]
--
Couchbase Lite is distributed as an xcframework, to support this:

* The minimum required Cocoapods version is *1.9*
* The minimum required Carthage version is *38.0*
--


[#lbl-install-tabs]
=== Install Methods
[{tabs}]
====
Direct Download::
+
--
// * https://www.couchbase.com/downloads[Download] Couchbase Lite.

* For BETA only, download from here:

** Community --
 https://packages.couchbase.com/releases/couchbase-lite-ios/{this-release}/couchbase-lite-objc_xc_community_{this-release}.zip[couchbase-lite-objc_xc_community_{this-release}.zip]


** Enterprise -- https://packages.couchbase.com/releases/couchbase-lite-ios/{this-release}/couchbase-lite-objc_xc_enterprise_{this-release}.zip[couchbase-lite-objc_xc_enterprise_{this-release}.zip]

* Drag *CouchbaseLite.xcframework* from your Finder to the Xcode navigator.
* Click on Project > General > Embedded Binary and add *CouchbaseLite.xcframework* to this section.
* Import the xcframework and start using it in your project.
+
[source]
----
#include <CouchbaseLite/CouchbaseLite.h>
...
----
--

Carthage::
+
--
NOTE:  The minimum required version of Carthage is *38.0*


. https://github.com/Carthage/Carthage#installing-carthage[Install Carthage]
. In your *Cartfile*, add the following.
+
.Couchbase Lite Community Edition
[source,ruby,subs=attributes+]
----
binary "https://packages.couchbase.com/releases/couchbase-lite-ios/carthage/CouchbaseLite-Community.json" {this-release}
----
+
.Couchbase Lite Enterprise Edition
[source,ruby,subs=attributes+]
----
binary "https://packages.couchbase.com/releases/couchbase-lite-ios/carthage/CouchbaseLite-Enterprise.json" {this-release}
----

. Run `carthage update --platform ios`.
. Drag *CouchbaseLite.xcframework* from *Carthage/Build/* to the Xcode navigator.
. Click on Project > General > Embedded Binary and add *CouchbaseLite.xcframework* to this section.
--

CocoaPods::
+
--
NOTE: The minimum required version of Cocoapods is *1.9*

. https://guides.cocoapods.org/using/getting-started.html[Install Cocoapods]
. In your *Podfile*, add the following.
+
.Couchbase Lite Community Edition
[source,ruby,subs=attributes+]
----
target '<your target name>' do
  use_frameworks!
  pod 'CouchbaseLite', '{this-release}'
end
----
+
.Couchbase Lite Enterprise Edition
[source,ruby,subs=attributes+]
----
target '<your target name>' do
  use_frameworks!
  pod 'CouchbaseLite-Enterprise', '{this-release}'
end
----

. Install the pods and open the .xcworkspace file generated by Cocoapods.
+
[source,bash]
----
pod install
----
--
====

include::{root-partials}block-related-content-start.adoc[]
