:docname: gs-install
:page-module: objc
:page-relative-src-path: gs-install.adoc
:page-origin-url: https://github.com/couchbase/docs-couchbase-lite.git
:page-origin-start-path:
:page-origin-refname: antora-assembler-simplification
:page-origin-reftype: branch
:page-origin-refhash: (worktree)
[#objc:gs-install:::]
== Install
:page-aliases: start/objc-gs-install.adoc
:page-role:
:description: Installing Couchbase Lite on Objective-C
:keywords: edge nosql api
:tabs:

// :this-release: {version-full}


:maintenance: 1


[abstract]
--
Description -- _{description}_ +
--


[discrete#objc:gs-install:::get-started]
=== Get Started

Create or open an existing _Xcode_ project and install _Couchbase Lite {major}.{minor}.{base}{empty} using one of the <<objc:gs-install:::lbl-install-tabs>> methods shown.

Enterprise users can also download the Couchbase Lite Vector Search extension library.

// include::ROOT:partial$block-caveats.adoc[tag=xcode-12x3-fix]

[NOTE]
--
Couchbase Lite is distributed as an xcframework, to support this:

* The minimum required Cocoapods version is *1.15*
* The minimum required Carthage version is *0.38*
--


[discrete#objc:gs-install:::lbl-install-tabs]
==== Install Couchbase Lite

IMPORTANT: There is no Carthage support for the 3.2.0 Beta version of Couchbase Lite.

[tabs]
====

Direct Download::
+
--
// * https://www.couchbase.com/downloads[Download] Couchbase Lite.

. Download the binaries from here -- https://www.couchbase.com/downloads#extend-with-mobile[Extend with Mobile].

. Unpack the download zip file into your XCode project location.

. Select your target settings in XCode and drag *CouchbaseLite.xcframework* from your Finder to the *Frameworks, Libraries, and Embedded Content* section.
* Import the xcframework and start using it in your project.
+
[source]
----
#include <CouchbaseLite/CouchbaseLite.h>
...
----
--

Carthage::
+
--
NOTE:  The minimum required version of Carthage is *38.0*


. https://github.com/Carthage/Carthage#installing-carthage[Install Carthage]
. In your *Cartfile*, add the following.
+
.Couchbase Lite Community Edition
[source,ruby,subs=attributes+]
----
binary "https://packages.couchbase.com/releases/couchbase-lite-ios/carthage/CouchbaseLite-Community.json" ~> {major}.{minor}.{base}{empty}
----
+
.Couchbase Lite Enterprise Edition
[source,ruby,subs=attributes+]
----
binary "https://packages.couchbase.com/releases/couchbase-lite-ios/carthage/CouchbaseLite-Enterprise.json" ~> {major}.{minor}.{base}{empty}
----

. Run `carthage update --platform ios`.
. Drag *CouchbaseLite.xcframework* from *Carthage/Build/* to the Xcode navigator.
. Click on Project > General > Embedded Binary and add *CouchbaseLite.xcframework* to this section.
--


CocoaPods::
+
--
NOTE: The minimum required version of Cocoapods is *1.15*

. https://guides.cocoapods.org/using/getting-started.html[Install Cocoapods]
. In your *Podfile*, add the following.
+
.Couchbase Lite Community Edition
[source,ruby,subs=attributes+]
----
target '<your target name>' do
  use_frameworks!
  pod 'CouchbaseLite', '{major}.{minor}.{base}{empty}'
end
----
+
.Couchbase Lite Enterprise Edition
[source,ruby,subs=attributes+]
----
target '<your target name>' do
  use_frameworks!
  pod 'CouchbaseLite-Enterprise', '{major}.{minor}.{base}{empty}'
end
----

. Install the pods and open the .xcworkspace file generated by Cocoapods.
+
[source,bash]
----
pod install
----
--
====

[discrete#objc:gs-install:::install-vector-search-extension]
=== Install Vector Search Extension

NOTE: Vector Search is an *Enterprise-only* feature.

You can get set up with the Vector Search Extension for iOS (Objective-C) by following these instructions.

[IMPORTANT]
--
To use Vector Search, you must have Couchbase Lite installed and add the Vector Search extension to your Couchbase Lite application.
There is no Carthage support for the beta release of Vector Search.
Vector Search is available only for 64-bit architectures and
Intel processors that support the Advanced Vector Extensions 2 (AVX2) instruction set.
To verify whether your device supports the AVX2 instructions set, https://www.intel.com/content/www/us/en/support/articles/000090473/processors/intel-core-processors.html[follow these instructions.]
--

[tabs]
=====

Direct Download::
+
--

. Download the binaries from here -- https://packages.couchbase.com/releases/couchbase-lite-vector-search/{vs-major}.{vs-minor}.{vs-maintenance-ios}{empty}/couchbase-lite-vector-search_xcframework_{vs-major}.{vs-minor}.{vs-maintenance-ios}{empty}.zip[binary download link.]

. Unpack the download zip file into your XCode project location.

. Select your target settings in XCode and drag *CouchbaseLiteVectorSearch.xcframework* from your Finder to the *Frameworks, Libraries, and Embedded Content* section.

. Start using Couchbase Lite Vector Search on Swift in your project.

--

Carthage::
+
--
NOTE:  The minimum required version of Carthage is *38.0*


. https://github.com/Carthage/Carthage#installing-carthage[Install Carthage]
. In your *Cartfile*, add the following.
+
.Couchbase Lite Enterprise Edition
[source,ruby,subs=attributes+]
----
binary "http://packages.couchbase.com/releases/couchbase-lite-vector-search/carthage/CouchbaseLiteVectorSearch.json" ~> {vs-major}.{vs-minor}.{vs-maintenance-ios}{empty}
----

. Run `carthage update --platform ios`.
. Drag *CouchbaseLite.xcframework* from *Carthage/Build/* to the Xcode navigator.
. Click on Project > General > Embedded Binary and add *CouchbaseLite.xcframework* to this section.
--


CocoaPods::
+
--
NOTE: The minimum required Cocoapods  version is *1.15*

. Install CocoaPods using the instructions here: +
 https://guides.cocoapods.org/using/getting-started.html

. Add one of these targets to your *Podfile*:
+

.Couchbase Lite Enterprise Edition
[source,ruby,subs=attributes+]
----
target 'Example' do
  use_frameworks!
  pod 'CouchbaseLiteVectorSearch', '{vs-major}.{vs-minor}.{vs-maintenance-ios}{empty}' // <.>
end
----

+
<.> Specify the required version number, here we use the latest version

. Install the pods and open the `.xcworkspace` file generated by CocoaPods, using:
+
[source,bash]
----
pod install
----
--
=====


[discrete#objc:gs-install:::related-content]
=== Related Content
++++
<div class="card-row three-column-row">
++++

[.column]
==== {empty}
.How to . . .
* xref:objc:gs-prereqs.adoc[Prerequisites]
* xref:objc:gs-install.adoc[Install]
* xref:objc:gs-build.adoc[Build and Run]


.

[discrete.colum#objc:gs-install:::-2n]
==== {empty}
.Learn more . . .
* xref:objc:database.adoc[Databases]
* xref:objc:document.adoc[Documents]
* xref:objc:blob.adoc[Blobs]
* xref:objc:replication.adoc[Remote Sync Gateway]
* xref:objc:conflict.adoc[Handling Data Conflicts]

.


[discrete.colum#objc:gs-install:::-3n]
==== {empty}
.Dive Deeper . . .
https://forums.couchbase.com/c/mobile/14[Mobile Forum] |
https://blog.couchbase.com/[Blog] |
https://docs.couchbase.com/tutorials/[Tutorials]

.


++++
</div>
++++


