= Installation - Couchbase Lite on Objective-C
:page-aliases: start/objc-gs-install.adoc
ifdef::show_edition[:page-edition: {release}]
ifdef::prerelease[:page-status: {prerelease}]
:page-role:
:description: Installing Couchbase Lite on Objective-C
:keywords: edge nosql api
:tabs:

// :this-release: {version-full}



include::partial$_set_page_context_for_objc.adoc[]
include::{root-partials}_show_page_header_block.adoc[]


== Get Started

Create or open an existing _Xcode_ project and install _Couchbase Lite {version-full}_ using one of the <<lbl-install-tabs>> methods shown.

Enterprise users can also download the Couchbase Lite Vector Search extension library.

// include::{root-partials}block-caveats.adoc[tag=xcode-12x3-fix]

[NOTE]
--
Couchbase Lite is distributed as an xcframework, to support this:

* The minimum required Cocoapods version is *1.15*
* The minimum required Carthage version is *0.38*
--


[#lbl-install-tabs]
=== Install Couchbase Lite
[{tabs}]
====
Direct Download::
+
--
// * https://www.couchbase.com/downloads[Download] Couchbase Lite.

. Download the binaries from here -- {downloads-mobile--xref}.

. Unpack the download zip file into your XCode project location.

. Select your target settings in XCode and drag *CouchbaseLite.xcframework* from your Finder to the *Frameworks, Libraries, and Embedded Content* section.
* Import the xcframework and start using it in your project.
+
[source]
----
#include <CouchbaseLite/CouchbaseLite.h>
...
----
--

Carthage::
+
--
NOTE:  The minimum required version of Carthage is *0.38*


. https://github.com/Carthage/Carthage#installing-carthage[Install Carthage]
. In your *Cartfile*, add the following.
+
.Couchbase Lite Community Edition
[source,ruby,subs=attributes+]
----
binary "https://packages.couchbase.com/releases/couchbase-lite-ios/carthage/CouchbaseLite-Community.json" ~> {version-full}
----
+
.Couchbase Lite Enterprise Edition
[source,ruby,subs=attributes+]
----
binary "https://packages.couchbase.com/releases/couchbase-lite-ios/carthage/CouchbaseLite-Enterprise.json" ~> {version-full}
----

. Run `carthage update --platform ios`.
. Drag *CouchbaseLite.xcframework* from *Carthage/Build/* to the Xcode navigator.
. Click on Project > General > Embedded Binary and add *CouchbaseLite.xcframework* to this section.
--

CocoaPods::
+
--
NOTE: The minimum required version of Cocoapods is *1.15*

. https://guides.cocoapods.org/using/getting-started.html[Install Cocoapods]
. In your *Podfile*, add the following.
+
.Couchbase Lite Community Edition
[source,ruby,subs=attributes+]
----
target '<your target name>' do
  use_frameworks!
  pod 'CouchbaseLite', '{version-full}'
end
----
+
.Couchbase Lite Enterprise Edition
[source,ruby,subs=attributes+]
----
target '<your target name>' do
  use_frameworks!
  pod 'CouchbaseLite-Enterprise', '{version-full}'
end
----

. Install the pods and open the .xcworkspace file generated by Cocoapods.
+
[source,bash]
----
pod install
----
--
====

== Install Vector Search Extension

[IMPORTANT]
--

You must have Couchbase Lite installed to use the Vector Search extension.
Vector Search is an Enterprise only feature.
There is no Carthage support for the beta release of Vector Search.

--

[{tabs}]
=====
Direct Download::
+
--

. Download the binaries from here -- {downloads-mobile--xref}.

. Unpack the download zip file into your XCode project location.

. Select your target settings in XCode and drag *CouchbaseLiteVectorSearch.xcframework* from your Finder to the *Frameworks, Libraries, and Embedded Content* section.

. Start using Couchbase Lite Vector Search on Swift in your project.

--

CocoaPods::
+
--
NOTE: The minimum required Cocoapods  version is *1.15*

. Install CocoaPods using the instructions here: +
 https://guides.cocoapods.org/using/getting-started.html

. Add one of these targets to your *Podfile*:
+

.Couchbase Lite Enterprise Edition
[source,ruby,subs=attributes+]
----
target 'Example' do
  use_frameworks!
  pod 'CouchbaseLiteVectorSearch', '1.0.0-beta.1' // <.>
end
----

+
<.> Specify the required version number, here we use the latest version of the beta

. Install the pods and open the `.xcworkspace` file generated by CocoaPods, using:
+
[source,bash]
----
pod install
----
--
=====

include::{root-partials}block-related-content-start.adoc[]
