= What's New in Objective-C CBL?

== Highlights

Deserunt proident ex magna eiusmod commodo. Nisi sunt anim est quis nulla magna eu non aliquip culpa. Commodo culpa cupidatat ad culpa veniam tempor fugiat non sit ut. Aute tempor ex ut qui incididunt.

Read more: xref:java-platform.adoc[Java]


== Release Notes

Magna aliquip in non labore laboris proident officia culpa ea sit laboris reprehenderit voluptate. Nisi eu quis consectetur anim ad in labore nisi consequat. Duis laborum sit ea ut sint cillum commodo consequat cillum.

Do proident consectetur aliquip qui excepteur. Exercitation eiusmod occaecat esse nulla quis aliqua laborum. Mollit sunt ea enim non tempor duis pariatur ullamco nulla sunt minim ad esse elit. Magna aliquip consectetur reprehenderit proident non.

Laborum reprehenderit sint occaecat minim. Id ex reprehenderit dolore do dolore. Proident quis laboris id esse eu adipisicing irure laboris ea enim eiusmod est dolor ullamco.

xref:swift.adoc#release-notes[swift] |
xref:java-platform.adoc#release-notes[Java] |
xref:java-android.adoc#release-notes[Java (Android)] |
xref:javascript.adoc#release-notes[Javascript] |
xref:csharp.adoc#release-notes[C#] |
xref:objc.adoc#release-notes[objective-C]
