:docname: indexing
:page-module: objc
:page-relative-src-path: indexing.adoc
:page-origin-url: https://github.com/couchbase/docs-couchbase-lite.git
:page-origin-start-path:
:page-origin-refname: antora-assembler-simplification
:page-origin-reftype: branch
:page-origin-refhash: (worktree)
[#objc:indexing:::]
= Indexing
:page-aliases: learn/objc-indexing.adoc
:page-role:
:description: Couchbase mobile database indexing concepts


:maintenance: 1


[abstract]
--
Description -- _{description}_ +
Related Content -- xref:objc:database.adoc[Databases] | xref:objc:document.adoc[Documents] | xref:objc:indexing.adoc[Indexing] |
--


[#objc:indexing:::introduction]
== Introduction
// tag::overview[]
Querying documents using a pre-existing database index is much faster because an index narrows down the set of documents to examine -- see: the xref:objc:query-troubleshooting.adoc[Query Troubleshooting] topic.

When planning the indexes you need for your database, remember that while indexes make queries faster, they may also:

* Make writes slightly slower, because each index must be updated whenever a document is updated
* Make your Couchbase Lite database slightly larger.

Too many indexes may hurt performance.
Optimal performance depends on designing and creating the _right_ indexes to go along with your queries.

.Constraints
[NOTE]
Couchbase Lite for ios does not currently support partial value indexes; indexes with non-property expressions.
You should only index with properties that you plan to use in the query.


//end::overview[]


[#objc:indexing:::creating-a-new-index]
== Creating a new index

You can use {sqlpp} or QueryBuilder syntaxes to create an index


<<objc:indexing:::ex-create-index>> creates a new index for the `type` and `name` properties, shown in this data model:

[#objc:indexing:::ex-datamodel]
.Data Model
====
[source,json]
----
{
    "_id": "hotel123",
    "type": "hotel",
    "name": "The Michigander",
    "overview": "Ideally situated for exploration of the Motor City and the wider state of Michigan. Tripadvisor rated the hotel ...",
    "state": "Michigan"
}
----
====

[#objc:indexing:::sql]
=== {sqlpp}

The code to create the index will look something like this:

.Create index
[#ex-create-index]


[#objc:indexing:::ex-create-index]
====


// Show Main Snippet
// include::objc:example$code_snippets/SampleCodeTest.m[tags="query-index", indent=0]
[source, objc]
----

CBLValueIndexConfiguration* config = [[CBLValueIndexConfiguration alloc]
                                      initWithExpression: @[@"type", @"name"]];

[collection createIndexWithName:@"TypeNameIndex" config:config error: &error];

----


====


[#objc:indexing:::querybuilder]
=== QueryBuilder

TIP: See the xref:objc:querybuilder.adoc[QueryBuilder] topic to learn more about QueryBuilder.

The code to create the index will look something like this:

.Create index with QueryBuilder
[#ex-create-index]


[#objc:indexing:::ex-create-index]
====


// Show Main Snippet
// include::objc:example$code_snippets/SampleCodeTest.m[tags="query-index_Querybuilder", indent=0]
[source, objc]
----
CBLValueIndexItem *type = [CBLValueIndexItem property:@"type"];
CBLValueIndexItem *name = [CBLValueIndexItem property:@"name"];
CBLIndex *index = [CBLIndexBuilder valueIndexWithItems:@[type, name]];
[collection createIndex:index name:@"TypeNameIndex" error:&error];
----


====


// DO NOT EDIT -- Footer Related Content Block


[#objc:indexing:::related-content]
== Related Content
++++
<div class="card-row three-column-row">
++++

[.column]
=== {empty}
.How to . . .
* xref:objc:gs-prereqs.adoc[Prerequisites]
* xref:objc:gs-install.adoc[Install]
* xref:objc:gs-build.adoc[Build and Run]


.

[discrete.colum#objc:indexing:::-2n]
=== {empty}
.Learn more . . .
* xref:objc:database.adoc[Databases]
* xref:objc:document.adoc[Documents]
* xref:objc:blob.adoc[Blobs]
* xref:objc:replication.adoc[Remote Sync Gateway]
* xref:objc:conflict.adoc[Handling Data Conflicts]

.


[discrete.colum#objc:indexing:::-3n]
=== {empty}
.Dive Deeper . . .
https://forums.couchbase.com/c/mobile/14[Mobile Forum] |
https://blog.couchbase.com/[Blog] |
https://docs.couchbase.com/tutorials/[Tutorials]

.


++++
</div>
++++
// DO NOT EDIT


