:docname: query-live
:page-module: objc
:page-relative-src-path: query-live.adoc
:page-origin-url: https://github.com/couchbase/docs-couchbase-lite.git
:page-origin-start-path:
:page-origin-refname: antora-assembler-simplification
:page-origin-reftype: branch
:page-origin-refhash: (worktree)
[#objc:query-live:::]
== Live Queries
:page-aliases: learn/objc-query-live.adoc
:page-role:
:description: Couchbase mobile database live query concepts




:maintenance: 1














































































[abstract]
--
Description -- _{description}_ +
--

// BEGIN::Local page attributes
// :blank-field: ____
// :lang-title: Objective C
// :module: objc
// :packageNm: couchbase-lite-objc
// :source-language: objc
// snippet: objc:example$code_snippets/SampleCodeTest.m
// :url-issues: https://github.com/couchbase/couchbase-lite-objc/issues

// END::Local page attributes




[discrete#objc:query-live:::activating-a-live-query]
=== Activating a Live Query


A live query is a query that, once activated, remains active and monitors the database for changes; refreshing the result set whenever a change occurs.
As such, it is a great way to build reactive user interfaces -- especially table/list views -- that keep themselves up to date.

*So, a simple use case may be:* A replicator running and pulling new data from a server, whilst a live-query-driven UI automatically updates to show the data without the user having to manually refresh.
This helps your app feel quick and responsive.

To activate a LiveQuery just add a change listener to the query statement.
It will be immediately active.
When a change is detected the query automatically runs, and posts the new query result to any observers (change listeners).


.Starting a Live Query
[#ex-qry-start]


[#objc:query-live:::ex-qry-start]
====


// Show Main Snippet
// include::objc:example$code_snippets/SampleCodeTest.m[tags="live-query", indent=0]
[source, objc]
----
CBLQuery *query = [CBLQueryBuilder select:@[[CBLQuerySelectResult all]]
                                     from:[CBLQueryDataSource collection:collection]]; // <.>

// Adds a query change listener.
// Changes will be posted on the main queue.
id<CBLListenerToken> token = [query addChangeListener:^(CBLQueryChange  *change) { // <.>
    for (CBLQueryResultSet *results in [change results]) {
        NSLog(@"%@", results);
        /* Update UI */
    }
}]; // <.>

----




====

<.> Build the query statements
<.> Activate the _live_ query by attaching a listener.
Save the token in order to detach the listener and stop the query later -- se <<objc:query-live:::ex-qry-stop>>


.Stop a LIve Query
[#ex-qry-stop]


[#objc:query-live:::ex-qry-stop]
====


// Show Main Snippet
// include::objc:example$code_snippets/SampleCodeTest.m[tags="stop-live-query", indent=0]
[source, objc]
----
[query removeChangeListenerWithToken:token]; // <.>
----




====

<.> Here we use the change lister token from <<objc:query-live:::ex-qry-start>> to remove the listener.
Doing so stops the live query.


