:docname: upgrade
:page-module: objc
:page-relative-src-path: upgrade.adoc
:page-origin-url: https://github.com/couchbase/docs-couchbase-lite.git
:page-origin-start-path:
:page-origin-refname: antora-assembler-simplification
:page-origin-reftype: branch
:page-origin-refhash: (worktree)
[#objc:upgrade:::]
== Upgrade
:page-aliases: advance/objc-dep-upgrade.adoc, dep-upgrade.adoc
:page-role:
:description:



// BEGIN -- inclusion -- {module-partials}_define_module_attributes.adoc
//  Usage:  Here we define module specific attributes. It is invoked during the compilation of a page,
//          making all attributes available for use on the page.
//  UsedBy: ROOT:partial$_std_cbl_hdr.adoc

// BEGIN::module page attributes

//
// CBL-Obj-C Maintenance release number
//
:maintenance: 1
//

// VECTOR SEARCH attributes
//



// BEGIN - Set attributes pointing to API references for this module


// API Reference Links
//
//



// Supporting Data Type Classes



// DATABASE CLASSES


// Docuument Class




// Begin -- DatabaseConfiguration
// End -- DatabaseConfiguration

//Database.SAVE



//Database.DELETE


//Database.COMPACT
// deprecated 2.8
//
// :url-api-method-database-compact: https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-ios}{empty}/couchbase-lite-objc/Classes/CBLDatabase.html#/c:objc(cs)CBLDatabase(im)compact:[CBLDatabase.compact()]






// QUERY RELATED CLASSES and METHODS

// Result Classes and Methods




// Query class and methods





// Expression class and methods
// :url-api-references-query-classes: https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-ios}{empty}/couchbase-lite-objc/Classes/[Query Class index]


// ArrayFunction class and methods


// Function class and methods
//

// Where class and methods
//
// https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-ios}{empty}/couchbase-lite-objc/Classes/CBLWhere.html
// NOT SET[Where]

// orderby class and methods
//
// https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-ios}{empty}/couchbase-lite-objc/Classes/CBLOrderBy.html

// GroupBy class and methods
//
// https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-ios}{empty}/couchbase-lite-objc/Classes/CBLGroupBy.html
// NOT SET[GroupBy]

// URLEndpointConfiguration





















// diag: Env+Module objc


// Replicator API











// Note there is a replicator.status property AND
// a ReplicationStatus class/struct --- oh yes, easy to confuse.

//:url-api-property-replicator-status-activity: https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-ios}{empty}/couchbase-lite-objc/Classes/CBLReplicator.html#/s:18CouchbaseLiteobjc10ReplicatorC13ActivityLevelO







// ReplicatorConfiguration API











// Begin Replicator Retry Config
// End Replicator Retry Config


// :url-api-prop-replicator-config-ServerCertificateVerificationMode: https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-ios}{empty}/couchbase-lite-objc/Classes/CBLReplicatorConfiguration.html#/c:objc(cs)CBLReplicatorConfiguration(py)serverCertificateVerificationMode[serverCertificateVerificationMode]

// :url-api-enum-replicator-config-ServerCertificateVerificationMode: https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-ios}{empty}/couchbase-lite-objc/Classes/CBLReplicatorConfiguration.html{Enums/ServerCertificateVerificationMode.html[serverCertificateVerificationMode enum]








// Meta API




// BEGIN Logs and logging references
// :url-api-class-logging: https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-ios}{empty}/couchbase-lite-objcLogging.html[CBLLogging classes]







// END  Logs and logging references

// End define module specific attributes

// BEGIN::module page attributes
// :snippet-p2psync-ws: {snippets-p2psync-ws--objc}
// END::Local page attributes



[IMPORTANT]
--
On upgrading from a 2.x release, all Couchbase Lite databases will be automatically re-indexed on initial database open. +
This can result in a delay before the database is usable.
--


[discrete#objc:upgrade:::3-2-0-upgrade]
=== {major}.{minor}.{base}{empty} Upgrade

NOTE: This upgrade requires all 2.x databases be reindexed on initial open.

The action will take place automatically and can lead to some delay in the database becoming available for use in your application.

In addition, if you are syncing with a {major}.{minor}.{base}{empty} Sync Gateway, you should be aware of the significant configuration enhancements introduced and their impact.
This is a one-way conversion.

[discrete#objc:upgrade:::api-changes]
==== API Changes

[discrete#objc:upgrade:::removed-apis]
===== Removed APIs

[discrete#objc:upgrade:::resetcheckpoint]
====== ResetCheckpoint
// |https://docs.couchbase.com/mobile/2.8.0/couchbase-lite-swift/Classes/Replicator.html#/s:18CouchbaseLiteSwift10ReplicatorC15resetCheckpointyyF

.Alternative
// https://docs.couchbase.com/mobile/2.8.0/couchbase-lite-swift/Classes/Replicator.html#/s:18CouchbaseLiteSwift10ReplicatorC5start5resetySb_tF
  `[replicator startWithReset:];`

.Before
----
[replicator resetCheckpoint];
[replicator start];
----

.After
----
[replicator startWithReset: YES];
----

[discrete#objc:upgrade:::database-setloglevel]
====== Database.setLogLevel
// https://docs.couchbase.com/mobile/2.8.0/couchbase-lite-swift/Classes/Database.html#/s:18CouchbaseLiteSwift8DatabaseC11setLogLevel_6domainyAA0fG0O_AA0F6DomainOtFZ[]

.Alternative
`CBLDatabase.log.console`

.Before
----
[CBLDatabase setLogLevel:kCBLLogLevelVerbose domain: kCBLLogDomainAll];
----

.After
----
CBLDatabase.log.console.level = kCBLLogLevelVerbose;
CBLDatabase.log.console.domains = kCBLLogDomainAll;
----

[discrete#objc:upgrade:::database-compact]
====== Database.compact
// https://docs.couchbase.com/mobile/2.8.0/couchbase-lite-swift/Classes/Database.html#/s:18CouchbaseLiteSwift8DatabaseC7compactyyKF[
.Alternative
`[db performMaintenance:error:]`
// https://docs.couchbase.com/mobile/2.8.0/couchbase-lite-swift/Classes/Database.html#/s:18CouchbaseLiteSwift8DatabaseC18performMaintenance4typeyAA0F4TypeO_tKF

.Before
----
[testdb compact: &error];
----

.After
----
[testdb performMaintenance:kCBLMaintenanceTypeCompact error:&error];
----



[discrete#objc:upgrade:::deprecated-api]
===== Deprecated API

[discrete#objc:upgrade:::match]
====== Match
// https://docs.couchbase.com/mobile/2.8.0/couchbase-lite-swift/Classes/FullTextExpression.html#/s:18CouchbaseLiteSwift18FullTextExpressionC5indexyAA0deF8Protocol_pSSFZ[MATCH]
.Alternative
`[CBLQueryFullTextFunction matchWithIndexName: query:]`

.Before
----
CBLQueryFullTextExpression* index = [CBLQueryFullTextExpression indexWithName: @"indexName"];
q = [CBLQueryBuilder select: @[[CBLQuerySelectResult expression: [CBLQueryMeta id]]]
                        from: [CBLQueryDataSource database: self.database]
                        where: [index match: @"'queryString'"]];
----

.After
----
    q = [CBLQueryBuilder select: @[[CBLQuerySelectResult expression: [CBLQueryMeta id]]]
                           from: [CBLQueryDataSource database: self.database]
                          where: [CBLQueryFullTextFunction matchWithIndexName: @"indexName"
                                                                        query: @"'queryString'"]];
----


[discrete#objc:upgrade:::isnullormissing-and-notnullormissing]
====== isNullOrMissing and notNullOrMissing
// https://docs.couchbase.com/mobile/2.8.0/couchbase-lite-swift/Protocols/ExpressionProtocol.html#/s:18CouchbaseLiteSwift18ExpressionProtocolP15isNullOrMissingAaB_pyF[
// https://docs.couchbase.com/mobile/2.8.0/couchbase-lite-swift/Protocols/ExpressionProtocol.html#/s:18CouchbaseLiteSwift18ExpressionProtocolP16notNullOrMissingAaB_pyF[notNullOrMissing/notNullOrMissing]

.Alternatives
----
[exp isValued];
[exp isNotValued];
----

.Before
----
    q = [CBLQueryBuilder select: @[[CBLQuerySelectResult expression: [CBLQueryMeta id]]]
                           from: [CBLQueryDataSource database: self.database]
                          where: [[CBLQueryExpression property: @"missingProp"] isNullOrMissing]];

    q2 = [CBLQueryBuilder select: @[[CBLQuerySelectResult expression: [CBLQueryMeta id]]]
                            from: [CBLQueryDataSource database: self.database]
                           where: [[CBLQueryExpression property: @"notMissingProp"] notNullOrMissing]];
----

.After
----
    q = [CBLQueryBuilder select: @[[CBLQuerySelectResult expression: [CBLQueryMeta id]]]
                           from: [CBLQueryDataSource database: self.database]
                          where: [[CBLQueryExpression property: @"missingProp"] isNotValued]];

    q2 = [CBLQueryBuilder select: @[[CBLQuerySelectResult expression: [CBLQueryMeta id]]]
                            from: [CBLQueryDataSource database: self.database]
                           where: [[CBLQueryExpression property: @"notMissingProp"] isValued]];
----

[discrete#objc:upgrade:::updated-api]
===== Updated API


[discrete#objc:upgrade:::atan2]
====== ATAN2

CAUTION: Breaking change

`ATAN2(x, y)` now becomes `ATAN2(y, x)`

.Before
[source, objc]
----
q = [CBLQueryBuilder select: @[[CBLQuerySelectResult expression: [CBLQueryFunction atan2: p y: [CBLQueryExpression integer: 90]]]]
                            from: [CBLQueryDataSource database: self.database]];
----

.After
[source, objc]
----
q = [CBLQueryBuilder select: @[[CBLQuerySelectResult expression: [CBLQueryFunction atan2: [CBLQueryExpression integer: 90] x: p]]]
                           from: [CBLQueryDataSource database: self.database]];
----


[discrete#objc:upgrade:::lbl-db-upgrades]
=== 1.x Databases Upgrades to 2.x

Databases created using Couchbase Lite 1.2 or later can still be used with Couchbase Lite 2.x; but will be automatically updated to the  current 2.x version.
This feature is only available for the default storage type (i.e., not a ForestDB database).

[discrete#objc:upgrade:::encrypted-databases]
==== Encrypted Databases
The automatic migration feature does not support encrypted databases.
So if the 1.x database is encrypted you will first need to disable encryption using the Couchbase Lite 1.x API (see the https://docs-archive.couchbase.com/couchbase-lite/1.4/objc.html#database-encryption[1.x Database Guide]).

Thus, to upgrade an encrypted 1.x database, you should do the following:

// set the correct language name for 1.4 pages
.Upgrading Encrypted Databases
****
. Disable encryption using the Couchbase Lite 1.x framework (see https://docs-archive.couchbase.com/couchbase-lite/1.4/objc.html#database-encryption[1.x encryption guide])
. Open the database file with encryption enabled using the Couchbase Lite 2.x framework.
****

Since it is not possible to package Couchbase Lite 1.x and Couchbase Lite 2.x in the same application this upgrade path would require two successive upgrades.

If you are using Sync Gateway to synchronize the database content, it may be preferable to run a pull replication from a new 2.x database with encryption enabled and delete the 1.x local database.


[discrete#objc:upgrade:::handling-of-existing-conflicts]
==== Handling of Existing Conflicts

If there are existing conflicts in the 1.x database, the automatic upgrade process copies the default winning revision to the new database and does NOT copy any conflicting revisions.

This functionality is related to the way conflicts are now being handled in Couchbase Lite -- see xref:objc:conflict.adoc[Handling Data Conflicts].

Optionally, existing conflicts in the 1.x database can be resolved with the https://docs-archive.couchbase.com/couchbase-lite/1.4/objc.html#resolving-conflicts[1.x API] prior to the database being upgraded.

[discrete#objc:upgrade:::handling-of-existing-attachments]
==== Handling of Existing Attachments

Attachments persisted in a 1.x database are copied to the new database.
NOTE: The relevant Couchbase Lite API is now called the `Blob` API not the `Attachments` API.

The functionally is identical but the internal schema for attachments has changed.

Blobs are stored anywhere in the document, just like other value types.
Whereas in 1.x they were stored under the `_attachments` field.

The automatic upgrade functionality *does not* update the internal schema for attachments, so they remain accessible under the `_attachments` field.
See <<objc:upgrade:::ex-get-att>> for how to retrieve an attachment that was created in a 1.x database with a 2.x API.

.Retrieve 1.x Attachment
[#ex-get-att]
// BEGIN inclusion -- block -- block_tabbed_code_example.adoc
//
//  Allows for abstraction of the showing of snippet examples
//  which makes displaying tabbed snippets for platforms with
//  more than one native language to show -- Android (Kotlin and Java)
//
// Surrounds code in Example block
//
//  PARAMETERS:
//    param-tags comma-separated list of tags to include/exclude
//    param-leader text for opening para of an example block
//
//  USE:
//    :param_tags: query-access-json
//    include::partial$block_show_snippet.adoc[]
//    :param_tags!:
//

[#objc:upgrade:::ex-get-att]
====


// Show Main Snippet
[source, objc]
----
include ::objc:example$code_snippets/SampleCodeTest.m[tags="1x-attachment", indent=0]
CBLDictionary *attachments = [doc dictionaryForKey:@"_attachments"];
CBLBlob *avatar = [attachments blobForKey:@"avatar"];
NSData *content = [avatar content];
----




// close example block

====

// Tidy-up atttibutes created
// END -- block_show_snippet.doc

[discrete#objc:upgrade:::replication-compatibility]
==== Replication Compatibility

The current replication protocol is not backwards compatible with the 1.x replication protocol.
Therefore, to use replication with Couchbase Lite 2.x, the target Sync Gateway instance must also be upgraded to 2.x.

Sync Gateway 2.x will continue to accept clients that connect through the 1.x protocol.
It will automatically use the 1.x replication protocol when a Couchbase Lite 1.x client connects through \http://localhost:4984/db and the 2.0 replication protocol when a Couchbase Lite 2.0 client connects through ws://localhost:4984/db.
This allows for a smoother transition to get all your user base onto a version of your application built with Couchbase Lite 2.x.


[discrete#objc:upgrade:::xcode]
=== Xcode

The API has changed in Couchbase Lite 2.0 and will require porting an application that is using Couchbase Lite 1.x API to the Couchbase Lite 2.0 API.
To update an Xcode project built with Couchbase Lite 1.x:

* Remove the existing *CouchbaseLite.framework* dependency from the Xcode project.
* Remove all the Couchbase Lite 1.x dependencies (see the https://docs-archive.couchbase.com/couchbase-lite/1.4/objc.html#getting-started[1.x installation guide]).
* Install the Couchbase Lite 2.0 framework in your project  -- see xref:objc:gs-install.adoc[Install].
At this point, there will be many compiler warnings.
Refer to the examples on this page to learn about the new API.
* Build & run your application.

[discrete#objc:upgrade:::visual-studio]
=== Visual Studio

The public facing API has completely changed in Couchbase Lite 2.0 and will require a re-write to upgrade an application that is using Couchbase Lite 1.x.
To update an Xcode project built with Couchbase Lite 1.x:

* Remove the existing Couchbase Lite nuget package from the Visual Studio project.
* Remove all the Couchbase Lite 1.x dependencies -- see the  https://docs-archive.couchbase.com/couchbase-lite/1.4/csharp.html#getting-started[1.x installation guide].
* Install the Couchbase Lite 2.0 framework in your project  -- see xref:objc:gs-install.adoc[Install].
At this point, there will be many compiler warnings.
Refer to the examples on this page to learn about the new API.
* Build & run your application.
endif::csharp[]
ifdef::is-android[]
== Android Studio


The API changed in Couchbase Lite 2.0 and you will need to port any application that is using Couchbase Lite 1.x API to the latest Couchbase Lite API.
To update an Android project built with Couchbase Lite 1.x:

* Remove the existing Couchbase Lite dependency from the Android Studio project.
* Install the Couchbase Lite framework in your project -- see the https://docs-archive.couchbase.com/couchbase-lite/1.4/java.html#getting-started[Getting Started].
At this point, there will be many compiler warnings.
Refer to the examples on this page to learn about the new API.
* Build & run your application.

endif::is-android[]



// DO NOT DELETE
// Include standard footer
include::ROOT:partial$block-related-content-std.adoc[]
// include::ROOT:partial$_unset-platform.adoc[]
// DO NOT DELETE


== Troubleshooting

