apply plugin: 'java'

ext {
    CBL_VERSION = project.hasProperty('cblVersion') ? project.cblVersion : { throw new GradleException('cblVersion property is required. Use -PcblVersion=x.x.x-x') }()
    EXT_VERSION = project.hasProperty('extVersion') ? project.extVersion : { throw new GradleException('extVersion property is required. Use -PextVersion=x.x.x-x') }()
}

def USE_LOCAL_MAVEN = project.hasProperty("useLocalMaven")

group 'com.couchbase'
version '3.2.0'

java {
    targetCompatibility JavaVersion.VERSION_11
    sourceCompatibility JavaVersion.VERSION_11

    sourceSets {
        main {
            java.srcDirs = [
                "${projectDir}/common/main/java",
                "${projectDir}/src/main/java",
            ]
        }
    }
}

repositories {
    if (USE_LOCAL_MAVEN) {
        mavenLocal()
    }

    maven {
        url "https://proget.sc.couchbase.com/maven2/internalmaven/"
        content { includeGroupByRegex "com\\.couchbase\\.lite.*" }
    }

    maven {
        url "https://mobile.maven.couchbase.com/maven2/dev/"
        content { includeGroupByRegex "com\\.couchbase\\.lite.*" }
    }

    google()
    mavenCentral()
}

dependencies {
    compileOnly 'androidx.annotation:annotation:1.5.0'

    implementation "com.couchbase.lite:couchbase-lite-java-ee:${CBL_VERSION}"
    implementation "com.couchbase.lite:couchbase-lite-java-vector-search:${EXT_VERSION}"

    implementation 'com.fasterxml.jackson.core:jackson-databind:2.14.1'
}
