= API Changes
:page-partials:
ifdef::show_edition[:page-edition: {release}]
ifdef::prerelease[:page-status: {prerelease}]
:page-role:
:description:

include::partial$_set_page_context_for_objc.adoc[]

//  tag::content[]
== Removed APIs

=== ResetCheckpoint
// |https://docs.couchbase.com/mobile/2.8.0/couchbase-lite-swift/Classes/Replicator.html#/s:18CouchbaseLiteSwift10ReplicatorC15resetCheckpointyyF

.Alternative
// https://docs.couchbase.com/mobile/2.8.0/couchbase-lite-swift/Classes/Replicator.html#/s:18CouchbaseLiteSwift10ReplicatorC5start5resetySb_tF
  `[replicator startWithReset:];`

.Before
----
[replicator resetCheckpoint];
[replicator start];
----

.After
----
[replicator startWithReset: YES];
----

=== Database.setLogLevel
// https://docs.couchbase.com/mobile/2.8.0/couchbase-lite-swift/Classes/Database.html#/s:18CouchbaseLiteSwift8DatabaseC11setLogLevel_6domainyAA0fG0O_AA0F6DomainOtFZ[]

.Alternative
`CBLDatabase.log.console`

.Before
----
[CBLDatabase setLogLevel:kCBLLogLevelVerbose domain: kCBLLogDomainAll];
----

.After
----
CBLDatabase.log.console.level = kCBLLogLevelVerbose;
CBLDatabase.log.console.domains = kCBLLogDomainAll;
----

=== Database.compact
// https://docs.couchbase.com/mobile/2.8.0/couchbase-lite-swift/Classes/Database.html#/s:18CouchbaseLiteSwift8DatabaseC7compactyyKF[
.Alternative
`[db performMaintenance:error:]`
// https://docs.couchbase.com/mobile/2.8.0/couchbase-lite-swift/Classes/Database.html#/s:18CouchbaseLiteSwift8DatabaseC18performMaintenance4typeyAA0F4TypeO_tKF

.Before
----
[testdb compact: &error];
----

.After
----
[testdb performMaintenance:kCBLMaintenanceTypeCompact error:&error];
----



== Deprecated API

=== Match
// https://docs.couchbase.com/mobile/2.8.0/couchbase-lite-swift/Classes/FullTextExpression.html#/s:18CouchbaseLiteSwift18FullTextExpressionC5indexyAA0deF8Protocol_pSSFZ[MATCH]
.Alternative
`[CBLQueryFullTextFunction matchWithIndexName: query:]`

.Before
----
CBLQueryFullTextExpression* index = [CBLQueryFullTextExpression indexWithName: @"indexName"];
q = [CBLQueryBuilder select: @[[CBLQuerySelectResult expression: [CBLQueryMeta id]]]
                        from: [CBLQueryDataSource database: self.database]
                        where: [index match: @"'queryString'"]];
----

.After
----
    q = [CBLQueryBuilder select: @[[CBLQuerySelectResult expression: [CBLQueryMeta id]]]
                           from: [CBLQueryDataSource database: self.database]
                          where: [CBLQueryFullTextFunction matchWithIndexName: @"indexName"
                                                                        query: @"'queryString'"]];
----


=== isNullOrMissing and notNullOrMissing
// https://docs.couchbase.com/mobile/2.8.0/couchbase-lite-swift/Protocols/ExpressionProtocol.html#/s:18CouchbaseLiteSwift18ExpressionProtocolP15isNullOrMissingAaB_pyF[
// https://docs.couchbase.com/mobile/2.8.0/couchbase-lite-swift/Protocols/ExpressionProtocol.html#/s:18CouchbaseLiteSwift18ExpressionProtocolP16notNullOrMissingAaB_pyF[notNullOrMissing/notNullOrMissing]

.Alternatives
----
[exp isValued];
[exp isNotValued];
----

.Before
----
    q = [CBLQueryBuilder select: @[[CBLQuerySelectResult expression: [CBLQueryMeta id]]]
                           from: [CBLQueryDataSource database: self.database]
                          where: [[CBLQueryExpression property: @"missingProp"] isNullOrMissing]];

    q2 = [CBLQueryBuilder select: @[[CBLQuerySelectResult expression: [CBLQueryMeta id]]]
                            from: [CBLQueryDataSource database: self.database]
                           where: [[CBLQueryExpression property: @"notMissingProp"] notNullOrMissing]];
----

.After
----
    q = [CBLQueryBuilder select: @[[CBLQuerySelectResult expression: [CBLQueryMeta id]]]
                           from: [CBLQueryDataSource database: self.database]
                          where: [[CBLQueryExpression property: @"missingProp"] isNotValued]];

    q2 = [CBLQueryBuilder select: @[[CBLQuerySelectResult expression: [CBLQueryMeta id]]]
                            from: [CBLQueryDataSource database: self.database]
                           where: [[CBLQueryExpression property: @"notMissingProp"] isValued]];
----

== Updated API


=== ATAN2

CAUTION: Breaking change

`ATAN2(x, y)` now becomes `ATAN2(y, x)`

.Before
[source, {source-language}]
----
q = [CBLQueryBuilder select: @[[CBLQuerySelectResult expression: [CBLQueryFunction atan2: p y: [CBLQueryExpression integer: 90]]]]
                            from: [CBLQueryDataSource database: self.database]];
----

.After
[source, {source-language}]
----
q = [CBLQueryBuilder select: @[[CBLQuerySelectResult expression: [CBLQueryFunction atan2: [CBLQueryExpression integer: 90] x: p]]]
                           from: [CBLQueryDataSource database: self.database]];
----
// end::content[]

// DO NOT DELETE
// Include standard

include::ROOT:partial$block-related-content-std.adoc[]
// DO NOT DELETE

// DO NOT DELETE
// include::ROOT:partial$_unset-platform.adoc[]
// DO NOT DELETE
// END: inclusion-page - common-database.adoc[]
