= Build and Run
:page-aliases: clang:gs-build.adoc
:page-role:
:description: Build and run a starter app to validate your install of Couchbase Lite on C
:keywords: mobile edge nosql api iOS C web-app device-app


:source-language: c

:source-language: c


[abstract]
--
Description -- _{description}_ +
--

Steps in Getting Started::
xref:c:gs-install.adoc[Install]
 |
*Build*

Couchbase Lite for C ships both a C API and a {cpp} wrapper API (cbl++).
After installation, both APIs are available in the same package.

.Include headers
[tabs]
=====

C::
+
[source, c]
----
#include cbl/CouchbaseLite.h
----

{cpp}::
+
[source, cpp]
----
#include cbl++/CouchbaseLite.hh
----

=====


[#verify-install]
== Verify Install

Now you have _Couchbase Lite for C_ installed, you can verify that your apps build correctly.

Enter the C and C++ code from xref:c:gs-build.adoc#ex-c-starter[] into your editor of choice and build it.

Running it creates a database, adds a document, retrieves the document, updates the document and then deletes the document.

.Sample code
[#ex-c-starter]
====
[{tabs}]
=====
C::
+
--
[source, c]
----
include::c:example$code_snippets/main.cpp[tag=getting-started,indent=0]
----
--

C++::
+
--
[source, cpp]
----
include::c:example$code_snippets_cpp/cbl_cpp.cpp[tag=getting-started,indent=0]
----
--
=====
====


[#related-content]
== Related Content
++++
<div class="card-row three-column-row">
++++

[.column]
====== {empty}
.How to . . .
* xref:c:gs-install.adoc[Install]
* xref:c:gs-build.adoc[Build and Run]


.

[.column]
====== {empty}
.Learn more . . .
* xref:c:database.adoc[Databases]
* xref:c:document.adoc[Documents]
* xref:c:blob.adoc[Blobs]
* xref:c:replication.adoc[Remote Sync Gateway]
* xref:c:conflict.adoc[Handling Data Conflicts]

.


[.column]
====== {empty}
.Dive Deeper . . .
https://forums.couchbase.com/c/mobile/14[Mobile Forum] |
https://blog.couchbase.com/[Blog] |
https://docs.couchbase.com/tutorials/[Tutorials]

.


++++
</div>
++++