:docname: indexing
:page-module: c
:page-relative-src-path: indexing.adoc
:page-origin-url: https://github.com/couchbase/docs-couchbase-lite.git
:page-origin-start-path:
:page-origin-refname: antora-assembler-simplification
:page-origin-reftype: branch
:page-origin-refhash: (worktree)
[#c:indexing:::]
= Indexing
:page-role:
:description: Couchbase Lite database data model concepts - indexes


[abstract]
--
Description -- _{description}_ +
Related Content -- xref:c:database.adoc[Databases] | xref:c:document.adoc[Documents] | xref:c:indexing.adoc[Indexing] |
--


[discrete#c:indexing:::introduction]
== Introduction
// tag::overview[]
Querying documents using a pre-existing database index is much faster because an index narrows down the set of documents to examine -- see: the xref:c:query-troubleshooting.adoc[Query Troubleshooting] topic.

When planning the indexes you need for your database, remember that while indexes make queries faster, they may also:

* Make writes slightly slower, because each index must be updated whenever a document is updated
* Make your Couchbase Lite database slightly larger.

Too many indexes may hurt performance.
Optimal performance depends on designing and creating the _right_ indexes to go along with your queries.

.Constraints
[NOTE]
Couchbase Lite for c does not currently support partial value indexes; indexes with non-property expressions.
You should only index with properties that you plan to use in the query.


//end::overview[]


[discrete#c:indexing:::creating-a-new-index]
== Creating a new index

You can use {sqlpp} or QueryBuilder syntaxes to create an index


<<c:indexing:::ex-create-index>> creates a new index for the `type` and `name` properties, shown in this data model:

[#c:indexing:::ex-datamodel]
.Data Model
====
[source,json]
----
{
    "_id": "hotel123",
    "type": "hotel",
    "name": "The Michigander",
    "overview": "Ideally situated for exploration of the Motor City and the wider state of Michigan. Tripadvisor rated the hotel ...",
    "state": "Michigan"
}
----
====

[discrete#c:indexing:::sql]
=== {sqlpp}

The code to create the index will look something like this:

.Create index
[#ex-create-index]


[#c:indexing:::ex-create-index]
====


// Show Main Snippet
// include::c:example$code_snippets/main.cpp[tags="query-index", indent=0]
[source, c]
----
// For value types, this is optional but provides performance enhancements
// NOTE: No error handling, for brevity (see getting started)

// Syntax for second argument is the same as taking from a N1QL SELECT
// i.e. SELECT (type, name) FROM _;
CBLValueIndexConfiguration config = {
    kCBLN1QLLanguage,
    FLSTR("type, name")
};

CBLError err;
CBLCollection_CreateValueIndex(collection, FLSTR("TypeNameIndex"), config, &err);
----


====


[discrete#c:indexing:::related-content]
== Related Content
++++
<div class="card-row three-column-row">
++++

[.column]
=== {empty}
.How to . . .
* xref:c:gs-prereqs.adoc[Prerequisites]
* xref:c:gs-install.adoc[Install]
* xref:c:gs-build.adoc[Build and Run]


.

[discrete.colum#c:indexing:::-2n]
=== {empty}
.Learn more . . .
* xref:c:database.adoc[Databases]
* xref:c:document.adoc[Documents]
* xref:c:blob.adoc[Blobs]
* xref:c:replication.adoc[Remote Sync Gateway]
* xref:c:conflict.adoc[Handling Data Conflicts]

.


[discrete.colum#c:indexing:::-3n]
=== {empty}
.Dive Deeper . . .
https://forums.couchbase.com/c/mobile/14[Mobile Forum] |
https://blog.couchbase.com/[Blog] |
https://docs.couchbase.com/tutorials/[Tutorials]

.


++++
</div>
++++


