
= Logging API
:page-status:
:page-edition:
:page-aliases:
:page-role:
:description: Introduced in Couchbase Lite 3.2.2.
:keywords: edge mobile api java kotlin android apple logging file console custom

[abstract]
{description}

// Sets the correct mobile sdk for xref links in the common page

:source-language: c

:source-language: c
:url-api-references-classes: https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-c}{empty}/couchbase-lite-c/C/html/group__


// ROOT:partial$commons/common-
[#logsinks]
== LogSinks

Log sinks are thread safe, removing risk of inconsistent states during initialization.

The three destinations for logs have been named as `LogSinks`, following the common source–sink terminology.

The `FileLogSink`, the `ConsoleLogSink` and the `CustomLogSink` are all to be installed in an instance of `LogSinks`.

Only `ConsoleLogSink` is enabled for all logging domains at the warning level by default.
To enable a specific type of log sink, create a log sink object of that type, set its minimum log level and domains, and assign it to `LogSinks`.
To disable a log sink, set it to null or use a log sink with `LogLevel.NONE`.

Couchbase still logs its messages in a handful of named domains and at common log levels: `LogLevel.DEBUG` the most verbose, and `LogLevel.ERROR` only for serious failures.

Accessing `LogSinks` depends on the platform.
In Java, use the method `LogSinks.get()` to obtain an instance.
In Swift, Objective-C, .NET, and C, `LogSinks` provides only static methods, without a singleton instance.

`LogSinks` are immutable: you set the level and domain at which they log in their constructors.
For example, you can only change the level at which the `ConsoleLogSink` forwards messages to the console by installing a new one created for the new log level.

Log output is split into the following streams:

* xref:c:new-logging-api.adoc#lbl-file-logsink[]
+
Each log level writes to a separate file and there is a single retention policy for all files

* xref:c:new-logging-api.adoc#lbl-console-logsink[]
+
--
You can independently configure and control console logs, which provides a convenient method of accessing diagnostic information during debugging scenarios.

With console logging, you can fine-tune diagnostic output to suit specific debug scenarios, without interfering with any logging required by Couchbase Support for the investigation of issues.
--

* xref:c:new-logging-api.adoc#lbl-custom-logsink[]
+
For greater flexibility you can implement a custom logging class.

[#lbl-console-logsink]
=== Logging to the Console

Create an instance of `ConsoleLogSink` initialized with the desired log level and domains and install it.

[source.no-callouts, c, indent=0]
----
include::c:example$code_snippets/main.cpp[tags=new-console-logging]
----

[#lbl-file-logsink]
=== Logging to the Couchbase File Log

The changes necessary to convert the installation of a file logger are also similar.
Create a new `FileLogSink` with the desired properties and install it.

NOTE: `setRotateCount` from before 3.2.2 API is slightly different from `setMaxKeptFiles`.
`setMaxKeptFiles` is the maximum number of log files that will exist at any time and is the count of rotated files (`setRotateCount`) plus one.

[source.no-callouts, c, indent=0]
----
include::c:example$code_snippets/main.cpp[tags=new-file-logging]
----

[#lbl-custom-logsink]
=== Using a Custom Logger

Create an instance of your custom sink, and to install it use `LogSinks.get().setCustom` in Java, or the appropriate static method in Swift, Objective-C, .NET, and C.

As with the other log sinks, you will have to specify the level and domain at which Couchbase logs are forwarded to your custom sink at its creation.

Your custom log sink code will have to change as well.
In C, the custom log sink implementation is a callback that is assigned to CBLCustomLogSink object during creation.

Your logger will receive only logs at the level and domain for which it is initialized.
There is no need to record or filter the logs forwarded to the protected `writeLog` method.

`LogSinks` are meant to support logging by the Couchbase Lite platform. They were never meant as a general framework for logging.

IMPORTANT: Customer code can no longer log, directly, to any of the Couchbase log sinks.
The Console and File log sinks cannot be subclassed and do not publish methods that allow writing logs.
If you need to log to the console for example, you'll have to create your own way of doing so.

[source.no-callouts, c, indent=0]
----
include::c:example$code_snippets/main.cpp[tags=new-custom-logging;set-new-custom-logging]
----


