
= Passive Peer
:page-aliases: clang:p2psync-websocket-using-passive.adoc
ifdef::show_edition[:page-edition: Enterprise Edition]
:page-status: Couchbase Lite 3.2.3
:page-role:
:description: Couchbase Lite's Peer-to-Peer Synchronization enables edge devices to synchronize securely without consuming centralized cloud-server resources


:source-language: c
:url-api-references: https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-c}{empty}/couchbase-lite-c/C/html
:url-api-references-urlendpointconfiguration: {url-api-references}/struct_c_b_l_u_r_l_endpoint_listener_configuration.html
:url-api-references-urlendpointlistener: {url-api-references}/_c_b_l_u_r_l_endpoint_listener_8h.html
:url-api-references-tlsidentity: {url-api-references}/group__TLSIdentity.html
:url-api-class-ListenerPasswordAuthenticator: {url-api-references}/struct_c_b_l_listener_authenticator.html#ab289395196d0bbd4b7bd27bfbf1b9157
:url-api-class-ListenerCertificateAuthenticator: {url-api-references}/struct_c_b_l_listener_authenticator.html#ab772751f6c964814f9c49c934eb9facf
:url-api-class-connection-status: {url-api-references}/struct_c_b_l_connection_status.html

// done in commons

// Present common content including abstract and related content footer blocks

[abstract]
--
Description -- _{description}_ +
_Abstract -- How to set up a Listener to accept a Replicator connection and sync using peer-to-peer_ +
Related Content -- {url-api-references}[API Reference]  |  xref:c:p2psync-websocket-using-passive.adoc[Passive Peer]  |  xref:c:p2psync-websocket-using-active.adoc[Active Peer]
--


.Code Snippets
[NOTE]
All code examples are indicative only.
They demonstrate the basic concepts and approaches to using a feature.
Use them as inspiration and adapt these examples to best practice when developing applications for your platform.


[#introduction]
== Introduction
This content provides code and configuration examples covering the implementation of xref:refer-glossary.adoc#peer-to-peer-sync[Peer-to-Peer Sync] over WebSockets.
Specifically, it covers the implementation of a xref:refer-glossary.adoc#passive-peer[Passive Peer].

Couchbase's Passive Peer (also referred to as the server, or Listener) will accept a connection from an xref:refer-glossary.adoc#active-peer[Active Peer] (also referred to as the client or replicator) and replicate database changes to synchronize both databases.

Subsequent sections provide additional details and examples for the main configuration options.

.Secure Storage
[NOTE]
The use of TLS, its associated keys and certificates requires using secure storage to minimize the chances of a security breach.
The implementation of this storage differs from platform to platform -- see xref:c:p2psync-websocket.adoc#using-secure-storage[Using secure storage].


[#configuration-summary]
== Configuration Summary

You must configure and initialize the Listener with a list of collections to sync.
There is no limit on the number of Listeners you may configure -- <<simple-listener-initialization>> shows a simple initialization and configuration process.

. Identify the local database and the collections to be used -- see: <<initialize-the-listener-configuration>>.

. Optionally, choose a port to use.
By default the system will automatically assign a port -- to over-ride this, see: <<lbl-set-network-and-port>>.

. Optionally, choose a network interface to use.
By default the system will listen on all network interfaces -- to over-ride this see: <<lbl-set-network-and-port>>.

. Set the credentials this server will present to the client for authentication.
Here we show the default TLS authentication, which is an anonymous self-signed certificate.
The server must always authenticate itself to the client.

. Set client security -- define the credentials the server expects the client to present for authentication.
Here we show how basic authentication is configured to authenticate the client-supplied credentials from the http authentication header against valid credentials -- see <<lbl-authenticating-the-client>> for more options. +
Note that client authentication is optional.

. Initialize the listener using the configuration settings.

. <<lbl-start-listener>>.


// Example 1
.Listener configuration and initialization
[#simple-listener-initialization]
====


[source, c]
----
include::c:example$code_snippets/main.cpp[tags="listener-initialize", indent=0]
----
====

<.> Here we show the default TLS authentication, which is an anonymous self-signed certificate.
The server must always authenticate itself to the client.

<.> Here we show how basic authentication is configured to authenticate the client-supplied credentials from the http authentication header against valid credentials -- see <<lbl-authenticating-the-client>> for more options. +
Note that client authentication is optional.


[#api-references]
== API References
You can find {url-api-references}[C API References] here.

[#device-discovery]
== Device Discovery
*This phase is optional:* If the Listener is initialized on a well-known URL endpoint (for example, a static IP Address or well-known DNS address) then you can configure Active Peers to connect to those.

Before initiating the Listener, you may execute a peer discovery phase.
For the Passive Peer, this involves advertising the service using platform libraries,
 and waiting for an invite from the Active Peer.
The connection is established once the Passive Peer has authenticated and accepted an Active Peer's invitation.


[#initialize-the-listener-configuration]
== Initialize the Listener Configuration
Initialize the Listener configuration with a list of collections from the local database -- see <<ex-locdb>>.
All other configuration values take their default setting.


// Example 2
.Specify Local Collections
[#ex-locdb]
====


[source, c]
----
include::c:example$code_snippets/main.cpp[tags="listener-config-db", indent=0]
----
====

<.> Set the local database using the {url-api-references-urlendpointconfiguration}[URLEndpointListenerConfiguration]'s {url-api-references-urlendpointconfiguration}#a79a013447ea7dfc423e43be1ddb6d2fa[database] field. +
The database must be opened before the Listener is started. +
`thisDB` has previously been declared as an object of type `Database`.

[#lbl-set-network-and-port]
== Set Port and Network Interface


[#port-number]
=== Port number
The Listener will automatically select an available port if you do not specify one -- see <<ex-port>> for how to specify a port.

// Example 3
.Specify a port
[#ex-port]
====


[source, c]
----
include::c:example$code_snippets/main.cpp[tags="listener-config-port", indent=0]
----
====

<.> To use a canonical port -- one known to other applications -- specify it explicitly using the {url-api-references-urlendpointconfiguration}#ae164b791eeeb816b9e3c3b25722a13a6[port] method shown here. +
Ensure that firewall rules do not block any port you do specify. +


[#network-interface]
=== Network Interface
The Listener will listen on all network interfaces by default.

// Example 4

.Specify a Network Interface to Use
[#specify-a-network-interface-to-use]
====


[source, c]
----
include::c:example$code_snippets/main.cpp[tags="listener-config-netw-iface", indent=0]
----
====

<.> To specify an interface -- one known to other applications -- identify it explicitly, using the {url-api-references-urlendpointconfiguration}#a5a10543158ed28e4489d1256cb50309f[networkInterface] method shown here.
This must be either an IP Address or network interface name such as `en0`.


[#lbl-tls-security]
== TLS Security

TLS-based encryption is enabled by default, and this setting ought to be used in any production environment.

Couchbase Lite provides several options on how the Listener may be configured with an appropriate TLS Identity -- see <<configure-tls-identity-for-listener>>.

Active peers will use the `wss://` URL scheme to connect to the listener.


[#configure-tls-identity-for-listener]
=== Configure TLS Identity for Listener

Define the credentials the server will present to the client for authentication.
Note that the server must always authenticate itself with the client -- see: xref:c:p2psync-websocket-using-active.adoc#authenticate-listener[Authenticate Listener on Active Peer] for how the client deals with this.

Use {url-api-references-urlendpointconfiguration}[URLEndpointListenerConfiguration]'s
{url-api-references-urlendpointconfiguration}#a3820c7764a7f413f787275dff0d6c262[tlsIdentity] method to configure the TLS Identity used in TLS communication.

If `TLSIdentity` is not set, then the listener uses an auto-generated anonymous self-signed identity.
Whilst the client cannot use this to authenticate the server, it will use it to encrypt communication, giving a more secure option than non-TLS communication.

On macOS, iOS, and Windows, the auto-generated anonymous self-signed identity is saved in secure storage for future use to obviate the need to re-generate it.
Typically, you will configure the Listener's TLS Identity once during the initial launch and re-use it (from secure storage) on any subsequent starts.

On Linux and Android, the auto-generated anonymous self-signed identity is kept in memory and will be regenerated each time the listener is started.

Alternatively, you can use the CBLTLSIdentity_CreateIdentityWithKeyPair() API with a CBLKeyPair object created using CBLKeyPair_CreateWithExternalKey().
This approach enables the use of a developer-provided private key stored in secure key storage of your choice, allowing cryptographic operations to be performed through CBLExternalKeyCallbacks functions without exposing the private key.

Couchbase Lite for C does not provide a convenience function to import a TLS identity from a secure key and certificate data source.
You can generate a TLS identity from existing private key and certificate data in either PEM or DER format.

Here are some example code snippets showing:

////
* Importing a TLS identity -- see: <<ex-import-tls-id>>
////
* Setting TLS identity to expect self-signed certificate -- see: <<ex-create-tls-id>>
* Setting TLS identity to expect anonymous certificate -- see: <<ex-anon-tls-id>>
* Perform cryptographic operations through external key callback functions -- see: <<ex-external-key-callbacks>>

////
.Import Listener's TLS identity
[#ex-import-tls-id]
====

Import an identity from a secure key and certificate data source.

[source, c]
----
include::c:example$code_snippets/main.cpp[tags="listener-config-tls-enable;listener-config-tls-id-full;!listener-config-tls-id-SelfSigned;!listener-config-tls-id-anon", indent=0]
----

====

<.> Ensure TLS is used
<.> Get key and certificate data
<.> Use the retrieved data to create and store the TLS identity
<.> Set this identity as the one presented in response to the client's prompt
////

.Create Self-Signed Cert
[#ex-create-tls-id]
====
Create a TLSIdentity for the server using convenience API.
The system generates a self-signed certificate.

[tabs]
======
macOS / iOS / Windows::
+
--
[source, c]
----
// Certificate Attributes:
FLMutableDict attributes = FLMutableDict_New();
FLMutableDict_SetString(attributes, kCBLCertAttrKeyCommonName, "Dev1");

// Creates and persists the self-signed identity with label named "myidentity":
CBLError error {};
CBLTLSIdentity* identity = CBLTLSIdentity_CreateIdentity(
  kCBLKeyUsagesServerAuth, 
  keypair, 
  attributes, 
  0 /* Default, 1 year */,  
  FLSTR("myidentity") /* Persistent label */, 
  &error
);

// Release the attributes after creating the identity
FLMutableDict_Release(attributes);

// Release identity when you finish using it.
CBLTLSIdentity_Release(identity);
----

. The Common Name (CN) is the only required attribute for generating the certificate. @/kCBLCertAttrKeyCommonName/

. Generate the self-signed TLS identity using the `CBLTLSIdentity_CreateIdentity()` function. @/CBLTLSIdentity_CreateIdentity/

. If a persistent label is specified, the identity (including an RSA key pair and certificate) is also stored in secure key storage. @/FLSTR/

--

Linux / Android::
+
--
[source, c]
----
// Certificate Attributes:
FLMutableDict attributes = FLMutableDict_New();
FLMutableDict_SetString(attributes, kCBLCertAttrKeyCommonName, "Dev1");

// Creates the self-signed identity:
CBLError error {};
CBLTLSIdentity* identity = CBLTLSIdentity_CreateIdentity(
  kCBLKeyUsagesServerAuth, 
  keypair, 
  attributes, 
  0 /* Default, 1 year */,  
  kFLSliceNull /* NULL label */, 
  &error
);

// Release the attributes after creating the identity
FLMutableDict_Release(attributes);

// Release identity when you finish using it.
CBLTLSIdentity_Release(identity);
----

. The Common Name (CN) is the only required attribute for generating the certificate. @/kCBLCertAttrKeyCommonName/

. Generate the self-signed TLS identity using the `CBLTLSIdentity_CreateIdentity()` function. @/CBLTLSIdentity_CreateIdentity/

. The persistent label must be NULL, as identity persistence with a label is not supported.
The created identity is stored in memory only. @/kFLSliceNull/
--
======
====

.Use Anonymous Self-Signed Certificate
[#ex-anon-tls-id]
====

This example uses an _anonymous_ self signed certificate.
Generated certificates are held in secure storage.

[source, c]
----
include::c:example$code_snippets/main.cpp[tags="listener-config-tls-enable;listener-config-tls-id-anon", indent=0]
----

====


<.> Ensure TLS is used. +
This is the default setting.
<.> Authenticate using an anonymous self-signed certificate. +
This is the default setting.

.Use External Key Callbacks
[#ex-external-key-callbacks]
====

[source, c]
----
typedef struct CBLExternalKeyCallbacks
{
  /** Provides the public key's raw data as an ASN.1 DER sequence of [modulus, exponent]. */
  bool (*publicKeyData)(void* externalKey,
                        void* output,
                        size_t outputMaxLen,
                        size_t* outputLen);

  /** Decrypts data using the private key. */
  bool (*decrypt)(void* externalKey,
                  FLSlice input,
                  void* output,
                  size_t outputMaxLen,
                  size_t* outputLen);

  /** Uses the private key to generate a signature of input data. */
  bool (*sign)(void* externalKey,
               CBLSignatureDigestAlgorithm digestAlgorithm,
               FLSlice inputData,
               void* outSignature);

  /** ( Optional ) For freeing any resource when the callbacks are no longer needed.*/
  void (*_cbl_nullable free)(void* externalKey);
} CBLKeyPairCallbacks;
----
====

. The public key is part of an RSA key pair generated by a secure key storage or cryptographic API. @/publicKeyData/

. `externalKey` is an opaque pointer passed to `CBLKeyPair_CreateWithExternalKey()`, typically representing a reference or token used to access the public / private key within the secure storage system. @4

. Use `outputMaxLen` as a guardrail to ensure the public key data size is within the expected range. @6

. Use RSA with PKCS#1 v1.5 padding.
Algorithm names may vary -- for example, RSA/ECB/PKCS1Padding on Java or Android.
Note that depending on the selected key exchange method, the `decrypt()` function may not be invoked during the TLS handshake. @/decrypt/

. You must use PKCS#1 v1.5 padding algorithm when generating the signature. @/CBLSignatureDigestAlgorithm/

. Ensure that the input data, which is already hashed based on the specified digest algorithm, is encoded as an ASN.1 DigestInfo structure in DER format before performing the signing operation.
Some cryptographic libraries may handle the DigestInfo formatting internally. @/inputData/

[#lbl-authenticating-the-client]
== Authenticating the Client

Define how the server (Listener) will authenticate the client as one it is prepared to interact with.

Whilst client authentication is optional, Couchbase lite provides the necessary tools to implement it.
Use the
{url-api-references-urlendpointconfiguration}[URLEndpointListenerConfiguration] class's {url-api-references-urlendpointconfiguration}#aeaa4e119113ab9c9be273b63902cc0df[authenticator] method to specify how the client-supplied credentials are to be authenticated.

Valid options are:

* No authentication -- If you do not define an Authenticator then all clients are accepted.
* Basic Authentication -- uses the Listener {url-api-class-ListenerPasswordAuthenticator}[passwordAuthenticator] to authenticate the client using the client-supplied username and password (from the http authentication header).
* Listener {url-api-class-ListenerCertificateAuthenticator}[certificate] authenticator -- which authenticates the client using a client supplied chain of one or more certificates.
You should initialize the authenticator using one of the following constructors:
** A root certificate, or a list of intermediate certificates and a root certificate -- the client supplied certificate must end at a certificate in this list if it is to be authenticated.
** A block of code that assumes total responsibility for authentication -- it must return a boolean response (true for an authenticated client, or false for a failed authentication).


[#use-basic-authentication]
=== Use Basic Authentication

Define how to authenticate client-supplied username and password credentials.
To use client-supplied certificates instead -- see: <<using-client-certificate-authentication>>


// Example 7
.Password authentication


====


[source, c]
----
include::c:example$code_snippets/main.cpp[tags="listener-config-client-auth-pwd", indent=0]
----
====


<.> Where 'username'/'password' are the client-supplied values (from the http-authentication header) and `validUser`/`validPassword` are the values acceptable to the server.


[#using-client-certificate-authentication]
=== Using Client Certificate Authentication
Define how the server will authenticate client-supplied certificates.

There are two ways to authenticate a client:

* A chain of one or more certificates that ends at a certificate in the list of certificates supplied to the constructor for the Listener {url-api-class-ListenerCertificateAuthenticator}[certificate] authenticator -- see: <<ex-set-cert-auth>>.

* Application logic: This method assumes complete responsibility for verifying and authenticating the client -- see: <<ex-use-app-logic>>.
+
If the parameter supplied to the constructor for the Listener `certificate` authenticator is of type `ListenerCertificateAuthenticatorDelegate`, all other forms of authentication are bypassed.
+
The client response to the certificate request is passed to the method supplied as the constructor parameter.
The logic should take the form of function or block (such as, a closure expression) where the platform allows.

// Example 8
.Set Certificate Authorization
[#ex-set-cert-auth]
====

Configure the server (listener) to authenticate the client against a list of one or more certificates provided by the server to the Listener {url-api-class-ListenerCertificateAuthenticator}[certificate] authenticator.

[source, c]
----
include::c:example$code_snippets/main.cpp[tags="listener-config-client-auth-root, indent=0]", indent=0]
----

====

<.>  Get the identity data to authenticate against.
This can be, for example, from a resource file provided with the app, or an identity previously saved in secure storage.
<.> Configure the authenticator to authenticate the client supplied certificate(s) using these root certs.
A valid client will provide one or more certificates that match a certificate in this list.
<.> Add the authenticator to the Listener configuration.


.Application Logic
[#ex-use-app-logic]
====

Configure the server (listener) to authenticate the client using user-supplied logic.

[source, c]
----
include::c:example$code_snippets/main.cpp[tags="listener-config-client-auth-lambda", indent=0]
----

====

<.>  Get the identity data to authenticate against.
This can be, for example, from a resource file provided with the app, or an identity previously saved in secure storage.
<.>  Configure the Authenticator to pass the root certificates to a user supplied code block.
This code assumes complete responsibility for authenticating the client supplied certificate(s).
It must return a boolean value; with `true` denoting the client supplied certificate authentic.
<.> Add the authenticator to the Listener configuration.


[#delete-tls-identity]
=== Delete Entry

You can remove unwanted TLS identities from secure storage using the convenience API.

// Example 9
.Deleting TLS Identities


====


[source, c]
----
include::c:example$code_snippets/main.cpp[tags="p2p-tlsid-delete-id-from-keychain", indent=0]
----
====


[#the-impact-of-tls-settings]
=== The Impact of TLS Settings

The table in this section shows the expected system behavior (in regards to security) depending on the TLS configuration settings deployed.


.Expected system behavior
[cols="44,44"]
|===
|tlsIdentity (corresponding to server) |Expected system behavior

a| set to nil
a|* The system will auto generate an _anonymous_ self signed cert.
* Active Peers (clients) should be configured to accept self-signed certificates.
* Communication is encrypted

a|Set to server identity generated from a self- or CA-signed certificate

* On first use -- Bring your own certificate and private key; for example, using the `CBLTLSIdentity_CreateIdentity()` method to add it to the secure storage.
* Each time -- Use the server identity from the certificate stored in the secure storage, if supported.
Alternatively, use external key callbacks to access private key stored in secure key storage of your choice.


a|* System will use the configured identity.
* Active Peers will validate the server certificate corresponding to the TLSIdentity (as long as they are configured to not skip validation -- see <<lbl-tls-security>>).

|===


[#lbl-start-listener]
== Start Listener

Once you have completed the Listener's configuration settings you can initialize the Listener instance and start it running -- see: <<initialize-and-start-listener>>

// Example 10
[#initialize-and-start-listener]
.Initialize and start listener
====


[source, c]
----
include::c:example$code_snippets/main.cpp[tags="listener-start", indent=0]
----
====


[#monitor-listener]
== Monitor Listener

Use the Listener's `{url-api-references-urlendpointlistener}#gac53d80177edd2ef849279d8e47af77fe[GetStatus]` property/method to get counts of total and active connections -- see: <<get-connection-counts>>.

You should note that these counts can be extremely volatile.
So, the actual number of active connections may have changed, by the time the `{url-api-class-connection-status}[ConnectionStatus]` class returns a result.

// Example 11
.Get connection counts
[#get-connection-counts]
====


[source, c]
----
include::c:example$code_snippets/main.cpp[tags="listener-status-check", indent=0]
----
====


[#stop-listener]
== Stop Listener

It is best practice to check the status of the Listener's connections and stop only when you have confirmed that there are no active connections -- see <<get-connection-counts>>.

// Example 12
.Stop listener using `stop` method


====


[source, c]
----
include::c:example$code_snippets/main.cpp[tags="listener-stop", indent=0]
----
====


NOTE: Closing the database will also close the Listener.


[#related-content]
== Related Content
++++
<div class="card-row three-column-row">
++++

[.column]
=== {empty}
.How to
* xref:c:p2psync-websocket-using-passive.adoc[Passive Peer]
* xref:c:p2psync-websocket-using-active.adoc[Active Peer]


.

[.column]
=== {empty}
.Concepts
* xref:c:landing-p2psync.adoc[Peer-to-Peer Sync]

* {url-api-references}[API References]

.


[.column]
=== {empty}
.Community Resources ...
https://forums.couchbase.com/c/mobile/14[Mobile Forum] |
https://blog.couchbase.com/[Blog] |
https://docs.couchbase.com/tutorials/[Tutorials]

.
xref:tutorials:cbl-p2p-sync-websockets:swift/cbl-p2p-sync-websockets.adoc[Getting Started with Peer-to-Peer Synchronization]


++++
</div>
++++


