= Couchbase Lite for C
ifdef::show_edition[:page-edition: {release}]
ifdef::prerelease[:page-status: {prerelease}]
:page-role:
:description: Couchbase Lite for C platform introduction

include::partial$_std-cbl-hdr-c.adoc[]

:param-related!:
:topic-group!:
include::{root-partials}block-abstract.adoc[]

== Introduction

_Couchbase Lite_ now has an officially supported *C API*.
It builds on the success of an engineering labs project that originally introduced a well-received C API for Couchbase Lite

The C API now includes support for Enterprise-grade features like database encryption.
This optimized implementation is ensured feature parity with our other Couchbase Lite platforms and is supported on a wide-reange of mobile and desktop platforms -- see: {supported-os--xref}.

The ease of building language bindings on top of the C API means  application developers can build for edge and embedded IoT devices using their preferred languages to harness the power of Couchbase Lite.

== FLeece





include::{root-partials}block-related-content-data.adoc[]
