:docname: prebuilt-database
:page-module: c
:page-relative-src-path: prebuilt-database.adoc
:page-origin-url: https://github.com/couchbase/docs-couchbase-lite.git
:page-origin-start-path:
:page-origin-refname: antora-assembler-simplification
:page-origin-reftype: branch
:page-origin-refhash: (worktree)
[#c:prebuilt-database:::]
== Pre-built Database
:page-aliases: clang:prebuilt-database.adoc
:page-role:
:description: How to handle pre-built databases in your Couchbase Lite on C app



// BEGIN -- inclusion -- {module-partials}_define_module_attributes.adoc
//  Usage:  Here we define module specific attributes. It is invoked during the compilation of a page,
//          making all attributes available for use on the page.
//  UsedBy: ROOT:partial$_std_cbl_hdr.adoc

//
// CBL-C Maintenance release number
//
//

// VECTOR SEARCH attributes
//


// BEGIN - Set attributes pointing to API references for this module

//
//






// DATABASE module and functions
// Database(im)

// :url-api-method-database-compact: https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-c}{empty}/couchbase-lite-c/C/html/group__database.html#gaa4b06dcb7427cafeabde8486f5f03f10[CBLDatabase_PerformMaintenance()]




// Begin -- DatabaseConfiguration
// End -- DatabaseConfiguration


// DOCUMENTS






// QUERY RELATED CLASSES and METHODS

// Result Classes and Methods




// Query class and methods





// Expression class and methods
// :url-api-references-query-classes: https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-c}{empty}/couchbase-lite-c/C/html/group__[Query Class index]


// ArrayFunction class and methods


// Function class and methods
//

// Where class and methods
//
// https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-c}{empty}/couchbase-lite-c/C/html/group__Where.html
// NOT SET[Where]

// orderby class and methods
//
// https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-c}{empty}/couchbase-lite-c/C/html/group__OrderBy.html

// GroupBy class and methods
//
// https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-c}{empty}/couchbase-lite-c/C/html/group__GroupBy.html
// NOT SET[GroupBy]

// URLEndpointConfiguration





















// diag: Env+Module c


// Replicator API










// Note there is a replicator.status property AND
// a ReplicationStatus class/struct --- oh yes, easy to confuse.







// ReplicatorConfiguration API




// Repl Cfg Props







// Begin Replicator Retry Config
// End Replicator Retry Config


// :url-api-prop-replicator-config-ServerCertificateVerificationMode: https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-c}{empty}/couchbase-lite-c/C/html/struct_c_b_l_replicator_configuration.html#(py)serverCertificateVerificationMode[serverCertificateVerificationMode]

// :url-api-enum-replicator-config-ServerCertificateVerificationMode: https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-c}{empty}/couchbase-lite-c/C/html/struct_c_b_l_replicator_configuration.html{Enums/ServerCertificateVerificationMode.html[serverCertificateVerificationMode enum]







// CBLPropertyEncryptor gab116a23be8bd24b86349379f370ef60c
// CBLPropertyDecryptor ga24a60a3d6f9816e1d32464cc31a15c0c
// CBLEncryptable gaaf20d661f9684632a005f0a4e52656b3

// Meta API




// BEGIN Logs and logging references
// :url-api-class-logging: https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-c}{empty}/couchbase-lite-c/C/htmlLogging.html[CBLLogging classes]







// END  Logs and logging references

// End define module specific attributes

// BEGIN::module page attributes
// :snippet-p2psync-ws: {snippets-p2psync-ws--c}
// END::Local page attributes

[abstract]
--
Description -- _{description}_ +
_Abstract -- This content explains how to include a snapshot of a pre-built database in your package to shorten initial sync time and reduce bandwidth use_ +
--

// BEGIN -- inclusion -- common-prebuilt-database.adoc - Used in {commons-}database.adoc file

// over-ride important-caption to create a MUST DO block instead
// :important-caption: Must Do



[discrete#c:prebuilt-database:::overview]
=== Overview


pass:q,a[_pass:q,a[pass:q,a[Couchbase{nbsp}Lite]]_] supports  pre-built databases. You can pre-load your app with data instead of syncing it from pass:q,a[_pass:q,a[Sync{nbsp}Gateway]_] during startup to minimize consumer wait time (arising from data setup) on initial install and launch of the application.

Avoiding an initial bulk sync reduces startup time and network transfer costs.

It is typically more efficient to download bulk data using the http/ftp stream employed during the application installation than to install a smaller application bundle and then use a replicator to pull in the bulk data.

Pre-loaded data is typically public/shared, non-user-specific data that is static. Even if the data is not static, you can still benefit from preloading it and only syncing the changed documents on startup.

The initial sync of any pre-built database pulls in any content changes on the server that occurred after its incorporation into the app, updating the database.

.To use a prebuilt database:
****
. Create a new Couchbase Lite database with the required dataset -- see <<c:prebuilt-database:::crt-db>>
. Incorporate the pre-built database with your app bundle as an asset/resource -- see <<c:prebuilt-database:::bundle-db>>
. Adjust the start-up logic of your app to check for the presence of the required database. +
If the database doesn't already exist, create one using the bundled pre-built database.
Initiate a sync to update the data -- see <<c:prebuilt-database:::deploy-db>>
****


[discrete#c:prebuilt-database:::crt-db]
=== Creating Pre-built database


These steps should form part of your build and release process:

. Create a fresh Couchbase Lite database (every time)
+
[IMPORTANT]
--
*Always start with a fresh database for each app version*; this ensures there are no xref:refer-glossary.adoc#checkpoint[checkpoint] issues

*Otherwise:*  You will invalidate the cached xref:refer-glossary.adoc#checkpoint[checkpoint] in the packaged database, and instead reuse the same database in your build process (for subsequent app versions).
--
. Pull the data from Sync Gateway into the new Couchbase Lite database
+
[IMPORTANT]
--
Ensure the replication used to populate Couchbase Lite database *uses the exact same remote URL and replication config parameters (channels and filters)* as those your app will use when it is running.

*Otherwise:* ... there will be a xref:refer-glossary.adoc#checkpoint[checkpoint] mismatch and the app will attempt to pull the data down again

Don't, for instance, create a pre-built database against a staging Sync Gateway server and use it within a production app that syncs against a production Sync Gateway.
--
+
You can use the cblite tool (`cblite cp`) for this -- see: https://github.com/couchbaselabs/couchbase-mobile-tools/blob/master/Documentation.md#cp-aka-export-import-push-pull[cblite cp (export, import, push, pull)]  |  https://github.com/couchbaselabs/couchbase-mobile-tools/blob/master/README.cblite.md[cblite on GitHub]
+
.*Alternatively* ...

* You can write a simple CBL app to just initiate the required pull sync -- see: xref:c:replication.adoc[Remote Sync Gateway]
* A third party community Java app is available.
It provides a UI to create a local Couchbase Lite database and pull data from a Sync Gateway database -- see:
https://github.com/Infosys/CouchbaseLiteTester[CouchbaseLite Tester]
+
NOTE: Couchbase accepts no responsibility for the ongoing availability, maintenance, or support of this third party community contribution, nor for the provision of support for issues arising from its use.

. Create the *same* indexes the app will use (wait for the replication to finish before doing this).


[discrete#c:prebuilt-database:::bundle-db]
=== Bundle a Database with an Application


Copy the database into your app package.

Put it in an appropriate place (for example, an assets or resource folder).

Where the platform permits you can zip the database.

*Alternatively* ... rather than bundling the database within the app, the app could pull the database down from a CDN server on launch.


[discrete#c:prebuilt-database:::database-encryption]
=== Database Encryption

IMPORTANT: This is an https://www.couchbase.com/products/editions[Enterprise Edition] feature.



If you are using an encrypted database,
https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-c}{empty}/couchbase-lite-c/C/html/group__database.html#ga027d34b2de65b040ecf42a2a83bf6720[CBL_CopyDatabase()]
does not change the encryption key.
The encryption key specified in the config when opening the database is the encryption key used for both the original database and copied database.

If you copied an un-encrypted database and want to apply encryption to the copy, or if you want to change (or remove) the encryption key applied to the copy:

. Provide the original encryption-key (if any) in the database copy's configuration using https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-c}{empty}/couchbase-lite-c/C/html/struct_c_b_l_database_configuration.html#aaab04fb9d092ff02693eea611efefc55[CBLDatabaseConfiguration.encryptionKey()]
. Open the database copy
. Use https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-c}{empty}/couchbase-lite-c/C/html/group__database.html#ga76a603bc678ceae18c9610b8a8274a09[CBLDatabase_ChangeEncryptionKey()] on the database copy to set the required encryption key. +
NOTE: To remove encryption on the copy, provide a null encryption-key


[discrete#c:prebuilt-database:::deploy-db]
=== Using Pre-built Database on App Launch


During the application start-up logic, check if database exists in the required location, and *if not*:

. Locate the pre-packaged database (for example, in the assets or other resource folder)

. Copy the pre-packaged database to the required location
+
Use the API's https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-c}{empty}/couchbase-lite-c/C/html/group__database.html#ga027d34b2de65b040ecf42a2a83bf6720[CBL_CopyDatabase()] method -- see: <<c:prebuilt-database:::lbl-code>>; this ensures that a UUID is generated for each copy
//  -- see: <<copy-db>>
+
IMPORTANT: *Do not copy the database using any other method* +
*Otherwise:* Each copy of the app will invalidate the other apps' xref:refer-glossary.adoc#checkpoint[checkpoints] because a new UUID was not generated.

. Open the database; you can now start querying the data and using it

. Start a pull replication, to sync any changes
+
The replicator uses the pre-built database's xref:refer-glossary.adoc#checkpoint[checkpoint] as the timestamp to sync from; only documents changed since then are synced
+
[IMPORTANT]
--
If you used cblite to pull the data *without including a port number with the URL* and are replicating in a Java or iOS (swift/ObjC) app -- *you must include the port number in the URL provided to the replication* (port 443 for `wss://` or 80 for `ws://`).

*Otherwise:* You will get a xref:refer-glossary.adoc#checkpoint[checkpoint] mismatch. +
This is caused by a URL discrepancy, which arises because `cblite` automatically adds the default port number when none is specified, *but* the Java and iOS (swift/ObjC) replicators DO NOT.

--

+
NOTE: Start your normal application logic immediately, unless it is essential to have the absolute up-to-date data set to begin.
That way the user is not kept hanging around watching a progress indicator.
They can begin interacting with your app whilst any out-of-data data is being updated.

.Copy database using API
[#lbl-code]
// BEGIN inclusion -- block -- block_tabbed_code_example.adoc
//
//  Allows for abstraction of the showing of snippet examples
//  which makes displaying tabbed snippets for platforms with
//  more than one native language to show -- Android (Kotlin and Java)
//
// Surrounds code in Example block
//
//  PARAMETERS:
//    param-tags comma-separated list of tags to include/exclude
//    param-leader text for opening para of an example block
//
//  USE:
//    :param_tags: query-access-json
//    include::partial$block_show_snippet.adoc[]
//    :param_tags!:
//

[#c:prebuilt-database:::lbl-code]
====


// Show Main Snippet
[source, c]
----
include ::c:example$code_snippets/main.cpp[tags="prebuilt-database", indent=0]
// Note: Getting the path to a database is platform-specific.  For desktop (including RPi)
// this can be a simple filesystem path.  For iOS you need to get the path from the
// main bundle.  For Android you need to extract it from your assets to a temporary directory
// and then pass that path.

// NOTE: No error handling, for brevity (see getting started)

CBLError err;
const char* path = "/path/to/travel-sample.cblite2";
if(!CBL_DatabaseExists(FLSTR("travel-sample.cblite2"), kFLSliceNull)) {
    CBL_CopyDatabase(FLStr(path), FLSTR("travel-sample"), NULL, &err);
}
----




// close example block

====

// Tidy-up atttibutes created
// END -- block_show_snippet.doc



// Reset important-caption
// END -- inclusion -- common-prebuilt-database.adoc - Used in {commons-}database.adoc file

// :param-add3-title: {empty}
// :param-reference: reference-p2psync


[discrete#c:prebuilt-database:::related-content]
=== Related Content
++++
<div class="card-row three-column-row">
++++

[.column]
==== {empty}
.How to . . .
* xref:c:gs-prereqs.adoc[Prerequisites]
* xref:c:gs-install.adoc[Install]
* xref:c:gs-build.adoc[Build and Run]


.

[discrete.colum#c:prebuilt-database:::-2n]
==== {empty}
.Learn more . . .
* xref:c:database.adoc[Databases]
* xref:c:document.adoc[Documents]
* xref:c:blob.adoc[Blobs]
* xref:c:replication.adoc[Remote Sync Gateway]
* xref:c:conflict.adoc[Handling Data Conflicts]

.


[.column]
// [.content]
[discrete#c:prebuilt-database:::-3]
==== {empty}
.Dive Deeper . . .
//* Community
https://forums.couchbase.com/c/mobile/14[Mobile Forum] |
https://blog.couchbase.com/[Blog] |
https://docs.couchbase.com/tutorials/[Tutorials]


.



++++
</div>
++++


