= Live Queries
:page-aliases: clang:query-live.adoc
:page-role:
:description: Couchbase mobile database live query concepts


:source-language: c

:source-language: c
:url-api-references-classes: https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-c}{empty}/couchbase-lite-c/C/html/group__


[abstract]
--
Description -- _{description}_ +
--

[#overview]
== Overview


[#activating-a-live-query]
== Activating a Live Query


A live query is a query that, once activated, remains active and monitors the database for changes; refreshing the result set whenever a change occurs.
As such, it is a great way to build reactive user interfaces -- especially table/list views -- that keep themselves up to date.

*So, a simple use case may be:* A replicator running and pulling new data from a server, whilst a live-query-driven UI automatically updates to show the data without the user having to manually refresh.
This helps your app feel quick and responsive.

To activate a LiveQuery just add a change listener to the query statement.
It will be immediately active.
When a change is detected the query automatically runs, and posts the new query result to any observers (change listeners).


.Starting a Live Query
[#ex-qry-start]


[#ex-qry-start]
====

[tabs]
=====
C::
+
--
[source, c]
----
include::c:example$code_snippets/main.cpp[tags="live-query", indent=0]
----
<.> Build the query statements
<.> Activate the _live_ query by attaching a listener.
Save the token in order to detach the listener and stop the query later -- see xref:c:query-live.adoc#ex-qry-stop[]
--

{cpp}::
+
--
[source, cpp]
----
include::c:example$code_snippets/cbl_cpp.cpp[tags="live-query", indent=0]
----
<.> Build the query statements
<.> Activate the _live_ query by attaching a listener.
Save the token in order to detach the listener and stop the query later -- see xref:c:query-live.adoc#ex-qry-stop[]
--
=====

====

.Stop a Live Query
[#ex-qry-stop]


[#ex-qry-stop]
====

[tabs]
=====
C::
+
--
[source, c]
----
include::c:example$code_snippets/main.cpp[tags="stop-live-query", indent=0]
----
<.> Here we use the change listener token from xref:c:query-live.adoc#ex-qry-start[] to remove the listener.
Doing so stops the live query.
--

{cpp}::
+
--
[source, cpp]
----
include::c:example$code_snippets/cbl_cpp.cpp[tags="stop-live-query", indent=0]
----
<.> Here we use the change listener token from xref:c:query-live.adoc#ex-qry-start[] to remove the listener.
Doing so stops the live query.
--
=====

====