= Upgrade
:page-aliases:
:page-role:


:source-language: c

:source-language: c
:url-api-references-classes: https://docs.couchbase.com/mobile/{major}.{minor-c}.{maintenance-c}{empty}/couchbase-lite-c/C/html/group__


[#3-4-0-upgrade]
== {major}.{minor-c}.{maintenance-c}{empty} Upgrade

Couchbase Lite {major}.{minor} is a non-breaking upgrade from 3.3.
Update your Couchbase Lite dependency to {major}.{minor} -- no API or configuration changes are required.

[WARNING]
--
When upgrading from Couchbase Lite 3.4.0 to the 4.x release line, upgrade directly to 4.1.0 or later.
Couchbase Lite 4.x versions below 4.1.0 do not include all APIs added in 3.4.0 (Multipeer Replicator with Bluetooth and Auto Switching, Replication Correlation ID, and on Android, Kotlin Serialization; and on C, the C++ API).
--

=== Vector Search Extension

Couchbase Lite 3.4.0 is compatible with Vector Search Extension 2.0.0 only.
If your application uses Vector Search, update the Vector Search Extension to 2.0.0 when upgrading to Couchbase Lite 3.4.0.

[#downgrading-couchbase-lite]
== Downgrading Couchbase Lite

[#downgrading-between-major-releases]
=== Downgrading Between Major Releases

*No Downgrade Support* - Downgrades between major versions of Couchbase Lite (CBL) are not supported.
Once you upgrade to a new major version, downgrading to a previous major version may lead to incompatibility issues.

[#downgrading-between-minor-releases]
=== Downgrading Between Minor Releases

*Conditional Downgrade Support* - Downgrade support for minor releases is considered on a case-by-case basis.
The release notes for each minor version will clarify whether downgrades are supported.

[#downgrading-between-patch-releases]
=== Downgrading Between Patch Releases

*Full Downgrade Support* - Downgrades between patch releases are supported.
Users can safely downgrade between different patch versions within the same minor release.

[#related-content]
== Related Content
++++
<div class="card-row three-column-row">
++++

[.column]
=== {empty}
.How to . . .
* xref:c:gs-prereqs.adoc[Prerequisites]
* xref:c:gs-install.adoc[Install]
* xref:c:gs-build.adoc[Build and Run]

.

[.column]
=== {empty}
.Learn more . . .
* xref:c:database.adoc[Databases]
* xref:c:document.adoc[Documents]
* xref:c:blob.adoc[Blobs]
* xref:c:replication.adoc[Remote Sync Gateway]
* xref:c:conflict.adoc[Handling Data Conflicts]

.

[.column]
=== {empty}
.Dive Deeper . . .
https://forums.couchbase.com/c/mobile/14[Mobile Forum] |
https://blog.couchbase.com/[Blog] |
https://docs.couchbase.com/tutorials/[Tutorials]

.

++++
</div>
++++