There are two ways to authenticate from a Couchbase Lite client: <<Basic Authentication>> or <<Session Authentication>>.

==== Basic Authentication

You can provide a user name and password to the basic authenticator class method.
Under the hood, the replicator will send the credentials in the first request to retrieve a `SyncGatewaySession` cookie and use it for all subsequent requests during the replication.
This is the recommended way of using basic authentication.
<<ex-base-auth>> shows how to initiate a one-shot replication as the user *username* with the password *password*.

.Basic Authentication
[#ex-base-auth]
:param-tags: basic-authentication
include::{root-partials}block_tabbed_code_example.adoc[]
:param-tags!:


==== Session Authentication

Session authentication is another way to authenticate with Sync Gateway.
A user session must first be created through the xref:sync-gateway:ROOT:refer/rest-api-public.adoc#/session/post\__db___session[`+POST /{tkn-db}/_session+`] endpoint on the Public REST API.
The HTTP response contains a session ID which can then be used to authenticate as the user it was created for.

<<ex-session-auth>> shows how to initiate a one-shot replication with the session ID that is returned from the `+POST /{tkn-db}/_session+` endpoint.

.Session Authentication
[#ex-session-auth]
:param-tags: session-authentication
include::{root-partials}block_tabbed_code_example.adoc[]
:param-tags!:
