Couchbase Lite supports certificate pinning.
Certificate pinning is a technique that can be used by applications to "pin" a host to its certificate.
The certificate is typically delivered to the client by an out-of-band channel and bundled with the client.
In this case, Couchbase Lite uses this embedded certificate to verify the trustworthiness of the server and no longer needs to rely on a trusted third party for that (commonly referred to as the Certificate Authority).

The `openssl` command can be used to create a new self-signed certificate and convert the `.pem` file to a `.cert` file (see xref:sync-gateway::configuring-ssl.adoc#creating-your-own-self-signed-certificate[creating your own self-signed certificate]).
You should then have 3 files: `cert.pem`, `cert.cer` and `key.pem`.

The `cert.pem` and `key.pem` can be used in the Sync Gateway configuration (see xref:sync-gateway::configuring-ssl.adoc#installing-the-certificate[installing the certificate]).

On the Couchbase Lite side, the replication must be configured with the `cert.cer` file.

[source]
----
include::{snippet}[tag=certificate-pinning,indent=0]
----

This example loads the certificate from the application sandbox, then converts it to the appropriate type to configure the replication object.
