
include::{root-partials}_block-caveats.adoc[tag=ee-only-feature]

_Couchbase Lite on {param-title}_ includes the ability to encrypt Couchbase Lite databases.
This allows mobile applications to secure the data at rest, when it is being stored on the device.
The algorithm used to encrypt the database is 256-bit AES.

To enable encryption, you must set the `DatabaseConfiguration.encryptionKey` property to the encryption key of your choice.
Provide this encryption key every time the database is opened -- see <<ex-sdb-encrypt>>.

.Database Encryption
[#ex-sdb-encrypt]
:param-tags: database-encryption
include::{root-partials}_block_tabbed_code_example.adoc[]
:param-tags!:


Couchbase Lite does not persist the key.
It is the application's responsibility to manage the key and store it in a platform specific secure store such as Apple's https://developer.apple.com/documentation/security/keychain_services[Keychain] or Android's https://developer.android.com/training/articles/keystore[Keystore].

An encrypted database can only be opened with the same language SDK that was used to encrypt it in the first place.
So a database encrypted using the Swift SDK, and then exported, is readable only by the Swift SDK.

==== Upgrading from 1.x when Encryption is Enabled

If you're migrating an application from Couchbase Lite 1.x to 2.x, note that the <<database-upgrade,automatic database upgrade>> functionality is *not supported* for encrypted databases.
Thus, to upgrade an encrypted 1.x database, you should do the following:

// set the correct language name for 1.4 pages
ifndef::param-language:[:param-language: {param-name}]
ifeval::["{param-language}"=="{lang-name-android}"]
:param-language: {lang-name-java}
endif::[]
. Disable encryption using the Couchbase Lite 1.x framework (see https://docs-archive.couchbase.com/couchbase-lite/1.4/{param-language}.html#database-encryption[1.x encryption guide])
. Open the database file with encryption enabled using the Couchbase Lite 2.x framework.

Since it is not possible to package Couchbase Lite 1.x and Couchbase Lite 2.x in the same application this upgrade path would require two successive upgrades.
If you are using Sync Gateway to synchronize the database content, it may be preferable to run a pull replication from a new 2.x database with encryption enabled and delete the 1.x local database.

:param-language!: