Starting version 2.5, Couchbase Lite provides a logging API that unifies the logging behavior across all platforms, making debugging and troubleshooting easier during development and in production.
The actual retrieval of the logs from the device is out of scope of this feature.

There are three different logging features:

Console based logging::
Enabled by default.
Console based logging is often used to facilitate troubleshooting during development.
+
File based logging::
Disabled by default.
File based logging is supported in two formats:

* a binary format mode which is much more efficient in terms of storage and performance.
It is the default configuration for file based logging.
* a plaintext mode
+
It is recommended that you use binary log format.
However, in order to view the binary encoded log files, you will need a decoder.
To decode the binary logs, there is a binary log decoder called the *cbl-log* which is a tool downloadable from link:https://github.com/couchbaselabs/couchbase-mobile-tools/blob/master/README.cbl-log.md[couchbaselabs/couchbase-mobile-tools, window=_blank].
+
The following example enables file based logging.
+
[source]
----
include::{snippet}[tag=file-logging,indent=0]
----
+
Custom logging::
Disabled by default.
Provides apps the ability to register a callback function in order to receive Couchbase Lite log messages.
The messages can be logged using any external logging framework.
Apps must implement the `Logger` interface.
+
[source]
----
include::{snippet}[tag=custom-logging,indent=0]
----
And set it on the `custom` property.
+
[source]
----
include::{snippet}[tag=set-custom-logging,indent=0]
----

==== Decoding binary logs

The *cbl-log* tool should be used to decode binary log files.

[{tabs}]
====
macOS::
+
--
Download the *cbl-log* tool using `wget`.

[source,console]
----
wget https://packages.couchbase.com/releases/couchbase-lite-log/2.6.0/couchbase-lite-log-2.6.0-macos.zip
----

Navigate to the *bin* directory and run the `cbl-log` executable.

[source,bash]
----
$ ./cbl-log logcat LOGFILE <OUTPUT_PATH>
----
--

CentOS::
+
--
Download the *cbl-log* tool using `wget`.

[source,console]
----
wget https://packages.couchbase.com/releases/couchbase-lite-log/2.6.0/couchbase-lite-log-2.6.0-centos.zip
----

Navigate to the *bin* directory and run the `cbl-log` executable.

[source,bash]
----
cbl-log logcat LOGFILE <OUTPUT_PATH>
----
--

Windows::
+
--
Download the *cbl-log* tool using PowerShell.

[source,powershell]
----
Invoke-WebRequest https://packages.couchbase.com/releases/couchbase-lite-log/2.6.0/couchbase-lite-log-2.6.0-windows.zip -OutFile couchbase-lite-log-2.6.0-windows.zip
----

Run the `cbl-log` executable.

[source,powershell]
----
$ .\cbl-log.exe logcat LOGFILE <OUTPUT_PATH>
----
--
====
