// Begin required attributes
// :cbl-log-version: the required cbl-log version number (eg 2.7.0)
// :snippet: the path to the language specific example code-snippets
ifndef::cbl-log-version[:cbl-log-version: UNDEFINED-CBL-LOG-VERSION]
ifndef::snippet[:snippet: UNDEFINED-SNIPPET-PATH]
:url-cbl-log-binaries: https://packages.couchbase.com/releases/couchbase-lite-log/{cbl-log-version}/couchbase-lite-log-{cbl-log-version}
//  End required attributes

// Begin text block
From version 2.5, Couchbase Lite provides a logging API that unifies the logging behavior across all platforms, making debugging and troubleshooting easier during development and in production.

NOTE: The retrieval of logs from the device is out of scope of this feature.

Available logging features include:

* Console based logging
* File based logging
* Custom logging

== Console based logging
Default: Enabled.

Console based logging is often used to facilitate troubleshooting during development.

== File based logging
Default: Disabled.

Available file based logging formats:

* Binary -- most efficient for storage and performance. It is the default for file based logging.
* Plaintext

We recommend using the binary log format and
a decoder, such as *cbl-log*, to view them. Download *cbl-log* from link:https://github.com/couchbaselabs/couchbase-mobile-tools/blob/master/README.cbl-log.md[couchbaselabs/couchbase-mobile-tools, window=_blank].

NOTE: See  <<Decoding binary logs>>.

The following example enables file based logging.

[source]
----
include::{snippet}[tag=file-logging,indent=0]
----

== Custom logging
Default: Disabled.

Allows registration of a callback function to receive Couchbase Lite log messages, which may be logged using any external logging framework.

Apps must implement the `Logger` interface, as shown below:

[source, {source-language}]
----
include::{snippet}[tag=custom-logging,indent=0]
----
And set it on the `custom` property.

[source, {source-language}]
----
include::{snippet}[tag=set-custom-logging,indent=0]
----

== Decoding binary logs

The *cbl-log* tool should be used to decode binary log files as shown in these examples.

[{tabs}]
====
macOS::
+
--
Download the *cbl-log* tool using `wget`.

[source,console]
----
wget {url-cbl-log-binaries}-macos.zip
----

Navigate to the *bin* directory and run the `cbl-log` executable.

[source,bash]
----
$ ./cbl-log logcat LOGFILE <OUTPUT_PATH>
----
--

CentOS::
+
--
Download the *cbl-log* tool using `wget`.

[source,console]
----
wget {url-cbl-log-binaries}-centos.zip
----

Navigate to the *bin* directory and run the `cbl-log` executable.

[source,bash]
----
cbl-log logcat LOGFILE <OUTPUT_PATH>
----
--

Windows::
+
--
Download the *cbl-log* tool using PowerShell.

[source,powershell]
----
Invoke-WebRequest {url-cbl-log-binaries}-windows.zip -OutFile couchbase-lite-log-{cbl-log-version}-windows.zip
----

Run the `cbl-log` executable.

[source,powershell]
----
$ .\cbl-log.exe logcat LOGFILE <OUTPUT_PATH>
----
--
====
