// BEGIN tagged-inclusions -- CBL change log
// Contains details on changes to features, behaviors, api or config for all platforms

// BEGIN -- Maintenance Releases

// == RELEASE 3.0.x
// tag::full-3-0-x[]

// tag::all-3-0-x[]
// == New Features
// tag::all-new-3-0-x[]
// end::all-new-3-0-x[]
// tag::all-changed-3-0-x[]
// == Changed Features
// tag::all-changed-features-3-0-x[]
// {ns-this}

// end::all-changed-features-3-0-x[]
// === Changes to API
// tag::all-changed-api-3-0-x[]
// end::all-changed-api-3-0-x[]
// end::all-changed-3-0-x[]
// end::all-3-0-x[]
// tag::java-3-0-x[]
// end::java-3-0-x[]
// end::full-3-0-x[]

// END -- Maintenance Releases

// BEGIN -- Major Release

== RELEASE 3.0
// tag::full-3-0[]

// tag::all--3-0[]
== New Features
// tag::all-new-3-0[]

// tag::all-new-cbl-for-kotlin-3-0[]
=== Kotlin Support in Android

_Couchbase Lite for Android_ delivers an idiomatic Kotlin API out-of-the-box.
This enables seamless integration with Android apps developed in Kotlin without the need for custom extensions.


Kotlin developers can now build apps using https://developer.android.com/kotlin/common-patterns[common Kotlin Patterns] and use familiar Kotlin features such as:

* Nullability annotations
* Named parameters
* Kotlin Flows

Java support and functionality continues for Android.
You can choose whether to use the Kotlin extensions API or continue using the Java api.

ifdef::param-link[Read More . . . {param-link}]

// end::all-new-cbl-for-kotlin-3-0[]


// tag::all-new-cbl-for-c-3-0[]
=== Couchbase Lite for C

_Couchbase Lite_ now has an officially supported *C API*, which builds on the success of the well-received engineering labs _C API for Couchbase Lite_.

The C API now includes support for Enterprise-grade features like database encryption.
This optimized implementation is ensured feature parity with our other Couchbase Lite platforms and is supported on a wide-range of mobile and desktop platforms -- see: xref:c:supported-os.adoc[Supported Platforms].

The ease of building language bindings on top of the C API means  application developers can build for edge and embedded IoT devices using their preferred languages to harness the power of Couchbase Lite.

ifdef::param-link[Read More . . . {param-link}]

// end::all-new-cbl-for-c-3-0[]

// tag::all-new-n1ql-string-3-0[]
=== {sqlpp_cbm}/N1QL Query Strings

Couchbase Lite's {sqlpp_cbm} for Mobile query API vastly simplifies the integration of Couchbase Lite within hybrid/cross platform apps.

N1QL for Mobile is an implementation of the emerging SQL-for-JSON query language specification (SQL++).
It provides native, hybrid and cross-platform mobile app developers with a consistent, convenient and flexible interface to query JSON documents within the embedded database using a SQL-based syntax.
This means developers can reuse queries across platforms, reducing development, testing and maintenance costs.

ifdef::param-link[Read More . . . {param-link}]

// end::all-new-n1ql-string-3-0[]

// end::all-new-3-0[]

// tag::all-changed-3-0[]
== Changes

=== Features
// tag::all-changed-features-3-0[]

// tag::all-changed-features-access-revocation-3-0[]
=== Auto-purge on Channel Access Revocation

An auto-purge feature is introduced for loss of access to channels and the documents in them.
This is important for enforcement of data governance and data retention policies.

Channels are the fundamental mechanism for enforcement of access control using Sync Gateway.
They guarantee that only users with access to a specific channel can access documents in that channel.

When a user loses access to a channel (_and so to its documents_) Couchbase Lite clients will auto purge all local documents on devices that belong to the revoked channel (during Pull or PushAndPull replication), unless the user has access to the document via some other channel.

ifdef::param-link[Read More . . . {param-link}]

// end::all-changed-features-access-revocation-3-0[]

// tag::all-changed-features-access-json-api-3-0[]
=== Document API Support for JSON Data

The Couchbase Lite API now offers out-of-the box support for document data in JSON format.
This will make it easier for developers' applications to store, transform and manipulate JSON data in the database.

The API offers JSON support for Documents, MutableDocuments, Arrays, MutableArrays, Dictionaries, MutableDictionaries and Query Results.

ifdef::param-link[Read More . . . {param-link}]

// CBL-1582/DOC-8063
=== Replicator Change Listeners

The API is enhanced to allow replicator listeners to be added at any point without requiring a replicator restart.


// end::all-changed-features-access-json-api-3-0[]


// end::all-changed-features-3-0[]

=== API
// tag::all-changed-api-3-0[]
The API has been enhanced with the following changes:

// * The _{url-api-method-database-close}_ method now automatically handles stopping open replicators, closing peer-to-peer websocket listener and removing observers for live queries.
// * The _{url-api-method-database-delete}_ method
// now automatically handles stopping open replicators, closing peer-to-peer websocket listener and removing observers for live queries.
// * The _{url-api-method-replicator-isDocumentPending}_ method checks whether or not the document with the given ID has any pending revisions to push
// * The _{url-api-method-replicator-getPendingDocumentIds}_ method gets the Ids of all documents currently pending push
// * _{url-api-property-meta-revisionid}_ property is now available as a metadata property, which can be accessed directly in queries

// end::all-changed-api-3-0[]
=== Behavior
// tag::all-changed-behavior-3-0[]
The following established behaviors are changed in this release:

// end::all-changed-behavior-3-0[]
// end::all-changed-3-0[]


// end::all-3-0[]

// tag::java-3-0[]

// end::java-3-0[]

// end::full-3-0[]

// END tagged-inclusions -- CBL change log