// inclusions -- CBL change log

// tag::latest-full[]

// tag::latest-all-[]
== New Features
// tag::latest-all-new[]

// tag::latest-all-new-p2p[]
=== Peer-to-Peer Synchronization
Using Couchbase Lite's Peer-to-Peer Synchronization solution, you can build offline-first applications on edge devices that directly collaborate in secure bi-directional database synchronization without depending on centralized cloud-based control.

The solution provides an out-of-the-box implementation of a websocket based listener for use in peer-to-peer applications communicating over in IP-based networks.

Read More . . . {param-link1}

// end::latest-all-new-p2p[]
// end::latest-all-new[]

// tag::latest-all-changed[]
== Changed Features
// tag::latest-all-changed-features[]
{ns-this}

// end::latest-all-changed-features[]
=== Changes to API
// tag::latest-all-changed-api[]
The API has been enhanced with the following changes:

* The _{url-api-method-database-close}_ method now automatically handles stopping open replicators, closing peer-to-peer websocket listener and removing observers for live queries.
* The _{url-api-method-database-delete}_ method
now automatically handles stopping open replicators, closing peer-to-peer websocket listener and removing observers for live queries.
* The _{url-api-method-replicator-isDocumentPending}_ method checks whether or not the document with the given ID has any pending revisions to push
* The _{url-api-method-replicator-getPendingDocumentIds}_ method gets the Ids of all documents currently pending push
* _{url-api-property-meta-revisionid}_ property is now available as a metadata property, which can be accessed directly in queries

// end::latest-all-changed-api[]
// end::latest-all-changed[]


// end::latest-all[]

// tag::latest-java[]

// end::latest-java[]

// end::latest-full[]
