// BEGIN tagged-inclusions -- CBL change log
// Contains details on changes to features, behaviors, api or config for all platforms

== RELEASE 2.8.1
// tag::full-2-8-1[]

// tag::all-2-8-1[]
== New Features
// tag::all-new-2-8-1[]
// end::all-new-2-8-1[]
// tag::all-changed-2-8-1[]
== Changed Features
// tag::all-changed-features-2-8-1[]
// {ns-this}

// end::all-changed-features-2-8-1[]
=== Changes to API
// tag::all-changed-api-2-8-1[]
// end::all-changed-api-2-8-1[]
// end::all-changed-2-8-1[]
// end::all-2-8-1[]
// tag::java-2-8-1[]
// end::java-2-8-1[]
// end::full-2-8-1[]

== RELEASE 2.8
// tag::full-2-8[]

// tag::all--2-8[]
== New Features
// tag::all-new-2-8[]

// tag::all-new-p2p-2-8[]
=== Peer-to-Peer Synchronization
Using Couchbase Lite's Peer-to-Peer Synchronization solution, you can build offline-first applications on edge devices that directly collaborate in secure bi-directional database synchronization without depending on centralized cloud-based control.

The solution provides an out-of-the-box implementation of a websocket based listener for use in peer-to-peer applications communicating over in IP-based networks.

Read More . . . {param-link1}

// end::all-new-p2p-2-8[]
// end::all-new-2-8[]

// tag::all-changed-2-8[]
== Changed Features
// tag::all-changed-features-2-8[]
{ns-this}

// end::all-changed-features-2-8[]
=== Changes to API
// tag::all-changed-api-2-8[]
The API has been enhanced with the following changes:

* The _{url-api-method-database-close}_ method now automatically handles stopping open replicators, closing peer-to-peer websocket listener and removing observers for live queries.
* The _{url-api-method-database-delete}_ method
now automatically handles stopping open replicators, closing peer-to-peer websocket listener and removing observers for live queries.
* The _{url-api-method-replicator-isDocumentPending}_ method checks whether or not the document with the given ID has any pending revisions to push
* The _{url-api-method-replicator-getPendingDocumentIds}_ method gets the Ids of all documents currently pending push
* _{url-api-property-meta-revisionid}_ property is now available as a metadata property, which can be accessed directly in queries

// end::all-changed-api-2-8[]
// end::all-changed-2-8[]


// end::all-2-8[]

// tag::java-2-8[]

// end::java-2-8[]

// end::full-2-8[]

// END tagged-inclusions -- CBL change log