// inclusions -- CBL change log

// tag::latest-full[]

// tag::latest-all-[]
== New Features
// tag::latest-all-new[]

// tag::latest-all-new-p2p[]
=== Peer-to-Peer Synchronization
Using Couchbase Lite's Peer-to-Peer Synchronization solution, you can build offline-first applications on edge devices that directly collaborate in secure bi-directional database synchronization without depending on centralized cloud-based control.

The solution provides an out-of-the-box implementation of a websocket based listener for use in peer-to-peer applications communicating over in IP-based networks.

Read More . . . {param-link1}

// end::latest-all-new-p2p[]
// end::latest-all-new[]

// tag::latest-all-changed[]
== Changed Features
// tag::latest-all-changed-features[]
{ns-this}

// end::latest-all-changed-features[]
=== Changes to API
// tag::latest-all-changed-api[]
The API has been enhanced with the following changes:

* The Database Close and Delete methods now automatically handle stopping open replicators, closing peer-to-peer websocket listener and removing observers for live queries.
* The Replicator's getPendingDocumentIds method will retrieve the Ids of all documents currently pending push
* The Revision ID is now available as a metadata property, which can be accessed directly in queries

// end::latest-all-changed-api[]
// end::latest-all-changed[]


// end::latest-all[]

// tag::latest-java[]

// end::latest-java[]

// end::latest-full[]