Replication Filters allow you to have quick control over which documents are stored as the result of a push and/or pull replication.



==== Push Filter

A push filter allows an app to push a subset of a database to the server, which can be very useful in some circumstances.
For instance, high-priority documents could be pushed first, or documents in a "draft" state could be skipped.

:param-tags: replication-push-filter
// pass:q,a,m[include::{root-partials}_block_tabbed_code.adoc[]]
.Push Filter
include::{root-partials}_block_tabbed_code.adoc[]
:param-tags!:

ifndef::is-c[]
<1> The callback should follow the semantics of a https://en.wikipedia.org/wiki/Pure_function[pure function^].
Otherwise, long running functions would slow down the replicator considerably.
Furthermore, your callback should not make assumptions about what thread it is being called on.
endif::is-c[]
ifdef::is-c[<1> Do not provide long running functions, which could slow down the replicator. Nor make assumptions about the thread the function is being called on.]


==== Pull Filter

A pull filter gives an app the ability to validate documents being pulled, and skip ones that fail.
This is an important security mechanism in a peer-to-peer topology with peers that are not fully trusted.

NOTE: Pull replication filters are not a substitute for channels.
Sync Gateway xref:sync-gateway::data-routing.adoc[channels] are designed to be scalable (documents are filtered on the server) whereas a pull replication filter is applied to a document once it has been downloaded.

:param-tags: replication-pull-filter
include::{root-partials}_block_tabbed_code.adoc[]
:param-tags!:
ifndef::is-c[]
<1> The callback should follow the semantics of a https://en.wikipedia.org/wiki/Pure_function[pure function^].
Otherwise, long running functions would slow down the replicator considerably.
Furthermore, your callback should not make assumptions about what thread it is being called on.
endif::is-c[]
ifdef::is-c[<1> Do not provide long running functions, which could slow down the replicator. Nor make assumptions about the thread the function is being called on.]

NOTE: Losing access to a document (via the Sync Function) also triggers the pull replication filter.
Filtering out such an event would retain the document locally.
As a result, there would be a local copy of the document disjointed from the one that resides on Couchbase Server.
Further updates to the document stored on Couchbase Server would not be received in pull replications and further local edits could be potentially pushed, which would result in 409 errors since access has been revoked.
