== Symbolication

In order to make sense of a crash report you will need to symbolicate
 its content.
Symbolication being the process of replacing memory addresses in a crash report with human-readable function names and line numbers.
To do this you need to have debug symbol (`.dSYM`) files for the application and for Couchbase Lite's framework.

== Finding local dSYM

To locate the local dSYM files:

* For scheme based builds, they are located in the derived data path
* For the target based builds, they are located in the configuration build directory path, as specified in the _target_ setting
* For archives, they are located in `.xcarchive`.

TIP: If you still cannot locate the file, then use `mdfind` as described in the
_Symbolication Troubleshooting_ section of the _Apple Technical Note TN2151 --
Understanding and Analyzing Application Crash Reports_: https://developer.apple.com/library/archive/technotes/tn2151/_index.html

== The CouchbaseLite dSYM

Couchbase Lite's `dSYM` folder is located in the same directory as the Couchbase Lite binary framework (this also applies for _Cocoapod_ and _Carthage_).
It has the same filename as framework but has a `.dSYM` extension.

.dSYM in CouchbaseLiteSwift
====
----
couchbase-lite-swift_enterprise_2.7.0/iOS/CouchbaseLiteSwift.framework.dSYM
----
====

== Bitcode enabled Apps

Apple creates new dSYM files for apps uploaded to the _App Store_ or _TestFlight_ with _Bitcode_ enabled.
To symbolicate crash reports generated by these apps you must download the generated dSYM files. Do this using _Xcode's Organizer_ or direcly from _App Store Connect_.

=== Downloading dSYM using Xcode Organizer

. Within _Xcode's_  _Archives Organiser_, select the required archive
. Within the _Archive Information_ dialog panel, select *Download Debug Symbols* button
+
The dSYM files are downloaded to the archive bundle in a folder named `dSYMs`
+
See _Download debug symbols_: https://help.apple.com/xcode/mac/current/#/devef5928039

=== Downloading dSYM directly from App Store Connect

. Inside _My Apps_ choose the *Activity* section
. Locate the required build (the one you want to download dSYM files for)
. In the _Includes Symbols_ column, select the download `dSYM` link .

== Using third-party crash report tools

You can upload your dSYM files to third-party crash reporting tools for analysis, either automatically via script or a manual _zip_ file upload. Links for some of the more popular crash reporting tools are included below.

.Third party crash reporting tools
====
* Firebase Crashlytics: https://firebase.google.com/docs/crashlytics/get-deobfuscated-reports
* Instabug: https://docs.instabug.com/docs/ios-symbolication
* Bugsee: https://docs.bugsee.com/sdk/ios/symbolication/
* Microsoft Visual Studio App Center: https://docs.microsoft.com/en-us/appcenter/diagnostics/ios-symbolication
* Apteligent: https://www.apteligent.com/technical-resource/symbolicating-an-ios-crash-report/
====

== Obfuscated symbols (`_hidden`)

Xcode includes obfuscated symbols in dSYM files if apps with _Bitcode_ enabled are uploaded to Apple without symbols.

In such cases you need to to de-obfuscate dSYM files before symbolicating.
De-obfuscation is done automatically if downloading through Xcode. But if you use _App Store Connect_, you may need to, use the `xcrun` command on each .dSYM file inside the downloaded dSYM folder.

.De-obfuscation using xcrun
====
----
xcrun dsymutil -symbol-map <pathToApplicationArchieve>.xcarchive/BCSymbolMaps <pathToDownloadedDSYMs>/3B15C133-88AA-35B0-B8BA-84AF76826CE0.dSYM
----
====

TIP: See Translating 'hidden' symbol names back to their original names: https://developer.apple.com/library/archive/technotes/tn2151/_index.html

