= Query Construction
:page-layout: article
:page-status:
:page-edition:
:page-role:
:description: Working with Couchbase Lite's data model  -- Constructing queries

include::partial$_std-cbl-hdr-java.adoc[]

:param-abstract!:
:param-related: {xref-cbl-pg-query-predictive} | {xref-cbl-pg-indexing} | {xref-cbl-pg-query}
:topic-group: Queries
include::{root-partials}block-abstract.adoc[]


== Overview
Couchbase Lite for {param-title}'s database queries are based on expressions, of the form:

----
SELECT {blank-field} FROM database WHERE {blank-field}, ORDERed by {blank-field}
----

Semantics are based on Couchbase's N1QL query language.

There are several parts to specifying a query:

SELECT:: Specifies the projection, which is the part of the document that is to be returned.
FROM:: Specifies the database to query the documents from.
JOIN:: Specifies the matching criteria in which to join multiple documents.
WHERE:: Specifies the query criteria that the result must satisfy.
GROUP BY:: Specifies the query criteria to group rows by.
ORDER BY:: Specifies the query criteria to sort the rows in the result.

== SELECT statement

With the SELECT statement, you can query and manipulate JSON data.
With projections, you retrieve just the fields that you need and not the entire document.

A SelectResult represents a single return value of the query statement.
You can specify a comma separated list of `SelectResult` expressions in the select statement of your query.
For instance the following select statement queries for the document `_id` as well as the `type` and `name` properties of all documents in the database.
In the query result, we print the `_id` and `name` properties of each row using the property name getter method.

[source,json]
----
{
    "_id": "hotel123",
    "type": "hotel",
    "name": "Apple Droid"
}
----

[source]
----
include::{snippet}[tags=query-select-meta,indent=0]
----

The `SelectResult.all()` method can be used to query all the properties of a document.
In this case, the document in the result is embedded in a dictionary where the key is the database name.
The following snippet shows the same query using `SelectResult.all()` and the result in JSON.

[source]
----
include::{snippet}[tags=query-select-all,indent=0]
----

[source,json]
----
[
    {
        "travel-sample": {
            "callsign": "MILE-AIR",
            "country": "United States",
            "iata": "Q5",
            "icao": "MLA",
            "id": 10,
            "name": "40-Mile Air",
            "type": "airline"
        }
    },
    {
        "travel-sample": {
            "callsign": "TXW",
            "country": "United States",
            "iata": "TQ",
            "icao": "TXW",
            "id": 10123,
            "name": "Texas Wings",
            "type": "airline"
        }
    }
]
----

== WHERE statement

Similar to SQL, you can use the where clause to filter the documents to be returned as part of the query.
The select statement takes in an `Expression`.
You can chain any number of Expressions in order to implement sophisticated filtering capabilities.

=== Comparison

The {url-api-references}/com/couchbase/lite/Expression.html[comparison operators] can be used in the WHERE statement to specify on which property to match documents.
In the example below, we use the `equalTo` operator to query documents where the `type` property equals "hotel".

[source,json]
----
{
    "_id": "hotel123",
    "type": "hotel",
    "name": "Apple Droid"
}
----

[source]
----
include::{snippet}[tags=query-where,indent=0]
----

== Collection Operators

{url-api-references}/com/couchbase/lite/ArrayFunction.html[Collection operators] are useful to check if a given value is present in an array.

=== CONTAINS Operator

The following example uses the `Function.arrayContains` to find documents whose `public_likes` array property contain a value equal to "Armani Langworth".

[source,json]
----
{
    "_id": "hotel123",
    "name": "Apple Droid",
    "public_likes": ["Armani Langworth", "Elfrieda Gutkowski", "Maureen Ruecker"]
}
----

[source]
----
include::{snippet}[tags=query-collection-operator-contains,indent=0]
----

=== IN Operator

The `IN` operator is useful when you need to select based on a specified term matching any element of a defined list of values.
The following example compiles a list of values from `first`, `last` and `username` property value. It then selects if any of those values equals "Armani".

[source]
----
include::{snippet}[tags=query-collection-operator-in,indent=0]
----

=== Like Operator

The {url-api-references}/com/couchbase/lite/Expression.html#like-com.couchbase.lite.Expression-[`like`] operator can be used for string matching.

// DOC-5813 change replicated from Java-Android during cherr-pick //

The `like` operator performs **case sensitive** matches.
So, to make the string matching case-insensitive, use `Function.lower` or `Function.upper` to transform the matched strings to lowercase or uppercase equivalents.

In the example below, we are looking for documents of type `landmark` where the name property exactly matches the string "Royal engineers museum".

TIP: For case-insensitive comparison, use `Function.lower` to align the cases of the strings being compared.

The following query returns "landmark" type documents regardless of the name's case (so, for example: "Royal Engineers Museum", "royal engineers museum", "ROYAL ENGINEERS MUSEUM" are all matches).

[source]
----
include::{snippet}[tags=query-like-operator,indent=0]
----

=== Wildcard Match

We can use `%` sign within a `like` expression to do a wildcard match against zero or more characters.
Using wildcards allows you to have some fuzziness in your search string.

In the example below, we are looking for documents of `type` "landmark" where the name property matches any string that begins with "eng" followed by zero or more characters, the letter "e", followed by zero or more characters.

The following query will return "landmark" `type` documents with name matching "Engineers", "engine", "english egg" , "England Eagle" and so on.

NOTE: Once again, we are using `Function.lower` to make the search act as case insensitive.

NOTE: The matches may span word boundaries.

[source]
----
include::{snippet}[tags=query-like-operator-wildcard-match,indent=0]
----

=== Wildcard Character Match

We can use an `_` sign within a like expression to do a wildcard match against a single character.

In the example below, we are looking for documents of type "landmark" where the `name` property matches any string that begins with "eng" followed by exactly 4 wildcard characters and ending in the letter "r".
The following query will return "landmark" `type` documents with the `name` matching "Engineer", "engineer" and so on.

[source]
----
include::{snippet}[tags=query-like-operator-wildcard-character-match,indent=0]
----

=== Regex Operator

Similar to wildcard `like` expressions, `regex` expressions based pattern matching allow you to have some fuzziness in your search string.

The `regex` operator is case sensitive.

TIP: For more on the regex spec used by {cbl} see http://www.cplusplus.com/reference/regex/ECMAScript/[cplusplus regex reference page]

In the example below, we are looking for documents of `type` "landmark" where the name property matches any string (on word boundaries) that begins with "eng" followed by exactly 4 wildcard characters and ending in the letter "r".
The following query will return "landmark" type documents with name matching "Engine", "engine" and so on.
Note that the `\b` specifies that the match must occur on word boundaries.

[source]
----
include::{snippet}[tags=query-regex-operator,indent=0]
----

== Query Deleted Document

You can query documents that have been deleted (tombstones).
The following example shows how to query deleted documents in the database.

[source]
----
include::{snippet}[tags=query-deleted-documents,indent=0]
----

== JOIN statement

The JOIN clause enables you to create new input objects by combining two or more source objects.

The following example uses a JOIN clause to find the airline details which have routes that start from RIX.
This example JOINS the document of type "route" with documents of type "airline" using the document ID (`_id`) on the "airline" document and `airlineid` on the "route" document.

[source]
----
include::{snippet}[tags=query-join,indent=0]
----

== GROUP BY statement

You can perform further processing on the data in your result set before the final projection is generated.
The following example looks for the number of airports at an altitude of 300 ft or higher and groups the results by country and timezone.

[source,json]
----
{
    "_id": "airport123",
    "type": "airport",
    "country": "United States",
    "geo": { "alt": 456 },
    "tz": "America/Anchorage"
}
----

[source]
----
include::{snippet}[tags=query-groupby,indent=0]
----

[source,text]
----
There are 138 airports on the Europe/Paris timezone located in France and above 300 ft
There are 29 airports on the Europe/London timezone located in United Kingdom and above 300 ft
There are 50 airports on the America/Anchorage timezone located in United States and above 300 ft
There are 279 airports on the America/Chicago timezone located in United States and above 300 ft
There are 123 airports on the America/Denver timezone located in United States and above 300 ft
----

== ORDER BY statement

It is possible to sort the results of a query based on a given expression result.
The example below returns documents of type equal to "hotel" sorted in ascending order by the value of the title property.

[source]
----
include::{snippet}[tags=query-orderby,indent=0]
----

[source,text]
----
Aberdyfi
Achiltibuie
Altrincham
Ambleside
Annan
Ardèche
Armagh
Avignon
----

include::{root-partials}block-related-content-query.adoc[]
