= API Changes
:page-partials:
ifdef::show_edition[:page-edition: {release}]
ifdef::prerelease[:page-status: {prerelease}]
:page-role:
:description: Couchbase Lite API Changes for this release

include::partial$_set_page_context_for_swift.adoc[]

//  tag::content[]
== Removed APIs

=== ResetCheckpoint

.Alternative
  `replicator.start(reset:)`

.Before
----
replicator.resetCheckpoint()
replicator.start()
----

.After
----
replicator.start(true)
----

=== Database.setLogLevel

.Alternative
`Database.log.console`

.Before
----
Database.setLogLevel(.verbose, domain: .all)
----

.After
----
Database.log.console.domain = .all
Database.log.console.level = .verbose
----

=== Database.compact
.Alternative

https://docs.couchbase.com/mobile/3.0.0-beta02/couchbase-lite-swift/Classes/Database.html#/s:18CouchbaseLiteSwift8DatabaseC18performMaintenance4typeyAA0F4TypeO_tKF[Database.performMaintenance(type:)]

.Before
----
try testdb.compact()
----

.After
----
try testdb.performMaintenance(type: .compact)
----



== Deprecated API

=== Match
.Alternative
`FullTextFunction.match(indexName:)`

.Before
----
let index = FullTextExpression.index ("indexName")
let q = QueryBuilder.select([SelectResult.
expression(Meta.id)])
            .from(DataSource.database(testdb)) +
            .where(index.match("'queryString'"))
----

.After
----
let q = QueryBuilder.select([SelectResult.expression(Meta.id)])
            .from(DataSource.database(testdb))
            .where(FullTextFunction.match(indexName: "indexName", query: "'queryString'"))
----


=== isNullOrMissing and notNullOrMissing

.Alternatives
`isNotValued()` +
`isValued()`

.Before
----
|let q1 = QueryBuilder.select([SelectResult.expression(Meta.id)])
            .from(DataSource.database(testdb))
            .where(Expression.property("missingProp").isNullOrMissing())

let q2 = QueryBuilder.select([SelectResult.expression(Meta.id)])
            .from(DataSource.database(testdb))
            .where(Expression.property("notMissingProp").notNullOrMissing())
----

.After
----
let q1 = QueryBuilder.select([SelectResult.expression(Meta.id)])
            .from(DataSource.database(testdb))
            .where(Expression.property("missingProp").isNotValued())

let q2 = QueryBuilder.select([SelectResult.expression(Meta.id)])
            .from(DataSource.database(testdb))
            .where(Expression.property("notMissingProp").isValued())
----

== Updated API

=== Configuration
The following classes are changed to Swift struct.

* DatabaseConfiguration
* ReplicatorConfiguration
* URLEndpointListenerConfiguration

.Before
----

let config = DatabaseConfiguration()
config.encryptionKey = EncryptionKey.password(password!)

let config = ReplicatorConfiguration(database: db, target: target)
config.continuous = true
----

.After
----
var config = DatabaseConfiguration()
config.encryptionKey = EncryptionKey.password(password!)

var config = ReplicatorConfiguration(database: db, target: target)
config.continuous = true
----

=== ATAN2

CAUTION: Breaking change

`ATAN2(x, y)` now becomes `ATAN2(y, x)`

.Before
[source, {source-language}]
----
let p = Expression.property("number")
let q = QueryBuilder.select([SelectResult.expression(Function.atan2(x: Expression.int(90), y: p))])
            .from(DataSource.database(testdb))
----

.After
[source, {source-language}]
----
let q = QueryBuilder.select([SelectResult.expression(Function.atan2(y: Expression.int(90), x: p))])
            .from(DataSource.database(testdb))
----
// end::content[]

include::{root-partials}block-related-content-std.adoc[]
