//
// Copyright (c) 2019 Couchbase, Inc All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
package com.couchbase.code_snippets

import android.content.Context
import android.util.Log
import android.widget.Toast
import com.couchbase.code_snippets.TensorFlowModel
import com.couchbase.lite.ArrayFunction
import com.couchbase.lite.BasicAuthenticator
import com.couchbase.lite.Blob
import com.couchbase.lite.Conflict
import com.couchbase.lite.ConflictResolver
import com.couchbase.lite.CouchbaseLite
import com.couchbase.lite.CouchbaseLiteException
import com.couchbase.lite.DataSource
import com.couchbase.lite.Database
import com.couchbase.lite.DatabaseConfiguration
import com.couchbase.lite.DatabaseEndpoint
import com.couchbase.lite.Dictionary
import com.couchbase.lite.Document
import com.couchbase.lite.DocumentFlag
import com.couchbase.lite.EncryptionKey
import com.couchbase.lite.Endpoint
import com.couchbase.lite.Expression
import com.couchbase.lite.FullTextExpression
import com.couchbase.lite.FullTextIndexItem
import com.couchbase.lite.Function
import com.couchbase.lite.IndexBuilder
import com.couchbase.lite.Join
import com.couchbase.lite.ListenerToken
import com.couchbase.lite.LogDomain
import com.couchbase.lite.LogFileConfiguration
import com.couchbase.lite.LogLevel
import com.couchbase.lite.Logger
import com.couchbase.lite.Message
import com.couchbase.lite.MessageEndpoint
import com.couchbase.lite.MessageEndpointConnection
import com.couchbase.lite.MessageEndpointDelegate
import com.couchbase.lite.MessageEndpointListener
import com.couchbase.lite.MessageEndpointListenerConfiguration
import com.couchbase.lite.MessagingCloseCompletion
import com.couchbase.lite.MessagingCompletion
import com.couchbase.lite.Meta
import com.couchbase.lite.MutableDictionary
import com.couchbase.lite.MutableDocument
import com.couchbase.lite.Ordering
import com.couchbase.lite.PredictionFunction
import com.couchbase.lite.PredictiveIndex
import com.couchbase.lite.PredictiveModel
import com.couchbase.lite.ProtocolType
import com.couchbase.lite.Query
import com.couchbase.lite.QueryBuilder
import com.couchbase.lite.ReplicatedDocument
import com.couchbase.lite.Replicator
import com.couchbase.lite.ReplicatorConfiguration
import com.couchbase.lite.ReplicatorConnection
import com.couchbase.lite.Result
import com.couchbase.lite.ResultSet
import com.couchbase.lite.SelectResult
import com.couchbase.lite.SessionAuthenticator
import com.couchbase.lite.URLEndpoint
import com.couchbase.lite.ValueIndex
import com.couchbase.lite.ValueIndexItem
import com.couchbase.lite.Where
import java.io.File
import java.io.IOException
import java.io.InputStream
import java.net.URI
import java.net.URISyntaxException
import java.time.Instant
import java.time.temporal.ChronoUnit
import java.util.*

// tag::example-app[]
class Examples(private val context: Context) {
    private val database: Database? = null
    private var replicator: Replicator? = null

    //@Test
    @Throws(CouchbaseLiteException::class, URISyntaxException::class)
    fun testGettingStarted() {
        // tag::getting-started[]

        // Initialize the Couchbase Lite system
        CouchbaseLite.init(context)

        // Get the database (and create it if it doesn’t exist).
        val config = DatabaseConfiguration()
        config.setDirectory(context.filesDir.absolutePath)
        val database = Database("getting-started", config)


        // Create a new document (i.e. a record) in the database.
        var mutableDoc: MutableDocument = MutableDocument()
            .setFloat("version", 2.0f)
            .setString("type", "SDK")

        // Save it to the database.
        database.save(mutableDoc)

        // Update a document.
        mutableDoc = database.getDocument(mutableDoc.getId()).toMutable()
        mutableDoc.setString("language", "Java")
        database.save(mutableDoc)
        val document: Document = database.getDocument(mutableDoc.getId())
        // Log the document ID (generated by the database) and properties
        Log.i(TAG, "Document ID :: " + document.getId())
        Log.i(TAG, "Learning " + document.getString("language"))

        // Create a query to fetch documents of type SDK.
        val query: Query = QueryBuilder.select(SelectResult.all())
            .from(DataSource.database(database))
            .where(Expression.property("type").equalTo(Expression.string("SDK")))
        val result: ResultSet = query.execute()
        Log.i(
            TAG,
            "Number of rows ::  " + result.allResults().size()
        )

        // Create replicators to push and pull changes to and from the cloud.
        val targetEndpoint: Endpoint =
            URLEndpoint(URI("ws://localhost:4984/getting-started-db"))
        val replConfig = ReplicatorConfiguration(database, targetEndpoint)
        replConfig.setReplicatorType(ReplicatorConfiguration.ReplicatorType.PUSH_AND_PULL)

        // Add authentication.
        replConfig.setAuthenticator(BasicAuthenticator("sync-gateway", "password"))

        // Create replicator (be sure to hold a reference somewhere that will prevent the Replicator from being GCed)
        val replicator = Replicator(replConfig)

        // Listen to replicator change events.
        replicator.addChangeListener({ change ->
            if (change.getStatus().getError() != null) {
                Log.i(
                    TAG,
                    "Error code ::  " + change.getStatus().getError().getCode()
                )
            }
        })

        // Start replication.
        replicator.start()

        // end::getting-started[]
        database.delete()
    }

    // end::example-app[]
    @Throws(CouchbaseLiteException::class, IOException::class)
    fun test1xAttachments() {
        // if db exist, delete it
        deleteDB("android-sqlite", context.filesDir)
        ZipUtils.unzip(getAsset("replacedb/android140-sqlite.cblite2.zip"), context.filesDir)
        val db = Database("android-sqlite", DatabaseConfiguration())
        try {
            val doc: Document = db.getDocument("doc1")

            // For Validation
            val attachments: Dictionary = doc.getDictionary("_attachments")
            val blob: Blob = attachments.getBlob("attach1")
            val content: ByteArray = blob.getContent()
            // For Validation
            val attach =
                String.format(Locale.ENGLISH, "attach1").toByteArray()
            Arrays.equals(attach, content)
        } finally {
            // close db
            db.close()
            // if db exist, delete it
            deleteDB("android-sqlite", context.filesDir)
        }
        val document: Document = MutableDocument()

        // tag::1x-attachment[]
        val attachments: Dictionary = document.getDictionary("_attachments")
        val blob: Blob?
        blob = if (attachments != null) attachments.getBlob("avatar") else null
        val content: ByteArray?
        content = if (blob != null) blob.getContent() else null
        // end::1x-attachment[]
    }

    // ### Initializer
    fun testInitializer() {
        // tag::sdk-initializer[]
        // Initialize the Couchbase Lite system
        CouchbaseLite.init(context)
        // end::sdk-initializer[]
    }

    // ### New Database
    @Throws(CouchbaseLiteException::class)
    fun testNewDatabase() {
        // tag::new-database[]
        val config = DatabaseConfiguration()
        config.setDirectory(context.filesDir.absolutePath) // <.>
        val database = Database("my-database", config)
        // end::new-database[]
        database.delete()
    }

    // ### Database Encryption
    @Throws(CouchbaseLiteException::class)
    fun testDatabaseEncryption() {
        // tag::database-encryption[]
        val config = DatabaseConfiguration()
        config.setEncryptionKey(EncryptionKey("PASSWORD"))
        val database = Database("mydb", config)
        // end::database-encryption[]
    }

    // ### Logging
    fun testLogging() {
        // tag::logging[]
        Database.setLogLevel(LogDomain.DATABASE, LogLevel.VERBOSE)
        Database.setLogLevel(LogDomain.QUERY, LogLevel.VERBOSE)
        // end::logging[]
    }

    fun testEnableCustomLogging() {
        // tag::set-custom-logging[]
        // this custom logger will never be asked to log an event
        // with a log level < WARNING
        Database.log.setCustom(LogTestLogger(LogLevel.WARNING)) // <.>
        // end::set-custom-logging[]
    }

    // ### Console logging
    @Throws(CouchbaseLiteException::class)
    fun testConsoleLogging() {
        // tag::console-logging[]
        Database.log.getConsole().setDomain(LogDomain.ALL_DOMAINS) // <.>
        Database.log.getConsole().setLevel(LogLevel.VERBOSE) // <.>
        // end::console-logging[]
    }

    // ### File logging
    @Throws(CouchbaseLiteException::class)
    fun testFileLogging() {
        // tag::file-logging[]
        val path = context.cacheDir
        val LogCfg = LogFileConfiguration(path.toString()) // <.>
        LogCfg.setMaxSize(10240) // <.>
        LogCfg.setMaxRotateCount(5) // <.>
        LogCfg.setUsePlainText(false) // <.>
        Database.log.getFile().setConfig(LogCfg)
        Database.log.getFile().setLevel(LogLevel.INFO) // <.>
        // end::file-logging[]
    }

    fun writeConsoleLog() {
        // tag::write-console-logmsg[]
        Database.log.Console.Log(LogLevel.Warning, LogDomain.Replicator, "Any old log message")
        // end::write-console-logmsg[]
    }

    fun writeCustomLog() {
        // tag::write-custom-logmsg[]
        if (Database.log.Custom)
            Log(LogLevel.Warning, LogDomain.Replicator, "Any old log message")
        // end::write-custom-logmsg[]
    }

    fun writeFileLog() {
        // tag::write-file-logmsg[]
        Database.log.File.Log(LogLevel.Warning, LogDomain.Replicator, "Any old log message")
        // end::write-file-logmsg[]
    }

    // ### Loading a pre-built database
    @Throws(IOException::class)
    fun testPreBuiltDatabase() {
        // tag::prebuilt-database[]
        // Note: Getting the path to a database is platform-specific.
        // For Android you need to extract it from your
        // assets to a temporary directory and then pass that path to Database.copy()
        val configuration = DatabaseConfiguration()
        if (!Database.exists("travel-sample", context.filesDir)) {
            ZipUtils.unzip(getAsset("travel-sample.cblite2.zip"), context.filesDir)
            val path = File(context.filesDir, "travel-sample")
            try {
                Database.copy(path, "travel-sample", configuration)
            } catch (e: CouchbaseLiteException) {
                e.printStackTrace()
            }
        }
        // end::prebuilt-database[]
    }

    // helper methods
    // if db exist, delete it
    private fun deleteDB(name: String, dir: File) {
        // database exist, delete it
        if (Database.exists(name, dir)) {
            // sometimes, db is still in used, wait for a while. Maximum 3 sec
            for (i in 0..9) {
                try {
                    Database.delete(name, dir)
                    break
                } catch (ex: CouchbaseLiteException) {
                    try {
                        Thread.sleep(300)
                    } catch (ignore: InterruptedException) {
                    }
                }
            }
        }
    }

    // ### Initializers
    fun testInitializers() {
        // tag::initializer[]
        val newTask = MutableDocument()
        newTask.setString("type", "task")
        newTask.setString("owner", "todo")
        newTask.setDate("createdAt", Date())
        try {
            database.save(newTask)
        } catch (e: CouchbaseLiteException) {
            Log.e(TAG, e.toString())
        }
        // end::initializer[]
    }

    // ### Mutability
    fun testMutability() {
        try {
            database.save(MutableDocument("xyz"))
        } catch (ignore: CouchbaseLiteException) {
        }

        // tag::update-document[]
        val document: Document = database.getDocument("xyz")
        val mutableDocument: MutableDocument = document.toMutable()
        mutableDocument.setString("name", "apples")
        try {
            database.save(mutableDocument)
        } catch (e: CouchbaseLiteException) {
            Log.e(TAG, e.toString())
        }
        // end::update-document[]
    }

    // ### Typed Accessors
    fun testTypedAccessors() {
        val newTask = MutableDocument()

        // tag::date-getter[]
        newTask.setValue("createdAt", Date())
        val date: Date = newTask.getDate("createdAt")
        // end::date-getter[]
    }

    // ### Batch operations
    fun testBatchOperations() {
        // tag::batch[]
        try {
            database.inBatch({
                for (i in 0..9) {
                    val doc = MutableDocument()
                    doc.setValue("type", "user")
                    doc.setValue("name", "user $i")
                    doc.setBoolean("admin", false)
                    try {
                        database.save(doc)
                    } catch (e: CouchbaseLiteException) {
                        Log.e(TAG, e.toString())
                    }
                    Log.i(
                        TAG,
                        java.lang.String.format("saved user document %s", doc.getString("name"))
                    )
                }
            })
        } catch (e: CouchbaseLiteException) {
            Log.e(TAG, e.toString())
        }
        // end::batch[]
    }

    // ### Document Expiration
    @Throws(CouchbaseLiteException::class)
    fun DocumentExpiration() {
        // tag::document-expiration[]
        // Purge the document one day from now
        val ttl =
            Instant.now().plus(1, ChronoUnit.DAYS)
        database.setDocumentExpiration("doc123", Date(ttl.toEpochMilli()))

        // Reset expiration
        database.setDocumentExpiration("doc1", null)

        // Query documents that will be expired in less than five minutes
        val fiveMinutesFromNow =
            Instant.now().plus(5, ChronoUnit.MINUTES)
        val query: Query = QueryBuilder
            .select(SelectResult.expression(Meta.id))
            .from(DataSource.database(database))
            .where(Meta.expiration.lessThan(Expression.doubleValue(fiveMinutesFromNow.toEpochMilli())))
        // end::document-expiration[]
    }

    @Throws(CouchbaseLiteException::class)
    fun testDocumentChangeListener() {
        // tag::document-listener[]
        database.addDocumentChangeListener(
            "user.john",
            { change ->
                val doc: Document = database.getDocument(change.getDocumentID())
                if (doc != null) {
                    Toast.makeText(
                        context,
                        "Status: " + doc.getString("verified_account"),
                        Toast.LENGTH_SHORT
                    ).show()
                }
            })
        // end::document-listener[]
    }

    // ### Blobs
    fun testBlobs() {
        val newTask = MutableDocument()

        // tag::blob[]
        val `is`: InputStream = getAsset("avatar.jpg") ?: return
        try {
            val blob = Blob("image/jpeg", `is`)
            newTask.setBlob("avatar", blob)
            database.save(newTask)
            val taskBlob: Blob = newTask.getBlob("avatar")
            val bytes: ByteArray = taskBlob.getContent()
        } catch (e: CouchbaseLiteException) {
            Log.e(TAG, e.toString())
        } finally {
            try {
                `is`.close()
            } catch (ignore: IOException) {
            }
        }
        // end::blob[]
    }

    // ### Indexing
    @Throws(CouchbaseLiteException::class)
    fun testIndexing() {
        // For Documentation
        run {
            // tag::query-index[]
            database.createIndex(
                "TypeNameIndex",
                IndexBuilder.valueIndex(
                    ValueIndexItem.property("type"),
                    ValueIndexItem.property("name")
                )
            )
            // end::query-index[]
        }
    }

    // ### SELECT statement
    fun testSelectStatement() {
        run {

            // tag::query-select-meta[]
            val query: Query = QueryBuilder
                .select(
                    SelectResult.expression(Meta.id),
                    SelectResult.property("name"),
                    SelectResult.property("type")
                )
                .from(DataSource.database(database))
                .where(Expression.property("type").equalTo(Expression.string("hotel")))
                .orderBy(Ordering.expression(Meta.id))
            try {
                val rs: ResultSet = query.execute()
                for (result in rs) {
                    Log.i(
                        "Sample",
                        java.lang.String.format("hotel id -> %s", result.getString("id"))
                    )
                    Log.i(
                        "Sample",
                        java.lang.String.format("hotel name -> %s", result.getString("name"))
                    )
                }
            } catch (e: CouchbaseLiteException) {
                Log.e("Sample", e.getLocalizedMessage())
            }
        }
    }

    // META function
    @Throws(CouchbaseLiteException::class)
    fun testMetaFunction() {
        // For Documentation
        run {
            val query: Query = QueryBuilder
                .select(SelectResult.expression(Meta.id))
                .from(DataSource.database(database))
                .where(Expression.property("type").equalTo(Expression.string("airport")))
                .orderBy(Ordering.expression(Meta.id))
            val rs: ResultSet = query.execute()
            for (result in rs) {
                Log.w(
                    "Sample",
                    java.lang.String.format("airport id -> %s", result.getString("id"))
                )
                Log.w(
                    "Sample",
                    java.lang.String.format("airport id -> %s", result.getString(0))
                )
            }
        }
    }

    // ### all(*)
    @Throws(CouchbaseLiteException::class)
    fun testSelectAll() {
        // For Documentation
        run {

            // tag::query-select-all[]
            val query: Query = QueryBuilder
                .select(SelectResult.all())
                .from(DataSource.database(database))
                .where(Expression.property("type").equalTo(Expression.string("hotel")))
            // end::query-select-all[]

            // tag::live-query[]
            val query: Query = QueryBuilder
                .select(SelectResult.all())
                .from(DataSource.database(database))

            // Adds a query change listener.
            // Changes will be posted on the main queue.
            val token: ListenerToken = query.addChangeListener({ change ->
                for (result in change.getResults()) {
                    Log.d(TAG, "results: " + result.getKeys())
                    /* Update UI */
                }
            })

            // Start live query.
            query.execute() // <1>
            // end::live-query[]

            // tag::stop-live-query[]
            query.removeChangeListener(token)
            // end::stop-live-query[]
            val rs: ResultSet = query.execute()
            for (result in rs) {
                Log.i(
                    "Sample",
                    java.lang.String.format(
                        "hotel -> %s",
                        result.getDictionary(DATABASE_NAME).toMap()
                    )
                )
            }
        }
    }

    // ###　WHERE statement
    @Throws(CouchbaseLiteException::class)
    fun testWhereStatement() {
        // For Documentation
        run {

            // tag::query-where[]
            val query: Query = QueryBuilder
                .select(SelectResult.all())
                .from(DataSource.database(database))
                .where(Expression.property("type").equalTo(Expression.string("hotel")))
                .limit(Expression.intValue(10))
            val rs: ResultSet = query.execute()
            for (result in rs) {
                val all: Dictionary = result.getDictionary(DATABASE_NAME)
                Log.i(
                    "Sample",
                    java.lang.String.format("name -> %s", all.getString("name"))
                )
                Log.i(
                    "Sample",
                    java.lang.String.format("type -> %s", all.getString("type"))
                )
            }
            // end::query-where[]
        }
    }

    fun testQueryDeletedDocuments() {
        // tag::query-deleted-documents[]
        // Query documents that have been deleted
        val query: Where = QueryBuilder
            .select(SelectResult.expression(Meta.id))
            .from(DataSource.database(database))
            .where(Meta.deleted)
        // end::query-deleted-documents[]
    }

    // ####　Collection Operators
    @Throws(CouchbaseLiteException::class)
    fun testCollectionStatement() {
        // For Documentation
        run {

            // tag::query-collection-operator-contains[]
            val query: Query = QueryBuilder
                .select(
                    SelectResult.expression(Meta.id),
                    SelectResult.property("name"),
                    SelectResult.property("public_likes")
                )
                .from(DataSource.database(database))
                .where(
                    Expression.property("type").equalTo(Expression.string("hotel"))
                        .and(
                            ArrayFunction
                                .contains(
                                    Expression.property("public_likes"),
                                    Expression.string("Armani Langworth")
                                )
                        )
                )
            val rs: ResultSet = query.execute()
            for (result in rs) {
                Log.i(
                    "Sample",
                    java.lang.String.format(
                        "public_likes -> %s",
                        result.getArray("public_likes").toList()
                    )
                )
            }
            // end::query-collection-operator-contains[]
        }
    }

    // IN operator
    @Throws(CouchbaseLiteException::class)
    fun testInOperator() {
        // For Documentation
        run {

            // tag::query-collection-operator-in[]
            val values: Array<Expression> = arrayOf<Expression>(
                Expression.property("first"),
                Expression.property("last"),
                Expression.property("username")
            )
            val query: Query = QueryBuilder.select(SelectResult.all())
                .from(DataSource.database(database))
                .where(Expression.string("Armani").`in`(values))
            // end::query-collection-operator-in[]
            val rs: ResultSet = query.execute()
            for (result in rs) {
                Log.w(
                    "Sample",
                    java.lang.String.format("%s", result.toMap().toString())
                )
            }
            // end::query-collection-operator-in[]
        }
    }

    // Pattern Matching
    @Throws(CouchbaseLiteException::class)
    fun testPatternMatching() {
        // For Documentation
        run {

            // tag::query-like-operator[]
            val query: Query = QueryBuilder
                .select(
                    SelectResult.expression(Meta.id),
                    SelectResult.property("country"),
                    SelectResult.property("name")
                )
                .from(DataSource.database(database))
                .where(
                    Expression.property("type").equalTo(Expression.string("landmark"))
                        .and(
                            Function.lower(Expression.property("name"))
                                .like(Function.Expression.string("royal engineers museum"))
                        )
                )
            val rs: ResultSet = query.execute()
            for (result in rs) {
                Log.i(
                    "Sample",
                    java.lang.String.format("name -> %s", result.getString("name"))
                )
            }
            // end::query-like-operator[]
        }
    }

    // ### Wildcard Match
    @Throws(CouchbaseLiteException::class)
    fun testWildcardMatch() {
        // For Documentation
        run {

            // tag::query-like-operator-wildcard-match[]
            val query: Query = QueryBuilder
                .select(
                    SelectResult.expression(Meta.id),
                    SelectResult.property("country"),
                    SelectResult.property("name")
                )
                .from(DataSource.database(database))
                .where(
                    Expression.property("type").equalTo(Expression.string("landmark"))
                        .and(
                            Function.lower(Expression.property("name"))
                                .like(Expression.string("eng%e%"))
                        )
                )
            val rs: ResultSet = query.execute()
            for (result in rs) {
                Log.i(
                    "Sample",
                    java.lang.String.format("name -> %s", result.getString("name"))
                )
            }
            // end::query-like-operator-wildcard-match[]
        }
    }

    // Wildcard Character Match
    @Throws(CouchbaseLiteException::class)
    fun testWildCharacterMatch() {
        // For Documentation
        run {

            // tag::query-like-operator-wildcard-character-match[]
            val query: Query = QueryBuilder
                .select(
                    SelectResult.expression(Meta.id),
                    SelectResult.property("country"),
                    SelectResult.property("name")
                )
                .from(DataSource.database(database))
                .where(
                    Expression.property("type").equalTo(Expression.string("landmark"))
                        .and(
                            Function.lower(Expression.property("name"))
                                .like(Expression.string("eng____r"))
                        )
                )
            val rs: ResultSet = query.execute()
            for (result in rs) {
                Log.i(
                    "Sample",
                    java.lang.String.format("name -> %s", result.getString("name"))
                )
            // end::query-like-operator-wildcard-character-match[]
            }
        }
    }

    // ### Regex Match
    @Throws(CouchbaseLiteException::class)
    fun testRegexMatch() {
        // For Documentation
        run {

            // tag::query-regex-operator[]
            val query: Query = QueryBuilder
                .select(
                    SelectResult.expression(Meta.id),
                    SelectResult.property("country"),
                    SelectResult.property("name")
                )
                .from(DataSource.database(database))
                .where(
                    Expression.property("type").equalTo(Expression.string("landmark"))
                        .and(
                            Function.lower(Expression.property("name"))
                                .regex(Expression.string("\\beng.*r\\b"))
                        )
                )
            val rs: ResultSet = query.execute()
            for (result in rs) {
                Log.i(
                    "Sample",
                    java.lang.String.format("name -> %s", result.getString("name"))
                )
            }
            // end::query-regex-operator[]
        }
    }

    // JOIN statement
    @Throws(CouchbaseLiteException::class)
    fun testJoinStatement() {
        // For Documentation
        run {

            // tag::query-join[]
            val query: Query = QueryBuilder.select(
                SelectResult.expression(Expression.property("name").from("airline")),
                SelectResult.expression(Expression.property("callsign").from("airline")),
                SelectResult.expression(Expression.property("destinationairport").from("route")),
                SelectResult.expression(Expression.property("stops").from("route")),
                SelectResult.expression(Expression.property("airline").from("route"))
            )
                .from(DataSource.database(database).`as`("airline"))
                .join(
                    Join.join(DataSource.database(database).`as`("route"))
                        .on(
                            Meta.id.from("airline")
                                .equalTo(Expression.property("airlineid").from("route"))
                        )
                )
                .where(
                    Expression.property("type").from("route").equalTo(Expression.string("route"))
                        .and(
                            Expression.property("type").from("airline")
                                .equalTo(Expression.string("airline"))
                        )
                        .and(
                            Expression.property("sourceairport").from("route")
                                .equalTo(Expression.string("RIX"))
                        )
                )
            val rs: ResultSet = query.execute()
            for (result in rs) {
                Log.w(
                    "Sample",
                    java.lang.String.format("%s", result.toMap().toString())
                )
            }
            // end::query-join[]
        }
    }

    // ### GROUPBY statement
    @Throws(CouchbaseLiteException::class)
    fun testGroupByStatement() {
        // For Documentation
        run {

            // tag::query-groupby[]
            val query: Query = QueryBuilder.select(
                SelectResult.expression(Function.count(Expression.string("*"))),
                SelectResult.property("country"),
                SelectResult.property("tz")
            )
                .from(DataSource.database(database))
                .where(
                    Expression.property("type").equalTo(Expression.string("airport"))
                        .and(
                            Expression.property("geo.alt")
                                .greaterThanOrEqualTo(Expression.intValue(300))
                        )
                )
                .groupBy(
                    Expression.property("country"),
                    Expression.property("tz")
                )
                .orderBy(Ordering.expression(Function.count(Expression.string("*"))).descending())
            val rs: ResultSet = query.execute()
            for (result in rs) {
                Log.i(
                    "Sample",
                    java.lang.String.format(
                        "There are %d airports on the %s timezone located in %s and above 300ft",
                        result.getInt("$1"),
                        result.getString("tz"),
                        result.getString("country")
                    )
                )
            }
            // end::query-groupby[]
        }
    }

    // ### ORDER BY statement
    @Throws(CouchbaseLiteException::class)
    fun testOrderByStatement() {
        // For Documentation
        run {

            // tag::query-orderby[]
            val query: Query = QueryBuilder
                .select(
                    SelectResult.expression(Meta.id),
                    SelectResult.property("name")
                )
                .from(DataSource.database(database))
                .where(Expression.property("type").equalTo(Expression.string("hotel")))
                .orderBy(Ordering.property("name").ascending())
                .limit(Expression.intValue(10))
            val rs: ResultSet = query.execute()
            for (result in rs) {
                Log.i("Sample", java.lang.String.format("%s", result.toMap()))
            }
            // end::query-orderby[]
        }
    }

    // ### EXPLAIN statement
    @Throws(CouchbaseLiteException::class)
    fun testExplainStatement() {
        // For Documentation
        run {

            // tag::query-explain-all[]
            val query: Query = QueryBuilder
                .select(SelectResult.all())
                .from(DataSource.database(database))
                .where(Expression.property("type").equalTo(Expression.string("university")))
                .groupBy(Expression.property("country"))
                .orderBy(Ordering.property("name").descending()) // <.>
            Log.i(query.explain()) // <.>
            // end::query-explain-all[]
            // tag::query-explain-like[]
            val query: Query = QueryBuilder
                .select(SelectResult.all())
                .from(DataSource.database(database))
                .where(Expression.property("type").like(Expression.string("%hotel%"))) // <.>
            Log.i(query.explain())
            // end::query-explain-like[]
            // tag::query-explain-nopfx[]
            val query: Query = QueryBuilder
                .select(SelectResult.all())
                .from(DataSource.database(database))
                .where(
                    Expression.property("type").like(Expression.string("hotel%")) // <.>
                        .and(Expression.property("name").like(Expression.string("%royal%")))
                )
            Log.i(query.explain())
            // end::query-explain-nopfx[]
            // tag::query-explain-function[]
            val query: Query = QueryBuilder
                .select(SelectResult.all())
                .from(DataSource.database(database))
                .where(
                    Function.lower(
                        Expression.property("type").equalTo(Expression.string("hotel"))
                    )
                ) // <.>
            Log.i(query.explain())
            // end::query-explain-function[]
            // tag::query-explain-nofunction[]
            val query: Query = QueryBuilder
                .select(SelectResult.all())
                .from(DataSource.database(database))
                .where(Expression.property("type").equalTo(Expression.string("hotel"))) // <.>
            Log.i(query.explain())
            // end::query-explain-nofunction[]
        }
    } // end query-explain
    // end::query-explain[]
    @Throws(CouchbaseLiteException::class)
    fun prepareIndex() {
        // tag::fts-index[]
        database.createIndex(
            "nameFTSIndex",
            IndexBuilder.fullTextIndex(FullTextIndexItem.property("name")).ignoreAccents(false)
        )
        // end::fts-index[]
    }

    @Throws(CouchbaseLiteException::class)
    fun testFTS() {
        // tag::fts-query[]
        val whereClause: Expression = FullTextExpression.index("nameFTSIndex").match("buy")
        val ftsQuery: Query = QueryBuilder.select(SelectResult.expression(Meta.id))
            .from(DataSource.database(database))
            .where(whereClause)
        val ftsQueryResult: ResultSet = ftsQuery.execute()
        for (result in ftsQueryResult) {
            Log.i(
                TAG,
                java.lang.String.format("document properties %s", result.getString(0))
            )
        }
        // end::fts-query[]
    }

    /* The `tag::replication[]` example is inlined in java.adoc */
    fun testTroubleshooting() {
        // tag::replication-logging[]
        Database.setLogLevel(LogDomain.REPLICATOR, LogLevel.VERBOSE)
        // end::replication-logging[]
    }

    @Throws(URISyntaxException::class)
    fun testReplicationBasicAuthentication() {
        // tag::basic-authentication[]
        val target = URLEndpoint(URI("ws://localhost:4984/mydatabase"))
        val config = ReplicatorConfiguration(database, target)
        config.setAuthenticator(BasicAuthenticator("username", "password"))

        // Create replicator (be sure to hold a reference somewhere that will prevent the Replicator from being GCed)
        replicator = Replicator(config)
        replicator.start()
        // end::basic-authentication[]
    }

    @Throws(URISyntaxException::class)
    fun testReplicationSessionAuthentication() {
        // tag::session-authentication[]
        val target = URLEndpoint(URI("ws://localhost:4984/mydatabase"))
        val config = ReplicatorConfiguration(database, target)
        config.setAuthenticator(SessionAuthenticator("904ac010862f37c8dd99015a33ab5a3565fd8447"))

        // Create replicator (be sure to hold a reference somewhere that will prevent the Replicator from being GCed)
        replicator = Replicator(config)
        replicator.start()
        // end::session-authentication[]
    }

    @Throws(URISyntaxException::class)
    fun testReplicationStatus() {
        val uri = URI("ws://localhost:4984/db")
        val endpoint: Endpoint = URLEndpoint(uri)
        val config = ReplicatorConfiguration(database, endpoint)
        config.setReplicatorType(ReplicatorConfiguration.ReplicatorType.PULL)
        // Create replicator (be sure to hold a reference somewhere that will prevent the Replicator from being GCed)
        replicator = Replicator(config)

        // tag::replication-status[]
        replicator.addChangeListener({ change ->
            if (change.getStatus().getActivityLevel() === Replicator.ActivityLevel.STOPPED) {
                Log.i(TAG, "Replication stopped")
            }
        })
        // end::replication-status[]
    }

    internal inner class PendingDocsExample {
        private val database: Database? = null
        private var replicator: Replicator? = null

        //  BEGIN PendingDocuments IB -- 11/Feb/21 --
        @Throws(URISyntaxException::class, CouchbaseLiteException::class)
        fun testReplicationPendingDocs() {
            // nottag::replication-pendingdocuments[]
            // ... include other code as required
            //
            val endpoint: Endpoint = URLEndpoint(URI("ws://localhost:4984/db"))
            val config: ReplicatorConfiguration = ReplicatorConfiguration(database, endpoint)
                .setReplicatorType(ReplicatorConfiguration.ReplicatorType.PUSH)
            // tag::replication-push-pendingdocumentids[]
            replicator = Replicator(config)
            val pendingDocs: Set<String> = replicator.getPendingDocumentIds() // <.>

            // end::replication-push-pendingdocumentids[]
            replicator.addChangeListener({ change ->
                onStatusChanged(
                    pendingDocs,
                    change.getStatus()
                )
            })
            replicator.start()

            // ... include other code as required
            // notend::replication-pendingdocuments[]
        }

        //
        // tag::replication-pendingdocuments[]
        //
        private fun onStatusChanged(
            @NonNull pendingDocs: Set<String>,
            @NonNull status: Replicator.Status
        ) {
            // ... sample onStatusChanged function
            //
            Log.i(
                Companion.TAG,
                "Replicator activity level is " + status.getActivityLevel().toString()
            )

            // iterate and report-on previously
            // retrieved pending docids 'list'
            val itr = pendingDocs.iterator()
            while (itr.hasNext()) {
                val docId = itr.next()
                try {
                    // tag::replication-push-isdocumentpending[]
                    if (!replicator.isDocumentPending(docId)) {
                        continue
                    } // <.>
                    // end::replication-push-isdocumentpending[]
                    itr.remove()
                    Log.i(
                        Companion.TAG,
                        "Doc ID $docId has been pushed"
                    )
                } catch (e: CouchbaseLiteException) {
                    Log.w(
                        Companion.TAG,
                        "isDocumentPending failed",
                        e
                    )
                }
            }
        } // end::replication-pendingdocuments[]

        //  END PendingDocuments BM -- 19/Feb/21 --
        companion object {
            private const val TAG = "SCRATCH"
        }
    }

    @Throws(URISyntaxException::class)
    fun testHandlingNetworkErrors() {
        val endpoint: Endpoint = URLEndpoint(URI("ws://localhost:4984/db"))
        val config = ReplicatorConfiguration(database, endpoint)
        config.setReplicatorType(ReplicatorConfiguration.ReplicatorType.PULL)
        // Create replicator (be sure to hold a reference somewhere that will prevent the Replicator from being GCed)
        replicator = Replicator(config)

        // tag::replication-error-handling[]
        replicator.addChangeListener({ change ->
            val error: CouchbaseLiteException = change.getStatus().getError()
            if (error != null) {
                Log.w(TAG, "Error code:: %d", error)
            }
        })
        replicator.start()
        // end::replication-error-handling[]
        replicator.stop()
    }

    @Throws(URISyntaxException::class)
    fun testReplicatorDocumentEvent() {
        val endpoint: Endpoint = URLEndpoint(URI("ws://localhost:4984/db"))
        val config = ReplicatorConfiguration(database, endpoint)
        config.setReplicatorType(ReplicatorConfiguration.ReplicatorType.PULL)
        // Create replicator (be sure to hold a reference somewhere that will prevent the Replicator from being GCed)
        replicator = Replicator(config)

        // tag::add-document-replication-listener[]
        val token: ListenerToken = replicator.addDocumentReplicationListener({ replication ->
            if (replication.isPush()) Log.i(
                TAG,
                "Replication type: " + "Push"
            ) else Log.i(TAG, "Replication type: " + "Pull")
            for (document in replication.getDocuments()) {
                Log.i(TAG, "Doc ID: " + document.getID())
                val err: CouchbaseLiteException = document.getError()
                if (err != null) {
                    // There was an error
                    Log.e(TAG, "Error replicating document: ", err)
                    return@addDocumentReplicationListener
                }
                if (document.flags().contains(DocumentFlag.DocumentFlagsDeleted)) {
                    Log.i(
                        TAG,
                        "Successfully replicated a deleted document"
                    )
                }
            }
        })
        replicator.start()
        // end::add-document-replication-listener[]

        // tag::remove-document-replication-listener[]
        replicator.removeChangeListener(token)
        // end::remove-document-replication-listener[]
    }

    @Throws(URISyntaxException::class)
    fun testReplicationCustomHeader() {
        val uri = URI("ws://localhost:4984/db")
        val endpoint: Endpoint = URLEndpoint(uri)

        // tag::replication-custom-header[]
        val config = ReplicatorConfiguration(database, endpoint)
        val headers: MutableMap<String, String> =
            HashMap()
        headers["CustomHeaderName"] = "Value"
        config.setHeaders(headers)
        // end::replication-custom-header[]
    }

    // ### Certificate Pinning
    @Throws(URISyntaxException::class, IOException::class)
    fun testCertificatePinning() {
        val uri = URI("ws://localhost:4984/db")
        val endpoint: Endpoint = URLEndpoint(uri)
        val config = ReplicatorConfiguration(database, endpoint)

        // tag::certificate-pinning[]
        val `is`: InputStream = getAsset("cert.cer")
        val cert: ByteArray = IOUtils.toByteArray(`is`)
        if (`is` != null) {
            try {
                `is`.close()
            } catch (ignore: IOException) {
            }
        }
        config.setPinnedServerCertificate(cert)
        // end::certificate-pinning[]
    }

    // ### Reset replicator checkpoint
    @Throws(URISyntaxException::class)
    fun testReplicationResetCheckpoint() {
        val uri = URI("ws://localhost:4984/db")
        val endpoint: Endpoint = URLEndpoint(uri)
        val config = ReplicatorConfiguration(database, endpoint)
        config.setReplicatorType(ReplicatorConfiguration.ReplicatorType.PULL)
        // Create replicator (be sure to hold a reference somewhere that will prevent the Replicator from being GCed)
        replicator = Replicator(config)
        replicator.start()

        // tag::replication-reset-checkpoint[]
        replicator.resetCheckpoint()
        replicator.start()
        // end::replication-reset-checkpoint[]
        replicator.stop()
    }

    @Throws(URISyntaxException::class)
    fun testReplicationPushFilter() {
        // tag::replication-push-filter[]
        val target = URLEndpoint(URI("ws://localhost:4984/mydatabase"))
        val config = ReplicatorConfiguration(database, target)
        config.setPushFilter({ document, flags -> flags.contains(DocumentFlag.DocumentFlagsDeleted) }) // <1>

        // Create replicator (be sure to hold a reference somewhere that will prevent the Replicator from being GCed)
        replicator = Replicator(config)
        replicator.start()
        // end::replication-push-filter[]
    }

    @Throws(URISyntaxException::class)
    fun testReplicationPullFilter() {
        // tag::replication-pull-filter[]
        val target = URLEndpoint(URI("ws://localhost:4984/mydatabase"))
        val config = ReplicatorConfiguration(database, target)
        config.setPullFilter({ document, flags -> "draft" == document.getString("type") }) // <1>

        // Create replicator (be sure to hold a reference somewhere that will prevent the Replicator from being GCed)
        replicator = Replicator(config)
        replicator.start()
        // end::replication-pull-filter[]
    }

    @Throws(URISyntaxException::class)
    fun testCustomRetryConfig() {
        // tag::replication-retry-config[]
        val target = URLEndpoint(URI("ws://localhost:4984/mydatabase"))
        val config = ReplicatorConfiguration(database, target)

        //  other config as required . . .
        // tag::replication-heartbeat-config[]
        config.setHeartbeat(150L) // <.>
        // end::replication-heartbeat-config[]
        // tag::replication-maxretries-config[]
        config.setMaxRetries(20L) // <.>
        // end::replication-maxretries-config[]
        // tag::replication-maxretrywaittime-config[]
        config.setMaxRetryWaitTime(600L) // <.>
        // end::replication-maxretrywaittime-config[]
        val repl = Replicator(config)

        // end::replication-retry-config[]
    }

    @Throws(CouchbaseLiteException::class)
    fun testDatabaseReplica() {
        var config: DatabaseConfiguration? = DatabaseConfiguration()
        val database1 = Database("mydb", config)
        config = DatabaseConfiguration()
        val database2 = Database("db2", config)

        /* EE feature: code below might throw a compilation error
           if it's compiled against CBL Android Community. */
        // tag::database-replica[]
        val targetDatabase = DatabaseEndpoint(database2)
        val replicatorConfig =
            ReplicatorConfiguration(database1, targetDatabase)
        replicatorConfig.setReplicatorType(ReplicatorConfiguration.ReplicatorType.PUSH)

        // Create replicator (be sure to hold a reference somewhere that will prevent the Replicator from being GCed)
        replicator = Replicator(replicatorConfig)
        replicator.start()
        // end::database-replica[]
    }

    @Throws(CouchbaseLiteException::class)
    fun testPredictiveModel() {
        val config = DatabaseConfiguration()
        val database = Database("mydb", config)

        // tag::register-model[]
        Database.prediction.registerModel("ImageClassifier", ImageClassifierModel())
        // end::register-model[]

        // tag::predictive-query-value-index[]
        val index: ValueIndex =
            IndexBuilder.valueIndex(ValueIndexItem.expression(Expression.property("label")))
        database.createIndex("value-index-image-classifier", index)
        // end::predictive-query-value-index[]

        // tag::unregister-model[]
        Database.prediction.unregisterModel("ImageClassifier")
        // end::unregister-model[]
    }

    @Throws(CouchbaseLiteException::class)
    fun testPredictiveIndex() {
        val config = DatabaseConfiguration()
        val database = Database("mydb", config)

        // tag::predictive-query-predictive-index[]
        val inputMap: MutableMap<String, Any> =
            HashMap()
        inputMap["numbers"] = Expression.property("photo")
        val input: Expression = Expression.map(inputMap)
        val index: PredictiveIndex = IndexBuilder.predictiveIndex("ImageClassifier", input, null)
        database.createIndex("predictive-index-image-classifier", index)
        // end::predictive-query-predictive-index[]
    }

    @Throws(CouchbaseLiteException::class)
    fun testPredictiveQuery() {
        val config = DatabaseConfiguration()
        val database = Database("mydb", config)

        // tag::predictive-query[]
        val inputProperties: MutableMap<String, Any> =
            HashMap()
        inputProperties["photo"] = Expression.property("photo")
        val input: Expression = Expression.map(inputProperties)
        val prediction: PredictionFunction =
            PredictiveModel.predict("ImageClassifier", input) // <1>
        val query: Query = QueryBuilder
            .select(SelectResult.all())
            .from(DataSource.database(database))
            .where(
                Expression.property("label").equalTo(Expression.string("car"))
                    .and(
                        Expression.property("probability")
                            .greaterThanOrEqualTo(Expression.doubleValue(0.8))
                    )
            )

        // Run the query.
        val result: ResultSet = query.execute()
        Log.d(TAG, "Number of rows: " + result.allResults().size())
        // end::predictive-query[]
    }

    @Throws(URISyntaxException::class)
    fun testReplicationWithCustomConflictResolver() {
        // tag::replication-conflict-resolver[]
        val target = URLEndpoint(URI("ws://localhost:4984/mydatabase"))
        val config = ReplicatorConfiguration(database, target)
        config.setConflictResolver(LocalWinConflictResolver())
        val replication = Replicator(config)
        replication.start()
        // end::replication-conflict-resolver[]
    }

    @Throws(CouchbaseLiteException::class)
    fun testSaveWithCustomConflictResolver() {
        // tag::update-document-with-conflict-handler[]
        val doc: Document = database.getDocument("xyz") ?: return
        val mutableDocument: MutableDocument = doc.toMutable()
        mutableDocument.setString("name", "apples")
        database.save(
            mutableDocument,
            { newDoc, curDoc ->  // <.>
                if (curDoc == null) {
                    return@save false
                } // <.>
                val dataMap: MutableMap<String, Any> =
                    curDoc.toMap()
                dataMap.putAll(newDoc.toMap()) // <.>
                newDoc.setData(dataMap)
                true // <.>
            }) // <.>
        // end::update-document-with-conflict-handler[]
    }

    companion object {
        private const val TAG = "EXAMPLE"
        private const val DATABASE_NAME = "database"
    }

}

// tag::update-document-with-conflict-handler-callouts[]

<.> The conflict handler code is provided as a lambda.

<.> If the handler cannot resolve a conflict, it can return false.
In this case, the save method will cancel the save operation and return false the same way as using the save() method with the failOnConflict concurrency control.

<.> Within the conflict handler, you can modify the document parameter which is the same instance of Document that is passed to the save() method. So in effect, you will be directly modifying the document that is being saved.

<.> When handling is done, the method must return true (for  successful resolution) or false (if it was unable to resolve the conflict).

<.> If there is an exception thrown in the handle() method, the exception will be caught and re-thrown in the save() method
// end::update-document-with-conflict-handler-callouts[]


// tag::local-win-conflict-resolver[]
// Using replConfig.setConflictResolver(new LocalWinConflictResolver());
internal class LocalWinConflictResolver : ConflictResolver {
    fun resolve(conflict: Conflict): Document {
        return conflict.getLocalDocument()
    }
} // end::local-win-conflict-resolver[]

// tag::remote-win-conflict-resolver[]
// Using replConfig.setConflictResolver(new RemoteWinConflictResolver());
internal class RemoteWinConflictResolver : ConflictResolver {
    fun resolve(conflict: Conflict): Document {
        return conflict.getRemoteDocument()
    }
} // end::remote-win-conflict-resolver[]

// tag::merge-conflict-resolver[]
// Using replConfig.setConflictResolver(new MergeConflictResolver());
internal class MergeConflictResolver : ConflictResolver {
    fun resolve(conflict: Conflict): Document {
        val merge: MutableMap<String, Any> =
            conflict.getLocalDocument().toMap()
        merge.putAll(conflict.getRemoteDocument().toMap())
        return MutableDocument(conflict.getDocumentId(), merge)
    }
} // end::merge-conflict-resolver[]

/* ----------------------------------------------------------- */ /* ---------------------  ACTIVE SIDE  ----------------------- */ /* ----------------------------------------------------------- */
internal class BrowserSessionManager private constructor(private val context: Context) :
    MessageEndpointDelegate {
    private var replicator: Replicator? = null

    @Throws(CouchbaseLiteException::class)
    fun initCouchbase() {
        // tag::message-endpoint[]
        val databaseConfiguration = DatabaseConfiguration(context)
        val database = Database("mydb", databaseConfiguration)

        // The delegate must implement the `MessageEndpointDelegate` protocol.
        val messageEndpointTarget = MessageEndpoint(
            "UID:123",
            "active",
            ProtocolType.MESSAGE_STREAM,
            this
        )
        // end::message-endpoint[]

        // tag::message-endpoint-replicator[]
        val config =
            ReplicatorConfiguration(database, messageEndpointTarget)

        // Create the replicator object.
        replicator = Replicator(config)
        // Start the replication.
        replicator.start()
        // end::message-endpoint-replicator[]
    }

    // tag::create-connection[]
    /* implementation of MessageEndpointDelegate */
    @NonNull
    fun createConnection(@NonNull endpoint: MessageEndpoint?): MessageEndpointConnection {
        return ActivePeerConnection() /* implements MessageEndpointConnection */
    } // end::create-connection[]

}

internal class ActivePeerConnection : MessageEndpointConnection {
    private var replicatorConnection: ReplicatorConnection? = null
    fun disconnect() {
        // tag::active-replicator-close[]
        replicatorConnection.close(null)
        // end::active-replicator-close[]
    }

    // tag::active-peer-open[]
    /* implementation of MessageEndpointConnection */
    fun open(
        @NonNull connection: ReplicatorConnection?,
        @NonNull completion: MessagingCompletion
    ) {
        replicatorConnection = connection
        completion.complete(true, null)
    }

    // end::active-peer-open[]
    // tag::active-peer-close[]
    fun close(
        error: Exception?,
        @NonNull completion: MessagingCloseCompletion
    ) {
        /* disconnect with communications framework */
        /* ... */
        /* call completion handler */
        completion.complete()
    }

    // end::active-peer-close[]
    // tag::active-peer-send[]
    /* implementation of MessageEndpointConnection */
    fun send(@NonNull message: Message?, @NonNull completion: MessagingCompletion) {
        /* send the data to the other peer */
        /* ... */
        /* call the completion handler once the message is sent */
        completion.complete(true, null)
    }

    // end::active-peer-send[]
    fun receive(message: Message?) {
        // tag::active-peer-receive[]
        replicatorConnection.receive(message)
        // end::active-peer-receive[]
    }
} /* ----------------------------------------------------------- */ /* ---------------------  PASSIVE SIDE  ---------------------- */ /* ----------------------------------------------------------- */

internal class PassivePeerConnection private constructor(private val context: Context) :
    MessageEndpointConnection {
    private var messageEndpointListener: MessageEndpointListener? = null
    private var replicatorConnection: ReplicatorConnection? = null

    @Throws(CouchbaseLiteException::class)
    fun startListener() {
        // tag::listener[]
        val databaseConfiguration = DatabaseConfiguration()
        val database = Database("mydb", databaseConfiguration)
        val listenerConfiguration =
            MessageEndpointListenerConfiguration(
                database,
                ProtocolType.MESSAGE_STREAM
            )
        messageEndpointListener = MessageEndpointListener(listenerConfiguration)
        // end::listener[]
    }

    fun stopListener() {
        // tag::passive-stop-listener[]
        messageEndpointListener.closeAll()
        // end::passive-stop-listener[]
    }

    fun accept() {
        // tag::advertizer-accept[]
        val connection = PassivePeerConnection(context) /* implements
        MessageEndpointConnection */
        messageEndpointListener.accept(connection)
        // end::advertizer-accept[]
    }

    fun disconnect() {
        // tag::passive-replicator-close[]
        replicatorConnection.close(null)
        // end::passive-replicator-close[]
    }

    // tag::passive-peer-open[]
    /* implementation of MessageEndpointConnection */
    fun open(
        @NonNull connection: ReplicatorConnection?,
        @NonNull completion: MessagingCompletion
    ) {
        replicatorConnection = connection
        completion.complete(true, null)
    }

    // end::passive-peer-open[]
    // tag::passive-peer-close[]
    /* implementation of MessageEndpointConnection */
    fun close(
        error: Exception?,
        @NonNull completion: MessagingCloseCompletion
    ) {
        /* disconnect with communications framework */
        /* ... */
        /* call completion handler */
        completion.complete()
    }

    // end::passive-peer-close[]
    // tag::passive-peer-send[]
    /* implementation of MessageEndpointConnection */
    fun send(@NonNull message: Message?, @NonNull completion: MessagingCompletion) {
        /* send the data to the other peer */
        /* ... */
        /* call the completion handler once the message is sent */
        completion.complete(true, null)
    }

    // end::passive-peer-send[]
    fun receive(message: Message?) {
        // tag::passive-peer-receive[]
        replicatorConnection.receive(message)
        // end::passive-peer-receive[]
    }

} // tag::predictive-model[]

// `tensorFlowModel` is a fake implementation
// this would be the implementation of the ml model you have chosen
internal class ImageClassifierModel : PredictiveModel {
    fun predict(@NonNull input: Dictionary): Dictionary? {
        val blob: Blob = input.getBlob("photo") ?: return null

        // `tensorFlowModel` is a fake implementation
        // this would be the implementation of the ml model you have chosen
        return MutableDictionary(TensorFlowModel.predictImage(blob.getContent())) // <1>
    }
}

internal object TensorFlowModel {
    fun predictImage(data: ByteArray?): Map<String, Any>? {
        return null
    }
} // end::predictive-model[]

// tag::custom-logging[]
internal class LogTestLogger(@NonNull level: LogLevel) : Logger {
    @NonNull
    private val level: LogLevel

    @NonNull
    fun getLevel(): LogLevel {
        return level
    }

    fun log(
        @NonNull level: LogLevel?,
        @NonNull domain: LogDomain?,
        @NonNull message: String?
    ) {
        // this method will never be called if param level < this.level
        // handle the message, for example piping it to a third party framework
    }

    init {
        this.level = level
    }
}

class CertAuthListener {
    companion object {
        private const val TAG = "PWD"
        private var CERT_ATTRIBUTES: Map<String, String>? = null

        init {
            val m: Map<String, String> =
                HashMap()
            com.couchbase.code_snippets.m.put(TLSIdentity.CERT_ATTRIBUTE_COMMON_NAME, "CBL Test")
            com.couchbase.code_snippets.m.put(TLSIdentity.CERT_ATTRIBUTE_ORGANIZATION, "Couchbase")
            com.couchbase.code_snippets.m.put(
                TLSIdentity.CERT_ATTRIBUTE_ORGANIZATION_UNIT,
                "Mobile"
            )
            com.couchbase.code_snippets.m.put(
                TLSIdentity.CERT_ATTRIBUTE_EMAIL_ADDRESS,
                "lite@couchbase.com"
            )
            CERT_ATTRIBUTES =
                Collections.unmodifiableMap(com.couchbase.code_snippets.m)
        }
    }

    // start a server and connect to it with a replicator
    @Throws(CouchbaseLiteException::class, IOException::class)
    fun run() {
        val localDb = Database("localDb")
        var doc = MutableDocument()
        doc.setString("dog", "woof")
        localDb.save(doc)
        val remoteDb = Database("remoteDb")
        doc = MutableDocument()
        doc.setString("cat", "meow")
        localDb.save(doc)
        val serverIdentity: TLSIdentity = TLSIdentity.createIdentity(
            true,
            CERT_ATTRIBUTES,
            null,
            "server"
        )
        val clientIdentity: TLSIdentity = TLSIdentity.createIdentity(
            false,
            CERT_ATTRIBUTES,
            null,
            "client"
        )
        val uri = startServer(remoteDb, serverIdentity, clientIdentity.getCerts())
            ?: throw IOException("Failed to start the server")
        Thread(Runnable {
            try {
                startClient(uri, serverIdentity.getCerts().get(0), clientIdentity, localDb)
                Log.e(TAG, "Success!!")
                deleteIdentity("server")
                Log.e(TAG, "Alias deleted: server")
                deleteIdentity("client")
                Log.e(TAG, "Alias deleted: client")
            } catch (e: Exception) {
                Log.e(TAG, "Failed!!", e)
            }
        }).start()
    }

    // start a client replicator
    @Throws(CertificateEncodingException::class, InterruptedException::class)
    fun startClient(
        @NonNull uri: URI?,
        @NonNull cert: Certificate,
        @NonNull clientIdentity: TLSIdentity,
        @NonNull db: Database?
    ) {
        val config = ReplicatorConfiguration(db, URLEndpoint(uri))
        config.setReplicatorType(ReplicatorConfiguration.ReplicatorType.PUSH_AND_PULL)
        config.setContinuous(false)
        configureClientCerts(config, cert, clientIdentity)
        val completionLatch = CountDownLatch(1)
        val repl = Replicator(config)
        repl.addChangeListener({ change ->
            if (change.getStatus()
                    .getActivityLevel() === AbstractReplicator.ActivityLevel.STOPPED
            ) {
                completionLatch.countDown()
            }
        })
        repl.start(false)
        completionLatch.await()
    }
    // tag::listener-config-auth-cert-full[]
    /**
     * Snippet 2: create a ListenerCertificateAuthenticator and configure the listener with it
     *
     *
     * Start a listener for db that accepts connections from a client identified by any of the passed certs
     *
     * @param db    the database to which the listener is attached
     * @param certs the name of the single valid user
     * @return the url at which the listener can be reached.
     * @throws CouchbaseLiteException on failure
     */
    @Nullable
    @Throws(CouchbaseLiteException::class)
    fun startServer(
        @NonNull db: Database?,
        @NonNull serverId: TLSIdentity?,
        @NonNull certs: List<Certificate?>?
    ): URI? {
        val config = URLEndpointListenerConfiguration(db)
        config.setPort(0) // this is the default
        config.setDisableTls(false)
        config.setTlsIdentity(serverId)
        config.setAuthenticator(ListenerCertificateAuthenticator(certs))
        val listener = URLEndpointListener(config)
        listener.start()
        val urls: List<URI> = listener.getUrls()
        return if (urls.isEmpty()) {
            null
        } else urls[0]
    }
    // end::listener-config-auth-cert-full[]
    // tag::listener-config-delete-cert-full[]
    /**
     * Delete an identity from the keystore
     *
     * @param alias the alias for the identity to be deleted
     */
    @Throws(
        KeyStoreException::class,
        CertificateException::class,
        NoSuchAlgorithmException::class,
        IOException::class
    )
    fun deleteIdentity(alias: String?) {
        val keyStore: KeyStore = KeyStore.getInstance("AndroidKeyStore")
        keyStore.load(null)
        keyStore.deleteEntry(alias) // <.>
    }
    // end::listener-config-delete-cert-full[]
    // nottag::p2p-tlsid-tlsidentity-with-label[]
    /**
     * Snippet 4: Create a ClientCertificateAuthenticator and use it in a replicator
     * Snippet 5: Specify a pinned certificate as a byte array
     *
     *
     * Configure Client (active) side certificates
     *
     * @param config         The replicator configuration
     * @param cert           The expected server side certificate
     * @param clientIdentity the identity offered to the server as authentication
     * @throws CertificateEncodingException on certifcate encoding error
     */
    @Throws(CertificateEncodingException::class)
    private fun configureClientCerts(
        config: ReplicatorConfiguration,
        @NonNull cert: Certificate,
        @NonNull clientIdentity: TLSIdentity
    ) {

        // Snippet 4: create an authenticator that provides the client identity
        config.setAuthenticator(ClientCertificateAuthenticator(clientIdentity))

        // Configure the pinned certificate passing a byte array.
        config.setPinnedServerCertificate(cert.getEncoded())
    }
    // notend::p2p-tlsid-tlsidentity-with-label[]
    /**
     * Snippet 5 (supplement): Copy a cert from a resource bundle
     *
     *
     * Configure Client (active) side certificates
     *
     * @param context Android context
     * @param resId   resource id for resource: R.id.foo
     * @throws IOException on copy error
     */
    @Throws(IOException::class)
    private fun readCertMaterialFromBundle(
        @NonNull context: Context,
        resId: Int
    ): ByteArray {
        val out = ByteArrayOutputStream()
        val `in` = context.resources.openRawResource(resId)
        val buf = ByteArray(1024)
        var n: Int
        while (`in`.read(buf).also { n = it } >= 0) {
            out.write(buf, 0, n)
        }
        return out.toByteArray()
    }
}

class PasswordAuthListener {
    // start a server and connect to it with a replicator
    @Throws(CouchbaseLiteException::class, IOException::class)
    fun run() {
        val localDb = Database("localDb")
        var doc = MutableDocument()
        doc.setString("dog", "woof")
        localDb.save(doc)
        val remoteDb = Database("remoteDb")
        doc = MutableDocument()
        doc.setString("cat", "meow")
        localDb.save(doc)
        val uri = startServer(remoteDb, "fox", "wa-pa-pa-pa-pa-pow".toCharArray())
            ?: throw IOException("Failed to start the server")
        Thread(Runnable {
            try {
                runClient(uri, "fox", "wa-pa-pa-pa-pa-pow".toCharArray(), localDb)
                Log.e(TAG, "Success!!")
            } catch (e: Exception) {
                Log.e(TAG, "Failed!!", e)
            }
        }).start()
    }

    // start a client replicator
    @Throws(InterruptedException::class)
    fun runClient(
        @NonNull uri: URI?,
        @NonNull username: String?,
        @NonNull password: CharArray?,
        @NonNull db: Database?
    ) {
        val config = ReplicatorConfiguration(db, URLEndpoint(uri))
        config.setReplicatorType(ReplicatorConfiguration.ReplicatorType.PUSH_AND_PULL)
        config.setContinuous(false)
        config.setAuthenticator(BasicAuthenticator(username, password))
        val completionLatch = CountDownLatch(1)
        val repl = Replicator(config)
        repl.addChangeListener({ change ->
            if (change.getStatus()
                    .getActivityLevel() === AbstractReplicator.ActivityLevel.STOPPED
            ) {
                completionLatch.countDown()
            }
        })
        repl.start(false)
        completionLatch.await()
    }
    // tag::listener-config-client-auth-pwd-full[]
    /**
     *
     * Start a listener for db that accepts connections using exactly the passed username and password
     *
     *
     * @param db       the database to which the listener is attached
     * @param username the name of the single valid user
     * @param password the password for the user
     * @return the url at which the listener can be reached.
     * @throws CouchbaseLiteException on failure
     */
    @Nullable
    fun startServer(
        @NonNull db: Database?,
        @NonNull username: String?,
        @NonNull password: CharArray?
    ): URI?

    companion object {
        private const val TAG = "PWD"
    }

    init {
        val config = URLEndpointListenerConfiguration(db)
        config.setPort(0) // this is the default
        config.setDisableTls(true)
        config.setAuthenticator(
            ListenerPasswordAuthenticator { validUser, pwd ->
                username.equals(validUser) && Arrays.equals(
                    validPassword,
                    pwd
                )
            }
        )
        val listener = URLEndpointListener(config)
        listener.start()
        val urls: List<URI> = listener.getUrls()
        return if (urls.isEmpty()) {
            null
        } else urls[0]
    }
    // end::listener-config-client-auth-pwd-full[]
}


class ExamplesP2p(private val context: Context) {
    private val database: Database? = null
    private var replicator: Replicator? = null

    //@Test
    @Throws(CouchbaseLiteException::class, URISyntaxException::class)
    fun testGettingStarted() {
        // tag::getting-started[]

        // Initialize the Couchbase Lite system
        CouchbaseLite.init(context)

        /* do some stuff here */
    }

    // PASSIVE PEER STUFF
    fun ibListenerSimple() {
        // tag::listener-simple[]
        val thisConfig =
            URLEndpointListenerConfiguration(thisDB) // <.>
        thisConfig.setAuthenticator(
            ListenerPasswordAuthenticator { username, password ->
                username.equals("valid.User") &&
                        Arrays.equals(password, valid.password.string)
            }
        ) // <.>
        val thisListener = URLEndpointListener(thisConfig) // <.>
        thisListener.start() // <.>

        // end::listener-simple[]
    }

    fun ibReplicatorSimple() {
        // tag::replicator-simple[]
        var uri: URI? = null
        try {
            uri = URI("wss://10.0.2.2:4984/db")
        } catch (e: URISyntaxException) {
            e.printStackTrace()
        }
        val theListenerEndpoint: Endpoint = URLEndpoint(uri) // <.>
        val thisConfig =
            ReplicatorConfiguration(database, theListenerEndpoint) // <.>
        thisConfig.setAcceptOnlySelfSignedServerCertificate(true) // <.>
        val thisAuth = BasicAuthenticator(
            "valid.user",
            "valid.password.string"
        )
        thisConfig.setAuthenticator(thisAuth) // <.>
        replicator = Replicator(config) // <.>
        replicator.start() // <.>

        // end::replicator-simple[]
    }

    fun ibPassListener() {
// EXAMPLE 1
        // tag::listener-initialize[]
        // tag::listener-config-db[]
        // Initialize the listener config
        val thisConfig =
            URLEndpointListenerConfiguration(thisDB) // <.>

        // end::listener-config-db[]
        // tag::listener-config-port[]
        thisConfig.setPort(55990) // <.>

        // end::listener-config-port[]
        // tag::listener-config-netw-iface[]
        thisConfig.setNetworkInterface("10.1.1.10") // <.>

        // end::listener-config-netw-iface[]
        // tag::listener-config-delta-sync[]
        thisConfig.setEnableDeltaSync(false) // <.>

        // end::listener-config-delta-sync[]
        // tag::listener-config-tls-full[]
        // Configure server security
        // tag::listener-config-tls-enable[]
        thisConfig.setDisableTls(false) // <.>

        // end::listener-config-tls-enable[]
        // tag::listener-config-tls-id-anon[]
        // Use an Anonymous Self-Signed Cert
        thisConfig.setTlsIdentity(null) // <.>

        // end::listener-config-tls-id-anon[]

        // tag::listener-config-client-auth-pwd[]
        // Configure Client Security using an Authenticator
        // For example, Basic Authentication <.>
        thisConfig.setAuthenticator(
            ListenerPasswordAuthenticator { validUser, validPassword ->
                username.equals(validUser) &&
                        Arrays.equals(password, validPassword)
            }
        )

        // end::listener-config-client-auth-pwd[]
        // tag::listener-start[]
        // Initialize the listener
        val thisListener = URLEndpointListener(thisConfig) // <.>

        // Start the listener
        thisListener.start() // <.>

        // end::listener-start[]
        // end::listener-initialize[]
    }

    fun ibListenerGetNetworkInterfaces() {
        // tag::listener-get-network-interfaces[]
        val thisConfig =
            URLEndpointListenerConfiguration(database)
        val thisListener = URLEndpointListener(thisConfig)
        thisListener.start()
        Log.i(
            TAG,
            "URLS are " + thisListener.getUrls()
        )

        // end::listener-get-network-interfaces[]
    }

    fun ibListenerLocalDb() {
        // tag::listener-local-db[]
        // . . . preceding application logic . . .
        CouchbaseLite.init(context) // <.>
        val thisDB = Database("passivepeerdb")

        // end::listener-local-db[]
    }

    fun ibListenerConfigTlsDisable() {
        // tag::listener-config-tls-disable[]
        thisConfig.setDisableTls(true) // <.>

        // end::listener-config-tls-disable[]
    }

    fun ibListenerConfigTlsIdFull() {
        // tag::listener-config-tls-id-full[]
        // tag::listener-config-tls-id-caCert[]
        // Use CA Cert
        // Import a key pair into secure storage
        // Create a TLSIdentity from the imported key-pair
        val thisKeyPair: InputStream = FileInputStream()
        thisKeyPair.javaClass.getResourceAsStream("serverkeypair.p12") // <.>
        val thisIdentity: TLSIdentity = importIdentity(
            EXTERNAL_KEY_STORE_TYPE,  // KeyStore type, eg: "PKCS12"
            thisKeyPair,  // An InputStream from the keystore
            password,  // The keystore password
            EXTERNAL_KEY_ALIAS,  // The alias to be used (in external keystore)
            null,  // The key password
            "test-alias" // The alias for the imported key
        )

        // end::listener-config-tls-id-caCert[]

        // tag::listener-config-tls-id-set[]
        // Set the TLS Identity
        thisConfig.setTlsIdentity(thisIdentity) // <.>

        // end::listener-config-tls-id-set[]
// end::listener-config-tls-id-full[]
    }

    fun ibListenerConfigClientAuthRoot() {
// tag::listener-config-client-root-ca[]
        // tag::listener-config-client-auth-root[]
        // Configure the client authenticator
        // to validate using ROOT CA
        // thisClientID.certs is a list containing a client cert to accept
        // and any other certs needed to complete a chain between the client cert
        // and a CA
        val validId: TLSIdentity =
            TLSIdentity.getIdentity("Our Corporate Id")
                ?: throw IllegalStateException("Cannot find corporate id") // get the identity <.>
        thisConfig.setTlsIdentity(validId)
        thisConfig.setAuthenticator(
            ListenerCertificateAuthenticator(validId.getCerts())
        ) // <.>
        // accept only clients signed by the corp cert
        val thisListener = URLEndpointListener(thisConfig)

        // end::listener-config-client-auth-root[]
// end::listener-config-client-root-ca[]
    }

    fun ibListenerConfigTlsDisable() {

        // tag::listener-config-tls-disable[]
        thisConfig.disableTLS(true)

        // end::listener-config-tls-disable[]
    }

    fun ibListenerStatusCheck() {
        // tag::listener-status-check[]
        val connectionCount: Int = thisListener.getStatus().getConnectionCount() // <.>
        val activeConnectionCount: Int =
            thisListener.getStatus().getActiveConnectionCount() // <.>

        // end::listener-status-check[]
    }

    fun ibListenerStop() {

        // tag::listener-stop[]
        thisListener.stop()

        // end::listener-stop[]
    }

    // ACTIVE PEER STUFF
    // Replication code
    @Throws(CouchbaseLiteException::class, URISyntaxException::class)
    fun testActPeerSync() {
        // tag::p2p-act-rep-func[]
        // tag::getting-started[]
        // tag::p2p-act-rep-initialize[]
        // initialize the replicator configuration
        val thisConfig = ReplicatorConfiguration(
            thisDB,
            URLEndpoint(URI("wss://listener.com:8954"))
        ) // <.>

        // end::p2p-act-rep-initialize[]
        // tag::p2p-act-rep-config-type[]
        // Set replicator type
        thisConfig.setReplicatorType(
            ReplicatorConfiguration.ReplicatorType.PUSH_AND_PULL
        )

        // end::p2p-act-rep-config-type[]
        // tag::p2p-act-rep-config-cont[]
        // Configure Sync Mode
        thisConfig.setContinuous(false) // default value

        // end::p2p-act-rep-config-cont[]
        // tag::p2p-act-rep-config-self-cert[]
        // Configure Server Authentication --
        // only accept self-signed certs
        thisConfig.setAcceptOnlySelfSignedServerCertificate(true) // <.>

        // end::p2p-act-rep-config-self-cert[]
        // tag::p2p-act-rep-auth[]
        // Configure the credentials the
        // client will provide if prompted
        val thisAuth: BasicAuthenticator // <.>
        thisAuth = BasicAuthenticator("Our Username", "Our PasswordValue")
        thisConfig.setAuthenticator(thisAuth)

        // end::p2p-act-rep-auth[]
        // tag::p2p-act-rep-config-conflict[]
        /* Optionally set custom conflict resolver call back */thisConfig.setConflictResolver() // <.>

        // end::p2p-act-rep-config-conflict[]
        // tag::p2p-act-rep-start-full[]
        // Create replicator
        // Consider holding a reference somewhere
        // to prevent the Replicator from being GCed
        val thisReplicator = Replicator(thisConfig) // <.>

        // tag::p2p-act-rep-add-change-listener[]
        // tag::p2p-act-rep-add-change-listener-label[]
        // Optionally add a change listener <.>
        // end::p2p-act-rep-add-change-listener-label[]
        val thisListener: ListenerToken = addChangeListener { change ->
            val err: CouchbaseLiteException = change.getStatus().getError()
            if (err != null) {
                Log.i(
                    TAG,
                    "Error code ::  " + err.getCode(),
                    e
                )
            }
        }

        // end::p2p-act-rep-add-change-listener[]
        // tag::p2p-act-rep-start[]
        // Start replicator
        thisReplicator.start(false) // <.>

        // end::p2p-act-rep-start[]
        // end::p2p-act-rep-start-full[]
        // end::p2p-act-rep-func[]         ***** End p2p-act-rep-func
    }

    fun ibReplicatorConfig() {
        // BEGIN additional snippets
        // tag::p2p-act-rep-config-tls-full[]
        // tag::p2p-act-rep-config-cacert[]
        // Configure Server Security
        // -- only accept CA attested certs
        thisConfig.setAcceptOnlySelfSignedServerCertificate(false) // <.>

        // end::p2p-act-rep-config-cacert[]
        // tag::p2p-act-rep-config-pinnedcert[]

        // Return the remote pinned cert (the listener's cert)
        val returnedCert: Byte =
            ByteArray(thisConfig.getPinnedCertificate()) // Get listener cert if pinned
        // end::p2p-act-rep-config-pinnedcert[]

        // end::p2p-act-rep-config-tls-full[]
        // tag::p2p-tlsid-tlsidentity-with-label[]
        // ... other replicator configuration
        // Provide a client certificate to the server for authentication
        val thisClientId: TLSIdentity = TLSIdentity.getIdentity("clientId")
            ?: throw IllegalStateException("Cannot find client id") // <.>
        thisConfig.setAuthenticator(ClientCertificateAuthenticator(thisClientId)) // <.>
        // ... other replicator configuration
        val thisReplicator = Replicator(thisConfig)

        // end::p2p-tlsid-tlsidentity-with-label[]
        // tag::p2p-act-rep-config-cacert-pinned[]

        // Use the pinned certificate from the byte array (cert)
        thisConfig.setPinnedServerCertificate(cert.getEncoded()) // <.>
        // end::p2p-act-rep-config-cacert-pinned[]
    }

    fun ibP2pReplicatorStatus() {
        // tag::p2p-act-rep-status[]
        Log.i(
            TAG, "The Replicator is currently " +
                    thisReplicator.getStatus().getActivityLevel()
        )
        Log.i(
            TAG,
            "The Replicator has processed $t"
        )
        if (thisReplicator.getStatus().getActivityLevel() ===
            Replicator.ActivityLevel.BUSY
        ) {
            Log.i(
                TAG,
                "Replication Processing"
            )
            Log.i(
                TAG, "It has completed " +
                        thisReplicator.getStatus().getProgess().getTotal().toString() +
                        " changes"
            )
        }
        // end::p2p-act-rep-status[]
    }

    fun ibP2pReplicatorStop() {
        // tag::p2p-act-rep-stop[]
        // Stop replication.
        thisReplicator.stop() // <.>
        // end::p2p-act-rep-stop[]
    }

    fun ibP2pListener() {
        CouchbaseLite.init(context)
        val thisDB = Database("passivepeerdb") // <.>
        // Initialize the listener config
        val thisConfig =
            URLEndpointListenerConfiguration(database)
        thisConfig.setPort(55990) /* <.>  Optional; defaults to auto */
        thisConfig.setDisableTls(false) /* <.>  Optional; defaults to false */
        thisConfig.setEnableDeltaSync(true) /* <.> Optional; defaults to false */

        // Configure the client authenticator (if using basic auth)
        val auth = ListenerPasswordAuthenticator(
            "username", "password"
        ) // <.>
        thisConfig.setAuthenticator(auth) // <.>

        // Initialize the listener
        val listener = URLEndpointListener(thisConfig) // <.>

        // Start the listener
        listener.start() // <.>


        // tag::createTlsIdentity[]

//        Map<String, String> X509_ATTRIBUTES = mapOf(
//                TLSIdentity.CERT_ATTRIBUTE_COMMON_NAME to "Couchbase Demo",
//                TLSIdentity.CERT_ATTRIBUTE_ORGANIZATION to "Couchbase",
//                TLSIdentity.CERT_ATTRIBUTE_ORGANIZATION_UNIT to "Mobile",
//                TLSIdentity.CERT_ATTRIBUTE_EMAIL_ADDRESS to "noreply@couchbase.com"
//        );
        val thisIdentity: TLSIdentity = createIdentity(true, X509_ATTRIBUTES, null, "test-alias")

        // end::createTlsIdentity[]

        // tag::p2p-tlsid-store-in-keychain[]
        // end::p2p-tlsid-store-in-keychain[]


        // tag::deleteTlsIdentity[]
        // tag::p2p-tlsid-delete-id-from-keychain[]
        val thisAlias = "alias-to-delete"
        val thisKeyStore: KeyStore = KeyStore.getInstance("AndroidKeyStore")
        thisKeyStore.load(null)
        thisKeyStore.deleteEntry(thisAlias)

        // end::p2p-tlsid-delete-id-from-keychain[]
        // end::deleteTlsIdentity[]

        // tag::retrieveTlsIdentity[]
        // OPTIONALLY:: Retrieve a stored TLS identity using its alias/label
        val thisIdentity: TLSIdentity = getIdentity("couchbase-docs-cert")
        // end::retrieveTlsIdentity[]
    }

    // tag::sgw-repl-pull[]
    fun ibRplicatorPull() {
        var database: Database
        var replicator: Replicator // <.>
        var uri: URI? = null
        try {
            uri = URI("wss://10.0.2.2:4984/db") // <.>
        } catch (e: URISyntaxException) {
            e.printStackTrace()
        }
        val endpoint: Endpoint = URLEndpoint(uri)
        val config = ReplicatorConfiguration(database, endpoint)
        config.setReplicatorType(ReplicatorConfiguration.ReplicatorType.PULL)
        this.replicator = Replicator(config)
        this.replicator.start()
    }

    // end::sgw-repl-pull[]
    // tag::sgw-act-rep-initialize[]
    // initialize the replicator configuration
    val thisConfig: ReplicatorConfiguration = ReplicatorConfiguration(
        thisDB,
        URLEndpoint(URI("wss://10.0.2.2:8954/travel-sample"))
    ) // <.> // end::sgw-act-rep-initialize[]

    /* C A L L O U T S

// Listener Callouts

  // tag::listener-callouts-full[]

    // tag::listener-start-callouts[]
    <.> Initialize the listener instance using the configuration settings.
    <.> Start the listener, ready to accept connections and incoming data from active peers.

  // end::listener-start-callouts[]

  // tag::listener-status-check-callouts[]

  <.> `connectionCount` -- the total number of connections served by the listener
  <.> `activeConnectionCount` -- the number of active (BUSY) connections currently being served by the listener
  //
  // end::listener-status-check-callouts[]

    // end::listener-callouts-full[]


    // tag::p2p-act-rep-config-cacert-pinned-callouts[]
  <.> Configure the pinned certificate using data from the byte array `cert`
  // end::p2p-act-rep-config-cacert-pinned-callouts[]

  // tag::p2p-tlsid-tlsidentity-with-label-callouts[]
  <.> Attempt to get the identity from secure storage
  <.> Set the authenticator to ClientCertificateAuthenticator and configure it to use the retrieved identity

  // end::p2p-tlsid-tlsidentity-with-label-callouts[]

  // tag::sgw-repl-pull-callouts[]
  <.> A replication is an asynchronous operation.
  To keep a reference to the `replicator` object, you can set it as an instance property.
  <.> The URL scheme for remote database URLs uses `ws:`, or `wss:` for SSL/TLS connections over wb sockets.
  In this example the hostname is `10.0.2.2` because the Android emulator runs in a VM that is generally accessible on `10.0.2.2` from the host machine (see https://developer.android.com/studio/run/emulator-networking[Android Emulator networking] documentation).
  +
  NOTE: As of Android Pie, version 9, API 28, cleartext support is disabled, by default.
  Although `wss:` protocol URLs are not affected, in order to use the `ws:` protocol, applications must target API 27 or lower, or must configure application network security as described https://developer.android.com/training/articles/security-config#CleartextTrafficPermitted[here].

  // end::sgw-repl-pull-callouts[]
  */
}





    fun testQuerySyntaxAll() {

        // tag::query-syntax-all[]
//        try {
//            this_Db = new Database("hotels");
//        } catch (CouchbaseLiteException e) {
//            e.printStackTrace();
//        }
        val db = openOrCreateDatabaseForUser(currentUser)
        val listQuery: Query = QueryBuilder.select(SelectResult.all())
                .from(DataSource.database(db!!))
        // end::query-syntax-all[]

        // tag::query-access-all[]
        val hotels: HashMap<String, Hotel> = HashMap<String, Hotel>()
        try {
            for (result in listQuery.execute().allResults()) {
                // get the k-v pairs from the 'hotel' key's value into a dictionary
                val thisDocsProps = result.getDictionary(0) // <.>
                val thisDocsId = thisDocsProps!!.getString("id")
                val thisDocsName = thisDocsProps.getString("name")
                val thisDocsType = thisDocsProps.getString("type")
                val thisDocsCity = thisDocsProps.getString("city")

                // Alternatively, access results value dictionary directly
                val hotel = Hotel()
                hotel.id = result.getDictionary(0)!!.getString("id").toString() // <.>
                hotel.type = result.getDictionary(0)!!.getString("type").toString()
                hotel.name = result.getDictionary(0)!!.getString("name").toString()
                hotel.city = result.getDictionary(0)!!.getString("city").toString()
                hotel.country = result.getDictionary(0)!!.getString("country").toString()
                hotel.description = result.getDictionary(0)!!.getString("description").toString()
                hotels[hotel.id] = hotel
            }
        } catch (e: CouchbaseLiteException) {
            e.printStackTrace()
        }

        // end::query-access-all[]
    }

    @Throws(CouchbaseLiteException::class, JSONException::class)
    fun testQuerySyntaxJson() {
        val db = openOrCreateDatabaseForUser(currentUser)
        // tag::query-syntax-json[]
        // Example assumes Hotel class object defined elsewhere
//        Database db = null;
//        try {
//                db = new Database(dbName);
//        } catch (CouchbaseLiteException e) {
//            e.printStackTrace();
//        }

        // Build the query
        val listQuery: Query = QueryBuilder.select(SelectResult.all())
                .from(DataSource.database(db!!))

        // end::query-syntax-json[]

      // tag::query-access-json[]
        // Uses Jackson JSON processor
        val mapper = ObjectMapper();
        val hotels: ArrayList<Hotel> = ArrayList<Hotel>()

        for (result in listQuery.execute()) {

          // Get result as JSON string
          val thisJsonString1: String = result.toJSON() // <.>
          // ALTERNATIVELY
          val thisJsonString = result.getDictionary(0)?.toJSON() // <.>


          // Get Hashmap from JSON string
          val dictFromJSONstring =
              mapper.readValue(thisJsonString, HashMap::class.java) // <.>

          // Use created hashmap
          val hotelId = dictFromJSONstring["id"].toString() //
          val hotelType = dictFromJSONstring["type"].toString()
          val hotelname = dictFromJSONstring["name"].toString()


          // Get custom object from JSON strin
          val thisHotel =
              mapper.readValue(thisJsonString, Hotel::class.java) // <.>
          hotels.add(thisHotel)

      }
      // end::query-access-json[]
    }
    /* end func testQuerySyntaxJson */
