= Database for Swift
:page-layout: article
:page-status: {release-status-cbl} -- {release-comments-cbl}
:page-edition: Under Development
:page-role:
:description: Working with Couchbase Lite Databases

include::partial$_std-cbl-hdr-swift.adoc[]

// BEGIN::Local page attributes
:blank-field: ____
:lang-title: {lang-title-swift}
//:url-issues: {url-github-cbl}{module}/issues

// END::Local page attributes

[abstract]
{description}

== New Database

As the top-level entity in the API, new databases can be created using the `Database` class by passing in a name, configuration, or both.
The following example creates a database using the `Database(name: String)` method.

[source]
----
include::{snippet}[tag=new-database,indent=0]
----

Just as before, the database will be created in a default location.
Alternatively, the `Database(name: Strings, config: DatabaseConfiguration?)` initializer can be used to provide specific options in the {url-api-references}/Classes/DatabaseConfiguration.html[`DatabaseConfiguration`] object such as the database directory.

== Database Encryption

include::{root-partials}database-encryption.adoc[]

== Finding a Database File

When the application is running on the iOS simulator, you can locate the application's sandbox directory using the https://simpholders.com/3/[SimPholders] utility.

== CLI tool

include::{root-partials}cli-tool.adoc[]

== Logging

If you are using a Couchbase Lite release prior to 2.5 see <<Logging functionality prior to Release 2.5, Deprecated functionality>>

include::{root-partials}logging.adoc[leveloffset=+2]

=== Logging functionality prior to Release 2.5

include::{root-partials}logging-pre2.5.adoc[]

[source, {source-language}]

----
include::{snippet}[tags=logging,indent=0]
----

== Loading a pre-built database

include::{root-partials}database-load-prebuilt.adoc[]

See Also: {url-api-references}/Classes/Database.html#/s:18CouchbaseLiteSwift8DatabaseC4copyySS8fromPath_SS02toD0AA0D13ConfigurationVSg10withConfigtKFZ[`Database.copy(fromPath:toDatabase:withConfig:)`]
