:docname: cordova
:page-module: javascript
:page-relative-src-path: cordova.adoc
:page-origin-url: https://github.com/couchbase/docs-couchbase-lite.git
:page-origin-start-path:
:page-origin-refname: antora-assembler-simplification
:page-origin-reftype: branch
:page-origin-refhash: (worktree)
[discrete#javascript:cordova:::javascript:cordova:::javascript:cordova:::javascript:cordova:::javascript:cordova:::javascript:cordova:::javascript:cordova:::javascript:cordova:::javascript:cordova:::javascript:cordova:::javascript:cordova:::javascript:cordova:::javascript:cordova:::javascript:cordova:::javascript:cordova:::javascript:cordova:::javascript:cordova:::javascript:cordova:::]
= Cordova
:page-partials:
:page-toclevels: 2@
:description: Using Couchbase Lite with Javascript applications


// BEGIN -- inclusion -- {module-partials}_define_module_attributes.adoc
//  Usage:  Here we define module specific attributes. It is invoked during the compilation of a page,
//          making all attributes available for use on the page.
//  UsedBy: ROOT:partial$_std_cbl_hdr.adoc

//
// CBL-JAVASCRIPT Maintenance release number
//
//


// End define module specific attributes

// BEGIN::module page attributes
// END::Local page attributes

[abstract]
--
Description -- _{description}_ +
_Abstract -- If you are building mobile or desktop applications using web technologies such as JavaScript/HTML/CSS, there are options for using Couchbase Lite as an embedded database within your app._ +
Related Content -- <<javascript:cordova:::javascript:cordova:::javascript:cordova:::javascript:cordova:::javascript:cordova:::javascript:cordova:::javascript:cordova:::javascript:cordova:::javascript:cordova:::javascript:cordova:::javascript:cordova:::javascript:cordova:::javascript:cordova:::javascript:cordova:::javascript:cordova:::javascript:cordova:::javascript:cordova:::javascript:ionic:::>> | <<javascript:cordova:::javascript:cordova:::javascript:cordova:::javascript:cordova:::javascript:cordova:::javascript:cordova:::javascript:cordova:::javascript:cordova:::javascript:cordova:::javascript:cordova:::javascript:cordova:::javascript:cordova:::javascript:cordova:::javascript:cordova:::javascript:cordova:::javascript:cordova:::javascript:cordova:::javascript:react:::>>
--

NOTE: Couchbase Lite for Cordova is a community-driven project without official support from Couchbase.

[discrete#javascript:cordova:::javascript:cordova:::javascript:cordova:::javascript:cordova:::javascript:cordova:::javascript:cordova:::javascript:cordova:::javascript:cordova:::javascript:cordova:::javascript:cordova:::javascript:cordova:::javascript:cordova:::javascript:cordova:::javascript:cordova:::javascript:cordova:::javascript:cordova:::javascript:cordova:::javascript:cordova:::introduction]
= Introduction


// tag::summary[]
To use Couchbase Lite as an embedded database within your Cordova-based app, you need a way to access Couchbase Lite's iOS and Android native APIs from within your Cordova web application.

// end::summary[]


[discrete#javascript:cordova:::javascript:cordova:::javascript:cordova:::javascript:cordova:::javascript:cordova:::javascript:cordova:::javascript:cordova:::javascript:cordova:::javascript:cordova:::javascript:cordova:::javascript:cordova:::javascript:cordova:::javascript:cordova:::javascript:cordova:::javascript:cordova:::javascript:cordova:::javascript:cordova:::javascript:cordova:::native-functionality]
= Native Functionality


https://cordova.apache.org/docs/en/10.x/guide/hybrid/plugins/index.html[Cordova Native Plugins]
allow web-based apps running in a Cordova webview to access native platform functionality through a Javascript interface.

.Enterprise-only
[NOTE]
Ionic supports both https://capacitorjs.com/docs/plugins[Capacitor] and Cordova, with Ionic recommending use of Capacitor.

To use Couchbase Lite within your Cordova apps, you should implement a Cordova native plugin, which exports the Couchbase Lite Android and iOS APIs to Javascript.
It is typical to start with exporting the minimal subset of APIs that your app needs and extend as needed.

*A reference implementation of a Cordova plugin will be available shortly.*


// DO NOT EDIT -- Footer Related Content Block
// include::ROOT:partial$block-related-content-std.adoc[]
// DO NOT EDIT

:page-toclevels: 2

