:docname: ionic
:page-module: javascript
:page-relative-src-path: ionic.adoc
:page-origin-url: https://github.com/couchbase/docs-couchbase-lite.git
:page-origin-start-path:
:page-origin-refname: antora-assembler-simplification
:page-origin-reftype: branch
:page-origin-refhash: (worktree)
[#javascript:ionic:::]
:page-partials:
:page-edition: Public Preview
:page-toclevels: 2@
:description: The Ionic Capacitor plugin for Couchbase Lite allows developers to leverage Couchbase Lite within cross-platform applications in JavaScript for iOS and Android.



// BEGIN -- inclusion -- {module-partials}_define_module_attributes.adoc
//  Usage:  Here we define module specific attributes. It is invoked during the compilation of a page,
//          making all attributes available for use on the page.
//  UsedBy: ROOT:partial$_std_cbl_hdr.adoc

//
// CBL-JAVASCRIPT Maintenance release number
//
//




// End define module specific attributes

// BEGIN::module page attributes
// END::Local page attributes

[discrete#javascript:ionic:::javascript:ionic:::javascript:ionic:::overview]
= Overview

NOTE: Developers who are currently using the https://ionic.io/docs/couchbase-lite[previous version of the Ionic plugin] should migrate to the newer version of the plugin documented at https://cbl-ionic.dev[Couchbase Lite for Ionic Capacitor].

This public preview release enables developers using Ionic to integrate Couchbase Lite into their mobile applications, ensuring they can build offline-first, cross-platform solutions with ease.

[discrete#javascript:ionic:::javascript:ionic:::javascript:ionic:::important-notes]
= Important Notes

* Platform Support - The plugin currently supports iOS and Android platforms.

* Couchbase Community Supported - This open-source plugin is Couchbase Community supported.
Note that the Couchbase Lite binary linked to the plugin is Couchbase Lite Enterprise Edition (EE) and its use is guided by the terms and conditions of the https://www.couchbase.com/2018-04-30v3_License_Agreement/[Couchbase Lite Enterprise license agreement].

NOTE: _**Couchbase Community Supported**_ is an Open source integration that is developed by Couchbase. Issues related to the integration can be raised in the relevant GitHub repositories or via Couchbase forums or Discord. Support is provided best effort by development team.
For more information, see xref:cloud:third-party:integrations.adoc#support-model[Support Models].

[discrete#javascript:ionic:::javascript:ionic:::javascript:ionic:::getting-started]
= Getting Started

You can get started with the new Ionic plugin and review the official documentation by visiting https://cbl-ionic.dev[the Ionic Plugin Documentation].

[discrete#javascript:ionic:::javascript:ionic:::javascript:ionic:::next-steps]
= Next Steps

As this is a community-supported project, we encourage you to explore, test, and provide feedback to help us improve the Ionic plugin for Couchbase Lite. Feel free to file issues through the https://github.com/Couchbase-Ecosystem/cbl-ionic/issues[GitHub issue tracker], our https://www.couchbase.com/blog/couchbase-on-discord/[Community Discord] or https://www.couchbase.com/forums/[Couchbase Forums].


// DO NOT EDIT -- Footer Related Content Block
// include::ROOT:partial$block-related-content-std.adoc[]
// DO NOT EDIT

:page-toclevels: 2

:page-toclevels: 2

:page-toclevels: 2

