:docname: ionic
:page-module: javascript
:page-relative-src-path: ionic.adoc
:page-origin-url: https://github.com/couchbase/docs-couchbase-lite.git
:page-origin-start-path:
:page-origin-refname: antora-assembler-simplification
:page-origin-reftype: branch
:page-origin-refhash: (worktree)
[#javascript:ionic:::]
== Ionic
:page-partials:
:page-edition:
:page-toclevels: 2@
:description: Using Couchbase Lite with Javascript Ionic applications



// BEGIN -- inclusion -- {module-partials}_define_module_attributes.adoc
//  Usage:  Here we define module specific attributes. It is invoked during the compilation of a page,
//          making all attributes available for use on the page.
//  UsedBy: ROOT:partial$_std_cbl_hdr.adoc

//
// CBL-JAVASCRIPT Maintenance release number
//
//




// End define module specific attributes

// BEGIN::module page attributes
// END::Local page attributes

[abstract]
--
Description -- _{description}_ +
_Abstract -- If you are building mobile or desktop applications using web technologies such as JavaScript/HTML/CSS, there are options for using Couchbase Lite as an embedded database within your app._ +
Related Content -- <<javascript:cordova:::>> | <<javascript:react:::>>
--

.Support Changes
[IMPORTANT]

--
* The Ionic plugin is now open source and community supported.
* The Couchbase Lite API, which contains storage and sync functionality, is fully supported as normal for Enterprise customers.
--

[discrete#javascript:ionic:::introduction]
=== Introduction


// tag::summary[]
Ionic's Couchbase Lite integration is an open source solution for web developers, enabling easy to build secure, high-performance, offline-enabled apps.

// end::summary[]
This integration supports apps built for iOS, Android, and native Windows.

[NOTE]
--
Users can build their own native plugin on top of Couchbase Lite's native API for iOS and Android.
Ionic recommends use of
https://capacitorjs.com/docs/plugins[Capacitor], which can be used independent of the application's UI layer, to access native functionality from within Ionic apps.
--

[discrete#javascript:ionic:::open-source-plugin]
=== Open source Plugin

There are several benefits to be drawn from the open source Ionic integration with Couchbase Lite:

. It is free to use.
. You have the flexibility to customise the plugin to your needs.
. You have more control over the functionality of the plugin and how it interacts with your applications.
. You can contribute to and engage with a community of developers who also make use of the plugin.

Alternatively, you can build your own native application on top of https://capacitorjs.com/docs/plugins[Capacitor].

[discrete#javascript:ionic:::accessing-couchbase-lite]
=== Accessing Couchbase Lite

Using a robust JavaScript API, you can access the entirety of Couchbase Lite's functionality with no native experience required.

As a starting point, you should follow the hotel search tutorial. +
The tutorial shows how to build an app that allows users to search and bookmark hotels.
It uses data loaded from a Couchbase Lite database -- see the tutorial at
https://ionic.io/docs/couchbase-lite/tutorials/hotel-search

.Resources
****

Docs::
https://ionic.io/docs/couchbase-lite.

Tutorial::
https://ionic.io/docs/couchbase-lite/tutorials/hotel-search

Demo::
https://github.com/ionic-team/demo-couchbaselite-hotels

Download::
Reach out to _Ionic_ sales to get access, either from the
https://ionic.io/docs/couchbase-lite[docs page] or this
https://ionic.io/integrations/couchbase-lite[landing page]

****


// DO NOT EDIT -- Footer Related Content Block
// include::ROOT:partial$block-related-content-std.adoc[]
// DO NOT EDIT

:page-toclevels: 2

