= Ionic
:page-partials:
:page-toclevels: 2@
:description: The Ionic Capacitor plugin for Couchbase Lite allows developers to leverage Couchbase Lite within cross-platform applications in JavaScript for iOS and Android. 

include::partial$_set_page_context_for_javascript.adoc[]

== Overview

NOTE: Developers who are using the https://ionic.io/docs/couchbase-lite[previous version of the Ionic plug-in] should migrate to the new version of the plug-in documented at https://cbl-ionic.dev[Couchbase Lite for Ionic Capacitor].

This new release enables developers using Ionic to integrate Couchbase Lite into their mobile applications, ensuring they can build offline-first, cross-platform solutions with ease.

== Important Notes

* Platform Support - The plug-in supports iOS and Android platforms.

* Couchbase Community Supported - This open source plug-in is Couchbase Community supported.
Note that the Couchbase Lite binary linked to the plug-in is Couchbase Lite Enterprise Edition (EE) and its use is guided by the terms and conditions of the https://www.couchbase.com/2018-04-30v3_License_Agreement/[Couchbase Lite Enterprise license agreement].

NOTE: _**Couchbase Community Supported**_ is an Open source integration that is developed by Couchbase. Issues related to the integration can be raised in the relevant GitHub repositories or via Couchbase forums or Discord. Support is provided best effort by development team.
For more information, see xref:cloud:third-party:integrations.adoc#support-model[Support Models].

== Getting Started

You can get started with the new Ionic plug-in and review the official documentation by visiting https://cbl-ionic.dev[the Ionic Plug-in Documentation].

== Next Steps

As this is a community-supported project, we encourage you to explore, test, and provide feedback to help us improve the Ionic plug-in for Couchbase Lite. Feel free to file issues through the https://github.com/Couchbase-Ecosystem/cbl-ionic/issues[GitHub issue tracker], our https://www.couchbase.com/blog/couchbase-on-discord/[Community Discord] or https://www.couchbase.com/forums/[Couchbase Forums].
