= Ionic
:page-partials:
:page-edition: 
:page-toclevels: 2@
:description: Using Couchbase Lite with Javascript Ionic applications

include::partial$_set_page_context_for_javascript.adoc[]

:param-abstract: If you are building mobile or desktop applications using web technologies such as JavaScript/HTML/CSS, there are options for using Couchbase Lite as an embedded database within your app.
:param-related: xref:cordova.adoc[] | xref:react.adoc[]
include::{root-partials}_show_page_header_block.adoc[]

.Support Changes
[IMPORTANT]

--
* The Ionic plugin is now open source and community supported.
* The Couchbase Lite API, which contains storage and sync functionality, is fully supported as normal for Enterprise customers. 
--

== Introduction


// tag::summary[]
Ionic's Couchbase Lite integration is an open source solution for web developers, enabling easy to build secure, high-performance, offline-enabled apps.

// end::summary[]
This integration supports apps built for iOS, Android, and native Windows.

[NOTE]
--
Users can build their own native plugin on top of Couchbase Lite's native API for iOS and Android.
Ionic recommends use of
https://capacitorjs.com/docs/plugins[Capacitor], which can be used independent of the application's UI layer, to access native functionality from within Ionic apps.
--

== Open source Plugin

There are several benefits to be drawn from the open source Ionic integration with Couchbase Lite:

. It is free to use.
. You have the flexibility to customise the plugin to your needs.
. You have more control over the functionality of the plugin and how it interacts with your applications.
. You can contribute to and engage with a community of developers who also make use of the plugin.

You can also create your own plugin based on this by cloning the repository here[] and creating a private repo.
Alternatively, you can build your own native application on top of https://capacitorjs.com/docs/plugins[Capacitor].

== Accessing Couchbase Lite

Using a robust JavaScript API, you can access the entirety of Couchbase Lite's functionality with no native experience required.

As a starting point, you should follow the hotel search tutorial. +
The tutorial shows how to build an app that allows users to search and bookmark hotels.
It uses data loaded from a Couchbase Lite database -- see the tutorial at
https://ionic.io/docs/couchbase-lite/tutorials/hotel-search

.Resources
****

Docs::
https://ionic.io/docs/couchbase-lite.

Tutorial::
https://ionic.io/docs/couchbase-lite/tutorials/hotel-search

Demo::
https://github.com/ionic-team/demo-couchbaselite-hotels

Download::
Reach out to _Ionic_ sales to get access, either from the
https://ionic.io/docs/couchbase-lite[docs page] or this
https://ionic.io/integrations/couchbase-lite[landing page]
*[Insert link to plugin repo here]*

****


// DO NOT EDIT -- Footer Related Content Block
// include::{root-partials}block-related-content-std.adoc[]
// DO NOT EDIT

