= Ionic
:page-partials:
:page-edition: Public Preview
:page-toclevels: 2@
:description: Couchbase is excited to announce the public preview of the Ionic Capacitor plugin for Couchbase Lite, which allows developers to leverage Couchbase Lite within cross-platform applications in JavaScript for iOS and Android. This plugin is open-source and supported by the Couchbase community. 

include::partial$_set_page_context_for_javascript.adoc[]

== Project Overview

NOTE: Developers who are currently using the https://ionic.io/docs/couchbase-lite[previous version of the Ionic plugin] should migrate to the newer version of the plugin documented https://cbl-ionic.dev[here].

This public preview release enables developers using Ionic to integrate Couchbase Lite into their mobile applications, ensuring they can build offline-first, cross-platform solutions with ease.

== Important Notes

* Platform Support - The plugin currently supports iOS and Android platforms.

* Community-Supported - This open-source plugin is Couchbase community supported and maintained, and it requires an Enterprise Edition Couchbase Lite license.
While it is not officially supported by Couchbase, any issues specific to Couchbase Lite are covered under our existing support policy.

NOTE: Couchbase Community Supported is an Open source integration that is developed by Couchbase. Issues can also be raised in the relevant GitHub repositories or via Couchbase forums or Discord. Support is provided best effort by development team.
For more information, see xref:cloud:third-party:integrations.adoc#support-model[Support Models].

== Getting Started

You can get started with the new Ionic plugin and review the official documentation by visiting https://cbl-ionic.dev[the Ionic Plugin Documentation].

== Next Steps

As this is a community-supported project, we encourage you to explore, test, and provide feedback to help us improve the React Native plugin for Couchbase Lite. Feel free to file issues through the https://github.com/Couchbase-Ecosystem/cbl-ionic/issues[GitHub issue tracker], our https://www.couchbase.com/blog/couchbase-on-discord/[Community Discord] or https://www.couchbase.com/forums/[Couchbase Forums].


// DO NOT EDIT -- Footer Related Content Block
// include::{root-partials}block-related-content-std.adoc[]
// DO NOT EDIT

