= React Native
:page-partials:
:page-edition: Public Preview
:page-toclevels: 2@
:description: The React Native plugin for Couchbase Lite is now in public preview. This is an open-source, community-supported project developed by Couchbase.

include::partial$_set_page_context_for_javascript.adoc[]

== High-Level Overview
Couchbase Lite Enterprise Edition for React Native is a Native Module implementation using TypeScript, with feature parity to Couchbase Lite implementations on other platforms.

More information on React Native Native Modules can be found https://cbl-reactnative.dev/[here].

== Important Notes

* Platform Support - This plugin currently only supports iOS and Android platforms. Web, Windows, and macOS are not currently supported.

* Enterprise License Required - The Native Module is based on supporting Couchbase Lite Enterprise for iOS and Android. It is not compatible with Couchbase Lite Community Edition, and a license is required to use the Enterprise edition.

* Community-Supported -  This open-source plugin is Couchbase community supported and maintained, and it requires an Enterprise Edition Couchbase Lite license. 
While it is not officially supported by Couchbase, any issues specific to Couchbase Lite are covered under our existing support policy.

NOTE: Couchbase Community Supported is an Open source integration that is developed by Couchbase. Issues can also be raised in the relevant GitHub repositories or via Couchbase forums or Discord. Support is provided best effort by development team.
For more information, see xref:cloud:third-party:integrations.adoc#support-model[Support Models].

== Getting Started
You can use the links below to help you get started with the React Native plugin for Couchbase Lite:

* https://cbl-reactnative.dev[Official Documentation].

* https://github.com/couchbase-examples/expo-cbl-travel[Example Project] -  A hands-on demonstration using Expo to showcase Couchbase Lite in a React Native app.

* https://github.com/Couchbase-Ecosystem/cbl-reactnative[Project Repository].

=== Why Use Expo?

Couchbase recommends using Expo. 
Expo makes working with React Native simpler and more efficient.
You can find information on the prerequisites and setup, including Expo configuration https://cbl-reactnative.dev/StartHere/prerequisites[here].

== Next Steps

As this is a community-supported project, we encourage you to explore, test, and provide feedback to help us improve the React Native plugin for Couchbase Lite. Feel free to file issues through the https://github.com/Couchbase-Ecosystem/cbl-reactnative/issues[GitHub issue tracker], our https://www.couchbase.com/blog/couchbase-on-discord/[Community Discord] or https://www.couchbase.com/forums/[Couchbase Forums].


// DO NOT EDIT -- Footer Related Content Block
// include::{root-partials}block-related-content-std.adoc[]
// DO NOT EDIT
