:docname: react
:page-module: javascript
:page-relative-src-path: react.adoc
:page-origin-url: https://github.com/couchbase/docs-couchbase-lite.git
:page-origin-start-path:
:page-origin-refname: antora-assembler-simplification
:page-origin-reftype: branch
:page-origin-refhash: (worktree)
[#javascript:react:::]
:page-partials:
:page-edition: Public Preview
:page-toclevels: 2@
:description: The React Native plugin for Couchbase Lite is now in public preview. This is an open-source, community-supported project developed by Couchbase.


// BEGIN -- inclusion -- {module-partials}_define_module_attributes.adoc
//  Usage:  Here we define module specific attributes. It is invoked during the compilation of a page,
//          making all attributes available for use on the page.
//  UsedBy: ROOT:partial$_std_cbl_hdr.adoc

//
// CBL-JAVASCRIPT Maintenance release number
//
//


// End define module specific attributes

// BEGIN::module page attributes
// END::Local page attributes

[discrete#javascript:react:::javascript:react:::javascript:react:::javascript:react:::javascript:react:::javascript:react:::overview]
= Overview

Couchbase Lite Enterprise Edition for React Native is a Native Module implementation that uses TypeScript.
This public preview release enables developers using React to integrate Couchbase Lite into their mobile applications, ensuring they can build offline-first, cross-platform solutions with ease.

More information on React Native Native Modules can be found at https://cbl-reactnative.dev/[Couchbase Lite Enterprise Edition for React Native].

[discrete#javascript:react:::javascript:react:::javascript:react:::javascript:react:::javascript:react:::javascript:react:::important-notes]
= Important Notes

* Platform Support - This plugin currently only supports iOS and Android platforms. Web, Windows, and macOS are not currently supported.

* Couchbase Community Supported - This open-source plugin is Couchbase Community supported.
Note that the Couchbase Lite binary linked to the plugin is Couchbase Lite Enterprise Edition (EE) and its use is guided by the terms and conditions of the https://www.couchbase.com/2018-04-30v3_License_Agreement/[Couchbase Lite Enterprise license agreement].

NOTE: _**Couchbase Community Supported**_ is an Open source integration that is developed by Couchbase. Issues related to the integration can be raised in the relevant GitHub repositories or via Couchbase forums or Discord. Support is provided best effort by development team.
For more information, see xref:cloud:third-party:integrations.adoc#support-model[Support Models].

[discrete#javascript:react:::javascript:react:::javascript:react:::javascript:react:::javascript:react:::javascript:react:::getting-started]
= Getting Started
You can use the links below to help you get started with the React Native plugin for Couchbase Lite:

* https://cbl-reactnative.dev[Official Documentation].

* https://github.com/couchbase-examples/expo-cbl-travel[Example Project] -  A hands-on demonstration using Expo to showcase Couchbase Lite in a React Native app.

* https://github.com/Couchbase-Ecosystem/cbl-reactnative[Project Repository].

[discrete#javascript:react:::javascript:react:::javascript:react:::javascript:react:::javascript:react:::javascript:react:::why-use-expo]
= Why Use Expo?

Couchbase recommends using Expo.
Expo makes working with React Native simpler and more efficient.
You can find information on the prerequisites and setup, including Expo configuration at https://cbl-reactnative.dev/StartHere/prerequisites[Couchbase Lite for React Native Prerequisites].

[discrete#javascript:react:::javascript:react:::javascript:react:::javascript:react:::javascript:react:::javascript:react:::next-steps]
= Next Steps

As this is a community-supported project, we encourage you to explore, test, and provide feedback to help us improve the React Native plugin for Couchbase Lite. Feel free to file issues through the https://github.com/Couchbase-Ecosystem/cbl-reactnative/issues[GitHub issue tracker], our https://www.couchbase.com/blog/couchbase-on-discord/[Community Discord] or https://www.couchbase.com/forums/[Couchbase Forums].


// DO NOT EDIT -- Footer Related Content Block
// include::ROOT:partial$block-related-content-std.adoc[]
// DO NOT EDIT

:page-toclevels: 2

:page-toclevels: 2

:page-toclevels: 2

:page-toclevels: 2

:page-toclevels: 2

:page-toclevels: 2
