:docname: react
:page-module: javascript
:page-relative-src-path: react.adoc
:page-origin-url: https://github.com/couchbase/docs-couchbase-lite.git
:page-origin-start-path:
:page-origin-refname: antora-assembler-simplification
:page-origin-reftype: branch
:page-origin-refhash: (worktree)
[#javascript:react:::]
== React Native
:page-partials:
:page-toclevels: 2@
:description: Using Couchbase Lite with Javascript applications



// BEGIN -- inclusion -- {module-partials}_define_module_attributes.adoc
//  Usage:  Here we define module specific attributes. It is invoked during the compilation of a page,
//          making all attributes available for use on the page.
//  UsedBy: ROOT:partial$_std_cbl_hdr.adoc

//
// CBL-JAVASCRIPT Maintenance release number
//
//




// End define module specific attributes

// BEGIN::module page attributes
// END::Local page attributes

[abstract]
--
Description -- _{description}_ +
_Abstract -- If you are building mobile or desktop applications using web technologies such as JavaScript/HTML/CSS, there are options for using Couchbase Lite as an embedded database within your app._ +
Related Content -- <<javascript:ionic:::>> | <<javascript:cordova:::>>
--





NOTE: Couchbase Lite for React Native is a community-driven project without official support from Couchbase.

// == Introduction


// tag::summary[]
To use Couchbase Lite as an embedded database within your React Native app, you need a way to access Couchbase Lite's iOS and Android native APIs from within it.

React Native's _NativeModule_ system provides an answer, exposing instances of native classes to JavaScript (JS) as JS objects.

// end::summary[]


// == Functionality


https://reactnative.dev/docs/native-modules-intro[React Native Modules]
allow mobile apps written in React Native to access native platform APIs.
So in order to use Couchbase Lite within your React Native apps, you should implement a React Native plugin that exports the Couchbase Lite Android and iOS APIs to Javascript.
It is typical to start with exporting the minimal subset of APIs that your app needs.

.Resources
****

Docs::
*https://reactnative.dev/docs/native-modules-intro[Docs:]* (https://reactnative.dev/docs/native-modules-intro)

Tutorial::
This tutorial is based on our series of _Getting Started_ User Profile app tutorials. +
*https://github.com/couchbaselabs/userprofile-couchbase-mobile-reactnative/blob/main/README.md[Get Started:]* (https://github.com/couchbaselabs/userprofile-couchbase-mobile-reactnative/blob/main/README.md)

Reference Implementation::
https://github.com/couchbaselabs/couchbase-lite-react-native-module/[Reference Implementation] (https://github.com/couchbaselabs/couchbase-lite-react-native-module/)

// DO NOT EDIT -- Footer Related Content Block
// include::ROOT:partial$block-related-content-std.adoc[]
// DO NOT EDIT

:page-toclevels: 2
