== Getting Started

This Android Studio project is used to write code examples for the documentation.
Code snippets are wrapped in AsciiDoc include tags and automatically imported in xref:../../pages/java.adoc[java.adoc] as part of the documentation build process (saving us some copy-pasting).

To start using the project to write code examples, run the following.

. Open *build.gradle* in Android Studio.
. Install Couchbase Lite Enterprise Edition to have auto-completion and verify the code compiles.
+
[source,bash]
----
$ cd libs
$ git clone git@github.com:couchbaselabs/couchbase-lite-android-ee.git
$ cd couchbase-lite-android-ee/
$ git submodule update --init --recursive
----
NOTE:: *couchbaselabs/couchbase-lite-android-ee* is a private repository.
Alternatively, you can install the Enterprise Edition from https://docs.couchbase.com/couchbase-lite/2.1/java.html#couchbase-lite-enterprise-edition[Couchbase's Maven repository].
. Code snippets are located in *MainActivity.java*.
Generally, the xref:../swift/SampleCodeTest.swift[SampleCodeText.swift] version serves as the template for other languages.
