// inclusion

:ld-library-path: LD_LIBRARY_PATH=<path-to-support-files>/libc++:<path-to-support-files>/libicu:$LD_LIBRARY_PATH

[#bmkLinuxSharedLibs]
.Additional Steps for Linux
In addition to setting-up your build environment, you also need to make the supplied native libraries (`<pathToCbl/support`) available:

NOTE: These libraries are provided only in the `.zip` distributable.

[{tabs}]
====

Web Service/Tomcat::
+
--
. Within the `.zip` file, locate the support files appropriate for your environment.
. Copy the directory `<pathToCbl>/support` to a location accessible and executable by your build and runtime environments.
+
include::partial$directory-diagrams.adoc[tag=couchbase-lite-zip]
+
. Add the path of the directories `libc++` and `libicu` to  `LD_LIBRARY_PATH` in `$CATALINA_BASE/bin/setenv.sh.
(If the setenv.sh file doesn't exist, you will need to create a new file.)
+
[source, bashrc, subs="attributes"]
----
{ld-library-path}
----
--

Desktop::
+
--
. Within the `.zip` file, locate the support files appropriate for your environment.
. Copy the directory `<pathToCbl>/support` to a location accessible and executable by your build and runtime environments.
+
include::partial$directory-diagrams.adoc[tag=couchbase-lite-zip]
+
. Add the path of the directories `libc++` and `libicu` to  `LD_LIBRARY_PATH` in the .bashrc file:
+
[source, bashrc, subs="normal"]
----
export {ld-library-path}
----

--
====

Please refer to the Linux Platform Support section for the minimum version requirements of those libraries.



