// inclusion

:ld-library-path: LD_LIBRARY_PATH=<path-to-support-files>/:$LD_LIBRARY_PATH

[#bmkLinuxSharedLibs]
.Additional Steps for Linux]
In addition to setting-up your build environment, you also need to make the supplied native libraries (`<pathToCbl/support`) available:

NOTE: These libraries are provided only in the `.zip` distributable.

[{tabs}]
====

Web Service/Tomcat::
+
--
. Locate the support files appropriate for your environment.
. Copy the _native libraries_ (`<pathToCbl>/support`) to a location accessible to -- and usable by -- your build and runtime environments.
. Add the path of the libraries to  `LD_LIBRARY_PATH` in `$CATALINA_BASE/bin/setenv.sh.
(If the setenv.sh file doesn't exist, you will need to create a new file.)
+
[source, bashrc, subs="attributes"]
----
{ld-library-path}
----
--

Desktop::
+
--
. Locate the support files appropriate for your environment.
. Copy the _native libraries_ (`<pathToCbl>/support`) to a location accessible to -- and usable by -- your build and runtime environments.
. Add the path the to  `LD_LIBRARY_PATH` in the .bashrc file:

+
[source, bashrc, subs="normal"]
----
export {ld-library-path}
----

--

Please refer to the Linux Platform Support section for the minimum version requirements of those libraries.
====
