:docname: gs-prereqs
:page-module: swift
:page-relative-src-path: gs-prereqs.adoc
:page-origin-url: https://github.com/couchbase/docs-couchbase-lite.git
:page-origin-start-path:
:page-origin-refname: antora-assembler-simplification
:page-origin-reftype: branch
:page-origin-refhash: (worktree)
[#swift:gs-prereqs:::]
== Prerequisites
:page-aliases: start/swift-gs-prereqs.adoc
:page-role:
:description: Prerequisites for the installation of Couchbase Lite
:keywords: edge nosql api


// :page-aliases: swift
[abstract]
--
Description -- _{description}_ +
--

.Vector Search Prerequisites
[IMPORTANT]
--
To use Vector Search, you must have Couchbase Lite installed and add the Vector Search extension to your Couchbase Lite application.
Vector Search is available only for 64-bit architectures and
Intel processors that support the Advanced Vector Extensions 2 (AVX2) instruction set.
To verify whether your device supports the AVX2 instructions set, https://www.intel.com/content/www/us/en/support/articles/000090473/processors/intel-core-processors.html[follow these instructions.]
--

[discrete#swift:gs-prereqs:::couchbase-lite-framework-size]
=== Couchbase Lite Framework Size

Couchbase Lite for Swift is provided as an `xcframework`.

The xcframework download size is between 100 and 140 MB.
This include includes a "fat" binary that contains slices for both device (`armv7`, `arm64`) and simulator (`i386` and `x86_64`) CPU architectures.
The fat binary allows you to link your app to the same xcframework and run your app on the simulator or a real device.

In addition, the bitcode that is included contributes to the majority of the download size.
https://help.apple.com/xcode/mac/current/#/devbbdc5ce4f[Bitcode] is an intermediate code representation that allows Apple to recompile the app after App submission and to deliver a thin version of the app specific to the device architecture.

Although you can disable bitcode within your app and strip away bitcode from the Couchbase Lite framework, it is not necessary to do so. In fact, it is probably best to leave it enabled to be future proof. This is because the bitcode is never downloaded by the user even though it is uploaded during App submission.

More information on App size is available on this https://developer.apple.com/library/archive/qa/qa1795/_index.html[Apple Q&A] page.

See also: xref:swift:supported-os.adoc[Supported Versions]

[CAUTION]
.Deprecation Notice -- Apple Mac OS

====
--
Support for Mac OS 10.12
was deprecated in release 3.0
and will be removed in
 a future release
_Action:_ Please plan to migrate your apps to use an appropriate alternative version.
--

====


[discrete#swift:gs-prereqs:::related-content]
=== Related Content
++++
<div class="card-row three-column-row">
++++

[.column]
==== {empty}
.How to . . .
* xref:swift:gs-prereqs.adoc[Prerequisites]
* xref:swift:gs-install.adoc[Install]
* xref:swift:gs-build.adoc[Build and Run]


.

[discrete.colum#swift:gs-prereqs:::-2n]
==== {empty}
.Learn more . . .
* xref:swift:database.adoc[Databases]
* xref:swift:document.adoc[Documents]
* xref:swift:blob.adoc[Blobs]
* xref:swift:replication.adoc[Remote Sync Gateway]
* xref:swift:conflict.adoc[Handling Data Conflicts]

.


[discrete.colum#swift:gs-prereqs:::-3n]
==== {empty}
.Dive Deeper . . .
https://forums.couchbase.com/c/mobile/14[Mobile Forum] |
https://blog.couchbase.com/[Blog] |
https://docs.couchbase.com/tutorials/[Tutorials]

.


++++
</div>
++++


