= Multipeer P2P Replicator
ifdef::show_edition[:page-edition: Enterprise Edition]
:description: The Multipeer P2P Replicator enables lightweight, self-organizing mesh networks for apps running on the same local Wi-Fi.
:source-language: swift


[abstract]
{description}
This approach requires minimal setup and automates peer discovery and connectivity management, making it simpler than xref:p2psync-websocket.adoc[active-passive P2P configurations].


[#introduction]
// == Introduction
// tag::introduction-full[]
// tag::introduction[]
Couchbase Lite's Peer-to-Peer synchronization solution offers secure storage and bidirectional data synchronization between mobile and IoT devices without needing a centralized cloud-based control point.



For small mesh topologies, Multipeer P2P Replicator offers autodiscovery for wifi-based networks and secure communication via TLS and certificate-based authentication.
The dynamic mesh topology gives optimal peer connectivity and the lightweight and low-maintenance configuration requires less management and less code than using Active-Passive peer-to-peer sync.


// Bluetooth - not yet

[TIP]
.Bluetooth networking
====
Multipeer Replication is currently available for use over IP networks.
If you are working over a bluetooth network, then take a look at xref:p2psync-custom.adoc[integrating a Custom Listener]
with Couchbase Lite's Active-Passive Peer-to-Peer synchronization.
====



// end::introduction[]
// end::introduction-full[]


== Overview

The Multipeer P2P Replicator automatically advertises its presence, discovers other peers,
and establishes connections for data replication with peers that share the same group identifier defined by the application.

To maintain optimal connectivity, efficient data transport, and balanced workloads, the Multipeer P2P Replicator forms a dynamic mesh network among peers in the same group.
It avoids redundant direct connections, evenly distributes connections across peers, and optimizes communication paths.
The mesh network continuously adapts as peers join or leave.



// Mesh Diagram

[graphviz]
....
graph {
    layout="circo";
    id1[ label="iOS Device #1" shape="square" ]
    id2[ label="iOS Device #2" shape="square" ]
    id3[ label="iOS Device #3" shape="square" ]
    id4[ label="iOS Device #4" shape="square" ]
    id5[ label="iOS Device #5" shape="square" ]
    id6[ label="iOS Device #6" shape="square" ]
    id1 -- id2
    id1 -- id3
    id1 -- id4
    id1 -- id5
    id1 -- id6
    id2 -- id3
    id2 -- id4
    id2 -- id5
    id2 -- id6
    id3 -- id4
    id3 -- id5
    id3 -- id6
    id4 -- id5
    id4 -- id6
    id5 -- id6
}
....



== Prerequisites

=== Transport and Peer Discovery Protocol

Multipeer P2P Replicator supports Wi-Fi transport, using `DNS-SD` (also known as *Bonjour*) for peer discovery.
Peers must be connected to the same Wi-Fi network to discover and establish connections with one another.

=== Supported Platforms

We recommend using a recent release of iOS -- you will need at least iOS 15 (or macOS 12).


== Configuration

Set up of the Multipeer P2P Replicator configures:

A Group ID::
The `peerGroupID` identifies the peer-to-peer network used by the app.
This differentiates it from Couchbase Lite networks sharing the same local wifi network, 
and ensures that the application only replicates with instances of itself, not some other app.

A TLS Certificate::
An X509 certificate used for mutual authentication on both the client and server side.

Authentication Function::
During TLS handshake, this checks the peer's certificate and decides whether or not to allow the connection.

Collection::
One or more collections from the database to be kept in sync.

See the example, <<use-example,below>> for how to set this up.



TIP: In version 3.3.0, the recommended maximum number of peers in a mesh network is approximately 15.
It should work with more -- but you will need to carry out testing with your particular network,
to assess any performance effects of packet loss or latency across larger mesh networks.


=== Life Cycle

Starting and stopping a peer-to-peer connection in Couchbase Lite 3.3 involves a simple `start()` and `stop()` function.
Once stopped, a new `MultipeerReplicator` must be created.


=== Listening for Changes

Event types are:

* Multipeer Replicator Status
** Active / Inactive
** Includes any error if present
* Peer Discovery Status
** `peerID`
** Online / Offline status
* Peer’s Replicator Status
** `peerID`
** Replicator status:
*** Activity level
*** Outgoing (direction)
*** Error if any
* Peer’s Document Replication
** `PeerID`
** `isPush` (true if push; false if pull)
** Replicated document information

In general, the connection should just work, and most of these optional listen events give status you may only wish to use during development and testing.


[source, swift]
----
include::swift:example$code_snippets/MultipeerP2pReplicator.swift[tags="multipeer-event-discovery", indent=0]
----


== Example Use



////
https://github.com/couchbase/docs-couchbase-lite/tree/multipeer-sync-3.3/modules/swift/examples/code_snippets


[source, swift]
----
include::swift:example$code_snippets/MultipeerP2pReplicator.swift[tags="", indent=0]
----

MultipeerP2pReplicator.swift

multipeer-config around the config / set-up
multipeer-collection-config for the collection set-up
multipeer-conflict-resolver  if you think this is worth highlighting?
multipeer-authenticator  for  MultipeerAuthenticator {}
multipeer-peer-info  as I should think we'll want to pull this out and mention it?
multipeer-event-discovery and multipeer-event-status (ReplicatorStatus) if you think these two could be useful?
multipeer-tlsidentity
multipeer-logdomain
////








Here we show how to instansiate a `MultipeerReplicatorConfiguration` configuration with self-signed certificates,
and connect it to an example collection.


.Configuration for creating a Multipeer P2P Replicator
[source,swift]
----
include::swift:example$code_snippets/MultipeerP2pReplicator.swift[tags="multipeer-config", indent=0]
----



=== `MultipeerCollectionConfiguration`

`MultipeerCollectionConfiguration` specifies a collection and its associated settings.
This includes a conflict resolver and replication filters.
A list of these configurations is required to define which collections will be replicated within the peer group network.

.Configuration for creating a Multipeer P2P Replicator
[source,swift]
----
include::swift:example$code_snippets/MultipeerP2pReplicator.swift[tags="multipeer-collection-config", indent=0]
----




=== `MultipeerConflictResolver`

*TODO* Check multipeer-conflict-resolver code when it arrives...


.Multipeer Conflict Resolver Protocol
[source,swift]
----
include::swift:example$code_snippets/MultipeerP2pReplicator.swift[tags="multipeer-conflict-resolver", indent=0]
----

For more control than a generic `MultipeerConflictResolver`,
you can define a custom `conflictResolver` within each `MultipeerCollectionConfiguration`:


[source,swift]
----
include::swift:example$code_snippets/MultipeerP2pReplicator.swift[tags="multipeer-conflict-resolver", indent=0]
----


=== Authenticator

Authentication succeeds if the peer’s certificate is signed by one of the specified root certificates.
A custom mechanism to authenticate peers based on their certificates can be implemented using callbacks.

[source,swift]
----
include::swift:example$code_snippets/MultipeerP2pReplicator.swift[tags="multipeer-authenticator", indent=0]
----


=== Peer Info

`PeerInfo` provides information about each peer:

* A peer unique identifier, generated as a digest of the peer’s identity certificate.
* The peer certificate
// * Online status -- a list of all known online peers
* Replicator status, and its current `neighborPeers`.
* Neighbor peers -- all peers known to the peer.

[source,swift]
----
include::swift:example$code_snippets/MultipeerP2pReplicator.swift[tags="multipeer-peer-info", indent=0]
----


=== Self-signed Certs

Multipeer P2P Sync uses TLS by default.
This code snippet shows the key set up, using the `TLSIdentity` method.


.Creating a self-signed certificate that can be used as both client and server cert
[source,swift]
----
include::swift:example$code_snippets/MultipeerP2pReplicator.swift[tags="multipeer-tlsidentity", indent=0]
----



////
----
Extended Key Usage for which the certified public key may be used.
public struct KeyUsages: OptionSet {
    /// For Server Authentication	
    public static let serverAuth = 0x40
    
    /// For Client Authentication
    public static let clientAuth = 0x80
}

/// TLS Identity
public class TLSIdentity {
    /// Create a TLS identity from private key and certificate data.
    /// 
    /// The private key and certificate data must be either in PEM or DER format.
    /// This method can be used to create an issuer identity for signing 
    /// a certificate when generating a new TLS identity.
    public static func createIdentity(privateKey: Data, 
                                      certificate: Data) throws -> TLSIdentity


    /// Generate a TLS identity, either self-signed or signed by an issuer identity.
    ///
    /// The `attributes` must include a common name (CN); otherwise an error 
    /// will be thrown.
    ///
    /// If no the expiration date is specified, the default validity of one year 
    /// will be applied. 
    ///
    /// The optional issuer identity may be specified to sign the certificate. 
    /// The  issuer identity can be created using 
    /// `createIdentity(privateKeyData:certificateData:)`. If no issuer is specified, 
    /// the certificate will be self-signed.
    /// 
    /// If a `label` is provided, the identity will be stored in the 
    /// platform’s secure key storage under that label.
    public static func createIdentity(keyUsages: KeyUsages,
                                      attributes: [String: String],
                                      expiration: Date?,
                                      issuer: TLSIdentity?,
                                      label: String?) throws -> TLSIdentity



    
    @Deprecated, “Use createIdentity(keyUsages:attributes:expiration:issuer:label)”
    public static func createIdentity(server: Bool,
                                     attributes: [String: String],
                                     expiration: Date?,
                                     label: String) throws -> TLSIdentity
}
----
////



=== Event Status

.Replicator Status
[source, swift]
----
include::swift:example$code_snippets/MultipeerP2pReplicator.swift[tags="multipeer-event-status", indent=0]
----



=== Logging

`LogDomain` sets up the logging of:

. Peer discovery log messages
. Multipeer replication and mesh network management log messages


[source,swift]
----
include::swift:example$code_snippets/MultipeerP2pReplicator.swift[tags="multipeer-logdomain", indent=0]
----


== API Reference

You can find https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-swift}{empty}/couchbase-lite-swift[Swift API References] here.
