:docname: p2psync-websocket-using-passive
:page-module: swift
:page-relative-src-path: p2psync-websocket-using-passive.adoc
:page-origin-url: https://github.com/couchbase/docs-couchbase-lite.git
:page-origin-start-path:
:page-origin-refname: antora-assembler-simplification
:page-origin-reftype: branch
:page-origin-refhash: (worktree)
[#swift:p2psync-websocket-using-passive:::]
==== Passive Peer
:page-aliases: advance/swift-p2psync-websocket-using-passive.adoc
ifdef::show_edition[:page-edition: {release}] {enterprise}
:page-role:
:description: Couchbase Lite's Peer-to-Peer Synchronization enables edge devices to synchronize securely without consuming centralized cloud-server resources



// BEGIN -- inclusion -- {module-partials}_define_module_attributes.adoc
//  Usage:  Here we define module specific attributes. It is invoked during the compilation of a page,
//          making all attributes available for use on the page.
//  UsedBy: ROOT:partial$_std_cbl_hdr.adoc

// BEGIN::module page attributes
//
// CBL-Swift Maintenance release number
//

// VECTOR SEARCH attributes
//




// BEGIN - Set attributes pointing to API references for this module

// API Reference Links
//
//




// Supporting Data Type Classes


// DATABASE CLASSES






// Begin -- DatabaseConfiguration
// End -- DatabaseConfiguration




// deprecated 2.8
//
// :url-api-method-database-compact: https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-ios}{empty}/couchbase-lite-swift/Classes/Database.html#/s:18CouchbaseLiteSwift8DatabaseC7compactyyKF[Database.compact()]








// links for documents pages






// QUERY RELATED CLASSES and METHODS

// Query class and methods

// Expression class and methods
// :url-api-references-query-classes: https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-ios}{empty}/couchbase-lite-swift/Classes/[Query Class index]



// ArrayFunction class and methods


// API Results Class and methods


// Function class and methods
//

// Where class and methods
//

// orderby class and methods
//

// GroupBy class and methods
//

// URLEndpointConfiguration




















// diag: Env+Module swift




// Replicator API




[Replicator.pendingDocumentIds()]



// Replicator Status



// :url-api-enum-replicator-status: https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-ios}{empty}/couchbase-lite-swift/Classes/Replicator/Status.html[Status struct]
// :url-api-enum-replicator-activity: https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-ios}{empty}/couchbase-lite-swift/Classes/Replicator/ActivityLevel.html[ActivityLevel enum]
// :url-api-enum-replicator-progress: https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-ios}{empty}/couchbase-lite-swift/Classes/Replicator/Progress.html[Progress struct]


// ReplicatorConfiguration API









// Begin Replicator Retry Config



// :url-api-prop-replicator-config-ServerCertificateVerificationMode: https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-ios}{empty}/couchbase-lite-swift/Structs/ReplicatorConfiguration.html#/s:18CouchbaseLiteSwift23ReplicatorConfigurationC33serverCertificateVerificationModeAA06ServerghI0Ovp[serverCertificateVerificationMode]

// :url-api-enum-replicator-config-ServerCertificateVerificationMode: https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-ios}{empty}/couchbase-lite-swift/Structs/ReplicatorConfiguration.html{Enums/ServerCertificateVerificationMode.html[serverCertificateVerificationMode enum]













// Metadata API



// BEGIN Logs and logging references







// END  Logs and logging references



// End define module specific attributes

// BEGIN::module page attributes
// :snippet-p2psync-ws: {snippets-p2psync-ws--swift}

// END::Local page attributes

//= Using Peer-to-Peer Synchronization (websockets)
// DO NOT EDIT



//  | {xref-cbl-pg-p2p-manage-tls-id}
[abstract]
--
Description -- _{description}_ +
_Abstract -- How to set up a Listener to accept a Replicator connection and sync using peer-to-peer_ +
Related Content -- https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-ios}{empty}/couchbase-lite-swift[API Reference]  |  xref:swift:p2psync-websocket-using-passive.adoc[Passive Peer]  |  xref:swift:p2psync-websocket-using-active.adoc[Active Peer]
--




.iOS Restrictions
[CAUTION]
--
iOS 14 Applications::
When your application attempts to access the user's local network, iOS will prompt them to allow (or deny) access.
You can customize the message presented to the user by editing the description for the `NSLocalNetworkUsageDescription` key in the `Info.plist`.
--



.Code Snippets
[NOTE]
All code examples are indicative only.
They demonstrate the basic concepts and approaches to using a feature.
Use them as inspiration and adapt these examples to best practice when developing applications for your platform.


// DO NOT EDIT
[discrete#swift:p2psync-websocket-using-passive:::introduction]
===== Introduction
This content provides code and configuration examples covering the implementation of xref:refer-glossary.adoc#peer-to-peer-sync[Peer-to-Peer Sync] over WebSockets.
Specifically, it covers the implementation of a xref:refer-glossary.adoc#passive-peer[Passive Peer].

Couchbase's Passive Peer (also referred to as the server, or Listener) will accept a connection from an xref:refer-glossary.adoc#active-peer[Active Peer] (also referred to as the client or replicator) and replicate database changes to synchronize both databases.

Subsequent sections provide additional details and examples for the main configuration options.

.Secure Storage
[NOTE]
The use of TLS, its associated keys and certificates requires using secure storage to minimize the chances of a security breach.
The implementation of this storage differs from platform to platform -- see xref:swift:p2psync-websocket.adoc#using-secure-storage[Using secure storage].



[discrete#swift:p2psync-websocket-using-passive:::configuration-summary]
===== Configuration Summary

You should configure and initialize a Listener for each Couchbase Lite database instance you want to sync.
There is no limit on the number of Listeners you may configure -- <<swift:p2psync-websocket-using-passive:::simple-listener-initialization>> shows a simple initialization and configuration process.




// Example 1
.Listener configuration and initialization
[#simple-listener-initialization]
// BEGIN inclusion -- block -- block_tabbed_code_example.adoc
//
//  Allows for abstraction of the showing of snippet examples
//  which makes displaying tabbed snippets for platforms with
//  more than one native language to show -- Android (Kotlin and Java)
//
// Surrounds code in Example block
//
//  PARAMETERS:
//    param-tags comma-separated list of tags to include/exclude
//    param-leader text for opening para of an example block
//
//  USE:
//    :param_tags: query-access-json
//    include::partial$block_show_snippet.adoc[]
//    :param_tags!:
//

[#swift:p2psync-websocket-using-passive:::simple-listener-initialization]
====


// Show Main Snippet
[source, swift]
----
include ::swift:example$code_snippets/SampleCodeTest.swift[tags="listener-initialize", indent=0]

var config = URLEndpointListenerConfiguration(collections: [otherCollection]) // <.>

/* optionally */ let wsPort: UInt16 = 55991
/* optionally */ let wssPort: UInt16 = 55990
config.port =  wssPort // <.>

config.networkInterface = "10.1.1.10"  // <.>

config.enableDeltaSync = true // <.>

config.disableTLS  = false // <.>

// Set the credentials the server presents the client
// Use an anonymous self-signed cert
config.tlsIdentity = nil // <.>

// Configure how the client is to be authenticated
// Here, use Basic Authentication
config.authenticator = ListenerPasswordAuthenticator(authenticator: { uname, pword -> Bool in
    return self.isValidCredentials(uname, password: pword)
}) // <.>


// Initialize the listener
self.listener = URLEndpointListener(config: config) // <.>
if self.listener == nil {
    fatalError("ListenerError Not Initialized")
    // ... take appropriate actions
}

// Start the listener
try self.listener.start() // <.>

----




// close example block

====

// Tidy-up atttibutes created
// END -- block_show_snippet.doc

<.> Identify the local database to be used -- see: <<swift:p2psync-websocket-using-passive:::initialize-the-listener-configuration>>

<.> Optionally, choose a port to use.
By default the system will automatically assign a port -- to over-ride this, see: <<swift:p2psync-websocket-using-passive:::lbl-set-network-and-port>>

<.> Optionally, choose a network interface to use.
By default the system will listen on all network interfaces -- to over-ride this see: <<swift:p2psync-websocket-using-passive:::lbl-set-network-and-port>>

<.> Optionally, choose to sync only changes.
The default is not to enable delta-sync -- see: <<swift:p2psync-websocket-using-passive:::delta-sync>>.

<.> Set server security.
TLS is always enabled instantly, so you can usually omit this line.
But you _can_, optionally, disable TLS (*not* advisable in production) -- see: <<swift:p2psync-websocket-using-passive:::lbl-tls-security>>

<.> Set the credentials this server will present to the client for authentication.
Here we show the default TLS authentication, which is an anonymous self-signed certificate.
The server must always authenticate itself to the client.

<.> Set client security -- define the credentials the server expects the client to present for authentication.
Here we show how basic authentication is configured to authenticate the client-supplied credentials from the http authentication header against valid credentials -- see <<swift:p2psync-websocket-using-passive:::lbl-authenticating-the-client>> for more options. +
Note that client authentication is optional.

<.> Initialize the listener using the configuration settings.

<.> <<swift:p2psync-websocket-using-passive:::lbl-start-listener>>



[discrete#swift:p2psync-websocket-using-passive:::api-references]
===== API References
You can find https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-ios}{empty}/couchbase-lite-swift[Swift API References] here.

[discrete#swift:p2psync-websocket-using-passive:::device-discovery]
===== Device Discovery
*This phase is optional:* If the Listener is initialized on a well-known URL endpoint (for example, a static IP Address or well-known DNS address) then you can configure Active Peers to connect to those.

Before initiating the Listener, you may execute a peer discovery phase.
For the Passive Peer, this involves advertising the service using, for example,
_Bonjour_ (see: https://developer.apple.com/bonjour/)
 and waiting for an invite from the Active Peer.
The connection is established once the Passive Peer has authenticated and accepted an Active Peer's invitation.


[discrete#swift:p2psync-websocket-using-passive:::initialize-the-listener-configuration]
===== Initialize the Listener Configuration
Initialize the Listener configuration with the local database -- see <<swift:p2psync-websocket-using-passive:::ex-locdb>>
All other configuration values take their default setting.

Each Listener instance serves one Couchbase Lite database.
Couchbase sets no hard limit on the number of Listeners you can initialize.

// Example 2
.Specify Local Database
[#ex-locdb]
// BEGIN inclusion -- block -- block_tabbed_code_example.adoc
//
//  Allows for abstraction of the showing of snippet examples
//  which makes displaying tabbed snippets for platforms with
//  more than one native language to show -- Android (Kotlin and Java)
//
// Surrounds code in Example block
//
//  PARAMETERS:
//    param-tags comma-separated list of tags to include/exclude
//    param-leader text for opening para of an example block
//
//  USE:
//    :param_tags: query-access-json
//    include::partial$block_show_snippet.adoc[]
//    :param_tags!:
//

[#swift:p2psync-websocket-using-passive:::ex-locdb]
====


// Show Main Snippet
[source, swift]
----
include ::swift:example$code_snippets/SampleCodeTest.swift[tags="listener-config-db", indent=0]
var config = URLEndpointListenerConfiguration(collections: [otherCollection]) // <.>

----




// close example block

====

// Tidy-up atttibutes created
// END -- block_show_snippet.doc
<.> Set the local database using the https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-ios}{empty}/couchbase-lite-swift/Structs/URLEndpointListenerConfiguration.html[URLEndpointListenerConfiguration]'s constructor https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-ios}{empty}/couchbase-lite-swift/Structs/URLEndpointListenerConfiguration.html#/s:18CouchbaseLiteSwift32URLEndpointListenerConfigurationC8databaseAcA8DatabaseC_tcfc[init(database:)]. +
The database must be opened before the Listener is started. +
`thisDB` has previously been declared as an object of type `Database`.

[discrete#swift:p2psync-websocket-using-passive:::lbl-set-network-and-port]
===== Set Port and Network Interface


[discrete#swift:p2psync-websocket-using-passive:::port-number]
====== Port number
The Listener will automatically select an available port if you do not specify one -- see <<swift:p2psync-websocket-using-passive:::ex-port>> for how to specify a port.

// Example 3
.Specify a port
[#ex-port]
// BEGIN inclusion -- block -- block_tabbed_code_example.adoc
//
//  Allows for abstraction of the showing of snippet examples
//  which makes displaying tabbed snippets for platforms with
//  more than one native language to show -- Android (Kotlin and Java)
//
// Surrounds code in Example block
//
//  PARAMETERS:
//    param-tags comma-separated list of tags to include/exclude
//    param-leader text for opening para of an example block
//
//  USE:
//    :param_tags: query-access-json
//    include::partial$block_show_snippet.adoc[]
//    :param_tags!:
//

[#swift:p2psync-websocket-using-passive:::ex-port]
====


// Show Main Snippet
[source, swift]
----
include ::swift:example$code_snippets/SampleCodeTest.swift[tags="listener-config-port", indent=0]
/* optionally */ let wsPort: UInt16 = 55991
/* optionally */ let wssPort: UInt16 = 55990
config.port =  wssPort // <.>

----




// close example block

====

// Tidy-up atttibutes created
// END -- block_show_snippet.doc
<.> To use a canonical port -- one known to other applications -- specify it explicitly using the https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-ios}{empty}/couchbase-lite-swift/Structs/URLEndpointListenerConfiguration.html#/s:18CouchbaseLiteSwift32URLEndpointListenerConfigurationC4ports6UInt16VSgvp[port] method shown here. +
Ensure that firewall rules do not block any port you do specify. +


[discrete#swift:p2psync-websocket-using-passive:::network-interface]
====== Network Interface
The Listener will listen on all network interfaces by default.

// Example 4

[#specify-a-network-interface-to-use]
.Specify a Network Interface to Use
// BEGIN inclusion -- block -- block_tabbed_code_example.adoc
//
//  Allows for abstraction of the showing of snippet examples
//  which makes displaying tabbed snippets for platforms with
//  more than one native language to show -- Android (Kotlin and Java)
//
// Surrounds code in Example block
//
//  PARAMETERS:
//    param-tags comma-separated list of tags to include/exclude
//    param-leader text for opening para of an example block
//
//  USE:
//    :param_tags: query-access-json
//    include::partial$block_show_snippet.adoc[]
//    :param_tags!:
//

[#swift:p2psync-websocket-using-passive:::specify-a-network-interface-to-use]
====


// Show Main Snippet
[source, swift]
----
include ::swift:example$code_snippets/SampleCodeTest.swift[tags="listener-config-netw-iface", indent=0]
config.networkInterface = "10.1.1.10"  // <.>

----




// close example block

====

// Tidy-up atttibutes created
// END -- block_show_snippet.doc
<.> To specify an interface -- one known to other applications -- identify it explicitly, using the https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-ios}{empty}/couchbase-lite-swift/Structs/URLEndpointListenerConfiguration.html#/s:18CouchbaseLiteSwift32URLEndpointListenerConfigurationC16networkInterfaceSSSgvp[networkInterface] method shown here.
This must be either an IP Address or network interface name such as `en0`.


TIP: Where necessary, you can identify the available interfaces at runtime, using appropriate platform tools -- see <<swift:p2psync-websocket-using-passive:::get-network-interfaces>>.

[#get-network-interfaces]
.Identify available network interfaces
// BEGIN inclusion -- block -- block_tabbed_code_example.adoc
//
//  Allows for abstraction of the showing of snippet examples
//  which makes displaying tabbed snippets for platforms with
//  more than one native language to show -- Android (Kotlin and Java)
//
// Surrounds code in Example block
//
//  PARAMETERS:
//    param-tags comma-separated list of tags to include/exclude
//    param-leader text for opening para of an example block
//
//  USE:
//    :param_tags: query-access-json
//    include::partial$block_show_snippet.adoc[]
//    :param_tags!:
//

[#swift:p2psync-websocket-using-passive:::get-network-interfaces]
====


// Show Main Snippet
[source, swift]
----
include ::swift:example$code_snippets/SampleCodeTest.swift[tags="listener-get-network-interfaces", indent=0]
import SystemConfiguration
// . . .

class SomeClass {
    func SomeFunction() {
        for interface in SCNetworkInterfaceCopyAll() as! [SCNetworkInterface] {
            // do something with this `interface`
        }
    }

    // . . .
}

----




// close example block

====

// Tidy-up atttibutes created
// END -- block_show_snippet.doc



[discrete#swift:p2psync-websocket-using-passive:::delta-sync]
===== Delta Sync

Delta Sync allows clients to sync only those parts of a document that have changed.
This can result in significant bandwidth consumption savings and throughput improvements.
Both are valuable benefits, especially when network bandwidth is constrained.

// Example 5
.Enable delta sync
// BEGIN inclusion -- block -- block_tabbed_code_example.adoc
//
//  Allows for abstraction of the showing of snippet examples
//  which makes displaying tabbed snippets for platforms with
//  more than one native language to show -- Android (Kotlin and Java)
//
// Surrounds code in Example block
//
//  PARAMETERS:
//    param-tags comma-separated list of tags to include/exclude
//    param-leader text for opening para of an example block
//
//  USE:
//    :param_tags: query-access-json
//    include::partial$block_show_snippet.adoc[]
//    :param_tags!:
//

====


// Show Main Snippet
[source, swift]
----
include ::swift:example$code_snippets/SampleCodeTest.swift[tags="listener-config-delta-sync", indent=0]
config.enableDeltaSync = true // <.>

----




// close example block

====

// Tidy-up atttibutes created
// END -- block_show_snippet.doc
<.> Delta sync replication is not enabled by default.
Use https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-ios}{empty}/couchbase-lite-swift/Structs/URLEndpointListenerConfiguration.html[URLEndpointListenerConfiguration]'s https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-ios}{empty}/couchbase-lite-swift/Structs/URLEndpointListenerConfiguration.html#/s:18CouchbaseLiteSwift32URLEndpointListenerConfigurationC15enableDeltaSyncSbvp[enableDeltaSync] method to activate or deactivate it.

[discrete#swift:p2psync-websocket-using-passive:::lbl-tls-security]
===== TLS Security


[discrete#swift:p2psync-websocket-using-passive:::enable-or-disable-tls]
====== Enable or Disable TLS

Define whether the connection is to use TLS or clear text.

TLS-based encryption is enabled by default, and this setting ought to be used in any production environment.
However, it _can_ be disabled. For example, for development or test environments.

When TLS is enabled, Couchbase Lite provides several options on how the Listener may be configured with an appropriate TLS Identity -- see <<swift:p2psync-websocket-using-passive:::configure-tls-identity-for-listener>>.


You can use https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-ios}{empty}/couchbase-lite-swift/Structs/URLEndpointListenerConfiguration.html[URLEndpointListenerConfiguration]'s https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-ios}{empty}/couchbase-lite-swift/Structs/URLEndpointListenerConfiguration.html#/s:18CouchbaseLiteSwift32URLEndpointListenerConfigurationC10disableTLSSbvp[disableTLS] method to disable TLS communication if necessary

The `disableTLS` setting must be 'false' when _Client Cert Authentication_ is required.

Basic Authentication can be used with, or without, TLS.

https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-ios}{empty}/couchbase-lite-swift/Structs/URLEndpointListenerConfiguration.html#/s:18CouchbaseLiteSwift32URLEndpointListenerConfigurationC10disableTLSSbvp[disableTLS] works in conjunction with `TLSIdentity`, to enable developers to define the key and certificate to be used.

* If `disableTLS` is true -- TLS communication is disabled and TLS identity is ignored.
Active peers will use the `ws://` URL scheme used to connect to the listener.
* If `disableTLS` is false or not specified -- TLS communication is enabled.
+
Active peers will use the `wss://` URL scheme to connect to the listener.



[discrete#swift:p2psync-websocket-using-passive:::configure-tls-identity-for-listener]
====== Configure TLS Identity for Listener

Define the credentials the server will present to the client for authentication.
Note that the server must always authenticate itself with the client -- see: xref:swift:p2psync-websocket-using-active.adoc#authenticate-listener[Authenticate Listener on Active Peer] for how the client deals with this.

Use https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-ios}{empty}/couchbase-lite-swift/Structs/URLEndpointListenerConfiguration.html[URLEndpointListenerConfiguration]'s
https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-ios}{empty}/couchbase-lite-swift/Structs/URLEndpointListenerConfiguration.html#/s:18CouchbaseLiteSwift32URLEndpointListenerConfigurationC11tlsIdentityAA11TLSIdentityCSgvp[tlsIdentity] method to configure the TLS Identity used in TLS communication.

If `TLSIdentity` is not set, then the listener uses an auto-generated anonymous self-signed identity (unless `disableTLS = true`).
Whilst the client cannot use this to authenticate the server, it will use it to encrypt communication, giving a more secure option than non-TLS communication.

The auto-generated anonymous self-signed identity is saved in secure storage for future use to obviate the need to re-generate it.


NOTE: Typically, you will configure the Listener's TLS Identity once during the initial launch and re-use it (from secure storage on any subsequent starts.

Here are some example code snippets showing:

* Importing a TLS identity -- see: <<swift:p2psync-websocket-using-passive:::ex-import-tls-id>>
* Setting TLS identity to expect self-signed certificate --  -- see: <<swift:p2psync-websocket-using-passive:::ex-create-tls-id>>
* Setting TLS identity to expect anonymous certificate -- see: <<swift:p2psync-websocket-using-passive:::ex-anon-tls-id>>

.Import Listener's TLS identity
[#ex-import-tls-id]
// BEGIN inclusion -- block -- block_tabbed_code_example.adoc
//
//  Allows for abstraction of the showing of snippet examples
//  which makes displaying tabbed snippets for platforms with
//  more than one native language to show -- Android (Kotlin and Java)
//
// Surrounds code in Example block
//
//  PARAMETERS:
//    param-tags comma-separated list of tags to include/exclude
//    param-leader text for opening para of an example block
//
//  USE:
//    :param_tags: query-access-json
//    include::partial$block_show_snippet.adoc[]
//    :param_tags!:
//

[#swift:p2psync-websocket-using-passive:::ex-import-tls-id]
====

Import an identity from a secure key and certificate data source.

// Show Main Snippet
[source, swift]
----
include ::swift:example$code_snippets/SampleCodeTest.swift[tags="listener-config-tls-enable;listener-config-tls-id-full;!listener-config-tls-id-SelfSigned;!listener-config-tls-id-anon", indent=0]
config.disableTLS  = false // <.>

guard let path = Bundle.main.path(forResource: "cert", ofType: "p12") else {
    /* process error */ return
}

guard let certData = try? NSData(contentsOfFile: path) as Data else {
    /* process error */ return
} // <.>

let tlsIdentity = try TLSIdentity.importIdentity(withData: certData,
                                                 password: "123",
                                                 label: "Server-Cert-Label") // <.>

// Set the credentials the server presents the client
config.tlsIdentity = tlsIdentity    // <.>

----




// close example block

====

// Tidy-up atttibutes created
// END -- block_show_snippet.doc
<.> Ensure TLS is used
<.> Get key and certificate data
<.> Use the retrieved data to create and store the TLS identity
<.> Set this identity as the one presented in response to the client's prompt

.Create Self-Signed Cert
[#ex-create-tls-id]
The system generates a self-signed certificate.]
// BEGIN inclusion -- block -- block_tabbed_code_example.adoc
//
//  Allows for abstraction of the showing of snippet examples
//  which makes displaying tabbed snippets for platforms with
//  more than one native language to show -- Android (Kotlin and Java)
//
// Surrounds code in Example block
//
//  PARAMETERS:
//    param-tags comma-separated list of tags to include/exclude
//    param-leader text for opening para of an example block
//
//  USE:
//    :param_tags: query-access-json
//    include::partial$block_show_snippet.adoc[]
//    :param_tags!:
//

[#swift:p2psync-websocket-using-passive:::ex-create-tls-id]
====

pass:q,a[Create a TLSIdentity for the server using convenience API. +

// Show Main Snippet
[source, swift]
----
include ::swift:example$code_snippets/SampleCodeTest.swift[tags="listener-config-tls-enable;listener-config-tls-id-full;!listener-config-tls-id-caCert;!listener-config-tls-id-anon", indent=0]
config.disableTLS  = false // <.>

let attrs = [certAttrCommonName: "Couchbase Inc"] // <.>

let identity = try TLSIdentity.createIdentity(forServer: true, /* isServer */
                                              attributes: attrs,
                                              expiration: Date().addingTimeInterval(86400),
                                              label: "Server-Cert-Label") // <.>

// Set the credentials the server presents the client
config.tlsIdentity = tlsIdentity    // <.>

----




// close example block

====

// Tidy-up atttibutes created
// END -- block_show_snippet.doc

<.> Ensure TLS is used.
<.> Map the required certificate attributes, in this case the common name.
<.> Create the required TLS identity using the attributes.
Add to secure storage as 'couchbase-docs-cert'.
<.> Configure the server to present the defined identity credentials when prompted.


.Use Anonymous Self-Signed Certificate
[#ex-anon-tls-id]
Generated certificates are held in secure storage.]
// BEGIN inclusion -- block -- block_tabbed_code_example.adoc
//
//  Allows for abstraction of the showing of snippet examples
//  which makes displaying tabbed snippets for platforms with
//  more than one native language to show -- Android (Kotlin and Java)
//
// Surrounds code in Example block
//
//  PARAMETERS:
//    param-tags comma-separated list of tags to include/exclude
//    param-leader text for opening para of an example block
//
//  USE:
//    :param_tags: query-access-json
//    include::partial$block_show_snippet.adoc[]
//    :param_tags!:
//

[#swift:p2psync-websocket-using-passive:::ex-anon-tls-id]
====

pass:q,a[This example uses an _anonymous_ self signed certificate. +

// Show Main Snippet
[source, swift]
----
include ::swift:example$code_snippets/SampleCodeTest.swift[tags="listener-config-tls-enable;listener-config-tls-id-anon", indent=0]
config.disableTLS  = false // <.>

// Set the credentials the server presents the client
// Use an anonymous self-signed cert
config.tlsIdentity = nil // <.>

----




// close example block

====

// Tidy-up atttibutes created
// END -- block_show_snippet.doc

<.> Ensure TLS is used. +
This is the default setting.
<.> Authenticate using an anonymous self-signed certificate. +
This is the default setting.

// Are we missing a section that shows how to use TLSIdentity.getIdentity.  It would be used to create an identity with a certificate signed by a Root CA, in important case.  It could also be used to get an existing self-signed cert (perhaps one created by CreateIdentity above)

// [#authenticating-the-client]
[discrete#swift:p2psync-websocket-using-passive:::lbl-authenticating-the-client]
===== Authenticating the Client
In this section: <<swift:p2psync-websocket-using-passive:::use-basic-authentication>>  |  <<swift:p2psync-websocket-using-passive:::using-client-certificate-authentication>>  |  <<swift:p2psync-websocket-using-passive:::delete-tls-identity>>  |  <<swift:p2psync-websocket-using-passive:::the-impact-of-tls-settings>>

Define how the server (Listener) will authenticate the client as one it is prepared to interact with.

Whilst client authentication is optional, Couchbase lite provides the necessary tools to implement it.
Use the
https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-ios}{empty}/couchbase-lite-swift/Structs/URLEndpointListenerConfiguration.html[URLEndpointListenerConfiguration] class's https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-ios}{empty}/couchbase-lite-swift/Structs/URLEndpointListenerConfiguration.html#/s:18CouchbaseLiteSwift32URLEndpointListenerConfigurationC13authenticatorAA0E13Authenticator_pSgvp[authenticator] method to specify how the client-supplied credentials are to be authenticated.

Valid options are:

* No authentication -- If you do not define an Authenticator then all clients are accepted.
* Basic Authentication -- uses the https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-ios}{empty}/couchbase-lite-swift/Classes//ListenerPasswordAuthenticator.html[ListenerPasswordAuthenticator] to authenticate the client using the client-supplied username and password (from the http authentication header).
* https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-ios}{empty}/couchbase-lite-swift/Classes//ListenerCertificateAuthenticator.html[ListenerCertificateAuthenticator] -- which authenticates the client using a client supplied chain of one or more certificates.
You should initialize the authenticator using one of the following constructors:
** A list of one or more root certificates -- the client supplied certificate must end at a certificate in this list if it is to be authenticated
** A block of code that assumes total responsibility for authentication -- it must return a boolean response (true for an authenticated client, or false for a failed authentication).

// include::ROOT:partial$p2p-api.adoc[tag=config-auth]

[discrete#swift:p2psync-websocket-using-passive:::use-basic-authentication]
====== Use Basic Authentication
// === Authenticate Using the Client Username and Password

Define how to authenticate client-supplied username and password credentials.
To use client-supplied certificates instead -- see: <<swift:p2psync-websocket-using-passive:::using-client-certificate-authentication>>


// include::ROOT:partial$p2p-api.adoc[tag=ListenerPasswordAuthenticatorDelegate]


// Example 7
.Password authentication
// BEGIN inclusion -- block -- block_tabbed_code_example.adoc
//
//  Allows for abstraction of the showing of snippet examples
//  which makes displaying tabbed snippets for platforms with
//  more than one native language to show -- Android (Kotlin and Java)
//
// Surrounds code in Example block
//
//  PARAMETERS:
//    param-tags comma-separated list of tags to include/exclude
//    param-leader text for opening para of an example block
//
//  USE:
//    :param_tags: query-access-json
//    include::partial$block_show_snippet.adoc[]
//    :param_tags!:
//

====


// Show Main Snippet
[source, swift]
----
include ::swift:example$code_snippets/SampleCodeTest.swift[tags="listener-config-client-auth-pwd", indent=0]
// Configure how the client is to be authenticated
// Here, use Basic Authentication
config.authenticator = ListenerPasswordAuthenticator(authenticator: { uname, pword -> Bool in
    return self.isValidCredentials(uname, password: pword)
}) // <.>

----




// close example block

====

// Tidy-up atttibutes created
// END -- block_show_snippet.doc

<.> Where 'username'/'password' are the client-supplied values (from the http-authentication header) and `validUser`/`validPassword` are the values acceptable to the server.


[discrete#swift:p2psync-websocket-using-passive:::using-client-certificate-authentication]
====== Using Client Certificate Authentication
Define how the server will authenticate client-supplied certificates.

There are two ways to authenticate a client:

* A chain of one or more certificates that ends at a certificate in the list of certificates supplied to the constructor for  https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-ios}{empty}/couchbase-lite-swift/Classes//ListenerCertificateAuthenticator.html[ListenerCertificateAuthenticator] -- see: <<swift:p2psync-websocket-using-passive:::ex-set-cert-auth>>

* Application logic: This method assumes complete responsibility for verifying and authenticating the client -- see: <<swift:p2psync-websocket-using-passive:::ex-use-app-logic>>
+
If the parameter supplied to the constructor for `ListenerCertificateAuthenticator` is of type  `ListenerCertificateAuthenticatorDelegate`, all other forms of authentication are bypassed.
+
The client response to the certificate request is passed to the method supplied as the constructor parameter.
The logic should take the form of function or block (such as, a closure expression) where the platform allows.

// Example 8
.Set Certificate Authorization
[#ex-set-cert-auth]
// BEGIN inclusion -- block -- block_tabbed_code_example.adoc
//
//  Allows for abstraction of the showing of snippet examples
//  which makes displaying tabbed snippets for platforms with
//  more than one native language to show -- Android (Kotlin and Java)
//
// Surrounds code in Example block
//
//  PARAMETERS:
//    param-tags comma-separated list of tags to include/exclude
//    param-leader text for opening para of an example block
//
//  USE:
//    :param_tags: query-access-json
//    include::partial$block_show_snippet.adoc[]
//    :param_tags!:
//

[#swift:p2psync-websocket-using-passive:::ex-set-cert-auth]
====

pass:q,a[Configure the server (listener) to authenticate the client against a list of one or more certificates provided by the server to the the https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-ios}{empty}/couchbase-lite-swift/Classes//ListenerCertificateAuthenticator.html[ListenerCertificateAuthenticator].]

// Show Main Snippet
[source, swift]
----
include ::swift:example$code_snippets/SampleCodeTest.swift[tags="listener-config-client-auth-root, indent=0]", indent=0]
// Authenticate using Cert Authority

// cert is a pre-populated object of type:SecCertificate representing a certificate
let rootCertData = SecCertificateCopyData(cert) as Data // <.>
let rootCert = SecCertificateCreateWithData(kCFAllocatorDefault, rootCertData as CFData)! //

config.authenticator = ListenerCertificateAuthenticator.init (rootCerts: [rootCert]) // <.> <.>

----




// close example block

====

// Tidy-up atttibutes created
// END -- block_show_snippet.doc
<.>  Get the identity data to authenticate against.
This can be, for example, from a resource file provided with the app, or an identity previously saved in secure storage.
<.> Configure the authenticator to authenticate the client supplied certificate(s) using these root certs.
A valid client will provide one or more certificates that match a certificate in this list.
<.> Add the authenticator to the Listener configuration.


.Application Logic
[#ex-use-app-logic]
// BEGIN inclusion -- block -- block_tabbed_code_example.adoc
//
//  Allows for abstraction of the showing of snippet examples
//  which makes displaying tabbed snippets for platforms with
//  more than one native language to show -- Android (Kotlin and Java)
//
// Surrounds code in Example block
//
//  PARAMETERS:
//    param-tags comma-separated list of tags to include/exclude
//    param-leader text for opening para of an example block
//
//  USE:
//    :param_tags: query-access-json
//    include::partial$block_show_snippet.adoc[]
//    :param_tags!:
//

[#swift:p2psync-websocket-using-passive:::ex-use-app-logic]
====

pass:q,a[Configure the server (listener) to authenticate the client using user-supplied logic.]

// Show Main Snippet
[source, swift]
----
include ::swift:example$code_snippets/SampleCodeTest.swift[tags="listener-config-client-auth-lambda", indent=0]
// Authenticate self-signed cert using application logic

config.authenticator = ListenerCertificateAuthenticator { certs -> Bool in // <.>
    // Validate the cert
    return self.isValidCertificates(certs)
} // <.>

----




// close example block

====

// Tidy-up atttibutes created
// END -- block_show_snippet.doc
<.>  Get the identity data to authenticate against.
This can be, for example, from a resource file provided with the app, or an identity previously saved in secure storage.
<.>  Configure the Authenticator to pass the root certificates to a user supplied code block.
This code assumes complete responsibility for authenticating the client supplied certificate(s).
It must return a boolean value; with `true` denoting the client supplied certificate authentic.
<.> Add the authenticator to the Listener configuration.


[discrete#swift:p2psync-websocket-using-passive:::delete-tls-identity]
====== Delete Entry

You can remove unwanted TLS identities from secure storage using the convenience API.

// Example 9
.Deleting TLS Identities
// BEGIN inclusion -- block -- block_tabbed_code_example.adoc
//
//  Allows for abstraction of the showing of snippet examples
//  which makes displaying tabbed snippets for platforms with
//  more than one native language to show -- Android (Kotlin and Java)
//
// Surrounds code in Example block
//
//  PARAMETERS:
//    param-tags comma-separated list of tags to include/exclude
//    param-leader text for opening para of an example block
//
//  USE:
//    :param_tags: query-access-json
//    include::partial$block_show_snippet.adoc[]
//    :param_tags!:
//

====


// Show Main Snippet
[source, swift]
----
include ::swift:example$code_snippets/SampleCodeTest.swift[tags="p2p-tlsid-delete-id-from-keychain", indent=0]

try TLSIdentity.deleteIdentity(withLabel: "doco-sync-server")

----




// close example block

====

// Tidy-up atttibutes created
// END -- block_show_snippet.doc


[discrete#swift:p2psync-websocket-using-passive:::the-impact-of-tls-settings]
====== The Impact of TLS Settings

The table in this section shows the expected system behavior (in regards to security) depending on the TLS configuration settings deployed.



.Expected system behavior
[cols="12,44,44"]
|===
|disableTLS |tlsIdentity (corresponding to server) |Expected system behavior

|true
|Ignored
a|TLS is disabled; all communication is plain text.

|false
a| set to nil
a|* The system will auto generate an _anonymous_ self signed cert.
* Active Peers (clients) should be configured to accept self-signed certificates.
* Communication is encrypted

|false
a|Set to server identity generated from a self- or CA-signed certificate

// On first use::
* On first use -- Bring your own certificate and private key; for example, using the https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-ios}{empty}/couchbase-lite-swift/Classes/TLSIdentity.html[TLSIdentity] class's https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-ios}{empty}/couchbase-lite-swift/Classes/TLSIdentity.html#/s:18CouchbaseLiteSwift11TLSIdentityC14createIdentity9forServer10attributes10expiration5labelACSb_SDyS2SG10Foundation4DateVSgSStKFZ[CreateIdentity()] method to add it to the secure storage.
* Each time -- Use the server identity from the certificate stored in the secure storage; for example, using the https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-ios}{empty}/couchbase-lite-swift/Classes/TLSIdentity.html[TLSIdentity] class's https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-ios}{empty}/couchbase-lite-swift/Classes/TLSIdentity.html#//s:18CouchbaseLiteSwift11TLSIdentityC8identity9withLabelACSgSS_tKFZ[identity(withLabel:)] method with the alias you want to retrieve..

// See: {xref-cbl-pg-p2p-manage-tls-id} for more on how to store and use identities.

a|* System will use the configured identity.
* Active Peers will validate the server certificate corresponding to the TLSIdentity (as long as they are configured to not skip validation -- see <<swift:p2psync-websocket-using-passive:::lbl-tls-security>>).

// |false
// a|
// // Use the convenience `createIdentity` API to generate the certificate and identity
// * On first use -- Bring your own CA certificate and private key (use `importIdentity`).
// * Each time -- Use the server identity from the CA certificate stored in the keychain; for example, use `TSLIdentity.identity(withIdentity:)`.

// See: {xref-cbl-pg-p2p-manage-tls-id} for more on how to store and use identities.
// a|. The system will use the provided CA cert.
// . Active peers will validate the CA cert.
// . Communication is encrypted.

|===


[discrete#swift:p2psync-websocket-using-passive:::lbl-start-listener]
===== Start Listener

Once you have completed the Listener's configuration settings you can initialize the Listener instance and start it running -- see: <<swift:p2psync-websocket-using-passive:::initialize-and-start-listener>>

// Example 10
[#initialize-and-start-listener]
.Initialize and start listener
// BEGIN inclusion -- block -- block_tabbed_code_example.adoc
//
//  Allows for abstraction of the showing of snippet examples
//  which makes displaying tabbed snippets for platforms with
//  more than one native language to show -- Android (Kotlin and Java)
//
// Surrounds code in Example block
//
//  PARAMETERS:
//    param-tags comma-separated list of tags to include/exclude
//    param-leader text for opening para of an example block
//
//  USE:
//    :param_tags: query-access-json
//    include::partial$block_show_snippet.adoc[]
//    :param_tags!:
//

[#swift:p2psync-websocket-using-passive:::initialize-and-start-listener]
====


// Show Main Snippet
[source, swift]
----
include ::swift:example$code_snippets/SampleCodeTest.swift[tags="listener-start", indent=0]
// Initialize the listener
self.listener = URLEndpointListener(config: config) // <.>
if self.listener == nil {
    fatalError("ListenerError Not Initialized")
    // ... take appropriate actions
}

// Start the listener
try self.listener.start() // <.>

----




// close example block

====

// Tidy-up atttibutes created
// END -- block_show_snippet.doc





[discrete#swift:p2psync-websocket-using-passive:::monitor-listener]
===== Monitor Listener

Use the Listener's `https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-ios}{empty}/couchbase-lite-swift/Classes/URLEndpointListener.html#/s:18CouchbaseLiteSwift19URLEndpointListenerC6statusAC16ConnectionStatusVvp[status]` property/method to get counts of total and active connections -- see: <<swift:p2psync-websocket-using-passive:::get-connection-counts>>.

You should note that these counts can be extremely volatile. So, the actual number of active connections may have changed, by the time the `https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-ios}{empty}/couchbase-lite-swift/Classes/URLEndpointListener/ConnectionStatus.html[ConnectionStatus]` class returns a result.

// Example 11
.Get connection counts
[#get-connection-counts]
// BEGIN inclusion -- block -- block_tabbed_code_example.adoc
//
//  Allows for abstraction of the showing of snippet examples
//  which makes displaying tabbed snippets for platforms with
//  more than one native language to show -- Android (Kotlin and Java)
//
// Surrounds code in Example block
//
//  PARAMETERS:
//    param-tags comma-separated list of tags to include/exclude
//    param-leader text for opening para of an example block
//
//  USE:
//    :param_tags: query-access-json
//    include::partial$block_show_snippet.adoc[]
//    :param_tags!:
//

[#swift:p2psync-websocket-using-passive:::get-connection-counts]
====


// Show Main Snippet
[source, swift]
----
include ::swift:example$code_snippets/SampleCodeTest.swift[tags="listener-status-check", indent=0]
let totalConnections = self.listener.status.connectionCount
let activeConnections = self.listener.status.activeConnectionCount

----




// close example block

====

// Tidy-up atttibutes created
// END -- block_show_snippet.doc

// include::{exampleblock_callouts.adoc[tags=listener-status-check, indent=0]

[discrete#swift:p2psync-websocket-using-passive:::stop-listener]
===== Stop Listener

It is best practice to check the status of the Listener's connections and stop only when you have confirmed that there are no active connections -- see <<swift:p2psync-websocket-using-passive:::get-connection-counts>>.

// Example 12
.Stop listener using `stop` method
// BEGIN inclusion -- block -- block_tabbed_code_example.adoc
//
//  Allows for abstraction of the showing of snippet examples
//  which makes displaying tabbed snippets for platforms with
//  more than one native language to show -- Android (Kotlin and Java)
//
// Surrounds code in Example block
//
//  PARAMETERS:
//    param-tags comma-separated list of tags to include/exclude
//    param-leader text for opening para of an example block
//
//  USE:
//    :param_tags: query-access-json
//    include::partial$block_show_snippet.adoc[]
//    :param_tags!:
//

====


// Show Main Snippet
[source, swift]
----
include ::swift:example$code_snippets/SampleCodeTest.swift[tags="listener-stop", indent=0]
self.listener.stop()

----




// close example block

====

// Tidy-up atttibutes created
// END -- block_show_snippet.doc

NOTE: Closing the database will also close the Listener.


// DO NOT EDIT -- Footer Related Content Block
// inclusion
//:param-how: //:param-reference: reference-deploy




[discrete#swift:p2psync-websocket-using-passive:::related-content]
===== Related Content
++++
<div class="card-row three-column-row">
++++

[.column]
====== {empty}
.How to
* xref:swift:p2psync-websocket-using-passive.adoc[Passive Peer]
* xref:swift:p2psync-websocket-using-active.adoc[Active Peer]


.

[discrete.colum#swift:p2psync-websocket-using-passive:::-2n]
====== {empty}
.Concepts
* xref:swift:landing-p2psync.adoc[Peer-to-Peer Sync]

* https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-ios}{empty}/couchbase-lite-swift[API References]

.


[.column]
// [.content]
[discrete#swift:p2psync-websocket-using-passive:::-3]
====== {empty}
.Community Resources ...
//* Community
https://forums.couchbase.com/c/mobile/14[Mobile Forum] |
https://blog.couchbase.com/[Blog] |
https://docs.couchbase.com/tutorials/[Tutorials]


.
xref:tutorials:cbl-p2p-sync-websockets:swift/cbl-p2p-sync-websockets.adoc[Getting Started with Peer-to-Peer Synchronization]




++++
</div>
++++
// DO NOT EDIT


