= Multipeer P2P Replicator
ifdef::show_edition[:page-edition: Enterprise Edition]
:description: The Multipeer P2P Replicator enables lightweight, self-organizing mesh networks for apps running on the same local Wi-Fi.
:source-language: swift


[abstract]
{description}
This approach requires minimal setup and automates peer discovery and connectivity management, making it simpler than xref:p2psync-websocket.adoc[active-passive P2P configurations].


[#introduction]
// == Introduction
// tag::introduction-full[]
// tag::introduction[]
Couchbase Lite's Peer-to-Peer synchronization solution offers secure storage and bidirectional data synchronization between mobile and IoT devices without needing a centralized cloud-based control point.



For small mesh topologies, Multipeer P2P Replicator offers autodiscovery for wifi-based networks and secure communication via TLS and certificate-based authentication.
The dynamic mesh topology gives optimal peer connectivity and the lightweight and low-maintenance configuration requires less management and less code than using Active-Passive peer-to-peer sync.


// Bluetooth - not yet

[TIP]
.Bluetooth networking
====
Multipeer Replication is available for use over IP networks.
If you are working over a bluetooth network, then take a look at xref:p2psync-custom.adoc[integrating a Custom Listener]
with Couchbase Lite's Active-Passive Peer-to-Peer synchronization.
====



// end::introduction[]
// end::introduction-full[]


== Overview

The Multipeer P2P Replicator automatically advertises its presence, discovers other peers,
and establishes connections for data replication with peers that share the same group identifier defined by the application.

To maintain optimal connectivity, efficient data transport, and balanced workloads, the Multipeer P2P Replicator forms a dynamic mesh network among peers in the same group.
It avoids redundant direct connections, evenly distributes connections across peers, and optimizes communication paths.
The mesh network continuously adapts as peers join or leave.



// Mesh Diagram

[graphviz]
....
graph {
    layout="circo";
    id1[ label="iOS Device #1" shape="square" ]
    id2[ label="iOS Device #2" shape="square" ]
    id3[ label="iOS Device #3" shape="square" ]
    id4[ label="iOS Device #4" shape="square" ]
    id5[ label="iOS Device #5" shape="square" ]
    id6[ label="iOS Device #6" shape="square" ]
    id1 -- id2
    id1 -- id3
    id1 -- id4
    id1 -- id5
    id1 -- id6
    id2 -- id3
    id2 -- id4
    id2 -- id5
    id2 -- id6
    id3 -- id4
    id3 -- id5
    id3 -- id6
    id4 -- id5
    id4 -- id6
    id5 -- id6
}
....



== Prerequisites

=== Transport and Peer Discovery Protocol

Multipeer P2P Replicator supports Wi-Fi transport, using `DNS-SD` (also known as *Bonjour*) for peer discovery.
Peers must be connected to the same Wi-Fi network to discover and establish connections with one another.

=== Supported Platforms

We recommend using a recent release of iOS, you'll need at least iOS 15 (or macOS 12).


== Configuration

=== Collection Configurations

You can specify one or more collections available for replication when creating a MultipeerReplicatorConfiguration.

For each collection, you will create `MultipeerCollectionConfiguration` with the collection object and optionally configure a custom conflict resolver or any replication filters you want to use for the collection.

.Specify collections without any configurations
[source,swift]
----
include::swift:example$code_snippets/MultipeerP2pReplicator.swift[tags="multipeer-collection-simple", indent=0]
----

.Specify collections with some configuration
[source,swift]
----
include::swift:example$code_snippets/MultipeerP2pReplicator.swift[tags="multipeer-collection-config", indent=0]
----

=== Peer Identity

Each peer in the multipeer replication is uniquely identified and authenticated by using a peer's certificate.
Multipeer Replicator which uses TLS communication by default will require to specify a `TLSIdentity` object for specifying the identity.
Even though we allow the identity to be a self-signed certificate which is mostly suggested for non-production environments, the recommendation is to have the identity's certificate signed by an authority / issuer.
The most simple setup is to bundle an issuer's identity with the application and use it for signing the peer identity's certificate.
Later on, the issuer's certificate can be used for authenticating the connecting peer.

In the multipeer replication environment, each peer can act as either a client or a server to the other peer, so you must create the identity's certificate with extension key usages for both client and server authentication to allow authentication in either direction

.Get and Create an identity signed by an issuer
[source,swift]
----
include::swift:example$code_snippets/MultipeerP2pReplicator.swift[tags="multipeer-tlsidentity", indent=0]
----

=== Peer Authenticator

MultpeerReplicator only supports certificate based authentication.
There are two ways to specify the authenticator : certificate authentication callback or root certificates.

When you specify the certificate authentication callback, the callback will receive the remote peer's identity certificate.

When you specify the root certificates, the multipeer replicator will automatically authenticate the remote peer's identity certificate by verifying whether one of the specified root certificates signed the certificate.

.Authenticator with authentication callback
[source,swift]
----
include::swift:example$code_snippets/MultipeerP2pReplicator.swift[tags="multipeer-authenticator-callback", indent=0]
----

.Authenticator with root certificates
[source,swift]
----
include::swift:example$code_snippets/MultipeerP2pReplicator.swift[tags="multipeer-authenticator-rootcerts", indent=0]
----

=== Create MultipeerReplicatorConfiguration

The MutlipeerReplicatorConfiguration can be created with a `peerGroupID` which is an identity identifies the peer-to-peer network used by the app, collection configurations, peer identity, and authenticator.

.Creating MultipeerReplicatorConfiguration
[source,swift]
----
include::swift:example$code_snippets/MultipeerP2pReplicator.swift[tags="multipeer-config", indent=0]
----

TIP: In version 3.3.0, the recommended maximum number of peers in a mesh network is approximately 15.
It should work with more -- but you will need to carry out testing with your particular network,
to assess any performance effects of packet loss or latency across larger mesh networks.


== Life Cycle

=== Create MultipeerReplicator with Configuration

.Creating MultipeerReplicator
[source,swift]
----
include::swift:example$code_snippets/MultipeerP2pReplicator.swift[tags="multipeer-replicator", indent=0]
----

=== Start

.Starting MultipeerReplicator
[source,swift]
----
include::swift:example$code_snippets/MultipeerP2pReplicator.swift[tags="multipeer-replicator-start", indent=0]
----

=== Stop

.Stopping MultipeerReplicator
[source,swift]
----
include::swift:example$code_snippets/MultipeerP2pReplicator.swift[tags="multipeer-replicator-stop", indent=0]
----

=== Events

Event types include the following.
In general, the connection should just work, and most of these optional listen events give status you may only want to use during development and testing.

==== Multipeer Replicator Status

.Multipeer Replicator Status Listener
[source,swift]
----
include::swift:example$code_snippets/MultipeerP2pReplicator.swift[tags="multipeer-status-listener", indent=0]
----

==== Peer Discovery Status

.Peer Discovery Status Listener
[source,swift]
----
include::swift:example$code_snippets/MultipeerP2pReplicator.swift[tags="multipeer-peer-discovery-listener", indent=0]
----

==== Peer's Replicator Status

.Peer's Replicator Status Listener
[source,swift]
----
include::swift:example$code_snippets/MultipeerP2pReplicator.swift[tags="multipeer-replicator-status-listener", indent=0]
----

==== Peer's Document Replication

.Peer's Document Replication Listener
[source,swift]
----
include::swift:example$code_snippets/MultipeerP2pReplicator.swift[tags="multipeer-document-replication-listener", indent=0]
----


== Peer Info

=== Peer Identifier

You assign each peer a unique peer ID, which is a digest of the peer's identity certificate.
You can get the peer ID from the `peerID` property of the `MultipeerReplicator`.

.Getting peer ID
[source,swift]
----
include::swift:example$code_snippets/MultipeerP2pReplicator.swift[tags="multipeer-peer-id", indent=0]
----

=== Neighbor Peers

You can get a list of current online peers' Identifiers from the `MultipeerReplicator` from the `neighborPeers` property.

.Getting neighbor peers
[source,swift]
----
include::swift:example$code_snippets/MultipeerP2pReplicator.swift[tags="multipeer-neighbor-peers", indent=0]
----

=== Peer Info

.Getting peer info
[source,swift]
----
include::swift:example$code_snippets/MultipeerP2pReplicator.swift[tags="multipeer-peer-info", indent=0]
----


== Logging

`LogDomain` sets up the logging of:

. Peer discovery log messages
. Multipeer replication and mesh network management log messages

[source,swift]
----
include::swift:example$code_snippets/MultipeerP2pReplicator.swift[tags="multipeer-logdomain", indent=0]
----


== API Reference

You can find https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-swift}{empty}/couchbase-lite-swift[Swift API References] here.
