
= Passive Peer
:page-aliases: advance/swift-p2psync-websocket-using-passive.adoc
ifdef::show_edition[:page-edition: {release}] {enterprise}
:page-role:
:description: Couchbase Lite's Peer-to-Peer Synchronization enables edge devices to synchronize securely without consuming centralized cloud-server resources


:source-language: swift

:source-language: swift


[abstract]
--
Description -- _{description}_ +
_Abstract -- How to set up a Listener to accept a Replicator connection and sync using peer-to-peer_ +
Related Content -- https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-ios}{empty}/couchbase-lite-swift[API Reference]  |  xref:swift:p2psync-websocket-using-passive.adoc[Passive Peer]  |  xref:swift:p2psync-websocket-using-active.adoc[Active Peer]
--


.iOS Restrictions
[CAUTION]
--
iOS 14 Applications::
When your application attempts to access the user's local network, iOS will prompt them to allow (or deny) access.
You can customize the message presented to the user by editing the description for the `NSLocalNetworkUsageDescription` key in the `Info.plist`.
--


.Code Snippets
[NOTE]
All code examples are indicative only.
They demonstrate the basic concepts and approaches to using a feature.
Use them as inspiration and adapt these examples to best practice when developing applications for your platform.


[#introduction]
== Introduction
This content provides code and configuration examples covering the implementation of xref:refer-glossary.adoc#peer-to-peer-sync[Peer-to-Peer Sync] over WebSockets.
Specifically, it covers the implementation of a xref:refer-glossary.adoc#passive-peer[Passive Peer].

Couchbase's Passive Peer (also referred to as the server, or Listener) will accept a connection from an xref:refer-glossary.adoc#active-peer[Active Peer] (also referred to as the client or replicator) and replicate database changes to synchronize both databases.

Subsequent sections provide additional details and examples for the main configuration options.

.Secure Storage
[NOTE]
The use of TLS, its associated keys and certificates requires using secure storage to minimize the chances of a security breach.
The implementation of this storage differs from platform to platform -- see xref:swift:p2psync-websocket.adoc#using-secure-storage[Using secure storage].


[#configuration-summary]
== Configuration Summary

You should configure and initialize a Listener for each Couchbase Lite database instance you want to sync.
There is no limit on the number of Listeners you may configure -- xref:swift:p2psync-websocket-using-passive.adoc#simple-listener-initialization[] shows a simple initialization and configuration process.


// Example 1
.Listener configuration and initialization
[#simple-listener-initialization]


[#simple-listener-initialization]
====


[source, swift]
----
include::swift:example$code_snippets/SampleCodeTest.swift[tags="listener-initialize", indent=0]
----


====


<.> Identify the local database to be used -- see: xref:swift:p2psync-websocket-using-passive.adoc#initialize-the-listener-configuration[]

<.> Optionally, choose a port to use.
By default the system will automatically assign a port -- to over-ride this, see: xref:swift:p2psync-websocket-using-passive.adoc#lbl-set-network-and-port[]

<.> Optionally, choose a network interface to use.
By default the system will listen on all network interfaces -- to over-ride this see: xref:swift:p2psync-websocket-using-passive.adoc#lbl-set-network-and-port[]

<.> Optionally, choose to sync only changes.
The default is not to enable delta-sync -- see: xref:swift:p2psync-websocket-using-passive.adoc#delta-sync[].

<.> Set server security.
TLS is always enabled instantly, so you can usually omit this line.
But you _can_, optionally, disable TLS (*not* advisable in production) -- see: xref:swift:p2psync-websocket-using-passive.adoc#lbl-tls-security[]

<.> Set the credentials this server will present to the client for authentication.
Here we show the default TLS authentication, which is an anonymous self-signed certificate.
The server must always authenticate itself to the client.

<.> Set client security -- define the credentials the server expects the client to present for authentication.
Here we show how basic authentication is configured to authenticate the client-supplied credentials from the http authentication header against valid credentials -- see xref:swift:p2psync-websocket-using-passive.adoc#lbl-authenticating-the-client[] for more options. +
Note that client authentication is optional.

<.> Initialize the listener using the configuration settings.

<.> xref:swift:p2psync-websocket-using-passive.adoc#lbl-start-listener[]


[#api-references]
== API References
You can find https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-ios}{empty}/couchbase-lite-swift[Swift API References] here.

[#device-discovery]
== Device Discovery
*This phase is optional:* If the Listener is initialized on a well-known URL endpoint (for example, a static IP Address or well-known DNS address) then you can configure Active Peers to connect to those.

Before initiating the Listener, you may execute a peer discovery phase.
For the Passive Peer, this involves advertising the service using, for example,
_Bonjour_ (see: https://developer.apple.com/bonjour/)
 and waiting for an invite from the Active Peer.
The connection is established once the Passive Peer has authenticated and accepted an Active Peer's invitation.


[#initialize-the-listener-configuration]
== Initialize the Listener Configuration
Initialize the Listener configuration with the local database -- see xref:swift:p2psync-websocket-using-passive.adoc#ex-locdb[]
All other configuration values take their default setting.

Each Listener instance serves one Couchbase Lite database.
Couchbase sets no hard limit on the number of Listeners you can initialize.

// Example 2
.Specify Local Database
[#ex-locdb]


[#ex-locdb]
====


[source, swift]
----
include::swift:example$code_snippets/SampleCodeTest.swift[tags="listener-config-db", indent=0]
----


====

<.> Set the local database using the https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-ios}{empty}/couchbase-lite-swift/Structs/URLEndpointListenerConfiguration.html[URLEndpointListenerConfiguration]'s constructor https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-ios}{empty}/couchbase-lite-swift/Structs/URLEndpointListenerConfiguration.html#/s:18CouchbaseLiteSwift32URLEndpointListenerConfigurationC8databaseAcA8DatabaseC_tcfc[init(database:)]. +
The database must be opened before the Listener is started. +
`thisDB` has previously been declared as an object of type `Database`.

[#lbl-set-network-and-port]
== Set Port and Network Interface


[#port-number]
=== Port number
The Listener will automatically select an available port if you do not specify one -- see xref:swift:p2psync-websocket-using-passive.adoc#ex-port[] for how to specify a port.

// Example 3
.Specify a port
[#ex-port]


[#ex-port]
====


[source, swift]
----
include::swift:example$code_snippets/SampleCodeTest.swift[tags="listener-config-port", indent=0]
----


====

<.> To use a canonical port -- one known to other applications -- specify it explicitly using the https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-ios}{empty}/couchbase-lite-swift/Structs/URLEndpointListenerConfiguration.html#/s:18CouchbaseLiteSwift32URLEndpointListenerConfigurationC4ports6UInt16VSgvp[port] method shown here. +
Ensure that firewall rules do not block any port you do specify. +


[#network-interface]
=== Network Interface
The Listener will listen on all network interfaces by default.

// Example 4

[#specify-a-network-interface-to-use]
.Specify a Network Interface to Use


[#specify-a-network-interface-to-use]
====


[source, swift]
----
include::swift:example$code_snippets/SampleCodeTest.swift[tags="listener-config-netw-iface", indent=0]
----


====

<.> To specify an interface -- one known to other applications -- identify it explicitly, using the https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-ios}{empty}/couchbase-lite-swift/Structs/URLEndpointListenerConfiguration.html#/s:18CouchbaseLiteSwift32URLEndpointListenerConfigurationC16networkInterfaceSSSgvp[networkInterface] method shown here.
This must be either an IP Address or network interface name such as `en0`.


TIP: Where necessary, you can identify the available interfaces at runtime, using appropriate platform tools -- see xref:swift:p2psync-websocket-using-passive.adoc#get-network-interfaces[].

[#get-network-interfaces]
.Identify available network interfaces


[#get-network-interfaces]
====


[source, swift]
----
include::swift:example$code_snippets/SampleCodeTest.swift[tags="listener-get-network-interfaces", indent=0]
----


====


[#delta-sync]
== Delta Sync

Delta Sync allows clients to sync only those parts of a document that have changed.
This can result in significant bandwidth consumption savings and throughput improvements.
Both are valuable benefits, especially when network bandwidth is constrained.

// Example 5
.Enable delta sync


====


[source, swift]
----
include::swift:example$code_snippets/SampleCodeTest.swift[tags="listener-config-delta-sync", indent=0]
----


====

<.> Delta sync replication is not enabled by default.
Use https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-ios}{empty}/couchbase-lite-swift/Structs/URLEndpointListenerConfiguration.html[URLEndpointListenerConfiguration]'s https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-ios}{empty}/couchbase-lite-swift/Structs/URLEndpointListenerConfiguration.html#/s:18CouchbaseLiteSwift32URLEndpointListenerConfigurationC15enableDeltaSyncSbvp[enableDeltaSync] method to activate or deactivate it.

[#lbl-tls-security]
== TLS Security


[#enable-or-disable-tls]
=== Enable or Disable TLS

Define whether the connection is to use TLS or clear text.

TLS-based encryption is enabled by default, and this setting ought to be used in any production environment.
However, it _can_ be disabled. For example, for development or test environments.

When TLS is enabled, Couchbase Lite provides several options on how the Listener may be configured with an appropriate TLS Identity -- see xref:swift:p2psync-websocket-using-passive.adoc#configure-tls-identity-for-listener[].


You can use https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-ios}{empty}/couchbase-lite-swift/Structs/URLEndpointListenerConfiguration.html[URLEndpointListenerConfiguration]'s https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-ios}{empty}/couchbase-lite-swift/Structs/URLEndpointListenerConfiguration.html#/s:18CouchbaseLiteSwift32URLEndpointListenerConfigurationC10disableTLSSbvp[disableTLS] method to disable TLS communication if necessary

The `disableTLS` setting must be 'false' when _Client Cert Authentication_ is required.

Basic Authentication can be used with, or without, TLS.

https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-ios}{empty}/couchbase-lite-swift/Structs/URLEndpointListenerConfiguration.html#/s:18CouchbaseLiteSwift32URLEndpointListenerConfigurationC10disableTLSSbvp[disableTLS] works in conjunction with `TLSIdentity`, to enable developers to define the key and certificate to be used.

* If `disableTLS` is true -- TLS communication is disabled and TLS identity is ignored.
Active peers will use the `ws://` URL scheme used to connect to the listener.
* If `disableTLS` is false or not specified -- TLS communication is enabled.
+
Active peers will use the `wss://` URL scheme to connect to the listener.


[#configure-tls-identity-for-listener]
=== Configure TLS Identity for Listener

Define the credentials the server will present to the client for authentication.
Note that the server must always authenticate itself with the client -- see: xref:swift:p2psync-websocket-using-active.adoc#authenticate-listener[Authenticate Listener on Active Peer] for how the client deals with this.

Use https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-ios}{empty}/couchbase-lite-swift/Structs/URLEndpointListenerConfiguration.html[URLEndpointListenerConfiguration]'s
https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-ios}{empty}/couchbase-lite-swift/Structs/URLEndpointListenerConfiguration.html#/s:18CouchbaseLiteSwift32URLEndpointListenerConfigurationC11tlsIdentityAA11TLSIdentityCSgvp[tlsIdentity] method to configure the TLS Identity used in TLS communication.

If `TLSIdentity` is not set, then the listener uses an auto-generated anonymous self-signed identity (unless `disableTLS = true`).
Whilst the client cannot use this to authenticate the server, it will use it to encrypt communication, giving a more secure option than non-TLS communication.

The auto-generated anonymous self-signed identity is saved in secure storage for future use to obviate the need to re-generate it.


NOTE: Typically, you will configure the Listener's TLS Identity once during the initial launch and re-use it (from secure storage on any subsequent starts.

Here are some example code snippets showing:

* Importing a TLS identity -- see: xref:swift:p2psync-websocket-using-passive.adoc#ex-import-tls-id[]
* Setting TLS identity to expect self-signed certificate --  -- see: xref:swift:p2psync-websocket-using-passive.adoc#ex-create-tls-id[]
* Setting TLS identity to expect anonymous certificate -- see: xref:swift:p2psync-websocket-using-passive.adoc#ex-anon-tls-id[]

.Import Listener's TLS identity
[#ex-import-tls-id]


[#ex-import-tls-id]
====

Import an identity from a secure key and certificate data source.

[source, swift]
----
include::swift:example$code_snippets/SampleCodeTest.swift[tags="listener-config-tls-enable;listener-config-tls-id-full;!listener-config-tls-id-SelfSigned;!listener-config-tls-id-anon", indent=0]
----


====

<.> Ensure TLS is used
<.> Get key and certificate data
<.> Use the retrieved data to create and store the TLS identity
<.> Set this identity as the one presented in response to the client's prompt

.Create Self-Signed Cert
[#ex-create-tls-id]


[#ex-create-tls-id]
====

Create a TLSIdentity for the server using convenience API.  The system generates a self-signed certificate.

[source, swift]
----
include::swift:example$code_snippets/SampleCodeTest.swift[tags="listener-config-tls-enable;listener-config-tls-id-full;!listener-config-tls-id-caCert;!listener-config-tls-id-anon", indent=0]
----


====


<.> Ensure TLS is used.
<.> Map the required certificate attributes, in this case the common name.
<.> Create the required TLS identity using the attributes.
Add to secure storage as 'couchbase-docs-cert'.
<.> Configure the server to present the defined identity credentials when prompted.


.Use Anonymous Self-Signed Certificate
[#ex-anon-tls-id]


[#ex-anon-tls-id]
====

This example uses an _anonymous_ self signed certificate.  Generated certificates are held in secure storage.

[source, swift]
----
include::swift:example$code_snippets/SampleCodeTest.swift[tags="listener-config-tls-enable;listener-config-tls-id-anon", indent=0]
----


====


<.> Ensure TLS is used. +
This is the default setting.
<.> Authenticate using an anonymous self-signed certificate. +
This is the default setting.


[#lbl-authenticating-the-client]
== Authenticating the Client
In this section: xref:swift:p2psync-websocket-using-passive.adoc#use-basic-authentication[]  |  xref:swift:p2psync-websocket-using-passive.adoc#using-client-certificate-authentication[]  |  xref:swift:p2psync-websocket-using-passive.adoc#delete-tls-identity[]  |  xref:swift:p2psync-websocket-using-passive.adoc#the-impact-of-tls-settings[]

Define how the server (Listener) will authenticate the client as one it is prepared to interact with.

Whilst client authentication is optional, Couchbase lite provides the necessary tools to implement it.
Use the
https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-ios}{empty}/couchbase-lite-swift/Structs/URLEndpointListenerConfiguration.html[URLEndpointListenerConfiguration] class's https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-ios}{empty}/couchbase-lite-swift/Structs/URLEndpointListenerConfiguration.html#/s:18CouchbaseLiteSwift32URLEndpointListenerConfigurationC13authenticatorAA0E13Authenticator_pSgvp[authenticator] method to specify how the client-supplied credentials are to be authenticated.

Valid options are:

* No authentication -- If you do not define an Authenticator then all clients are accepted.
* Basic Authentication -- uses the https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-ios}{empty}/couchbase-lite-swift/Classes//ListenerPasswordAuthenticator.html[ListenerPasswordAuthenticator] to authenticate the client using the client-supplied username and password (from the http authentication header).
* https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-ios}{empty}/couchbase-lite-swift/Classes//ListenerCertificateAuthenticator.html[ListenerCertificateAuthenticator] -- which authenticates the client using a client supplied chain of one or more certificates.
You should initialize the authenticator using one of the following constructors:
** A list of one or more root certificates -- the client supplied certificate must end at a certificate in this list if it is to be authenticated
** A block of code that assumes total responsibility for authentication -- it must return a boolean response (true for an authenticated client, or false for a failed authentication).


[#use-basic-authentication]
=== Use Basic Authentication

Define how to authenticate client-supplied username and password credentials.
To use client-supplied certificates instead -- see: xref:swift:p2psync-websocket-using-passive.adoc#using-client-certificate-authentication[]


// Example 7
.Password authentication


====


[source, swift]
----
include::swift:example$code_snippets/SampleCodeTest.swift[tags="listener-config-client-auth-pwd", indent=0]
----


====


<.> Where 'username'/'password' are the client-supplied values (from the http-authentication header) and `validUser`/`validPassword` are the values acceptable to the server.


[#using-client-certificate-authentication]
=== Using Client Certificate Authentication
Define how the server will authenticate client-supplied certificates.

There are two ways to authenticate a client:

* A chain of one or more certificates that ends at a certificate in the list of certificates supplied to the constructor for  https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-ios}{empty}/couchbase-lite-swift/Classes//ListenerCertificateAuthenticator.html[ListenerCertificateAuthenticator] -- see: xref:swift:p2psync-websocket-using-passive.adoc#ex-set-cert-auth[]

* Application logic: This method assumes complete responsibility for verifying and authenticating the client -- see: xref:swift:p2psync-websocket-using-passive.adoc#ex-use-app-logic[]
+
If the parameter supplied to the constructor for `ListenerCertificateAuthenticator` is of type  `ListenerCertificateAuthenticatorDelegate`, all other forms of authentication are bypassed.
+
The client response to the certificate request is passed to the method supplied as the constructor parameter.
The logic should take the form of function or block (such as, a closure expression) where the platform allows.

// Example 8
.Set Certificate Authorization
[#ex-set-cert-auth]


[#ex-set-cert-auth]
====

Configure the server (listener) to authenticate the client against a list of one or more certificates provided by the server to the the https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-ios}{empty}/couchbase-lite-swift/Classes//ListenerCertificateAuthenticator.html[ListenerCertificateAuthenticator].

[source, swift]
----
include::swift:example$code_snippets/SampleCodeTest.swift[tags="listener-config-client-auth-root, indent=0]", indent=0]
----


====

<.>  Get the identity data to authenticate against.
This can be, for example, from a resource file provided with the app, or an identity previously saved in secure storage.
<.> Configure the authenticator to authenticate the client supplied certificate(s) using these root certs.
A valid client will provide one or more certificates that match a certificate in this list.
<.> Add the authenticator to the Listener configuration.


.Application Logic
[#ex-use-app-logic]


[#ex-use-app-logic]
====

Configure the server (listener) to authenticate the client using user-supplied logic.

[source, swift]
----
include::swift:example$code_snippets/SampleCodeTest.swift[tags="listener-config-client-auth-lambda", indent=0]
----


====

<.>  Get the identity data to authenticate against.
This can be, for example, from a resource file provided with the app, or an identity previously saved in secure storage.
<.>  Configure the Authenticator to pass the root certificates to a user supplied code block.
This code assumes complete responsibility for authenticating the client supplied certificate(s).
It must return a boolean value; with `true` denoting the client supplied certificate authentic.
<.> Add the authenticator to the Listener configuration.


[#delete-tls-identity]
=== Delete Entry

You can remove unwanted TLS identities from secure storage using the convenience API.

// Example 9
.Deleting TLS Identities


====


[source, swift]
----
include::swift:example$code_snippets/SampleCodeTest.swift[tags="p2p-tlsid-delete-id-from-keychain", indent=0]
----


====


[#the-impact-of-tls-settings]
=== The Impact of TLS Settings

The table in this section shows the expected system behavior (in regards to security) depending on the TLS configuration settings deployed.


.Expected system behavior
[cols="12,44,44"]
|===
|disableTLS |tlsIdentity (corresponding to server) |Expected system behavior

|true
|Ignored
a|TLS is disabled; all communication is plain text.

|false
a| set to nil
a|* The system will auto generate an _anonymous_ self signed cert.
* Active Peers (clients) should be configured to accept self-signed certificates.
* Communication is encrypted

|false
a|Set to server identity generated from a self- or CA-signed certificate

* On first use -- Bring your own certificate and private key; for example, using the https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-ios}{empty}/couchbase-lite-swift/Classes/TLSIdentity.html[TLSIdentity] class's https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-ios}{empty}/couchbase-lite-swift/Classes/TLSIdentity.html#/s:18CouchbaseLiteSwift11TLSIdentityC14createIdentity9forServer10attributes10expiration5labelACSb_SDyS2SG10Foundation4DateVSgSStKFZ[CreateIdentity()] method to add it to the secure storage.
* Each time -- Use the server identity from the certificate stored in the secure storage; for example, using the https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-ios}{empty}/couchbase-lite-swift/Classes/TLSIdentity.html[TLSIdentity] class's https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-ios}{empty}/couchbase-lite-swift/Classes/TLSIdentity.html#//s:18CouchbaseLiteSwift11TLSIdentityC8identity9withLabelACSgSS_tKFZ[identity(withLabel:)] method with the alias you want to retrieve..


a|* System will use the configured identity.
* Active Peers will validate the server certificate corresponding to the TLSIdentity (as long as they are configured to not skip validation -- see xref:swift:p2psync-websocket-using-passive.adoc#lbl-tls-security[]).

|===


[#lbl-start-listener]
== Start Listener

Once you have completed the Listener's configuration settings you can initialize the Listener instance and start it running -- see: xref:swift:p2psync-websocket-using-passive.adoc#initialize-and-start-listener[]

// Example 10
[#initialize-and-start-listener]
.Initialize and start listener


[#initialize-and-start-listener]
====


[source, swift]
----
include::swift:example$code_snippets/SampleCodeTest.swift[tags="listener-start", indent=0]
----


====


[#monitor-listener]
== Monitor Listener

Use the Listener's `https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-ios}{empty}/couchbase-lite-swift/Classes/URLEndpointListener.html#/s:18CouchbaseLiteSwift19URLEndpointListenerC6statusAC16ConnectionStatusVvp[status]` property/method to get counts of total and active connections -- see: xref:swift:p2psync-websocket-using-passive.adoc#get-connection-counts[].

You should note that these counts can be extremely volatile. So, the actual number of active connections may have changed, by the time the `https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-ios}{empty}/couchbase-lite-swift/Classes/URLEndpointListener/ConnectionStatus.html[ConnectionStatus]` class returns a result.

// Example 11
.Get connection counts
[#get-connection-counts]


[#get-connection-counts]
====


[source, swift]
----
include::swift:example$code_snippets/SampleCodeTest.swift[tags="listener-status-check", indent=0]
----


====


[#stop-listener]
== Stop Listener

It is best practice to check the status of the Listener's connections and stop only when you have confirmed that there are no active connections -- see xref:swift:p2psync-websocket-using-passive.adoc#get-connection-counts[].

// Example 12
.Stop listener using `stop` method


====


[source, swift]
----
include::swift:example$code_snippets/SampleCodeTest.swift[tags="listener-stop", indent=0]
----


====


NOTE: Closing the database will also close the Listener.


[#related-content]
== Related Content
++++
<div class="card-row three-column-row">
++++

[.column]
=== {empty}
.How to
* xref:swift:p2psync-websocket-using-passive.adoc[Passive Peer]
* xref:swift:p2psync-websocket-using-active.adoc[Active Peer]


.

[.column]
=== {empty}
.Concepts
* xref:swift:landing-p2psync.adoc[Peer-to-Peer Sync]

* https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-ios}{empty}/couchbase-lite-swift[API References]

.


[.column]
=== {empty}
.Community Resources ...
https://forums.couchbase.com/c/mobile/14[Mobile Forum] |
https://blog.couchbase.com/[Blog] |
https://docs.couchbase.com/tutorials/[Tutorials]

.
xref:tutorials:cbl-p2p-sync-websockets:swift/cbl-p2p-sync-websockets.adoc[Getting Started with Peer-to-Peer Synchronization]


++++
</div>
++++


