:docname: query-resultsets
:page-module: swift
:page-relative-src-path: query-resultsets.adoc
:page-origin-url: https://github.com/couchbase/docs-couchbase-lite.git
:page-origin-start-path:
:page-origin-refname: antora-assembler-simplification
:page-origin-reftype: branch
:page-origin-refhash: (worktree)
[#swift:query-resultsets:::]
== Query Resultsets
:page-role:
:description: How to use Couchbase Lite Query's Result Sets
:keywords: query, sql, n1ql, fuzzy-matching


:version: {major}.{minor}
:vs-version: {vs-major}.{vs-minor}
:version-full: {major}.{minor}.{base}{empty}
:version-full-hyphenated: {major}-{minor}-{base}{empty}
:version-full-untagged: {major}.{minor}.{base}
:version-maintenance-android: {major}.{minor}.{maintenance-android}{empty}
:version-maintenance-c: {major}.{minor}.{maintenance-c}{empty}
:version-maintenance-net: {major}.{minor}.{maintenance-net}{empty}
:version-maintenance-java: {major}.{minor}.{maintenance-java}{empty}
:version-maintenance-ios: {major}.{minor}.{maintenance-ios}{empty}
:vs-version-maintenance-android: {vs-major}.{vs-minor}.{vs-maintenance-android}{empty}
:vs-version-maintenance-c: {vs-major}.{vs-minor}.{vs-maintenance-c}{empty}
:vs-version-maintenance-net: {vs-major}.{vs-minor}.{vs-maintenance-net}{empty}
:vs-version-maintenance-java: {vs-major}.{vs-minor}.{vs-maintenance-java}{empty}
:vs-version-maintenance-ios: {vs-major}.{vs-minor}.{vs-maintenance-ios}{empty}
:version-maintenance: {version}.{maintenance-ios}{empty}
:version-maintenance-hyphenated: {major}-{minor}-{maintenance-ios}{empty}

:vs-version-maintenance: {vs-version}.{vs-maintenance-ios}{empty}
:vs-version-maintenance-hyphenated: {vs-major}-{vs-minor}-{vs-maintenance-ios}{empty}


// :url-api-references-query-classes: https://docs.couchbase.com/mobile/{version-maintenance-ios}/couchbase-lite-swift/Classes/[Query Class index]


[Replicator.pendingDocumentIds()]


:version: {major}.{minor}
:vs-version: {vs-major}.{vs-minor}
:version-full: {major}.{minor}.{base}{empty}
:version-full-hyphenated: {major}-{minor}-{base}{empty}
:version-full-untagged: {major}.{minor}.{base}
:version-maintenance-android: {major}.{minor}.{maintenance-android}{empty}
:version-maintenance-c: {major}.{minor}.{maintenance-c}{empty}
:version-maintenance-net: {major}.{minor}.{maintenance-net}{empty}
:version-maintenance-java: {major}.{minor}.{maintenance-java}{empty}
:version-maintenance-ios: {major}.{minor}.{maintenance-ios}{empty}
:vs-version-maintenance-android: {vs-major}.{vs-minor}.{vs-maintenance-android}{empty}
:vs-version-maintenance-c: {vs-major}.{vs-minor}.{vs-maintenance-c}{empty}
:vs-version-maintenance-net: {vs-major}.{vs-minor}.{vs-maintenance-net}{empty}
:vs-version-maintenance-java: {vs-major}.{vs-minor}.{vs-maintenance-java}{empty}
:vs-version-maintenance-ios: {vs-major}.{vs-minor}.{vs-maintenance-ios}{empty}


[abstract]
--
Description -- _{description}_ +
Related Content -- xref:swift:querybuilder.adoc[QueryBuilder] |  xref:swift:query-n1ql-mobile.adoc[{sqlpp} for Mobile] |  xref:swift:querybuilder.adoc#lbl-predquery[Predictive Queries] | xref:swift:query-live.adoc[Live Queries] | xref:swift:indexing.adoc[Indexing]
--

// END -- DO NOT EDIT


[discrete#swift:query-resultsets:::query-execution]
=== Query Execution
The execution of a Couchbase Lite for Swift's database query returns an array of results, a result set.

Each row of the result set represents the data returned from a document that met the conditions defined by the `WHERE` statement of your query.
The composition of each row is determined by the `SelectResult` expressions provided in the `SELECT` statement.

[discrete#swift:query-resultsets:::lbl-rtnd-res]
=== Returned Results
<<swift:query-resultsets:::lbl-rtn-all>>
| <<swift:query-resultsets:::lbl-rtn-id>>
| <<swift:query-resultsets:::lbl-rtn-specific>>

The types of SelectResult formats you may encounter include those generated by :

* `QueryBuilder.select(SelectResult.all())` -- <<swift:query-resultsets:::lbl-rtn-all,Using All>>
* `QueryBuilder.select(SelectResult.expression(Meta.id))` -- <<swift:query-resultsets:::lbl-rtn-id,Using Doc Id>> Metadata such as the `_id`
* `QueryBuilder.select(SelectResult.property("myProp"))` -- <<swift:query-resultsets:::lbl-rtn-specific,Using Specific Properties>>


[discrete#swift:query-resultsets:::lbl-rtn-all]
==== Return All Document Properties
The SelectResult returned by `SelectResult.all()` is a dictionary object, with the database name as the key and the document properties as an array of key-value pairs

--
.Returning All Properties
[#swift:query-resultsets:::ex-result-id]
====
[pass:q,a[source, json, subs="+attributes, +macros"], role="no-callouts"]
----

[
  {
    "travel-sample": { // <.>
      "callsign": "MILE-AIR",
      "country": "United States",
      "iata": "Q5",
      "icao": "MLA",
      "id": 10,
      "name": "40-Mile Air",
      "type": "airline"
    }
  },
  {
    "travel-sample": { // <.>
      "callsign": "ALASKAN-AIR",
      "country": "United States",
      "iata": "AA",
      "icao": "AAA",
      "id": 10,
      "name": "Alaskan Airways",
      "type": "airline"
    }
  }
]


----
====
--


[discrete#swift:query-resultsets:::lbl-rtn-id]
==== Return Document Id Only
The SelectResult returned by queries using a SelectResult expression of the form `SelectResult.expression(Meta.id)` comprises a dictionary object with `ID` as the key and the ID value as the value.

--
.Returning Meta Properties -- Document ID
[#swift:query-resultsets:::ex-result-id]
====
[pass:q,a[source, json, subs="+attributes, +macros"]]
----

[
  {
    "id": "hotel123"
  },
  {
    "id": "hotel456"
  },
]

----
====
--


[discrete#swift:query-resultsets:::lbl-rtn-specific]
==== Return Specific Properties Only
The SelectResult returned by queries using one or more SelectResult expressions of the form `SelectResult.expression(property("name")) )` comprises a key-value pair for each SelectResult expression in the query.
The key being the property name.

--
.Returning Specific Properties
[#swift:query-resultsets:::ex-result-props]
====
[pass:q,a[source, json, subs="+attributes, +macros"], role="no-callouts"]
----

[
  { // <.>
    "id": "hotel123",
    "type": "hotel",
    "name": "Hotel Ghia"
  },
  { // <.>
    "id": "hotel456",
    "type": "hotel",
    "name": "Hotel Deluxe",
  }
]

----
====
--

[discrete#swift:query-resultsets:::lbl-process-resultset]
=== Processing Results
<<swift:query-resultsets:::lbl-acc-all>>
| <<swift:query-resultsets:::lbl-acc-id>>
| <<swift:query-resultsets:::lbl-acc-specific>>

To retrieve the results of your query,  you need to execute it using `Query.execute`.

The output from the execution is an array, with each array element representing the data from a document that matched your search criteria.

To unpack the results you need to iterate through this array.
Alternatively, you can convert the result to a JSON string -- see:


[discrete#swift:query-resultsets:::lbl-acc-all]
==== Access Document Properties - All Properties
Here we look at how to access document properties when you have used SelectResult.all.

In this case each array element is a dictionary structure with the database name as its key.
The properties are presented in the value as an array of key-value pairs (property name/property value).

You access the retrieved document properties by converting each row's value, in turn, to a dictionary -- as shown in <<swift:query-resultsets:::ex-acc-all>>.

[#ex-acc-all]
.Access All Properties


[#swift:query-resultsets:::ex-acc-all]
====


// Show Main Snippet
// include::swift:example$code_snippets/SampleCodeTest.swift[tags="query-access-all", indent=0]
[source, swift]
----
let results = try query.execute()
for row in results {
    let docsProps = row.dictionary(at: 0)! // <.>

    let docid = docsProps.string(forKey: "id")!
    let name = docsProps.string(forKey: "name")!
    let type = docsProps.string(forKey: "type")!
    let city = docsProps.string(forKey: "city")!

    print("\(docid): \(name), \(type), \(city)")
    let hotel = row.dictionary(at: 0)!  //<.>
    guard let hotelId = hotel.string(forKey: "id") else {
        continue
    }

    hotels[hotelId] = hotel
}

----


====

<.> Here we get the dictionary of document properties using the database name as the key.
You can add this dictionary to an array of returned matches, for processing elsewhere in the app.
<.> Alternatively, you can access the document properties here, by using the property names as keys to the dictionary object.

[discrete#swift:query-resultsets:::lbl-acc-id]
==== Access Document Properties - ID
Here we look at how to access document properties when you have returned only the document IDs for documents that matched your selection criteria.

This is something you may do when retrieval of the properties directly by the query may consume excessive amounts of memory and-or processing time.

In this case each array element is a dictionary structure where `ID` is the key and the required document ID is the value.

Access the required document properties by retrieving the document from the database using its document ID -- as shown in <<swift:query-resultsets:::ex-acc-id>>.

[#ex-acc-id]
.Access by ID


[#swift:query-resultsets:::ex-acc-id]
====


// Show Main Snippet
// include::swift:example$code_snippets/SampleCodeTest.swift[tags="query-access-id", indent=0]
[source, swift]
----
let results = try query.execute()
for result in results {

    print(result.toDictionary())

    let docId = result.string(forKey: "metaId")! // <.>
    print("Document Id is -- \(docId)")

    // Now you can get the document using the ID
    if let doc = try collection.document(id: docId) {
        let hotelId = doc.string(forKey: "id")!
        let name = doc.string(forKey: "name")!
        let city = doc.string(forKey: "city")!
        let type = doc.string(forKey: "type")!

        // ... process document properties as required
        print("Result properties are: \(hotelId), \(name), \(city), \(type)")
    }
}
----


====

<.> Extract the Id value from the dictionary and use it to get the document from the database


[discrete#swift:query-resultsets:::lbl-acc-specific]
==== Access Document Properties - Selected Properties
Here we look at how to access properties when you have used SelectResult to get a specific subset of properties.

In this case each array element is an array of key value pairs (property name/property value).

Access the retrieved properties by converting each row into a dictionary -- as shown in <<swift:query-resultsets:::ex-acc-specific>>.

[#ex-acc-specific]


[#swift:query-resultsets:::ex-acc-specific]
====


// Show Main Snippet
// include::swift:example$code_snippets/SampleCodeTest.swift[tags="query-access-props", indent=0]
[source, swift]
----
for result in try! query.execute() {
    let docID = result.string(forKey: "metaId")!
    print("processing doc: \(docID)")

    let id = result.string(forKey: "id")!
    var hotel = Hotel(id: id)
    hotel.name = result.string(forKey: "name")
    hotel.city = result.string(forKey: "city")
    hotel.type = result.string(forKey: "type")
    hotels[id] = hotel
} // end for

----


====


[discrete#swift:query-resultsets:::json-result-sets]
=== JSON Result Sets

[#ex-json]
.Using JSON Results


[#swift:query-resultsets:::ex-json]
====

pass:q,a[Use https://docs.couchbase.com/mobile/{version-maintenance-ios}/couchbase-lite-swift/Classes/Result.html#/s:18CouchbaseLiteSwift6ResultC6toJSONSSyF[result.toJSON()] to transform your result string into a JSON string, which can easily be serialized or used as required in your application. See <<swift:query-resultsets:::ex-json>> for a working example.]

// Show Main Snippet
// include::swift:example$code_snippets/SampleCodeTest.swift[tags="query-access-json", indent=0]
[source, swift]
----

// In this example the Hotel class is defined using Codable
//
// class Hotel : Codable {
//   var id : String = "undefined"
//   var type : String = "hotel"
//   var name : String = "undefined"
//   var city : String = "undefined"
//   var country : String = "undefined"
//   var description : String? = ""
//   var text : String? = ""
//   ... other class content
// }

let results = try query.execute()
for row in  results {

    // get the result into a JSON String
    let jsonString = row.toJSON()

    let thisJsonObj:Dictionary =
    try (JSONSerialization.jsonObject(
        with: jsonString.data(using: .utf8)!,
        options: .allowFragments)
         as? [String: Any])!

    // Use Json Object to populate Native object
    // Use Codable class to unpack JSON data to native object
    var this_hotel: Hotel = try JSONDecoder().decode(Hotel.self, from: jsonString.data(using: .utf8)!) // <.>

    // ALTERNATIVELY unpack in steps
    this_hotel.id = thisJsonObj["id"] as! String
    this_hotel.name = thisJsonObj["name"] as? String
    this_hotel.type = thisJsonObj["type"] as? String
    this_hotel.city = thisJsonObj["city"] as? String
    hotels[this_hotel.id] = this_hotel

} // end for

----


====


.JSON String Format
[#swift:query-resultsets:::ex-json-format]
If your query selects ALL then the JSON format will be:

[source, JSON]
----
{
  database-name: {
    key1: "value1",
    keyx: "valuex"
  }
}
----

If your query selects a sub-set of available properties then the JSON format will be:

[source, JSON]
----
{
  key1: "value1",
  keyx: "valuex"
}
----


// BEGIN -- DO NOT EDIT


[discrete#swift:query-resultsets:::related-content]
=== Related Content
++++
<div class="card-row three-column-row">
++++

[.column]
==== {empty}
.How to . . .
* xref:swift:gs-prereqs.adoc[Prerequisites]
* xref:swift:gs-install.adoc[Install]
* xref:swift:gs-build.adoc[Build and Run]


.

[discrete.colum#swift:query-resultsets:::-2n]
==== {empty}
.Learn more . . .
* xref:swift:database.adoc[Databases]
* xref:swift:document.adoc[Documents]
* xref:swift:blob.adoc[Blobs]
* xref:swift:replication.adoc[Remote Sync Gateway]
* xref:swift:conflict.adoc[Handling Data Conflicts]

.


[discrete.colum#swift:query-resultsets:::-3n]
==== {empty}
.Dive Deeper . . .
https://forums.couchbase.com/c/mobile/14[Mobile Forum] |
https://blog.couchbase.com/[Blog] |
https://docs.couchbase.com/tutorials/[Tutorials]

.


++++
</div>
++++

// END -- DO NOT EDIT


