:docname: query-resultsets
:page-module: swift
:page-relative-src-path: query-resultsets.adoc
:page-origin-url: https://github.com/couchbase/docs-couchbase-lite.git
:page-origin-start-path:
:page-origin-refname: antora-assembler-simplification
:page-origin-reftype: branch
:page-origin-refhash: (worktree)
[#swift:query-resultsets:::]
=== Query Resultsets
:page-role:
:description: How to use Couchbase Lite Query's Result Sets
:keywords: query, sql, n1ql, fuzzy-matching



// BEGIN -- inclusion -- {module-partials}_define_module_attributes.adoc
//  Usage:  Here we define module specific attributes. It is invoked during the compilation of a page,
//          making all attributes available for use on the page.
//  UsedBy: ROOT:partial$_std_cbl_hdr.adoc

// BEGIN::module page attributes
//
// CBL-Swift Maintenance release number
//

// VECTOR SEARCH attributes
//




// BEGIN - Set attributes pointing to API references for this module

// API Reference Links
//
//




// Supporting Data Type Classes


// DATABASE CLASSES






// Begin -- DatabaseConfiguration
// End -- DatabaseConfiguration




// deprecated 2.8
//
// :url-api-method-database-compact: https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-ios}{empty}/couchbase-lite-swift/Classes/Database.html#/s:18CouchbaseLiteSwift8DatabaseC7compactyyKF[Database.compact()]








// links for documents pages






// QUERY RELATED CLASSES and METHODS

// Query class and methods

// Expression class and methods
// :url-api-references-query-classes: https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-ios}{empty}/couchbase-lite-swift/Classes/[Query Class index]



// ArrayFunction class and methods


// API Results Class and methods


// Function class and methods
//

// Where class and methods
//

// orderby class and methods
//

// GroupBy class and methods
//

// URLEndpointConfiguration




















// diag: Env+Module swift




// Replicator API




[Replicator.pendingDocumentIds()]



// Replicator Status



// :url-api-enum-replicator-status: https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-ios}{empty}/couchbase-lite-swift/Classes/Replicator/Status.html[Status struct]
// :url-api-enum-replicator-activity: https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-ios}{empty}/couchbase-lite-swift/Classes/Replicator/ActivityLevel.html[ActivityLevel enum]
// :url-api-enum-replicator-progress: https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-ios}{empty}/couchbase-lite-swift/Classes/Replicator/Progress.html[Progress struct]


// ReplicatorConfiguration API









// Begin Replicator Retry Config



// :url-api-prop-replicator-config-ServerCertificateVerificationMode: https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-ios}{empty}/couchbase-lite-swift/Structs/ReplicatorConfiguration.html#/s:18CouchbaseLiteSwift23ReplicatorConfigurationC33serverCertificateVerificationModeAA06ServerghI0Ovp[serverCertificateVerificationMode]

// :url-api-enum-replicator-config-ServerCertificateVerificationMode: https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-ios}{empty}/couchbase-lite-swift/Structs/ReplicatorConfiguration.html{Enums/ServerCertificateVerificationMode.html[serverCertificateVerificationMode enum]













// Metadata API



// BEGIN Logs and logging references







// END  Logs and logging references



// End define module specific attributes

// BEGIN::module page attributes
// :snippet-p2psync-ws: {snippets-p2psync-ws--swift}

// END::Local page attributes

[abstract]
--
Description -- _{description}_ +
Related Content -- xref:swift:querybuilder.adoc[QueryBuilder] |  xref:swift:query-n1ql-mobile.adoc[{sqlpp} for Mobile] |  xref:swift:querybuilder.adoc#lbl-predquery[Predictive Queries] | xref:swift:query-live.adoc[Live Queries] | xref:swift:indexing.adoc[Indexing]
--

// END -- DO NOT EDIT

// BEGIN -- inclusion -- common-query-resultsets.adoc
//  Purpose -- describes the use of the query's resultset
//
// // BEGIN::REQUIRED EXTERNALS
// :this-module: {par-module}
// :this-lang-title: {par-lang-title}
// :this-packageNm: {par-packageNm}
// :this-source-language: {par-source-language}
// snippet: {par-snippet}
//:this-url-issues: {par-url-issues}
// END::REQUIRED EXTERNALS

// BEGIN::Local page attributes

// END::Local page attributes


[discrete#swift:query-resultsets:::query-execution]
==== Query Execution
The execution of a Couchbase Lite for Swift's database query returns an array of results, a result set.

Each row of the result set represents the data returned from a document that met the conditions defined by the `WHERE` statement of your query.
The composition of each row is determined by the `SelectResult` expressions provided in the `SELECT` statement.

[discrete#swift:query-resultsets:::lbl-rtnd-res]
==== Returned Results
<<swift:query-resultsets:::lbl-rtn-all>>
| <<swift:query-resultsets:::lbl-rtn-id>>
| <<swift:query-resultsets:::lbl-rtn-specific>>

The types of SelectResult formats you may encounter include those generated by :

* `QueryBuilder.select(SelectResult.all())` -- <<swift:query-resultsets:::lbl-rtn-all,Using All>>
* `QueryBuilder.select(SelectResult.expression(Meta.id))` -- <<swift:query-resultsets:::lbl-rtn-id,Using Doc Id>> Metadata such as the `_id`
* `QueryBuilder.select(SelectResult.property("myProp"))` -- <<swift:query-resultsets:::lbl-rtn-specific,Using Specific Properties>>


[discrete#swift:query-resultsets:::lbl-rtn-all]
===== Return All Document Properties
The SelectResult returned by `SelectResult.all()` is a dictionary object, with the database name as the key and the document properties as an array of key-value pairs

--
.Returning All Properties
[#swift:query-resultsets:::ex-result-id]
====
[pass:q,a[source, json, subs="+attributes, +macros"], role="no-callouts"]
----

[
  {
    "travel-sample": { // <.>
      "callsign": "MILE-AIR",
      "country": "United States",
      "iata": "Q5",
      "icao": "MLA",
      "id": 10,
      "name": "40-Mile Air",
      "type": "airline"
    }
  },
  {
    "travel-sample": { // <.>
      "callsign": "ALASKAN-AIR",
      "country": "United States",
      "iata": "AA",
      "icao": "AAA",
      "id": 10,
      "name": "Alaskan Airways",
      "type": "airline"
    }
  }
]


----
====
--


[discrete#swift:query-resultsets:::lbl-rtn-id]
===== Return Document Id Only
The SelectResult returned by queries using a SelectResult expression of the form `SelectResult.expression(Meta.id)` comprises a dictionary object with `ID` as the key and the ID value as the value.

--
.Returning Meta Properties -- Document ID
[#swift:query-resultsets:::ex-result-id]
====
[pass:q,a[source, json, subs="+attributes, +macros"]]
----

[
  {
    "id": "hotel123"
  },
  {
    "id": "hotel456"
  },
]

----
====
--


[discrete#swift:query-resultsets:::lbl-rtn-specific]
===== Return Specific Properties Only
The SelectResult returned by queries using one or more SelectResult expressions of the form `SelectResult.expression(property("name")) )` comprises a key-value pair for each SelectResult expression in the query.
The key being the property name.

--
.Returning Specific Properties
[#swift:query-resultsets:::ex-result-props]
====
[pass:q,a[source, json, subs="+attributes, +macros"], role="no-callouts"]
----

[
  { // <.>
    "id": "hotel123",
    "type": "hotel",
    "name": "Hotel Ghia"
  },
  { // <.>
    "id": "hotel456",
    "type": "hotel",
    "name": "Hotel Deluxe",
  }
]

----
====
--

[discrete#swift:query-resultsets:::lbl-process-resultset]
==== Processing Results
<<swift:query-resultsets:::lbl-acc-all>>
| <<swift:query-resultsets:::lbl-acc-id>>
| <<swift:query-resultsets:::lbl-acc-specific>>

To retrieve the results of your query,  you need to execute it using `Query.execute`.

The output from the execution is an array, with each array element representing the data from a document that matched your search criteria.

To unpack the results you need to iterate through this array.
Alternatively, you can convert the result to a JSON string -- see:


[discrete#swift:query-resultsets:::lbl-acc-all]
===== Access Document Properties - All Properties
Here we look at how to access document properties when you have used SelectResult.all.

In this case each array element is a dictionary structure with the database name as its key.
The properties are presented in the value as an array of key-value pairs (property name/property value).

You access the retrieved document properties by converting each row's value, in turn, to a dictionary -- as shown in <<swift:query-resultsets:::ex-acc-all>>.

[#ex-acc-all]
.Access All Properties
// BEGIN inclusion -- block -- block_tabbed_code_example.adoc
//
//  Allows for abstraction of the showing of snippet examples
//  which makes displaying tabbed snippets for platforms with
//  more than one native language to show -- Android (Kotlin and Java)
//
// Surrounds code in Example block
//
//  PARAMETERS:
//    param-tags comma-separated list of tags to include/exclude
//    param-leader text for opening para of an example block
//
//  USE:
//    :param_tags: query-access-json
//    include::partial$block_show_snippet.adoc[]
//    :param_tags!:
//

[#swift:query-resultsets:::ex-acc-all]
====


// Show Main Snippet
[source, swift]
----
include ::swift:example$code_snippets/SampleCodeTest.swift[tags="query-access-all", indent=0]
let results = try query.execute()
for row in results {
    let docsProps = row.dictionary(at: 0)! // <.>

    let docid = docsProps.string(forKey: "id")!
    let name = docsProps.string(forKey: "name")!
    let type = docsProps.string(forKey: "type")!
    let city = docsProps.string(forKey: "city")!

    print("\(docid): \(name), \(type), \(city)")
    let hotel = row.dictionary(at: 0)!  //<.>
    guard let hotelId = hotel.string(forKey: "id") else {
        continue
    }

    hotels[hotelId] = hotel
}

----




// close example block

====

// Tidy-up atttibutes created
// END -- block_show_snippet.doc
<.> Here we get the dictionary of document properties using the database name as the key.
You can add this dictionary to an array of returned matches, for processing elsewhere in the app.
<.> Alternatively, you can access the document properties here, by using the property names as keys to the dictionary object.

// ====
// [source, swift, subs="+attributes, +macros"]
// ----
// let yourQuery = QueryBuilder.select(SelectResult.all)
//             .from(DataSource.database(yourDb))

// for dataRow in try yourQuery.execute() {
//   if let yourDoc = dict[dataRow.toDictionary()] as? [String:Any] {
//       let docid = yourDoc["id"]
//       let name = yourDoc["name"]
//       let type = yourDoc["type"]
//       let city = yourDoc["city"]
//   }
// }

// ----
// ====


[discrete#swift:query-resultsets:::lbl-acc-id]
===== Access Document Properties - ID
Here we look at how to access document properties when you have returned only the document IDs for documents that matched your selection criteria.

This is something you may do when retrieval of the properties directly by the query may consume excessive amounts of memory and-or processing time.

In this case each array element is a dictionary structure where `ID` is the key and the required document ID is the value.

Access the required document properties by retrieving the document from the database using its document ID -- as shown in <<swift:query-resultsets:::ex-acc-id>>.

[#ex-acc-id]
.Access by ID
// BEGIN inclusion -- block -- block_tabbed_code_example.adoc
//
//  Allows for abstraction of the showing of snippet examples
//  which makes displaying tabbed snippets for platforms with
//  more than one native language to show -- Android (Kotlin and Java)
//
// Surrounds code in Example block
//
//  PARAMETERS:
//    param-tags comma-separated list of tags to include/exclude
//    param-leader text for opening para of an example block
//
//  USE:
//    :param_tags: query-access-json
//    include::partial$block_show_snippet.adoc[]
//    :param_tags!:
//

[#swift:query-resultsets:::ex-acc-id]
====


// Show Main Snippet
[source, swift]
----
include ::swift:example$code_snippets/SampleCodeTest.swift[tags="query-access-id", indent=0]
let results = try query.execute()
for result in results {

    print(result.toDictionary())

    let docId = result.string(forKey: "metaId")! // <.>
    print("Document Id is -- \(docId)")

    // Now you can get the document using the ID
    if let doc = try collection.document(id: docId) {
        let hotelId = doc.string(forKey: "id")!
        let name = doc.string(forKey: "name")!
        let city = doc.string(forKey: "city")!
        let type = doc.string(forKey: "type")!

        // ... process document properties as required
        print("Result properties are: \(hotelId), \(name), \(city), \(type)")
    }
}
----




// close example block

====

// Tidy-up atttibutes created
// END -- block_show_snippet.doc
<.> Extract the Id value from the dictionary and use it to get the document from the database

// .Access Properties using Doc ID
// ====
// [source, swift, subs="+attributes, +macros"]
// ----
// let yourQuery = QueryBuilder.select(SelectResult.expression(Meta.id))
//             .from(DataSource.database(yourDb))

// for dataRow in try yourQuery.execute() {
//   if let yourDocID = dict[dataRow["id"] {
//       let yourDoc = try yourDb.document(withID: yourDocId)
//       let name = yourDoc.name
//       let type = yourDoc.type
//       let city = yourDoc.city
//   }
// }

// ----
// ====


[discrete#swift:query-resultsets:::lbl-acc-specific]
===== Access Document Properties - Selected Properties
Here we look at how to access properties when you have used SelectResult to get a specific subset of properties.

In this case each array element is an array of key value pairs (property name/property value).

Access the retrieved properties by converting each row into a dictionary -- as shown in <<swift:query-resultsets:::ex-acc-specific>>.

[#ex-acc-specific]
// BEGIN inclusion -- block -- block_tabbed_code_example.adoc
//
//  Allows for abstraction of the showing of snippet examples
//  which makes displaying tabbed snippets for platforms with
//  more than one native language to show -- Android (Kotlin and Java)
//
// Surrounds code in Example block
//
//  PARAMETERS:
//    param-tags comma-separated list of tags to include/exclude
//    param-leader text for opening para of an example block
//
//  USE:
//    :param_tags: query-access-json
//    include::partial$block_show_snippet.adoc[]
//    :param_tags!:
//

[#swift:query-resultsets:::ex-acc-specific]
====


// Show Main Snippet
[source, swift]
----
include ::swift:example$code_snippets/SampleCodeTest.swift[tags="query-access-props", indent=0]
for result in try! query.execute() {
    let docID = result.string(forKey: "metaId")!
    print("processing doc: \(docID)")

    let id = result.string(forKey: "id")!
    var hotel = Hotel(id: id)
    hotel.name = result.string(forKey: "name")
    hotel.city = result.string(forKey: "city")
    hotel.type = result.string(forKey: "type")
    hotels[id] = hotel
} // end for

----




// close example block

====

// Tidy-up atttibutes created
// END -- block_show_snippet.doc


// [#ex-acc-all]
// .Access All Properties
// ====
// [source, swift, subs="+attributes, +macros"]
// ----
// let yoursearchQuery = QueryBuilder
//             .select(SelectResult.expression(Meta.id),
//                     SelectResult.expression(Expression.property("name")),
//                     SelectResult.expression(Expression.property("city")),
//                     SelectResult.expression(Expression.property("type")))
//             .from(DataSource.database(yourDb))

// for dataRow in try yourQuery.execute() {
//   if let yourDoc = dict[dataRow.toDictionary()] as? [String:Any] {
//       let docid = yourDoc["id"]
//       let name = yourDoc["name"]
//       let type = yourDoc["type"]
//   }
// }

// ----
// ====
// END -- inclusion -- common-query-resultsets.adoc

[discrete#swift:query-resultsets:::json-result-sets]
==== JSON Result Sets

// Inclusion block
[#ex-json]
.Using JSON Results
// BEGIN inclusion -- block -- block_tabbed_code_example.adoc
//
//  Allows for abstraction of the showing of snippet examples
//  which makes displaying tabbed snippets for platforms with
//  more than one native language to show -- Android (Kotlin and Java)
//
// Surrounds code in Example block
//
//  PARAMETERS:
//    param-tags comma-separated list of tags to include/exclude
//    param-leader text for opening para of an example block
//
//  USE:
//    :param_tags: query-access-json
//    include::partial$block_show_snippet.adoc[]
//    :param_tags!:
//

[#swift:query-resultsets:::ex-json]
====

pass:q,a[Use https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-ios}{empty}/couchbase-lite-swift/Classes/Result.html#/s:18CouchbaseLiteSwift6ResultC6toJSONSSyF[result.toJSON()] to transform your result string into a JSON string, which can easily be serialized or used as required in your application. See <<swift:query-resultsets:::ex-json>> for a working example.]

// Show Main Snippet
[source, swift]
----
include ::swift:example$code_snippets/SampleCodeTest.swift[tags="query-access-json", indent=0]

// In this example the Hotel class is defined using Codable
//
// class Hotel : Codable {
//   var id : String = "undefined"
//   var type : String = "hotel"
//   var name : String = "undefined"
//   var city : String = "undefined"
//   var country : String = "undefined"
//   var description : String? = ""
//   var text : String? = ""
//   ... other class content
// }

let results = try query.execute()
for row in  results {

    // get the result into a JSON String
    let jsonString = row.toJSON()

    let thisJsonObj:Dictionary =
    try (JSONSerialization.jsonObject(
        with: jsonString.data(using: .utf8)!,
        options: .allowFragments)
         as? [String: Any])!

    // Use Json Object to populate Native object
    // Use Codable class to unpack JSON data to native object
    var this_hotel: Hotel = try JSONDecoder().decode(Hotel.self, from: jsonString.data(using: .utf8)!) // <.>

    // ALTERNATIVELY unpack in steps
    this_hotel.id = thisJsonObj["id"] as! String
    this_hotel.name = thisJsonObj["name"] as? String
    this_hotel.type = thisJsonObj["type"] as? String
    this_hotel.city = thisJsonObj["city"] as? String
    hotels[this_hotel.id] = this_hotel

} // end for

----




// close example block

====

// Tidy-up atttibutes created
// END -- block_show_snippet.doc

.JSON String Format
[#swift:query-resultsets:::ex-json-format]
If your query selects ALL then the JSON format will be:

[source, JSON]
----
{
  database-name: {
    key1: "value1",
    keyx: "valuex"
  }
}
----

If your query selects a sub-set of available properties then the JSON format will be:

[source, JSON]
----
{
  key1: "value1",
  keyx: "valuex"
}
----


// BEGIN -- DO NOT EDIT
// :param-add3-title: {empty}
// :param-reference: reference-p2psync


[discrete#swift:query-resultsets:::related-content]
==== Related Content
++++
<div class="card-row three-column-row">
++++

[.column]
===== {empty}
.How to . . .
* xref:swift:gs-prereqs.adoc[Prerequisites]
* xref:swift:gs-install.adoc[Install]
* xref:swift:gs-build.adoc[Build and Run]


.

[discrete.colum#swift:query-resultsets:::-2n]
===== {empty}
.Learn more . . .
* xref:swift:database.adoc[Databases]
* xref:swift:document.adoc[Documents]
* xref:swift:blob.adoc[Blobs]
* xref:swift:replication.adoc[Remote Sync Gateway]
* xref:swift:conflict.adoc[Handling Data Conflicts]

.


[.column]
// [.content]
[discrete#swift:query-resultsets:::-3]
===== {empty}
.Dive Deeper . . .
//* Community
https://forums.couchbase.com/c/mobile/14[Mobile Forum] |
https://blog.couchbase.com/[Blog] |
https://docs.couchbase.com/tutorials/[Tutorials]


.



++++
</div>
++++

// END -- DO NOT EDIT


