= Reactive APIs
:page-status: Couchbase Lite 3.2.3
ifdef::show_edition[:page-edition: {release}]
ifdef::prerelease[:page-status: Couchbase Lite 3.2.3 {prerelease}]
:page-role:
:description: The Reactive APIs provide integration with SwiftUI, enabling reactive programming styles for concurrent user interface updates.
:keywords: reactive swiftui codable combine observation

:url-api-references: https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-swift}{empty}/couchbase-lite-swift

// Sets the correct mobile sdk for xref links in the common page
include::partial$_set_page_context_for_swift.adoc[]

[abstract]
{description}

The Reactive APIs enable you map Couchbase Lite documents directly to Swift models, and then bind a model to a view representing the user interface.
The user interface is automatically updated when the underlying data changes.

The Reactive APIs are available for Swift in Couchbase Lite 3.2.3 and later.

== Represent Documents as Codable Objects

Prior to the Reactive APIs, Couchbase Lite developers working with Swift could interact with documents through APIs that require manual handling of data conversion.
For example, reading and writing data would often involve using the Mutable Documents abstraction and working directly with dictionary representations.
While this approach provides flexibility, it can involve additional steps for developers when integrating Swift models into their applications.
For more information, see xref:swift:document.adoc[].

The Reactive APIs simplify this process by introducing native adherence to Swift's https://developer.apple.com/documentation/swift/codable[Codable] protocol.
This eliminates intermediate conversion layers, reducing the need to convert from Fleece format to JSON, and then to app-specific object representation.

=== Map Couchbase Lite Data to Swift Codable Document Models

A document model is a Swift Codable class used for encoding and decoding to and from a Couchbase Lite document.

The Reactive APIs provide the `@documentID` property wrapper.
This associates a model object with a document using the specified ID.
If no document ID is provided, one is automatically generated and assigned to the model when it is encoded and saved to the database.

To avoid multiple copies of the model from being associated with the same document, the document model is required to be a class rather than a struct.

.Data model
====
[source,swift]
----
class Task: Codable {
    @DocumentID var id: String?
    var title: String
    var completed: Bool
}
----
====

== Manipulate Documents as Codable Objects

The document-level APIs have been enhanced to enable automatic encoding and decoding between Couchbase Lite documents and Swift codable model objects.
You can retrieve documents from the collection as decodable model objects.
You can also save, delete, and purge model objects encoded as documents in the collection.

=== Get a Document as a Decodable Object

To get a document from a collection as a decodable model object:

* Use the `document` function with the collection.
* Specify the document ID and type.

====
[source,swift]
----
----
====

// FIXME: API link
For API details, see {url-api-references}/Classes/Collection.html#/Document%20Management[Document Management].

=== Save an Encodable Object as a Document

To save a document represented by an encodable model object into a collection:

* Use the `save` function with the collection.
* Specify the object.
* Optionally, specify a concurrency control or a conflict handler.
By default, last-write-wins concurrency control will be used if a conflict occurs.

====
[source,swift]
----
----
====

// FIXME: API link
For API details, see {url-api-references}/Classes/Collection.html#/Document%20Management[Document Management].

=== Delete a Document

To delete a document represented by an encodable model object from a collection:

* Use the `delete` function with the collection.
* Specify the object.
* Optionally, specify a concurrency control.
By default, last-write-wins concurrency control will be used if a conflict occurs.

====
[source,swift]
----
----
====

// FIXME: API link
For API details, see {url-api-references}/Classes/Collection.html#/Document%20Management[Document Management].

=== Purge a Document

To purge a document represented by an encodable model object from a collection:

* Use the `purge` function with the collection.
* Specify the object.

====
[source,swift]
----
----
====

// FIXME: API link
For API details, see {url-api-references}/Classes/Collection.html#/Document%20Management[Document Management].

== Decode Query Results

The Reactive APIs enable you to decode Couchbase {sqlpp} query results directly into model objects.
This makes queries observable, so that you can refresh the application automatically as the results change.

With prior solutions such as xref:swift:query-live.adoc[Live Queries], you need to trigger user interface updates manually inside the listener.
This can lead to complex and difficult-to-maintain state management.
With the Reactive APIs, you can use SwiftUI's minimalistic and declarative approach to manage querying and updating the user interface.

To make query results observable, the model object only needs to conform to the decodable protocol, and does not require a document ID property annotated with the `@DocumentID` property wrapper.
However, if you want to save the model to a collection later, it must include a document ID property with the `@DocumentID` property wrapper.
Additionally, the query result must include a document ID, which can be retrieved using the `meta().id` expression, as shown in <<ex-query-doc-id>>.

[#ex-query-doc-id]
.Query results with document ID
====
[source,sqlpp]
----
SELECT meta().id AS id, name FROM _default.users
----
====

=== Get a Query Result as Decodable

To get a query's result as a decodable model object:

* Use the `data` function with the query result.
* Specify the decodable model type.
* Optionally, specify a <<datakey,data key>>.

====
[source,swift]
----
----
====

// FIXME: API link
For API details, see {url-api-references}/Classes/Result.html#/ReadOnlyArrayProtocol[ReadOnlyArrayProtocol].

NOTE: When saving a document model decoded from the query's result, the document associated with the model will be retrieved during the save time.
As a result, the document may not be the same document during the query time if the document has been changed.

=== Get All Query Results as Decodable

To get all a query's results as an array of a decodable model objects:

* Use the `data` function with the query result set.
* Specify the decodable model type.
* Optionally, specify a <<datakey,data key>>.

====
[source,swift]
----
----
====

// FIXME: API link
For API details, see {url-api-references}/Classes/ResultSet.html[ResultSet].

WARNING: Getting all the query's results as an array of decodable model objects may take a long time and consume a large amount of memory, depending on the data size and the number of results.

[#datakey]
=== Specify a Data Key

If the query includes a wildcard (`{asterisk}`), you can provide an optional data key to the `data` function to specify the alias of the `{asterisk}` dictionary.
For instance, in <<ex-query-wildcard>>, the wildcard produces a dictionary with the alias `data`.

[#ex-query-wildcard]
.Query with a wildcard
====
[source,sqlpp]
SELECT meta().id AS id, * AS data FROM users
====

When using `data(as:, dataKey:)` to decode the query result, setting the data key to `data` ensures the correct source is used.

== Publish Change Notifications

To align with declarative programming paradigms, the Reactive APIs provide an efficient way to publish change notifications.
This allows for automatic updates to UI components, streamlined data pipelines, and improved code readability.

To publish change notifications, the Reactive APIs provide interoperability with two underlying Swift frameworks.
The way that you use the Reactive APIs differs slightly, depending on the underlying framework.
The framework that you use depends on your operating system version.

* The https://developer.apple.com/documentation/combine[Combine] framework is available in iOS 13 and later, and macOS 10.15 to 14.
* The https://developer.apple.com/documentation/observation[Observation] framework is available in iOS 17 and later, and macOS 14 and later.

=== Publish Query Result Changes

To get a publisher that emits `QueryChange` events whenever a query result changes:

* Use the `changePublisher` function with the query.
* Optionally, specify the dispatch queue on which the changes are to be delivered.
By default, the main queue is used.

====
[source,swift]
----
----
====

// FIXME: API link
For API details, see {url-api-references}/Classes/Query.html[Query].

NOTE: The emitted `QueryChange` contains the entire new result set of the query, not just the delta.

=== Publish Document Changes

To get a publisher that emits `CollectionChange` events whenever documents in a collection change:

* Use the `changePublisher` function with the collection.
* Optionally, specify the dispatch queue on which the changes are to be delivered.
By default, the main queue is used.

====
[source,swift]
----
----
====

// FIXME: API link
For API details, see {url-api-references}/Classes/Collection.html#/Combine%20Publisher[Combine Publisher].

To get a publisher that emits `DocumentChange` events whenever a specific document in a collection changes:

* Use the `documentChangePublisher` function with the collection.
* Specify the document ID.
* Optionally, specify the dispatch queue on which the changes are to be delivered.
By default, the main queue is used.

====
[source,swift]
----
----
====

// FIXME: API link
For API details, see {url-api-references}/Classes/Collection.html#/Combine%20Publisher[Combine Publisher].

=== Publish Replicator Changes

To get a publisher that emits `ReplicatorChange` events when a replicator's status changes:

* Use the `changePublisher` function with the replicator.
* Optionally, specify the dispatch queue on which the changes are to be delivered.
By default, the main queue is used.

====
[source,swift]
----
----
====

// FIXME: API link
For API details, see {url-api-references}/Classes/Replicator.html#/Combine%20Publisher[Combine Publisher].

To get a publisher that emits `DocumentReplication` events whenever documents are pushed or pulled during replication:

* Use the `documentReplicationPublisher` function with the replicator.
* Optionally, specify the dispatch queue on which the changes are to be delivered.
By default, the main queue is used.

====
[source,swift]
----
----
====

// FIXME: API link
For API details, see {url-api-references}/Classes/Replicator.html#/Combine%20Publisher[Combine Publisher].

== Examples

=== ViewModel

[tabs]
====
Combine Framework::
+
--
For iOS 13 and later, or macOS 10.15 to 14:

[source,swift]
----
@MainActor
class TodoViewModel: ObservableObject {
   @Published var todos: [Task] = []

   private let db: Database
   private let tasks: Collection
   private var cancellables = Set<AnyCancellable>()

   init() {
       self.db = AppDataStore.shared.database
       self.tasks = db.collection(name: "tasks")


       let query = "SELECT meta().id, title, completed from tasks"
       try? db.createQuery(query).publish()
           .map { $0.results?.data(as: Task.self) ?? [] }
           .sink { [weak self] tasks in self?.todos = tasks }
           .store(in: &cancellables)
   }

   func addTask(title: String) throws {
       try tasks.save(from: Task(title: title))
   }
  
   func toggleCompletion(for task: Task) throws {
       if let index = todos.firstIndex(where: { $0.id == task.id }) {
           todos[index].completed.toggle() // Reflect UI right away
           try tasks.save(from: todos[index])
       }
   }
  
   func deleteTask(_ task: Task) throws {
       try tasks.delete(for: task)
   }
}
----
--

Observation Framework::
+
--
For iOS 17 and later, or macOS 14 and later:

[source,swift]
----
@Observable class TodoViewModel {
    var todos: [Task] = []    // Observable property automatically tracked by SwiftUI

    private let db: Database
    private let tasks: Collection

    init() {
        self.db = AppDataStore.shared.database
        self.tasks = db.collection(name: "tasks")

        let query = "SELECT meta().id, title, completed FROM tasks"
        
        // Subscribe to changes and update todos directly
        try? db.createQuery(query).publish()
            .map { $0.results?.data(as: Task.self) ?? [] }
            .sink { [weak self] tasks in
                self?.todos = tasks
            }
    }

    func addTask(title: String) throws {
        try tasks.save(from: Task(title: title, completed: false))
    }
  
    func toggleCompletion(for task: Task) throws {
        if let index = todos.firstIndex(where: { $0.id == task.id }) {
            todos[index].completed.toggle()
            try tasks.save(from: todos[index])
        }
    }
  
    func deleteTask(_ task: Task) throws {
        try tasks.delete(for: task)
    }
}
----
--
====

=== View

[tabs]
====
Combine Framework::
+
--
For iOS 13 and later, or macOS 10.15 to 14:

[source,swift]
----
​​struct TodoListView: View {
    @StateObject private var viewModel = TodoViewModel()

    var body: some View {
        List {
            ForEach(viewModel.todos) { task in
                HStack {
                    Text(task.title)
                    Spacer()
                    Button(action: {
                        try? viewModel.toggleCompletion(for: task)
                    }) {
                        Image(systemName: task.completed ? "checkmark" : "circle")
                            .foregroundColor(task.completed ? .green : .gray)
                    }
                }
            }
            .onDelete { indexSet in
                indexSet.forEach { index in
                    let task = viewModel.todos[index]
                    try? viewModel.deleteTask(task)
                }
            }
        }
        .toolbar {
            ToolbarItem(placement: .navigationBarTrailing) {
                Button(action: { try? viewModel.addTask(title: "New Task") }) {
                    Image(systemName: "plus")
                }
            }
        }
    }
}
----
--

Observation Framework::
+
--
For iOS 17 and later, or macOS 14 and later:

[source,swift]
----
​struct TodoView: View {
    @State var viewModel = TodoViewModel()
    @State private var newTaskTitle = ""

    var body: some View {
        VStack {
            TextField("New Task", text: $newTaskTitle)
                .textFieldStyle(.roundedBorder)
                .padding()
            
            Button("Add") {
                guard !newTaskTitle.isEmpty else { return }
                try? viewModel.addTask(title: newTaskTitle)
                newTaskTitle = ""
            }

            List(viewModel.todos, id: \.id) { task in
                HStack {
                    Button(action: { try? viewModel.toggleCompletion(for: task) }) {
                        Image(systemName: task.completed ? "checkmark.circle.fill" : "circle")
                    }

                    Text(task.title)
                        .strikethrough(task.completed)

                    Spacer()

                    Button(action: { try? viewModel.deleteTask(task) }) {
                        Image(systemName: "trash")
                    }
                }
            }
        }
        .padding()
    }
}
----
--
====

== See Also

* xref:swift:scopes-collections-manage.adoc[]
* xref:swift:document.adoc[]
* xref:swift:query-resultsets.adoc[]
* xref:swift:conflict.adoc[]
