
= Reactive APIs
:page-status: Couchbase Lite 3.2.3
:page-role:
:description: The Reactive APIs are enhanced APIs for Swift that streamline data modeling and enable reactive programming patterns.
:keywords: reactive swiftui codable combine observation


// Sets the correct mobile sdk for xref links in the common page

:source-language: swift

:source-language: swift


[abstract]
{description}

The Reactive APIs are designed for developers building apps with SwiftUI, Combine, or Swift's new Observation framework.
They provide two tightly integrated capabilities:

* *Codable protocol compatibility* -- enables automatic mapping between Couchbase Lite documents and Swift model objects using the https://developer.apple.com/documentation/swift/codable[Codable] protocol, reducing boilerplate and improving type safety.

* *Change publishers* -- provides https://developer.apple.com/documentation/combine[Combine] and https://developer.apple.com/documentation/observation[Observation] publishers for observing changes to queries, documents, and collections, enabling SwiftUI views and view models to react automatically to underlying data updates.

Together, these APIs allow developers to define Swift classes that can be directly persisted as Couchbase Lite documents and observed for changes in a reactive UI context.
They eliminate the need for manual dictionary manipulation, JSON conversion, or explicit change listeners.

The Reactive APIs are available for Swift in Couchbase Lite 3.2.3 and later.

[#represent-documents-as-codable-model-objects]
== Represent Documents as Codable Model Objects

Prior to the Reactive APIs, Couchbase Lite developers working with Swift could interact with documents through APIs that require manual handling of data conversion.
For example, reading and writing data would often involve using the Mutable Documents abstraction and working directly with dictionary representations.
While this approach provides flexibility, it can involve additional steps for developers when integrating Swift models into their applications.
For more information, see xref:swift:document.adoc[].

The Reactive APIs simplify this process by introducing native adherence to the https://developer.apple.com/documentation/swift/codable[Codable] protocol.
This eliminates intermediate conversion layers, reducing the need to convert from Fleece format to JSON, and then to app-specific object representation.

[#map-couchbase-lite-data-to-swift-codable-document-models]
=== Map Couchbase Lite Data to Swift Codable Document Models

A *document model* is a Swift class that conforms to Codable and includes an optional property annotated with `@DocumentID`.
This special property wrapper associates the model with a Couchbase Lite document via its unique document ID.

If no document ID is provided, Couchbase Lite generates a new one automatically and assigns to the model when it is encoded and saved.

NOTE: Document models must be declared as classes, not structs.
This ensures reference semantics and avoids issues where multiple in-memory objects point to the same document.

.Data model
====
[source,swift]
----
include::swift:example$code_snippets/CodableCombine.swift[tags="codable-data-model", indent=0]
----
====

[#manipulate-documents-as-codable-model-objects]
== Manipulate Documents as Codable Model Objects

Once defined, document models can be persisted, retrieved, and removed using type-safe APIs on the Collection object.

[#get-a-document-as-a-decodable-object]
=== Get a Document as a Decodable Object

To get a document from a collection and decode it into a Swift model:

* Use the `document` function with the collection.
* Specify the document ID and type.

====
[source,swift]
----
include::swift:example$code_snippets/CodableCombine.swift[tags="get-codable-doc", indent=0]
----
====

For API details, see https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-ios}{empty}/couchbase-lite-swift/Classes/Collection.html#/Document%20Management[Document Management].

[#save-an-encodable-object-as-a-document]
=== Save an Encodable Object as a Document

To save a document represented by a Swift model object into a collection:

* Use the `save` function with the collection.
* Specify the object.
* Optionally, specify a conflict handler or a concurrency control.
By default, last-write-wins concurrency control will be used if a conflict occurs.

====
[source,swift]
----
include::swift:example$code_snippets/CodableCombine.swift[tags="save-codable-doc", indent=0]
----

.Specify a conflict handler
[source,swift]
----
include::swift:example$code_snippets/CodableCombine.swift[tags="conflict-save-codable-doc", indent=0]
----

.Specify concurrency control
[source,swift]
----
include::swift:example$code_snippets/CodableCombine.swift[tags="concurrency-save-codable-doc", indent=0]
----
====

For API details, see https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-ios}{empty}/couchbase-lite-swift/Classes/Collection.html#/Document%20Management[Document Management].

[#delete-a-document]
=== Delete a Document

To remove a document represented by a Swift model object from a collection:

* Use the `delete` function with the collection.
* Specify the object.
* Optionally, specify a concurrency control.
By default, last-write-wins concurrency control will be used if a conflict occurs.

====
[source,swift]
----
include::swift:example$code_snippets/CodableCombine.swift[tags="delete-codable-doc", indent=0]
----

.Specify concurrency control
[source,swift]
----
include::swift:example$code_snippets/CodableCombine.swift[tags="concurrency-delete-codable-doc", indent=0]
----
====

For API details, see https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-ios}{empty}/couchbase-lite-swift/Classes/Collection.html#/Document%20Management[Document Management].

[#purge-a-document]
=== Purge a Document

Purging a document is permanent deletion, not replicated.

To purge a document represented by a Swift model object from a collection:

* Use the `purge` function with the collection.
* Specify the object.

====
[source,swift]
----
include::swift:example$code_snippets/CodableCombine.swift[tags="purge-codable-doc", indent=0]
----
====

For API details, see https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-ios}{empty}/couchbase-lite-swift/Classes/Collection.html#/Document%20Management[Document Management].

[#decode-query-results]
== Decode Query Results

The Reactive APIs enable you to decode Couchbase {sqlpp} query results directly into model objects.
This makes queries observable, so that you can refresh the application automatically as the results change.

With prior solutions such as xref:swift:query-live.adoc[], you need to trigger user interface updates manually inside the listener.
This can lead to complex and difficult-to-maintain state management.
With the Reactive APIs, you can use SwiftUI's minimalistic and declarative approach to manage querying and updating the user interface.

To make query results observable, the model object only needs to conform to the decodable protocol, and does not require a document ID property annotated with the `@DocumentID` property wrapper.

However, if you wish to save any result later, the decoding model must include a document ID property with the `@DocumentID` property wrapper.
Additionally, the query result must include a document ID, which can be retrieved using the `meta().id` expression, as shown in xref:swift:reactive.adoc#ex-query-doc-id[].

[#ex-query-doc-id]
.Query results with document ID
====
[source,sqlpp]
----
SELECT meta().id AS id, title FROM _default.tasks
----
====

[#get-a-query-result-as-decodable]
=== Get a Query Result as Decodable

To get a query's result as a decodable model object:

* Use the `data` function with the query result.
* Specify the decodable model type.
* Optionally, specify a xref:swift:reactive.adoc#datakey[data key].

====
[source,swift]
----
include::swift:example$code_snippets/CodableCombine.swift[tags="get-codable-result", indent=0]
----
====

For API details, see https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-ios}{empty}/couchbase-lite-swift/Classes/Result.html#/ReadOnlyArrayProtocol[ReadOnlyArrayProtocol].

NOTE: When saving a document model decoded from the query's result, the document associated with the model will be retrieved during the save time.
As a result, the document may not be the same document during the query time if the document has been changed.

[#get-all-query-results-as-decodable]
=== Get All Query Results as Decodable

To get all a query's results as an array of a decodable model objects:

* Use the `data` function with the query result set.
* Specify the decodable model type.
* Optionally, specify a xref:swift:reactive.adoc#datakey[data key].

====
[source,swift]
----
include::swift:example$code_snippets/CodableCombine.swift[tags="get-codable-result-all", indent=0]
----
====

For API details, see https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-ios}{empty}/couchbase-lite-swift/Classes/ResultSet.html[ResultSet].

WARNING: Getting all the query's results as an array of decodable model objects may take a long time and consume a large amount of memory, depending on the data size and the number of results.

[#datakey]
=== Specify a Data Key

If the query includes a wildcard (`{asterisk}`), you can provide an optional data key to the `data` function to specify the alias of the `{asterisk}` dictionary.
For instance, in xref:swift:reactive.adoc#ex-query-wildcard[], the wildcard produces a dictionary with the alias `data`.

[#ex-query-wildcard]
.Query with a wildcard
====
[source,sqlpp]
SELECT meta().id AS id, * AS data FROM _default.tasks
====

When using `data(as:, dataKey:)` to decode the query result, setting the data key to `data` ensures the correct source is used.

[#publish-change-notifications]
== Publish Change Notifications

To align with declarative programming paradigms, the Reactive APIs provide an efficient way to publish change notifications.
This allows for automatic updates to UI components, streamlined data pipelines, and improved code readability.

To publish change notifications, the Reactive APIs provide interoperability with two underlying Swift frameworks.
The way that you use the Reactive APIs differs slightly, depending on the underlying framework.
The framework that you use depends on your operating system version.

* The https://developer.apple.com/documentation/combine[Combine] framework is available in iOS 13 and later, and macOS 10.15 to 14.
* The https://developer.apple.com/documentation/observation[Observation] framework is available in iOS 17 and later, and macOS 14 and later.

[#publish-query-result-changes]
=== Publish Query Result Changes

To get a publisher that emits `QueryChange` events whenever a query result changes:

* Use the `changePublisher` function with the query.
* Optionally, specify the dispatch queue on which the changes are to be delivered.
By default, the main queue is used.

====
[source,swift]
----
include::swift:example$code_snippets/CodableCombine.swift[tags="publish-result-changes", indent=0]
----
====

For API details, see https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-ios}{empty}/couchbase-lite-swift/Classes/Query.html[Query].

NOTE: The emitted `QueryChange` contains the entire new result set of the query, not just the delta.

[#publish-document-changes]
=== Publish Document Changes

To get a publisher that emits `CollectionChange` events whenever any documents are added, removed or changed in that collection:

* Use the `changePublisher` function with the collection.
* Optionally, specify the dispatch queue on which the changes are to be delivered.
By default, the main queue is used.

====
[source,swift]
----
include::swift:example$code_snippets/CodableCombine.swift[tags="publish-collection-changes", indent=0]
----
====

For API details, see https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-ios}{empty}/couchbase-lite-swift/Classes/Collection.html#/Combine%20Publisher[Combine Publisher].

To get a publisher that emits `DocumentChange` events whenever a specific document in a collection changes:

* Use the `documentChangePublisher` function with the collection.
* Specify the document ID.
* Optionally, specify the dispatch queue on which the changes are to be delivered.
By default, the main queue is used.

====
[source,swift]
----
include::swift:example$code_snippets/CodableCombine.swift[tags="publish-doc-changes", indent=0]
----
====

For API details, see https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-ios}{empty}/couchbase-lite-swift/Classes/Collection.html#/Combine%20Publisher[Combine Publisher].

[#publish-replicator-changes]
=== Publish Replicator Changes

To get a publisher that emits `ReplicatorChange` events when a replicator's status changes:

* Use the `changePublisher` function with the replicator.
* Optionally, specify the dispatch queue on which the changes are to be delivered.
By default, the main queue is used.

====
[source,swift]
----
include::swift:example$code_snippets/CodableCombine.swift[tags="publish-replicator-changes", indent=0]
----
====

For API details, see https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-ios}{empty}/couchbase-lite-swift/Classes/Replicator.html#/Combine%20Publisher[Combine Publisher].

To get a publisher that emits `DocumentReplication` events whenever documents are pushed or pulled during replication:

* Use the `documentReplicationPublisher` function with the replicator.
* Optionally, specify the dispatch queue on which the changes are to be delivered.
By default, the main queue is used.

====
[source,swift]
----
include::swift:example$code_snippets/CodableCombine.swift[tags="publish-replication-changes", indent=0]
----
====

For API details, see https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-ios}{empty}/couchbase-lite-swift/Classes/Replicator.html#/Combine%20Publisher[Combine Publisher].

[#examples]
== Examples

[#viewmodel]
=== ViewModel

[tabs]
====

Combine Framework::
+
--
For iOS 13 and later, or macOS 10.15 to 14:

[source,swift]
----
@MainActor
class TodoViewModel: ObservableObject {
   @Published var todos: [Task] = []

   private let db: Database
   private let tasks: Collection
   private var cancellables = Set<AnyCancellable>()

   init() {
       self.db = AppDataStore.shared.database
       self.tasks = db.collection(name: "tasks")


       let query = "SELECT meta().id, title, completed from tasks"
       try? db.createQuery(query).publish()
           .map { $0.results?.data(as: Task.self) ?? [] }
           .sink { [weak self] tasks in self?.todos = tasks }
           .store(in: &cancellables)
   }

   func addTask(title: String) throws {
       try tasks.save(from: Task(title: title))
   }

   func toggleCompletion(for task: Task) throws {
       if let index = todos.firstIndex(where: { $0.id == task.id }) {
           todos[index].completed.toggle() // Reflect UI right away
           try tasks.save(from: todos[index])
       }
   }

   func deleteTask(_ task: Task) throws {
       try tasks.delete(for: task)
   }
}
----
--


Observation Framework::
+
--
For iOS 17 and later, or macOS 14 and later:

[source,swift]
----
@Observable class TodoViewModel {
    var todos: [Task] = []    // Observable property automatically tracked by SwiftUI

    private let db: Database
    private let tasks: Collection

    init() {
        self.db = AppDataStore.shared.database
        self.tasks = db.collection(name: "tasks")

        let query = "SELECT meta().id, title, completed FROM tasks"

        // Subscribe to changes and update todos directly
        try? db.createQuery(query).publish()
            .map { $0.results?.data(as: Task.self) ?? [] }
            .sink { [weak self] tasks in
                self?.todos = tasks
            }
    }

    func addTask(title: String) throws {
        try tasks.save(from: Task(title: title, completed: false))
    }

    func toggleCompletion(for task: Task) throws {
        if let index = todos.firstIndex(where: { $0.id == task.id }) {
            todos[index].completed.toggle()
            try tasks.save(from: todos[index])
        }
    }

    func deleteTask(_ task: Task) throws {
        try tasks.delete(for: task)
    }
}
----
--
====

[#view]
=== View

[tabs]
====

Combine Framework::
+
--
For iOS 13 and later, or macOS 10.15 to 14:

[source,swift]
----
​​struct TodoListView: View {
    @StateObject private var viewModel = TodoViewModel()

    var body: some View {
        List {
            ForEach(viewModel.todos) { task in
                HStack {
                    Text(task.title)
                    Spacer()
                    Button(action: {
                        try? viewModel.toggleCompletion(for: task)
                    }) {
                        Image(systemName: task.completed ? "checkmark" : "circle")
                            .foregroundColor(task.completed ? .green : .gray)
                    }
                }
            }
            .onDelete { indexSet in
                indexSet.forEach { index in
                    let task = viewModel.todos[index]
                    try? viewModel.deleteTask(task)
                }
            }
        }
        .toolbar {
            ToolbarItem(placement: .navigationBarTrailing) {
                Button(action: { try? viewModel.addTask(title: "New Task") }) {
                    Image(systemName: "plus")
                }
            }
        }
    }
}
----
--


Observation Framework::
+
--
For iOS 17 and later, or macOS 14 and later:

[source,swift]
----
​struct TodoView: View {
    @State var viewModel = TodoViewModel()
    @State private var newTaskTitle = ""

    var body: some View {
        VStack {
            TextField("New Task", text: $newTaskTitle)
                .textFieldStyle(.roundedBorder)
                .padding()

            Button("Add") {
                guard !newTaskTitle.isEmpty else { return }
                try? viewModel.addTask(title: newTaskTitle)
                newTaskTitle = ""
            }

            List(viewModel.todos, id: \.id) { task in
                HStack {
                    Button(action: { try? viewModel.toggleCompletion(for: task) }) {
                        Image(systemName: task.completed ? "checkmark.circle.fill" : "circle")
                    }

                    Text(task.title)
                        .strikethrough(task.completed)

                    Spacer()

                    Button(action: { try? viewModel.deleteTask(task) }) {
                        Image(systemName: "trash")
                    }
                }
            }
        }
        .padding()
    }
}
----
--
====

[#see-also]
== See Also

* xref:swift:scopes-collections-manage.adoc[]
* xref:swift:document.adoc[]
* xref:swift:query-resultsets.adoc[]
* xref:swift:conflict.adoc[]


