= Upgrade
:page-aliases: advance/swift-dep-upgrade.adoc, dep-upgrade.adoc
:page-role:
:description:

:source-language: swift


[IMPORTANT]
--
On upgrading from a 2.x release, all Couchbase Lite databases will automatically be re-indexed on initial database open. +
This can result in a delay before the database is usable.
--

=== Vector Search Extension

Couchbase Lite 3.4.0 is compatible with Vector Search Extension 2.0.0 only.
If your application uses Vector Search, update the Vector Search Extension to 2.0.0 when upgrading to Couchbase Lite 3.4.0.

[#3-4-0-upgrade]
== {major}.{minor}.{base}{empty} Upgrade

Couchbase Lite {major}.{minor} is a non-breaking upgrade from 3.3.
Update your Couchbase Lite dependency to {major}.{minor} -- no API or configuration changes are required.
Existing `MultipeerReplicatorConfiguration` setups continue to work without modification.
The default transport remains Wi-Fi only.

[WARNING]
--
When upgrading from Couchbase Lite 3.4.0 to the 4.x release line, upgrade directly to 4.1.0 or later.
Couchbase Lite 4.x versions below 4.1.0 do not include all APIs added in 3.4.0 (Multipeer Replicator with Bluetooth and Auto Switching, Replication Correlation ID, and on Android, Kotlin Serialization; and on C, the C++ API).
--

=== Enabling Bluetooth Transport (Optional)

To enable Bluetooth Low Energy transport alongside Wi-Fi, set the `transports` property on your `MultipeerReplicatorConfiguration`.
Setting both transports enables automatic transport switching: the replicator defaults to Wi-Fi when available and falls back to Bluetooth when Wi-Fi is unavailable.
For more detail, see xref:swift:p2psync-multipeer.adoc#automatic-transport-switching[Automatic Transport Switching].

[source, swift]
----
var config = MultipeerReplicatorConfiguration(
    peerGroupID: "myGroup",
    identity: identity,
    authenticator: authenticator,
    collections: collections)
config.transports = [.wifi, .bluetooth]
----

To restrict replication to Bluetooth exclusively, omit `.wifi`:

[source, swift]
----
var config = MultipeerReplicatorConfiguration(
    peerGroupID: "myGroup",
    identity: identity,
    authenticator: authenticator,
    collections: collections)
config.transports = [.bluetooth]
----

Bluetooth transport requires iOS 15.0 or later.

[#api-changes]
=== API Changes

[#removed-apis]
==== Removed APIs

[#resetcheckpoint]
===== ResetCheckpoint

.Alternative
  `replicator.start(reset:)`

.Before
----
replicator.resetCheckpoint()
replicator.start()
----

.After
----
replicator.start(true)
----

[#database-setloglevel]
===== Database.setLogLevel

.Alternative
`Database.log.console`

.Before
----
Database.setLogLevel(.verbose, domain: .all)
----

.After
----
Database.log.console.domain = .all
Database.log.console.level = .verbose
----

[#database-compact]
===== Database.compact
.Alternative

https://docs.couchbase.com/mobile/3.0.0-beta02/couchbase-lite-swift/Classes/Database.html#/s:18CouchbaseLiteSwift8DatabaseC18performMaintenance4typeyAA0F4TypeO_tKF[Database.performMaintenance(type:)]

.Before
----
try testdb.compact()
----

.After
----
try testdb.performMaintenance(type: .compact)
----

[#lbl-db-upgrades]
== 1.x Databases Upgrades to 2.x

Databases created using Couchbase Lite 1.2 or later can still be used with Couchbase Lite 2.x; but will automatically be updated to the current 2.x version.
This feature is only available for the default storage type (i.e., not a ForestDB database).

[#encrypted-databases]
=== Encrypted Databases
The automatic migration feature does not support encrypted databases.
So if the 1.x database is encrypted you will first need to disable encryption using the Couchbase Lite 1.x API (see the https://docs-archive.couchbase.com/couchbase-lite/1.4/swift.html#database-encryption[1.x Database Guide]).

.Upgrading Encrypted Databases
****
. Disable encryption using the Couchbase Lite 1.x framework (see https://docs-archive.couchbase.com/couchbase-lite/1.4/swift.html#database-encryption[1.x encryption guide])
. Open the database file with encryption enabled using the Couchbase Lite 2.x framework.
****

Since it is not possible to package Couchbase Lite 1.x and Couchbase Lite 2.x in the same application this upgrade path would require two successive upgrades.

If you are using Sync Gateway to synchronize the database content, it may be preferable to run a pull replication from a new 2.x database with encryption enabled and delete the 1.x local database.

[#downgrading-couchbase-lite]
== Downgrading Couchbase Lite

[#downgrading-between-major-releases]
=== Downgrading Between Major Releases

*No Downgrade Support* - Downgrades between major versions of Couchbase Lite (CBL) are not supported.
Once you upgrade to a new major version, downgrading to a previous major version may lead to incompatibility issues.

[#downgrading-between-minor-releases]
=== Downgrading Between Minor Releases

*Conditional Downgrade Support* - Downgrade support for minor releases is considered on a case-by-case basis.
The release notes for each minor version clarifies whether downgrades are supported.

[#downgrading-between-patch-releases]
=== Downgrading Between Patch Releases

*Full Downgrade Support* - Downgrades between patch releases are supported.
Users can downgrade between different patch versions within the same minor release.

[#related-content]
== Related Content
++++
<div class="card-row three-column-row">
++++

[.column]
=== {empty}
.How to . . .
* xref:swift:gs-prereqs.adoc[Prerequisites]
* xref:swift:gs-install.adoc[Install]
* xref:swift:gs-build.adoc[Build and Run]

.

[.column]
=== {empty}
.Learn more . . .
* xref:swift:database.adoc[Databases]
* xref:swift:document.adoc[Documents]
* xref:swift:blob.adoc[Blobs]
* xref:swift:replication.adoc[Remote Sync Gateway]
* xref:swift:conflict.adoc[Handling Data Conflicts]

.

[.column]
=== {empty}
.Dive Deeper . . .
https://forums.couchbase.com/c/mobile/14[Mobile Forum] |
https://blog.couchbase.com/[Blog] |
https://docs.couchbase.com/tutorials/[Tutorials]

.

++++
</div>
++++