= Vector Search
:page-status: Beta
:page-aliases: 
ifdef::show_edition[:page-edition: {release}]
ifdef::prerelease[:page-status: {prerelease}]
:page-role:
:description: Use Vector Search for AI applications.
:keywords: edge AI api swift ios macos apple vector search generative

== About Vector Search

You can use Vector Search to efficiently find similar items or content based on the similarity of their vector representations. 
This is particularly useful for large datasets and real-time response applications.

Vector Search is a Similarity Search method that looks for approximated nearest vectors in localised vector space. 
These vectors are represented by arrays of numbers known as an embedding, which are generated by Large Language Models (LLMs) to represent objects such as text, images, and audio. 

== Applications of Vector Search

You can use Vector Search to efficently perform common operations on remote and document Vector Embeddings such as:

* Anomaly Detection - Identifying outliers with little relatedness

* Classification - Classifying text strings by their most similar text label

* Clustering - Grouping text strings by similarity

* Diversity Measurement - Analyzing similarity distributions

* Recommendations - Recommending items with related text strings

* Search - Ranking results by similarity to given input strings

== About Vector Indexes

Vector Indexes are objects used to efficiently perform similarity search on collections of vectors.
Before use, a Vector Index needs to be trained to compute the centroids and parameters for encoding the vectors. 
Training is configured to commence automatically on the first Vector Search query when there are enough vectors to be trained based on the `minimum-training-size` configuration.

=== Vector Index Configuration

.Vector Index Configuration Options
[cols ="4*"]
|===
|Configuration Name |Is Required |Default Configuration |Further Information

|Expression
|Required
|No default
| A SQL++ expression indicating where to get the vectors. 
A document property for embedded vectors
`prediction()` to call a registered Predictive model.
|Number of Dimensions
|Required
|No default
|2-2048
|Number of Centroids
|Required
|No default
|1-64000. The general guideline is an approximate square root of the number of documents
|Distance Metric
|Optional
|Euclidean Distance
|You can also configure Cosine Distance as your Distance Metric
|Encoding
|Optional
| Scalar Quantizer(SQ) or SQ-8 bits
a|There are three possible configurations:

* None
No compression, No data loss
* Scalar Quantizer (SQ) or SQ-8 bits (Default)
Reduces the number of bits per dimension 
* Product Quantizer (PQ)
Reduces the number of dimensions and bits per dimension

|Training Size
|Optional
a|There are defaults for both the minimum and maximum training size

* The minimum training size is set to 25x the number of Centroids

* The maximum training size is set to 256x the number of Centroids
|

|===

CAUTION: Altering the default training sizes could be detrimental to the accuracy of returned results produced by the model and total computation time.

== See Also

* xref:swift:vector-search-api-reference.adoc[Vector Search API Reference]

* xref:swift:working-with-vector-search.adoc[Working with Vector Search]

* xref:swift:fts.adoc[Full Text Search]