= Working with Vector Search
:page-status: Beta
:page-edition: Enterprise
:page-aliases: 
ifdef::show_edition[:page-edition: {release}]
ifdef::prerelease[:page-status: {prerelease}]
:page-role:
:description: Use Vector Search with Full Text Search and Query.
:keywords: edge AI api swift ios macos apple vector search generative

This page is TODO!

//
//  VectorSearchSnippets.swift
//
//  Created by Vlad Velicu on 20/03/2024.
//

import Foundation
import CouchbaseLiteSwift
import NaturalLanguage

class VectorSearchSnippets {
    var database: Database!
    var collection: Collection!
    var model: NLEmbedding!

    // MARK: Configuring a project to use Vector Search.

    /*/
     Download Couchbase Lite iOS Swift and Couchbase Lite Vector Search libraries
     Extract the xcframeworks and copy them into the App Project Directory
     
     Add both libraries to the *Frameworks, Libraries and Embedded Content* of your desired target
     */


== Create a Vector Index

[source, swift]
----

func vectorIndex() throws {
    database = try Database(name: "vectorDB")
    collection = try database.defaultCollection()
        
     // MARK: Create a default Vector Index Configuration
        
    var config = VectorIndexConfiguration(expression: "string", dimensions: 300, centroids: 20)
        
     // Default values already set:
     print(config.encoding) // scalarQuantizer(type: .SQ8)
     print(config.metric) // euclidean
     print(config.minTrainingSize) // 25 * centroids(20)
     print(config.maxTrainingSize) // 256 * centroids(20)
        
        // MARK: Set custom optional settings
     config.encoding = .none
     config.metric = .cosine
     config.minTrainingSize = 50
     config.maxTrainingSize = 300
        
}
----

== Create a Vector Index with Embeddings

[source, swift]
----

func vectorIndexEmbedding() throws -> ResultSet? {
    // MARK: Create Vector Index with Embedding
    let config = VectorIndexConfiguration(expression: "word", dimensions: 300, centroids: 20)
    try collection.createIndex(withName: "vector_index", config: config)
        
    model = NLEmbedding.wordEmbedding(for: .english)!
    guard let wordVector = model.vector(for: "<word>") else {
        NSLog("Cannot generate vector for <word>")
        return nil
    }
        
    let sql = "SELECT word FROM words WHERE vector_match(vector_index, $vector, 20)"
    let query = try database.createQuery(sql)
        
    let params = Parameters()
    params.setValue(wordVector, forName: "vector")
    query.parameters = params
        
    return try query.execute()
}
----

== Create a Vector Index from a Predictive Model

[source, swift]
----
        
    func vectorIndexPredictiveModel() throws {
        // MARK: Create Vector Index with Predictive Model
        let model = NLEmbedding.wordEmbedding(for: .english)!
        Database.prediction.registerModel(model as! PredictiveModel, withName: "WordEmbedding")
        let expression = "prediction(WordEmbedding,{\"word\": word}).vector"
        let config = VectorIndexConfiguration(expression: expression, dimensions: 300, centroids: 8)
        try collection.createIndex(withName: "words_pred_index", config: config)
    }
----

== Use `vector_match()`

[source, swift]
----
        
    func useVectorMatch() throws -> ResultSet? {
        // MARK: Use vector_match
        let config = VectorIndexConfiguration(expression: "vector", dimensions: 300, centroids: 8)
        
        try collection.createIndex(withName: "vector_index", config: config)
        
        let sql = "select meta().id, word from _default.words where vector_match(vector_index, $vector, 20)"
        let query = try database.createQuery(sql)
        
        let parameters = Parameters()
        parameters.setValue(<inputArray>, forName: "vector")
        query.parameters = parameters
        
        return try query.execute()
    }
----

== Use `vector_distance()`

[source, swift]
----

    func useVectorDistance() throws -> ResultSet? {
        // MARK: Use vector_distance
        var config = VectorIndexConfiguration(expression: "vector", dimensions: 300, centroids: 8)
        config.metric = .cosine
        try collection.createIndex(withName: "vector_index", config: config)
        
        let sql = "select meta().id, word, vector_distance(vector_index) from _default.words where vector_match(vector_index, $vector, 20)"
        let query = try database.createQuery(sql)
        
        let parameters = Parameters()
        parameters.setValue(<inputArray>, forName: "vector")
        query.parameters = parameters
        
        return try query.execute()
    }

}
----

The examples below were taken from the presentation for reference 

== Create a Vector Index from an Embedding

[source, swift]

----

import CouchbaseLiteSwift

func createIndex() throws {
   var config = VectorIndexConfiguration(expression: "vector", dimensions: 300, controids: 20)
   config.metric = .cosine
   config.minTrainingSize = 50
   config.maxTrainingSize = 200

   try collection.createIndex(withName: "words_index", config: config)
}


func search(for word: String, limit: UInt) throws -> ResultSet {
   guard let wordVector = model.vector(for: word) else { throws Errors.notFound }

   let sql = "SELECT word FROM words WHERE vector_match(words_index, $vector, 10)"
   
   let query = try db.createQuery(sql)

   let params = Parameters()
   params.setValue(wordVector, forName: "vector")
   query.parameters = params

   return try query.execute()
}


----

== Create a Vector Index from a Predictive Model

[source, swift]

----

import CouchbaseLiteSwift

class WordModel: PredictiveModel {
   let model = NLEmbedding.wordEmbedding(for: .english)!

   func predict(input: DictionaryObject) -> DictionaryObject? {
     guard let word = input.string(forKey: "word") else { return nil }

     guard let vector = model.vector(for: word) else { return nil }
     
     let result = MutableDictionaryObject()
     result.setValue(vector, forKey: "vector")
     return result
}

func registerWordModel() {
    Database.prediction.registerModel(WordModel(), withName: "word_model")
}


func createIndex() throws {
   var config = VectorIndexConfiguration(expression: "prediction(word_model, {\"word\": word}).vector", 
                                         dimensions: 300, controids: 20)
   config.metric = .cosine
   config.minTrainingSize = 50
   config.minTrainingSize = 200

   try collection.createIndex(withName: “words_index”, config: config)
}


----


== See Also

* xref:swift:vector-search.adoc[Vector Search]

* xref:swift:vector-search-api-reference.adoc[Vector Search API Reference]

* xref:swift:fts.adoc[Full Text Search]