= Compatibility

[NOTE]
====
Supported iOS and Android versions are dependent on React Native.  See the https://github.com/reactwg/react-native-releases/blob/main/docs/support.md[React Native Documentation] documentation for more information.
====

The @couchbase/couchbase-lite-react-native library is built against Couchbase Lite Enterprise for iOS and Android. Version 1.1 uses Couchbase Lite Android Enterprise 3.3.3 and Couchbase Lite Swift Enterprise 3.3.3.

Version 1.1 supports https://reactnative.dev/architecture/overview[React Native New Architecture] through TurboModules. Apps should use React Native 0.76.3 or higher and enable New Architecture for the TurboModule path.

== Platform Support

[cols="1,1"]
|===
|Environment |Support Status

|iOS
|Supported

|Android
|Supported

|Web
|Not supported

|Windows
|Not supported

|macOS
|Not supported
|===

== Native SDK Compatibility

To see the compatibility notes for the native SDK, see the following documentation:

* https://docs.couchbase.com/couchbase-lite/current/swift/supported-os.html[Couchbase Mobile Compatibility Guide - iOS].
* https://docs.couchbase.com/couchbase-lite/current/android/supported-os.html[Couchbase Mobile Compatibility Guide - Android].
