= Working with Replications
:page-layout: article
:page-status:
:page-edition: Under Development
:page-role:
:description: Couchbase database replication and synchronization concepts

include::partial$_std-cbl-hdr-csharp.adoc[]

:param-abstract: Related Concepts: {xref-cbl-pg-conflict} | {xref-cbl-pg-dbreplica} | {xref-cbl-pg-cert-pinning} |
:topic-group: Topic Group -- Replication
include::{root-partials}block-abstract.adoc[]


== Replication

include::{root-partials}replication-introduction.adoc[]

=== Compatibility

WARNING: The new protocol is *incompatible* with CouchDB-based databases.
And since Couchbase Lite 2 only supports the new protocol, you will need to run a version of Sync Gateway that xref:sync-gateway::compatibility-matrix.adoc[supports it].

To use this protocol with Couchbase Lite 2.0, the replication URL should specify WebSockets as the URL scheme (see the "Starting a Replication" section below).
Mobile clients using Couchbase Lite 1.x can continue to use *http* as the URL scheme.
Sync Gateway 2.0 will automatically use the 1.x replication protocol when a Couchbase Lite 1.x client connects through "http://localhost:4984/db" and the 2.0 replication protocol when a Couchbase Lite 2.0 client connects through "ws://localhost:4984/db".

=== Starting Sync Gateway

https://www.couchbase.com/downloads[Download Sync Gateway] and start it from the command line with the configuration file created above.

.Windows
 powershell & 'C:\Program Files (x86)\Couchbase\sync_gateway.exe' sync-gateway-config.json

.Unix
 bash ~/Downloads/couchbase-sync-gateway/bin/sync_gateway

For platform specific installation instructions, refer to the Sync Gateway xref:sync-gateway::getting-started.adoc#installation[installation guide].

=== Starting a Replication

Replication objects are now bidirectional, this means you can start a `push`/`pull` replication with a single instance.
The replication's parameters can be specified through the {url-api-references}/api/Couchbase.Lite.Sync.ReplicatorConfiguration.html[`ReplicatorConfiguration`] object;
for example, if you wish to start a `push` only or `pull` only replication.

The following example creates a `pull` replication with Sync Gateway.

[source, {source-language}]
----
public class MyClass
{
    public Database Database { get; set; }
    public Replicator Replicator { get; set; } // <1>

    public void StartReplication()
    {
        var url = new Uri("ws://localhost:4984/db"); // <2>
        var target = new URLEndpoint(url);
        var config = new ReplicatorConfiguration(Database, target)
        {
            ReplicatorType = ReplicatorType.Pull
        };

        Replicator = new Replicator(config);
        Replicator.Start();
    }
}
----
<1> A replication is an asynchronous operation.
To keep a reference to the `replicator` object, you can set it as an instance property.
<2> The URL scheme for remote database URLs has changed in Couchbase Lite 2.0.
You should now use `ws:`, or `wss:` for SSL/TLS connections.

include::partial$verify-replication.adoc[]

Couchbase Lite 2.0 uses WebSockets as the communication protocol to transmit data.
Some load balancers are not configured for WebSocket connections by default (NGINX for example);
so it might be necessary to explicitly enable them in the load balancer's configuration (see xref:sync-gateway::load-balancer.adoc[Load Balancers]).

By default, the WebSocket protocol uses compression to optimize for speed and bandwidth utilization.
The level of compression is set on Sync Gateway and can be tuned in the configuration file (xref:sync-gateway::config-properties.adoc#replicator_compression[`replicator_compression`]).

==== Replication Ordering

To optimize for speed, the replication protocol doesn't guarantee that documents will be received in a particular order.
So we don't recommend to rely on that when using the replication or database change listeners for example.

=== Troubleshooting

As always, when there is a problem with replication, logging is your friend.
The following example increases the log output for activity related to replication with Sync Gateway.

[source, {source-language}]
----
include::{snippet}[tag=replication-logging,indent=0]
----

=== Authentication

By default, Sync Gateway does not enable authentication.
This is to make it easier to get up and running with synchronization.
You can enable authentication with the following properties in the configuration file:

[source,json]
----
{
  "databases": {
    "mydatabase": {
      "users": {
        "GUEST": {"disabled": true}
      }
    }
  }
}
----

To authenticate with Sync Gateway, an associated user must first be created.
Sync Gateway users can be created through the xref:sync-gateway::admin-rest-api.adoc#/user/post\__db___user_[`+POST /{tkn-db}/_user+`] endpoint on the Admin REST API.
Provided that the user exists on Sync Gateway, there are two ways to authenticate from a Couchbase Lite client: Basic Authentication or Session Authentication.

==== Basic Authentication

You can provide a user name and password to the basic authenticator class method.
Under the hood, the replicator will send the credentials in the first request to retrieve a `SyncGatewaySession` cookie and use it for all subsequent requests during the replication.
This is the recommended way of using basic authentication.
The following example initiates a one-shot replication as the user *john* with the password *pass*.

[source, {source-language}]
----
include::{snippet}[tag=basic-authentication,indent=0]
----

==== Session Authentication

Session authentication is another way to authenticate with Sync Gateway.
A user session must first be created through the xref:sync-gateway::rest-api.adoc#/session/post\__db___session[`+POST /{tkn-db}/_session+`] endpoint on the Public REST API.
The HTTP response contains a session ID which can then be used to authenticate as the user it was created for.
The following example initiates a one-shot replication with the session ID that is returned from the `+POST /{tkn-db}/_session+` endpoint.

[source, {source-language}]
----
include::{snippet}[tag=session-authentication,indent=0]
----

=== Replication Status

The `replication.Status.Activity` property can be used to check the status of a replication.
For example, when the replication is actively transferring data and when it has stopped.

[source, {source-language}]
----
include::{snippet}[tag=replication-status,indent=0]
----

The following table lists the different activity levels in the API and the meaning of each one.

[cols="1,2"]
|===
|State |Meaning

|`STOPPED`
|The replication is finished or hit a fatal error.

|`OFFLINE`
|The replicator is offline as the remote host is unreachable.

|`CONNECTING`
|The replicator is connecting to the remote host.

|`IDLE`
|The replication caught up with all the changes available from the server.
The `IDLE` state is only used in continuous replications.

|`BUSY`
|The replication is actively transferring data.
|===

NOTE: The replication change object also has properties to track the progress (`change.status.completed` and `change.status.total`).
But since the replication occurs in batches and the total count can vary through the course of a replication, those progress indicators are not very useful from the standpoint of an app user.
Hence, these should not be used for tracking the actual progress of the replication.

==== Replication Status and App Life Cycle

Couchbase Lite doesn't react to OS backgrounding or foregrounding events and replication(s) will continue running as long as the remote system does not terminate the connection and the app does not terminate.
It is generally recommended to stop replications before going into the background otherwise socket connections may be closed by the OS and this may interfere with the replication process.

=== Handling Network Errors

If an error occurs, the replication status will be updated with an `Error` which follows the standard HTTP error codes.
The following example monitors the replication for errors and logs the error code to the console.

[source, {source-language}]
----
include::{snippet}[tag=replication-error-handling,indent=0]
----

When a permanent error occurs (i.e., `404`: not found, `401`: unauthorized), the replicator (continuous or one-shot) will stop permanently.
If the error is temporary (i.e., waiting for the network to recover), a continuous replication will retry to connect indefinitely and if the replication is one-shot it will retry for a limited number of times.
The following error codes are considered temporary by the Couchbase Lite replicator and thus will trigger a connection retry.

* `408`: Request Timeout
* `429`: Too Many Requests
* `500`: Internal Server Error
* `502`: Bad Gateway
* `503`: Service Unavailable
* `504`: Gateway Timeout
* `1001`: DNS resolution error

=== Replication Events

include::{root-partials}replication-events.adoc[]

=== Custom Headers

include::{root-partials}replication-custom-header.adoc[]

[source, {source-language}]
----
include::{snippet}[tag=replication-custom-header,indent=0]
----

=== Replication Checkpoint Reset

include::{root-partials}replication-checkpoint.adoc[]

[source, {source-language}]
----
include::{snippet}[tag=replication-reset-checkpoint,indent=0]
----

=== Replication Filters

include::{root-partials}replication-filters.adoc[]


include::{root-partials}block-related-content-rep.adoc[]