// = P2P Sync Using WebsocketEndpointListener
// :page-layout: article
// :page-status: {release-status-cbl} -- {release-comments-cbl}
// :page-edition: Under Development
// :page-role:
// :description: Couchbase mobile database queries - concepts
//
// include::partial$_std-cbl-hdr-android.adoc[]
[abstract]
--
{description}
{param-abstract}
--

ifndef::release-status-cbl[:release-status-cbl!:]
ifeval::["{release-status-cbl}" == "gamma"]
[.pane__frame--orange]
.Author's Notes
--

DOC-6892-H2-P2P: New topic - WebsockedtEndpointListener and P2P Sync
https://issues.couchbase.com/browse/DOC-6892

Add content covering CBL websocketlistener

Sources:
* reqs https://docs.google.com/document/d/1o1Dol-g6_D5Stf0IrgY_yxr0kO6AYVJFGOgGjoh6Q6c/edit?ts=5e5fe7da#
* design https://docs.google.com/document/d/1R2Vd5Iei1OLJvU4QJ-zE6FED8VH-nr2Q9PyjbjwVW48/edit#heading=h.ayhq9efeewhi

This will be  full description of the websocketendpointlistener including:

* Overview and feature description
* API
* Workflow - operational sequence for normal P2P sync ops
* Example code for simple sync ops
* Constraints

The content may ultimately be split up as needed.

Topic to include from requirements:

* If user-defined port is not specified, the system will automatically select a port to use. -- https://docs.google.com/document/d/1o1Dol-g6_D5Stf0IrgY_yxr0kO6AYVJFGOgGjoh6Q6c/edit#bookmark=id.s5y61p8gawi1
--
endif::[]

==  Overview

Couchbase Lite provides out-of-the-box {glos-term-peer-to-peer-sync}, over websockets, between Couchbase Lite enabled clients in IP-based networks.

Using this _WebsocketEndpointListener_ developers can implement peer-to-peer replication without navigating the compexity of the _MessageEndpoint_ API, which can often be a barrier.
The _WebsocketEndpointListener_ listens for incoming websocket connections on a user-defined, or auto-selected, port.

== Features

The listener features comprise:
--
* Capable of serving one couchbase lite databases per listener.
** Instantiated by client, each instance for different db. no limit on instances (ex. practical limit).
** If user-defined port is not specified, the system will automatically select a port to use.
** The API allows users to get the current port of the listener.
** The API CAN return the list of URL(s) endpoint of listener. The URL must include the listener port as well as the serving database.

* Support for encryption and authentication over TLS with multiple modes comprising:
** Anonymous
+
Auto-generated anonymous TLS Identity if the TLS Identity is not specified.
This provides encryption but *not* authentication.
** Certificate
+
Self-signed or Client Certificate Authentication (CA signed).
** Not-enabled, that-is, plain text.
* Support for basic authentication.
* Delta Sync Support.
* Built-in network resiliency with retries.
* Built-in conflict resolution support (automatic and custom).
--

== API

include::{root-partials}p2p-api.adoc[leveloffset=+1]

== Security

include::{root-partials}p2p-security.adoc[leveloffset=+1]

== Sizing

include::{root-partials}p2p-sizing.adoc[leveloffset=+1]

* Sizing - eg num websocket endponi listeners
** The scalability of the sync must only be limited by OS-level factors like number of open socket descriptions, volume of mutations getting synced .
* We must provide some guidance on the sizing factors that will determine the number of supported clients. This is probably the most commonly asked question when it comes to p2p support. Alternatives like MPC specify the same.
Context: This has been one of the reasons why off-the-shelf solutions haven’t worked requiring custom implementation

== Conflict handling

include::{root-partials}p2p-conflict.adoc[leveloffset=+1]
