// {param-module} grabs the correct platform name from the related _set_page_context_for_[platform] 
== Upgrading to the new CBL Logging API

ifndef::is-c[]

You can find information about the new Couchbase Lite Logging API introduced in Couchbase Lite 3.2.2.
For information about the now deprecated earlier version of the Logging API, see xref:3.1@couchbase-lite:{param-module}:troubleshooting-logs.adoc[]

endif::is-c[]

== LogSinks

A lot of the new logging API will seem very familiar: many of the concepts are
the same.  There are still three places that log messages can be sent: the log
files, the console, and custom code and Couchbase still logs its messages in a
handfull of named "domains" and at common log levels: `debug` the most verbose,
ane `error` only for serious failures.

The first thing to note is that the three destinations for logs have been
renamed as "LogSinks", in keeping with common source/sink terminology. The
`FileLogSink`, the `ConsoleLogSink` and the `CustomLogSink` are all installed in
an instance of `LogSinks`.  To get the instance of `LogsSinks`, use the method
`LogSinks.get()`.  This is the analog of getting the instance of Log from
`Database.log` in the old API.

Perhaps the biggest difference between the new and the old API is that
`LogSinks` are immutable: you set the level and domain at which they log in
their constructors. The only way to change, for instance, the level at which the
`ConsoleLogSink` forwards messages to the console is to install a new one
created for the new log level.

All three log sinks are initialized by default. If you want to stop all logging
to one of them, though, just set the sink to null:
`LogSinks.get().setFile(null)`

=== Logging to the Console

The changes necessary convert the installation of a console logger from the old
to the new API are minimal <1>.  Simply create an instance of `ConsoleLogSink`
initialized with the desired log level and domains and install it using
`LogSinks.setCustom`. (Snippet here)

=== Logging to the Couchbase File Log

The changes necessary to convert the installation of a file logger are similarly easy. 
Instead of configuring a `FileLogger` using a`LogFileConfiguration`, use
the `FileLogSink.Builder` to create a new `FileLogSink` with the desired
properties and install it <2>. (Set file snippet)  Note, though, that `setRotateCount` from the old
API is slightly different from `setMaxKeptFiles`.  The latter is the maximum
number of log files that will exist at any time and is the count of rotated
files plus one.

=== Using a Custom Logger

Installing a custom log sink with the new API is also streamlined: create an
instance of your custom sink and use `LogSinks.get().setCustom` to install it
<3>. (new custom snippet) As with the other log sinks, you will have to specify the level and domain
at which Couchbase logs are forwarded to your custom sink at its creation.

Your custom log sink code will have to change as well.  The most significant
change is that instead of implementing the `Logger` interface, a custom log sink
must extend the `BaseLogSink` class <4>.  The `BaseLogSink` class does not have
a no-args constructor: you must specify at least the level at which Couchbase
logs will be forwarded to the logger <6>.  Unless otherwise specified logs from
all Couchbase domains will be forwarded to the custom log sink.

A second important change is that your logger will receive only logs at the
level and domain for which it is initialized.  There is no need to record or
filter the logs forwarded to the protected `writeLog` method (which replaces the
public `log` method from the old API) <5> <7>.

Related to this last point, the Couchbase `Logger`s, now `LogSink`s are meant to
support logging by the Couchbase Lite platform.  They were never meant as a
general framework for logging.  With the new API, customer code can no longer
log, directly, to any of the Couchbase log sinks.  The Console and File log
sinks are (or will be in subsequent releases) final classes and do not publish
methods that allow writing logs.  If you need to log e.g., to the console, you
will have to create your own way of doing so.

// You can change the number of Probes by altering the value  of the `NumProbes` variable xref:{param-module}:working-with-vector-search.adoc#create-a-vector-index[shown in the following example].

// == See Also

// * xref:{param-module}:gs-install.adoc[Install Couchbase Lite and Vector Search]
