// BEGIN -- inclusion -- common-query-resultsets.adoc
//  Purpose -- describes the use of the query's resultset
//
// // BEGIN::REQUIRED EXTERNALS
// :this-module: {par-module}
// :this-lang-title: {par-lang-title}
// :this-packageNm: {par-packageNm}
// :this-source-language: {par-source-language}
// snippet: {par-snippet}
//:this-url-issues: {par-url-issues}
// END::REQUIRED EXTERNALS

// BEGIN::Local page attributes
:blank-field: ____

// END::Local page attributes


== Query Execution
The execution of a Couchbase Lite for {param-title}'s database query returns an array of results, a result set.

Each row of the result set represents the data returned from a document that met the conditions defined by the `WHERE` statement of your query.
The composition of each row is determined by the `SelectResult` expressions provided in the `SELECT` statement.

ifndef::is-c[]
[#lbl-rtnd-res]
== Returned Results
<<lbl-rtn-all>>
| <<lbl-rtn-id>>
| <<lbl-rtn-specific>>

The types of SelectResult formats you may encounter include those generated by :

* `QueryBuilder.select(SelectResult.all())` -- <<lbl-rtn-all,Using All>>
* `QueryBuilder.select(SelectResult.expression(Meta.id))` -- <<lbl-rtn-id,Using Doc Id>> Metadata such as the `_id`
* `QueryBuilder.select(SelectResult.property("myProp"))` -- <<lbl-rtn-specific,Using Specific Properties>>


[#lbl-rtn-all]
=== Return All Document Properties
The SelectResult returned by `SelectResult.all()` is a dictionary object, with the database name as the key and the document properties as an array of key-value pairs

--
.Returning All Properties
[#ex-result-id]
====
[pass:q,a[source, json, subs="+attributes, +macros"], role="no-callouts"]
----

include::ROOT:example$query-snippets.adoc[tags=query-result-format-all]

----
====
--


[#lbl-rtn-id]
=== Return Document Id Only
The SelectResult returned by queries using a SelectResult expression of the form `SelectResult.expression(Meta.id)` comprises a dictionary object with `ID` as the key and the ID value as the value.

--
.Returning Meta Properties -- Document ID
[#ex-result-id]
====
[pass:q,a[source, json, subs="+attributes, +macros"]]
----

include::ROOT:example$query-snippets.adoc[tags=query-result-format-id]

----
====
--


[#lbl-rtn-specific]
=== Return Specific Properties Only
The SelectResult returned by queries using one or more SelectResult expressions of the form `SelectResult.expression(property("name")) )` comprises a key-value pair for each SelectResult expression in the query.
The key being the property name.

--
.Returning Specific Properties
[#ex-result-props]
====
[pass:q,a[source, json, subs="+attributes, +macros"], role="no-callouts"]
----

include::ROOT:example$query-snippets.adoc[tags=query-result-format-props]

----
====
--
endif::is-c[]

[#lbl-process-resultset]
== Processing Results
<<lbl-acc-all>>
| <<lbl-acc-id>>
| <<lbl-acc-specific>>

To retrieve the results of your query,  you need to execute it using `Query.execute`.

The output from the execution is an array, with each array element representing the data from a document that matched your search criteria.

To unpack the results you need to iterate through this array.
Alternatively, you can convert the result to a JSON string -- see:


[#lbl-acc-all]
=== Access Document Properties - All Properties
Here we look at how to access document properties when you have used SelectResult.all.

In this case each array element is a dictionary structure with the database name as its key.
The properties are presented in the value as an array of key-value pairs (property name/property value).

You access the retrieved document properties by converting each row's value, in turn, to a dictionary -- as shown in <<ex-acc-all>>.

[#ex-acc-all]
.Access All Properties
:param-tags: query-access-all
include::ROOT:partial$block_tabbed_code_example.adoc[]
:param-tags!:
:param-leader!:
<.> Here we get the dictionary of document properties using the database name as the key.
You can add this dictionary to an array of returned matches, for processing elsewhere in the app.
<.> Alternatively, you can access the document properties here, by using the property names as keys to the dictionary object.

// ====
// [{code-snippet}]
// ----
// let yourQuery = QueryBuilder.select(SelectResult.all)
//             .from(DataSource.database(yourDb))

// for dataRow in try yourQuery.execute() {
//   if let yourDoc = dict[dataRow.toDictionary()] as? [String:Any] {
//       let docid = yourDoc["id"]
//       let name = yourDoc["name"]
//       let type = yourDoc["type"]
//       let city = yourDoc["city"]
//   }
// }

// ----
// ====


[#lbl-acc-id]
=== Access Document Properties - ID
Here we look at how to access document properties when you have returned only the document IDs for documents that matched your selection criteria.

This is something you may do when retrieval of the properties directly by the query may consume excessive amounts of memory and-or processing time.

In this case each array element is a dictionary structure where `ID` is the key and the required document ID is the value.

Access the required document properties by retrieving the document from the database using its document ID -- as shown in <<ex-acc-id>>.

[#ex-acc-id]
.Access by ID
:param-tags: query-access-id
include::ROOT:partial$block_tabbed_code_example.adoc[]
:param-tags!:
<.> Extract the Id value from the dictionary and use it to get the document from the database

// .Access Properties using Doc ID
// ====
// [{code-snippet}]
// ----
// let yourQuery = QueryBuilder.select(SelectResult.expression(Meta.id))
//             .from(DataSource.database(yourDb))

// for dataRow in try yourQuery.execute() {
//   if let yourDocID = dict[dataRow["id"] {
//       let yourDoc = try yourDb.document(withID: yourDocId)
//       let name = yourDoc.name
//       let type = yourDoc.type
//       let city = yourDoc.city
//   }
// }

// ----
// ====


[#lbl-acc-specific]
=== Access Document Properties - Selected Properties
Here we look at how to access properties when you have used SelectResult to get a specific subset of properties.

In this case each array element is an array of key value pairs (property name/property value).

Access the retrieved properties by converting each row into a dictionary -- as shown in <<ex-acc-specific>>.

[#ex-acc-specific]
:param-tags: query-access-props
include::ROOT:partial$block_tabbed_code_example.adoc[]
:param-tags!:


// [#ex-acc-all]
// .Access All Properties
// ====
// [{code-snippet}]
// ----
// let yoursearchQuery = QueryBuilder
//             .select(SelectResult.expression(Meta.id),
//                     SelectResult.expression(Expression.property("name")),
//                     SelectResult.expression(Expression.property("city")),
//                     SelectResult.expression(Expression.property("type")))
//             .from(DataSource.database(yourDb))

// for dataRow in try yourQuery.execute() {
//   if let yourDoc = dict[dataRow.toDictionary()] as? [String:Any] {
//       let docid = yourDoc["id"]
//       let name = yourDoc["name"]
//       let type = yourDoc["type"]
//   }
// }

// ----
// ====
// END -- inclusion -- common-query-resultsets.adoc
