

== Activating a Live Query


A live query is a query that, once activated, remains active and monitors the database for changes; refreshing the result set whenever a change occurs.
As such, it is a great way to build reactive user interfaces -- especially table/list views -- that keep themselves up to date.

*So, a simple use case may be:* A replicator running and pulling new data from a server, whilst a live-query-driven UI automatically updates to show the data without the user having to manually refresh.
This helps your app feel quick and responsive.

To activate a LiveQuery just add a change listener to the query statement.
It will be immediately active.
When a change is detected the query automatically runs, and posts the new query result to any observers (change listeners).


.Starting a Live Query
[#ex-qry-start]
:param-tags: live-query
include::ROOT:partial$block_tabbed_code_example.adoc[]
:param-tags!:
<.> Build the query statements
<.> Activate the _live_ query by attaching a listener.
Save the token in order to detach the listener and stop the query later -- se <<ex-qry-stop>>


.Stop a LIve Query
[#ex-qry-stop]
:param-tags: stop-live-query
include::ROOT:partial$block_tabbed_code_example.adoc[]
:param-tags!:
<.> Here we use the change lister token from <<ex-qry-start>> to remove the listener.
Doing so stops the live query.
