// BEGIN -- page-inclusion -- common-database.adoc
// Applies to all platforms with some platform-specific differences

include::{root-partials}_set-platform.adoc[]

:param-related: {xref-cbl-pg-blob} | {xref-cbl-pg-document} | {xref-cbl-pg-indexing}
:topic-group: Topic Group -- Data Model
include::{root-partials}block-abstract.adoc[]

:fn-2-8: footnote:fn28[Commencing with Release 2.8]
:fnref-2-8: footnote:fn28[]

// BEGIN: Conditional Block -- applies to Android and JVM Java
ifdef::is-android,is-java[]
// Output block only for Android and Java modules
== Initializer
Your first step in using the API must be to call its initializer.
An exception is raised if any other API method is invoked before the  initializer.

.Initializer code
====
[source, {source-language}]
----
include::{snippet}[tag=sdk-initializer,indent=0]

----
====

endif::[]
// END: Conditional Block -- applies to Android and JVM Java

[#open-db]
== Create or Open Database

You can create a new database and-or open and existing database, using the {url-api-class-database} class.
Just pass in a database name and optionally a {url-api-class-databasecfg} -- see <<ex-dbopen>>.

Things to watch for include:

* Opening/Creating a database is an asynchronous process
* If the named database does not exist in the specified, or default, location then a new one is created
* The database is created in a default location unless you  specify a directory for it -- see: {url-api-class-databasecfg} and {url-api-method-databasecfg-setdir}
+
--
TIP: Best Practice is to always specify the path to the database explicitly.

Typically, the default location for {param-title} is
ifndef::is-csharp[]
the application sandbox.
endif::[]
ifdef::is-csharp[]
a platform-dependant location:

include::{module-partials}database-finding-file.adoc[tags=list-only]
endif::[]

See also <<lbl-find-db-loc>>.
--

[#ex-dbopen]
.Open or create a database
====
[source, {source-language}]
----
include::{snippet}[tag=new-database,indent=0]
----

<.> Here we are specifying the database directory path.

====

== Close Database
You are advised to incorporate the closing of all open databases into your application workflow.

Closing a database is a simple, just use {url-api-method-database-close} -- see: <<ex-dbclose>>. +
However, there are a number of things to be aware of:

* Closing a database is a *synchronous* operation, it is effective immediately
* You cannot close a database that is not open. +
Remember that opening (or creating) a database is asynchronous.
So issuing a close immediately after initiating an open/create, may result in an error if that process has not completed.

* Closing a database {fn-2-8} also closes any active replications, listeners and-or live queries attached to the database. +
Closing a database immediately after kicking-off a replication could cause the sync to generate an exception. +
For example: +
`IllegalStateException: Attempt to perform an operation on a closed database`

.Safely Closing a Database pre 2.8
[TIP]
--
. Stop any active live queries -- by removing the query's change listener
. Remove any active replication change listeners
. Stop any active replications -- this is an asynchronous operation
. Wait for all active replications to fully stop -- for this you can monitor the replication status -- see: {xref-cbl-pg-replication--monitor-status}.
. Finally, close the database

--

[#ex-dbclose]
.Close a Database
====
[source, {source-language}]
----
include::{snippet}[tag=close-database,indent=0]
----

====

== Database Encryption

:param-language: {param-name}
include::{root-partials}database-encryption.adoc[]


[#lbl-find-db-loc]
== Finding a Database File

:tags: {empty}
ifdef::is-csharp[]
:tags: "tags=list-only"
endif::[]

include::{module-partials}database-finding-file.adoc[{tags}]


[#cli-tool]
== Command Line Tool

// tag::cli-tool[]
include::{root-partials}cli-tool.adoc[]

// end::cli-tool[]

== Troubleshooting
You should use Couchbase's console logs as your first source of diagnostic information.
If the information in the default logging level is insufficient you can focus it on database errors and generate more verbose messages -- see: <<ex-logdb>>.

For more on using Couchbase logs -- see: {xref-cbl-pg-troubleshooting-logs}.

[#ex-logdb]
.Increase Level of Database Log Messages
====
[source, {source-language}]
----
include::{snippet}[tag=console-logging-db, indent=0]

----
====


// DO NOT DELETE
// Include standard

include::{root-partials}block-related-content-std.adoc[]
// DO NOT DELETE

// DO NOT DELETE
include::{root-partials}_unset-platform.adoc[]
// DO NOT DELETE
// END: inclusion-page - common-database.adoc[]