// BEGIN -- page-inclusion -- common-database.adoc
// Applies to all platforms with some platform-specific differences

include::{root-partials}_set-platform.adoc[]

:param-related: {xref-cbl-pg-blob} | {xref-cbl-pg-document} | {xref-cbl-pg-indexing}
:topic-group: Topic Group -- Data Model
include::{root-partials}block-abstract.adoc[]

// BEGIN: Conditional Block -- applies to Android and JVM Java
ifdef::is-android,is-java[]
// Output block only for Android and Java modules
== Initializer
Your first step in using the API must be to call its initializer.
An exception is raised if any other API method is invoked before the  initializer.

.Initializer code
====
[source, {source-language}]
----
include::{snippet}[tag=sdk-initializer,indent=0]

----
====

endif::[]
// END: Conditional Block -- applies to Android and JVM Java

// == Default Database Location
// By default, _Couchbase Lite on {param-title}_ creates databases in the following path location shown in <<default-path>>.

// [#default-path]
// .Default database path
// ====
// [source, {console}]
// ----
// <root dir>/.couchbase/<db name>.cblite // <.>
// ----

// ifdef::is-java[<.> Where the <root dir> is the directory in which JVM was started.]
// ifdef::is-android[<.> Where the <root dir> can be identified using `context.getFilesDir()`]

// ====

[#open-db]
== New Database
As the top-level entity in the API, new databases can be created using the `Database` class by passing in a name, configuration, or both.
The following example opens, or creates, a database using the `Database(String name, DatabaseConfiguration config)` method.

.Open or create a database
====
[source, {source-language}]
----
include::{snippet}[tag=new-database,indent=0]
----

Just as before, the database will be created in a default location.
Alternatively, the `Database(string name, DatabaseConfiguration config)` initializer can be used to provide specific options in the {url-api-references}/com/couchbase/lite/DatabaseConfiguration.html[`DatabaseConfiguration`] object.

<.> Here we are specifying the database directory path.
====

* Remember that:
** Opening (or creating) a database is asynchronous.
** Closing a database is a *synchronous* operation, it is effective immediately

[NOTE]
--
You cannot close a database that is not fully open.

So issuing a close immediately after initiating an open/create, may result in an error if that process has not completed.
--

== Database Encryption
// tag::database-encryption[]
include::{root-partials}_block-caveats.adoc[tag=ee-only-feature]

_Couchbase Lite on {param-title}_ includes the ability to encrypt Couchbase Lite databases.
This allows mobile applications to secure the data at rest, when it is being stored on the device.
The algorithm used to encrypt the database is 256-bit AES.

To enable encryption, you must set the `DatabaseConfiguration.encryptionKey` property to the encryption key of your choice.
Provide this encryption key every time the database is opened.

.Database encryption
====
[source, {source-language}]
----
include::{snippet}[tag=database-encryption,indent=0]
----
====

Couchbase Lite does not persist the key.
It is the application's responsibility to manage the key and store it in a platform specific secure store such as Apple's https://developer.apple.com/documentation/security/keychain_services[Keychain] or Android's https://developer.android.com/training/articles/keystore[Keystore].

An encrypted database can only be opened with the same language SDK that was used to encrypt it in the first place.
So a database encrypted using the Swift SDK, and then exported, is readable only by the Swift SDK.

=== Upgrading from 1.x when Encryption is Enabled

If you're migrating an application from Couchbase Lite 1.x to 2.x, note that the <<database-upgrade,automatic database upgrade>> functionality is *not supported* for encrypted databases.
Thus, to upgrade an encrypted 1.x database, you should do the following:

// set the correct language name for 1.4 pages
ifeval::["{param-name}"=="{lang-name-android}"]
:param-language: {lang-name-java}
endif::[]
. Disable encryption using the Couchbase Lite 1.x framework (see https://docs-archive.couchbase.com/couchbase-lite/1.4/{param-name}.html#database-encryption[1.x encryption guide])
. Open the database file with encryption enabled using the Couchbase Lite 2.x framework.

Since it is not possible to package Couchbase Lite 1.x and Couchbase Lite 2.x in the same application this upgrade path would require two successive upgrades.
If you are using Sync Gateway to synchronize the database content, it may be preferable to run a pull replication from a new 2.x database with encryption enabled and delete the 1.x local database.

// end::database-encryption[]

== Finding a Database File

include::{module-partials}database-finding-file.adoc[]


[#cli-tool]
== Command Line Tool

// tag::cli-tool[]

`cblite` is a command-line tool for inspecting and querying Couchbase Lite 2.x databases.

You can download and build it from the couchbaselabs https://github.com/couchbaselabs/couchbase-mobile-tools/blob/master/README.cblite.md[GitHub repository].

NOTE: The `cblite` tool is not covered under the  https://www.couchbase.com/support-policy[Couchbase Support Policy].

// end::cli-tool[]

== Logging

If you are using a Couchbase Lite release prior to 2.5 see <<pre-2x5-logging, Deprecated functionality>>

include::{root-commons}logging.adoc[leveloffset=+2]

[#pre-2x5-logging]
=== Logging functionality prior to Release 2.5

include::{root-partials}logging-pre2.5.adoc[]


// == Loading a pre-built database

// include::{root-partials}database-load-prebuilt.adoc[]

// DO NOT DELETE
// Include standard footer
include::{root-partials}block-related-content-std.adoc[]
// DO NOT DELETE

// DO NOT DELETE
include::{root-partials}_unset-platform.adoc[]
// DO NOT DELETE
// END: inclusion-page - common-database.adoc[]