// BEGIN -- page-inclusion -- common-database.adoc
// Applies to all platforms with some platform-specific differences


// include::{root-partials}_set-platform.adoc[]

:param-related: {blob--xref} | {document--xref} | {indexing--xref}
:topic-group: Topic Group -- Data Model
include::{root-partials}_show_page_header_block.adoc[]

:fn-2-8: footnote:fn28[Commencing with Release 2.8]
:fnref-2-8: footnote:fn28[]

// BEGIN: Conditional Block -- applies to Android and JVM Java
ifdef::is-android,is-java[]
// Output block only for Android and Java modules


== Initializer


Your first step in using the API must be to call its initializer.
An exception is raised if any other API method is invoked before the initializer.

.Initializer code
[#ex-init-cdl]
:param-tags: sdk-initializer
include::{root-partials}block_tabbed_code_example.adoc[]
:param-tags!:


endif::[]
// END: Conditional Block -- applies to Android and JVM Java


[#open-db]
== Create or Open Database


You can create a new database and-or open an existing database, using the {url-api-class-database} class.
Just pass in a database name and optionally a {url-api-class-databasecfg} -- see <<ex-dbopen>>.

Things to watch for include:

* If the named database does not exist in the specified, or default, location then a new one is created
* The database is created in a default location unless you  specify a directory for it -- see: {url-api-class-databasecfg} and {url-api-method-databasecfg-setdir}
+
--
TIP: Best Practice is to always specify the path to the database explicitly.

Typically, the default location for {param-title} is
ifndef::is-csharp[the application sandbox]
ifdef::is-c[or current working directory]
.
ifdef::is-csharp[]
a platform-dependant location:

include::{module-partials}database-finding-file.adoc[tags=list-only]
endif::is-csharp[]

See also <<lbl-find-db-loc>>.
--

[#ex-dbopen]
.Open or create a database
:param-tags: new-database
include::{root-partials}block_tabbed_code_example.adoc[]
:param-tags!:
// <.> Here we are specifying the database directory path.

== Close Database

You are advised to incorporate the closing of all open databases into your application workflow.

Closing a database is simple, just use {url-api-method-database-close} -- see: <<ex-dbclose>>.
This also closes
ifndef::is-c[{fn-2-8}]
active replications, listeners and-or live queries connected to the database.

NOTE: Closing a database soon after starting a replication involving it can cause an exception as the asynchronous `replicator (start)` may not yet be `connected`.

ifndef::is-c[]
.Safely Closing a Database pre 2.8
TIP: Before closing, check that any attached listeners (query/replication/change) indicate they are at least at `connected` status before closing -- see for example: {replication--xref--monitor-status}.
endif::is-c[]

.Close a Database
[#ex-dbclose]
:param-tags: close-database
include::{root-partials}block_tabbed_code_example.adoc[]
:param-tags!:


== Database Encryption

:param-language: {param-name}
include::{root-commons}database-encryption.adoc[]


[#lbl-find-db-loc]
== Finding a Database File


:tags: {empty}
ifdef::is-csharp[]
:tags: "tags=list-only"
endif::[]

include::{module-partials}database-finding-file.adoc[{tags}]


[#lbl-db-util]
== Database Maintenance

From time to time it may be necessary to perform certain maintenance activities on your database, for example to
compact the database file, removing unused documents and blobs no longer referenced by any documents.

Couchbase Lite's API provides the {url-api-method-database-performMaintenance} method.
The available maintenance operations, including `compact` are as shown in the enum {url-api-enum-database-maintenance-type} to accomplish this.

This is a resource intensive operation and is not performed automatically.
It should be run on-demand using the API.
If in doubt, consult Couchbase support.


[#cli-tool]
== Command Line Tool

// tag::cli-tool[]
`cblite` is a command-line tool for inspecting and querying Couchbase Lite databases.

You can download and build it from the couchbaselabs https://github.com/couchbaselabs/couchbase-mobile-tools/blob/master/README.cblite.md[GitHub repository].
Note that the `cblite` tool is not supported by the https://www.couchbase.com/support-policy[Couchbase Support Policy].

// end::cli-tool[]

ifndef::is-c[]
== Troubleshooting
You should use console logs as your first source of diagnostic information.
If the information in the default logging level is insufficient you can focus it on database errors and generate more verbose messages -- see: <<ex-logdb>>.

For more on using Couchbase logs -- see: {troubleshooting-logs--xref}.

[#ex-logdb]
.Increase Level of Database Log Messages
:param-tags: console-logging-db
include::{root-partials}block_tabbed_code_example.adoc[]
:param-tags!:
endif::is-c[]

// DO NOT DELETE
// Include standard

include::{root-partials}block-related-content-std.adoc[]
// DO NOT DELETE

// DO NOT DELETE
// include::{root-partials}_unset-platform.adoc[]
// DO NOT DELETE
// END: inclusion-page - common-database.adoc[]