// The admonition does not apply to C as it references upgrading from versions 2.x.
// CBL-C started at version 3.0
ifndef::is-c[]
include::{root-partials}block-caveats.adoc[tag="cbl-3-0-0-reindexing"]
endif::is-c[]

== {version-full} Upgrade

The action will take place automatically and can lead to some delay in the database becoming available for use in your application.

In addition, if you are syncing with a {version-full} Sync Gateway, you should be aware of the significant configuration enhancements introduced and their impact.
See xref:sync-gateway::upgrading.adoc[Upgrading Sync Gateway] for more details.
This is a one-way conversion.


== Upgrading to the new CBL Logging API

Couchbase Lite 3.2.2 introduces 

=== LogSinks

A lot of the new logging API will seem very familiar: many of the concepts are
the same.  There are still three places that log messages can be sent: the log
files, the console, and custom code and Couchbase still logs its messages in a
handfull of named "domains" and at common log levels: `debug` the most verbose,
ane `error` only for serious failures.

The first thing to note is that the three destinations for logs have been
renamed as "LogSinks", in keeping with common source/sink terminology. The
`FileLogSink`, the `ConsoleLogSink` and the `CustomLogSink` are all installed in
an instance of `LogSinks`.  To get the instance of `LogsSinks`, use the method
`LogSinks.get()`.  This is the analog of getting the instance of Log from
`Database.log` in the old API.

Perhaps the biggest difference between the new and the old API is that
`LogSinks` are immutable: you set the level and domain at which they log in
their constructors. The only way to change, for instance, the level at which the
`ConsoleLogSink` forwards messages to the console is to install a new one
created for the new log level.

All three log sinks are initialized by default.  If you want to stop all logging
to one of them, though, just set the sink to null:
`LogSinks.get().setFile(null)`

=== Logging to the Console

The changes necessary convert the installation of a console logger from the old
to the new API are minimal <1>.  Simply create an instance of `ConsoleLogSink`
initialized with the desired log level and domains and install it using
`LogSinks.setCustom`. (Snippet here)

=== Logging to the Couchbase File Log

The changes necessary to convert the installation of a file logger are similarly easy. 
Instead of configuring a `FileLogger` using a`LogFileConfiguration`, use
the `FileLogSink.Builder` to create a new `FileLogSink` with the desired
properties and install it <2>. (Set file snippet)  Note, though, that `setRotateCount` from the old
API is slightly different from `setMaxKeptFiles`.  The latter is the maximum
number of log files that will exist at any time and is the count of rotated
files plus one.

=== Using a Custom Logger

Installing a custom log sink with the new API is also streamlined: create an
instance of your custom sink and use `LogSinks.get().setCustom` to install it
<3>. (new custom snippet) As with the other log sinks, you will have to specify the level and domain
at which Couchbase logs are forwarded to your custom sink at its creation.

Your custom log sink code will have to change as well.  The most significant
change is that instead of implementing the `Logger` interface, a custom log sink
must extend the `BaseLogSink` class <4>.  The `BaseLogSink` class does not have
a no-args constructor: you must specify at least the level at which Couchbase
logs will be forwarded to the logger <6>.  Unless otherwise specified logs from
all Couchbase domains will be forwarded to the custom log sink.

A second important change is that your logger will receive only logs at the
level and domain for which it is initialized.  There is no need to record or
filter the logs forwarded to the protected `writeLog` method (which replaces the
public `log` method from the old API) <5> <7>.

Related to this last point, the Couchbase `Logger`s, now `LogSink`s are meant to
support logging by the Couchbase Lite platform.  They were never meant as a
general framework for logging.  With the new API, customer code can no longer
log, directly, to any of the Couchbase log sinks.  The Console and File log
sinks are (or will be in subsequent releases) final classes and do not publish
methods that allow writing logs.  If you need to log e.g., to the console, you
will have to create your own way of doing so.

// All API and other listed changes included in the other platforms do not apply to CBL-C for the following reasons
// The changes apply to pre 3.x versions (CBL-C started at 3.0)
// Or they relate to Querybuilder functionality - CBL-C doesn't have Querybuilder.
ifndef::is-c[]
=== API Changes

include::{module-partials}api-changes.adoc[tag=content, leveloffset=+2]



[#lbl-db-upgrades]
== 1.x Databases Upgrades to 2.x

Databases created using Couchbase Lite 1.2 or later can still be used with Couchbase Lite 2.x; but will be automatically updated to the  current 2.x version.
This feature is only available for the default storage type (i.e., not a ForestDB database).

=== Encrypted Databases
The automatic migration feature does not support encrypted databases.
So if the 1.x database is encrypted you will first need to disable encryption using the Couchbase Lite 1.x API (see the https://docs-archive.couchbase.com/couchbase-lite/1.4/{source-language}.html#database-encryption[1.x Database Guide]).

Thus, to upgrade an encrypted 1.x database, you should do the following:

// set the correct language name for 1.4 pages
ifndef::param-language:[:param-language: {param-name}]
ifeval::["{param-language}"=="{lang-name-android}"]
:param-language: {lang-name-java}
endif::[]
.Upgrading Encrypted Databases
****
. Disable encryption using the Couchbase Lite 1.x framework (see https://docs-archive.couchbase.com/couchbase-lite/1.4/{param-language}.html#database-encryption[1.x encryption guide])
. Open the database file with encryption enabled using the Couchbase Lite 2.x framework.
****

Since it is not possible to package Couchbase Lite 1.x and Couchbase Lite 2.x in the same application this upgrade path would require two successive upgrades.

If you are using Sync Gateway to synchronize the database content, it may be preferable to run a pull replication from a new 2.x database with encryption enabled and delete the 1.x local database.


=== Handling of Existing Conflicts

If there are existing conflicts in the 1.x database, the automatic upgrade process copies the default winning revision to the new database and does NOT copy any conflicting revisions.

This functionality is related to the way conflicts are now being handled in Couchbase Lite -- see {conflict--xref}.

Optionally, existing conflicts in the 1.x database can be resolved with the https://docs-archive.couchbase.com/couchbase-lite/1.4/{source-language}.html#resolving-conflicts[1.x API] prior to the database being upgraded.

=== Handling of Existing Attachments

Attachments persisted in a 1.x database are copied to the new database.
NOTE: The relevant Couchbase Lite API is now called the `Blob` API not the `Attachments` API.

The functionally is identical but the internal schema for attachments has changed.

Blobs are stored anywhere in the document, just like other value types.
Whereas in 1.x they were stored under the `_attachments` field.

The automatic upgrade functionality *does not* update the internal schema for attachments, so they remain accessible under the `_attachments` field.
See <<ex-get-att>> for how to retrieve an attachment that was created in a 1.x database with a 2.x API.

.Retrieve 1.x Attachment
[#ex-get-att]
:param-tags: 1x-attachment
include::{root-partials}block_tabbed_code_example.adoc[]
:param-tags!:

=== Replication Compatibility

The current replication protocol is not backwards compatible with the 1.x replication protocol.
Therefore, to use replication with Couchbase Lite 2.x, the target Sync Gateway instance must also be upgraded to 2.x.

Sync Gateway 2.x will continue to accept clients that connect through the 1.x protocol.

It will automatically use the 1.x replication protocol when a Couchbase Lite 1.x client connects through \http://localhost:4984/db and the 2.0 replication protocol when a Couchbase Lite 2.0 client connects through ws://localhost:4984/db.

This allows for a smoother transition to get all your user base onto a version of your application built with Couchbase Lite 2.x.

endif::is-c[]

ifdef::is-ios[]
== Xcode

The API has changed in Couchbase Lite 2.0 and will require porting an application that is using Couchbase Lite 1.x API to the Couchbase Lite 2.0 API.
To update an Xcode project built with Couchbase Lite 1.x:

* Remove the existing *CouchbaseLite.framework* dependency from the Xcode project.
* Remove all the Couchbase Lite 1.x dependencies (see the https://docs-archive.couchbase.com/couchbase-lite/1.4/{source-language}.html#getting-started[1.x installation guide]).
* Install the Couchbase Lite 2.0 framework in your project  -- see {gs-install--xref}.
At this point, there will be many compiler warnings.
Refer to the examples on this page to learn about the new API.
* Build & run your application.

endif::is-ios[]
ifdef::is-net[]
== Visual Studio

The public facing API has completely changed in Couchbase Lite 2.0 and will require a re-write to upgrade an application that is using Couchbase Lite 1.x.
To update an Xcode project built with Couchbase Lite 1.x:

* Remove the existing Couchbase Lite nuget package from the Visual Studio project.
* Remove all the Couchbase Lite 1.x dependencies -- see the  https://docs-archive.couchbase.com/couchbase-lite/1.4/csharp.html#getting-started[1.x installation guide].
* Install the Couchbase Lite 2.0 framework in your project  -- see {gs-install--xref}.
At this point, there will be many compiler warnings.
Refer to the examples on this page to learn about the new API.
* Build & run your application.
endif::is-net[]
ifdef::is-android[]
== Android Studio


The API changed in Couchbase Lite 2.0 and you will need to port any application that is using Couchbase Lite 1.x API to the latest Couchbase Lite API.
To update an Android project built with Couchbase Lite 1.x:

* Remove the existing Couchbase Lite dependency from the Android Studio project.
* Install the Couchbase Lite framework in your project -- see the https://docs-archive.couchbase.com/couchbase-lite/1.4/java.html#getting-started[Getting Started].
At this point, there will be many compiler warnings.
Refer to the examples on this page to learn about the new API.
* Build & run your application.

endif::is-android[]

== Downgrading Couchbase Lite

=== Downgrading Between Major Releases

*No Downgrade Support* - Downgrades between major versions of Couchbase Lite (CBL) are not supported.
Once you upgrade to a new major version, downgrading to a previous major version may lead to incompatibility issues.

For example, Upgrading from CBL 2.x.x to CBL 3.x.x does not guarantee the ability to revert to CBL 2.x.x.

=== Downgrading Between Minor Releases

*Conditional Downgrade Support* - Downgrade support for minor releases is considered on a case-by-case basis.
The release notes for each minor version will clarify whether downgrades are supported.

For example, if a new minor version such as CBL 3.1.0 is released the release notes will specify whether downgrading to CBL 3.0.x is supported.

=== Downgrading Between Patch Releases

*Full Downgrade Support* - Downgrades between patch releases are supported.
Users can safely downgrade between different patch versions within the same minor release.

For example, if you're running CBL 3.1.6 you can downgrade to CBL 3.1.4 or CBL 3.1.3 without issues.

// DO NOT DELETE
// Include standard footer
include::{root-partials}block-related-content-std.adoc[]
// include::{root-partials}_unset-platform.adoc[]
// DO NOT DELETE
