// BEGIN -- inclusion -- common-sgw-replication.adoc

// DO NOT DELETE
// Include standard header
:param-related: {conflict--xref} | {dbreplica--xref} | xref:{p2psync-websocket--page}[Peer-to-Peer]
:topic-group: Topic Group -- Replication
include::{root-partials}block-abstract.adoc[]
:is-p2p!:
:is-sgw:
// DO NOT DELETE

ifdef::is-android[]
include::{root-partials}_block-caveats.adoc[tags=android-constraints]
endif::[]
include::{root-partials}_block-caveats.adoc[tags=code-disclaimer]

== Introduction

Couchbase Lite for {param-title} provides API support for secure, bi-directional, synchronization of data changes between mobile applications and a central server database.
It does so by using a _replicator_ to interact with Sync Gateway.

The _replicator_ is designed to manage replication of documents and-or document changes between a source and a target database.
For example, between a local Couchbase Lite database and remote Sync Gateway database, which is ultimately mapped to a bucket in a Couchbase Server instance in the cloud or on a server.

This page shows sample code and configuration examples covering the implementation of a replication using Sync Gateway.

Your application runs a replicator (also referred to here as a client), which  will initiate connection with a Sync Gateway (also referred to here as a server) and participate in the replication of database changes to bring both local and remote databases into sync.

Subsequent sections provide additional details and examples for the main configuration options.


== Replication Protocol

=== Scheme

Couchbase Mobile uses a replication protocol based on WebSockets for replication.
To use this protocol the replication URL should specify WebSockets as the URL scheme (see the <<lbl-cfg-tgt>> section below).

Incompatibilities::
Couchbase Lite's replication protocol is *incompatible* with CouchDB-based databases.
And since Couchbase Lite 2.x+ only supports the new protocol, you will need to run a version of Sync Gateway that supports it -- see: {compatibility--xref}.

Legacy Compatibility::
Clients using Couchbase Lite 1.x can continue to use `http` as the URL scheme.
Sync Gateway 2.x+ will automatically use:
* The 1.x replication protocol when a Couchbase Lite 1.x client connects through `\http://localhost:4984/db`
* The 2.0 replication protocol when a Couchbase Lite 2.0 client connects through `ws://localhost:4984/db`.

You can find further information in our blog: {url-cb-blog-replication}.

[#lbl-repl-ord]
=== Ordering

To optimize for speed, the replication protocol doesn't guarantee that documents will be received in a particular order.
So we don't recommend to rely on that when using the replication or database change listeners for example.

ifdef::is-android[]
include::{module-partials}sgw-replication-custom-executor.adoc[]
endif::[]

// include::{root-partials}_block-caveats.adoc[tags=securestorage]

// tag::replicator-config-sample[]
== Configuration Summary
You should configure and initialize a replicator for each Couchbase Lite database instance you want to sync.
<<ex-simple-repl>> shows the configuration and initialization process.

ifdef::is-android[]
[NOTE]
--
include::{root-partials}_block-caveats.adoc[tags=android-threads]
--
endif::[]

// Example 1
[#ex-simple-repl]
.Replication configuration and initialization
:param-tags: p2p-act-rep-func
include::{root-partials}_block_tabbed_code_example.adoc[]
:param-tags!:

*Notes on Example*

<.> get endpoint for target DB
ifndef::is-c[]
<.> Use the {url-api-class-replicator-config} class's constructor -- {url-api-constructor-replicator-config-db-tgt} -- to initialize the replicator configuration with the local database -- see also: <<lbl-cfg-tgt>>
endif::is-c[]
ifdef::is-c[]
<.> Set local database and target endpoint
endif::is-c[]
<.> The default is to auto-purge documents that this user no longer has access to -- see: <<anchor-auto-purge-on-revoke>>.
Here we over-ride this behavior by setting its flag false.

<.> Configure how the client will authenticate the server.
Here we say connect only to servers presenting a self-signed certificate.
By default, clients accept only servers presenting certificates that can be verified using the OS bundled Root CA Certificates -- see: <<lbl-svr-auth>>.
endif::is-c[]
<.> Configure the client-authentication credentials (if required).
These are the credential the client will present to {sgw} if requested to do so. +
Here we configure to provide _Basic Authentication_ credentials.
Other options are available -- see: <<lbl-client-auth>>.

<.> Configure how the replication should handle conflict resolution -- see: {conflict--xref} topic for mor on conflict resolution.

<.> Initialize the replicator using your configuration -- see: <<lbl-init-repl>>.

<.> Optionally, register an observer, which will notify you of changes to the replication status -- see: <<lbl-repl-mon>>

<.> Start the replicator  -- see: <<lbl-repl-start>>.
endif::is-c[]
ifdef::is-c[]

endif::is-c[]


[#lbl-cfg-repl]
== Configure

In this section::
+
--
<<lbl-cfg-tgt>>
|  <<lbl-cfg-sync>>
|  <<lbl-cfg-keep-alive>>
|  <<lbl-user-auth>>
ifndef::is-c[|  <<lbl-svr-auth>>]
|  <<lbl-client-auth>>
|  <<lbl-repl-evnts>>
|  <<lbl-repl-hdrs>>
|  <<lbl-repl-ckpt>>
|  <<lbl-repl-fltrs>>
|  <<lbl-repl-chan>>
|  <<anchor-auto-purge-on-revoke>>
|  <<lbl-repl-delta>>
--

[#lbl-cfg-tgt]
=== Configure Target

include::{root-commons}sgw-replication-cfg-tgt.adoc[]


[#lbl-cfg-sync]
=== Sync Mode

include::{root-commons}sgw-replication-cfg-sync-mode.adoc[]

[#lbl-cfg-keep-alive]
=== Retry Configuration

include::{root-commons}sgw-replication-cfg-retry.adoc[]

[#lbl-user-auth]
=== User Authorization

include::{root-partials}authorization.adoc[]

ifndef::is-c[]
[#lbl-svr-auth]
=== Server Authentication

Define the credentials your app (the client) is expecting to receive from the Sync Gateway (the server) in order to ensure it is prepared to continue with the sync.

include::{root-commons}set-server-authentication.adoc[]

This all assumes that you have configured the Sync Gateway to provide the appropriate SSL certificates, and have included the appropriate certificate in your app bundle -- for more on this see: <<lbl-cert-pinning>>.

endif::is-c[]


[#lbl-client-auth]
=== Client Authentication

include::{root-partials}authentication.adoc[]


[#lbl-repl-hdrs]
=== Custom{nbsp}Headers

include::{root-partials}replication-custom-header.adoc[]

.Setting custom headers
[#ex-cust-hdr]
:param-tags: replication-custom-header
include::{root-partials}_block_tabbed_code_example.adoc[]
:param-tags!:


[#lbl-repl-fltrs]
=== Replication Filters

include::{root-partials}replication-filters.adoc[]

[#lbl-repl-chan]
=== Channels

include::{root-partials}replication-channels.adoc[]


[#anchor-auto-purge-on-revoke]
=== Auto-purge on Channel Access Revocation

include::{root-commons}sgw-replication-cfg-autopurge.adoc[]


[#lbl-repl-delta]
=== Delta Sync

// tag::rep-delta-sync-concept[]

include::{root-partials}_block-caveats.adoc[tag=ee-only-feature]

With Delta Sync footnote:[Couchbase Mobile 2.5+], only the changed parts of a Couchbase document are replicated.
This can result in significant savings in bandwidth consumption as well as throughput improvements, especially when network bandwidth is typically constrained.

Replications to a Server (for example, a Sync Gateway, or passive listener) automatically use delta sync if the property is enabled at database level by the server -- see: xref:sync-gateway:ROOT:refer/config-properties.adoc#databases-foo_db-delta_sync[databases.$db.delta_sync.enabled].

{dbreplica--xref} replications automatically *disable* delta sync, whilst xref:{p2psync-websocket--page}[Peer-to-Peer] replications automatically *enable* delta sync.

// end::rep-delta-sync-concept[]


[#lbl-init-repl]
== Initialize

In this section::
<<lbl-repl-start>>  | <<lbl-repl-ckpt>>

[#lbl-repl-start]
=== Start Replicator

include::{root-commons}sgw-replication-init.adoc[]


[#lbl-repl-ckpt]
=== Checkpoint Starts

include::{root-partials}replication-checkpoint.adoc[]

.Resetting checkpoints
[#ex-repl-ckpt]
:param-tags: replication-reset-checkpoint
include::{root-partials}_block_tabbed_code_example.adoc[]
:param-tags!:
<.> Set start's reset option to `true`. +
ifndef::is-c[The default `false` is shown here for completeness only; it is unlikely you would explicitly use it in practice.]

[#lbl-repl-mon]
== Monitor

include::{root-commons}sgw-replication-monitor.adoc[leveloffset=+1]


[#lbl-repl-stop]
== Stop

include::{root-commons}sgw-replication-stop.adoc[]


[#lbl-nwk-errs]
== Error Handling

When _replicator_ detects a network error it updates its status depending on the error type (permanent or temporary) and returns an appropriate HTTP error code.

The following code snippet adds a `Change Listener`, which monitors a replication for errors and logs the the returned error code.

.Monitoring for network errors
:param-tags: replication-error-handling
include::{root-partials}_block_tabbed_code_example.adoc[]
:param-tags!:

*For permanent network errors* (for example, `404` not found, or `401` unauthorized):
_Replicator_ will stop permanently, whether `setContinuous`  is _true_ or _false_. Of course, it sets its status to `STOPPED`

*For recoverable or temporary errors:* _Replicator_ sets its status to `OFFLINE`, then:

* If `setContinuous=_true_` it retries the connection indefinitely
* If `setContinuous=_false_` (one-shot) it retries the connection a limited number of times.

The following error codes are considered temporary by the Couchbase Lite replicator and thus will trigger a connection retry.

* `408`: Request Timeout
* `429`: Too Many Requests
* `500`: Internal Server Error
* `502`: Bad Gateway
* `503`: Service Unavailable
* `504`: Gateway Timeout
* `1001`: DNS resolution error


== Load Balancers

Couchbase Lite footnote:[From 2.0] uses WebSockets as the communication protocol to transmit data.
Some load balancers are not configured for WebSocket connections by default (NGINX for example);
so it might be necessary to explicitly enable them in the load balancer's configuration (see xref:sync-gateway::load-balancer.adoc[Load Balancers]).

By default, the WebSocket protocol uses compression to optimize for speed and bandwidth utilization.
The level of compression is set on Sync Gateway and can be tuned in the configuration file (xref:sync-gateway:ROOT:refer/config-properties.adoc#replicator_compression[`replicator_compression`]).

// === Replicator Notifications on a Custom Executor

[#lbl-cert-pinning]
== Certificate Pinning

Couchbase Lite for {param-title} supports certificate pinning.

Certificate pinning is a technique that can be used by applications to "pin" a host to its certificate.
The certificate is typically delivered to the client by an out-of-band channel and bundled with the client.
In this case, Couchbase Lite uses this embedded certificate to verify the trustworthiness of the server (for example, a Sync Gateway) and no longer needs to rely on a trusted third party for that (commonly referred to as the Certificate Authority).

The following steps describe how to configure certificate pinning between Couchbase Lite and Sync Gateway.

. xref:sync-gateway::security.adoc#creating-your-own-self-signed-certificate[Create your own self-signed certificate] with the `openssl` command.
After completing this step, you should have 3 files: `cert.pem`, `cert.cer` and `privkey.pem`.
. xref:sync-gateway::security.adoc#installing-the-certificate[Configure Sync Gateway] with the `cert.pem` and `privkey.pem` files.
After completing this step, Sync Gateway is reachable over `https`/`wss`.
. On the Couchbase Lite side, the replication must point to a URL with the `wss` scheme and configured with the `cert.cer` file created in step 1.
+
This example loads the certificate from the application sandbox, then converts it to the appropriate type to configure the replication object.

.Cert Pinnings
[#ex-crt-pinning]
:param-tags: certificate-pinning
include::{root-partials}_block_tabbed_code_example.adoc[]
:param-tags!:

. Build and run your app.
The replication should now run successfully over https/wss with certificate pinning.

For more on pinning certificates see the blog entry: {url-cb-blog-cert-pinning}

ifndef::is-c[]
[#lbl-trouble]
== Troubleshooting

=== Logs
As always, when there is a problem with replication, logging is your friend.
You can increase the log output for activity related to replication with Sync Gateway -- see <<ex-logs>>.

[#ex-logs]
.Set logging verbosity
:param-tags: replication-logging
include::{root-partials}_block_tabbed_code_example.adoc[]
:param-tags!:


For more on troubleshooting with logs, see: {troubleshooting-logs--xref}.
endif::is-c[]


=== Authentication Errors
If Sync Gateway is configured with a self signed certificate but your app points to a `ws` scheme instead of `wss` you will encounter an error with status code `11006` -- see: <<ex-11006>>

[#ex-11006]
.Protocol Mismatch
====
[source,console]
----
CouchbaseLite Replicator ERROR: {Repl#2} Got LiteCore error: WebSocket error 1006 "connection closed abnormally"
----
====

If Sync Gateway is configured with a self signed certificate, and your app points to a `wss` scheme but the replicator configuration isn't using the certificate you will encounter an error with status code `5011` -- see: <<ex-5011>>

[#ex-5011]
.Certificate Mismatch or Not Found

====
[source,text]
----
CouchbaseLite Replicator ERROR: {Repl#2} Got LiteCore error: Network error 11 "server TLS certificate is self-signed or has unknown root cert"
----
====

// DO NOT DELETE
// Include standard footer
include::{root-partials}block-related-content-std.adoc[]
:is-sgw!:
// DO NOT DELETE

// END -- inclusion -- common-sgw-replication.adoc
