== Upgrading to the New CBL Logging API

CAUTION: Use of the deprecated and new Logging API at the same time is not supported.

You can find information about the new Couchbase Lite Logging API introduced in Couchbase Lite 3.2.2.

ifndef::is-c[]

For information about the now deprecated earlier version of the Logging API, see xref:3.1@couchbase-lite:{param-module}:troubleshooting-logs.adoc[].

endif::is-c[]

== LogSinks

Couchbase Lite 3.2.2 introduces a new Logging API.
The new Logging API has the following benefits:

* Log sinks are now thread safe, removing risk of inconsistent states during initialization.

* Simplified API and reduced implementation complexity.

The new logging API retains many of the core concepts of the previous API.

The first thing to note is that the three destinations for logs have been renamed as `LogSinks`, in keeping with common source/sink terminology.

The `FileLogSink`, the `ConsoleLogSink` and the `CustomLogSink` are all to be installed in an instance of `LogSinks`.

Only `ConsoleLogSink` is enabled for all logging domains at the warning level by default.
To enable a specific type of log sink, create a log sink object of that type, set its minimum log level and domains, and assign it to `LogSinks`.
To disable a log sink, set it to null or use a log sink with `LogLevel.NONE`.

Couchbase still logs its messages in a handful of named domains and at common log levels: `LogLevel.DEBUG` the most verbose, and `LogLevel.ERROR` only for serious failures.

Accessing `LogSinks` depends on the platform.
In Java, use the method `LogSinks.get()` to obtain an instance.
In Swift, Objective-C, .NET, and C, `LogSinks` provides only static methods, without a singleton instance.

The biggest difference between the new and the old API is that `LogSinks` are immutable: you set the level and domain at which they log in their constructors.
For example, you can only change the level at which the `ConsoleLogSink` forwards messages to the console by installing a new one created for the new log level.

Log output is split into the following streams:

* <<lbl-file-logsink>>
+
Each log level writes to a separate file and there is a single retention policy for all files

* <<lbl-console-logsink>>
+
--
You can independently configure and control console logs, which provides a convenient method of accessing diagnostic information during debugging scenarios.

With console logging, you can fine-tune diagnostic output to suit specific debug scenarios, without interfering with any logging required by Couchbase Support for the investigation of issues.
--

* <<lbl-custom-logsink>>
+
For greater flexibility you can implement a custom logging class.

[#lbl-console-logsink]
=== Logging to the Console

The changes necessary convert the installation of a console logger from the old to the new API are minimal.
Create an instance of `ConsoleLogSink` initialized with the desired log level and domains and install it.

ifdef::is-android[]

[tabs]
=====
Java::
+
--

.Old API
:!example-caption:
[source.no-callouts, java, indent=0]
----

include::java:example$snippets/common/main/java/com/couchbase/codesnippets/Examples.java[tags=console-logging]

----

.New API
:!example-caption:
[source.no-callouts, java, indent=0]
----

include::java:example$snippets/common/main/java/com/couchbase/codesnippets/Examples.java[tags=new-console-logging]

----
--

Kotlin::
+
--

.Old API
:!example-caption:
[source.no-callouts, kotlin, indent=0]
----

include::android:example$kotlin_snippets/app/src/main/kotlin/com/couchbase/codesnippets/BasicExamples.kt[tags=console-logging]

----

.New API
:!example-caption:
[source.no-callouts, kotlin, indent=0]
----

include::android:example$kotlin_snippets/app/src/main/kotlin/com/couchbase/codesnippets/BasicExamples.kt[tags=new-console-logging]

----
--
=====

endif::is-android[]
ifdef::is-java[]

.Old API
:!example-caption:
[source.no-callouts, java, indent=0]
----

include::java:example$snippets/common/main/java/com/couchbase/codesnippets/Examples.java[tags=console-logging]

----

.New API
:!example-caption:
[source.no-callouts, java, indent=0]
----

include::java:example$snippets/common/main/java/com/couchbase/codesnippets/Examples.java[tags=new-console-logging]

----

endif::is-java[]
ifdef::is-csharp[]

.Old API
:!example-caption:
[source.no-callouts, csharp, indent=0]
----
include::csharp:example$code_snippets/Program.cs[tags=console-logging]
----

.New API
:!example-caption:
[source.no-callouts, csharp, indent=0]
----
include::csharp:example$code_snippets/Program.cs[tags=new-console-logging]
----

endif::is-csharp[]
ifdef::is-objc[]

.Old API
:!example-caption:
[source.no-callouts, objc, indent=0]
----

include::objc:example$code_snippets/SampleCodeTest.m[tags=console-logging]

----

.New API
:!example-caption:
[source.no-callouts, objc, indent=0]
----

include::objc:example$code_snippets/SampleCodeTest.m[tags=new-console-logging]

----
endif::is-objc[]
ifdef::is-swift[]

.Old API
:!example-caption:
[source.no-callouts, swift]
----

include::swift:example$code_snippets/SampleCodeTest.swift[tags=console-logging]

----


.New API
:!example-caption:
[source.no-callouts, swift]
----

include::swift:example$code_snippets/SampleCodeTest.swift[tags=new-console-logging]

----
endif::is-swift[]
ifdef::is-c[]

.Old API
:!example-caption:
[source.no-callouts, c, indent=0]
----

include::c:example$code_snippets/main.cpp[tags=console-logging]

----


.New API
:!example-caption:
[source.no-callouts, c, indent=0]
----

include::c:example$code_snippets/main.cpp[tags=new-console-logging]

----
endif::is-c[]

[#lbl-file-logsink]
=== Logging to the Couchbase File Log

The changes necessary to convert the installation of a file logger are also similar.
Instead of configuring a `FileLogger` using a `LogFileConfiguration`, create a new `FileLogSink` with the desired properties and install it.

NOTE: `setRotateCount` from the old API is slightly different from `setMaxKeptFiles`.
`setMaxKeptFiles` is the maximum number of log files that will exist at any time and is the count of rotated files (`setRotateCount`) plus one.



ifdef::is-android[]

[tabs]
=====
Java::
+
--

.Old API
:!example-caption:
[source.no-callouts, java, indent=0]
----

include::java:example$snippets/common/main/java/com/couchbase/codesnippets/Examples.java[tags=file-logging]

----

.New API
:!example-caption:
[source.no-callouts, java, indent=0]
----

include::java:example$snippets/common/main/java/com/couchbase/codesnippets/Examples.java[tags=new-file-logging]

----
--

Kotlin::
+
--

.Old API
:!example-caption:
[source.no-callouts, kotlin, indent=0]
----

include::android:example$kotlin_snippets/app/src/main/kotlin/com/couchbase/codesnippets/BasicExamples.kt[tags=file-logging]

----

.New API
:!example-caption:
[source.no-callouts, kotlin, indent=0]
----

include::android:example$kotlin_snippets/app/src/main/kotlin/com/couchbase/codesnippets/BasicExamples.kt[tags=new-file-logging]

----
--
=====

endif::is-android[]
ifdef::is-java[]

.Old API
:!example-caption:
[source.no-callouts, java, indent=0]
----

include::java:example$snippets/common/main/java/com/couchbase/codesnippets/Examples.java[tags=file-logging]

----

.New API
:!example-caption:
[source.no-callouts, java, indent=0]
----

include::java:example$snippets/common/main/java/com/couchbase/codesnippets/Examples.java[tags=new-file-logging]

----

endif::is-java[]
ifdef::is-csharp[]

.Old API
:!example-caption:
[source.no-callouts, csharp, indent=0]
----
include::csharp:example$code_snippets/Program.cs[tags=file-logging]
----

.New API
:!example-caption:
[source.no-callouts, csharp, indent=0]
----
include::csharp:example$code_snippets/Program.cs[tags=new-file-logging]
----
endif::is-csharp[]
ifdef::is-objc[]

.Old API
:!example-caption:
[source.no-callouts, objc, indent=0]
----

include::objc:example$code_snippets/SampleCodeTest.m[tags=file-logging]

----

.New API
:!example-caption:
[source.no-callouts, objc, indent=0]
----

include::objc:example$code_snippets/SampleCodeTest.m[tags=new-file-logging]

----
endif::is-objc[]
ifdef::is-swift[]

.Old API
:!example-caption:
[source.no-callouts, swift]
----

include::swift:example$code_snippets/SampleCodeTest.swift[tags=file-logging]

----

.New API
:!example-caption:
[source.no-callouts, swift]
----

include::swift:example$code_snippets/SampleCodeTest.swift[tags=new-file-logging]

----
endif::is-swift[]
ifdef::is-c[]

.Old API
:!example-caption:
[source.no-callouts, c, indent=0]
----

include::c:example$code_snippets/main.cpp[tags=file-logging]

----

.New API
:!example-caption:
[source.no-callouts, c, indent=0]
----

include::c:example$code_snippets/main.cpp[tags=new-file-logging]

----
endif::is-c[]

[#lbl-custom-logsink]
=== Using a Custom Logger

Installing a custom log sink with the new API is also streamlined: create an instance of your custom sink, and to install it use `LogSinks.get().setCustom` in Java, or the appropriate static method in Swift, Objective-C, .NET, and C.

As with the other log sinks, you will have to specify the level and domain at which Couchbase logs are forwarded to your custom sink at its creation.

ifdef::is-android[]

Your custom log sink code will have to change as well.
For Android, the most significant change is that instead of _implementing_ the `Logger` interface, a custom log sink must _extend_ the `BaseLogSink` class.

The `BaseLogSink` class does not have a no-args constructor: you must specify at least the level at which Couchbase logs will be forwarded to the logger.

endif::is-android[]
ifdef::is-java[]

Your custom log sink code will have to change as well.
In Java, the most significant change is that instead of _implementing_ the `Logger` interface, a custom log sink must _extend_ the `BaseLogSink` class.

The `BaseLogSink` class does not have a no-args constructor: you must specify at least the level at which Couchbase logs will be forwarded to the logger.

endif::is-java[]
ifdef::is-csharp[]

Your custom log sink code will have to change as well.
For .NET, the most significant change is that instead of _implementing_ the `Logger` interface, a custom log sink must _extend_ the `BaseLogSink` class.

The `BaseLogSink` class does not have a no-args constructor: you must specify at least the level at which Couchbase logs will be forwarded to the logger.

endif::is-csharp[]
ifdef::is-objc[]

Your custom log sink code will have to change as well.
In Objective-C, which lacks abstract methods, a custom log sink implements LogSinkProtocol and is assigned to a CustomLogSink instance during creation.

endif::is-objc[]
ifdef::is-swift[]

Your custom log sink code will have to change as well.
In Swift, which lacks abstract methods, a custom log sink implements LogSinkProtocol and is assigned to a CustomLogSink instance during creation.

endif::is-swift[]
ifdef::is-c[]

Your custom log sink code will have to change as well.
In C, the custom log sink implementation is a callback that is assigned to CBLCustomLogSink object during creation.

endif::is-c[]

A second important change is that your logger will receive only logs at the level and domain for which it is initialized.
There is no need to record or filter the logs forwarded to the protected `writeLog` method which replaces the public `log` method from the old API.

Related to this last point, the Couchbase `Loggers`, now `LogSinks` are meant to support logging by the Couchbase Lite platform.
They were never meant as a general framework for logging.

IMPORTANT: With the new API, customer code can no longer log, directly, to any of the Couchbase log sinks.
The Console and File log sinks cannot be subclassed and do not publish methods that allow writing logs.
If you need to log to the console for example, you'll have to create your own way of doing so.

ifdef::is-android[]

[tabs]
=====
Java::
+
--

.Old API Implementing The Custom Logger Interface
:!example-caption:
[source.no-callouts, java, indent=0]
----

include::java:example$snippets/common/main/java/com/couchbase/codesnippets/Examples.java[tags=custom-logging]

----

.Old API Enable Custom Logger
:!example-caption:
[source.no-callouts, java, indent=0]
----

include::java:example$snippets/common/main/java/com/couchbase/codesnippets/Examples.java[tags=set-custom-logging]

----

.New API
:!example-caption:
[source.no-callouts, java, indent=0]
----

include::java:example$snippets/common/main/java/com/couchbase/codesnippets/Examples.java[tags=new-custom-logging]

----
--

Kotlin::
+
--

.Old API Implementing The Custom Logger Interface
:!example-caption:
[source.no-callouts, kotlin, indent=0]
----

include::android:example$kotlin_snippets/app/src/main/kotlin/com/couchbase/codesnippets/BasicExamples.kt[tags=custom-logging]

----

.Old API Enable Custom Logger
:!example-caption:
[source.no-callouts, kotlin, indent=0]
----

include::android:example$kotlin_snippets/app/src/main/kotlin/com/couchbase/codesnippets/BasicExamples.kt[tags=set-custom-logging]

----


.New API
:!example-caption:
[source.no-callouts, kotlin, indent=0]
----

include::android:example$kotlin_snippets/app/src/main/kotlin/com/couchbase/codesnippets/BasicExamples.kt[tags=new-custom-logging]

----
--
=====

endif::is-android[]
ifdef::is-java[]

.Old API Implementing The Custom Logger Interface
:!example-caption:
[source.no-callouts, java, indent=0]
----

include::java:example$snippets/common/main/java/com/couchbase/codesnippets/Examples.java[tags=custom-logging]

----

.Old API Enable Custom Logger
:!example-caption:
[source.no-callouts, java, indent=0]
----

include::java:example$snippets/common/main/java/com/couchbase/codesnippets/Examples.java[tags=set-custom-logging]

----

.New API
:!example-caption:
[source.no-callouts, java, indent=0]
----

include::java:example$snippets/common/main/java/com/couchbase/codesnippets/Examples.java[tags=new-custom-logging]

----

endif::is-java[]
ifdef::is-csharp[]

.Old API Implementing The Custom Logger Interface
:!example-caption:
[source.no-callouts, csharp, indent=0]
----
include::csharp:example$code_snippets/Program.cs[tags=custom-logging]
----

.Old API Enable Custom Logger
:!example-caption:
[source.no-callouts, csharp, indent=0]
----
include::csharp:example$code_snippets/Program.cs[tags=set-custom-logging]
----

.New API
:!example-caption:
[source.no-callouts, csharp, indent=0]
----
include::csharp:example$code_snippets/Program.cs[tags=new-custom-logging]
----
endif::is-csharp[]
ifdef::is-objc[]

.Old API Implementing The Custom Logger Interface
:!example-caption:
[source.no-callouts, objc, indent=0]
----

include::objc:example$code_snippets/SampleCodeTest.m[tags=custom-logging]

----

.Old API Set Custom Logger
:!example-caption:
[source.no-callouts, objc, indent=0]
----

include::objc:example$code_snippets/SampleCodeTest.m[tags=set-custom-logging]

----

.New API Custom Logger Class
:!example-caption:
[source.no-callouts, objc, indent=0]
----

include::objc:example$code_snippets/SampleCodeTest.m[tags=new-custom-logging]

----

.New API Enable Custom Logger
:!example-caption:
[source.no-callouts, objc, indent=0]
----

include::objc:example$code_snippets/SampleCodeTest.m[tags=set-new-custom-logging]

----
endif::is-objc[]
ifdef::is-swift[]

.Old API Implementing Custom Logger Interface
:!example-caption:
[source.no-callouts, swift]
----

include::swift:example$code_snippets/SampleCodeTest.swift[tags=custom-logging]

----

.Old API Enable Custom Logger
:!example-caption:
[source.no-callouts, swift]
----

include::swift:example$code_snippets/SampleCodeTest.swift[tags=set-custom-logging]

----

.New API Implementing Custom Logger Interface
:!example-caption:
[source.no-callouts, swift]
----

include::swift:example$code_snippets/SampleCodeTest.swift[tags=new-custom-logging]

----

.New API Enable Custom Logger
:!example-caption:
[source.no-callouts, swift]
----

include::swift:example$code_snippets/SampleCodeTest.swift[tags=set-new-custom-logging]

----
endif::is-swift[]
ifdef::is-c[]

.Old API
:!example-caption:
[source.no-callouts, c, indent=0]
----

include::c:example$code_snippets/main.cpp[tags=custom-logging;set-custom-logging]

----

.New API
:!example-caption:
[source.no-callouts, c, indent=0]
----

include::c:example$code_snippets/main.cpp[tags=new-custom-logging;set-new-custom-logging]

----
endif::is-c[]
