// = Custom Peer-to-Peer Synchronization
// :page-layout: article
// :page-status:
// :page-edition: Enterprise
// :page-role:
//
// include::partial$_std-cbl-hdr-android.adoc[]

// BEGIN::Local page attributes
// :blank-field: ____
// :lang-title: {lang-title-android}
// :module: {lang-mod-android}
// :packageNm: couchbase-lite-{module}
// :source-language: {lang-name-android}

// :snippet: {snippets-content--android}
// :url-issues-java: {url-github-cbl}{module}/issues
// :ziputils: {snippets-pfx--android}/code_snippets/ZipUtils.java

include::{root-partials}block-abstract.adoc[]

ifndef::release-status-cbl[:release-status-cbl!:]
ifeval::["{release-status-cbl}" == "gamma"]
[.pane__frame--orange]
.Author's Notes
--
This is the existing (2.7) content covering Couchbase Lite P2P

--
endif::[]

== Overview

.Enterprise Edition only
IMPORTANT: Peer-to-peer sync is an https://www.couchbase.com/products/editions[Enterprise Edition] feature.
You must purchase the Enterprise License which includes official https://www.couchbase.com/support-policy[Couchbase Support] to use it in production (also see the https://www.couchbase.com/licensing-and-support-faq[FAQ]).

This content covers how to integrate a custom __MessageEndpointListener__ solution with Couchbase Lite to handle the data transfer; the sending and receiving of data.
Where applicable, we discuss how to integrate Couchbase Lite into the workflow.

The following sections describe a typical peer-to-peer workflow.

== Peer Discovery

include::{root-partials}p2p-peer-discovery.adoc[]

== Peer Selection and Connection Setup

include::{root-partials}p2p-peer-selection.adoc[]

== Replication Setup

include::{root-partials}p2p-replication-setup.adoc[]

== Push/Pull Replication

include::{root-partials}p2p-push-pull-repl.adoc[]

== Connection Teardown

include::{root-partials}p2p-connection-teardown.adoc[]

