//= Using Peer-to-Peer Synchronization (websockets)
//:page-status:
//:page-edition: Enterprise
//:page-layout: article
//:page-role:
//
//include::partial$_std-cbl-hdr-{param-module}.adoc[]
//
// BEGIN::Local page attributes
//
//:url-issues-java: {url-github-cbl}{module}/issues
//:ziputils: {snippets-pfx--android}/code_snippets/ZipUtils.java
//

[abstract]
--
{description}
{param-abstract}
--

== Overview

.Enterprise Edition only
IMPORTANT: Peer-to-Peer Synchronization is an {url-enterprise} feature.
You must purchase the Enterprise License which includes official {url-support-policy} to use it in production (also see the {url-license-and-supp-faq}).

{glos-term-peer-to-peer-sync} allows devices running Couchbase Lite to directly sync Couchbase Lite database changes with each other without a server.

In this exchange, Couchbase Lite is responsible for storing the data and keeping track of the data exchange.
The data transfer itself -- the sending and receiving of data -- is handled by a communication framework.

With Couchbase you have the option of using either of the following approaches:

* Couchbase Mobile's out-of-the-box support for peer-to-peer sync
+
Using this approach Couchbase Lite enabled clients in an IP-based network can sync database changes.
+
For two instances of Couchbase Lite to sync, at least one of them must use a _URLEndpointListener_, which enables any Couchbase Lite database to become the remote in a replication by listening and exposing standard replication endpoints on a selected port.
* A custom built _MessageEndpointListener_
+
Using this approach developers can use the platform APIs and-or a third party Communication Framework such as
ifdef::is-android[]
Android's https://developers.google.com/nearby/messages/overview[Nearby Messages API]
endif::[]
ifdef::is-ios[]
Apple’s https://developer.apple.com/documentation/multipeerconnectivity[Multipeer Connectivity Framework]
endif::[]
, to implement their own listener.
+
This provides great flexibility. It will handle sending and receiving messages and supports multiple transport technologies -- WiFi and Bluetooth and uses whichever is available to establish a connection between devices.

In Couchbase Lite, a peer can take on one of these two roles:

Active Peer::
The peer that initializes the connection and replication (i.e the "client" side).
Passive Peer::
The passive side reacts to things that it receives but does not initiate any communication on its own (i.e. the "server" side).

[.pane__frames.no-title]
== {empty}

=== Websocket Listener

{p2psync-websocket--xref}

=== Custom Listener

{p2psync-custom--xref}
