// BEGIN -- inclusion -- common-sgw-replication-stop.adoc
//  Usage:
//  Params:
//    :is-p2p:  set when including from P2P topic such as common-p2psync-websocket-using-active
//  Included-by:
//    {root-commons}p2psync-websocket-using-active.adoc
//    {root-commons}sgw-replication.adoc
//  ####

Stopping a replication is straightforward.
It is done using {url-api-method-replicator-stop}.
This initiates an asynchronous operation and so is not necessarily immediate.
Your app should account for this potential delay before attempting any subsequent operations, for example closing the database.

You can find further information on database operations in {xref-cbl-gp-database}.

.Best Practice
[TIP]
--
. When you start a change listener, save the returned token, you will need it when you remove the listener
. Remove any active change listener prior to stopping your replication
. Ensure the replication has completely stopped by checking for a replication status = STOPPED, before closing any associated database
--

// Example 9
.Stop replicator
====
[source, {source-language}]
----

include::{snippet}[tags=p2p-act-rep-stop, indent=0]

----

<.> First we stop our change listener
<.> Here we initiate the stopping of the replication using the {url-api-method-replicator-stop} method. +
Remove any active <<lbl-repl-chng, change listener>> before stopping the replicator.

====

// END -- inclusion -- common-sgw-replication-monitor.adoc