// = Peer-to-Peer Synchronization
// :page-layout: article
// :page-status: {release-status-cbl} -- {release-comments-cbl}
// :page-edition: Under Development
// :page-role:
// :description: Couchbase mobile database peer-to-peer (P2P) synchronization concepts
//
// include::shared-mobile::partial$_attributes-shared.adoc[]
// include::ROOT:partial$_page-index.adoc[]
// include::ROOT:partial$_glossary-links.adoc[]
// include::ROOT:partial$_attributes-local.adoc[]
// include::{lang-mod-swift}:partial$_attributes-module.adoc[]
//
// // BEGIN::Local page attributes
// :blank-field: ____
// :lang-title: {lang-title-swift}
// :module: {lang-mod-swift}
// :packageNm: couchbase-lite-{module}
// :source-language: {lang-name-swift}
// :snippet: {snippets-content--swift}
// :url-issues: {url-github-cbl}{module}/issues
//
// // END::Local page attributes
//
// [abstract]
// {description}
//

// // BEGIN::required attributes
:this-module: {par-module}
// // END::required attributes

== Overview


.Enterprise Edition only
IMPORTANT: Peer-to-peer sync is an https://www.couchbase.com/products/editions[Enterprise Edition] feature.
You must purchase the Enterprise License which includes official https://www.couchbase.com/support-policy[Couchbase Support] to use it in production (also see the https://www.couchbase.com/licensing-and-support-faq[FAQ]).



Peer-to-peer sync allows devices running Couchbase Lite to directly sync data with each other.
As part of this, Couchbase Lite is responsible for storing the data and keeping track of the data exchange, but isn't responsible for the data transfer itself.
Sending and receiving data must be handled by the platform APIs or a third party framework.
In this section, we will refer to these third party frameworks as communication frameworks.

ifeval::[{this-module}={lang-mod-swift}]
On iOS, Apple's https://developer.apple.com/documentation/multipeerconnectivity[Multipeer Connectivity Framework] would be a good choice for the Communication Framework.
endif::[]

ifeval::[{this-module}={lang-mod-android}]
On Android, the https://developers.google.com/nearby/messages/overview[Nearby Messages API] would be a good choice for the Communication Framework.
endif::[]
This framework will handle sending and receiving messages and supports multiple transport technologies -- WiFi and Bluetooth and uses whichever is available to establish a connection between devices.

Thus, to enable peer-to-peer sync with Couchbase Lite, the application must use the Communication Framework with Couchbase Lite.
The following sections describe a typical peer-to-peer workflow.
Where applicable, we discuss how to integrate Couchbase Lite into the workflow.

In Couchbase Lite, a peer can take on one of these two roles:

Active Peer::
The peer that initializes the connection and replication (i.e the "client" side).
Passive Peer::
The passive side reacts to things that it receives but does not initiate any communication on its own (i.e. the "server" side).

=== Peer Discovery

include::{root-partials}p2p-peer-discovery.adoc[]

=== Peer Selection and Connection Setup

include::{root-partials}p2p-peer-selection.adoc[]

=== Replication Setup

include::{root-partials}p2p-replication-setup.adoc[]

=== Push/Pull Replication

include::{root-partials}p2p-push-pull-repl.adoc[]

=== Connection Teardown

include::{root-partials}p2p-connection-teardown.adoc[]


