
== Introduction
// tag::overview[]
Querying documents using a pre-existing database index is much faster because an index narrows down the set of documents to examine -- see: the {query-troubleshooting--xref} topic.

When planning the indexes you need for your database, remember that while indexes make queries faster, they may also:

* Make writes slightly slower, because each index must be updated whenever a document is updated
* Make your Couchbase Lite database slightly larger.

Too many indexes may hurt performance.
Optimal performance depends on designing and creating the _right_ indexes to go along with your queries.

include::{root-partials}block-caveats.adoc[tag=index-partial-value]

//end::overview[]


== Creating a new index

You can use {sqlpp} or QueryBuilder syntaxes to create an index


<<ex-create-index>> creates a new index for the `type` and `name` properties, shown in this data model:

[#ex-datamodel]
.Data Model
====
[source,json]
----
{
    "_id": "hotel123",
    "type": "hotel",
    "name": "The Michigander",
    "overview": "Ideally situated for exploration of the Motor City and the wider state of Michigan. Tripadvisor rated the hotel ...",
    "state": "Michigan"
}
----
====

=== {sqlpp}

The code to create the index will look something like this:

.Create index
[#ex-create-index]

:param-tags: query-index
include::{root-partials}block_tabbed_code_example.adoc[]
:param-tags!:

ifndef::is-c[]
=== QueryBuilder

TIP: See the {querybuilder--xref} topic to learn more about QueryBuilder.

The code to create the index will look something like this:

.Create index with QueryBuilder
[#ex-create-index]

:param-tags: query-index_Querybuilder
include::{root-partials}block_tabbed_code_example.adoc[]
:param-tags!:

endif::is-c[]




