// BEGIN -- inclusion -- common-querybuilder.adoc
//  Purpose -- describes the use of the query syntax
//
// // BEGIN::REQUIRED EXTERNALS
// :this-module: {par-module}
// :this-lang-title: {par-lang-title}
// :this-packageNm: {par-packageNm}
// :this-source-language: {par-source-language}
// :snippet: {par-snippet}
//:this-url-issues: {par-url-issues}
// END::REQUIRED EXTERNALS

// BEGIN::Local page attributes
:blank-field: ____
:menuitem-delimiter: {nbsp}{nbsp}|{nbsp}{nbsp}
:count-result-text: The result set representing a count is a key-value pair. The key being the count name, as defined using `SelectResult.as`

// END::Local page attributes

NOTE: The examples used in this topic are based on the _Travel Sample_ app and data introduced in the {url-tutorial-mobile-workshop} tutorial


== Introduction
Couchbase Lite for {param-title}'s database queries are defined using the QueryBuilder API.
This uses query statements of the form shown in <<ex-query-form>>.
The structure and semantics of the query format are based on that of Couchbase's xref:server:learn:data/n1ql-versus-sql.adoc[N1QL query language].

[#ex-query-form]
.Query Format
====
[source, SQL, subs="+attributes, +macros"]
----
SELECT {blank-field} // <.>
FROM 'database' // <.>
WHERE {blank-field}, // <.>
JOIN {blank-field} // <.>
GROUP BY {blank-field} // <.>
ORDER BY {blank-field} // <.>
----

Query Components::
<.> The <<lbl-select>> specifies the document properties that will be returned in the result set
<.> FROM specifies the database to query the documents from
<.> <<lbl-where>> specifies the query criteria. +
The `SELECT`ed properties of documents matching this criteria will be returned in the result set
<.> <<lbl-join>> specifies the criteria for joining multiple documents
<.> <<lbl-group>> specifies the criteria used to group returned items in the result set
<.> <<lbl-order>> specifies the criteria used to order the items in the result set
====

TIP: We recommend working through the query section of the {url-tutorial-mobile-workshop} as a good way to build your skills in this area.


== Indexing

Before we begin querying documents, let's briefly mention the importance of having a query index.
A query can only be fast if there's a pre-existing database index it can search to narrow down the set of documents to examine -- see: <<ex-indexing>>, which shows how to create an index and our {xref-cbl-pg-query-troubleshooting} topic.

TIP: See the {indexing--xref} topic to learn more about indexing.

[#ex-indexing]
.Creating a New Index
====
This example creates a new index for the `type` and `name` properties in the <<lbl-data-format>> shown.

[#lbl-data-format]
.Data Format
[{json-snippet}]
----
include::{root-examples}query-snippets.adoc[tags=query-result-format-props]
----

.Code to Create Index
[{code-snippet}]
----
include::{snippet}[tag=query-index,indent=0]
----
====

NOTE: Every index has to be updated whenever a document is updated, so too many indexes can hurt performance.
Thus, good performance depends on designing and creating the _right_ indexes to go along with your queries.


[#lbl-select]
== SELECT statement

--
In this section::
<<lbl-return-properties>>{menuitem-delimiter} <<lbl-return-all>>
Related::
<<lbl-resultsets, Handling result sets>>
--

Use the `SELECT` statement to specify which properties you want to return from the queried documents.
You can opt to retrieve entire documents, or just the specific properties you need.

[#lbl-return-all]
=== Return All Properties
Use the `SelectResult.all()` method to return all the properties of selected documents -- see: <<ex-select-all>>.

[#ex-select-all]
.Using SELECT to Retrieve All Properties
====
This query shows how to retrieve all properties from all documents in your database.

[{code-snippet}]
----
include::{snippet}[tag=query-select-all,indent=0]
----
====

The query.execute statement returns the results in a dictionary, where the key is the database name -- see <<ex-return-all>>.


[#ex-return-all]
.Return Data Format from SelectResult.all()
====
[{json-snippet}]
----

include::{root-examples}query-snippets.adoc[tags=query-result-format-all]

----
<.> Here we see the result for the first document matching the query criteria.
<.> Here we see the result for the next document matching the query criteria.

====

See: <<lbl-resultsets>> for more on processing query results.


[#lbl-return-properties]
=== Return Selected Properties
To access only specific properties, specify a comma separated list of `SelectResult` expressions, one for each property, in the select statement of your query  -- see: <<ex-select-properties>>

[#ex-select-properties]
.Using SELECT to Retrieve Specific Properties
====
In this query we retrieve and then print the `_id`, `type` and `name` properties of each document.

[{code-snippet}]
----
include::{snippet}[tag=query-select-props,indent=0]
----
====

The `query.execute` statement returns one or more key-value pairs, one for each SelectResult expression, with the property-name as the key -- see <<ex-return-properties>>

[#ex-return-properties]
.Select Result Format
====
[{json-snippet}]
----

include::{root-examples}query-snippets.adoc[tags=query-result-format-props]

----
<.> Here we see the result for the first document matching the query criteria.
<.> Here we see the result for the next document matching the query criteria.

====

See: <<lbl-resultsets>> for more on processing query results.


[#lbl-where]
== WHERE statement

In this section::
<<lbl-comp-ops>>{menuitem-delimiter}
<<lbl-coll-ops>>{menuitem-delimiter}
<<lbl-like-ops>>{menuitem-delimiter}
<<lbl-regex-ops>>{menuitem-delimiter}
<<lbl-deleted-ops>>

Like SQL, you can use the `WHERE` statement to choose  which documents are returned by your query.
The select statement takes in an `Expression`.
You can chain any number of Expressions in order to implement sophisticated filtering capabilities.


[#lbl-comp-ops]
=== Comparison Operators
The {url-api-classes-query-expression-comparators} can be used in the WHERE statement to specify on which property to match documents.
In the example below, we use the `equalTo` operator to query documents where the `type` property equals "hotel".

[{json-snippet}]
----

include::{root-examples}query-snippets.adoc[tags=query-result-format-props]

----

[{code-snippet}]
----
include::{snippet}[tag=query-where,indent=0]
----


[#lbl-coll-ops]
=== Collection Operators
{url-api-classes-query-arrayfunction-collection-ops} are useful to check if a given value is present in an array.


==== CONTAINS Operator
The following example uses the `{url-api-classes-query-arrayfunction}` to find documents where the `public_likes` array property contains a value equal to "Armani Langworth".

[{json-snippet}]
----
{
    "_id": "hotel123",
    "name": "Apple Droid",
    "public_likes": ["Armani Langworth", "Elfrieda Gutkowski", "Maureen Ruecker"]
}
----

[{code-snippet}]
----
include::{snippet}[tag=query-collection-operator-contains,indent=0]
----


==== IN Operator

The `IN` operator is useful when you need to explicitly list out the values to test against.
The following example looks for documents whose `first`, `last` or `username` property value equals "Armani".

[{code-snippet}]
----
include::{snippet}[tag=query-collection-operator-in,indent=0]
----


[#lbl-like-ops]
=== Like Operator
In this section::
<<lbl-string-match>>{menuitem-delimiter}
<<lbl-wild-match>>{menuitem-delimiter}
<<lbl-wild-chars>>

[#lbl-string-match]
==== String Matching
The {url-api-method-expression-like} operator can be used for string matching.

The `like` operator performs **case sensitive** matches. +
To perform case insensitive matching, use `Function.lower` or `Function.upper` to ensure all comparators have the same case, thereby removing the case issue.

[#ex-like-case-insensitive]
.Case-insensitive Matching
====
This query returns `landmark` type documents where the `name` matches the string "Royal Engineers Museum", regardless of how it is capitalized (so, it selects "royal engineers museum", "ROYAL ENGINEERS MUSEUM" and so on).

Note the use of `Function.lower` to transform `name` values to the same case as the literal comparator.

[{code-snippet}]
----
include::{snippet}[tag=query-like-operator,indent=0]
----
====

[#lbl-wild-match]
==== Wildcard Match

We can use `%` sign within a `like` expression to do a wildcard match against zero or more characters.
Using wildcards allows you to have some fuzziness in your search string.

In the example below, we are looking for documents of `type` "landmark" where the name property matches any string that begins with "eng" followed by zero or more characters, the letter "e", followed by zero or more characters.
Once again, we are using `Function.lower` to make the search case insensitive.

The following query will return "landmark" `type` documents with name matching "Engineers", "engine", "english egg" , "England Eagle" and so on.
Notice that the matches may span word boundaries.

[{code-snippet}]
----
include::{snippet}[tag=query-like-operator-wildcard-match,indent=0]
----


[#lbl-wild-chars]
==== Wildcard Character Match

We can use an `_` sign within a like expression to do a wildcard match against a single character.

In the example below, we are looking for documents of type "landmark" where the `name` property matches any string that begins with "eng" followed by exactly 4 wildcard characters and ending in the letter "r".
The following query will return "landmark" `type` documents with the `name` matching "Engineer", "engineer" and so on.

[{code-snippet}]
----
include::{snippet}[tag=query-like-operator-wildcard-character-match,indent=0]
----


[#lbl-regex-ops]
=== Regex Operator

Similar to the wildcards in `like` expressions, `regex` based pattern matching allow you to introduce an element of fuzziness in your search string.

*Note* though, that the `regex` operator is case sensitive.

TIP: For more on the regex spec used by {cbl} see http://www.cplusplus.com/reference/regex/ECMAScript/[cplusplus regex reference page^]

The code shown in <<ex-regex>> executes a query that will return documents of type "landmark" with a name matching "Engine", "engine" and so on.


[#ex-regex]
.Using Regular Expressions
====
This example returns documents with a `type` of "landmark" and a `name` property that matches any string that begins with "eng" and ends in the letter "e".

[{code-snippet}]
----
include::{snippet}[tag=query-regex-operator,indent=0]
----
<.> The `\b` specifies that the match must occur on word boundaries.
====


[#lbl-deleted-ops]
=== Deleted Document
You can query documents that have been deleted (tombstones)
footnote:[Starting in Couchbase Lite 2.5].

[#ex-del-qry]
.Query to select Deleted Documents
====
This example shows how to query deleted documents in the database.
The result set it returns is an array of key-value pairs.
One for each document matching the criteria -- see <<lbl-id-sel>> for how to work with this result set.

[{code-snippet}]
----

include::{snippet}[tag=query-deleted-documents,indent=0]

----
====

[#lbl-join]
== JOIN statement
The JOIN clause enables you to select data from multiple documents that have been linked by criteria specified in the JOIN statement. For example to combine airline details with route details, linked by the airline id -- see <<ex-join>>.

[#ex-join]
.Using JOIN to Combine Document Details
====
This example JOINS the document of type `route` with documents of type `airline` using the document ID (`_id`) on the _airline_ document and `airlineid` on the _route_ document.

[{code-snippet}]
----
include::{snippet}[tag=query-join,indent=0]
----
====


[#lbl-group]
== GROUP BY statement
You can perform further processing on the data in your result set before the final projection is generated.
The following example looks for the number of airports at an altitude of 300 ft or higher and groups the results by country and timezone.

.Data Model for Example
[{json-snippet}]
----
{
    "_id": "airport123",
    "type": "airport",
    "country": "United States",
    "geo": { "alt": 456 },
    "tz": "America/Anchorage"
}
----

[#ex-grpby-qry]
.Query using GroupBy
====
This example shows a query that selects all airports with an altitude above 300ft.
The output (a count, $1) is grouped by country, within timezone.

[{code-snippet}]
----
include::{snippet}[tag=query-groupby,indent=0]
----
====

The query shown in <<ex-grpby-qry>> generates the following output:
--
There are 138 airports on the Europe/Paris timezone located in France and above 300 ft +
There are 29 airports on the Europe/London timezone located in United Kingdom and above 300 ft +
There are 50 airports on the America/Anchorage timezone located in United States and above 300 ft +
There are 279 airports on the America/Chicago timezone located in United States and above 300 ft +
There are 123 airports on the America/Denver timezone located in United States and above 300 ft
--


[#lbl-order]
== ORDER BY statement

It is possible to sort the results of a query based on a given expression result.
The example below returns documents of type equal to "hotel" sorted in ascending order by the value of the title property.


[#ex-orderby-qry]
.Query using OrderBy
====

[{code-snippet}]
----
include::{snippet}[tag=query-orderby,indent=0]
----
====

The query shown in <<ex-orderby-qry>> generates the following output:
[{text-snippet}]
----
Aberdyfi
Achiltibuie
Altrincham
Ambleside
Annan
Ardèche
Armagh
Avignon
----


[#lbl-date-time]
== Date/Time Functions
include::ROOT:partial$query-date-time-functions.adoc[]


[#lbl-resultsets]
== Result Sets
In this section::
<<lbl-process-resultset>>{menuitem-delimiter}
<<lbl-all-sel>>{menuitem-delimiter}
<<lbl-specific-sel>>{menuitem-delimiter}
<<lbl-id-sel>>{menuitem-delimiter}
<<lbl-count-sel>>{menuitem-delimiter}
<<lbl-pagination>>


[#lbl-process-resultset]
=== Processing

This section shows how to handle the returned result sets for different types of `SELECT` statements.

The result set format and its handling varies slightly depending on the type of SelectResult statements used.
The result set formats you may encounter include those generated by :

* SelectResult.all -- see: <<lbl-all-sel, All Properties>>
* SelectResult.expression(property("name")) -- see: <<lbl-specific-sel, Specific Properties>>
* SelectResult.expression(meta.id) --  Metadata (such as the `_id`) -- see: <<lbl-id-sel, Document ID Only>>
* SelectResult.expression(Function.count(Expression.all())).as("mycount") --  see: <<lbl-count-sel>>

To process the results of a query, you first need to execute it using `Query.execute`.

The execution of a Couchbase Lite for {param-title}'s database query typically returns an array of results, a result set.

* The result set of an aggregate, count-only, query is a key-value pair -- see <<lbl-count-sel>> -- which you can access using the count name as its key.

* The result set of a query returning document properties is an array. +
Each array row represents the data from a document that matched your search criteria (the `WHERE` statements)
The composition of each row is determined by the combination of `SelectResult` expressions provided in the `SELECT` statement.
To unpack these result sets you need to iterate this array.


[#lbl-all-sel]
=== Select All Properties

.Query
The `Select` statement for this type of query, which returns all document properties for each document matching the query criteria, is fairly straightforward -- see <<ex-all-qry>>

[#ex-all-qry]
.Query selecting All Properties
====
[{code-snippet}]
----

include::{snippet}[tags=query-syntax-all]

----

====

.Result Set Format
The result set returned by queries using `SelectResult.all` is an array of dictionary objects -- one for each document matching the query criteria.

For each result object, the key is the database name and the 'value' is a dictionary representing each document property as a key-value pair -- see: <<ex-all-rtn>>.

.Format of Result Set (All Properties)
[#ex-all-rtn]
====
[{json-snippet}]
----

include::{root-examples}query-snippets.adoc[tags=query-result-format-all]

----
<.> Here we see the result for the first document matching the query criteria.
<.> Here we see the result for the next document matching the query criteria.

====

.Result Set Access

In this case access the retrieved document properties by converting each row's value, in turn, to a dictionary -- as shown in <<ex-all-acc>>.

[#ex-all-acc]
.Using Document Properties (All)
====
[{code-snippet}]
----

include::{snippet}[tags=query-access-all]

----
<.> Here we get the dictionary of document properties using the database name as the key.
You can add this dictionary to an array of returned matches, for processing elsewhere in the app.

<.> Alternatively you can access the document properties here, by using the property names as keys to the dictionary object.

====


[#lbl-specific-sel]
=== Select Specific Properties

.Query
Here we use `SelectResult.expression(property("<property-name>")))` to specify the document properties we want our query to return -- see: <<ex-specific-qry>>.

[#ex-specific-qry]
.Query selecting Specific Properties
====
[{code-snippet}]
----

include::{snippet}[tags=query-syntax-props]

----

====

.Result Set Format
The result set returned when selecting only specific document properties is an array of dictionary objects -- one for each document matching the query criteria.

Each result object comprises a key-value pair for each selected document property -- see <<ex-specific-rtn>>

.Format of Result Set (Specific Properties)
[#ex-specific-rtn]
====
[{json-snippet}]
----

include::{root-examples}query-snippets.adoc[tags=query-result-format-props]

----
<.> Here we see the result for the first document matching the query criteria.
<.> Here we see the result for the next document matching the query criteria.
====

.Result Set Access
Access the retrieved properties by converting each row into a dictionary -- as shown in <<ex-specific-acc>>.

[#ex-specific-acc]
.Using Returned Document Properties (Specific Properties)
====
[{code-snippet}]
----
include::{snippet}[tags=query-access-props]

----
====


[#lbl-id-sel]
=== Select Document Id Only

.Query
You would typically use this type of query if retrieval of document properties directly would consume excessive amounts of memory and-or processing time -- see: <<ex-id-qry>>.

[#ex-id-qry]
.Query selecting only Doc Id
====
[{code-snippet}]
----
include::{snippet}[tags=query-syntax-id]
----
====

.Result Set Format
The result set returned by queries using a SelectResult expression of the form `SelectResult.expression(meta.id)` is an array of dictionary objects -- one for each document matching the query criteria.
Each result object has `id` as the key and the ID value as its value -- -see <<ex-id-rtn>>.

.Format of Result Set (Doc Id only)
[#ex-id-rtn]
====
[{json-snippet}]
----

include::{root-examples}query-snippets.adoc[tags=query-result-format-id]

----
====

.Result Set Access
In this case, access the required document's properties by unpacking the `id` and using it to get the document from the database -- see: <<ex-id-acc>>.

.Using Returned Document Properties (Document Id)
[#ex-id-acc]
====
[{code-snippet}]
----

include::{snippet}[tags=query-access-id]

----

<.> Extract the Id value from the dictionary and use it to get the document from the database

====


[#lbl-count-sel]
=== Select Count-only

[#ex-count-qry]
.Query selecting a Count-only
====
[{code-snippet}]
----

include::{snippet}[tags=query-syntax-count-only]

----
<.> The alias name, `mycount`, is used to access the count value.
====

.Result Set Format
The result set returned by a count such as `Select.expression(Function.count(Expression.all)))` is a key-value pair.
The key is the count name, as defined using `SelectResult.as` -- see: <<ex-count-rtn>> for the format and <<ex-count-qry>> for the query.

.Format of Result Set (Count)
[#ex-count-rtn]
====
[{json-snippet}]
----

include::{root-examples}query-snippets.adoc[tags=query-result-format-count]

----
<.> Here we see the key-value pair returned by a count.
====

.Result Set Access

Access the count using its alias name (`mycount` in this example) -- see <<ex-count-acc>>

[#ex-count-acc]
.Using Returned Document Properties (Count)
====
[{code-snippet}]
----

include::{snippet}[tags=query-access-count-only]

----
<.> Get the count using the `SelectResult.as` alias, which is used as its key.
====

[#lbl-pagination]
=== Handling Pagination
One way to handle pagination in high-volume queries is to retrieve the results in batches.
Use the `limit` and `offset` feature, to return a defined number of results starting from a given offset -- see: <<ex-pagination>>.


[#ex-pagination]
.Query Pagination
====
[{code-snippet}]
----
include::{snippet}[tags=query-syntax-pagination]
----
<.> Return a maximum of `limit` results starting from result number `offset`
====


TIP: For more on using the QueryBuilder API, see our blog: {url-cb-blog-query-interface}


== JSON Result Sets

Couchbase Lite for {param-title} provides a convenience API to convert query results to JSON strings.

include::{root-commons}querybuilder-jsonresult.adoc[subs="macros,attributes"]



// END --- inclusion -- querybuilder.adoc