// = Indexing
// :page-layout: article
// :page-status:
// :page-edition:
// :page-role:
//
// include::shared-mobile::partial$_attributes-shared.adoc[]
// include::ROOT:partial$_page-index.adoc[]
// include::ROOT:partial$_glossary-links.adoc[]
// include::ROOT:partial$_attributes-local.adoc[]
// include::{lang-mod-swift}:partial$_attributes-module.adoc[]
//
// // BEGIN::Local page attributes
// :blank-field: ____
// :ziputils: {snippets-pfx--swift}/code_snippets/ZipUtils.java
// // END::Local page attributes


// // BEGIN::REQUIRED EXTERNALS
// :this-module: {par-module}
// :this-lang-title: {par-lang-title}
// :this-packageNm: {par-packageNm}
// :this-source-language: {par-source-language}
// :this-snippet: {par-snippet}
//:this-url-issues: {par-url-issues}
// END::REQUIRED EXTERNALS

.Constraints
NOTE:
Couchbase Lite for {param-platform} does not currently supported partial value indexes; that is, indexes with non property expressions.
You should only index with properties that you plan to use in the query.


== Introduction

Before we begin querying documents, let's briefly mention the importance of having an appropriate and balanced approach to indexes.

Creating indexes can speed up the performance of queries.
A query will typically return results more quickly if it can take advantage of an existing database index to search, narrowing down the set of documents to be examined.

.Creating a new index
====

This example creates a new index for the `type` and `name` properties, shown in this data model:

[source,json]
----
{
    "_id": "hotel123",
    "type": "hotel", <.>
    "name": "Apple Droid"
}
----

The code to create the index will look something like this:

[source, {source-language}]
----
include::{snippet}[tag=query-index,indent=0]
----

====

When planning the indexes you need for your database, remember that while indexes make queries faster, they may also:

* Make writes slightly slower, because each index must be updated whenever a document is updated
* Make your Couchbase Lite database slightly larger.

So too many indexes may hurt performance.
Optimal performance depends on designing and creating the _right_ indexes to go along with your queries.
