= Working with Replications
:page-layout: article
:page-status:
:page-edition:
:page-role:
:description: Couchbase database replication and synchronization concepts

include::partial$_std-cbl-hdr-android.adoc[]

:param-related: {xref-cbl-pg-conflict} | {xref-cbl-pg-dbreplica} | {xref-cbl-pg-cert-pinning} |
:topic-group: Topic Group -- Replication
include::{root-partials}block-abstract.adoc[]

== Replication Protocol

include::{root-partials}replication-introduction.adoc[]

== Protocol Compatibility

include::{root-partials}replication-protocol-compatibility.adoc[]

== Starting Sync Gateway

https://www.couchbase.com/downloads[Download Sync Gateway] and start it from the command line with the configuration file created above.

[source,bash]
----
~/Downloads/couchbase-sync-gateway/bin/sync_gateway
----

For platform specific installation instructions, refer to the Sync Gateway xref:sync-gateway::getting-started.adoc#installation[installation guide].

== Starting a Replication

Replication can be bidirectional, this means you can start a `push`/`pull` replication with a single instance.
The replication's parameters can be specified through the {url-api-references}/index.html?com/couchbase/lite/ReplicatorConfiguration.html[`ReplicatorConfiguration`] object;
for example, if you wish to start a `push` only or `pull` only replication.

The following example creates a `pull` replication with Sync Gateway.

[source, {source-language}]
----
class MyClass {
    Database database;
    Replicator replicator; // <.>

    void startReplication() {
        URI uri = null;
        try {
            uri = new URI("wss://10.0.2.2:4984/db"); // <.>
        } catch (URISyntaxException e) {
            e.printStackTrace();
        }
        Endpoint endpoint = new URLEndpoint(uri);
        ReplicatorConfiguration config = new ReplicatorConfiguration(database, endpoint);
        config.setReplicatorType(ReplicatorConfiguration.ReplicatorType.PULL);
        this.replicator = new Replicator(config);
        this.replicator.start();
    }

}
----
<.> A replication is an asynchronous operation.
To keep a reference to the `replicator` object, you can set it as an instance property.
<.> The URL scheme for remote database URLs uses `ws:`, or `wss:` for SSL/TLS connections over wb sockets.
In this example the hostname is `10.0.2.2` because the Android emulator runs in a VM that is generally accessible on `10.0.2.2` from the host machine (see https://developer.android.com/studio/run/emulator-networking[Android Emulator networking] documentation).
+
NOTE: As of Android Pie, version 9, API 28, cleartext support is disabled, by default.
Although `wss:` protocol URLs are not affected, in order to use the `ws:` protocol, applications must target API 27 or lower, or must configure application network security as described https://developer.android.com/training/articles/security-config#CleartextTrafficPermitted[here].

include::{root-partials}verify-replication.adoc[]

Couchbase Lite uses WebSockets as the communication protocol to transmit data.
Some load balancers are not configured for WebSocket connections by default (NGINX for example);
so it might be necessary to explicitly enable them in the load balancer's configuration (see xref:sync-gateway::load-balancer.adoc[Load Balancers]).

By default, the WebSocket protocol uses compression to optimize for speed and bandwidth utilization.
The level of compression is set on Sync Gateway and can be tuned in the configuration file (xref:sync-gateway::config-properties.adoc#replicator_compression[`replicator_compression`]).

== Replication Ordering

To optimize for speed, the replication protocol doesn't guarantee that documents will be received in a particular order.
So we don't recommend to rely on that when using the replication or database change listeners for example.

=== Replicator Notifications on a Custom Executor

Prior to version 2.6, Couchbase Lite spun up multiple executors.
This policy could result in too many threads being spun up.

NOTE: If no listeners are registered to listen to a replicator at the time of the most recent `start(. . .)`, then no subsequently registered listeners will receive notifications.

An executor manages a pool of threads and, perhaps, a queue in front of the executor, to handle the asynchronous callbacks.
Couchbase Lite API calls which are processed by an executor are listed below.

[source]
----
Query.addChangeListener
MessageEndpointListerner.addChangeListener
LiveQuery.addChangeListener
AbstractReplicator.addDocumentReplicationListener
AbstractReplicator.addChangeListener
Database.addChangeListener
Database.addDocumentChangeListener
Database.addDatabaseChangeListener
Database.addChangeListener
----

As of version 2.6, Couchbase sometimes uses its own internal executor to run asynchronous client code.
While this is fine for small tasks, larger tasks -- those that take significant compute time, or that perform I/O -- can block Couchbase processing.
If this happens your application will fail with a `RejectedExecutionException` and it may be necessary to create a separate executor on which to run the large tasks.

The following examples show how to specify a separate executor in the client code.
The client code executor can enforce an application policy for delivery ordering and the number of threads.

*Guaranteed Order Delivery*

[source,java]
----
/**
 * This version guarantees in order delivery and is parsimonious with space
 * The listener does not need to be thread safe (at least as far as this code is concerned).
 * It will run on only thread (the Executor's thread) and must return from a given call
 * before the next call commences.  Events may be delivered arbitrarily late, though,
 * depending on how long it takes the listener to run.
 */
public class InOrderExample {
    private static final ExecutorService IN_ORDER_EXEC = Executors.newSingleThreadExecutor();

    public Replicator runReplicator(Database db1, Database db2, ReplicatorChangeListener listener)
        throws CouchbaseLiteException {
        ReplicatorConfiguration config = new ReplicatorConfiguration(db1, new DatabaseEndpoint(db2));
        config.setReplicatorType(ReplicatorConfiguration.ReplicatorType.PUSH_AND_PULL);
        config.setContinuous(false);

        Replicator repl = new Replicator(config);
        ListenerToken token = repl.addChangeListener(IN_ORDER_EXEC, listener::changed);

        repl.start();

        return repl;
    }
}
----

*Maximum Throughput*

[source,]
----
/**
 * This version maximizes throughput.  It will deliver change notifications as quickly
 * as CPU availability allows. It may deliver change notifications out of order.
 * Listeners must be thread safe because they may be called from multiple threads.
 * In fact, they must be re-entrant because a given listener may be running on mutiple threads
 * simultaneously.  In addition, when notifications swamp the processors, notifications awaiting
 * a processor will be queued as Threads, (instead of as Runnables) with accompanying memory
 * and GC impact.
 */
public class MaxThroughputExample {
    private static final ExecutorService MAX_THROUGHPUT_EXEC = Executors.newCachedThreadPool();

    public Replicator runReplicator(Database db1, Database db2, ReplicatorChangeListener listener)
        throws CouchbaseLiteException {
        ReplicatorConfiguration config = new ReplicatorConfiguration(db1, new DatabaseEndpoint(db2));
        config.setReplicatorType(ReplicatorConfiguration.ReplicatorType.PUSH_AND_PULL);
        config.setContinuous(false);

        Replicator repl = new Replicator(config);
        ListenerToken token = repl.addChangeListener(MAX_THROUGHPUT_EXEC, listener::changed);

        repl.start();

        return repl;
    }
}
----

*Extreme Configurability*

[source]
----
/**
 * This version demonstrates the extreme configurability of the CouchBase Lite replicator callback system.
 * It may deliver updates out of order and does require thread-safe and re-entrant listeners
 * (though it does correctly synchronizes tasks passed to it using a SynchronousQueue).
 * The thread pool executor shown here is configured for the sweet spot for number of threads per CPU.
 * In a real system, this single executor might be used by the entire application and be passed to
 * this module, thus establishing a reasonable app-wide threading policy.
 * In an emergency (Rejected Execution) it lazily creates a backup executor with an unbounded queue
 * in front of it.  It, thus, may deliver notifications late, as well as out of order.
 */
public class PolicyExample {
    private static final int CPUS = Runtime.getRuntime().availableProcessors();

    private static ThreadPoolExecutor BACKUP_EXEC;

    private static final RejectedExecutionHandler BACKUP_EXECUTION
        = new RejectedExecutionHandler() {
        public void rejectedExecution(Runnable r, ThreadPoolExecutor e) {
            synchronized (this) {
                if (BACKUP_EXEC =  null) { BACKUP_EXEC = createBackupExecutor(); }
            }
            BACKUP_EXEC.execute(r);
        }
    };

    private static ThreadPoolExecutor createBackupExecutor() {
        ThreadPoolExecutor exec
            = new ThreadPoolExecutor(CPUS + 1, 2 * CPUS + 1, 30, TimeUnit.SECONDS, new LinkedBlockingQueue<Runnable>());
        exec.allowCoreThreadTimeOut(true);
        return exec;
    }

    private static final ThreadPoolExecutor STANDARD_EXEC
        = new ThreadPoolExecutor(CPUS + 1, 2 * CPUS + 1, 30, TimeUnit.SECONDS, new SynchronousQueue<Runnable>());

    static { STANDARD_EXEC.setRejectedExecutionHandler(BACKUP_EXECUTION); }

    public Replicator runReplicator(Database db1, Database db2, ReplicatorChangeListener listener)
        throws CouchbaseLiteException {
        ReplicatorConfiguration config = new ReplicatorConfiguration(db1, new DatabaseEndpoint(db2));
        config.setReplicatorType(ReplicatorConfiguration.ReplicatorType.PUSH_AND_PULL);
        config.setContinuous(false);

        Replicator repl = new Replicator(config);
        ListenerToken token = repl.addChangeListener(STANDARD_EXEC, listener::changed);

        repl.start();

        return repl;
    }
}
----

== Delta Sync

include::{root-partials}replication-delta-sync.adoc[]

== Troubleshooting

As always, when there is a problem with replication, logging is your friend.
The following example increases the log output for activity related to replication with Sync Gateway.

[source]
----
include::{snippet}[tag=replication-logging,indent=0]
----

== Authentication

include::{root-partials}authentication.adoc[]

== Replication Status

The `replication.Status.Activity` property can be used to check the status of a replication.
For example, when the replication is actively transferring data and when it has stopped.

[source]
----
include::{snippet}[tag=replication-status,indent=0]
----

The following table lists the different activity levels in the API and the meaning of each one.

[cols="1,2"]
|===
|State |Meaning

|`STOPPED`
|The replication is finished or hit a fatal error.

|`OFFLINE`
|The replicator is offline as the remote host is unreachable.

|`CONNECTING`
|The replicator is connecting to the remote host.

|`IDLE`
|The replication caught up with all the changes available from the server.
The `IDLE` state is only used in continuous replications.

|`BUSY`
|The replication is actively transferring data.
|===

NOTE: The replication change object also has properties to track the progress (`change.status.completed` and `change.status.total`).
But since the replication occurs in batches and the total count can vary through the course of a replication, those progress indicators are not very useful from the standpoint of an app user.
Hence, these should not be used for tracking the actual progress of the replication.

anchor:repstatus-and-lifecycle[]

=== Replication Status and App Lifecycle

Couchbase Lite replications will continue running until the app terminates, unless the remote system, or the application, terminates the connection.

NOTE: Recall that the Android OS may kill an application without warning.
You should explicitly stop replication processes when they are no longer useful (for example, when they are `suspended` or `idle`) to avoid socket connections being closed by the OS, which may interfere with the replication process.

== Handling Network Errors

If an error occurs, the replication status will be updated with an `Error` which follows the standard HTTP error codes.
The following example monitors the replication for errors and logs the error code to the console.

[source]
----
include::{snippet}[tag=replication-error-handling,indent=0]
----

When a permanent error occurs (i.e., `404`: not found, `401`: unauthorized), the replicator (continuous or one-shot) will stop permanently.
If the error is temporary (i.e., waiting for the network to recover), a continuous replication will retry to connect indefinitely and if the replication is one-shot it will retry for a limited number of times.
The following error codes are considered temporary by the Couchbase Lite replicator and thus will trigger a connection retry.

* `408`: Request Timeout
* `429`: Too Many Requests
* `500`: Internal Server Error
* `502`: Bad Gateway
* `503`: Service Unavailable
* `504`: Gateway Timeout
* `1001`: DNS resolution error

== Replication Events

include::{root-partials}replication-events.adoc[]

== Custom Headers

include::{root-partials}replication-custom-header.adoc[]

[source]
----
include::{snippet}[tag=replication-custom-header,indent=0]
----

== Replication Checkpoint Reset

include::{root-partials}replication-checkpoint.adoc[]

[source]
----
include::{snippet}[tag=replication-reset-checkpoint,indent=0]
----

== Replication Filters

include::{root-partials}replication-filters.adoc[]

include::{root-partials}block-related-content-rep.adoc[]