= P2P Sync Using WebsocketEndpointListener
:page-layout: article
:page-status: {release-status-cbl} -- {release-comments-cbl}
:page-edition: Under Development
:page-role:
:description: Couchbase mobile database queries - concepts

include::partial$_std-cbl-hdr-android.adoc[]

ifndef::release-status-cbl[:release-status-cbl!:]
ifeval::["{release-status-cbl}" == "gamma"]
[.pane__frame--orange]
.Author's Notes
--

DOC-6892-H2-P2P: New topic - WebsockedtEndpointListener and P2P Sync
https://issues.couchbase.com/browse/DOC-6892

Add content covering CBL websocketlistener

Sources:
* reqs https://docs.google.com/document/d/1o1Dol-g6_D5Stf0IrgY_yxr0kO6AYVJFGOgGjoh6Q6c/edit?ts=5e5fe7da#
* design https://docs.google.com/document/d/1R2Vd5Iei1OLJvU4QJ-zE6FED8VH-nr2Q9PyjbjwVW48/edit#heading=h.ayhq9efeewhi

This will be  full description of the websocketendpointlistener including:

* Overview and feature description
* API
* Workflow - operational sequence for normal P2P sync ops
* Example code for simple sync ops
* Constraints

The content may ultimately be split up as needed.

Topic to include from requirements:

* If user-defined port is not specified, the system will automatically select a port to use. -- https://docs.google.com/document/d/1o1Dol-g6_D5Stf0IrgY_yxr0kO6AYVJFGOgGjoh6Q6c/edit#bookmark=id.s5y61p8gawi1



--
endif::[]

==  Overview

Couchbase's replication listener API and implementation uses WebSocket protocol to provide a concrete implementation of a _MessageEndpointListener_.

Using this _WebsocketEndpointListener_ developers can implement peer-to-peer replication without navigating the compexity of the _MessageEndpoint_ API, which can often be a barrier.
The _WebsocketEndpointListener_ listens for incoming websocket connections on a user-defined, or auto-selected, port.

== API

The listener API features comprise:
--
* A replication listener for a single database with an option to allow only pull replication
* Support TLS communication by default (can be disabled)
* Support an auto-generated anonymous TLS Identity if the TLS Identity is not specified.
* Support two types of authentication:
** Password Authentication
** Client Certificate Authentication as a part of TLS Communication
** Provide connection status information.
** A utility API to programmatically generate a self-sign certificate.
--

URLEndpointListener::
The `URLEndpointListener` is the Peer-to-Peer listener for replication. It acts like a passive replicator, in the same way that Sync Gateway does.
+
Core functionalities of the listener are:
+
* Users can initialize the class using a _URLEndpointListenerConfiguration_ object.
* The listener can be started, or can be stopped.
* Once the listener is started, a total number of connections or active connections can be checked.

URLEndpointListenerConfiguration::
A configuration class used for creating a _URLEndpointListener_ object.
The property setters should be made fluent API if the platform allows.

TLSIdentity::
TLSIdentity represents the identity information (Key pair and Certificates) used for setting up TLS Communication. The TLSIdentity API would be different among between platforms. The following API is based on the Apple Platform.


== Features
* If user-defined port is not specified, the system will automatically select a port to use.
* Capable of serving one  couchbase lite databases.
* Instantiated by client, each instance for different db. no limit on instances (ex. practical limit)
* There must be an API that will allow users to get the current port of the listener.
* api to return the list of URL(s) endpoint of listener. The URL must include the listener port as well as the serving database.

== Typical Workflow

Initialize::
Use `URLEndpointListenerConfiguration` to set the required listener configuration, specifically:
+
* database
* tls status and identity
* delta_sync status

+
Use `URLEndpointListener` to instantiate the _WebsocketEndpointListener_ using the _URLEndpointListenerConfiguration_ configuration values in the constructor.

Start::
Use `URLEndpointListener.start` method to start the listener

Assuming no error is returned the listener is operational.

Initialize Replication::
Use `ReplicatorConfiguration.init` to provide:
+
* db
* URLEndpoint.init(target url)



// * Discovery
// * Connection
// * Peer setup/Config
// * Replicator setup
// * Replication
// * Disconnection

== Discovery

Automatic Device Discovery is out of scope for release.


== Connection



== Peer setup/Config



== Replicator setup



== Replication



== Disconnection



== Conflict handling


== Constraints
* Sizing - eg num websocket endponi listeners
** The scalability of the sync must only be limited by OS-level factors like number of open socket descriptions, volume of mutations getting synced .
* We must provide some guidance on the sizing factors that will determine the number of supported clients. This is probably the most commonly asked question when it comes to p2p support. Alternatives like MPC specify the same.
Context: This has been one of the reasons why off-the-shelf solutions haven’t worked requiring custom implementation


[.pane__frames.cols-3]
== Related Content

.How-to ...

* {xref-cbl-pg-p2psync-custom}
* {xref-cbl-pg-p2psync-websocket}

.Learn more ...

* include how-to links as relevant,
* include how-to links as relevant,

//include::shared-mobile:ROOT:partial$_related-content.adoc[tags=icr]

.Dive Deeper ...

* Reference content
** {url-api-references}[API References]
+
include::shared-mobile::partial$_related-content.adoc[tags=community]
