= Peer-to-Peer Synchronization
:page-layout: article
:page-status: {release-status-cbl} -- {release-comments-cbl}
:page-edition: Enterprise
:page-role:

include::partial$_std-cbl-hdr-android.adoc[]

// BEGIN::Local page attributes

:url-issues-java: {url-github-cbl}{module}/issues
:ziputils: {snippets-pfx--android}/code_snippets/ZipUtils.java

ifndef::release-status-cbl[:release-status-cbl!:]
ifeval::["{release-status-cbl}" == "gamma"]
[.pane__frame--orange]
.Author's Notes
--

DOC-6340-H2-P2P: New topic - Implementing P2P Sync
https://issues.couchbase.com/browse/DOC-6340

This is the main P2P content covering CBL P2P:

Create a parent topic P2P Sync that will cover the generic sync concepts and then branch to cover new WebsocketEndpointListener topic, existing EndpointListener topic

--
endif::[]

== Current Position

.Enterprise Edition only
IMPORTANT: Peer-to-peer sync is an https://www.couchbase.com/products/editions[Enterprise Edition] feature.
You must purchase the Enterprise License which includes official https://www.couchbase.com/support-policy[Couchbase Support] to use it in production (also see the https://www.couchbase.com/licensing-and-support-faq[FAQ]).

Peer-to-peer sync allows devices running Couchbase Lite to directly sync data with each other without a server.


Couchbase Lite is responsible for storing the data and keeping track of the data exchange.
The data transfer itself -- the sending and receiving of data -- is handled by a communication framework. With Couchbase you have the option of using either of:

* Couchbase's out-of-the-box _WebsocketEndpointListener_
+
For two instances of Couchbase Lite to sync, at least one of them must use a _WebsocketEndpointListener_, which enables any Couchbase Lite database to become the remote in a replication by listening and exposing standard replication endpoints on a selected port.
* A custom built _MessageEndpointListener_
+
Alternativley develpers can use the platform APIs and-or a third party framework such as Android's https://developers.google.com/nearby/messages/overview[Nearby Messages API], implementtheir owne listener. This will handle sending and receiving messages and supports multiple transport technologies -- WiFi and Bluetooth and uses whichever is available to establish a connection between devices.

The following sections describe a typical peer-to-peer workflow.
Where applicable, we discuss how to integrate Couchbase Lite into the workflow.

In Couchbase Lite, a peer can take on one of these two roles:

* *Active Peer:* The peer that initializes the connection and replication (i.e the "client" side).
* *Passive Peer:* The passive side reacts to things that it receives but does not initiate any communication on its own (i.e. the "server" side).

[.pane__frames.no-title]
== {empty}

=== Out the box

{xref-cbl-pg-p2psync-websocket}

=== Custom Listener

{xref-cbl-pg-p2psync-custom}

[.pane__frames.cols-3]
== Related Content

.How-to ...

* Write {xref-cbl-pg-p2psync-custom} listener
* Write {xref-cbl-pg-p2psync-websocket} listener

.Learn more ...

* include how-to links as relevant,
* include how-to links as relevant,

//include::shared-mobile:ROOT:partial$_related-content.adoc[tags=icr]

.Dive Deeper ...

{xref-cbl-pg-p2psync-custom}

[.pane__frames.cols-3]
== Related Content

.How-to ...

* Write {xref-cbl-pg-p2psync-custom} listener
* Write {xref-cbl-pg-p2psync-websocket} listener

.Learn more ...

* include how-to links as relevant,
* include how-to links as relevant,

//include::shared-mobile:ROOT:partial$_related-content.adoc[tags=icr]

.Dive Deeper ...

* Reference content
** {url-api-references}[API References]
+
include::shared-mobile::partial$_related-content.adoc[tags=community]
