= Database for C
:page-aliases: learn/clang-database.adoc
:page-layout: article
:page-status:
:page-edition:
:page-role:
:description: Working with Couchbase Lite Databases

include::partial$_std-cbl-hdr-clang.adoc[]

// BEGIN::Local page attributes
:blank-field: ____
:lang-title: {lang-title-clang}
//:url-issues: {url-github-cbl}{module}/issues

// END::Local page attributes
:param-related: {xref-cbl-pg-blob} | {xref-cbl-pg-document} | {xref-cbl-pg-indexing}
:topic-group: Data Model
include::{root-partials}block-abstract.adoc[]

== New Database

As the top-level entity in the API, new databases can be created using the `Database` class by passing in a name, configuration, or both.
The following example creates a database using the `Database(name: String)` method.

[source]
----
include::{snippet}[tag=new-database,indent=0]
----

Just as before, the database will be created in a default location.
Alternatively, the `Database(string name, DatabaseConfiguration config)` initializer can be used to provide specific options in the {url-api-references}/Classes/CBLDatabaseConfiguration.html[`DatabaseConfiguration`] object such as the database directory.

== Database Encryption

:param-language: {param-name}
include::{root-partials}database-encryption.adoc[]

== Finding a Database File

When the application is running on the iOS simulator, you can locate the application's sandbox directory using the https://simpholders.com/3/[SimPholders] utility.

== CLI tool

include::{root-partials}cli-tool.adoc[]

== Logging

If you are using a Couchbase Lite release prior to 2.5 see <<Logging functionality prior to Release 2.5, Deprecated functionality>>

include::{root-commons}logging.adoc[leveloffset=+2]

=== Logging functionality prior to Release 2.5

include::{root-partials}logging-pre2.5.adoc[]

[source]

----
include::{snippet}[tags=logging,indent=0]
----

// == Loading a pre-built database

// include::{root-partials}database-load-prebuilt.adoc[]

include::{root-partials}block-related-content-data.adoc[]