= Field Level Encryption
:page-status: placeholder
:page-edition: 3.0
:description: Client-side Field Level Encryption on Couchbase Lite C Clients

include::partial$_std-cbl-hdr-clang.adoc[]

// :param-name: {lang-name-clang}
// :param-title: {lang-title-clang}
// :param-module: {lang-mod-clang}

== Overview

Couchbase Lite for C 3.x supports client-side, field-Level encryption on replications, allowing applications to encrypt/decrypt sensitive fields in documents using an encryption framework of choice.

Using the new client-side encryption capability, Couchbase Lite C applications can
designate selected fields for encryption and have the client automatically handle the encryption and-or decryption process prior to syncing with Couchbase Server.

This means only clients with access to the correct encryption keys can decrypt and read the protected data.

The client-side encryption is compatible with the Couchbase server SDK field-level encryption format -- see, for example, https://docs.couchbase.com/python-sdk/current/concept-docs/encryption.html#format

== Use

Encrypted properties are created using a new dictionary structure, which represents a property value that will be automatically recognized by the replicator for encryption.

// The format of the dictionary is as follows:
[#ex-fldlevenc]
.Format
[source, {source-langauge}]
----
{
  "@type": "EncryptedProperty",
  "value": <Non-Encrypted Value>
}
----

Construct properties requiring encryption by the replicator, as a dictionary with the structure shown in <<ex-fldlevenc>>.

Replicator will replace the _value_ key with `encrypted_value` in BASE64 format. The result dictionary for the encrypted value is as follows:
----
{
  "@type": "EncryptedProperty",
  "encrypted_value": "<BASE64>"
}
----

When the replicator pulls and saves a document into the local database, it will automatically recognize the EncryptedProperty dictionary and use it to decrypt the value.

Encrypted properties can be queried using the value, for example: +
----
SELECT ssn.value FROM db WHERE ssn.value = "123-45-6789"
----

== Encryption Callback

Use the following callback to set the replicator's configuration for encryption/decryption.
----
bool (*CBLPropertyEncryption)(
     void *context,
     boolean isEncrypting,
     FLString docID,
     FLDict properties,
     FLString keyPath,
     FLSlice input,
     void *output,
     size_t *outLen);
----

When the callback returns false, the document will fail to replicate with a crypto error; the replicator will skip the document and report the error.

If the replicator detects an EncryptedProperty but there is no callback set to the replicator, the document will be failed to replicate with a crypto error as well.


include::{root-partials}block-related-content-data.adoc[]
