= Field Level Encryption
:page-status: placeholder
:page-edition: 3.0
:description: Client-side Field Level Encryption on Couchbase Lite C Clients

include::partial$_std-cbl-hdr-clang.adoc[]

// :param-name: {lang-name-clang}
// :param-title: {lang-title-clang}
// :param-module: {lang-mod-clang}


Need to build a page covering field level encryption

Client-side Field Level Encryption on Couchbase Lite C Clients
The new C API also supports client side field level encryption, a capability that will be introduced in other Couchbase Lite platforms in future. Using the new client-side encryption capability, Couchbase Lite C clients can encrypt fields in documents prior to replicating data over the wire to Couchbase Server. Only clients with access to the correct encryption keys can decrypt and read the protected data. The client-side encryption  is compatible with the Couchbase server SDK field-level encryption format.

Value Proposition
Enable secure transfer of sensitive data to backend servers, guaranteeing that sensitive data is never leaked to actors that do not have credentials or privileges to access the data.
Couchbase Lite applications to encrypt/decrypt sensitive fields in documents using any encryption framework of choice


see also https://docs.couchbase.com/python-sdk/current/concept-docs/encryption.html#format



include::{root-partials}block-related-content-data.adoc[]
