= Prerequisites

Couchbase Lite for React Native is provided as a https://reactnative.dev/docs/legacy/native-modules-intro[Native Module]. Version 1.1 supports https://reactnative.dev/architecture/overview[React Native New Architecture] through TurboModules on iOS and Android.

The Native Module can be found at the following repository: https://github.com/couchbase/couchbase-lite-react-native[Couchbase Lite for React Native]. npm package: https://www.npmjs.com/package/@couchbase/couchbase-lite-react-native[@couchbase/couchbase-lite-react-native]. Shared TypeScript and JavaScript code lives in https://github.com/couchbase/couchbase-lite-js-common[cblite-js].

A developer using this plugin should have a basic understanding of the following technologies:

* https://reactnative.dev/[React Native]
* https://reactnative.dev/docs/legacy/native-modules-intro[React Native - Native Modules]
* https://reactnative.dev/architecture/overview[React Native - New Architecture]
* https://docs.expo.dev/[Expo Framework]
* https://docs.couchbase.com/couchbase-lite/current/index.html[Couchbase Lite]

== Expo Note

React Native's recommmendation is to use https://reactnative.dev/blog/2024/06/25/use-a-framework-to-build-react-native-apps[Expo] for development . The example app that comes with the repository is an Expo based app, thus this Native Module can work in Expo apps.  Note using Expo Go is not supported due to Expo Go not supporting loading 3rd party Native Modules.  You will need to be familiar with the https://docs.expo.dev/guides/local-app-development/#local-builds-with-expo-dev-client[Expo Dev Client] process to use this Native Module in an Expo app.

== Supported Platforms

* The React Native - Native Module is supported on iOS and Android platforms.  MacOS, Windows, and Web support is not available at this time.

== React Native Version

* The plugin is built using React Native 0.76.3. Support for older versions of React Native is not guaranteed and apps should be based on 0.76.3 or higher.
* Version 1.1 supports TurboModules through https://reactnative.dev/architecture/overview[React Native New Architecture]. Apps should enable New Architecture when using the TurboModule implementation.

Please review the React Native https://github.com/reactwg/react-native-releases/blob/main/docs/support.md[Support documentation] for a full listed of supported platform versions.

== Development Environment

* Javascript
 ** https://formulae.brew.sh/formula/node@18[Node >= 20]
* React Native
 ** https://reactnative.dev/[React Native Docs]
 ** https://reactnative.dev/docs/legacy/native-modules-intro[Understanding React Native - Native Modules]
* Expo (if you choose to use Expo, not required but recommended)
 ** https://docs.expo.dev/[Expo Docs]
 ** https://docs.expo.dev/guides/local-app-development/#local-builds-with-expo-dev-client[Expo Dev Client]
 ** https://docs.expo.dev/guides/monorepos/[Expo Mono Repos]
 ** https://docs.expo.dev/config-plugins/introduction/[Expo Plugin and mods]
* IDEs
 ** https://code.visualstudio.com/download[Visual Studio Code]
 ** https://www.jetbrains.com/idea/download/[IntelliJ IDEA]
* iOS Development
 ** A modern Mac
 ** https://developer.apple.com/xcode/[XCode 15.1] or higher installed and working
 ** [iOS 15.1 or higher].  Any apps using the plugin must be upgraded to iOS 15.1 or higher.
 ** https://developer.apple.com/download/more/[XCode Command Line Tools] installed
 ** https://developer.apple.com/documentation/safari-developer-tools/installing-xcode-and-simulators[Simulators] downloaded and working
 ** https://brew.sh/[Homebrew]
 ** https://formulae.brew.sh/formula/cocoapods[Cocopods]
 ** A valid Apple Developer account and certificates installed and working
* Android Development
 ** [API 24 (Android 7)] or higher.  Any apps using the plugin must be upgraded to API 24 or higher.  Any older versions of Android are not supported by React Native and Expo.
 ** https://developer.android.com/studio?gad_source=1&gclid=CjwKCAjwzN-vBhAkEiwAYiO7oALYfxbMYW_zkuYoacS9TX16aItdvLYe6GB7_j1QwvXBjFDRkawfUBoComcQAvD_BwE&gclsrc=aw.ds[Android Studio] installed and working
 ** Android SDK 34 >= installed and working (with command line tools)
 ** Java SDK v17 installed and configured to work with Android Studio
 ** An Android Emulator downloaded and working
