
= Databases
:page-aliases: learn/java-android-database.adoc
:page-role:
:description: Working with Couchbase Lite on Android databases


:source-language: Java


:source-language: Kotlin


[abstract]
--
Description -- _{description}_ +
Related Content -- xref:android:blob.adoc[Blobs] | xref:android:document.adoc[Documents] | xref:android:indexing.adoc[Indexing]
--


[#database-concepts]
== Database Concepts

Databases created on Couchbase Lite can share the same hierarchical structure as Capella databases.
This makes it easier to sync data between mobile applications and applications built using Capella.

.Couchbase Lite Database Hierarchy
[plantuml]
----
@startuml


database "Database" as db

rectangle "Scope" as scope

folder "Collection" as collection


file "Document" as document1
file "Document" as document2
file "Document" as document3

db --> scope
scope --> collection
collection --> document1
collection --> document2
collection --> document3


note right of collection

  Maximum of 1000 per scope

end note

note right of db

  One database per application

end note

@enduml
----

Although the terminology is different, the structure can be mapped to relational database terms:


.Relational Database -> Couchbase
[width=70%,grid=none]
|===
|Relational database |Couchbase

|Database
|Database

|Schema
|Scope

|Table
|Collection
|===

This structure gives you plenty of choices when it comes to partitioning your data.
The most basic structure is to use the single default scope with a single default collection; or you could opt for a structure that allow you to split your collections into logical scopes.

[#cbl-database-structure]
.Couchbase Lite Examples

[plantuml#cbl-database-structure]
----
@startuml


database "Couchbase Lite database" as db1 {

      node "_default scope" as dfs1 {

        folder "_default collection" as dfc1 {

        }
      }

}

database "Couchbase Lite database" as db2 {


    node "_default scope" as dfs2 {

      folder "_default collection" as dfc2 {

      }

        folder "Collection A" as collectionA {

        }
    }

    node "Scope A" as scopeA {

      folder "Collection A" as collectionA2 {

      }

        folder "Collection B" as collectionB {

        }
    }

}

collectionA2 -D[hidden]-> collectionB
collectionA -D[hidden]-> dfc2
@enduml
----


.Storing local configuration
****
You may not need to sync all the data related for a particular application. You can set up a scope that syncs data, and a second scope that doesn't.

One reason for doing this is to store local configuration data (such as the preferred screen orientation or keyboard layout). Since this information only relates to a particular device, there is no need to sync it:

[horizontal]
local data scope:: Contains information pertaining to the device.

syncing data scope:: Contains information pertaining to the user, which can be synced back to the cloud for use on the web or another device.

****


[#initializer]
== Initializer


Your first step in using the API must be to call its initializer.
An exception is raised if any other API method is invoked before the initializer.

.Initializer code
[#ex-init-cdl]


[#ex-init-cdl]
====

[tabs]
=====


Kotlin::
+
--

[source, Kotlin]
----
include::android:example$codesnippet_collection.kt[tags="sdk-initializer", indent=0]
----

--

Java::
+
--
[source, Java]
----
include::android:example$codesnippet_collection.java[tags="sdk-initializer", indent=0]
----
--

=====


====


[#open-db]
== Create or Open Database


You can create a new database and-or open an existing database, using the https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-android}{empty}/couchbase-lite-android/com/couchbase/lite/Database.html[Database] class.
Just pass in a database name and optionally a https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-android}{empty}/couchbase-lite-android/com/couchbase/lite/DatabaseConfiguration.html[DatabaseConfiguration] -- see xref:android:database.adoc#ex-dbopen[].

Things to watch for include:

* If the named database does not exist in the specified, or default, location then a new one is created
* The database is created in a default location unless you  specify a directory for it -- see: https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-android}{empty}/couchbase-lite-android/com/couchbase/lite/DatabaseConfiguration.html[DatabaseConfiguration] and https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-android}{empty}/couchbase-lite-android/com/couchbase/lite/DatabaseConfiguration.html#setDirectory-java.lang.String-[DatabaseConfiguration.setDirectory()]
+
--

Typically, the default location for Android is
the application sandbox
.

See also xref:android:database.adoc#lbl-find-db-loc[].
--

[#ex-dbopen]
.Open or create a database


[#ex-dbopen]
====

[tabs]
=====


Kotlin::
+
--

[source, Kotlin]
----
include::android:example$codesnippet_collection.kt[tags="new-database", indent=0]
----

--

Java::
+
--
[source, Java]
----
include::android:example$codesnippet_collection.java[tags="new-database", indent=0]
----
--

=====


====


[#close-database]
== Close Database

You are advised to incorporate the closing of all open databases into your application workflow.

To close a database, use https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-android}{empty}/couchbase-lite-android/com/couchbase/lite/Database.html#close--[Database.close()] -- see: xref:android:database.adoc#ex-dbclose[].
This also closes
footnote:fn28[Commencing with Release 2.8]
active replications, listeners and-or live queries connected to the database.

NOTE: Closing a database soon after starting a replication involving it can cause an exception as the asynchronous `replicator (start)` may not yet be `connected`.

.Safely Closing a Database pre 2.8
TIP: Before closing, check that any attached listeners (query/replication/change) indicate they are at least at `connected` status before closing -- see for example: xref:android:replication.adoc#lbl-repl-mon[Monitor Status].

.Close a Database
[#ex-dbclose]


[#ex-dbclose]
====

[tabs]
=====


Kotlin::
+
--

[source, Kotlin]
----
include::android:example$codesnippet_collection.kt[tags="close-database", indent=0]
----

--

Java::
+
--
[source, Java]
----
include::android:example$codesnippet_collection.java[tags="close-database", indent=0]
----
--

=====


====


[#database-full-sync]
== Database Full Sync

Database Full Sync will prevent the loss of transactional data due to an unexpected system crash or loss of power.
This feature is not enabled by default and must be manually set in your database configuration.


CAUTION: Database Full Sync is a safe method to prevent data loss but will incur a significant degredation of performance.

.Enable Database Full Sync
[#ex-dbfullsync]


[#ex-dbfullsync]
====

[tabs]
=====


Kotlin::
+
--

[source, Kotlin]
----
include::android:example$codesnippet_collection.kt[tags="database-fullsync", indent=0]
----

--

Java::
+
--
[source, Java]
----
include::android:example$codesnippet_collection.java[tags="database-fullsync", indent=0]
----
--

=====


====


NOTE: Once a Database is created, its configuration is immutable — modifying the `DatabaseConfiguration` property afterwards has no effect on the existing instance.

[#database-encryption]
== Database Encryption


IMPORTANT: This is an https://www.couchbase.com/products/editions[Enterprise Edition] feature.


_Couchbase Lite on Android_ includes the ability to encrypt Couchbase Lite databases.
This allows mobile applications to secure the data at rest, when it is being stored on the device.
The algorithm used to encrypt the database is 256-bit AES.

[#enabling]
=== Enabling
To enable encryption, use https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-android}{empty}/couchbase-lite-android/com/couchbase/lite/DatabaseConfiguration.html#setEncryptionKey-com.couchbase.lite.EncryptionKey-[DatabaseConfiguration.setEncryptionKey()] to set the encryption key of your choice.
Provide this encryption key every time the database is opened -- see xref:android:database.adoc#ex-sdb-encrypt[].

.Configure Database Encryption
[#ex-sdb-encrypt]


[#ex-sdb-encrypt]
====

[tabs]
=====


Kotlin::
+
--

[source, Kotlin]
----
include::android:example$codesnippet_collection.kt[tags="database-encryption", indent=0]
----

--

Java::
+
--
[source, Java]
----
include::android:example$codesnippet_collection.java[tags="database-encryption", indent=0]
----
--

=====


====


[#persisting]
=== Persisting
Couchbase Lite does not persist the key.
It is the application's responsibility to manage the key and store it in a platform-specific secure store such Android's
https://developer.android.com/training/articles/keystore[Keystore].

[#opening]
=== Opening
An encrypted database can only be opened with the same platform that was used to encrypt it in the first place.
So a database encrypted using the Android SDK, and then exported, is readable only by the Android SDK.

[#changing]
=== Changing
To change an existing encryption key, open the database using its existing encryption-key and use https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-android}{empty}/couchbase-lite-android/com/couchbase/lite/Database.html#changeEncryptionKey(com.couchbase.lite.EncryptionKey)[Database.changeEncryptionKey()]
to set the required new encryption-key value.


[#removing]
=== Removing
To remove encryption, open the database using its existing encryption-key and use
https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-android}{empty}/couchbase-lite-android/com/couchbase/lite/Database.html#changeEncryptionKey(com.couchbase.lite.EncryptionKey)[Database.changeEncryptionKey()]
with a null value as the encryption key.

[#upgrading]
=== Upgrading
To upgrade an encrypted database see: xref:android:dep-upgrade.adoc#lbl-db-upgrades[Upgrade 1.x databases]


[#lbl-find-db-loc]
== Finding a Database File


When the application is running on the Android emulator, you can locate the application's data folder and access the database file by using the *adb* CLI tools.
For example, to list the different databases on the emulator, you can run the following commands.

.List
[source, bash]
----
$ adb shell
$ su
$ cd /data/data/{APPLICATION_ID}/files
$ ls
----

The *adb pull* command can be used to pull a specific database to your host machine.

.Pull using adb command
====
[source, bash]
----
$ adb root
$ adb pull /data/data/{APPLICATION_ID}/files/{DATABASE_NAME}.cblite2 .
----
====


[#lbl-db-util]
== Database Maintenance

From time to time it may be necessary to perform certain maintenance activities on your database, for example to
compact the database file, removing unused documents and blobs no longer referenced by any documents.

Couchbase Lite's API provides the https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-android}{empty}/couchbase-lite-android/com/couchbase/lite/Database.html#performMaintenance-com.couchbase.lite.MaintenanceType-[Database.performMaintenance()] method.
The available maintenance operations, including `compact` are as shown in the enum https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-android}{empty}/couchbase-lite-android/com/couchbase/lite/MaintenanceType.html[MaintenanceType] to accomplish this.

This is a resource intensive operation and is not performed automatically.
It should be run on-demand using the API.
If in doubt, consult Couchbase support.


[#cli-tool]
== Command Line Tool

// tag::cli-tool[]
`cblite` is a command-line tool for inspecting and querying Couchbase Lite databases.

You can download and build it from the couchbaselabs https://github.com/couchbaselabs/couchbase-mobile-tools/blob/master/README.cblite.md[GitHub repository].
Note that the `cblite` tool is not supported by the https://www.couchbase.com/support-policy[Couchbase Support Policy].

// end::cli-tool[]

[#troubleshooting]
== Troubleshooting
You should use console logs as your first source of diagnostic information.
If the information in the default logging level is insufficient you can focus it on database errors and generate more verbose messages -- see: xref:android:database.adoc#ex-logdb[].

For more on using Couchbase logs -- see: xref:android:troubleshooting-logs.adoc[Using Logs].

[#ex-logdb]
.Increase Level of Database Log Messages


[#ex-logdb]
====

[tabs]
=====


Kotlin::
+
--

[source, Kotlin]
----
include::android:example$codesnippet_collection.kt[tags="console-logging-db", indent=0]
----

--

Java::
+
--
[source, Java]
----
include::android:example$codesnippet_collection.java[tags="console-logging-db", indent=0]
----
--

=====


====


[#related-content]
== Related Content
++++
<div class="card-row three-column-row">
++++

[.column]
=== {empty}
.How to . . .
* xref:android:gs-prereqs.adoc[Prerequisites]
* xref:android:gs-install.adoc[Install]
* xref:android:gs-build.adoc[Build and Run]


.

[.column]
=== {empty}
.Learn more . . .
* xref:android:database.adoc[Databases]
* xref:android:document.adoc[Documents]
* xref:android:blob.adoc[Blobs]
* xref:android:replication.adoc[Remote Sync Gateway]
* xref:android:conflict.adoc[Handling Data Conflicts]

.


[.column]
=== {empty}
.Dive Deeper . . .
https://forums.couchbase.com/c/mobile/14[Mobile Forum] |
https://blog.couchbase.com/[Blog] |
https://docs.couchbase.com/tutorials/[Tutorials]

.


++++
</div>
++++


