
= Data Sync Locally on Device
:page-aliases: learn/java-android-dbreplica.adoc
:page-role:
:description: Couchbase Lite Database Sync - Synchronize changes between databases on the same device


:source-language: Java


:source-language: Kotlin


[abstract]
--
Description -- _{description}_ +
Related Content -- xref:android:replication.adoc[Remote Sync Gateway] | xref:android:landing-p2psync.adoc[Peer-to-Peer Sync]
--

[#overview]
== Overview


Couchbase Lite supports replication between two local databases at the database, scope, or collection level.
This allows a Couchbase Lite replicator to store data on secondary storage.
It is useful in scenarios when a user's device is damaged and its data is moved to a different device.

.Replication between Local Databases


====

[tabs]
=====


Kotlin::
+
--

[source, Kotlin]
----
include::android:example$codesnippet_collection.kt[tags="database-replica", indent=0]
----

--

Java::
+
--
[source, Java]
----
include::android:example$codesnippet_collection.java[tags="database-replica", indent=0]
----
--

=====


====


[#related-content]
== Related Content
++++
<div class="card-row three-column-row">
++++

[.column]
====== {empty}
.How to . . .
* xref:android:gs-prereqs.adoc[Prerequisites]
* xref:android:gs-install.adoc[Install]
* xref:android:gs-build.adoc[Build and Run]


.

[.column]
====== {empty}
.Learn more . . .
* xref:android:database.adoc[Databases]
* xref:android:document.adoc[Documents]
* xref:android:blob.adoc[Blobs]
* xref:android:replication.adoc[Remote Sync Gateway]
* xref:android:conflict.adoc[Handling Data Conflicts]

.


[.column]
====== {empty}
.Dive Deeper . . .
https://forums.couchbase.com/c/mobile/14[Mobile Forum] |
https://blog.couchbase.com/[Blog] |
https://docs.couchbase.com/tutorials/[Tutorials]

.


++++
</div>
++++


