= Preparing for Couchbase Lite on Android
:page-aliases: start/java-android-gs-prereqs.adoc
:page-role:
:description: Prerequisites for the installation of Couchbase Lite
:keywords: edge nosql api android java

:source-language: Java

:source-language: Kotlin


[abstract]
--
Description -- _{description}_ +
_Abstract -- Laying out some of the pre-requisites and preparatory steps to be considered before installing Couchbase Lite for android_ +
--
// include::ROOT:partial$block-related-get-started.adoc[]

// :ziputils: ROOT:example$/java-android/app/src/main/java/com/couchbase/code_snippets/ZipUtils.java

[#supported-versions]
== Supported Versions

[IMPORTANT]
--
The requirements listed below are for the *Java/Kotlin SDK* on Android (Minimum API Level *22*).

If you're developing with the *C/{cpp} SDK* on Android, the minimum API Level is *24*.
For C/{cpp} SDK requirements, see xref:c:supported-os.adoc#android[Couchbase Lite for C - Android Requirements].
--

The xref:android:supported-os.adoc#supported-os-versions[Supported OS Versions] lists certified Android versions.
Couchbase does not test against, nor guarantee support for, uncertified Android versions such as versions built from source.

[%autowidth.stretch]
|===
|Platform |Runtime architectures |Minimum API Level

|Android
|armeabi-v7a
|22

|Android
|arm64-v8a
|22

|Android
|x86
|22

|Android
|x86_64
|22
|===

[#supported-versions-for-vector-search-4-0-0]
== Supported Versions for Vector Search 4.0.0

[IMPORTANT]
--
To use Vector Search, you must have Couchbase Lite installed and add the Vector Search extension to your Couchbase Lite application.
Vector Search is available only for 64-bit architectures and
Intel processors that support the Advanced Vector Extensions 2 (AVX2) instruction set.
To verify whether your device supports the AVX2 instructions set, https://www.intel.com/content/www/us/en/support/articles/000090473/processors/intel-core-processors.html[follow these instructions.]
--

[%autowidth.stretch]
|===
|Platform |Runtime architectures |Minimum API Level

|Android
|arm64-v8a
|23

|Android
|x86_64
|23
|===


// more applicable for bluetooth implementations - others _should_ work with older Android - commenting out for now
////
== Supported Versions for Multipeer Replicator

[%autowidth.stretch]
|===
|Platform |Runtime architectures |Minimum API Level

|Android
|arm64-v8a
|35

|Android
|x86_64
|35
|===
////



[#related-content]
== Related Content
++++
<div class="card-row three-column-row">
++++

[.column]
====== {empty}
.How to . . .
* xref:android:gs-prereqs.adoc[Prerequisites]
* xref:android:gs-install.adoc[Install]
* xref:android:gs-build.adoc[Build and Run]


.

[.column]
====== {empty}
.Learn more . . .
* xref:android:database.adoc[Databases]
* xref:android:document.adoc[Documents]
* xref:android:blob.adoc[Blobs]
* xref:android:replication.adoc[Remote Sync Gateway]
* xref:android:conflict.adoc[Handling Data Conflicts]

.


[.column]
====== {empty}
.Dive Deeper . . .
https://forums.couchbase.com/c/mobile/14[Mobile Forum] |
https://blog.couchbase.com/[Blog] |
https://docs.couchbase.com/tutorials/[Tutorials]

.


++++
</div>
++++


