:docname: kotlin
:page-module: android
:page-relative-src-path: kotlin.adoc
:page-origin-url: https://github.com/couchbase/docs-couchbase-lite.git
:page-origin-start-path:
:page-origin-refname: antora-assembler-simplification
:page-origin-reftype: branch
:page-origin-refhash: (worktree)
[#android:kotlin:::]
== Kotlin
:page-role:
:description: Couchbase Lite for Android -- Kotlin support


[abstract]
--
Description -- _{description}_ +
Related Content -- xref:android:database.adoc[Databases] | xref:android:document.adoc[Documents] | xref:android:indexing.adoc[Indexing] |
--








[discrete#android:kotlin:::introduction]
=== Introduction


pass:q,a[_pass:q,a[pass:q,a[Couchbase{nbsp}Lite]]_] _Android {major}.{minor}.{base}{empty}_ introduces full idiomatic support for Kotlin apps, out-of-the-box.

Kotlin developers can now build apps using https://developer.android.com/kotlin/common-patterns[common Kotlin Patterns], that integrate seamlessly with Couchbase Lite for Android and have full feature parity with the Java API; including some convenient Kotlin Extensions to get you started.

Key features include:

* Nullability annotations
* Named parameters
* Kotlin Flows, for asynchronous event notifications

Java support and functionality continues for Android.


[discrete#android:kotlin:::kotlin-extensions]
=== Kotlin Extensions

In addition to having full co-compatible access to the existing Java API, Kotlin developers can also access a number of Kotlin Extensions.

The
https://docs.couchbase.com/mobile/{major}.{minor}.{base}{empty}/couchbase-lite-android-ktx[Kotlin Extensions]
package includes:

* <<android:kotlin:::lbl-factories>> for the configuration of important Couchbase Lite objects such as _Databases_, _Replicators_ and _Listeners_.
* Change Flows that monitor key  Couchbase Lite objects fpr change using Kotlin features such as, Co-routines and https://developer.android.com/kotlin/flow[Flows].

See: https://docs.couchbase.com/mobile/{major}.{minor}.{base}{empty}/couchbase-lite-android-ktx[Kotlin Extensions] for extension API docs


[discrete#android:kotlin:::lbl-factories]
=== Configuration Factories

pass:q,a[pass:q,a[Couchbase{nbsp}Lite]] provides a set of https://docs.couchbase.com/mobile/{major}.{minor}.{base}{empty}/couchbase-lite-android-ktx/com/couchbase/lite/ConfigurationFactoriesKt.html[ConfigurationFactories] and https://docs.couchbase.com/mobile/{major}.{minor}.{base}{empty}/couchbase-lite-android-ktx/com/couchbase/lite/CommonConfigurationFactoriesKt.html[CommonConfigurationFactories], these allow use of named parameters to specify property settings.

This makes it simple to create variant configurations, by simply overriding named parameters:

.Example of overriding configuration
[pass:q,a[source, kotlin, indent=0]]
----
        val listener8080 = URLEndpointListenerConfigurationFactory.newConfig(
            networkInterface = "en0",
            port = 8080
        )
        val listener8081 = listener8080.newConfig(port = 8081)
----

[discrete#android:kotlin:::database]
==== Database
Use
https://docs.couchbase.com/mobile/{major}.{minor}.{base}{empty}/couchbase-lite-android-ktx/com/couchbase/lite/ConfigurationFactoriesKt.html#DatabaseConfigurationFactory[DatabaseConfigurationFactory]
to create a `DatabaseConfiguration` object, overriding the receiver's values with the passed parameters.

[{tabs}]
=====

[#android:kotlin:::tabs-1-in-use]
In Use::
+
--
[pass:q,a[source, kotlin, indent=0]]
----

        database = Database("getting-started")

----
--

[#android:kotlin:::tabs-1-definition]
Definition::
+
--
[pass:q,a[source, kotlin, indent=0]]
----
val DatabaseConfigurationFactory: DatabaseConfiguration? = null

fun DatabaseConfiguration?.create(
    databasePath: String? = null,
    encryptionKey: EncryptionKey? = null
)
----
--
=====

[discrete#android:kotlin:::replication]
==== Replication
Use
https://docs.couchbase.com/mobile/{major}.{minor}.{base}{empty}/couchbase-lite-android-ktx/com/couchbase/lite/ConfigurationFactoriesKt.html#ReplicatorConfigurationFactory[ReplicatorConfigurationFactory]
to create a `ReplicatorConfiguration` object, overriding the receiver's values with the passed parameters.

[{tabs}]
=====

[#android:kotlin:::tabs-2-in-use]
In Use::
+
--
[pass:q,a[source, kotlin, indent=0]]
----
        val replicator =
            Replicator(
                ReplicatorConfigurationFactory.newConfig(
                    collections = mapOf(db.collections to null),
                    target = URLEndpoint(URI("ws://localhost:4984/getting-started-db")),
                    type = ReplicatorType.PUSH_AND_PULL,
                    authenticator = BasicAuthenticator("sync-gateway", "password".toCharArray())
                )
            )

----
--

[#android:kotlin:::tabs-2-definition]
Definition::
+
--
[pass:q,a[source, kotlin, indent=0]]
----
val ReplicatorConfigurationFactory: ReplicatorConfiguration? = null

fun ReplicatorConfiguration?.create(
    database: Database? = null,
    target: Endpoint? = null,
    type: ReplicatorType? = null,
    continuous: Boolean? = null,
    authenticator: Authenticator? = null,
    headers: Map<String, String>? = null,
    pinnedServerCertificate: ByteArray? = null,
    channels: List<String>? = null,
    documentIDs: List<String>? = null,
    pushFilter: ReplicationFilter? = null,
    pullFilter: ReplicationFilter? = null,
    conflictResolver: ConflictResolver? = null,
    maxAttempts: Int? = null,
    maxAttemptWaitTime: Int? = null,
    heartbeat: Int? = null,
    enableAutoPurge: Boolean? = null,
    acceptOnlySelfSignedServerCertificate: Boolean? = null
)

val MessageEndpointListenerConfigurationFactory: MessageEndpointListenerConfiguration? = null

fun MessageEndpointListenerConfiguration?.create(
    database: Database? = null,
    protocolType: ProtocolType? = null
)
----
--
=====

//
[discrete#android:kotlin:::full-text-search]
==== Full Text Search
Use
https://docs.couchbase.com/mobile/{major}.{minor}.{base}{empty}/couchbase-lite-android-ktx/com/couchbase/lite/CommonConfigurationFactoriesKt.html#FullTextIndexConfigurationFactory[FullTextIndexConfigurationFactory]
to create a `FullTextIndexConfiguration` object, overriding the receiver's values with the passed parameters.

[{tabs}]
=====

[#android:kotlin:::tabs-3-in-use]
In Use::
+
--
[pass:q,a[source, kotlin, indent=0]]
----
    collection.createIndex(
        "overviewFTSIndex",
        FullTextIndexConfigurationFactory.newConfig("overview"))
----
--

[#android:kotlin:::tabs-3-definition]
Definition::
+
--
----
val FullTextIndexConfigurationFactory: FullTextIndexConfiguration? = null

fun FullTextIndexConfiguration?.create(expression: String? = null)
----
--
=====


[discrete#android:kotlin:::indexing]
==== Indexing
Use
https://docs.couchbase.com/mobile/{major}.{minor}.{base}{empty}/couchbase-lite-android-ktx/com/couchbase/lite/CommonConfigurationFactoriesKt.html#ValueIndexConfigurationFactory[ValueIndexConfigurationFactory]
to create a `ValueIndexConfiguration` object, overriding the receiver's values with the passed parameters.

[{tabs}]
=====

[#android:kotlin:::tabs-4-in-use]
In Use::
+
--
[pass:q,a[source, kotlin, indent=0]]
----
    collection.createIndex(
        "TypeNameIndex",
        ValueIndexConfigurationFactory.newConfig("type", "name")
    )
----
--

[#android:kotlin:::tabs-4-definition]
Definition::
+
--
----
val ValueIndexConfigurationFactory: ValueIndexConfiguration? = null

fun ValueIndexConfiguration?.create(vararg expressions: String = emptyArray())
----
--
=====

[discrete#android:kotlin:::logs]
==== Logs
Use
https://docs.couchbase.com/mobile/{major}.{minor}.{base}{empty}/couchbase-lite-android-ktx/com/couchbase/lite/CommonConfigurationFactoriesKt.html#LogFileConfigurationFactory[LogFileConfigurationFactory]
to create a `LogFileConfiguration` object, overriding the receiver's values with the passed parameters.

[{tabs}]
=====

[#android:kotlin:::tabs-5-in-use]
In Use::
+
--
[pass:q,a[source, kotlin, indent=0]]
----

        Database.log.file.let {
            it.config = LogFileConfigurationFactory.newConfig(
                context.cacheDir.absolutePath, // <.>
                maxSize = 10240, // <.>
                maxRotateCount = 5, // <.>
                usePlainText = false
            ) // <.>
            it.level = LogLevel.INFO // <.>

        }

----
--

[#android:kotlin:::tabs-5-definition]
Definition::
+
--
----
val LogFileConfigurationFactory: LogFileConfiguration? = null

.LogFileConfiguration.create()

fun LogFileConfiguration?.create(
    directory: String? = null,
    maxSize: Long? = null,
    maxRotateCount: Int? = null,
    usePlainText: Boolean? = null
)
----
--
=====


[discrete#android:kotlin:::flows]
=== Flows

These wrappers use _Flowables_ to monitor for changes.

[discrete#android:kotlin:::database-change-flow]
==== Database Change Flow

Use the
https://docs.couchbase.com/mobile/{major}.{minor}.{base}{empty}/couchbase-lite-android-ktx/com/couchbase/lite/CommonFlowsKt.html#databaseChangeFlow(Database,Executor)[databaseChangeFlow(Database,Executor)]
to monitor database change events.

[{tabs}]
=====

[#android:kotlin:::tabs-6-in-use]
In Use::
+
--

[pass:q,a[source, kotlin, indent=0]]
----

val updatedDocs = db.databaseChangeFlow()
    .map { it.documentIDs }
    .asLiveData()

----
--

[#android:kotlin:::tabs-6-definition]
Definition::
+
--

[pass:q,a[source, kotlin, indent=0]]
----

@ExperimentalCoroutinesApi
fun Database.databaseChangeFlow(executor: Executor? = null)
----
--

=====


[discrete#android:kotlin:::document-change-flow]
==== Document Change Flow
Use
https://docs.couchbase.com/mobile/{major}.{minor}.{base}{empty}/couchbase-lite-android-ktx/com/couchbase/lite/CommonFlowsKt.html#documentChangeFlow(Database,String,Executor)[documentChangeFlow(Database,String,Executor)]
to monitor changes to a document.

[{tabs}]
=====

[#android:kotlin:::tabs-7-in-use]
In Use::
+
--

[pass:q,a[source, kotlin, indent=0]]
----

val docModDate = db.documentChangeFlow("1001", null)
    .map { it.collection.getDocument(it.documentID)?.getString("lastModified") }
    .asLiveData()

----
--

[#android:kotlin:::tabs-7-definition]
Definition::
+
--

[pass:q,a[source, kotlin, indent=0]]
----
@ExperimentalCoroutinesApi

fun Database.documentChangeFlow(documentId: String, executor: Executor? = null)

----
--

=====

[discrete#android:kotlin:::replicator-change-flow]
==== Replicator Change Flow
Use
https://docs.couchbase.com/mobile/{major}.{minor}.{base}{empty}/couchbase-lite-android-ktx/com/couchbase/lite/CommonFlowsKt.html#replicatorChangeFlow(Replicator,Executor)[replicatorChangeFlow(Replicator,Executor)]
to monitor replicator changes.

[{tabs}]
=====

[#android:kotlin:::tabs-8-in-use]
In Use::
+
--

[pass:q,a[source, kotlin, indent=0]]
----

val replState = repl.replicatorChangesFlow()
    .map { it.status.activityLevel }
    .asLiveData()

----
--

[#android:kotlin:::tabs-8-definition]
Definition::
+
--

[pass:q,a[source, kotlin, indent=0]]
----
@ExperimentalCoroutinesApi
fun Replicator.replicatorChangesFlow(executor: Executor? = null)
----
--
=====


[discrete#android:kotlin:::document-replicator-change-flow]
==== Document Replicator Change Flow
Use
https://docs.couchbase.com/mobile/{major}.{minor}.{base}{empty}/couchbase-lite-android-ktx/com/couchbase/lite/CommonFlowsKt.html#documentReplicationFlow(Replicator,Executor)[documentReplicationFlow(Replicator,Executor)]
to monitor document changes during replication.

[{tabs}]
=====

[#android:kotlin:::tabs-9-in-use]
In Use::
+
--

[pass:q,a[source, kotlin, indent=0]]
----

val replicatedDocs = repl.documentReplicationFlow(testSerialExecutor)
    .map { update -> update.documents }
    .onEach { listView.setUpdated(it) }
    .collect()

----
--

[#android:kotlin:::tabs-9-definition]
Definition::
+
--

[pass:q,a[source, kotlin, indent=0]]
----

@ExperimentalCoroutinesApi
fun Replicator.documentReplicationFlow(executor: Executor? = null)


----
--
=====


[discrete#android:kotlin:::query-change-flow]
==== Query Change Flow
Use
https://docs.couchbase.com/mobile/{major}.{minor}.{base}{empty}/couchbase-lite-android-ktx/com/couchbase/lite/CommonFlowsKt.html#queryChangeFlow(Query,Executor)[queryChangeFlow(Query,Executor)]
to monitor document changes during replication.

[{tabs}]
=====

[#android:kotlin:::tabs-10-in-use]
In Use::
+
--

[pass:q,a[source, kotlin, indent=0]]
----

    fun watchQuery(query: Query): LiveData<List<Result>> {
        return query.queryChangeFlow()
            .mapNotNull { change ->
                val err = change.error
                if (err != null) {
                    throw err
                }
                change.results?.allResults()
            }
            .asLiveData()
    }

----
--

[#android:kotlin:::tabs-10-definition]
Definition::
+
--

[pass:q,a[source, kotlin, indent=0]]
----

@ExperimentalCoroutinesApi
fun Query.queryChangeFlow(executor: Executor? = null)

----
--
=====


//
// :param-add3-title: {empty}
// :param-reference: reference-p2psync


[discrete#android:kotlin:::related-content]
=== Related Content
++++
<div class="card-row three-column-row">
++++

[.column]
==== {empty}
.How to . . .
* xref:android:gs-prereqs.adoc[Prerequisites]
* xref:android:gs-install.adoc[Install]
* xref:android:gs-build.adoc[Build and Run]


.

[discrete.colum#android:kotlin:::-2n]
==== {empty}
.Learn more . . .
* xref:android:database.adoc[Databases]
* xref:android:document.adoc[Documents]
* xref:android:blob.adoc[Blobs]
* xref:android:replication.adoc[Remote Sync Gateway]
* xref:android:conflict.adoc[Handling Data Conflicts]

.


[.column]
// [.content]
[discrete#android:kotlin:::-3]
==== {empty}
.Dive Deeper . . .
//* Community
https://forums.couchbase.com/c/mobile/14[Mobile Forum] |
https://blog.couchbase.com/[Blog] |
https://docs.couchbase.com/tutorials/[Tutorials]


.



++++
</div>
++++


