= Kotlin
:page-edition: {release}
:page-status: {prerelease}
:page-role:
:description: Couchbase Lite for Android -- Kotlin support

include::partial$_std-cbl-hdr-android.adoc[]

:param-related: {database--xref} | {document--xref} | {indexing--xref} |
:topic-group: Topic Group -- Data Model
include::{root-partials}block-abstract.adoc[]

:url-api-references-kotlin: https://docs.couchbase.com/mobile/3.0.0-beta01/couchbase-lite-android-ktx/com/couchbase/lite/
:url-api-references-kotlin-config-factories: {url-api-references-kotlin}ConfigurationFactoriesKt.html
:url-api-references-kotlin-common-config-factories: {url-api-references-kotlin}CommonConfigurationFactoriesKt.html
:url-api-references-kotlin-common-flows: {url-api-references-kotlin}CommonFlowsKt.html


:config-factories: {url-api-references-kotlin-config-factories}[ConfigurationFactories()]
:database-configuration-factory: {url-api-references-kotlin-config-factories}#DatabaseConfigurationFactory[DatabaseConfigurationFactory]
:replicator-configuration-factory: {url-api-references-kotlin-config-factories}#ReplicatorConfigurationFactory[ReplicatorConfigurationFactory]

:common-config-factories: {url-api-references-kotlin-common-config-factories}[CommonConfigurationFactories()]
:fulltextindex-configuration-factory: {url-api-references-kotlin-common-config-factories}#FullTextIndexConfigurationFactory[FullTextIndexConfigurationFactory]
:valueindex-configuration-factory: {url-api-references-kotlin-common-config-factories}#ValueIndexConfigurationFactory[ValueIndexConfigurationFactory]
:logfile-configuration-factory: {url-api-references-kotlin-common-config-factories}#LogFileConfigurationFactory[LogFileConfigurationFactory]

:flows-database-change: {url-api-references-kotlin-common-flows}#databaseChangeFlow(Database,Executor)[databaseChangeFlow(Database,Executor)]
:flows-document-change: {url-api-references-kotlin-common-flows}#documentChangeFlow(Database,String,Executor)[documentChangeFlow(Database,String,Executor)]
:flows-replicator-changes: {url-api-references-kotlin-common-flows}#replicatorChangeFlow(Replicator,Executor)[replicatorChangeFlow(Replicator,Executor)]
:flows-document-replication: {url-api-references-kotlin-common-flows}#documentReplicationFlow(Replicator,Executor)[documentReplicationFlow(Replicator,Executor)]
:flows-query-changes: {url-api-references-kotlin-common-flows}#queryChangeFlow(Query,Executor)[queryChangeFlow(Query,Executor)]

:source-header: pass:q,a[source, kotlin, subs="attributes+,macros+", indent=0]
:snippets_root: example$snippets/app/src/main/kotlin/com/couchbase/code_snippets/


== Introduction

{cbl-te} _{param-title} {version-full}_ introduces full idiomatic support for Kotlin apps, out-of-the-box.

Kotlin developers can now build apps using https://developer.android.com/kotlin/common-patterns[common Kotlin Patterns], that integrate seamlessly with Couchbase Lite for Android and have full feature parity with the Java API; no need for custom extensions.

Key features include:

* Nullability annotations
* Named parameters
* Kotlin Flows, for asynchronous event notifications

Java support and functionality continues for Android.

You can choose whether to use the Kotlin extensions API or continue using the Java API.


== Kotlin-specific API

In addition to having full co-compatible access to the existing Java API, Kotlin developers can also access a number of Kotlin-specific API calls.

These
https://docs.couchbase.com/mobile/{major}.{minor}.{base}-{releasetag}/couchbase-lite-android-ktx[Kotlin Specific API]
take advantage of Kotlin features such as, Co-routines and https://developer.android.com/kotlin/flow[Flows].


== Configuration Factory Constructors

{cbl-t} provides a set of {config-factories} and {common-config-factories}, these constructors allow use of named parameters to specify property settings.

=== Database
Use
{database-configuration-factory}
to create a `DatabaseConfiguration` object, overriding the receiver's values with the passed parameters.

[{tabs}]
=====

In Use::
+
--
[{source-header}]
----

include::{snippets_root}BasicExamples.kt[tags=database-config-factory]

----
--

Definition::
+
--
[{source-header}]
----
val DatabaseConfigurationFactory: DatabaseConfiguration? = null

fun DatabaseConfiguration?.create(
    databasePath: String? = null,
    encryptionKey: EncryptionKey? = null
)
----
--
=====

=== Replication
Use
{replicator-configuration-factory}
to create a `ReplicatorConfiguration` object, overriding the receiver's values with the passed parameters.

[{tabs}]
=====

In Use::
+
--
[{source-header}]
----

include::{snippets_root}BasicExamples.kt[tags=replicator-config-factory]

----
--

Definition::
+
--
[{source-header}]
----
val ReplicatorConfigurationFactory: ReplicatorConfiguration? = null

fun ReplicatorConfiguration?.create(
    database: Database? = null,
    target: Endpoint? = null,
    type: ReplicatorType? = null,
    continuous: Boolean? = null,
    authenticator: Authenticator? = null,
    headers: Map<String, String>? = null,
    pinnedServerCertificate: ByteArray? = null,
    channels: List<String>? = null,
    documentIDs: List<String>? = null,
    pushFilter: ReplicationFilter? = null,
    pullFilter: ReplicationFilter? = null,
    conflictResolver: ConflictResolver? = null,
    maxAttempts: Int? = null,
    maxAttemptWaitTime: Int? = null,
    heartbeat: Int? = null,
    enableAutoPurge: Boolean? = null,
    acceptOnlySelfSignedServerCertificate: Boolean? = null
)

val MessageEndpointListenerConfigurationFactory: MessageEndpointListenerConfiguration? = null

fun MessageEndpointListenerConfiguration?.create(
    database: Database? = null,
    protocolType: ProtocolType? = null
)
----
--
=====

//
=== Full Text Search
Use
{fulltextindex-configuration-factory}
to create a `FullTextIndexConfiguration` object, overriding the receiver's values with the passed parameters.

[{tabs}]
=====

In Use::
+
--
[{source-header}]
----

db.createIndex("fts_index",
      FullTextIndexConfigurationFactory.create(expressions = ["name","location"])
    )

----
--

Definition::
+
--
----
val FullTextIndexConfigurationFactory: FullTextIndexConfiguration? = null

fun FullTextIndexConfiguration?.create(expression: String? = null)
----
--
=====


=== Indexing
Use
{valueindex-configuration-factory}
to create a `ValueIndexConfiguration` object, overriding the receiver's values with the passed parameters.

[{tabs}]
=====

In Use::
+
--
[{source-header}]
----

db.createIndex("name_and_location_index",
      ValueIndexConfigurationFactory.create(expressions = ["name","location"])
    )

----
--

Definition::
+
--
----
val ValueIndexConfigurationFactory: ValueIndexConfiguration? = null

fun ValueIndexConfiguration?.create(vararg expressions: String = emptyArray())
----
--
=====

=== Logs
Use
{logfile-configuration-factory}
to create a `LogFileConfiguration` object, overriding the receiver's values with the passed parameters.

[{tabs}]
=====

In Use::
+
--
[{source-header}]
----
include::{snippets_root}BasicExamples.kt
include::{snippets_root}BasicExamples.kt[tags=file-logging-config-factory]

----
--

Definition::
+
--
----
val LogFileConfigurationFactory: LogFileConfiguration? = null

.LogFileConfiguration.create()

fun LogFileConfiguration?.create(
    directory: String? = null,
    maxSize: Long? = null,
    maxRotateCount: Int? = null,
    usePlainText: Boolean? = null
)
----
--
=====


== Flows

These wrappers use _Flowables_ to monitor for changes.

=== Database Change Listener

Use the
{flows-database-change}
to monitor database change events.

[{tabs}]
=====

In Use::
+
--

[{source-header}]
----

include::{snippets_root}FlowExamples.kt[tags=flow-as-database-change-listener]

----
--

Definition::
+
--

[{source-header}]
----

@ExperimentalCoroutinesApi
fun Database.databaseChangeFlow(executor: Executor? = null)
----
--

=====


=== Document Change Listener
Use
{flows-document-change}
to monitor changes to a document.

[{tabs}]
=====

In Use::
+
--

[{source-header}]
----

include::{snippets_root}FlowExamples.kt[tags=flow-as-document-change-listener]

----
--

Definition::
+
--

[{source-header}]
----
@ExperimentalCoroutinesApi

fun Database.documentChangeFlow(documentId: String, executor: Executor? = null)

----
--

=====

=== Replicator Change Listener
Use
{flows-replicator-changes}
to monitor replicator changes.

[{tabs}]
=====

In Use::
+
--

[{source-header}]
----

include::{snippets_root}FlowExamples.kt[tags=flow-as-replicator-change-listener]

----
--

Definition::
+
--

[{source-header}]
----
@ExperimentalCoroutinesApi
fun Replicator.replicatorChangesFlow(executor: Executor? = null)
----
--
=====


=== Document Replicator Change Listener
Use
{flows-document-replication}
to monitor document changes during replication.

[{tabs}]
=====

In Use::
+
--

[{source-header}]
----
// Placeholder -- content to be provided by GA
include::{snippets_root}FlowExamples.kt[tags=flow-as-document-replicator-change-listener]

----
--

Definition::
+
--

[{source-header}]
----

@ExperimentalCoroutinesApi
fun Replicator.documentReplicationFlow(executor: Executor? = null)


----
--
=====


=== Query Change Listener
Use
{flows-query-changes}
to monitor document changes during replication.

[{tabs}]
=====

In Use::
+
--

[{source-header}]
----

include::{snippets_root}FlowExamples.kt[tags=flow-as-query-change-listener]

----
--

Definition::
+
--

[{source-header}]
----

@ExperimentalCoroutinesApi
fun Query.queryChangeFlow(executor: Executor? = null)

----
--
=====


//
include::{root-partials}block-related-content-data.adoc[]
