
= Logging API
:page-status:
:page-edition:
:page-aliases:
:page-role:
:description: Introduced in Couchbase Lite 3.2.2.
:keywords: edge mobile api java kotlin android apple logging file console custom

[abstract]
--
{description} +
Related Content -- xref:android:troubleshooting-queries.adoc[Troubleshooting Queries]
--

// Sets the correct mobile sdk for xref links in the common page

:source-language: Java


:source-language: Kotlin


// ROOT:partial$commons/common-
[#logsinks]
== LogSinks

Log sinks are thread safe, removing risk of inconsistent states during initialization.

The three destinations for logs have been named as `LogSinks`, following the common source–sink terminology.

The `FileLogSink`, the `ConsoleLogSink` and the `CustomLogSink` are all to be installed in an instance of `LogSinks`.

Only `ConsoleLogSink` is enabled for all logging domains at the warning level by default.
To enable a specific type of log sink, create a log sink object of that type, set its minimum log level and domains, and assign it to `LogSinks`.
To disable a log sink, set it to null or use a log sink with `LogLevel.NONE`.

Couchbase still logs its messages in a handful of named domains and at common log levels: `LogLevel.DEBUG` the most verbose, and `LogLevel.ERROR` only for serious failures.

Accessing `LogSinks` depends on the platform.
In Java, use the method `LogSinks.get()` to obtain an instance.
In Swift, Objective-C, .NET, and C, `LogSinks` provides only static methods, without a singleton instance.

`LogSinks` are immutable: you set the level and domain at which they log in their constructors.

Log output is split into the following streams:

* xref:android:new-logging-api.adoc#lbl-file-logsink[]
+
Each log level writes to a separate file and there is a single retention policy for all files

* xref:android:new-logging-api.adoc#lbl-console-logsink[]
+
--
You can independently configure and control console logs, which provides a convenient method of accessing diagnostic information during debugging scenarios.

With console logging, you can fine-tune diagnostic output to suit specific debug scenarios, without interfering with any logging required by Couchbase Support for the investigation of issues.
--

* xref:android:new-logging-api.adoc#lbl-custom-logsink[]
+
For greater flexibility you can implement a custom logging class.

[#lbl-console-logsink]
=== Logging to the Console

Create an instance of `ConsoleLogSink` initialized with the desired log level and domains and install it.


[tabs]
=====

Java::
+
--

[source.no-callouts, java, indent=0]
----

include::java:example$snippets/common/main/java/com/couchbase/codesnippets/Examples.java[tags=new-console-logging]

----
--


Kotlin::
+
--

[source.no-callouts, kotlin, indent=0]
----

include::android:example$kotlin_snippets/app/src/main/kotlin/com/couchbase/codesnippets/BasicExamples.kt[tags=new-console-logging]

----
--
=====


[#lbl-file-logsink]
=== Logging to the Couchbase File Log

Create a new `FileLogSink` with the desired properties and install it.

NOTE: `setRotateCount` from before 3.2.2 API is slightly different from `setMaxKeptFiles`.
`setMaxKeptFiles` is the maximum number of log files that will exist at any time and is the count of rotated files (`setRotateCount`) plus one.


[tabs]
=====

Java::
+
--

[source.no-callouts, java, indent=0]
----

include::java:example$snippets/common/main/java/com/couchbase/codesnippets/Examples.java[tags=new-file-logging]

----
--


Kotlin::
+
--

[source.no-callouts, kotlin, indent=0]
----

include::android:example$kotlin_snippets/app/src/main/kotlin/com/couchbase/codesnippets/BasicExamples.kt[tags=new-file-logging]

----
--
=====


[#lbl-custom-logsink]
=== Using a Custom Logger

Create an instance of your custom sink, and to install it use `LogSinks.get().setCustom` in Java, or the appropriate static method in Swift, Objective-C, .NET, and C.

As with the other log sinks, you will have to specify the level and domain at which Couchbase logs are forwarded to your custom sink at its creation.


Your custom log sink code will have to change as well.
For Android, the most significant change is that instead of _implementing_ the `Logger` interface, a custom log sink must _extend_ the `BaseLogSink` class.

The `BaseLogSink` class does not have a no-args constructor: you must specify at least the level at which Couchbase logs will be forwarded to the logger.

Your logger will receive only logs at the level and domain for which it is initialized.
There is no need to record or filter the logs forwarded to the protected `writeLog` method.

`LogSinks` are meant to support logging by the Couchbase Lite platform. They were never meant as a general framework for logging.

IMPORTANT: Customer code can no longer log, directly, to any of the Couchbase log sinks.
The Console and File log sinks cannot be subclassed and do not publish methods that allow writing logs.
If you need to log to the console for example, you'll have to create your own way of doing so.


[tabs]
=====

Java::
+
[source.no-callouts, java, indent=0]
----

include::java:example$snippets/common/main/java/com/couchbase/codesnippets/Examples.java[tags=new-custom-logging]

----


Kotlin::
+
[source.no-callouts, kotlin, indent=0]
----

include::android:example$kotlin_snippets/app/src/main/kotlin/com/couchbase/codesnippets/BasicExamples.kt[tags=new-custom-logging]

----
=====

[#decoding-binary-logs]
== Decoding binary logs

NOTE: The latest version of the cbl-log tool is `3.0.0`.

You can use the *cbl-log* tool to decode binary log files -- see xref:android:troubleshooting-logs.adoc#eg-cbl-log[].

[#eg-cbl-log]
.Using the cbl-log tool
=====
[tabs]
====

macOS::
+
--
Download the *cbl-log* tool using `wget`.

[source,console,subs="attributes"]
----
wget https://packages.couchbase.com/releases/couchbase-lite-log/3.0.0/couchbase-lite-log-3.0.0-macos.zip
----

Extract the downloaded zip file.

[source,console]
----
unzip couchbase-lite-log-3.0.0-macos.zip
----

Navigate to the *bin* directory and run the `cbl-log` executable.

[source,console]
----
$ ./cbl-log logcat LOGFILE <OUTPUT_PATH>
----
--


CentOS::
+
--
Download the *cbl-log* tool using `wget`.

[source,console, subs="attributes"]
----
wget https://packages.couchbase.com/releases/couchbase-lite-log/3.0.0/couchbase-lite-log-3.0.0-centos.zip
----

Extract the downloaded zip file.

[source,console]
----
unzip couchbase-lite-log-3.0.0-centos.zip
----

Navigate to the *bin* directory and run the `cbl-log` executable.

[source,console]
----
cbl-log logcat LOGFILE <OUTPUT_PATH>
----
--


Windows::
+
--
Download the *cbl-log* tool using PowerShell.

[source,powershell, subs="attributes"]
----
Invoke-WebRequest https://packages.couchbase.com/releases/couchbase-lite-log/3.0.0/couchbase-lite-log-3.0.0-windows.zip -OutFile couchbase-lite-log-3.0.0-windows.zip
----

Extract the downloaded zip file.

[source,powershell]
----
Expand-Archive -Path couchbase-lite-log-3.0.0-windows.zip -DestinationPath .
----

Run the `cbl-log` executable.

[source,powershell]
----
$ .\cbl-log.exe logcat LOGFILE <OUTPUT_PATH>
----
--
====
=====


[#related-content]
== Related Content
++++
<div class="card-row three-column-row">
++++

[.column]
====== {empty}
.How to . . .
* xref:android:querybuilder.adoc[QueryBuilder]
* xref:android:query-n1ql-mobile.adoc[{sqlpp} for Mobile]
* xref:android:query-live.adoc[Live Queries]
* xref:android:fts.adoc[Full Text Search]


.

[.column]
====== {empty}
.Learn more . . .
* xref:android:query-n1ql-mobile-querybuilder-diffs.adoc[{sqlpp} Mobile - Querybuilder  Differences]
* xref:android:query-n1ql-mobile-server-diffs.adoc[{sqlpp} Mobile - {sqlpp} Server Differences]
* xref:android:query-resultsets.adoc[Query Resultsets]
* xref:android:query-troubleshooting.adoc[Query Troubleshooting]
* xref:android:query-live.adoc[Live Queries]

* xref:android:database.adoc[Databases]
* xref:android:document.adoc[Documents]
* xref:android:blob.adoc[Blobs]

.


[.column]
====== {empty}
.Dive Deeper . . .
https://forums.couchbase.com/c/mobile/14[Mobile Forum] |
https://blog.couchbase.com/[Blog] |
https://docs.couchbase.com/tutorials/[Tutorials]

.


++++
</div>
++++
