
= Result Sets
:page-role:
:description: How to use Couchbase Lite Query's Result Sets
:keywords: query, sql, n1ql, fuzzy-matching


:source-language: Java


:source-language: Kotlin


[abstract]
--
Description -- _{description}_ +
Related Content -- xref:android:querybuilder.adoc[QueryBuilder] |  xref:android:query-n1ql-mobile.adoc[{sqlpp} for Mobile] |  xref:android:querybuilder.adoc#lbl-predquery[Predictive Queries] | xref:android:query-live.adoc[Live Queries] | xref:android:indexing.adoc[Indexing]
--


[#query-execution]
== Query Execution
The execution of a Couchbase Lite for Android's database query returns an array of results, a result set.

Each row of the result set represents the data returned from a document that met the conditions defined by the `WHERE` statement of your query.
The composition of each row is determined by the `SelectResult` expressions provided in the `SELECT` statement.

[#lbl-rtnd-res]
== Returned Results
xref:android:query-resultsets.adoc#lbl-rtn-all[]
| xref:android:query-resultsets.adoc#lbl-rtn-id[]
| xref:android:query-resultsets.adoc#lbl-rtn-specific[]

The types of SelectResult formats you may encounter include those generated by :

* `QueryBuilder.select(SelectResult.all())` -- xref:android:query-resultsets.adoc#lbl-rtn-all[Using All]
* `QueryBuilder.select(SelectResult.expression(Meta.id))` -- xref:android:query-resultsets.adoc#lbl-rtn-id[Using Doc Id] Metadata such as the `_id`
* `QueryBuilder.select(SelectResult.property("myProp"))` -- xref:android:query-resultsets.adoc#lbl-rtn-specific[Using Specific Properties]


[#lbl-rtn-all]
=== Return All Document Properties
The SelectResult returned by `SelectResult.all()` is a dictionary object, with the database name as the key and the document properties as an array of key-value pairs

--
.Returning All Properties
[#ex-result-id]
====
[source, json, subs="+attributes, +macros", role="no-callouts"]
----

[
  {
    "travel-sample": { // <.>
      "callsign": "MILE-AIR",
      "country": "United States",
      "iata": "Q5",
      "icao": "MLA",
      "id": 10,
      "name": "40-Mile Air",
      "type": "airline"
    }
  },
  {
    "travel-sample": { // <.>
      "callsign": "ALASKAN-AIR",
      "country": "United States",
      "iata": "AA",
      "icao": "AAA",
      "id": 10,
      "name": "Alaskan Airways",
      "type": "airline"
    }
  }
]


----
====
--


[#lbl-rtn-id]
=== Return Document Id Only
The SelectResult returned by queries using a SelectResult expression of the form `SelectResult.expression(Meta.id)` comprises a dictionary object with `ID` as the key and the ID value as the value.

--
.Returning Meta Properties -- Document ID
[#ex-result-id]
====
[source, json, subs="+attributes, +macros"]
----

[
  {
    "id": "hotel123"
  },
  {
    "id": "hotel456"
  },
]

----
====
--


[#lbl-rtn-specific]
=== Return Specific Properties Only
The SelectResult returned by queries using one or more SelectResult expressions of the form `SelectResult.expression(property("name")) )` comprises a key-value pair for each SelectResult expression in the query.
The key being the property name.

--
.Returning Specific Properties
[#ex-result-props]
====
[source, json, subs="+attributes, +macros", role="no-callouts"]
----

[
  { // <.>
    "id": "hotel123",
    "type": "hotel",
    "name": "Hotel Ghia"
  },
  { // <.>
    "id": "hotel456",
    "type": "hotel",
    "name": "Hotel Deluxe",
  }
]

----
====
--

[#lbl-process-resultset]
== Processing Results
xref:android:query-resultsets.adoc#lbl-acc-all[]
| xref:android:query-resultsets.adoc#lbl-acc-id[]
| xref:android:query-resultsets.adoc#lbl-acc-specific[]

To retrieve the results of your query,  you need to execute it using `Query.execute`.

The output from the execution is an array, with each array element representing the data from a document that matched your search criteria.

To unpack the results you need to iterate through this array.
Alternatively, you can convert the result to a JSON string -- see:


[#lbl-acc-all]
=== Access Document Properties - All Properties
Here we look at how to access document properties when you have used SelectResult.all.

In this case each array element is a dictionary structure with the database name as its key.
The properties are presented in the value as an array of key-value pairs (property name/property value).

You access the retrieved document properties by converting each row's value, in turn, to a dictionary -- as shown in xref:android:query-resultsets.adoc#ex-acc-all[].

[#ex-acc-all]
.Access All Properties


[#ex-acc-all]
====

[tabs]
=====


Kotlin::
+
--

[source, Kotlin]
----
include::android:example$codesnippet_collection.kt[tags="query-access-all", indent=0]
----

--

Java::
+
--
[source, Java]
----
include::android:example$codesnippet_collection.java[tags="query-access-all", indent=0]
----
--

=====


====

<.> Here we get the dictionary of document properties using the database name as the key.
You can add this dictionary to an array of returned matches, for processing elsewhere in the app.
<.> Alternatively, you can access the document properties here, by using the property names as keys to the dictionary object.

[#lbl-acc-id]
=== Access Document Properties - ID
Here we look at how to access document properties when you have returned only the document IDs for documents that matched your selection criteria.

This is something you may do when retrieval of the properties directly by the query may consume excessive amounts of memory and-or processing time.

In this case each array element is a dictionary structure where `ID` is the key and the required document ID is the value.

Access the required document properties by retrieving the document from the database using its document ID -- as shown in xref:android:query-resultsets.adoc#ex-acc-id[].

[#ex-acc-id]
.Access by ID


[#ex-acc-id]
====

[tabs]
=====


Kotlin::
+
--

[source, Kotlin]
----
include::android:example$codesnippet_collection.kt[tags="query-access-id", indent=0]
----

--

Java::
+
--
[source, Java]
----
include::android:example$codesnippet_collection.java[tags="query-access-id", indent=0]
----
--

=====


====

<.> Extract the Id value from the dictionary and use it to get the document from the database


[#lbl-acc-specific]
=== Access Document Properties - Selected Properties
Here we look at how to access properties when you have used SelectResult to get a specific subset of properties.

In this case each array element is an array of key value pairs (property name/property value).

Access the retrieved properties by converting each row into a dictionary -- as shown in xref:android:query-resultsets.adoc#ex-acc-specific[].

[#ex-acc-specific]


[#ex-acc-specific]
====

[tabs]
=====


Kotlin::
+
--

[source, Kotlin]
----
include::android:example$codesnippet_collection.kt[tags="query-access-props", indent=0]
----

--

Java::
+
--
[source, Java]
----
include::android:example$codesnippet_collection.java[tags="query-access-props", indent=0]
----
--

=====


====


[#json-result-sets]
== JSON Result Sets

[#ex-json]
.Using JSON Results


[#ex-json]
====

Use https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-android}{empty}/couchbase-lite-android/com/couchbase/lite/Result.html#toJSON--[Result.toJSON()] to transform your result string into a JSON string, which can easily be serialized or used as required in your application. See xref:android:query-resultsets.adoc#ex-json[] for a working example.
[tabs]
=====


Kotlin::
+
--

[source, Kotlin]
----
include::android:example$codesnippet_collection.kt[tags="query-access-json", indent=0]
----

--

Java::
+
--
[source, Java]
----
include::android:example$codesnippet_collection.java[tags="query-access-json", indent=0]
----
--

=====


====


.JSON String Format
[#ex-json-format]
If your query selects ALL then the JSON format will be:

[source, JSON]
----
{
  database-name: {
    key1: "value1",
    keyx: "valuex"
  }
}
----

If your query selects a sub-set of available properties then the JSON format will be:

[source, JSON]
----
{
  key1: "value1",
  keyx: "valuex"
}
----


[#related-content]
== Related Content
++++
<div class="card-row three-column-row">
++++

[.column]
====== {empty}
.How to . . .
* xref:android:gs-prereqs.adoc[Prerequisites]
* xref:android:gs-install.adoc[Install]
* xref:android:gs-build.adoc[Build and Run]


.

[.column]
====== {empty}
.Learn more . . .
* xref:android:database.adoc[Databases]
* xref:android:document.adoc[Documents]
* xref:android:blob.adoc[Blobs]
* xref:android:replication.adoc[Remote Sync Gateway]
* xref:android:conflict.adoc[Handling Data Conflicts]

.


[.column]
====== {empty}
.Dive Deeper . . .
https://forums.couchbase.com/c/mobile/14[Mobile Forum] |
https://blog.couchbase.com/[Blog] |
https://docs.couchbase.com/tutorials/[Tutorials]

.


++++
</div>
++++


