[#android:query-resultsets:::]
= Query Resultsets
:page-role:
:description: How to use Couchbase Lite Query's Result Sets
:keywords: query, sql, n1ql, fuzzy-matching


[abstract]
--
Description -- _{description}_ +
Related Content -- xref:android:querybuilder.adoc[QueryBuilder] |  xref:android:query-n1ql-mobile.adoc[{sqlpp} for Mobile] |  xref:android:querybuilder.adoc#lbl-predquery[Predictive Queries] | xref:android:query-live.adoc[Live Queries] | xref:android:indexing.adoc[Indexing]
--


[#android:query-resultsets:::query-execution]
== Query Execution
The execution of a Couchbase Lite for Android's database query returns an array of results, a result set.

Each row of the result set represents the data returned from a document that met the conditions defined by the `WHERE` statement of your query.
The composition of each row is determined by the `SelectResult` expressions provided in the `SELECT` statement.

[#android:query-resultsets:::lbl-rtnd-res]
== Returned Results
<<android:query-resultsets:::lbl-rtn-all>>
| <<android:query-resultsets:::lbl-rtn-id>>
| <<android:query-resultsets:::lbl-rtn-specific>>

The types of SelectResult formats you may encounter include those generated by :

* `QueryBuilder.select(SelectResult.all())` -- <<android:query-resultsets:::lbl-rtn-all,Using All>>
* `QueryBuilder.select(SelectResult.expression(Meta.id))` -- <<android:query-resultsets:::lbl-rtn-id,Using Doc Id>> Metadata such as the `_id`
* `QueryBuilder.select(SelectResult.property("myProp"))` -- <<android:query-resultsets:::lbl-rtn-specific,Using Specific Properties>>


[#android:query-resultsets:::lbl-rtn-all]
=== Return All Document Properties
The SelectResult returned by `SelectResult.all()` is a dictionary object, with the database name as the key and the document properties as an array of key-value pairs

--
.Returning All Properties
[#android:query-resultsets:::ex-result-id]
====
[pass:q,a[source, json, subs="+attributes, +macros"], role="no-callouts"]
----

[
  {
    "travel-sample": { // <.>
      "callsign": "MILE-AIR",
      "country": "United States",
      "iata": "Q5",
      "icao": "MLA",
      "id": 10,
      "name": "40-Mile Air",
      "type": "airline"
    }
  },
  {
    "travel-sample": { // <.>
      "callsign": "ALASKAN-AIR",
      "country": "United States",
      "iata": "AA",
      "icao": "AAA",
      "id": 10,
      "name": "Alaskan Airways",
      "type": "airline"
    }
  }
]


----
====
--


[#android:query-resultsets:::lbl-rtn-id]
=== Return Document Id Only
The SelectResult returned by queries using a SelectResult expression of the form `SelectResult.expression(Meta.id)` comprises a dictionary object with `ID` as the key and the ID value as the value.

--
.Returning Meta Properties -- Document ID
[#android:query-resultsets:::ex-result-id]
====
[pass:q,a[source, json, subs="+attributes, +macros"]]
----

[
  {
    "id": "hotel123"
  },
  {
    "id": "hotel456"
  },
]

----
====
--


[#android:query-resultsets:::lbl-rtn-specific]
=== Return Specific Properties Only
The SelectResult returned by queries using one or more SelectResult expressions of the form `SelectResult.expression(property("name")) )` comprises a key-value pair for each SelectResult expression in the query.
The key being the property name.

--
.Returning Specific Properties
[#android:query-resultsets:::ex-result-props]
====
[pass:q,a[source, json, subs="+attributes, +macros"], role="no-callouts"]
----

[
  { // <.>
    "id": "hotel123",
    "type": "hotel",
    "name": "Hotel Ghia"
  },
  { // <.>
    "id": "hotel456",
    "type": "hotel",
    "name": "Hotel Deluxe",
  }
]

----
====
--

[#android:query-resultsets:::lbl-process-resultset]
== Processing Results
<<android:query-resultsets:::lbl-acc-all>>
| <<android:query-resultsets:::lbl-acc-id>>
| <<android:query-resultsets:::lbl-acc-specific>>

To retrieve the results of your query,  you need to execute it using `Query.execute`.

The output from the execution is an array, with each array element representing the data from a document that matched your search criteria.

To unpack the results you need to iterate through this array.
Alternatively, you can convert the result to a JSON string -- see:


[#android:query-resultsets:::lbl-acc-all]
=== Access Document Properties - All Properties
Here we look at how to access document properties when you have used SelectResult.all.

In this case each array element is a dictionary structure with the database name as its key.
The properties are presented in the value as an array of key-value pairs (property name/property value).

You access the retrieved document properties by converting each row's value, in turn, to a dictionary -- as shown in <<android:query-resultsets:::ex-acc-all>>.

[#ex-acc-all]
.Access All Properties


[#android:query-resultsets:::ex-acc-all]
====

[tabs]
=====


Kotlin::
+
--

// Show Main Snippet
// include::android:example$codesnippet_collection.kt[tags="query-access-all", indent=0]
[source, Kotlin]
----
val hotels = mutableMapOf<String, Hotel>()
listQuery.execute().use { rs ->
    rs.allResults().forEach {
        // get the k-v pairs from the 'hotel' key's value into a dictionary
        val thisDocsProps = it.getDictionary(0) // <.>
        val thisDocsId = thisDocsProps!!.getString("id")
        val thisDocsName = thisDocsProps.getString("name")
        val thisDocsType = thisDocsProps.getString("type")
        val thisDocsCity = thisDocsProps.getString("city")

        // Alternatively, access results value dictionary directly
        val id = it.getDictionary(0)?.getString("id").toString() // <.>
        hotels[id] = Hotel(
            id,
            it.getDictionary(0)?.getString("type"),
            it.getDictionary(0)?.getString("name"),
            it.getDictionary(0)?.getString("city"),
            it.getDictionary(0)?.getString("country"),
            it.getDictionary(0)?.getString("description")
        )
    }
}
----

--
// Show Optional Alternate Snippet
// include::android:example$codesnippet_collection.java[tags="query-access-all", indent=0]

Java::
+
--
[source, Java]
----
Map<String, Hotel> hotels = new HashMap<>();
try (ResultSet resultSet = listQuery.execute()) {
    for (Result result: resultSet) {
        // get the k-v pairs from the 'hotel' key's value into a dictionary
        Dictionary docsProp = result.getDictionary(0); // <.>
        String docsId = docsProp.getString("id");
        String docsName = docsProp.getString("Name");
        String docsType = docsProp.getString("Type");
        String docsCity = docsProp.getString("City");

        // Alternatively, access results value dictionary directly
        final Hotel hotel = new Hotel();
        hotel.setId(result.getDictionary(0).getString("id")); // <.>
        hotel.setType(result.getDictionary(0).getString("Type"));
        hotel.setName(result.getDictionary(0).getString("Name"));
        hotel.setCity(result.getDictionary(0).getString("City"));
        hotel.setCountry(result.getDictionary(0).getString("Country"));
        hotel.setDescription(result.getDictionary(0).getString("Description"));
        hotels.put(hotel.getId(), hotel);
    }
}
----
--

=====


====

<.> Here we get the dictionary of document properties using the database name as the key.
You can add this dictionary to an array of returned matches, for processing elsewhere in the app.
<.> Alternatively, you can access the document properties here, by using the property names as keys to the dictionary object.

[#android:query-resultsets:::lbl-acc-id]
=== Access Document Properties - ID
Here we look at how to access document properties when you have returned only the document IDs for documents that matched your selection criteria.

This is something you may do when retrieval of the properties directly by the query may consume excessive amounts of memory and-or processing time.

In this case each array element is a dictionary structure where `ID` is the key and the required document ID is the value.

Access the required document properties by retrieving the document from the database using its document ID -- as shown in <<android:query-resultsets:::ex-acc-id>>.

[#ex-acc-id]
.Access by ID


[#android:query-resultsets:::ex-acc-id]
====

[tabs]
=====


Kotlin::
+
--

// Show Main Snippet
// include::android:example$codesnippet_collection.kt[tags="query-access-id", indent=0]
[source, Kotlin]
----
query.execute().use { rs ->
    rs.allResults().forEach {
        log("hotel id ->${it.getString("hotelId")}")
    }
}
----

--
// Show Optional Alternate Snippet
// include::android:example$codesnippet_collection.java[tags="query-access-id", indent=0]

Java::
+
--
[source, Java]
----
try (ResultSet rs = listQuery.execute()) {
    for (Result result: rs.allResults()) {

        // get the ID form the result's k-v pair array
        String thisDocsId = result.getString("metaID"); // <.>

        // Get document from DB using retrieved ID
        Document thisDoc = collection.getDocument(thisDocsId);

        // Process document as required
        String thisDocsName = thisDoc.getString("Name");
    }
}
----
--

=====


====

<.> Extract the Id value from the dictionary and use it to get the document from the database


[#android:query-resultsets:::lbl-acc-specific]
=== Access Document Properties - Selected Properties
Here we look at how to access properties when you have used SelectResult to get a specific subset of properties.

In this case each array element is an array of key value pairs (property name/property value).

Access the retrieved properties by converting each row into a dictionary -- as shown in <<android:query-resultsets:::ex-acc-specific>>.

[#ex-acc-specific]


[#android:query-resultsets:::ex-acc-specific]
====

[tabs]
=====


Kotlin::
+
--

// Show Main Snippet
// include::android:example$codesnippet_collection.kt[tags="query-access-props", indent=0]
[source, Kotlin]
----
query.execute().use { rs ->
    rs.allResults().forEach {
        log("Hotel name -> ${it.getString("name")}, in ${it.getString("country")}")
    }
}
----

--
// Show Optional Alternate Snippet
// include::android:example$codesnippet_collection.java[tags="query-access-props", indent=0]

Java::
+
--
[source, Java]
----
HashMap<String, Hotel> hotels = new HashMap<>();
try (ResultSet resultSet = listQuery.execute()) {
    for (Result result: resultSet) {

        // get data direct from result k-v pairs
        final Hotel hotel = new Hotel();
        hotel.setId(result.getString("id"));
        hotel.setType(result.getString("Type"));
        hotel.setName(result.getString("Name"));
        hotel.setCity(result.getString("City"));

        // Store created hotel object in a hashmap of hotels
        hotels.put(hotel.getId(), hotel);

        // Get result k-v pairs into a 'dictionary' object
        Map<String, Object> thisDocsProps = result.toMap();
        String docId =
            thisDocsProps.getOrDefault("id", null).toString();
        String docName =
            thisDocsProps.getOrDefault("Name", null).toString();
        String docType =
            thisDocsProps.getOrDefault("Type", null).toString();
        String docCity =
            thisDocsProps.getOrDefault("City", null).toString();
    }
}
----
--

=====


====


[#android:query-resultsets:::json-result-sets]
== JSON Result Sets

[#ex-json]
.Using JSON Results


[#android:query-resultsets:::ex-json]
====

Use https://docs.couchbase.com/mobile/{major}.{minor}.{maintenance-android}{empty}/couchbase-lite-android/com/couchbase/lite/Result.html#toJSON--[Result.toJSON()] to transform your result string into a JSON string, which can easily be serialized or used as required in your application. See <<android:query-resultsets:::ex-json>> for a working example.
[tabs]
=====


Kotlin::
+
--

// Show Main Snippet
// include::android:example$codesnippet_collection.kt[tags="query-access-json", indent=0]
[source, Kotlin]
----
// Uses Jackson JSON processor
val mapper = ObjectMapper()
val hotels = mutableListOf<Hotel>()

listQuery.execute().use { rs ->
    rs.forEach {

        // Get result as JSON string
        val json = it.toJSON() // <.>

        // Get Hashmap from JSON string
        val dictFromJSONstring = mapper.readValue(json, HashMap::class.java) // <.>

        // Use created hashmap
        val hotelId = dictFromJSONstring["id"].toString() //
        val hotelType = dictFromJSONstring["type"].toString()
        val hotelname = dictFromJSONstring["name"].toString()

        // Get custom object from JSON string
        val thisHotel = mapper.readValue(json, Hotel::class.java) // <.>
        hotels.add(thisHotel)
    }
}
----

--
// Show Optional Alternate Snippet
// include::android:example$codesnippet_collection.java[tags="query-access-json", indent=0]

Java::
+
--
[source, Java]
----
// Uses Jackson JSON processor
ObjectMapper mapper = new ObjectMapper();
List<Hotel> hotels = new ArrayList<>();

try (ResultSet rs = listQuery.execute()) {
    for (Result result: rs) {
        String json = result.toJSON();
        Map<String, String> dictFromJSONstring = mapper.readValue(json, HashMap.class);

        String hotelId = dictFromJSONstring.get("id");
        String hotelType = dictFromJSONstring.get("type");
        String hotelname = dictFromJSONstring.get("name");

        // Get custom object from JSON string
        Hotel thisHotel = mapper.readValue(json, Hotel.class);
        hotels.add(thisHotel);
    }
}
----
--

=====


====


.JSON String Format
[#android:query-resultsets:::ex-json-format]
If your query selects ALL then the JSON format will be:

[source, JSON]
----
{
  database-name: {
    key1: "value1",
    keyx: "valuex"
  }
}
----

If your query selects a sub-set of available properties then the JSON format will be:

[source, JSON]
----
{
  key1: "value1",
  keyx: "valuex"
}
----


[#android:query-resultsets:::related-content]
== Related Content
++++
<div class="card-row three-column-row">
++++

[.column]
====== {empty}
.How to . . .
* xref:android:gs-prereqs.adoc[Prerequisites]
* xref:android:gs-install.adoc[Install]
* xref:android:gs-build.adoc[Build and Run]


.

[.column#android:query-resultsets:::-2]
====== {empty}
.Learn more . . .
* xref:android:database.adoc[Databases]
* xref:android:document.adoc[Documents]
* xref:android:blob.adoc[Blobs]
* xref:android:replication.adoc[Remote Sync Gateway]
* xref:android:conflict.adoc[Handling Data Conflicts]

.


[.column#android:query-resultsets:::-3]
====== {empty}
.Dive Deeper . . .
https://forums.couchbase.com/c/mobile/14[Mobile Forum] |
https://blog.couchbase.com/[Blog] |
https://docs.couchbase.com/tutorials/[Tutorials]

.


++++
</div>
++++


