
= Live Query -- Working with Queries
:page-aliases: learn/java-android-query-live.adoc
:page-role:
:description: Couchbase Lite database data querying concepts -- live queries


:source-language: Java


:source-language: Kotlin


[abstract]
--
Description -- _{description}_ +
Related Content -- xref:android:querybuilder.adoc#lbl-predquery[Predictive Queries] | xref:android:indexing.adoc[Indexing] | xref:android:querybuilder.adoc[QueryBuilder]
--


[#activating-a-live-query]
== Activating a Live Query


A live query is a query that, once activated, remains active and monitors the database for changes; refreshing the result set whenever a change occurs.
As such, it is a great way to build reactive user interfaces -- especially table/list views -- that keep themselves up to date.

*So, a simple use case may be:* A replicator running and pulling new data from a server, whilst a live-query-driven UI automatically updates to show the data without the user having to manually refresh.
This helps your app feel quick and responsive.

To activate a LiveQuery just add a change listener to the query statement.
It will be immediately active.
When a change is detected the query automatically runs, and posts the new query result to any observers (change listeners).


.Starting a Live Query
[#ex-qry-start]


[#ex-qry-start]
====

[tabs]
=====


Kotlin::
+
--

[source, Kotlin]
----
include::android:example$codesnippet_collection.kt[tags="live-query", indent=0]
----

--

Java::
+
--
[source, Java]
----
include::android:example$codesnippet_collection.java[tags="live-query", indent=0]
----
--

=====


====

<.> Build the query statements
<.> Activate the _live_ query by attaching a listener.
Save the token in order to detach the listener and stop the query later -- se xref:android:query-live.adoc#ex-qry-stop[]


.Stop a LIve Query
[#ex-qry-stop]


[#ex-qry-stop]
====

[tabs]
=====


Kotlin::
+
--

[source, Kotlin]
----
include::android:example$codesnippet_collection.kt[tags="stop-live-query", indent=0]
----

--

Java::
+
--
[source, Java]
----
include::android:example$codesnippet_collection.java[tags="stop-live-query", indent=0]
----
--

=====


====

<.> Here we use the change lister token from xref:android:query-live.adoc#ex-qry-start[] to remove the listener.
Doing so stops the live query.


[#using-kotlin-flows-and-livedata]
== Using Kotlin Flows and LiveData
Kotlin developers also have the option of using Flows and Live Data to feed query changes to the UI.

Define a live query as a Flow returning a LiveData object and activate an Observer in the View onCreate() function.

[source, Kotlin, subs="attributes+"]
----
include::example$kotlin_snippets/app/src/main/kotlin/com/couchbase/code_snippets/FlowExamples.kt[tag="flow-as-query-change-listener"]
----


[#related-content]
== Related Content
++++
<div class="card-row three-column-row">
++++

[.column]
====== {empty}
.How to . . .
* xref:android:querybuilder.adoc[QueryBuilder]
* xref:android:query-n1ql-mobile.adoc[{sqlpp} for Mobile]
* xref:android:query-live.adoc[Live Queries]
* xref:android:fts.adoc[Full Text Search]


.

[.column]
====== {empty}
.Learn more . . .
* xref:android:query-n1ql-mobile-querybuilder-diffs.adoc[{sqlpp} Mobile - Querybuilder  Differences]
* xref:android:query-n1ql-mobile-server-diffs.adoc[{sqlpp} Mobile - {sqlpp} Server Differences]
* xref:android:query-resultsets.adoc[Query Resultsets]
* xref:android:query-troubleshooting.adoc[Query Troubleshooting]
* xref:android:query-live.adoc[Live Queries]

* xref:android:database.adoc[Databases]
* xref:android:document.adoc[Documents]
* xref:android:blob.adoc[Blobs]

.


[.column]
====== {empty}
.Dive Deeper . . .
https://forums.couchbase.com/c/mobile/14[Mobile Forum] |
https://blog.couchbase.com/[Blog] |
https://docs.couchbase.com/tutorials/[Tutorials]

.


++++
</div>
++++


