= Supported Operating System Versions
:page-aliases: product/java-android-supported-os.adoc
:page-role: -toc
:description: Couchbase Lite on Android -- the OS and SDK versions on which this framework is supported

:source-language: Java
:source-language: Kotlin

[abstract]
--
Description -- _{description}_ +
Related Content -- xref:cbl-whatsnew.adoc[What's New]  |  xref:android:releasenotes.adoc[Release Notes] | xref:android:compatibility.adoc[Compatibility]
--

[#officially-supported-versions]
== Officially Supported Versions

[IMPORTANT]
--
The requirements listed below are for the *Java/Kotlin SDK* on Android.

If you're developing with the *C/{cpp} SDK* on Android, the minimum API Level is *24*.
For C/{cpp} SDK requirements, see xref:c:supported-os.adoc#android[Couchbase Lite for C - Android Requirements].
--

The operating systems listed in xref:android:supported-os.adoc#supported-os-versions[] are certified Android versions.
Couchbase does not test against, nor guarantee support for, uncertified Android versions such as versions built from source.

.Supported versions
[#supported-os-versions]
[%autowidth.stretch]
|===
|Platform |Runtime architectures |Minimum API Level

|Android
|armeabi-v7a
|22

|Android
|arm64-v8a
|22

|Android
|x86
|22

|Android
|x86_64
|22
|===

[#bluetooth-transport-requirements]
== Bluetooth Transport Requirements

[NOTE]
--
Bluetooth Low Energy (BLE) transport for the Multipeer Replicator requires *Android API 29 (Android 10) or later*, due to the availability of BLE L2CAP support on that API level.

Devices running API 22--28 can still use Couchbase Lite 3.4 with all non-Bluetooth features, including Wi-Fi-based Multipeer replication.
If your application targets API 22--28, do not include `.bluetooth` in your `MultipeerReplicatorConfiguration.transports` set.
--

[cols="1,^1", options="header"]
|===
|Feature |Minimum API Level

|Couchbase Lite core
|22

|Multipeer Replicator (Wi-Fi)
|22

|Multipeer Replicator (Bluetooth LE)
|29
|===