= Upgrade
:page-aliases: advance/java-android-dep-upgrade.adoc, dep-upgrade.adoc
:page-role:


:source-language: Java


:source-language: Kotlin


[IMPORTANT]
--
On upgrading from a 2.x release, all Couchbase Lite databases will be automatically re-indexed on initial database open. +
This can result in a delay before the database is usable.
--

=== Vector Search Extension

Couchbase Lite 3.4.0 is compatible with Vector Search Extension 2.0.0 only.
If your application uses Vector Search, update the Vector Search Extension to 2.0.0 when upgrading to Couchbase Lite 3.4.0.

[#3-4-0-upgrade]
== {major}.{minor}.{base}{empty} Upgrade

Couchbase Lite {major}.{minor} is a non-breaking upgrade from 3.3.
Update your Couchbase Lite dependency to {major}.{minor} -- no API or configuration changes are required.
Existing `MultipeerReplicatorConfiguration` setups continue to work without modification.
The default transport remains Wi-Fi only.

[WARNING]
--
When upgrading from Couchbase Lite 3.4.0 to the 4.x release line, upgrade directly to 4.1.0 or later.
Couchbase Lite 4.x versions below 4.1.0 do not include all APIs added in 3.4.0 (Multipeer Replicator with Bluetooth and Auto Switching, Replication Correlation ID, Kotlin Serialization, and on C, the C++ API).
--

=== Enabling Bluetooth Transport (Optional)

By default, Multipeer Replication uses Wi-Fi only.
You can configure the `transports` property on `MultipeerReplicatorConfiguration` to enable Bluetooth Low Energy (BLE) transport alongside Wi-Fi.
This enables automatic transport switching: the replicator uses Wi-Fi when available and falls back to BLE when Wi-Fi is unavailable.
For more detail, see xref:android:p2psync-multipeer.adoc#automatic-transport-switching[Automatic Transport Switching].

==== Auto-Switching (Wi-Fi and BLE)

Setting both transports enables auto-switching.
When both transports can reach a peer, the replicator uses Wi-Fi.
It falls back to BLE when Wi-Fi is unavailable.

[source, Kotlin]
----
val config = MultipeerReplicatorConfiguration(
    peerGroupID = "myGroup",
    identity = identity,
    authenticator = authenticator,
    collections = collections)
config.transports = EnumSet.of(MultipeerTransport.WIFI, MultipeerTransport.BLUETOOTH)
----

[source, Java]
----
MultipeerReplicatorConfiguration config = new MultipeerReplicatorConfiguration(
    "myGroup",
    identity,
    authenticator,
    collections);
config.setTransports(EnumSet.of(MultipeerTransport.WIFI, MultipeerTransport.BLUETOOTH));
----

==== BLE Only

To restrict replication to BLE exclusively, omit `MultipeerTransport.WIFI`.

[source, Kotlin]
----
val config = MultipeerReplicatorConfiguration(
    peerGroupID = "myGroup",
    identity = identity,
    authenticator = authenticator,
    collections = collections)
config.transports = EnumSet.of(MultipeerTransport.BLUETOOTH)
----

[source, Java]
----
MultipeerReplicatorConfiguration config = new MultipeerReplicatorConfiguration(
    "myGroup",
    identity,
    authenticator,
    collections);
config.setTransports(EnumSet.of(MultipeerTransport.BLUETOOTH));
----

NOTE: Bluetooth transport requires Android API 29 or later.

[#api-changes]
=== API Changes

This content introduces the changes made to the Couchbase{nbsp}Lite for Android API for release {major}.{minor}.{base}{empty}.

[#removed]
==== Removed

[#resetcheckpoint]
===== ResetCheckpoint

The method https://docs.couchbase.com/mobile/2.8.0/couchbase-lite-android/com/couchbase/lite/AbstractReplicator.html#resetCheckpoint--[Replicator.resetCheckpoint()] has been removed. +
Instead, use https://docs.couchbase.com/mobile/{major}.{minor}.{base}{empty}/couchbase-lite-android/com/couchbase/lite/AbstractReplicator.html#start-boolean-[Replicator.resetCheckpoint(boolean reset)].

.Before
[source, java]
----
replicator.resetCheckpoint()
replicator.start()
----

.After
[source, java, subs="attributes+, macros+"]
----
replicator.start(true)
----

[#database-setloglevel]
===== Database.setLogLevel

The method https://docs.couchbase.com/mobile/2.8.0/couchbase-lite-android/com/couchbase/lite/Database.html#setLogLevel-com.couchbase.lite.LogDomain-com.couchbase.lite.LogLevel-[Database.setLogLevel()]
has been removed. +
Instead:

. Set the logging levels for loggers, individually
. Set the domains to be logged by the console logger, explicitly.

.Before
[source, java, subs="attributes+, macros+"]
----
Database.setLogLevel(LogDomain.ALL, LogLevel.VERBOSE)
----

.After
[source, java, subs="attributes+, macros+"]
----
Database.log.getConsole().setDomains(LogDomain.ALL_DOMAINS)
Database.log.getConsole().setLevel(LogLevel.VERBOSE)
Database.log.getFile().setDomains(LogLevel.DEBUG)
----

[#database-compact]
===== Database.compact
The https://docs.couchbase.com/mobile/2.8.0/couchbase-lite-android/com/couchbase/lite/Database.html#compact--[Database.compact()] method has been removed. +
It is replaced by the new https://docs.couchbase.com/mobile/{major}.{minor}.{base}{empty}/couchbase-lite-android/com/couchbase/lite/Database.html#performMaintenance-com.couchbase.lite.MaintenanceType-[Database.performMaintenance(MaintenanceType)] method, and the maintenance operations represented in the enum https://docs.couchbase.com/mobile/{major}.{minor}.{base}{empty}/couchbase-lite-android/com/couchbase/lite/MaintenanceType.html[MaintenanceType]

.Before
[source, java, subs="attributes+, macros+"]
----
try testdb.compact()
----

.After
[source, java, subs="attributes+, macros+"]
----
testdb.performMaintenance(MaintenanceType.COMPACT)
----

[#lbl-db-upgrades]
== 1.x Databases Upgrades to 2.x

Databases created using Couchbase Lite 1.2 or later can still be used with Couchbase Lite 2.x; but will be automatically updated to the current 2.x version.
This feature is only available for the default storage type (i.e., not a ForestDB database).

[#encrypted-databases]
=== Encrypted Databases
The automatic migration feature does not support encrypted databases.
So if the 1.x database is encrypted you will first need to disable encryption using the Couchbase Lite 1.x API (see the https://docs-archive.couchbase.com/couchbase-lite/1.4/Kotlin.html#database-encryption[1.x Database Guide]).

.Upgrading Encrypted Databases
****
. Disable encryption using the Couchbase Lite 1.x framework (see https://docs-archive.couchbase.com/couchbase-lite/1.4/android.html#database-encryption[1.x encryption guide])
. Open the database file with encryption enabled using the Couchbase Lite 2.x framework.
****

Since it is not possible to package Couchbase Lite 1.x and Couchbase Lite 2.x in the same application this upgrade path would require two successive upgrades.

If you are using Sync Gateway to synchronize the database content, it may be preferable to run a pull replication from a new 2.x database with encryption enabled and delete the 1.x local database.

[#downgrading-couchbase-lite]
== Downgrading Couchbase Lite

[#downgrading-between-major-releases]
=== Downgrading Between Major Releases

*No Downgrade Support* - Downgrades between major versions of Couchbase Lite (CBL) are not supported.
Once you upgrade to a new major version, downgrading to a previous major version may lead to incompatibility issues.

[#downgrading-between-minor-releases]
=== Downgrading Between Minor Releases

*Conditional Downgrade Support* - Downgrade support for minor releases is considered on a case-by-case basis.
The release notes for each minor version will clarify whether downgrades are supported.

[#downgrading-between-patch-releases]
=== Downgrading Between Patch Releases

*Full Downgrade Support* - Downgrades between patch releases are supported.
Users can safely downgrade between different patch versions within the same minor release.

[#related-content]
== Related Content
++++
<div class="card-row three-column-row">
++++

[.column]
=== {empty}
.How to . . .
* xref:android:gs-prereqs.adoc[Prerequisites]
* xref:android:gs-install.adoc[Install]
* xref:android:gs-build.adoc[Build and Run]

.

[.column]
=== {empty}
.Learn more . . .
* xref:android:database.adoc[Databases]
* xref:android:document.adoc[Documents]
* xref:android:blob.adoc[Blobs]
* xref:android:replication.adoc[Remote Sync Gateway]
* xref:android:conflict.adoc[Handling Data Conflicts]

.

[.column]
=== {empty}
.Dive Deeper . . .
https://forums.couchbase.com/c/mobile/14[Mobile Forum] |
https://blog.couchbase.com/[Blog] |
https://docs.couchbase.com/tutorials/[Tutorials]

.

++++
</div>
++++