:docname: upgrade
:page-module: android
:page-relative-src-path: upgrade.adoc
:page-origin-url: https://github.com/couchbase/docs-couchbase-lite.git
:page-origin-start-path:
:page-origin-refname: antora-assembler-simplification
:page-origin-reftype: branch
:page-origin-refhash: (worktree)
[#android:upgrade:::]
= Upgrade
:page-aliases: advance/java-android-dep-upgrade.adoc, dep-upgrade.adoc
:page-role:


[IMPORTANT]
--
On upgrading from a 2.x release, all Couchbase Lite databases will be automatically re-indexed on initial database open. +
This can result in a delay before the database is usable.
--


[#android:upgrade:::3-2-0-upgrade]
== {major}.{minor}.{base}{empty} Upgrade

NOTE: This upgrade requires all 2.x databases be reindexed on initial open.

The action will take place automatically and can lead to some delay in the database becoming available for use in your application.

In addition, if you are syncing with a {major}.{minor}.{base}{empty} Sync Gateway, you should be aware of the significant configuration enhancements introduced and their impact.
This is a one-way conversion.

[#android:upgrade:::api-changes]
=== API Changes


This content introduces the changes made to the pass:q,a[pass:q,a[Couchbase{nbsp}Lite]] for Android API for release {major}.{minor}.{base}{empty}.


[#android:upgrade:::removed]
==== Removed


[#android:upgrade:::resetcheckpoint]
===== ResetCheckpoint

The method https://docs.couchbase.com/mobile/2.8.0/couchbase-lite-android/com/couchbase/lite/AbstractReplicator.html#resetCheckpoint--[Replicator.resetCheckpoint()] has been removed. +
Instead, use https://docs.couchbase.com/mobile/{major}.{minor}.{base}{empty}/couchbase-lite-android/com/couchbase/lite/AbstractReplicator.html#start-boolean-[Replicator.resetCheckpoint(boolean reset)].

.Before
[source, java]
----
replicator.resetCheckpoint()
replicator.start()
----

.After
[pass:q,a[source, java, subs="attributes+, macros+"]]
----
replicator.start(true)
----

[#android:upgrade:::database-setloglevel]
===== Database.setLogLevel

The method https://docs.couchbase.com/mobile/2.8.0/couchbase-lite-android/com/couchbase/lite/Database.html#setLogLevel-com.couchbase.lite.LogDomain-com.couchbase.lite.LogLevel-[Database.setLogLevel()]
has been removed. +
Instead:

. Set the logging levels for loggers, individually
. Set the domains to be logged by the console logger, explicitly.

.Before
[pass:q,a[source, java, subs="attributes+, macros+"]]
----
Database.setLogLevel(LogDomain.ALL, LogLevel.VERBOSE)

----

.After
[pass:q,a[source, java, subs="attributes+, macros+"]]
----
Database.log.getConsole().setDomains(LogDomain.ALL_DOMAINS)
Database.log.getConsole().setLevel(LogLevel.VERBOSE)
Database.log.getFile().setDomains(LogLevel.DEBUG)
----

[#android:upgrade:::database-compact]
===== Database.compact
The https://docs.couchbase.com/mobile/2.8.0/couchbase-lite-android/com/couchbase/lite/Database.html#compact--[Database.compact()] method has been removed. +
It is replaced by the new https://docs.couchbase.com/mobile/{major}.{minor}.{base}{empty}/couchbase-lite-android/com/couchbase/lite/Database.html#performMaintenance-com.couchbase.lite.MaintenanceType-[Database.performMaintenance(MaintenanceType)] method, and the maintenance operations represented in the enum https://docs.couchbase.com/mobile/{major}.{minor}.{base}{empty}/couchbase-lite-android/com/couchbase/lite/MaintenanceType.html[MaintenanceType]

.Before
[pass:q,a[source, java, subs="attributes+, macros+"]]
----
try testdb.compact()

----

.After
[pass:q,a[source, java, subs="attributes+, macros+"]]
----
testdb.performMaintenance(MaintenanceType.COMPACT)
----


[#android:upgrade:::deprecated-in-the-api]
==== Deprecated in the API


[#android:upgrade:::match]
===== MATCH
The class, https://docs.couchbase.com/mobile/2.8.0/couchbase-lite-android/com/couchbase/lite/FullTextExpression.html[FullTextExpression]
has been deprecated. +
Use https://docs.couchbase.com/mobile/{major}.{minor}.{base}{empty}/couchbase-lite-android/com/couchbase/lite/FullTextFunction.html[FullTextFunction] instead.

.Before
[pass:q,a[source, java, subs="attributes+, macros+"]]
----
FullTextExpression index = FullTextExpression.index("indexName")
Query q = QueryBuilder.select([SelectResult.expression(Meta.id)])
  .from(DataSource.database(testdb))
  .where(index.match(queryString))

----

.After
[pass:q,a[source, java, subs="attributes+, macros+"]]
----
Query q = QueryBuilder.select([SelectResult.expression(Meta.id)])
  .from(DataSource.database(testdb))
  .where(FullTextFunction.match("indexName", queryString))

----

[#android:upgrade:::isnullormissingnotnullormissing]
===== isNullOrMissing/notNullOrMissing

The functions https://docs.couchbase.com/mobile/2.8.0/couchbase-lite-android/com/couchbase/lite/Expression.html#isNullOrMissing--[Expression.isNullOrMissing] and https://docs.couchbase.com/mobile/2.8.0/couchbase-lite-android/com/couchbase/lite/Expression.html#notNullOrMissing--[Expression.notNullOrMissing] have been deprecated. +
Use `isNotValued()` and-or `isValued()` instead.

.Before
[pass:q,a[source, java, subs="attributes+, macros+"]]
----
Query q =
  QueryBuilder
    .select([SelectResult.expression(Meta.id)])
    .from(DataSource.database(testdb))
    .where(
      Expression.property("missingProp").isNullOrMissing())

Query q =
  QueryBuilder
    .select([SelectResult.expression(Meta.id)])
    .from(DataSource.database(testdb))
    .where(Expression.property("notMissingProp").notNullOrMissing())

----
.After
[pass:q,a[source, java, subs="attributes+, macros+"]]
----
Query q = QueryBuilder.select([SelectResult.expression(Meta.id)])
  .from(DataSource.database(testdb))
  .where(Expression.property("missingProp").isNotValued())

Query q = QueryBuilder.select([SelectResult.expression(Meta.id)])
  .from(DataSource.database(testdb))
  .where(Expression.property("notMissingProp").isValued())

----

[#android:upgrade:::abstractreplicatorconfiguration]
===== AbstractReplicatorConfiguration

The enum https://docs.couchbase.com/mobile/2.8.0/couchbase-lite-android/com/couchbase/lite/ReplicatorConfiguration.html#setReplicatorType-com.couchbase.lite.AbstractReplicatorConfiguration.ReplicatorType-[AbstractReplicatorConfiguration.ReplicatorType]
and the methods
https://docs.couchbase.com/mobile/2.8.0/couchbase-lite-android/com/couchbase/lite/ReplicatorConfiguration.html#setReplicatorType--[
ReplicatorConfiguration.setReplicatorType]
and
https://docs.couchbase.com/mobile/2.8.0/couchbase-lite-android/com/couchbase/lite/ReplicatorConfiguration.html#getReplicatorType--[
ReplicatorConfiguration.getReplicatorType]
have all been deprecated. +
Instead, use the methods `ReplicatorConfiguration.setType` and `ReplicatorConfiguration.getType`, and the top level enum `ReplicatorType`.

.Before
[pass:q,a[source, java, subs="attributes+, macros+"]]
----
ReplicatorConfiguration config =
  new ReplicatorConfiguration().setReplicatorType(ReplicatorConfiguration.ReplicatorType.PUSH_AND_PULL);
----
.After
[pass:q,a[source, java, subs="attributes+, macros+"]]
----
ReplicatorConfiguration config =
  new ReplicatorConfiguration().setType(ReplicatorType.PUSH_AND_PULL);
----


[#android:upgrade:::moved-in-the-api]
==== Moved in the API


The enum https://docs.couchbase.com/mobile/2.8.0/couchbase-lite-android/com/couchbase/lite/AbstractReplicator.ActivityLevel.html[AbstractReplicator.ActivityLevel] and the classes https://docs.couchbase.com/mobile/2.8.0/couchbase-lite-android/com/couchbase/lite/AbstractReplicator.Progress.html[AbstractReplicator.Progress] and https://docs.couchbase.com/mobile/2.8.0/couchbase-lite-android/com/couchbase/lite/AbstractReplicator.Status.html[AbstractReplicator.Status] have all been moved to be top level definitions. +
They are replaced by these definitions:

* https://docs.couchbase.com/mobile/{major}.{minor}.{base}{empty}/couchbase-lite-android/com/couchbase/lite/ReplicatorActivityLevel.html[ReplicatorActivityLevel]
* https://docs.couchbase.com/mobile/{major}.{minor}.{base}{empty}/couchbase-lite-android/com/couchbase/lite/ReplicatorProgress.html[ReplicatorProgress]
* https://docs.couchbase.com/mobile/{major}.{minor}.{base}{empty}/couchbase-lite-android/com/couchbase/lite/ReplicatorStatus.html[ReplicatorStatus]


.Before
[pass:q,a[source, java, subs="attributes+, macros+"]]
----
ListenerToken token =
  replicator.addChangeListener(
    testSerialExecutor,
    change -> {
      final AbstractReplicator.Status status = change.getStatus()
      if (status.getActivityLevel() == AbstractReplicator.ActivityLevel.BUSY)
      { AbstractReplicator.Progress progress =
          status.getProgress(); Logger.log("Progress: " + progress.completed + "/" progress.total);
      }
    });

----
.After
[pass:q,a[source, java, subs="attributes+, macros+"]]
----
ListenerToken token =
  replicator.addChangeListener(
    testSerialExecutor,
    change -> {
      final ReplicatorStatus status = change.getStatus()
      if (status.getActivityLevel() == ReplicatorActivityLevel.BUSY)
      { ReplicatorProgress progress =
          status.getProgress(); Logger.log("Progress: " + progress.completed + "/" progress.total);
      }
    });

----


[#android:upgrade:::lbl-db-upgrades]
== 1.x Databases Upgrades to 2.x

Databases created using Couchbase Lite 1.2 or later can still be used with Couchbase Lite 2.x; but will be automatically updated to the  current 2.x version.
This feature is only available for the default storage type (i.e., not a ForestDB database).

[#android:upgrade:::encrypted-databases]
=== Encrypted Databases
The automatic migration feature does not support encrypted databases.
So if the 1.x database is encrypted you will first need to disable encryption using the Couchbase Lite 1.x API (see the https://docs-archive.couchbase.com/couchbase-lite/1.4/Kotlin.html#database-encryption[1.x Database Guide]).

Thus, to upgrade an encrypted 1.x database, you should do the following:

.Upgrading Encrypted Databases
****
. Disable encryption using the Couchbase Lite 1.x framework (see https://docs-archive.couchbase.com/couchbase-lite/1.4/android.html#database-encryption[1.x encryption guide])
. Open the database file with encryption enabled using the Couchbase Lite 2.x framework.
****

Since it is not possible to package Couchbase Lite 1.x and Couchbase Lite 2.x in the same application this upgrade path would require two successive upgrades.

If you are using Sync Gateway to synchronize the database content, it may be preferable to run a pull replication from a new 2.x database with encryption enabled and delete the 1.x local database.


[#android:upgrade:::handling-of-existing-conflicts]
=== Handling of Existing Conflicts

If there are existing conflicts in the 1.x database, the automatic upgrade process copies the default winning revision to the new database and does NOT copy any conflicting revisions.

This functionality is related to the way conflicts are now being handled in Couchbase Lite -- see xref:android:conflict.adoc[Handling Data Conflicts].

Optionally, existing conflicts in the 1.x database can be resolved with the https://docs-archive.couchbase.com/couchbase-lite/1.4/Kotlin.html#resolving-conflicts[1.x API] prior to the database being upgraded.

[#android:upgrade:::handling-of-existing-attachments]
=== Handling of Existing Attachments

Attachments persisted in a 1.x database are copied to the new database.
NOTE: The relevant Couchbase Lite API is now called the `Blob` API not the `Attachments` API.

The functionally is identical but the internal schema for attachments has changed.

Blobs are stored anywhere in the document, just like other value types.
Whereas in 1.x they were stored under the `_attachments` field.

The automatic upgrade functionality *does not* update the internal schema for attachments, so they remain accessible under the `_attachments` field.
See <<android:upgrade:::ex-get-att>> for how to retrieve an attachment that was created in a 1.x database with a 2.x API.

.Retrieve 1.x Attachment
[#ex-get-att]


[#android:upgrade:::ex-get-att]
====

[tabs]
=====


Kotlin::
+
--

// Show Main Snippet
// include::android:example$codesnippet_collection.kt[tags="1x-attachment", indent=0]
[source, Kotlin]
----
val content = document.getDictionary("_attachments")?.getBlob("avatar")?.content
----

--
// Show Optional Alternate Snippet
// include::android:example$codesnippet_collection.java[tags="1x-attachment", indent=0]

Java::
+
--
[source, Java]
----
Dictionary attachments = document.getDictionary("_attachments");
Blob blob = attachments != null ? attachments.getBlob("avatar") : null;
byte[] content = blob != null ? blob.getContent() : null;
----
--

=====


====


[#android:upgrade:::replication-compatibility]
=== Replication Compatibility

The current replication protocol is not backwards compatible with the 1.x replication protocol.
Therefore, to use replication with Couchbase Lite 2.x, the target Sync Gateway instance must also be upgraded to 2.x.

Sync Gateway 2.x will continue to accept clients that connect through the 1.x protocol.
It will automatically use the 1.x replication protocol when a Couchbase Lite 1.x client connects through \http://localhost:4984/db and the 2.0 replication protocol when a Couchbase Lite 2.0 client connects through ws://localhost:4984/db.
This allows for a smoother transition to get all your user base onto a version of your application built with Couchbase Lite 2.x.


[#android:upgrade:::visual-studio]
== Visual Studio

The public facing API has completely changed in Couchbase Lite 2.0 and will require a re-write to upgrade an application that is using Couchbase Lite 1.x.
To update an Xcode project built with Couchbase Lite 1.x:

* Remove the existing Couchbase Lite nuget package from the Visual Studio project.
* Remove all the Couchbase Lite 1.x dependencies -- see the  https://docs-archive.couchbase.com/couchbase-lite/1.4/csharp.html#getting-started[1.x installation guide].
* Install the Couchbase Lite 2.0 framework in your project  -- see xref:android:gs-install.adoc[Install].
At this point, there will be many compiler warnings.
Refer to the examples on this page to learn about the new API.
* Build & run your application.
endif::csharp[]
ifdef::is-android[]
= Android Studio


The API changed in Couchbase Lite 2.0 and you will need to port any application that is using Couchbase Lite 1.x API to the latest Couchbase Lite API.
To update an Android project built with Couchbase Lite 1.x:

* Remove the existing Couchbase Lite dependency from the Android Studio project.
* Install the Couchbase Lite framework in your project -- see the https://docs-archive.couchbase.com/couchbase-lite/1.4/java.html#getting-started[Getting Started].
At this point, there will be many compiler warnings.
Refer to the examples on this page to learn about the new API.
* Build & run your application.

endif::is-android[]

include::ROOT:partial$block-related-content-std.adoc[]


= Troubleshooting

