
= Upgrade
:page-aliases: advance/java-android-dep-upgrade.adoc, dep-upgrade.adoc
:page-role:


:source-language: Java


:source-language: Kotlin


// The admonition does not apply to C as it references upgrading from versions 2.x.
// CBL-C started at version 3.0
[IMPORTANT]
--
On upgrading from a 2.x release, all Couchbase Lite databases will be automatically re-indexed on initial database open. +
This can result in a delay before the database is usable.
--

[#3-2-1-upgrade]
== {major}.{minor}.{base}{empty} Upgrade

The action will take place automatically and can lead to some delay in the database becoming available for use in your application.

In addition, if you are syncing with a {major}.{minor}.{base}{empty} Sync Gateway, you should be aware of the significant configuration enhancements introduced and their impact.
See xref:sync-gateway::upgrading.adoc[Upgrading Sync Gateway] for more details.
This is a one-way conversion.

// All API and other listed changes included in the other platforms do not apply to CBL-C for the following reasons
// The changes apply to pre 3.x versions (CBL-C started at 3.0)
// Or they relate to Querybuilder functionality - CBL-C doesn't have Querybuilder.
[#api-changes]
=== API Changes


This content introduces the changes made to the pass:q,a[Couchbase{nbsp}Lite] for Android API for release {major}.{minor}.{base}{empty}.


[#removed]
==== Removed


[#resetcheckpoint]
===== ResetCheckpoint

The method https://docs.couchbase.com/mobile/2.8.0/couchbase-lite-android/com/couchbase/lite/AbstractReplicator.html#resetCheckpoint--[Replicator.resetCheckpoint()] has been removed. +
Instead, use https://docs.couchbase.com/mobile/{major}.{minor}.{base}{empty}/couchbase-lite-android/com/couchbase/lite/AbstractReplicator.html#start-boolean-[Replicator.resetCheckpoint(boolean reset)].

.Before
[source, java]
----
replicator.resetCheckpoint()
replicator.start()
----

.After
[pass:q,a[source, java, subs="attributes+, macros+"]]
----
replicator.start(true)
----

[#database-setloglevel]
===== Database.setLogLevel

The method https://docs.couchbase.com/mobile/2.8.0/couchbase-lite-android/com/couchbase/lite/Database.html#setLogLevel-com.couchbase.lite.LogDomain-com.couchbase.lite.LogLevel-[Database.setLogLevel()]
has been removed. +
Instead:

. Set the logging levels for loggers, individually
. Set the domains to be logged by the console logger, explicitly.

.Before
[pass:q,a[source, java, subs="attributes+, macros+"]]
----
Database.setLogLevel(LogDomain.ALL, LogLevel.VERBOSE)

----

.After
[pass:q,a[source, java, subs="attributes+, macros+"]]
----
Database.log.getConsole().setDomains(LogDomain.ALL_DOMAINS)
Database.log.getConsole().setLevel(LogLevel.VERBOSE)
Database.log.getFile().setDomains(LogLevel.DEBUG)
----

[#database-compact]
===== Database.compact
The https://docs.couchbase.com/mobile/2.8.0/couchbase-lite-android/com/couchbase/lite/Database.html#compact--[Database.compact()] method has been removed. +
It is replaced by the new https://docs.couchbase.com/mobile/{major}.{minor}.{base}{empty}/couchbase-lite-android/com/couchbase/lite/Database.html#performMaintenance-com.couchbase.lite.MaintenanceType-[Database.performMaintenance(MaintenanceType)] method, and the maintenance operations represented in the enum https://docs.couchbase.com/mobile/{major}.{minor}.{base}{empty}/couchbase-lite-android/com/couchbase/lite/MaintenanceType.html[MaintenanceType]

.Before
[pass:q,a[source, java, subs="attributes+, macros+"]]
----
try testdb.compact()

----

.After
[pass:q,a[source, java, subs="attributes+, macros+"]]
----
testdb.performMaintenance(MaintenanceType.COMPACT)
----


[#deprecated-in-the-api]
==== Deprecated in the API


[#match]
===== MATCH
The class, https://docs.couchbase.com/mobile/2.8.0/couchbase-lite-android/com/couchbase/lite/FullTextExpression.html[FullTextExpression]
has been deprecated. +
Use https://docs.couchbase.com/mobile/{major}.{minor}.{base}{empty}/couchbase-lite-android/com/couchbase/lite/FullTextFunction.html[FullTextFunction] instead.

.Before
[pass:q,a[source, java, subs="attributes+, macros+"]]
----
FullTextExpression index = FullTextExpression.index("indexName")
Query q = QueryBuilder.select([SelectResult.expression(Meta.id)])
  .from(DataSource.database(testdb))
  .where(index.match(queryString))

----

.After
[pass:q,a[source, java, subs="attributes+, macros+"]]
----
Query q = QueryBuilder.select([SelectResult.expression(Meta.id)])
  .from(DataSource.database(testdb))
  .where(FullTextFunction.match("indexName", queryString))

----

[#isnullormissingnotnullormissing]
===== isNullOrMissing/notNullOrMissing

The functions https://docs.couchbase.com/mobile/2.8.0/couchbase-lite-android/com/couchbase/lite/Expression.html#isNullOrMissing--[Expression.isNullOrMissing] and https://docs.couchbase.com/mobile/2.8.0/couchbase-lite-android/com/couchbase/lite/Expression.html#notNullOrMissing--[Expression.notNullOrMissing] have been deprecated. +
Use `isNotValued()` and-or `isValued()` instead.

.Before
[pass:q,a[source, java, subs="attributes+, macros+"]]
----
Query q =
  QueryBuilder
    .select([SelectResult.expression(Meta.id)])
    .from(DataSource.database(testdb))
    .where(
      Expression.property("missingProp").isNullOrMissing())

Query q =
  QueryBuilder
    .select([SelectResult.expression(Meta.id)])
    .from(DataSource.database(testdb))
    .where(Expression.property("notMissingProp").notNullOrMissing())

----
.After
[pass:q,a[source, java, subs="attributes+, macros+"]]
----
Query q = QueryBuilder.select([SelectResult.expression(Meta.id)])
  .from(DataSource.database(testdb))
  .where(Expression.property("missingProp").isNotValued())

Query q = QueryBuilder.select([SelectResult.expression(Meta.id)])
  .from(DataSource.database(testdb))
  .where(Expression.property("notMissingProp").isValued())

----

[#abstractreplicatorconfiguration]
===== AbstractReplicatorConfiguration

The enum https://docs.couchbase.com/mobile/2.8.0/couchbase-lite-android/com/couchbase/lite/ReplicatorConfiguration.html#setReplicatorType-com.couchbase.lite.AbstractReplicatorConfiguration.ReplicatorType-[AbstractReplicatorConfiguration.ReplicatorType]
and the methods
https://docs.couchbase.com/mobile/2.8.0/couchbase-lite-android/com/couchbase/lite/ReplicatorConfiguration.html#setReplicatorType--[
ReplicatorConfiguration.setReplicatorType]
and
https://docs.couchbase.com/mobile/2.8.0/couchbase-lite-android/com/couchbase/lite/ReplicatorConfiguration.html#getReplicatorType--[
ReplicatorConfiguration.getReplicatorType]
have all been deprecated. +
Instead, use the methods `ReplicatorConfiguration.setType` and `ReplicatorConfiguration.getType`, and the top level enum `ReplicatorType`.

.Before
[pass:q,a[source, java, subs="attributes+, macros+"]]
----
ReplicatorConfiguration config =
  new ReplicatorConfiguration().setReplicatorType(ReplicatorConfiguration.ReplicatorType.PUSH_AND_PULL);
----
.After
[pass:q,a[source, java, subs="attributes+, macros+"]]
----
ReplicatorConfiguration config =
  new ReplicatorConfiguration().setType(ReplicatorType.PUSH_AND_PULL);
----


[#moved-in-the-api]
==== Moved in the API


The enum https://docs.couchbase.com/mobile/2.8.0/couchbase-lite-android/com/couchbase/lite/AbstractReplicator.ActivityLevel.html[AbstractReplicator.ActivityLevel] and the classes https://docs.couchbase.com/mobile/2.8.0/couchbase-lite-android/com/couchbase/lite/AbstractReplicator.Progress.html[AbstractReplicator.Progress] and https://docs.couchbase.com/mobile/2.8.0/couchbase-lite-android/com/couchbase/lite/AbstractReplicator.Status.html[AbstractReplicator.Status] have all been moved to be top level definitions. +
They are replaced by these definitions:

* https://docs.couchbase.com/mobile/{major}.{minor}.{base}{empty}/couchbase-lite-android/com/couchbase/lite/ReplicatorActivityLevel.html[ReplicatorActivityLevel]
* https://docs.couchbase.com/mobile/{major}.{minor}.{base}{empty}/couchbase-lite-android/com/couchbase/lite/ReplicatorProgress.html[ReplicatorProgress]
* https://docs.couchbase.com/mobile/{major}.{minor}.{base}{empty}/couchbase-lite-android/com/couchbase/lite/ReplicatorStatus.html[ReplicatorStatus]


.Before
[pass:q,a[source, java, subs="attributes+, macros+"]]
----
ListenerToken token =
  replicator.addChangeListener(
    testSerialExecutor,
    change -> {
      final AbstractReplicator.Status status = change.getStatus()
      if (status.getActivityLevel() == AbstractReplicator.ActivityLevel.BUSY)
      { AbstractReplicator.Progress progress =
          status.getProgress(); Logger.log("Progress: " + progress.completed + "/" progress.total);
      }
    });

----
.After
[pass:q,a[source, java, subs="attributes+, macros+"]]
----
ListenerToken token =
  replicator.addChangeListener(
    testSerialExecutor,
    change -> {
      final ReplicatorStatus status = change.getStatus()
      if (status.getActivityLevel() == ReplicatorActivityLevel.BUSY)
      { ReplicatorProgress progress =
          status.getProgress(); Logger.log("Progress: " + progress.completed + "/" progress.total);
      }
    });

----


[#lbl-db-upgrades]
== 1.x Databases Upgrades to 2.x

Databases created using Couchbase Lite 1.2 or later can still be used with Couchbase Lite 2.x; but will be automatically updated to the  current 2.x version.
This feature is only available for the default storage type (i.e., not a ForestDB database).

[#encrypted-databases]
=== Encrypted Databases
The automatic migration feature does not support encrypted databases.
So if the 1.x database is encrypted you will first need to disable encryption using the Couchbase Lite 1.x API (see the https://docs-archive.couchbase.com/couchbase-lite/1.4/Kotlin.html#database-encryption[1.x Database Guide]).

Thus, to upgrade an encrypted 1.x database, you should do the following:

.Upgrading Encrypted Databases
****
. Disable encryption using the Couchbase Lite 1.x framework (see https://docs-archive.couchbase.com/couchbase-lite/1.4/android.html#database-encryption[1.x encryption guide])
. Open the database file with encryption enabled using the Couchbase Lite 2.x framework.
****

Since it is not possible to package Couchbase Lite 1.x and Couchbase Lite 2.x in the same application this upgrade path would require two successive upgrades.

If you are using Sync Gateway to synchronize the database content, it may be preferable to run a pull replication from a new 2.x database with encryption enabled and delete the 1.x local database.


[#handling-of-existing-conflicts]
=== Handling of Existing Conflicts

If there are existing conflicts in the 1.x database, the automatic upgrade process copies the default winning revision to the new database and does NOT copy any conflicting revisions.

This functionality is related to the way conflicts are now being handled in Couchbase Lite -- see xref:android:conflict.adoc[Handling Data Conflicts].

Optionally, existing conflicts in the 1.x database can be resolved with the https://docs-archive.couchbase.com/couchbase-lite/1.4/Kotlin.html#resolving-conflicts[1.x API] prior to the database being upgraded.

[#handling-of-existing-attachments]
=== Handling of Existing Attachments

Attachments persisted in a 1.x database are copied to the new database.
NOTE: The relevant Couchbase Lite API is now called the `Blob` API not the `Attachments` API.

The functionally is identical but the internal schema for attachments has changed.

Blobs are stored anywhere in the document, just like other value types.
Whereas in 1.x they were stored under the `_attachments` field.

The automatic upgrade functionality *does not* update the internal schema for attachments, so they remain accessible under the `_attachments` field.
See xref:android:upgrade.adoc#ex-get-att[] for how to retrieve an attachment that was created in a 1.x database with a 2.x API.

.Retrieve 1.x Attachment
[#ex-get-att]


[#ex-get-att]
====

[tabs]
=====


Kotlin::
+
--

[source, Kotlin]
----
include::android:example$codesnippet_collection.kt[tags="1x-attachment", indent=0]
----

--

Java::
+
--
[source, Java]
----
include::android:example$codesnippet_collection.java[tags="1x-attachment", indent=0]
----
--

=====


====


[#replication-compatibility]
=== Replication Compatibility

The current replication protocol is not backwards compatible with the 1.x replication protocol.
Therefore, to use replication with Couchbase Lite 2.x, the target Sync Gateway instance must also be upgraded to 2.x.

Sync Gateway 2.x will continue to accept clients that connect through the 1.x protocol.

It will automatically use the 1.x replication protocol when a Couchbase Lite 1.x client connects through \http://localhost:4984/db and the 2.0 replication protocol when a Couchbase Lite 2.0 client connects through ws://localhost:4984/db.

This allows for a smoother transition to get all your user base onto a version of your application built with Couchbase Lite 2.x.


[#android-studio]
== Android Studio


The API changed in Couchbase Lite 2.0 and you will need to port any application that is using Couchbase Lite 1.x API to the latest Couchbase Lite API.
To update an Android project built with Couchbase Lite 1.x:

* Remove the existing Couchbase Lite dependency from the Android Studio project.
* Install the Couchbase Lite framework in your project -- see the https://docs-archive.couchbase.com/couchbase-lite/1.4/java.html#getting-started[Getting Started].
At this point, there will be many compiler warnings.
Refer to the examples on this page to learn about the new API.
* Build & run your application.


[#downgrading-couchbase-lite]
== Downgrading Couchbase Lite

[#downgrading-between-major-releases]
=== Downgrading Between Major Releases

*No Downgrade Support* - Downgrades between major versions of Couchbase Lite (CBL) are not supported.
Once you upgrade to a new major version, downgrading to a previous major version may lead to incompatibility issues.

For example, Upgrading from CBL 2.x.x to CBL 3.x.x does not guarantee the ability to revert to CBL 2.x.x.

[#downgrading-between-minor-releases]
=== Downgrading Between Minor Releases

*Conditional Downgrade Support* - Downgrade support for minor releases is considered on a case-by-case basis.
The release notes for each minor version will clarify whether downgrades are supported.

For example, if a new minor version such as CBL 3.1.0 is released the release notes will specify whether downgrading to CBL 3.0.x is supported.

[#downgrading-between-patch-releases]
=== Downgrading Between Patch Releases

*Full Downgrade Support* - Downgrades between patch releases are supported.
Users can safely downgrade between different patch versions within the same minor release.

For example, if you're running CBL 3.1.6 you can downgrade to CBL 3.1.4 or CBL 3.1.3 without issues.


// Include standard footer


[#related-content]
== Related Content
++++
<div class="card-row three-column-row">
++++

[.column]
=== {empty}
.How to . . .
* xref:android:gs-prereqs.adoc[Prerequisites]
* xref:android:gs-install.adoc[Install]
* xref:android:gs-build.adoc[Build and Run]


.

[.column]
=== {empty}
.Learn more . . .
* xref:android:database.adoc[Databases]
* xref:android:document.adoc[Documents]
* xref:android:blob.adoc[Blobs]
* xref:android:replication.adoc[Remote Sync Gateway]
* xref:android:conflict.adoc[Handling Data Conflicts]

.


[.column]
=== {empty}
.Dive Deeper . . .
https://forums.couchbase.com/c/mobile/14[Mobile Forum] |
https://blog.couchbase.com/[Blog] |
https://docs.couchbase.com/tutorials/[Tutorials]

.


++++
</div>
++++


= Troubleshooting

