name: ObjC

on:
  workflow_dispatch: 

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: "Build - ObjC"
      env:
          SCHEME: ${{ "code-snippets" }}
          platform: ${{ 'iOS Simulator' }}
      run: |
          device=`xcrun xctrace list devices 2>&1 | grep -oE 'iPhone.*?[^\(]+' | head -1 | awk '{$1=$1;print}'`
          xcodebuild build-for-testing -scheme "${SCHEME}" -project modules/objc/examples/code_snippets.xcodeproj  -destination "platform=$platform,name=$device"

